### ISSUE TITLE
[Entry] General: Virtual reality

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1010]
### Reason/inspiration (optional)

Currently there is an entry for AR: https://www.codecademy.com/resources/docs/general/augmented-reality

There's a section that mentions AR vs VR but it would be beneficial to create a separate VR entry. Edits to the AR entry may also be needed.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by ishaanbedi** [comment]
Hi! 
I'd like to work on this!
Can you please assign it to me?

**Comment by yesimhozman** [comment]
I want to work on that. Can you assign it to me?

**Comment by Dusch4593** [comment]
@yesimhozman You are assigned and thank you for your interest in contributing to Codecademy Docs for Hacktoberfest! 😄 🚀

**Comment by yesimhozman** [comment]
hello, I hope you are doing great @Dusch4593 . Are we going to add description and vr examples for VR ?  Do you have it? I need it to create Vr section actually.

**Comment by Dusch4593** [comment]
Hi @yesimhozman! Yes, we should add a description of VR near the top of the file. And we should have an "Examples" section, too. But are we taking about examples of how VR is used or what tools used to build VR experiences?

One tool that comes to mind is a framework called A-Frame (Codecademy actually has a [course](https://www.codecademy.com/learn/learn-a-frame) on this). [This Codecademy article](https://www.codecademy.com/article/a-frame-what-is-virtual-reality) also has info about VR headsets, browsers, and the WebXR API, which covers both VR and AR.

Hope this answer helps but do let me know if I'm missing anything. 😄

**Comment by Dusch4593** [comment]
@yesimhozman I think it would be worthwhile to have this information in both entries. 😄

**Comment by yesimhozman** [comment]
> @yesimhozman I think it would be worthwhile to have this information in both entries. 😄 

Yes, I think so. 👍🏻🥳
