### ISSUE TITLE
[Edit] General: Object

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1021]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

The general concept, [object](https://www.codecademy.com/resources/docs/general/object), need some TLC! The intro paragraph is not the most accurate and some additional info on objects is missing.

In addition, we should update the links that bring us to the different language's object entries. Any further improvements to this entry are welcome.

If you'd like to take this issue, feel free to tag someone on the CFT and we'll assign it to you! Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Dusch4593** [comment]
@Nessvah assigned!

**Comment by igoche7v** [comment]
Hi, I will like to contribute to this.

**Comment by Dusch4593** [comment]
Hi @igoche7v! This one has already assigned. However, we have more open issues on our "Issues" tab. Comment on one and we'll assign you. 😊
