### ISSUE TITLE
[Term Entry] HTML Elements: `<style>`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1026]
### Reason/inspiration (optional)

We would like a new HTML Elements term entry about the `<style>` element. Please include "Syntax" and "Example" sections along with any other necessary subsections that are brief but deeply informative.

To get started with the PR and new entry:

1. Create a new folder called `style` under `content/html/concepts/elements/terms/`.
2. Then create a new file called `style.md` inside of the new `content/html/concepts/elements/terms/style/` directory.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by SaumyaBhushan** [comment]
Hi @Dusch4593 I would like to work on this . Please assign it to me .

**Comment by Dusch4593** [comment]
@SaumyaBhushan You got it! Assigned! 😎

**Comment by xMan-Model11** [comment]
I would like to work on this.  If the option is available can I have this re-assigned to me... I am also open to any other suggestions.

**Comment by Dusch4593** [comment]
Hey @xMan-Model11 since this issue is already assigned, and a PR has already been opened for it, we won't be able to assign this particular issue to you. _But_, there are plenty of [open issues yet to be assigned](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee) that you should definitely check out! 😄
