### ISSUE TITLE
[Term Entry] JavaScript Strings: toString()

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1027]
### Reason/inspiration (optional)

Please write a new term entry under `content/javascript/concepts/strings/terms/` about the `.toString()` method of the `String` object in JavaScript. Let's include the following sections:

- A "Syntax" section with \```pseudo code snippet.
- An "Example" section with a \```js code snippet.

Bonus: If you're feeling extra adventurous, let's write an additional example in a "Codebyte Example" section that features a \```codebyte/javascript snippet.

To get started with the PR and entry file:

1. Under `content/javascript/concepts/strings/terms/`, create a new folder called `to-string`.
2. Then create a new file called `to-string.md` under `content/javascript/concepts/strings/terms/to-string/`.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by PriyanshuAhlawat** [comment]
I will like to work on it, please assign to me

**Comment by Dusch4593** [comment]
@PriyanshuAhlawat You got it! Assigned. Let us know if you have any questions with getting started or anything. 😄

**Comment by PriyanshuAhlawat** [comment]
@Dusch4593 Thanks, I will let you know if there are doubts🙂

**Comment by PriyanshuAhlawat** [comment]
@Dusch4593 pls check pr, some review issue seems to be there

**Comment by vicontiveros00** [comment]
Noticed this is still open after a while, could I also contribute?

**Comment by Dusch4593** [comment]
Hey @vicontiveros00! I'm actually conducting a review for this PR right now. We like to keep each issue assigned to just one contributor but feel free to check out [these open issues](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee) to see if any are of interest! 🚀
