### ISSUE TITLE
[Entry] CSS: Pseudo-classes

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1028]
### Reason/inspiration (optional)

Please write a new CSS concept entry about pseudo-classes under `content/css/concepts/`. Let's make sure to include the following:

- A clear definition of what pseudo-classes are and what they do (2-5 sentences).
- A "Syntax" section with a \```pseudo code snippet.
- An "Example" section with \```css snippet.

To get started with the PR and with writing the entry file:

1. Under `content/css/concepts/`, create a new folder called `pseudo-classes`.
2. Create a new file called `pseudo-classes.md` under `content/css/concepts/pseudo-classes/`.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Shivashish-rwt** [comment]
I can do that. Can u please assign this to me??

**Comment by Dusch4593** [comment]
@Shivashish-rwt Of course. You are assigned and thank you so much for being interested in contributing to Codecademy Docs! 😄

**Comment by SSwiniarski** [comment]
@Shivashish-rwt I wanted to check on your progress on this issue. Respond in this thread if you're still working on this or if you need any assistance. Reminder, we only have two days left for credit in hacktoberfest.

**Comment by Calvinadeyemi** [comment]
Hi, i can work on this if and when available. Thanks

**Comment by SSwiniarski** [comment]
@Calvinadeyemi, we're going to give @Shivashish-rwt some time to respond to see if they're still working on this. Check back in a week or so.

**Comment by SSwiniarski** [comment]
@Shivashish-rwt because of several weeks of inactivity I'm unassigning you and assigning @Calvinadeyemi .

@Calvinadeyemi, you're assigned.

**Comment by SSwiniarski** [comment]
@Calvinadeyemi, it's been two weeks since you were assigned. Are you working on this PR? Do you need any assistance?

**Comment by SSwiniarski** [comment]
@Calvinadeyemi, because of over two weeks of inactivity, I am unassigning you so someone else can work on this issue.

**Comment by carocoda** [comment]
Hi! In that case, I'd like to work on this issue if as part of my Intro to Git/Github portfolio project if possible. :)

**Comment by SSwiniarski** [comment]
@carocoda, You're assigned!

**Comment by carocoda** [comment]
Great! I've added the pull request.
