### ISSUE TITLE
[Entry] R: Vectors

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1045]
### Reason/inspiration (optional)

We would like a new concept entry about vectors in the [R programming language](https://www.codecademy.com/resources/docs/r). Please include the following information:

- A "Syntax" section with a \```pseudo code snippet that describes the common structure(s) of vectors.
- A section about accessing and updating elements in a vector (with example \```r snippet).
- A section about elements are recycled when two vectors of different lengths are operated on (with example \```r snippet).

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by monieshravichandrran** [comment]
Hey hi! I can do that. Can u please assign this to me?

**Comment by Dusch4593** [comment]
@monieshravichandrran Sure thing! You're assigned and thanks for your interest in contributing to Codecademy Docs. 😄

**Comment by Dusch4593** [comment]
@monieshravichandrran Also, I was wondering how you discovered Codecademy Docs and this repository?

**Comment by monieshravichandrran** [comment]
> and this repository?

I was looking forward to contribute to open source and came across this repository from a contribution of my collegemate and came to know more about Codecademy and the repository

**Comment by monieshravichandrran** [comment]
Hi @Dusch4593 I have raised the PR #1049 for the issue have created the documentation of Vectors in R
Can you please review it?
