### ISSUE TITLE
[Edit] General: File Paths

### ISSUE THREAD

**Issue by YanisaHS** [Codecademy/docs#1075]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

The general concept, [file paths](https://www.codecademy.com/resources/docs/general/file-paths), has information on relative file paths, but it doesn't explain or provide an example of an absolute file path.

I suggest that the "Relative File Paths" heading be changed to "Absolute and Relative File Paths". In that section, a new paragraph could be added at the beginning briefly explaining what an absolute file path is with an example. I think this would help frame the relative file paths more clearly, since a lot of people are familiar with absolute file paths.

Also, I think the "URLs and File Paths" section is a bit unclear. I suggest the following changes for that section:
- Remove the temporary/permanent connection
- Link to the [URL](https://www.codecademy.com/resources/docs/general/url) page
- Re-write that section to clarify the differences between a URL and local file path

If this is something you want to move forward with, feel free to assign it to me and I'll submit a PR! Thanks!

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by rojitaLuwang** [comment]
Can I work on this, please

**Comment by SSwiniarski** [comment]
@rojitaLuwang, this issue has already been assigned to @YanisaHS. There are plenty of other unassigned issues you could work on.

**Comment by rojitaLuwang** [comment]
Thank you. Sorry, I thought it was not taken. Will look for other
unassigned issues.
