### ISSUE TITLE
[Term Entry] SwiftUI Views: Circle

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1092]
### Reason/inspiration (optional)

Please write a new entry under:
content/swiftui/concepts/views/terms/ about the Circle view in SwiftUI.

A "Syntax" section with pseudo code snippet.
An "Example" section with a swift code snippet and an accompanying image to display the view.

To get started with the PR and entry file:

Under content/swiftui/concepts/views/terms/, create a new folder called circle.
Then create a new file called circle.md under content/swiftui/concepts/views/terms/circle

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by girijakar** [comment]
Hi, please assign me this issue. 
Thank you

**Comment by Dusch4593** [comment]
@girijakar There we are 😎
