### ISSUE TITLE
[Term Entry] SwiftUI Views: Image

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1093]
### Reason/inspiration (optional)

Please write a new entry under:
content/swiftui/concepts/views/terms/ about the Image view in SwiftUI.

A "Syntax" section with pseudo code snippet.
An "Example" section with a swift code snippet and an accompanying image to display the view.

To get started with the PR and entry file:

Under content/swiftui/concepts/views/terms/, create a new folder called image.
Then create a new file called image.md under content/swiftui/concepts/views/terms/image

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by JonnySimmons** [comment]
I'd like to take this issue @yangc95

**Comment by yangc95** [comment]
@JonnySimmons thanks for being so speedy!

Also if you can take a minute, how did you find out about contributing to Docs?

**Comment by yangc95** [comment]
@JonnySimmons congrats on the merge!
