### ISSUE TITLE
[Term Entry] SwiftUI Views: Label

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1094]
### Reason/inspiration (optional)

Please write a new entry under:
content/swiftui/concepts/views/terms/ about the Label view in SwiftUI.

A "Syntax" section with pseudo code snippet.
An "Example" section with a swift code snippet and an accompanying image to display the view.

To get started with the PR and entry file:

Under content/swiftui/concepts/views/terms/, create a new folder called label.
Then create a new file called label.md under content/swiftui/concepts/views/terms/label

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by cilippofilia** [comment]
Hey! I'd like to get assigned this issue.

**Comment by yangc95** [comment]
@cilippofilia assigned!

**Comment by cilippofilia** [comment]
Yes I am working on it and will submit the first draft soon. Sorry for the delay but I have been busy with other stuff
