### ISSUE TITLE
[Term Entry] SwiftUI Views: Color

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1095]
### Reason/inspiration (optional)

Please write a new entry under:
content/swiftui/concepts/views/terms/ about the Color view in SwiftUI.

A "Syntax" section with pseudo code snippet.
An "Example" section with a swift code snippet and an accompanying image to display the view.

To get started with the PR and entry file:

Under content/swiftui/concepts/views/terms/, create a new folder called color.
Then create a new file called color.md under content/swiftui/concepts/views/terms/color

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by cesarfras** [comment]
Hello, I would like to work on this issue.

**Comment by YKWIBN** [comment]
Hi! 
My name is Raul, and I would like to be assigned this issue, if it is not yet claimed. 
I am currently on the iOS Career Path on Codecademy and learning how to contribute to the GitHub community. 
Thank you!

**Comment by yangc95** [comment]
Apologies for the late reply. @cesarfras are you still wanting to work on this issue?

**Comment by cesarfras** [comment]
Sure, I want to work on it!!

**Comment by yangc95** [comment]
@cesarfras awesome! Assigned to you 🙂

**Comment by SSwiniarski** [comment]
@cesarfras, it's been two weeks since you were assigned this issue. Are you still working on it? Do you need any help?

**Comment by cesarfras** [comment]
Sorry I've been busy on another thing, I'll keep working on it as soon as I can but if you prefer to assign it to someone else I have no problem.

**Comment by yangc95** [comment]
> Sorry I've been busy on another thing, I'll keep working on it as soon as I can but if you prefer to assign it to someone else I have no problem.

@cesarfras it would be great if you could keep us in the loop of when you expect to push out a PR. I don't see a branch opened for this issue yet on your fork, so if you need any assistance, don't hesitate to reach out!

If you'd prefer, we can also proceed with assigning this to another community member.

**Comment by cesarfras** [comment]
Yes, I think I need assistance to continue.

**Comment by SSwiniarski** [comment]
@cesarfras, what assistance do you need?

**Comment by cesarfras** [comment]
Thanks for your reply, making the branch, I lost a little bit the track on that topic.

**Comment by SSwiniarski** [comment]
In the online UI, on the main page for your forked repo, in the upper left above the list of folders, there's a little box that should say "main". This is a dropdown to let you change/create the branch you're working with. You drop it down an there's a text box that says "find or create a branch". You can type in a new name in this box, and below it will be a link "Create branch:" with your branch name.

As for doing it via the command line, I think @Dusch4593 would be better at explaining it.

**Comment by SSwiniarski** [comment]
@cesarfras, are you still working on this PR?

**Comment by flodega** [comment]
Hello, does this issue still need somebody to work on it ?  If so I would love to do so.  I have already forked the repository and cloned it on my local machine.  I also created a new branch on my local machine.  I am just looking for an issue to work on now.  Please let me know.

**Comment by SSwiniarski** [comment]
@cesarfras because of inactivity, I am unassigning you from this PR so others can work on it.

**Comment by flodega** [comment]
@SSwiniarski thanks for assigning this to me

**Comment by flodega** [comment]
@SSwiniarski @yangc95 I have submitted a pull request for this issue

**Comment by flodega** [comment]
@SSwiniarski I have created a new pull request that resolved the CLA issue.  Awaiting a final review now.
