### ISSUE TITLE
[Term Entry] SwiftUI Views: Text

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1097]
### Reason/inspiration (optional)

Please write a new entry under:
content/swiftui/concepts/views/terms/ about the Text view in SwiftUI.

A "Syntax" section with pseudo code snippet.
An "Example" section with a swift code snippet and an accompanying image to display the view.

To get started with the PR and entry file:

Under content/swiftui/concepts/views/terms/, create a new folder called text.
Then create a new file called text.md under content/swiftui/concepts/views/terms/text

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by KarinaNi** [comment]
Can I be assigned this issue?

**Comment by YKWIBN** [comment]
Hi! 
My name is Raul, and I would like to be assigned this issue, if it is not yet claimed. 
I am currently on the iOS Career Path on Codecademy and learning how to contribute to the GitHub community. 
Thank you!

**Comment by yangc95** [comment]
Hi @KarinaNi, thanks for your patience! Did you still wish to work on this entry?

**Comment by KarinaNi** [comment]
/Yes i would love to take this issue! Can I please be assigned?

**Comment by yangc95** [comment]
@YKWIBN This has been assigned on a first-come basis. Check out another "unclaimed" issue and see if you can be assigned there!

**Comment by JWegener** [comment]
How do I filter by unclaimed?

**Comment by yangc95** [comment]
> How do we filter by unclaimed?

> For future questions like these, please post here: https://github.com/Codecademy/docs/discussions

@JWegener
see the other question you asked here: https://github.com/Codecademy/docs/issues/1207#issuecomment-1305814078

When you go to the issues tab, there is an option under the "Assignee" toggle. If you click on "Assigned to nobody," you will be able to "filter by unclaimed."
![Screen Shot 2022-11-07 at 11 31 08 AM](https://user-images.githubusercontent.com/72277593/200363782-61e62a33-ad3f-4723-b40f-deee2e78c7d0.png)

Hope this helps!
