### ISSUE TITLE
[Term Entry] Swift Arrays: `.reduce()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1108]
### Reason/inspiration (optional)

Please write a new entry under:
content/swift/concepts/arrays/terms/ about the Array method .reduce() in Swift.

A "Syntax" section with pseudo code snippet.
An "Example" section with a swift code snippet.

To get started with the PR and entry file:

Under content/swift/concepts/arrays/terms/, create a new folder called reduce.
Then create a new file called reduce.md under content/swift/concepts/arrays/terms/reduce

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Prerna-Bhargava** [comment]
Hey, Please assign me this issue.

**Comment by yangc95** [comment]
@Prerna-Bhargava assigned!
