### ISSUE TITLE
[Term Entry] Swift Sets: `.contains()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1109]
### Reason/inspiration (optional)

Please write a new entry under:
content/swift/concepts/sets/terms/ about the Set method .contains() in Swift.

A "Syntax" section with pseudo code snippet.
An "Example" section with a swift code snippet.

To get started with the PR and entry file:

Under content/swift/concepts/sets/terms/, create a new folder called contains (create a terms folder if not already created).
Then create a new file called contains.md under content/swift/concepts/sets/terms/contains

Include this as a description: "Check whether an item exists within the set."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Minkyeong-Ko** [comment]
Hi can I be assigned to this issue?

**Comment by Dusch4593** [comment]
@Minkyeong-Ko Assigned 😄
