### ISSUE TITLE
[Term Entry] Swift Sets: `.isSuperset()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1111]
### Reason/inspiration (optional)

Please write a new entry under:
content/swift/concepts/sets/terms/ about the Set method .isSuperset() in Swift.

A "Syntax" section with pseudo code snippet.
An "Example" section with a swift code snippet.

To get started with the PR and entry file:

Under content/swift/concepts/sets/terms/, create a new folder called isSuperset (create a terms folder if not already created).
Then create a new file called isSuperset.md under content/swift/concepts/sets/terms/isSuperset

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by MarkLovesCoding** [comment]
If possible, can I please be assigned to this?

**Comment by yangc95** [comment]
Assigned to you @MarkLovesCoding !

**Comment by SSwiniarski** [comment]
@MarkLovesCoding, it's been two weeks since you were assigned this issue. Are you still working on it? Do you need any help?

**Comment by MarkLovesCoding** [comment]
Apologies, I was away. I’ll have this completed today!
