### ISSUE TITLE
[Term Entry] Swift Sets: `.union()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1112]
### Reason/inspiration (optional)

Please write a new entry under:
content/swift/concepts/sets/terms/ about the Set method .union() in Swift.

A "Syntax" section with pseudo code snippet.
An "Example" section with a swift code snippet.

To get started with the PR and entry file:

Under content/swift/concepts/sets/terms/, create a new folder called union(create a terms folder if not already created).
Then create a new file called union.md under content/swift/concepts/sets/terms/union

Include this as a description: "Populates a new set by taking all the values from two sets and combining them."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by hcz** [comment]
I've wrote an article about .union() method here: https://github.com/Codecademy/docs/pull/1117
Feel free to comment
