### ISSUE TITLE
[Term Entry] Swift Sets: `.intersection()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1113]
### Reason/inspiration (optional)

Please write a new entry under:
content/swift/concepts/sets/terms/ about the Set method .intersection() in Swift.

A "Syntax" section with pseudo code snippet.
An "Example" section with a swift code snippet.

To get started with the PR and entry file:

Under content/swift/concepts/sets/terms/, create a new folder called intersection (create a terms folder if not already created).
Then create a new file called intersection.md under content/swift/concepts/sets/terms/intersection

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by hcz** [comment]
I've wrote an article about `.intersection()` method here: #1116
Feel free to comment
