### ISSUE TITLE
[Term Entry] Swift Sets: `.subtracting()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1125]
### Reason/inspiration (optional)

Please write a new entry under:
content/swift/concepts/sets/terms/ about the Set method .subtracting() in Swift.

A "Syntax" section with pseudo code snippet.
An "Example" section with a swift code snippet.

To get started with the PR and entry file:

Under content/swift/concepts/sets/terms/, create a new folder called subtracting (create a terms folder if not already created).
Then create a new file called subtracting.md under content/swift/concepts/sets/terms/subtracting

Suggestion for description: "Removes the values of one second set from another set and stores the remaining values in a new set."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by st3hall** [comment]
I would like to be assigned this issue.

**Comment by yangc95** [comment]
@st3hall assigned!
