### ISSUE TITLE
[Term Entry] Swift Sets: `.symmetricDifference()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1126]
### Reason/inspiration (optional)

Please write a new entry under:
content/swift/concepts/sets/terms/ about the Set method .symmetricDifference() in Swift.

A "Syntax" section with pseudo code snippet.
An "Example" section with a swift code snippet.

To get started with the PR and entry file:

Under content/swift/concepts/sets/terms/, create a new folder called symmetricDifference (create a terms folder if not already created).
Then create a new file called symmetricDifference.md under content/swift/concepts/sets/terms/symmetricDifference

Suggestion for description: "Creates a new set with all the non-overlapping values between two sets."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by KarinaNi** [comment]
Can I take this issue please?

**Comment by yangc95** [comment]
@KarinaNi assigned!

**Comment by KarinaNi** [comment]
Thank you! Means a lot

**Comment by SSwiniarski** [comment]
@KarinaNi, it's been two weeks since you were assigned this issue. Are you still working on it? Do you need any help?

**Comment by KarinaNi** [comment]
I am working on it, sorry for the late reply I am trying to get done within a week.

**Comment by SSwiniarski** [comment]
@KarinaNi I just want to check on your progress with this PR since its been two weeks since we've heard from you.

**Comment by KarinaNi** [comment]
I will make a pull request soon. Sorry for being so late, been a bit sick. But I really really want to do it. Sorry for the delay, again.
