### ISSUE TITLE
[Term Entry] Swift Sets: `.removeAll()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1127]
### Reason/inspiration (optional)

Please write a new entry under:
content/swift/concepts/sets/terms/ about the Set method .removeAll() in Swift.

A "Syntax" section with pseudo code snippet.
An "Example" section with a swift code snippet.

To get started with the PR and entry file:

Under content/swift/concepts/sets/terms/, create a new folder called removeAll (create a terms folder if not already created).
Then create a new file called removeAll.md under content/swift/concepts/sets/terms/removeAll

Suggestion for description: "Remove every single value from a set."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by rriver2** [comment]
hi, Can i assigne this issue?

**Comment by Dusch4593** [comment]
@rriver2 You are assigned 😄 Thanks for your interest in contributing to Codecademy Docs! 🚀

Quick question, how did you happen to learn about contributing to this repo?

**Comment by SSwiniarski** [comment]
@rriver2 I wanted to check on your progress on this issue. Respond in this thread if you're still working on this or if you need any assistance. Reminder, we only have two days left for credit in hacktoberfest.

**Comment by YKWIBN** [comment]
Hi!
My name is Raul, and I would like to be assigned this issue, if it is not resolved by the previous assignee.
I am currently on the iOS Career Path on Codecademy and learning how to contribute to the GitHub community.
Thank you!

**Comment by SSwiniarski** [comment]
@rriver2, because of inactivity, I am unassigning you from this issue so other people can work on it.

@YKWIBN, are you still interested in taking this issue?

**Comment by YKWIBN** [comment]
Yes! I would prefer this assignment over the one I have already been assigned to. 
Is there a way I can be assigned to this one and for me to leave issue # 949 for another student or developer to tackle?

**Comment by Dusch4593** [comment]
> Yes! I would prefer this assignment over the one I have already been assigned to. Is there a way I can be assigned to this one and for me to leave issue #949 for another student or developer to tackle?

Hey @YKWIBN 👋🏻 I went ahead and assigned you to this issue and un-assigned you from #949, per your request. 😄

**Comment by YKWIBN** [comment]
Ah! You rock!
On it!

**Comment by SSwiniarski** [comment]
@YKWIBN, it's been two weeks since there's been activity on this issue. Are you still working on this PR? Do you need any assistance?

**Comment by YKWIBN** [comment]
I have it pretty much ready to go, except for the sample code, which I wanted to make in Xcode. The hold up has been that I ran into an issue. The “Expressions not allowed on top level” error appeared. I had not seen it before so I had to figure out how to solve it. I would love some assistance here. 
Coding has been rather tough for me in respect to understanding the logic behind it. If you could point me to resources that explain the logic behind this error, so I don't bump into it again, it would be greatly appreciated!

**Comment by YKWIBN** [comment]
Only today did I learn about Playgrounds. Thank you for the input! I should have this ready to go tomorrow.

**Comment by DavidJC9** [comment]
> ### Reason/inspiration (optional)
> Please write a new entry under: content/swift/concepts/sets/terms/ about the Set method .removeAll() in Swift.
> 
> A "Syntax" section with pseudo code snippet. An "Example" section with a swift code snippet.
> 
> To get started with the PR and entry file:
> 
> Under content/swift/concepts/sets/terms/, create a new folder called removeAll (create a terms folder if not already created). Then create a new file called removeAll.md under content/swift/concepts/sets/terms/removeAll
> 
> Suggestion for description: "Remove every single value from a set."
> 
> ### Entry Type (select all that apply)
> New Term for Existing Concept Entry
> 
> ### Code of Conduct
> * [x]  By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).
> 
> ### For Maintainers
> * [x]  Labels added
> * [x]  Issue is assigned

Hi, my name is David, and I would like to be assigned this issue, I am currently on the iOS Career Path on Codecademy
Thank you!

**Comment by DavidJC9** [comment]
Hi, my name is David, and I would like to be assigned this issue, I am currently on the iOS Career Path on Codecademy
Thank you!

**Comment by SSwiniarski** [comment]
@DavidJC9 this issue already has a PR associated with it. Please see if you can find another issue.
