### ISSUE TITLE
[Edit] JavaScript: Data Types

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1164]
### Type of Edit (select all that apply)

Clarify unclear content and/or terms

### Description (optional)

Asking for some edits to be made to the existing [JavaScript: Data Types](https://www.codecademy.com/resources/docs/javascript/data-types) entry in the `javascript/concepts/data-types/data-types.md` file. Looking for the following edits:

- On line # 17, **bold** the first instance of "Data types".
- Add a new lv. 2 header above the markdown table, entitled `## Primitive Data Types`.
- Move the first sentence of # 30 to above the markdown table (but under the new header).
- We should make the following changes to the markdown table:
  - Rename "Data Type" column to `"Wrapper Object"`.
  - Add a new column and name it as `"Data Type"`.
  - Link to the existing [Number Methods entry](https://www.codecademy.com/resources/docs/javascript/number-methods) to `Number` in the appropriate row.
  - Link to the existing [Strings entry](https://www.codecademy.com/resources/docs/javascript/strings) to `String` in the appropriate row.
  - Remove the row about the `Object` (this information should be in its own header + section).
  - On line # 30, place the remaining text under a new lv. 2 header called `## Objects`.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by siddharth595** [comment]
@Dusch4593 
 Can you please assign this to me?

**Comment by Dusch4593** [comment]
@siddharth595 Assigned! 😄

**Comment by siddharth595** [comment]
![image](https://user-images.githubusercontent.com/51822297/197601184-0293ccc3-9959-44aa-a105-4d68f3d2d201.png)
Can you please explain a little bit in detail about the two requirements

**Comment by siddharth595** [comment]
![image](https://user-images.githubusercontent.com/51822297/197601547-b8a92427-8dbc-4ac3-856d-49164ae5d24a.png)
Here the respective readme pages should be linked right?

**Comment by Dusch4593** [comment]
> ![image](https://user-images.githubusercontent.com/51822297/197601547-b8a92427-8dbc-4ac3-856d-49164ae5d24a.png) Here the respective readme pages should be linked right?

Yes, that's right. 😄

**Comment by Dusch4593** [comment]
> ![image](https://user-images.githubusercontent.com/51822297/197601184-0293ccc3-9959-44aa-a105-4d68f3d2d201.png) Can you please explain a little bit in detail about the two requirements

The current markdown table needs to be revised to include information about each _primitive_ data type (which is immutable and expressed as lowercase &mdash; i.e., `string`) in addition to the existing information about their corresponding _wrapper object_ (i.e. `String`). It should look something like this:

| Data Type | Wrapper Object | Description |
| --- | --- | --- |
| `number` | `Number` | Any number, including numbers with decimals: 1, -2, 99, 3.14. |
| `bigint` | `BigInt` | Any number, greater than 2^53-1 or less than -(2^53-1) with n appended to the number: 1234567890123456n. |
| `string` | `String` | Any grouping of characters on your keyboard (letters, numbers, spaces, symbols, etc.) surrounded by single quotes '' or double quotes "". |

**Comment by siddharth595** [comment]
@Dusch4593 I have created the PR. Please suggest any changes that has to be made

**Comment by PRO-BROS** [comment]
I also faced a similar issue on my [site](https://prhocoding.com/) but thankfully I hire a developer which resolve that's issue.
