### ISSUE TITLE
[Term Entry] Python Built-in Functions: `iter()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1167]
### Reason/inspiration (optional)

We'd like someone to write a new term entry about the built-in `iter()` function in Python. Be sure to include the following information:

- A "Syntax" section with a \```pseudo code block.
- An "Example" section with a \```py code block.
- A "Codebyte Example" section with a \```codebyte/python block.

A nice-to-have:

- Link out to the [existing entry](https://www.codecademy.com/resources/docs/python/iterators) about Iterators in Python.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by mcuocolo** [comment]
Hello Dusch,
I would like to be assigned the iter() documentation.
I'm quite knew to Markdown but I have some knowledge about python.
Though not quite with iter ... so I have 2 good reasons to work on that.
I'll gladly take another python assignement if this one is taken.
Thanks in advance for your answer
Best regards

**Comment by Dusch4593** [comment]
@mcuocolo Nope this one is open to be assigned to you! Thanks for your interest in contributing to Codecademy Docs!

I was curious, how did you happen to learn about Docs and about contributing to it?

**Comment by mcuocolo** [comment]
It's part of the excellent course about git/github : Learn Git & GitHub

Thanks. I'll do my best to submit a PR in the next few days ;-)
