### ISSUE TITLE
[Term Entry] Python Built-in Functions: `next()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1168]
### Reason/inspiration (optional)

We'd like someone to write a new term entry about the built-in `next()` function in Python. Be sure to include the following information:

- A "Syntax" section with a \```pseudo code block.
- An "Example" section with a \```py code block.
- A "Codebyte Example" section with a \```codebyte/python block.

A nice-to-have:

- Link out to the [existing entry](https://www.codecademy.com/resources/docs/python/iterators) about Iterators in Python.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by alextolon** [comment]
Hello,
As I'm enrolled in Codecademy Git/Github course, I have to choose a task and I think this one could be good for me. 
Waiting for your assignment if it is possible.
Thanks.

**Comment by Dusch4593** [comment]
Hi @alextolon! Sure thing, you're assigned. 😄

Thank you for your interest in contributing to Codecademy Docs! 🚀
