### ISSUE TITLE
[Concept Entry] SwiftUI: ViewModifier

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1207]
### Reason/inspiration (optional)

Please write a new entry under:
content/swiftui/concepts/ about `ViewModifier` in SwiftUI. This is going to push out a ton of term entry issues upon merge.

A "Syntax" section with pseudo code snippet.
An "Example" section with a swift code snippet.

To get started with the PR and entry file:

Under content/swiftui/concepts/, create a new folder called viewmodifier.
Then create a new file called viewmodifiers.md under content/swiftui/concepts/viewmodifiers/

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by sammts** [comment]
Hi, my name is Samuel, I would like to work on this problem

**Comment by AustinWheel** [comment]
Hi, my name is Austin, I would like to also work on this problem if possible?

**Comment by YKWIBN** [comment]
Good luck to you all! 
I would also like to add my name to the list 😄.
I am currently on the iOS Career Path on Codecademy, and learning how to contribute to the GitHub community.
Thank you!

**Comment by yangc95** [comment]
@sammts assigned on a first-come basis!

**Comment by yangc95** [comment]
Apologies @sammts, normally these issues are assigned on a first-come basis.

@AustinWheel thank you for being so quick with creating an entry on this topic. However, for future contributions or interest in an issue, make sure that you are assigned first before creating a PR.

We want to keep Docs as collaborative and inviting as possible -- these procedures in contributing are set in place to make that possible. Thank you both.

**Comment by JWegener** [comment]
The tutorial says "Browse available issues and select one to work on" -- how do we find these?

**Comment by yangc95** [comment]
@JWegener I recommend going to the [issues](https://github.com/Codecademy/docs/issues) tab and glancing over each issue's title to determine if you have any interest in the topic to be covered:

![Screen Shot 2022-11-07 at 10 49 25 AM](https://user-images.githubusercontent.com/72277593/200353867-dbfd0e9e-053e-411d-9cd5-0d24c3d4291f.png)

On the right hand side of each issue, you'll see if there is an assignee. If the issue you choose does not have an assignee or potential assignee, comment along the thread (like you've done for this issue), and a maintainer will get back to you about your assignment status.
