### ISSUE TITLE
[Entry] JavaScript: Scope

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1214]
### Reason/inspiration (optional)

We would like to create a new JavaScript entry about **scope** that includes the following information:

- Three (3) separate sections (lv. 2 header) about each scope type:
  - Global scope
  - Module scope
  - Function scope

- Let's dedicate a separate section (also lv. 2 header) about "block scope" regarding variables declared with `let` and `const`.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by rinyusri** [comment]
Hi! I'm new to this, but can I try to work on this entry?

**Comment by Dusch4593** [comment]
Hey @rinyusri, thanks for your interest in contributing to Codecademy Docs! 🚀 

I just assigned this issue to you. If you need help with getting started, I'd recommend starting [here](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md#how-do-i-submit-a-pull-request-pr) in our `CONTRIBUTING.md` guide. Some other documentation to check out:

- [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md)
- [Concept Entry Template](https://github.com/Codecademy/docs/blob/main/documentation/entry-template.md)
- Lists of [subjects](https://github.com/Codecademy/docs/blob/main/documentation/subjects.md), [tags](https://github.com/Codecademy/docs/blob/main/documentation/subjects.md), and [ContentCatalog](https://github.com/Codecademy/docs/blob/main/documentation/catalog-content.md) data

Let me know if you have any questions, I'm happy to help. 😄

**Comment by SSwiniarski** [comment]
@rinyusri, it's been over two weeks since you were assigned this issue. Are you still working on this PR? Do you need assistance?

**Comment by rinyusri** [comment]
@SSwiniarski Hi, i'm working on it but i'm struggling as i haven't finished learning the JS yet. I'll probably take a longer time to complete one. I'm sorry but can I withdraw from this entry because it's difficult for me as a beginner?

**Comment by SSwiniarski** [comment]
@rinyusri no problem, I can unassign you and you can pick up an issue you're more comfortable with.

**Comment by MeganGroenendaal** [comment]
I would like to take on this entry.

**Comment by SSwiniarski** [comment]
@MeganGroenendaal, You're assigned! Thanks for contributing.

**Comment by Xuxuh15** [comment]
Hi! I would like to contribute to this issue.

**Comment by SSwiniarski** [comment]
@Xuxuh15 I'm afraid this has already been assigned.

**Comment by MeganGroenendaal** [comment]
I have been busy with work over the last week and I don't think that will change. I would like to give someone else the chance to take this one. Sorry bout that.

**Comment by SSwiniarski** [comment]
Ok @MeganGroenendaal, I'm unassigning you.

@Xuxuh15, are you still interested in this issue?

**Comment by Xuxuh15** [comment]
@SSwiniarski I am still interested!

**Comment by Dusch4593** [comment]
@Xuxuh15 You are assigned 😄
