### ISSUE TITLE
[Edit] HTML: Forms

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1215]
### Type of Edit (select all that apply)

Clarify unclear content and/or terms, Add new content (definitions, codeblocks, etc.)

### Description (optional)

We'd like the following edits to be made for [HTML: Forms](https://www.codecademy.com/resources/docs/html/forms) entry, in the `html/concepts/forms/forms.md` file:

- **Bold** the first use of the word "forms".
- On line # 19, change "tag" to "element".
- Add a "Syntax" section that offers a minimal \```pseudo code block of what an HTML form would typically look like.
  - This should include the `<form>`, `<label>`, and `<input>` elements.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by petros-wursta** [comment]
I'd like to work on this issue

**Comment by yangc95** [comment]
@petros-wursta assigned!

**Comment by USERALOOO** [comment]
I would  like to work on the issue can I ?

**Comment by Buono-Marco** [comment]
Hello,
I already worked on the task. If you give me the ok, I can submit the PR.

Thank you!

**Comment by Dusch4593** [comment]
Hi @Buono-Marco and @USERALOOO,

Thank you for expressing interest in contributing to this issue. At this time, the issue was recently assigned to another user, @petros-wursta. We're still giving them time to open a PR. Our issues are assigned on a first-come-first-serve basis and we limit each issue to just one assignee.

In the meantime, my team and I are working to produce more issues for this repo. In the meantime, you can view our current unassigned issues [here](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee), which includes [this one](https://github.com/Codecademy/docs/issues/674) that calls for a new HTML entry.

**Comment by petros-wursta** [comment]
Hi All, you can unassign me, I have a work obligation that came up, i
apologize
Best,

*Petros Dertsakyan* | ***@***.***
<http://voice.google.com/calls?a=nc,%2B18182842203>

**Comment by Dusch4593** [comment]
That's no worries, @petros-wursta! 😄

Since @Buono-Marco is already assigned to another issue, I'm going to assign this issue to @USERALOOO.

**Comment by petros-wursta** [comment]
Thank you so much!
Best,

*Petros Dertsakyan* | ***@***.***
<http://voice.google.com/calls?a=nc,%2B18182842203>

**Comment by Buono-Marco** [comment]
Hi @Dusch4593,
I'm ready to work on this task if you want.

**Comment by Dusch4593** [comment]
> Hi @Dusch4593, I'm ready to work on this task if you want.

This has already been assigned to someone else.

**Comment by SSwiniarski** [comment]
@USERALOOO, it's been over two weeks since you were assigned this issue. Are you still working on a PR for this, do you need assistance?

**Comment by SSwiniarski** [comment]
Because of inactivity, I am opening this up so it can be assigned to someone else. @Buono-Marco, are you still interested in working on this PR?

**Comment by farah-qistina** [comment]
Hi, may I claim this issue? I'm doing this as part of the Git and GitHub course

**Comment by SSwiniarski** [comment]
@farah-qistina, you're assigned! Thanks for contributing.

**Comment by jbonjour1** [comment]
Hi, may I claim this issue? I'm doing this as part of the Git and GitHub course

**Comment by SSwiniarski** [comment]
@jbonjour1 This issue has already been assigned. Please look through our many still-open issues.

**Comment by penalus** [comment]
I would like to work on this issue please! Im a super fresh newbie and this looks like something within my reach.

**Comment by SSwiniarski** [comment]
@penalus This issue has already been assigned and has a PR addressing it. Please look through our many [still-open issues](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee).
