### ISSUE TITLE
[Term Entry] HTML Elements: `<section>`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1216]
### Reason/inspiration (optional)

We like someone to create a new term entry about the `<section>` element under the HTML: Elements concept. It should include the following information:

- "Syntax" section with a \```pseudo code block
- "Example" section with an \```html code block
- Include link to existing [HTML: Forms](https://www.codecademy.com/resources/docs/html/forms) entry.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by D-Salkovic** [comment]
Hello, 
I would like to participate in this Issue. 
I am a new Codecademy student and this would be my first contribution.
I came here due to my _Portfolio_ assignment  in **Learn Git & GitHub** course.
Thanks in advance.

**Comment by Dusch4593** [comment]
Hi @D-Salkovic, just assigned you. 😁

**Comment by D-Salkovic** [comment]
#1227

**Comment by D-Salkovic** [comment]
It's my first time submitting a PR so I apologize in advance if it is sloppy

**Comment by Dusch4593** [comment]
Hey @D-Salkovic see [my note](https://github.com/Codecademy/docs/pull/1227#issuecomment-1307470608). 😄
