### ISSUE TITLE
[Term Entry] HTML Elements: `<textarea>`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1218]
### Reason/inspiration (optional)

We would like a new term entry about the `<textarea>` element to be created under the HTML: Elements concept. It should include the following information:

- A "Syntax" section with a \```pseudo code snippet.
  - Include a breakdown of the required and option attributes like `id`, `name`, `rows`, and `cols`.
- An "Example" section with an \```html code snippet.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by USERALOOO** [comment]
I would like to work on this

**Comment by USERALOOO** [comment]
can I work on this

**Comment by Dusch4593** [comment]
@USERALOOO You're assigned! Thanks for your interest in contributing to Codecademy Docs 😄

I was wondering, how did you learn about Docs and about contributing to it?

**Comment by dziarae** [comment]
@Dusch4593 Hi, is this issue already resolved? I am looking for a contribution for my Learn Git/Github lesson.

**Comment by Dusch4593** [comment]
@USERALOOO were you still working on a pull request for this issues?

**Comment by dziarae** [comment]
@Dusch4593 I'm working on it, anyway

**Comment by SSwiniarski** [comment]
@USERALOOO because of over two weeks of inactivity, I am unassigning you and assigning @dziarae.

@dziarae, are you working on this now?

**Comment by dziarae** [comment]
@SSwiniarski yes, it's waiting in my local repository

**Comment by dziarae** [comment]
well, it seems I did something wrong
https://github.com/Codecademy/docs/pull/1298

**Comment by Mateuccio** [comment]
I would like to work on this :)

**Comment by Dusch4593** [comment]
Hey @Mateuccio! 👋🏻 This issue has already been assigned and a pull request is already opened. Check out the current list of open issues [here](https://github.com/Codecademy/docs/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+) to see if anything looks interesting to you. We're looking to add more issues by end of year. 😄

**Comment by Cesarcas1958** [comment]
I would like to work on this

**Comment by yangc95** [comment]
@Cesarcas1958 apologies, this issue is currently taken. I would recommend heading over to the issues tab and checking out [issues that are available](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee) and unclaimed.

Thanks for your interest in contributing to Docs!
