### ISSUE TITLE
[Term Entry] HTML Elements: `<label>`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1219]
### Reason/inspiration (optional)

We would like a new term entry about the `<label>` element to be created under the HTML: Elements concept. It should include the following information:

- A "Syntax" section with a \```pseudo code snippet.
  - Include a `> **Note:**` about how the benefits of using `<label>` with `<input>`.
  - Link to [the existing Docs entry](https://www.codecademy.com/resources/docs/html/elements/input) about the `<input>` element.
- An "Example" section with an \```html code snippet.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Armania** [comment]
Hi, 

I am working on the "Intro to Open Source" course and would love to make this addition to the docs.

Ty,

**Comment by yangc95** [comment]
@Armania, glad the course brought you here to Docs! Assigning you this issue 🙂

**Comment by Armania** [comment]
Just commenting, still working on this, hope to submit something by this weekend

**Comment by Armania** [comment]
Hi team!

I submitted a pull-request, https://github.com/Codecademy/docs/pull/1268 , 

could use a little guidance?

**Comment by Armania** [comment]
@SSwiniarski Created a new pull-request for this issue

->  https://github.com/Codecademy/docs/pull/1429
