### ISSUE TITLE
[Term Entry] Python Built-in Functions: `list()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1220]
### Reason/inspiration (optional)

We would like a new term entry about the `list()` function to be created under the Python: Built-in Functions concept. It should include the following information:

- Include a link to [the existing entry](https://www.codecademy.com/resources/docs/python/iterators) on iterators in Python.
- A "Syntax" section with a \```pseudo code snippet.
- An "Example" section with a \```py code snippet.
- A "Codebyte Example" section with a \```codebyte/python snippet.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by God-ass** [comment]
I am a newbie, but I would like to try this. Pls assign this to me
