### ISSUE TITLE
[Concept Entry] Go: arrays

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1224]
### Reason/inspiration (optional)

We would like a new concept entry for [Go](https://www.codecademy.com/resources/docs/go) about arrays.

The entry should go in a new file in docs/content/go/concepts/arrays/arrays.md

The entry should
- Explain the difference between an array and a slice.
- Have a "Syntax" section with a ```pseudo code snippet showing examples of the different ways of creating and initalizing an array.
- Have a section about accessing the array items with an example ```go snippet
- explain multi-dimensional arrays with an example ```go snippet

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by JJGuilloryGit** [comment]
Good Morning. I would like to contribute to this issue.  Thank you!

**Comment by SSwiniarski** [comment]
@JJGuilloryGit, you've been assigned. Thanks for contributing. Can you let me know how you came across this repo?

**Comment by JJGuilloryGit** [comment]
Yes indeed and thank you.  I came across the repo from the Github course on CA. I had previously taken the Learn Go course so I figured I would give it a go.

**Comment by SSwiniarski** [comment]
@JJGuilloryGit, it's been over two weeks since you were assigned. Are you still working on this PR? Do you need assistance?

**Comment by SSwiniarski** [comment]
@JJGuilloryGit, since it's been over two weeks of inactivity, I am unassigning you so someone else can work on this issue.

**Comment by DominikFeret** [comment]
Hi! I come from the Learn Git & GitHub course on Codecademy and would like to work on this issue. Cheers!

**Comment by SSwiniarski** [comment]
@DominikFeret, you've been assigned.
