### ISSUE TITLE
[Concept Entry] Go: slices

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1225]
### Reason/inspiration (optional)

We would like a new concept entry for [Go](https://www.codecademy.com/resources/docs/go) about slices.

The entry should go in a new file in docs/content/go/concepts/slices/slices.md

The entry should
- Explain the difference between an array and a slice
- Explain the length and capacity
- Have a "Syntax" section with a ```pseudo code snippet showing the different ways of creating and initalizing a slice.
- Have an example about and accessing slice items with an example ```go snippet
- Explain the effects modifying the slice has on its underlying array

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by gracekishino** [comment]
Can I work on this issue?

**Comment by SSwiniarski** [comment]
@gracekishino, you've been assigned. Thanks for contributing. Can I ask how you came across this repo?

**Comment by gracekishino** [comment]
@SSwiniarski thank you for assigning me! I found this repo when I was doing the Codecademy Learn Git & GitHub course.
