### ISSUE TITLE
[Concept Entry] Go: comments

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1236]
### Reason/inspiration (optional)

We would like a new concept entry for [Go](https://www.codecademy.com/resources/docs/go) about comments.

The entry should go in a new file in docs/content/go/concepts/comments/comments.md

The entry should
- Explain single line and multi-line block comments
- briefly describe "doc comments"

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Maheshwaran17** [comment]
Hi @SSwiniarski , I would like to work on this. Could you please assign this issue to me.

**Comment by Maheshwaran17** [comment]
I have submitted a PR for this issue - https://github.com/Codecademy/docs/pull/1241
