### ISSUE TITLE
[Concept Entry] Go: Functions

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1242]
### Reason/inspiration (optional)

We would like a new concept entry for [Go](https://www.codecademy.com/resources/docs/go) about functions.

The entry should go in a new file in docs/content/go/concepts/functions/functions.md

The entry should

- Include a "Syntax" section with a ```pseudo code block showing how a function is declared.
- Include an "Example" section with a ```go code block showing an example of a working function.
- Explain how Go functions can have multiple return values.
- Explain function closures/anonymous functions, with syntax and example.
- Explain how functions become a method, with syntax and example.
- Have one runnable "Codebyte Example" section with a ```codebyte/golang block. 

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by jaymay1979** [comment]
I would like to contribute a new concept entry to Go. Thank you.

**Comment by SSwiniarski** [comment]
@jaymay1979, you've been assigned.

**Comment by SSwiniarski** [comment]
@jaymay1979, it's been over two weeks since you were assigned this issue, are you still working on a PR? Do you need any assistance?

**Comment by SSwiniarski** [comment]
@jaymay1979 because of inactivity on this issue I am unassigning you so someone else can work on it.

**Comment by Pavan-Nambi** [comment]
@SSwiniarski  hey is this up for grabs? or anyone working?

**Comment by Pavan-Nambi** [comment]
hey i am almost finished working on this 

but i am not sure on what to add in
``` Have one runnable "Codebyte Example" section with a codebyte/golang block.```
should i just make all examples in a single code? and keep it in tht section?

**Comment by Pavan-Nambi** [comment]
appologies for this i messed up few things while reverting ignore these commits as of now as i haven't made pull request eitherway...

**Comment by yangc95** [comment]
@Pavan-Nambi Thanks for looking into this issue! For the examples, feel free to use regular code blocks in addition to a codebyte so long as the examples flows well in terms of pedagogy (For example, if we want to show the syntax of a function, we'll use a pseudo code block instead of a dynamic codebyte. Or if we have some more complex piece of code we'd like to show off, we'll use a codebyte so a user can run the code and see its output).

Note that what is in your PR may be subject to change, so TY for your continued efforts ^^

**Comment by Pavan-Nambi** [comment]
@yangc95  hey gotcha thankyou for assisting me , i have a pr at https://github.com/Codecademy/docs/pull/1454#issue-1520429676 so i have to wait until it completely reviewed? as of now 1 review done 

or can i just make a new branch and contribute to this..?

**Comment by yangc95** [comment]
For future reference @Pavan-Nambi if you're assigned a certain number of issues, you can have that many PRs up!

**Comment by Pavan-Nambi** [comment]
ok thankyou!
