### ISSUE TITLE
[Concept Entry] Go: Variables

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1243]
### Reason/inspiration (optional)

We would like a new concept entry for [Go](https://www.codecademy.com/resources/docs/go) about variables.

The entry should go in a new file in docs/content/go/concepts/variables/variables.md

The entry should

- Explain what variables are.
- Explain the syntax of declaring a variable.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Abdelrahmanabusaa** [comment]
can you assign this issue for me to work on 
thank you .

**Comment by SSwiniarski** [comment]
@Abdelrahmanabusaa, you are assigned.
