### ISSUE TITLE
Requesting to make entry in Codecademy Docs per Learn Git and Github Course[Entry] Subject: Entry Name

### ISSUE THREAD

**Issue by strikeouts27** [Codecademy/docs#1244]
### Reason/inspiration (optional)

I am a bit of a rookie and I am going through the codeecademy courses. I was wondering if you guys had any way that I could contribute to the Docs per the course requirements?

-strikeouts27
stribling.andrew@gmail.com

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by SSwiniarski** [comment]
@strikeouts27, you just need to look through the list of issues and find an unassigned one that you're interested in working on. (The ones without the "claimed" label.) Leave a comment there requesting to be assigned.
