### ISSUE TITLE
[Bug/Error] Font of code text

### ISSUE THREAD

**Issue by maki-keep** [Codecademy/docs#1245]
### Actual Behavior

`Code` text is in a serif font when viewing the site on both Chrome and Edge browsers.
The font is a sans-serif on Firefox.
The device used is a Windows 10 PC.

### Expected Behavior

`Code` text should have a monospace font family. Currently "Monaco" is assigned to it.

### On what browser(s) are you seeing the problem?

Firefox, Chrome, Microsoft Edge, Brave

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by EmeraldSerpent57** [comment]
I would like to be assigned this issue!

**Comment by yangc95** [comment]
@EmeraldSerpent57 I'm not sure if this is within scope of Docs contributions for community members.

cc: @christian-dinh

**Comment by christian-dinh** [comment]
Yeah this is an issue we'd have to handle internally, sorry!

**Comment by yangc95** [comment]
Thanks @christian-dinh! Should I go ahead and close this issue?

**Comment by christian-dinh** [comment]
yep I'll make a separate ticket we can track internally
