### ISSUE TITLE
[Concept Entry] Go: Structs

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1246]
### Reason/inspiration (optional)

We would like a new concept entry for [Go](https://www.codecademy.com/resources/docs/go) about structs.

The entry should go in a new file in docs/content/go/concepts/structs/structs.md

The entry should

- Explain what a `struct` is.
- Include a "Syntax" section with a ```pseudo code block showing how a `struct` is declared.
- Include an "Example" section with a ```go code block showing an example of a working `struct`.
- Explain using dot notation to set values of fields.
- Explain setting default values for fields.
- Show initialization of a `struct` with the `var` keyword and with a literal value.
- Show adding a method to a `struct` type.
- Have one runnable "Codebyte Example" section with a ```codebyte/golang block.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by DKB08** [comment]
I would like to work on this.

**Comment by SSwiniarski** [comment]
@DKB08, you've been assigned. Thanks for contributing! I'd like to ask, how did you came across this repo?

**Comment by DKB08** [comment]
> @DKB08, you've been assigned. Thanks for contributing! I'd like to ask, how did you came across this repo?

I'm going through the "Learn Git & GitHub" course on Codecademy.

**Comment by SSwiniarski** [comment]
@DKB08, it's been over two weeks. Are you still working on this PR? Do you need any assistance?

**Comment by SSwiniarski** [comment]
@DKB08 I am unassigning you so someone else can work on this entry.

**Comment by Pavan-Nambi** [comment]
can i be assigned for this? @SSwiniarski

**Comment by SSwiniarski** [comment]
@Pavan-Nambi, you've been assigned.

**Comment by SSwiniarski** [comment]
@Pavan-04-08 Are you working on this? I just noticed I tagged the wrong person assigning this.

**Comment by Pavan-04-08** [comment]
oh yeah @SSwiniarski  no u tagged me only i changed username so yeah i will submit a pr today sorry for delay:)

**Comment by SSwiniarski** [comment]
@Pavan-04-08 It's been another two weeks, are you still working on this?

**Comment by SSwiniarski** [comment]
@Pavan-04-08 Because of inactivity, I am unassigning you so someone else can work on this.

**Comment by Nessvah** [comment]
Hi @SSwiniarski can you assign me this issue? Since it's been a while since I last contributed, I'm going to take a lot at the guidelines again.

**Comment by SSwiniarski** [comment]
@Nessvah You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

Also see [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for styling tips.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by Nessvah** [comment]
Thanks @SSwiniarski ! I'm going to work on it.

**Comment by Nessvah** [comment]
@SSwiniarski hi! I'm almost done with this issue. I have some uni work to do but if I can't finish it this weekend, it'll be ready next one.

**Comment by SSwiniarski** [comment]
@Nessvah Thanks for the update, we like to see that progress is being made after we assign an issue.
