### ISSUE TITLE
[Concept Entry] Go: maps

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1248]
### Reason/inspiration (optional)

We would like a new concept entry for [Go](https://www.codecademy.com/resources/docs/go) about maps.

The entry should go in a new file in docs/content/go/concepts/maps/maps.md

The entry should

- Explain what a `map` is.
- Have a "Syntax" section with a ```pseudo code snippet showing examples of the different ways of creating and initializing a `map`.
- Have a section about accessing and adding to the `map` items with an example ```go snippet.
- Have one runnable "Codebyte Example" section with a ```codebyte/golang block.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by JustinSu77** [comment]
I will like to contribute.

**Comment by SSwiniarski** [comment]
@JustinSu77, you've been assigned. Can you tell us how you came across this repo?

**Comment by JustinSu77** [comment]
I came across this repo from taking the Learn Git & Github course on Codecademy.
