### ISSUE TITLE
[Entry] Open Source: Linux Kernel

### ISSUE THREAD

**Issue by YanisaHS** [Codecademy/docs#1271]
### Reason/inspiration (optional)

A new entry on the Linux Kernel could be added to the [Open Source](https://www.codecademy.com/resources/docs/open-source) concept entry. Also it should be linked in the [Linus Torvalds](https://www.codecademy.com/resources/docs/general/linus-torvalds) and [Linux](https://www.codecademy.com/resources/docs/open-source/linux) pages. This entry could describe what the kernel is used for and how it fits in with the rest of the Linux architecture.

You can assign this issue to me if it's something you want to add. 😇 

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by YanisaHS** [comment]
Hi! Can I be assigned to this? 🥳

**Comment by yangc95** [comment]
Happy holiday season @YanisaHS - Thanks for your patience! I've assigned you to your issue 😄
