### ISSUE TITLE
[Term Entry] Nmap: TCP SYN Scan

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1316]
### Reason/inspiration (optional)

We would like an entry for [Nmap ](https://www.codecademy.com/resources/docs/cybersecurity/nmap) about the TCP SYN Scan option.

It should be located under docs/content/cybersecurity/concepts/nmap/terms/tcp-syn-scan/tcp-syn-scan.md

It should include:
- A description of what the option does.
- A listing of the option itself: `-sS`
- A syntax section showing the option in use.
- An example showing Nmap's output with the option. (Use `scanme.nmap.org` as a target.)

You can look at [Aggressive Scan](https://www.codecademy.com/resources/docs/cybersecurity/nmap/aggressive-scan) to see an example of what we'd like to see.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by fchagasjr** [comment]
I would like to work this issue. Can I be assigned to it?

**Comment by SSwiniarski** [comment]
@fchagasjr You've been assigned. Thanks for contributing!
