### ISSUE TITLE
[Term Entry] Nmap: Version Detection

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1318]
### Reason/inspiration (optional)

We would like an entry for [Nmap ](https://www.codecademy.com/resources/docs/cybersecurity/nmap) about the Version Detection option.

It should be located under docs/content/cybersecurity/concepts/nmap/terms/version-detection/version-detection.md

It should include:
- A description of what the option does.
- A listing of the option itself: `-sV`
- A syntax section showing the option in use.
- An example showing Nmap's output with the option. (Use `scanme.nmap.org` as a target.)

You can look at [Aggressive Scan](https://www.codecademy.com/resources/docs/cybersecurity/nmap/aggressive-scan) to see an example of what we'd like to see.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by JEC1909** [comment]
Hello, I am taking the Git/Github learning course, and I would like to know if I could be assigned to this.

**Comment by SSwiniarski** [comment]
You're assigned @JEC1909. Thanks for contributing!
