### ISSUE TITLE
[Concept Entry] C#: Comments

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1320]
### Reason/inspiration (optional)

We would like a new concept entry for [C#](https://www.codecademy.com/resources/docs/c-sharp) about comments.

The entry should go in a new file in docs/content/c-sharp/concepts/comments/comments.md

The entry should

- Explain single line and multi-line comments.
- Explain XML comments.
- Have syntax and example sections.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by wimthomzik** [comment]
Hey, I just know C from CS50, but as far as I am concerned the syntax is kind of similar. I would like to try to work on this issue..

**Comment by KTom101** [comment]
@wimthomzik Thanks for your interest in creating a Docs entry! You can take a stab at this, I will assign you. If you need help with anything please let us know in this thread. 

Also, you can take a look at the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) or this [article](https://dev.to/codecademy/how-to-contribute-to-codecademy-docs-1a77) for additional information on contributing to Codecademy Docs. 😄

**Comment by wimthomzik** [comment]
Thanks so much! @KTom101
