### ISSUE TITLE
[Concept Entry] C#: Data Types

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1321]
### Reason/inspiration (optional)

We would like a new concept entry for [C#](https://www.codecademy.com/resources/docs/c-sharp) about data types.

The entry should go in a new file in docs/content/c-sharp/concepts/data-types/data-types.md

The entry should

- List all the basic data types and what they hold.
- Have a table listing memory size for each data type.
- Show examples of declaring a variable with a particular data type.

Look at the Data Type entries for other languages to see what we'd like.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by YanisaHS** [comment]
Hi!! 🥳  Could I be assigned to this?

**Comment by SSwiniarski** [comment]
@YanisaHS, you're assigned!
