### ISSUE TITLE
[Concept Entry] C#: System.Math

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1322]
### Reason/inspiration (optional)

We would like a new concept entry for [C#](https://www.codecademy.com/resources/docs/c-sharp) about the built in `System.Math` Class.

The entry should go in a new file in docs/content/c-sharp/concepts/system-math/system-math.md

The entry should

- Explain what it is used for.
- Show an example of using some `System.Math` methods in code.
- End with a line introducing the list of terms that will eventually follow, like in the C++ [Math Functions](https://www.codecademy.com/resources/docs/cpp/math-functions) entry.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Zakalvve** [comment]
Hi, I would like to work on this concept entry. Could I claim it please?

**Comment by SSwiniarski** [comment]
@Zakalvve, you've been assigned. Thanks for contributing to Docs!
