### ISSUE TITLE
[Concept Entry] C#: Methods

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1324]
### Reason/inspiration (optional)

We would like a new concept entry for [C#](https://www.codecademy.com/resources/docs/c-sharp) about Methods.

The entry should go in a new file in docs/content/c-sharp/concepts/methods/methods.md

The entry should

- Show and describe the syntax of declaring and calling a method.
- Show an example of declaring and calling a method.
- Explain the difference in C# between a function and a method.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept for Existing Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by heftif** [comment]
Could I be assigned this issue?

**Comment by SSwiniarski** [comment]
@heftif, you've been assigned! Thanks for contributing!
