### ISSUE TITLE
[Term Entry] SwiftUI ViewModifier: `.frame()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1329]
### Reason/inspiration (optional)

Please write a new entry under:  content/swiftui/concepts/viewmodifier/terms/ about the modifier `.frame()` in Swift.

- A "Syntax" section with pseudo code snippet. [Include height and width]
- An "Example" section with a swift code snippet and image to accompany. Images should go in the `media/` folder.

To get started with the PR and entry file:

Under content/swiftui/concepts/viewmodifier/terms/, create a new folder called `frame`. Then create a new file called `frame.md` under content/swiftui/concepts/viewmodifier/terms/`frame`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by cslylla** [comment]
I would like to work on this issue.

**Comment by Dusch4593** [comment]
@cslylla Sure, you're assigned 😄

**Comment by SSwiniarski** [comment]
@cslylla, it's been over two weeks. Are you still working on this PR? Do you need any assistance?

**Comment by cslylla** [comment]
Yes, @SSwiniarski, I am still working on it. Thanks for following up; I am almost finished with it. I will submit a PR tomorrow, and then I am looking forward to having feedback! 😊
