### ISSUE TITLE
[Term Entry] SwiftUI ViewModifier: `.padding()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1330]
### Reason/inspiration (optional)

Please write a new entry under: content/swiftui/concepts/viewmodifier/terms/ about the modifier `.padding()` in Swift.

- A "Syntax" section with pseudo code snippet. [Horizontal or vertical]
- An "Example" section with a swift code snippet and image to accompany. Images should go in the media/ folder.

To get started with the PR and entry file:

Under content/swiftui/concepts/viewmodifier/terms/, create a new folder called `padding`.  Then create a new file called `padding.md` under content/swiftui/concepts/viewmodifier/terms/`padding`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by cslylla** [comment]
I would like to work on this issue 🤓

**Comment by NSelimA** [comment]
Hello, I would like to work on this issue

**Comment by Dusch4593** [comment]
Since @cslylla asked first, they'll be assigned to this issue.

@NSelimA feel free to look at [these available SwiftUI issue](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee+label%3Aswiftui) and see if any of them interest you 😄
