### ISSUE TITLE
[Term Entry] SwiftUI ViewModifier: `.font()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1331]
### Reason/inspiration (optional)

Please write a new entry under: content/swiftui/concepts/viewmodifier/terms/ about the modifier `.font()` in Swift.

- A "Syntax" section with pseudo code snippet. [Can also mention a note about custom font stacks]
- An "Example" section with a swift code snippet and image to accompany. Images should go in the media/ folder.

To get started with the PR and entry file:

Under content/swiftui/concepts/viewmodifier/terms/, create a new folder called `font`. Then create a new file called `font.md` under content/swiftui/concepts/viewmodifier/terms/`font`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by DavidJC9** [comment]
Hi!
My name is David, I would like to work on this issue.
Thanks

**Comment by Dusch4593** [comment]
Hi, @DavidJC9, thank you for your interest in contributing to Codecademy Docs! I've assigned this issue to you 😄

By chance, how did you learn about Codecademy Docs and about contributing to it?

**Comment by SSwiniarski** [comment]
@DavidJC9 it's been two weeks, are you still working on this PR? Do you need any assistance?

**Comment by SSwiniarski** [comment]
@DavidJC9 I am unassigning you so someone else can work on this entry.

**Comment by gracekishino** [comment]
Please can I work on this issue?

**Comment by yangc95** [comment]
Thanks @gracekishino! Assigned ^^
