### ISSUE TITLE
[Term Entry] SwiftUI ViewModifier: `.fontWeight()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1332]
### Reason/inspiration (optional)

Please write a new entry under: content/swiftui/concepts/viewmodifier/terms/ about the modifier `.fontWeight()` in Swift.

- A "Syntax" section with pseudo code snippet.
- An "Example" section with a swift code snippet and image to accompany. Images should go in the media/ folder.

To get started with the PR and entry file:

Under content/swiftui/concepts/viewmodifier/terms/, create a new folder called `fontWeight`. Then create a new file called `fontWeight.md` under content/swiftui/concepts/viewmodifier/terms/`fontWeight`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by pipcia** [comment]
Hi, I am following the Github course on codecademy. Can you assign me to this task? 
Thank you!

**Comment by Dusch4593** [comment]
Hi @pipcia, thank you for your interest in contributing to Codecademy Docs! You are assigned 😄

**Comment by SSwiniarski** [comment]
@pipcia, it's been two weeks, are you still working on this PR? Do you need any assistance?

**Comment by pipcia** [comment]
yep, sorry , just realized , in 2 days I will have first version added !
