### ISSUE TITLE
[Term Entry] SwiftUI ViewModifier: `.bold()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1333]
### Reason/inspiration (optional)

Please write a new entry under: content/swiftui/concepts/viewmodifier/terms/ about the modifier `.bold()` in Swift.

- A "Syntax" section with pseudo code snippet.
- An "Example" section with a swift code snippet and image to accompany. Images should go in the media/ folder.

To get started with the PR and entry file:

Under content/swiftui/concepts/viewmodifier/terms/, create a new folder called `bold`. Then create a new file called `bold.md` under content/swiftui/concepts/viewmodifier/terms/`bold`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by gracekishino** [comment]
Please can I work on this issue?

**Comment by Dusch4593** [comment]
@gracekishino You're assigned! 😄
