### ISSUE TITLE
[Edit] React Hooks: `useContext`

### ISSUE THREAD

**Issue by DerTimonius** [Codecademy/docs#1335]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Thank you for the great documentation!

I would like to add docs for the `useContext` hook if possible. 
The hook is not part of the React curriculum yet, but the `useContext` hook is a very powerful tool and easy to learn - so I think adding it to the curriculum would be great!

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by yangc95** [comment]
@DerTimonius Sounds like a great idea! I've assigned you to your issue 😄

**Comment by DerTimonius** [comment]
@yangc95 Thank you, will open a PR soon!

**Comment by DerTimonius** [comment]
Hi @yangc95, my PR is ready for review!
