### ISSUE TITLE
C++ functors

### ISSUE THREAD

**Issue by arestrepogiraldo2200** [Codecademy/docs#1336]
### Reason/inspiration (optional)

Under content/cpp/concepts/, I would like to add a new concept about functors (not functions!) in c++ language.

The contents would be

+ Definition and use of overloaded *operator()*
+ Syntax section 
+ Example section

Of course following the [template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md). Please let me know if possible and assign this issue to me.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [x] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Dusch4593** [comment]
Hey @arestrepogiraldo2200! 👋🏻 Thank you for your interest in contributing to Codecademy Docs. Based on your issue description, it seems like you'd like to be assigned to this issue?

**Comment by arestrepogiraldo2200** [comment]
Yes!, assign me please. Thanks beforehand.

**Comment by Dusch4593** [comment]
No worries! 😄

Just a heads up, if there's something that you'd like to write and there isn't an entry/issue for it, go ahead and write it! 🚀
