### ISSUE TITLE
[Term Entry] Python Time Module: `.sleep()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1364]
### Reason/inspiration (optional)

Can we add a new term entry about the `.sleep()` under the [Python: Time Module](https://www.codecademy.com/resources/docs/python/time-module) concept?

It should include the following:

- A "Syntax" section with a \```pseudo code block
- An "Example" section with a \```py code block
- A "Codebyte Example" section with a \```codebyte/python block

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by japhet40** [comment]
Can i take this task ?

**Comment by yangc95** [comment]
@japhet40 you're assigned!

**Comment by mattfwilson** [comment]
@yangc95 Are issues able to be assigned to multiple users? I've been looking for a Python "good first issue" and they are always claimed before I can request to take it.

**Comment by ismahussein** [comment]
i would like to work on this task.

**Comment by yangc95** [comment]
@ismahussein Thanks for your interest! This issue is already completed but feel free to check out other open and unclaimed issues here: https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee
