### ISSUE TITLE
[Concept Entry] Kotlin: Data-Types

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1376]
### Reason/inspiration (optional)

We would like a new concept entry for [Kotlin](https://www.codecademy.com/resources/docs/kotlin) about data types.

The entry should go in a new file in docs/content/kotlin/concepts/data-types/data-types.md

The entry should

- List all the basic data types and what they hold.
- Show examples of declaring a variable with a particular data type.

Look at the Data Type entries for other languages to see what we'd like.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by dakshdeepHERE** [comment]
Can you assign this to me?

**Comment by yangc95** [comment]
@dakshdeepHERE assigned! In addition, how did you find this repository?

**Comment by dakshdeepHERE** [comment]
Well yesterday I was exploring the GitHub issues section with the Kotlin tag present so I can contribute in some Kotlin based projects and there I found these issues posted there ☺️.

**Comment by yangc95** [comment]
@dakshdeepHERE love it, thanks for sharing! Let us know if you need any assistance as you're getting a PR in for this issue 🙂

**Comment by dakshdeepHERE** [comment]
@yangc95 ye I will ask if I face any issue no idea why I was getting cla assistant error when I made a pr for that arrray issue today in morning wait I will attach the ss too. 
<img width="1596" alt="Screenshot 2022-12-28 at 2 28 01 PM" src="https://user-images.githubusercontent.com/94860622/209837846-cb26e359-8f40-4e8a-9ffc-4645e2db7830.png">
😔
I have already tried signing it in many times still the error is not going away for me, well I have also opened a issue related to this on there repo.

**Comment by dakshdeepHERE** [comment]
I guess the cla assistant issue is fixed as it didnt come in my new pr for the data type. 😃

<img width="535" alt="Screenshot 2022-12-29 at 1 31 05 AM" src="https://user-images.githubusercontent.com/94860622/209866590-7dd9e7ae-2bd8-4273-b993-51ec9b749371.png">
<img width="1224" alt="Screenshot 2022-12-29 at 1 34 52 AM" src="https://user-images.githubusercontent.com/94860622/209866606-e8d0084a-d836-463f-b8c5-378171225f76.png">
