### ISSUE TITLE
[Concept Entry] Kotlin: Arrays

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1377]
### Reason/inspiration (optional)

We would like a new concept entry for [Kotlin](https://www.codecademy.com/resources/docs/kotlin) about arrays.

The entry should go in a new file in docs/content/kotlin/concepts/arrays/arrays.md

The entry should

- Have a "Syntax" section with a ```pseudo code snippet showing examples of the different ways of creating and initializing an array.
- Have a section about accessing the array items with an example code snippet
- Have a section on the Arrays class

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by dakshdeepHERE** [comment]
So you need us to tell about arrays in kotlin?

**Comment by dakshdeepHERE** [comment]
If yes then can you assign me for this? I can do it for you.

**Comment by yangc95** [comment]
@dakshdeepHERE assigned! Yes, we would like an entry on arrays in Kotlin. Let us know if you have any additional questions/concerns. Thanks for your interest 🙂

**Comment by dakshdeepHERE** [comment]
No mam that's all I wanted to ask and from tomorrow I will get on with the entry writing.

**Comment by dakshdeepHERE** [comment]
@yangc95  When I was checking the repo and the other files like I know about java too and python so when I was checking there folder for arrays I saw that md file which I have to work on and there was one more file called **terms** so just out of curiosity I want to ask that I have to add that file too?

**Comment by dakshdeepHERE** [comment]
Also when I was checking the arrays file of java and python there was no method mentioned there to print them. Like we have 3 ways of printing a array in java but only one was mentioned there. The loop method of printing the arrays was not mentioned there so if you want I can make a issue there and commit changes there too once I am done with kotlin.

**Comment by SSwiniarski** [comment]
@dakshdeepHERE  There's no need to make a terms folder until someone makes a PR with the terms that would go in there. You're also free to make a PR to update an entry if you feel something is missing.

**Comment by yangc95** [comment]
Thanks for the thoughts! @dakshdeepHERE I think you mean JavaScript here. In addition, arrays don't exist natively in Python, lists are used instead to create an array-like structure.

For future discussion ideas like this, make sure to create a new discussion here: https://github.com/Codecademy/docs/discussions/categories/ideas
This way, it's easier to track these thoughts, and other maintainers can easily chime in if needed.

**Comment by dakshdeepHERE** [comment]
you can see I have done the pr @yangc95 @SSwiniarski

**Comment by dakshdeepHERE** [comment]
@SSwiniarski I'm facing some issues when making a pr I have also open a [issue](https://github.com/Codecademy/docs/issues/1409#issue-1514702436) related to this
