### ISSUE TITLE
[Edit] JavaScript: Arrow Functions

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1378]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

Could we make the following edits to the `arrow-functions.md` file, inside the `content/javascript/concepts/arrow-functions/` directory?

- On line # 17, either change to "\*\*Arrow functions\*\* are expressions first introduced...." _or_ "\*\*Arrow function\*\* expressions were first introduced..."
- The list items on lines # 21 & 22 should be moved somewhere in the "Syntax" section below (preferably below line # 34.
- Lines # 36-41: the block quote **note** should be changed into its own section with a lv. 3 header titled "Limitations".
- Line # 71: The code block signature needs to be changed to \```codebyte/javascript.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by faiz887** [comment]
Hi @Dusch4593

Can I work on this issue?

**Comment by yangc95** [comment]
🎁 @faiz887 assigned! What brought you to this repository?

**Comment by faiz887** [comment]
@yangc95 I wanna start contributing to open source and I found this repo when I searched for the label "good first issues" on github.

**Comment by faiz887** [comment]
Hey , It's my first time submitting a PR so I apologize in advance if it is sloppy. And let me know if you need to me add something more to it.
#1388

**Comment by aditya123473892** [comment]
** Hi  i want to contribute on the issue**

**Comment by aditya123473892** [comment]
#  Hi i want to contribute on the issue

**Comment by Dusch4593** [comment]
Hi @aditya123473892, this issue has already been assigned and a PR has been opened for it. Feel free to check out the list of available issues [here](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee).
