### ISSUE TITLE
[Term Entry] Pandas DataFrame: `.shape()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1380]
### Reason/inspiration (optional)

Let's write a new term entry about the `.shape()` DataFrame method (in pandas).

Folder/file structure: `content/pandas/concepts/dataframe/shape/shape.md`

Make sure to include the following sections:

- A "Syntax" section with a \```pseudo code snippet.
- An "Example" section with a \```py code snippet.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by remoonp** [comment]
Hello Dusch4593.
My name is Reymond from Indonesia.
My job currently is math teacher and I am interested in programming.
Since I'm a newbie, what can I do for `.shape()` Pandas DataFrame?
I have a little knowledge about Pandas.
Thank you before.

**Comment by yangc95** [comment]
Hi Reymond @remoonp ! Great to have you here. How did you find out about contributing to the Docs repository?

We'll gladly go ahead and assign this issue to you about the `.shape()` method. I see you've already forked the project.

First, I'm going to go ahead and assign you this issue and then you can create a term entry by adding the respective folder+file. If you have any specific questions, please do not hesitate to ask!

**Comment by remoonp** [comment]
Thank you for assigned me in this issue.
How can I create a term entry?
Is there any references that can I learn first?

**Comment by yangc95** [comment]
@remoonp No problem!

If you're making changes directly through GitHub, you can create a new term entry by:

- Go to your [fork](https://github.com/remoonp/docs)

**Comment by remoonp** [comment]
I'm already forked (updated branches) those documentations.

**Comment by yangc95** [comment]
@remoonp No problem!

If you're making changes directly through GitHub, you can create a new term entry by these steps:

- Go to your [fork](https://github.com/remoonp/docs). I notice you forked off of one of our maintainer's repos. I'd like you to delete your current fork and fork the [official Codecademy repo](https://github.com/Codecademy/docs) instead.
- Create a new branch
<img width="329" alt="Screen Shot 2022-12-26 at 7 37 03 AM" src="https://user-images.githubusercontent.com/72277593/209549838-f86ba847-a245-4e55-8817-64dc76b83240.png">
- Create a new file in that branch
<img width="224" alt="Screen Shot 2022-12-26 at 7 39 54 AM" src="https://user-images.githubusercontent.com/72277593/209550109-09cfae3c-6dc9-4c51-8d7a-a5d5268b1a94.png">
<img width="646" alt="Screen Shot 2022-12-26 at 7 40 53 AM" src="https://user-images.githubusercontent.com/72277593/209550192-fd859099-e68a-4fdf-9513-372fa07bfd82.png">

After that, follow the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) and this [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md) to get you started. Feel free to also look at other [DataFrame terms](https://github.com/Codecademy/docs/tree/main/content/pandas/concepts/dataframe/terms) as examples as well.

**Comment by remoonp** [comment]
What branches should I choose? Main or Dusch?
![image](https://user-images.githubusercontent.com/119769639/209550804-bb437cb4-adf8-48e6-8558-95e9f0068631.png)

**Comment by yangc95** [comment]
@remoonp start typing in a name for the branch. `dataframe-shape` should do nicely or another semantic name. Then, you'll see the option to create that branch.

**Comment by remoonp** [comment]
I'm already create new file in my branch.

**Comment by yangc95** [comment]
@remoonp Great! Let me know if you need any further assistance.

**Comment by remoonp** [comment]
I'm already pull request a new term.
Please make any suggestion for this term.
