### ISSUE TITLE
[Concept Entry] Kotlin: Variables

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1385]
### Reason/inspiration (optional)

We would like a new concept entry for [Kotlin](https://www.codecademy.com/resources/docs/kotlin) about variables.

The entry should go in a new file in docs/content/kotlin/concepts/variables/variables.md

The entry should

- Explain what variables are.
- Explain the syntax of declaring a variable.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by dakshdeepHERE** [comment]
claim

**Comment by SSwiniarski** [comment]
@dakshdeepHERE, can we have PRs for the other two outstanding issues you claimed before we assign you to another one?

**Comment by dakshdeepHERE** [comment]
@SSwiniarski yes for sure I will work on them today no worries.

**Comment by dakshdeepHERE** [comment]
claim @SSwiniarski I am with all the last 4 issues that were assigned to me and I have also made the pr

**Comment by dakshdeepHERE** [comment]
claim

**Comment by dakshdeepHERE** [comment]
@SSwiniarski @yoiang

**Comment by SSwiniarski** [comment]
@dakshdeepHERE, You've been assigned.
