### ISSUE TITLE
[Concept Entry] Kotlin: Classes

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1386]
### Reason/inspiration (optional)

We would like a new concept entry for [Kotlin](https://www.codecademy.com/resources/docs/kotlin) about classes.

The entry should go in a new file in docs/content/kotlin/concepts/classes/classes.md

The entry should

- Explain what classes are.
- Explain the rules and syntax of declaring a class.
- Have a code block with an example class, showing it in use.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by dakshdeepHERE** [comment]
claim
