### ISSUE TITLE
[Concept Entry] Kotlin: Loops

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1387]
### Reason/inspiration (optional)

We would like a new concept entry for [Kotlin](https://www.codecademy.com/resources/docs/kotlin) about loops.

The entry should go in a new file in docs/content/kotlin/concepts/loops/loops.md

The entry should:

- Have a section on each type of looping control structure..
- Have a syntax pseudo block for each type of loop.
- Have an example code block for each loop

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by dakshdeepHERE** [comment]
claim

**Comment by yangc95** [comment]
@dakshdeepHERE assigned 👍

**Comment by dakshdeepHERE** [comment]
@yangc95  can you check my pull requests that I made

**Comment by dakshdeepHERE** [comment]
@yangc95 @SSwiniarski I'm facing some issues with lint can you please check the issue that I opened related to it.

**Comment by dakshdeepHERE** [comment]
@SSwiniarski all problems are fixed and I am making prs for all the issues that were assigned to me now :D

**Comment by dakshdeepHERE** [comment]
i have made the pr for this issue too.
