### ISSUE TITLE
[Entry] Python Strings: .startswith()

### ISSUE THREAD

**Issue by AaronJohnson02** [Codecademy/docs#1392]
### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by edvardsmazprecnieks** [comment]
Can this be assigned to me? :)

**Comment by yangc95** [comment]
Thanks @edvardsmazprecnieks for submitting the PR so quickly.

In the future, make sure to get approval by one of the Docs maintainers before submitting a PR for an issue. After you've been approved and assigned the issue, then you can proceed to creating a PR.

In addition, we'd like to know: how did you find out about contributing to Codecademy's Docs?

**Comment by edvardsmazprecnieks** [comment]
> In addition, we'd like to know: how did you find out about contributing to Codecademy's Docs?

Through git course materials :)
