### ISSUE TITLE
[Term Entry] SwiftUI View Modifier: `.textFieldStyle()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1393]
### Reason/inspiration (optional)

Please write a new entry under: content/swiftui/concepts/viewmodifier/terms/ about the modifier `.textFieldStyle()` in Swift.

- A "Syntax" section with pseudo code snippet.
- An "Example" section with a swift code snippet and image to accompany. Images should go in the media/ folder.

To get started with the PR and entry file:

Under content/swiftui/concepts/viewmodifier/terms/, create a new folder called `textFieldStyle`. Then create a new file called `textFieldStyle.md` under content/swiftui/concepts/viewmodifier/terms/`textFieldStyle`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by gracekishino** [comment]
@yangc95 please can I work on this? Also, is the 's' a typo and this issue is for te**x**tFieldStyle()?

**Comment by Dusch4593** [comment]
@gracekishino just assigned you. Thank you! 😄

**Comment by gracekishino** [comment]
@Dusch4593 just checking, is this for .te**x**tFieldStyle(), rather than .te**s**tFieldStyle()? Thanks!

**Comment by Dusch4593** [comment]
> @Dusch4593 just checking, is this for .te**x**tFieldStyle(), rather than .te**s**tFieldStyle()? Thanks!
> 
> 
> 
> 

cc @yangc95

**Comment by yangc95** [comment]
@gracekishino yes, good eye! 😃 Changed to reflect the proper modifier!

**Comment by gracekishino** [comment]
@yangc95 thanks for the clarification! 🙏
