### ISSUE TITLE
[Term Entry] SwiftUI View Modifier: `.underline()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1395]
### Reason/inspiration (optional)

Please write a new entry under: content/swiftui/concepts/viewmodifier/terms/ about the modifier `.underline()` in Swift.

- A "Syntax" section with pseudo code snippet.
- An "Example" section with a swift code snippet and image to accompany. Images should go in the media/ folder.

To get started with the PR and entry file:

Under content/swiftui/concepts/viewmodifier/terms/, create a new folder called `underline`. Then create a new file called `underline.md` under content/swiftui/concepts/viewmodifier/terms/`underline`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by TernovoiD** [comment]
May I work on it? It seems like a “good first issue”

**Comment by Dusch4593** [comment]
Hey @TernovoiD I just officially assigned this issue to you 😄

Once #1427 is merged, this issue should automatically close afterward.

**Comment by TernovoiD** [comment]
Many thanks @Dusch4593 ! :)
