### ISSUE TITLE
[Term Entry] SwiftUI View Modifier: `.strikethrough()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1396]
### Reason/inspiration (optional)

Please write a new entry under: content/swiftui/concepts/viewmodifier/terms/ about the modifier `.strikethrough()` in Swift.

- A "Syntax" section with pseudo code snippet.
- An "Example" section with a swift code snippet and image to accompany. Images should go in the media/ folder.

To get started with the PR and entry file:

Under content/swiftui/concepts/viewmodifier/terms/, create a new folder called `strikethrough`. Then create a new file called `strikethrough.md` under content/swiftui/concepts/viewmodifier/terms/`strikethrough`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by matthewogtong** [comment]
Can I be assigned this issue?

**Comment by yangc95** [comment]
@matthewogtong assigned!
