### ISSUE TITLE
[Term Entry] SwiftUI View Modifier: `.scaledToFit()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1398]
### Reason/inspiration (optional)

Please write a new entry under: content/swiftui/concepts/viewmodifier/terms/ about the modifier `.scaledToFit()` in Swift.

- A "Syntax" section with pseudo code snippet.
- An "Example" section with a swift code snippet and image to accompany. Images should go in the media/ folder.

To get started with the PR and entry file:

Under content/swiftui/concepts/viewmodifier/terms/, create a new folder called `scaledToFit`. Then create a new file called `scaledToFit.md` under content/swiftui/concepts/viewmodifier/terms/`scaledToFit`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by cjsdehaas** [comment]
Hello, I'm currently following the Github course. Can I be assigned to the above? Thank you!

**Comment by yangc95** [comment]
@cjsdehaas woohoo! Ahead of the game - thanks for letting us know you've found Docs through the GitHub course.

I've gone ahead and assigned you this issue. If you're having difficulty with anything, don't hesitate to ask! Thanks for your efforts 🙂
