### ISSUE TITLE
[Entry] Subject: Lint error

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#1409]
### Reason/inspiration (optional)

So today when I was trying to push 2 PRs I got same error in both of them.Which was MD046/code-block-style Code block style [Expected: fenced; Actual: indented] but the thing is that I have put all the code in ``` ``` then why I'm getting this error?
<img width="1155" alt="Screenshot_2022-12-30_at_11_27_26_PM" src="https://user-images.githubusercontent.com/94860622/210100891-e0a8ea27-c6c1-4f52-834d-29c83c04513a.png">

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by dakshdeepHERE** [comment]
I have fenced all the code blocks like this still I'm getting this error.
<img width="1209" alt="Screenshot 2022-12-31 at 12 00 13 AM" src="https://user-images.githubusercontent.com/94860622/210101747-1b8cbd60-b104-4b9c-a833-4dbf1405e38d.png">

**Comment by gracekishino** [comment]
@dakshdeepHERE  are there any other indents or white space in the markdown anywhere, apart from the code blocks?

**Comment by dakshdeepHERE** [comment]
@gracekishino Yes ! its fixed at last !!!! 
<img width="1728" alt="Screenshot 2022-12-31 at 5 09 06 PM" src="https://user-images.githubusercontent.com/94860622/210135357-c95c7636-75dd-4655-a046-7089bb264667.png">
Both yarn test and yarn list passed the tests !
I think the problem was white space in the list that I did 😢

**Comment by dakshdeepHERE** [comment]
@gracekishino Thanks a lot now I can make my last 3 PRs that were pending. yay

**Comment by gracekishino** [comment]
@dakshdeepHERE Great! I think I had the same problem with my first PR too 😅

**Comment by yangc95** [comment]
@dakshdeepHERE @gracekishino love this thread! Thanks for helping one-another out.

It'd be great if discussions/issue like this can live in https://github.com/Codecademy/docs/discussions so anyone with similar concerns can refer back to them. If you'd like to create a new discussion revolving around this error and fix, that would be amazing.

Thanks for your efforts ☺️
