### ISSUE TITLE
[Entry] SQL: Drop Table

### ISSUE THREAD

**Issue by kazumikerr** [Codecademy/docs#1424]
### Reason/inspiration (optional)

There is no **Drop Table** topic for the SQL Terms in the codecademy docs yet.

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by kazumikerr** [comment]
I am taking the Git and Github course on Codecademy and would like to work on this issue.

**Comment by KTom101** [comment]
@kazumikerr Thanks for your interest in contributing! I've gone ahead and assigned you. Please, reach out if you need any help, and feel free to take a look at the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for guidance!

**Comment by KTom101** [comment]
@kazumikerr Also, may I ask how did you find out about contributing to Codecademy Docs? 😃

**Comment by kazumikerr** [comment]
Thank you for assigning the task to me.  I will work on it as soon as possible. 
I'm currently taking the **Learn Git & Github**  course and contributing to the codecademy docs repository is one of the assignments.  I'm excited to work on this.

**Comment by KTom101** [comment]
@kazumikerr So happy to hear that! Looking forward to seeing your entry!
