### ISSUE TITLE
[Term Entry] Java ArrayList: `.get()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1441]
### Reason/inspiration (optional)

We'd like to add a new term entry for the `.get()` method under the Java: ArrayList concept. In the new entry, please include the following:

- A "Syntax" section with a \```pseudo code snippet.
- An "Example" section with a \```java code snippet.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by dakshdeepHERE** [comment]
claim

**Comment by dakshdeepHERE** [comment]
Oh I was already done with those Pr and thinking to work on a new issue @Dusch4593 I thought I can claim it 😅

**Comment by Dusch4593** [comment]
@dakshdeepHERE No worries! Some of your PRs still need a next review and may require additional changes.

**Comment by dakshdeepHERE** [comment]
@Dusch4593 Yep I'm always here for the changes no worries hoping to contribute more in this community as a grow in android development and artificial intelligence ❤️

**Comment by hectorconte** [comment]
Hi, can I claim this please? Thanks in advance

**Comment by Dusch4593** [comment]
Hi @hectorconte, thanks for your interest in contributing to Codecademy Docs! 😄

Since a PR has already been created for this one (#1441), this issue is technically claimed (apologies for not labeling sooner 😓)

Feel free to check out the list of available, unassigned issues [here](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee).

**Comment by hectorconte** [comment]
No problem @Dusch4593 ! Just starting on my developing journey anyways, will keep searching. Thanks a lot!

**Comment by Dusch4593** [comment]
Sincere apologies for my oversight, @hectorconte. Would you still like to work on this issue? The PR I was previously referring to had to do with a separate, unrelated topic, not Java.

**Comment by hectorconte** [comment]
If that's ok with you, yes, @Dusch4593, I would like that! Thanks in advance.

**Comment by Dusch4593** [comment]
@hectorconte Assigned! 😄
