### ISSUE TITLE
[Edit] CSS Position: `position`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1443]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting, Clarify unclear content and/or terms, Add new content (definitions, codeblocks, etc.)

### Description (optional)

We'd like to make the following edits to the term entry about the CSS `position` property:

- Rewrite opening sentence to (1) explicitly name the term and (2) emphasize the term in **bold**.
- Currently, there are 4 "Example .." sections that showcase the different values of `position`. Can we consolidate this into 1 or 2 "Example .." sections that feature multiple `.box`es that have the same height/width but different `position` values? (`fixed`, `static`, `relative`, etc.)
- Can we add an image of what the rendered output of these examples would look like?
  - Make sure to save this image as a `.png` file and store in the [`media/` folder](https://github.com/Codecademy/docs/tree/main/media).

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by lindsaylearns** [comment]
I would like to work on this issue. Please assign to me.

**Comment by lindsaylearns** [comment]
@Dusch4593 Yes, I'm doing this for the git project on Codeacademy.
