### ISSUE TITLE
[Edit] JavaScript Arrays: `.indexOf()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1444]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting, Clarify unclear content and/or terms

### Description (optional)

We'd like the following edits to be made to the `.indexOf()` term entry under JavaScript: Arrays:

- Under the "Syntax" section, let's change the code block signature from \```js to \```pseudo.
- For line's # 24-27, can we try to consolidate this information into two list items (each a single, complete sentence)?
- There is a typo on line # 51; can we change from "... after the _first_ element" to "... after the _second_ element"? (emphasis mine)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by gracekishino** [comment]
Please can I work on this one?

**Comment by Dusch4593** [comment]
@gracekishino Sure! You are assigned. 😄
