### ISSUE TITLE
[Edit] SQL: Primary Keys

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1445]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Could we make the following edits in the concept entry for primary keys in SQL?

- On line # 15, can we rearranges the text such that (1) the phrase "primary key" is closer to the start of the sentence, and (2) the phrase "primary key" is emphasized in **bold**? (just on line # 15, though, nowhere else).
- In addition to the existing sections, can we add a new section about "Composite Keys" and how they allow some database tables to have primary keys that span multiple columns?
  - Would it be possible to include some code and output examples with \```sql and \```shell code blocks, respectively?

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by fedoteh** [comment]
Claim!

**Comment by Dusch4593** [comment]
You got it, @fedoteh! Thank you for your interest in contributing to Codecademy Docs!

**Comment by fedoteh** [comment]
@Dusch4593 I think it's done now! Let me know what you think; did I do anything weird on the entire PR process? This is my first one! Thanks in advance
