### ISSUE TITLE
[Edit] Python Strings: `.split()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1446]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

Could we make the following edits to the term entry for the `.split()` method under Python: Strings?

- Under the list of `Tags` (lines # 8-12), let's add `'Lists'` to it.
- On line # 28, let's remove the extra "a" from "A `delimiter` that is a either a ..."
- On line # 33, let's add `>` in front of \*\*Note:\*\*.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Dusch4593** [comment]
@pipcia You're assigned 😄

**Comment by pipcia** [comment]
Done, #1474 pr
