### ISSUE TITLE
[Edit] Python Strings: `.upper()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1448]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting, Clarify unclear content and/or terms, Add new content (definitions, codeblocks, etc.)

### Description (optional)

Can we make the following changes to the term entry for the `.upper()` method under Python:Strings?

- Change the typo in the `Description` on line # 3 from "lowercase" to "uppercase"
- Rephrase the opening text on line # 16 to "The \*\*\`.upper()\`\*\* method takes a string, and returns..."
- Under the "Syntax" section, let's change the code block signature to \```pseudo.
- All remaining \```python signatures should be edited to \```py.
- Currently, there are three (3) "Example ..." sections. Let's consolidate this into the following:
  - One "Example" section with a \```py code block and a \```shell output snippet.
  - One "Codebyte Example" section with a \```codebyte/python code block _(**no output snippet, though**)_

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by gracekishino** [comment]
Please can I work on this?

**Comment by Dusch4593** [comment]
@gracekishino Sure! Assigned 😄
