### ISSUE TITLE
[Term Entry] Java ArrayList: `.add()`

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1449]
### Reason/inspiration (optional)

Add a new term entry under the [Java: ArrayList](https://www.codecademy.com/resources/docs/java/array-list) concept. This entry should include:

- An explanation of the method.
- A "Syntax" section with a ```pseudo code snippet showing the general syntax.
- An "Example" section with a ```java code snippet showing how it works.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by dakshdeepHERE** [comment]
Claim

**Comment by KTom101** [comment]
@dakshdeepHERE Assigned, thanks!

**Comment by dakshdeepHERE** [comment]
@KTom101  I have to add a file **add().md** in the terms folder or edit the **arraylist.md** and info about .add() in that file?

**Comment by dakshdeepHERE** [comment]
also there is already a file which states about **.add()** in the terms folder 
<img width="1578" alt="image" src="https://user-images.githubusercontent.com/94860622/210727450-8bc99003-b291-4a45-b80f-c57b571002a1.png">

**Comment by KTom101** [comment]
@dakshdeepHERE Thank you for catching this and I apologize for the overlook. I will go ahead and close this and assign you to the Java ArrayList: `.length()` issue.
