### ISSUE TITLE
[Term Entry] Java ArrayList: `.size()`

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1450]
### Reason/inspiration (optional)

Add a new term entry under the [Java: ArrayList](https://www.codecademy.com/resources/docs/java/array-list) concept. This entry should include:

- An explanation of the method.
- A "Syntax" section with a ```pseudo code snippet showing the general syntax.
- An "Example" section with a ```java code snippet showing how it works.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by dakshdeepHERE** [comment]
claim

**Comment by dakshdeepHERE** [comment]
check #1470

**Comment by dakshdeepHERE** [comment]
@KTom101
