### ISSUE TITLE
[Term Entry] Java Array: `.length` property 

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1451]
### Reason/inspiration (optional)

Add a new term entry under the [Java: Array](https://www.codecademy.com/resources/docs/java/array-list) concept. This entry should include:

- An explanation of the property.
- A "Syntax" section with a ```pseudo code snippet showing the general syntax.
- An "Example" section with a ```java code snippet showing how it works.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by dakshdeepHERE** [comment]
claim

**Comment by KTom101** [comment]
@dakshdeepHERE You've been assigned. Please add under the ArrayList terms folder as `length.md`.

**Comment by SSwiniarski** [comment]
@KTom101 this issue needs a slight change. an `ArrayList` doesn't have a `.length` property, it has a `.size` property. I left a note about this in @dakshdeepHERE's PR.

**Comment by SSwiniarski** [comment]
@KTom101, it can be a term entry for Array.

**Comment by KTom101** [comment]
@dakshdeepHERE I've corrected this to `Array`. Do you still want to work on this? I see you wrote in the PR you're going to change it to the `ArrayList` `.size()` method.

**Comment by dakshdeepHERE** [comment]
@KTom101 sure

**Comment by dakshdeepHERE** [comment]
@KTom101 will create new pr with `size().`

**Comment by dakshdeepHERE** [comment]
@KTom101 #1470 pr I created on .size()

**Comment by naveengatlewar** [comment]
Requesting to work on this issue.

**Comment by KTom101** [comment]
@dakshdeepHERE So that it's clear, you are not working on the .length property for Arrays? If not, I can reassign this.

**Comment by dakshdeepHERE** [comment]
@KTom101 I guess I have already completed this but haven't pushed yet. Wait I will update it.

**Comment by KTom101** [comment]
@naveengatlewar Since @dakshdeepHERE is working on this, please check the [issues tab](https://github.com/Codecademy/docs/issues) for any unclaimed issues.

**Comment by dakshdeepHERE** [comment]
@KTom101 Please check PR #1547 and sorry for the delayed push it was already done like a week ago just forgot to push it due to college work.
