### ISSUE TITLE
[Term Entry] Java ArrayList: `.indexOf()`

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1453]
### Reason/inspiration (optional)

Add a new term entry under the [Java: ArrayList](https://www.codecademy.com/resources/docs/java/array-list) concept. This entry should include:

- An explanation of the method.
- A "Syntax" section with a ```pseudo code snippet showing the general syntax.
- An "Example" section with a ```java code snippet showing how it works.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Pavan-Nambi** [comment]
hello, can i be assigned for this?

**Comment by KTom101** [comment]
@Pavan-Nambi Of course, you have been assigned. Feel free to check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) or drop a question if you need any help.

Also, where did you learn about contributing to Codecademy Docs?

**Comment by Pavan-Nambi** [comment]
@KTom101 hey there thankyou! i have been just checking goodfirstissues on github and found this....

**Comment by KTom101** [comment]
@Pavan-Nambi Got it! Happy you came across this.

**Comment by Pavan-Nambi** [comment]
@KTom101  there is no rust section...?

**Comment by KTom101** [comment]
@Pavan-Nambi No, Rust is not a topic on Codecademy Docs. We're only adding concept & term entries under existing topics at the moment.
