### ISSUE TITLE
[Term Entry] Python Built-in Functions: `isinstance()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1482]
### Reason/inspiration (optional)

We'd like someone to write a new term entry about the `isinstance()` function under [Python: Built-in Functions](https://www.codecademy.com/resources/docs/python/built-in-functions). Could we include the following sections?

- A "Syntax" section with a \```pseudo.
- An "Example" section with a \```py.
- A "Codebyte Example" with a runnble \```codebyte/python.

This content should be stored in a Markdown file called `isinstance.md` and this file should be stored in a new folder called `isinstance`. From there, `isinstance/isinstance.md` should be stored inside the `content/python/concepts/built-in-functions/terms/` directory.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by mattfwilson** [comment]
Thanks for adding some new Python tasks! Mind if I claim this one?

**Comment by Dusch4593** [comment]
Hey @mattfwilson, I do not mind at all! 😄 You are assigned, my friend. And thank you for your interest in contributing to Codecademy Docs! 🚀 By chance, how did you learn about Docs and about contributing to it?

**Comment by mattfwilson** [comment]
@Dusch4593 Appreciate it! I've been using Codecademy for about a year and change slowly making my way through the git and Python courses. :)

**Comment by SSwiniarski** [comment]
@mattfwilson are you still working on this issue? It's been several weeks with no PR. Do you need assistance?

**Comment by mattfwilson** [comment]
@SSwiniarski Yes, apologies. Life has gotten in the way; hoping to create a PR this week. Thank you for the reminder!

**Comment by mattfwilson** [comment]
Hi @yangc95, thanks for merging everything in. I saw you reopened this? Is there anything you need me to do on my end to resolve?

**Comment by yangc95** [comment]
Hey @mattfwilson thanks for your response!

I had to revert the merge because the file placed in the functions folder rather than the built-in functions folder. I'm sure the similar naming was a bit confusing. It would be great if you can open a new PR but this time have the term entry be a term under built-in functions instead.

If you're having difficulty moving the file, feel free to open a PR with a small change to the file and I can assist with the move. Thanks!

**Comment by mattfwilson** [comment]
Hi @yangc95 Thanks for all the help on this. I'm in the midst of learning git. I believe I've correctly opened a new PR with the isinstance.md in the correct built-in directory, but let me know if not.
