### ISSUE TITLE
[Term Entry] Python Built-in Functions: `issubclass()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#1484]
### Reason/inspiration (optional)

We'd like someone to write a new term entry about the `issubclass()` function under [Python: Built-in Functions](https://www.codecademy.com/resources/docs/python/built-in-functions). Could we include the following sections?

- A "Syntax" section with a \```pseudo.
- An "Example" section with a \```py.
- A "Codebyte Example" with a runnble \```codebyte/python.

This content should be stored in a Markdown file called `issubclass.md` and this file should be stored in a new folder called `issubclass`. From there, `issubclass/issubclass.md` should be stored inside the `content/python/concepts/built-in-functions/terms/` directory.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by cacaprog** [comment]
Hey, I'd like to work on it 😉

**Comment by Dusch4593** [comment]
@cacaprog you are assigned! Thank you for your interest in contributing to Codecademy Docs! 😄

**Comment by cacaprog** [comment]
Hi @Dusch4593 , how are you?
I just make a pull request.

Is everything ok?
Waiting for your review / comments.
