### ISSUE TITLE
[Term Entry] C# Array `.Sort()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1498]
### Reason/inspiration (optional)

We would like a new term entry for [C#](https://www.codecademy.com/resources/docs/c-sharp) about the Array.Sort() method.

The entry should go in a new file in docs/content/c-sharp/concepts/arrays/terms/sort/sort.md

The entry should

Have a syntax section illustrating the method with a \`\`\`pseudo code block.
An example showing the method in use with a \`\`\`cs code block.
A runnable codebyte example in a \`\`\`codebyte/csharp block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by cslylla** [comment]
I would like to work on this issue.

**Comment by SSwiniarski** [comment]
@cslylla, You're assigned!
