### ISSUE TITLE
[Term Entry] C# Array `.Copy()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1500]
### Reason/inspiration (optional)

We would like a new term entry for [C#](https://www.codecademy.com/resources/docs/c-sharp) about the Array.Copy() method.

The entry should go in a new file in docs/content/c-sharp/concepts/arrays/terms/copy/copy.md

The entry should

Have a syntax section illustrating the method with a \`\`\`pseudo code block.
An example showing the method in use with a \`\`\`cs code block.
A runnable codebyte example in a \`\`\`codebyte/csharp block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by mailmyk** [comment]
Hi, can this issue be assigned to me so I can submit a contribution? Thanks

**Comment by SSwiniarski** [comment]
@mailmyk You've been assigned! Can I ask how you came across this repo?

**Comment by SSwiniarski** [comment]
@mailmyk, It's been two weeks. Are you still working on this issue? Do you need any assistance?

**Comment by SSwiniarski** [comment]
@mailmyk, because of inactivity, I am unassigning you so someone else can work on this.

**Comment by yangc95** [comment]
@d-glennon Looking forward to your Pull Request!

Feel free to refer to the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for a general overview and [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for help with structure and styling for your PR 🙂
