### ISSUE TITLE
[Term Entry] C# Array `.CopyTo()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1501]
### Reason/inspiration (optional)

We would like a new term entry for [C#](https://www.codecademy.com/resources/docs/c-sharp) about the Array.CopyTo() method.

The entry should go in a new file in docs/content/c-sharp/concepts/arrays/terms/copyto/copyto.md

The entry should

Have a syntax section illustrating the method with a \`\`\`pseudo code block.
An example showing the method in use with a \`\`\`cs code block.
A runnable codebyte example in a \`\`\`codebyte/csharp block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Greekforce1821** [comment]
Hello,

I would like to take part in this issue by helping with the writing!

P.S. I am a newcomer.

**Comment by SSwiniarski** [comment]
@Greekforce1821, You're assigned. Can I ask you how you came across this repo?

**Comment by Greekforce1821** [comment]
Hello sir,

I have an active educational subscription at the Codeacademy platform. I nearly completed my Github course, but, in order to finish it (100%), the platform assigned me an exercise . The idea of the exercise is to get familiar with the functionality of the GitHub by forking a specific repository and contributing by creating an .MD file from the issues of the Docs Repo.

**Comment by ladimoe1** [comment]
@SSwiniarski Hello, I am interested in taking this issue on, I found out about Docs through my Codecademy course on Github.

**Comment by SSwiniarski** [comment]
@ladimoe1 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md)for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by PeddiAlekhya** [comment]
@anunaidu I am very interested to part of this in taking issues. I am new to  this platform.

**Comment by SSwiniarski** [comment]
@PeddiAlekhya this issue was already assigned. Look for an unclaimed issue if you want to contribute.

**Comment by SSwiniarski** [comment]
@ladimoe1 it's been over two weeks. Are you still working on this issue? Do you need assistance?

**Comment by LALITASAMANTA** [comment]
@ls I am interested in taking of issues on, i found the doc through friend

**Comment by SSwiniarski** [comment]
@ladimoe1 Because of inactivity I am unassigning you from this issue.

**Comment by SSwiniarski** [comment]
@LALITASAMANTA You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@LALITASAMANTA It's been two weeks. Are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@LALITASAMANTA this is being unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
Closing and reposting due to inability to unlink closed PR.
