### ISSUE TITLE
[Concept Entry] Go: Interfaces

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1503]
### Reason/inspiration (optional)

We would like a new term entry for [Go](https://www.codecademy.com/resources/docs/go) about Interfaces.

The entry should go in a new file in docs/content/go/concepts/interfaces/interfaces.md

The entry should

Describe what interfaces are and their relationship to types.
Show a type implementing an interface.
Have a syntax section illustrating an interface structure with a \`\`\`pseudo code block.
Have an example showing an interface in use with a \`\`\`go code block.
Have a runnable codebyte example in a \`\`\`codebyte/golang block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Pavan-Nambi** [comment]
hey i would like to work on this

**Comment by SSwiniarski** [comment]
@Pavan-Nambi you've been assigned!

**Comment by SSwiniarski** [comment]
@Pavan-Nambi, it's been over two weeks. Are you still working on this issue. Do you need any assistance?

**Comment by Pavan-Nambi** [comment]
hey @SSwiniarski  apologies for delay , if no one requests for assignment of this by friday i will complete this on saturday, forgot abt this

**Comment by SSwiniarski** [comment]
@Pavan-Nambi, are you going to create a PR? Let me know.

**Comment by Pavan-Nambi** [comment]
> @Pavan-Nambi, are you going to create a PR? Let me know.

yeah will do shortly , have to start writting...
