### ISSUE TITLE
[Concept Entry] Go: Composition

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1504]
### Reason/inspiration (optional)

We would like a new term entry for [Go](https://www.codecademy.com/resources/docs/go) about composition.

The entry should go in a new file in docs/content/go/concepts/composition/composition.md

The entry should

Describe what composition is and how it differs from inheritance.
Show a struct implementing composition.
Have a syntax section illustrating composition with a \`\`\`pseudo code block.
Have an example showing composition in use with a \`\`\`go code block.
Have a runnable codebyte example in a \`\`\`codebyte/golang block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by gracekishino** [comment]
Please can I work on this issue?

**Comment by ZeraAI** [comment]
I have went ahead and started working on this issue. I am requesting assignee status so I can submit my work

**Comment by gracekishino** [comment]
@ZeraAI OK! I will work on another issue :)

**Comment by ZeraAI** [comment]
> 

Thank you very much Grace. Have a lovely day

**Comment by SSwiniarski** [comment]
@ZeraAI I've assigned you, but next time ask to be assigned an issue before you start working on it.

**Comment by ZeraAI** [comment]
> 

My bad! Thank you very much for assigning me :) Have a lovely day
