### ISSUE TITLE
[Term Entry] SwiftUI View Modifier: `.scaledToFill()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1508]
### Reason/inspiration (optional)

Please write a new entry under: content/swiftui/concepts/viewmodifier/terms/ about the modifier `.scaledToFill()` in Swift.

A "Syntax" section with pseudo code snippet.
An "Example" section with a swift code snippet and image to accompany. Images should go in the media/ folder.

To get started with the PR and entry file:

Under content/swiftui/concepts/viewmodifier/terms/, create a new folder called `scaledToFill`. Then create a new file called `scaledToFill.md` under content/swiftui/concepts/viewmodifier/terms/`scaledToFill`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Fritzeous** [comment]
hello i would like to work on this issue

**Comment by Fritzeous** [comment]
Thank you very much  for the assignment im enrolled in the codecademy ios
developer class and curretly in the github chapter .

**Comment by SSwiniarski** [comment]
@Fritzeous it's been two weeks. Are you still working on this issue? Do you need any assistance?

**Comment by Fritzeous** [comment]
Yes, I am working on it.
Had a few personal issues that set me back but i believe i ll finish it
soon as posible . Thank you for the help offer i ll let  you know if i need
assistance .

**Comment by SSwiniarski** [comment]
@Fritzeous, It's been another two weeks. Are you still working on this?

**Comment by Fritzeous** [comment]
Yes, I am working on it.

Στις Κυρ 26 Φεβ 2023 στις 10:45 μ.μ., ο/η SSwiniarski <
***@***.***> έγραψε:

**Comment by SSwiniarski** [comment]
@Fritzeous at this point it's been over a month. If we don't see a PR in another week, we'll release this issue for someone else to work on it.

**Comment by SSwiniarski** [comment]
@Fritzeous It's been too long without a PR. I'm going to unassign you so someone else can work on this.

**Comment by Fritzeous** [comment]
Ok, thanks.

**Comment by JaredDanielJones** [comment]
Hi, I'd like to work on this issue.

**Comment by yangc95** [comment]
@JaredDanielJones You're assigned! You can check out the [[Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md)](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

> See [[Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md)](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the  [[Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md)](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

After creating a PR, maintainer(s) (with the collaborater label) will add in comments/suggestions to address any revisions prior to approving.
