### ISSUE TITLE
[Term Entry] SwiftUI View Modifier: `.foregroundColor()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1509]
### Reason/inspiration (optional)

Please write a new entry under: content/swiftui/concepts/viewmodifier/terms/ about the modifier `.foregroundColor()` in Swift.

A "Syntax" section with pseudo code snippet.
An "Example" section with a swift code snippet and image to accompany. Images should go in the media/ folder.

To get started with the PR and entry file:

Under content/swiftui/concepts/viewmodifier/terms/, create a new folder called `foregroundColor`. Then create a new file called `foregroundColor.md` under content/swiftui/concepts/viewmodifier/terms/`foregroundColor`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by beamthecode** [comment]
Hello, can I work on this issue? 

I have already forked the repository, cloned it, and created a new branch.

Thank you!

**Comment by Dusch4593** [comment]
Hi, @beamthecode! 👋🏻 Thanks for your interest in contributing to Codecademy Docs! 🚀

I've assigned this issue to you 😄

Just curious, how did you happen to learn about Docs and about contributing to it?

**Comment by SSwiniarski** [comment]
@beamthecode, it's been two weeks. Are you still working on this issue? Do you need any assistance?

**Comment by beamthecode** [comment]
> @beamthecode, it's been two weeks. Are you still working on this issue? Do you need any assistance?

I have the files ready to go. This is my first time cloning a repository and contributing to a project. I am working on moving my files from the local branch I created to the forked branch in GitHub so that I can do a pull request. Sort of having a tough time with it. Any advice would be great, I am going to work on this this afternoon, so hopefully I get it all ready and get the pull request done today.

**Comment by beamthecode** [comment]
> @beamthecode, it's been two weeks. Are you still working on this issue? Do you need any assistance?

My main issue is that I do not have an upstream branch assigned to the branch I created. I am working to set the remote repository as the upstream branch, but I am having an issue with authenticating this.

**Comment by yangc95** [comment]
@beamthecode Great work with creating the PR on your end!
