### ISSUE TITLE
[Term Entry] SwiftUI View Modifier: `.border()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1511]
### Reason/inspiration (optional)

Please write a new entry under: content/swiftui/concepts/viewmodifier/terms/ about the modifier `.border()` in Swift.

A "Syntax" section with pseudo code snippet.
An "Example" section with a swift code snippet and image to accompany. Images should go in the media/ folder.

To get started with the PR and entry file:

Under content/swiftui/concepts/viewmodifier/terms/, create a new folder called `border`. Then create a new file called `border.md` under content/swiftui/concepts/viewmodifier/terms/`border`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by danieltorres4** [comment]
Hello, I'm Daniel. I'm interested in working on this issue. Can I work on it?
Thank you!

**Comment by KTom101** [comment]
@danieltorres4 You are now assigned to this! Please don't hesitate to let us know if you need any help and feel free to look at the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for guidance.

Also, may I know how did you come across the Codecademy Docs repo?

**Comment by SSwiniarski** [comment]
@danieltorres4 it's been two weeks, are you still working on this issue? Do you need any assistance?

**Comment by SSwiniarski** [comment]
@danieltorres4, because of the inactivity on this PR I am going to unassign you so someone else can work on this.

**Comment by matthewogtong** [comment]
Can I be assigned this issue?

**Comment by SSwiniarski** [comment]
@matthewogtong You've been assigned!
