### ISSUE TITLE
[Term Entry] SwiftUI View Modifier: `.tracking()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1512]
### Reason/inspiration (optional)

Please write a new entry under: content/swiftui/concepts/viewmodifier/terms/ about the modifier `.tracking()` in Swift.

A "Syntax" section with pseudo code snippet.
An "Example" section with a swift code snippet and image to accompany. Images should go in the media/ folder.

To get started with the PR and entry file:

Under content/swiftui/concepts/viewmodifier/terms/, create a new folder called `tracking`. Then create a new file called `tracking.md` under content/swiftui/concepts/viewmodifier/terms/`tracking`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by cslylla** [comment]
I would like to work on this issue.

**Comment by yangc95** [comment]
@cslylla assigned! 😊

**Comment by SSwiniarski** [comment]
@cslylla It's been two weeks. Are you still working on this issue? Do you need any assistance?

**Comment by cslylla** [comment]
@SSwiniarski Yes, I am still working on it. Is it okay if I take a few more days to finalize it?
