### ISSUE TITLE
[Term Entry] HTML Attributes: `title`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1529]
### Reason/inspiration (optional)

Please write a new entry under: content/html/concepts/attributes/terms/ about the global attribute `title` in HTML.

A "Syntax" section with pseudo code snippet.
An "Example" section with a HTML code snippet. If an image is added, the file should go in the `media/` folder.

To get started with the PR and entry file:

Under content/html/concepts/attributes/terms/, create a new folder called `title`. Then create a new file called `title.md` under content/html/concepts/attributes/terms/`title`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by BigShuff** [comment]
Hello could I work on this please it's not flagged as a good first issue, but not sure if anything else is going to come up anyway, so I might as well give this a go if that's ok.
Kind regards @BigShuff

**Comment by KTom101** [comment]
@BigShuff Sure you can, I have assigned you! Feel free to take a look at the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) or reach out to us if you need any help.

Also, how did you come across the Codecademy Docs repo?

**Comment by BigShuff** [comment]
Hi again How did I come across the Codecademy Docs repo? Simply by doing the Git & GitHub course, although I am also taking the full stack web course. Quite enjoying myself. I have submitted a pull request now (so if you see one of your work mates in fits of laughter) you will know what is going on.

**Comment by KTom101** [comment]
@BigShuff So glad to hear! Thank you for deciding to contribute 😁

**Comment by SSwiniarski** [comment]
Cleared assignment because original assignee did not have the time to finish PR.

**Comment by cslylla** [comment]
I can create this entry!

**Comment by PetrZajkasWebdesign** [comment]
Hi, can I contribute on this one please?

**Comment by PetrZajkasWebdesign** [comment]
Hi, thanks for reply. Will do.
