### ISSUE TITLE
[Term Entry] HTML Attributes: `dir`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1530]
### Reason/inspiration (optional)

Please write a new entry under:  content/html/concepts/attributes/terms/ about the global attribute `dir` in HTML.

A "Syntax" section with pseudo code snippet.
An "Example" section with a HTML code snippet. If an image is added, the file should go in the `media/` folder.

To get started with the PR and entry file:

Under content/html/concepts/attributes/terms/, create a new folder called `dir`. Then create a new file called `dir.md` under content/html/concepts/attributes/terms/`dir`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by RobinLilly** [comment]
I would like to be assigned this task please.

**Comment by KTom101** [comment]
@RobinLilly I've assigned you! Please don't hesitate to let us know if you need any help. The [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) is also a good resource for additional information on contributing.

May I ask how did you come across the Codecademy Docs repo?

**Comment by RobinLilly** [comment]
Codecademy course - Learn Git and Github
I'm working toward the Front end Engineer career path.
Thanks for assigning me.

**Comment by RobinLilly** [comment]
One question though:
The instructions say:
"Under content/html/concepts/attributes/terms/, create a new folder called dir. Then create a new file called dir.md under content/html/concepts/attributes/terms/dir"

There is no "terms" folder within attributes.
"Terms" is located within the following path: content/html/concepts/elements/terms
Will I be able to create the new "terms" file within "attributes" when I contribute my entry?

**Comment by KTom101** [comment]
@RobinLilly That's a great question! In this case, since there aren't any term entries yet, a "terms" folder must be created inside the "attributes" folder.  Once the "terms" folder is created then you can create another new folder named "dir" containing the "dir.md" file and then place the folder inside the "terms" folder.

I hope this makes sense! If anything, we can guide you further or change the file placement for you once you make the pull request.
