### ISSUE TITLE
[Term Entry] HTML Attributes: `class`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1531]
### Reason/inspiration (optional)

Please write a new entry under:  content/html/concepts/attributes/terms/ about the global attribute `class` in HTML.

A "Syntax" section with pseudo code snippet.
An "Example" section with a HTML code snippet. If an image is added, the file should go in the `media/` folder.

To get started with the PR and entry file:

Under content/html/concepts/attributes/terms/, create a new folder called `class`. Then create a new file called `class.md` under content/html/concepts/attributes/terms/`class`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Pavan-Nambi** [comment]
hey can i work on this? @yangc95

**Comment by Cesarcas1958** [comment]
I would like to work on this

**Comment by Pavan-Nambi** [comment]
hey just to avoid confusion when u assign,
 he can take this

**Comment by KTom101** [comment]
@Pavan-Nambi Thank you for your comment, I will go ahead and assign this to @Cesarcas1958 since they are not assigned to any other issues yet.

**Comment by KTom101** [comment]
@Cesarcas1958 I have assigned you to this issue. Please don't hesitate to let us know if you need any help and feel free to look at the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for guidance.

Also, may I ask how did you come across the Codecademy Docs repo?

**Comment by Cesarcas1958** [comment]
Dear Ktom101

Thanks for assigning me this issue. However, I need to ask you for a few
days (probably 4 days) to start working on that because my mother in-law
has been hospitalized and my wife and I are the people who take care of
her. This problem has my head out of focus and I would not perform my best
now. Sorry for the inconvenience. If there is any problem please let me know

Thanks

Cesarcas1958

**Comment by KTom101** [comment]
@Cesarcas1958 Sorry to hear! That timeframe should be fine. We usually ask for some progress within 5-7 days. We can check back in if you're unable to do so by then.

**Comment by Cesarcas1958** [comment]
Thank you for understanding, my mother in-law is 93 years old so anything
can happen. But I hope to be able to contribute. I will let you know how it
goes

Cesarcas1958

**Comment by Cesarcas1958** [comment]
Dear KTom101

I am trying to get back to work but it has been difficult with may mother
in-law´s condition. However, I would like to ask you for some guidance to
start working on my assigned issue. Please if you could send me the steps I
should follow I would appreciate it. I will try my best with the little
time I have available. Thanks in advance.

**Comment by KTom101** [comment]
@Cesarcas1958 Thanks for reaching out. I've included a short guideline on how to go about this, below. Please, let us know if there are any questions or if you change your mind about contributing. We do understand if you are unable to contribute at this time and will welcome you back at a later time if you decide to do so.

1. Start by creating the markdown file called `class.md`. Inside the file add an explanation of what the `class` attribute is. Then there should be two subheadings (##) sections. One for showing a general syntax, and another for giving a concrete example of what it would look like when used inside some code.
2. Add the file to the correct position within the file directory. You can take a look at how the files are organized under [content](https://github.com/Codecademy/docs/tree/main/content). Just note for this article in particular there aren't currently any term entries under [HTML|Attributes](https://github.com/Codecademy/docs/tree/main/content/html/concepts/attributes) right now so you will have to create a `terms` folder inside the `attributes` folder. Then inside the `terms` folder create a new folder called `class` and add the `class.md` file you wrote into this folder. In the end, the file path should look like `content/html/concepts/attributes/terms/class/class.md`. Do your best with the file placement, I know it can sound a little confusing. We can always assist you further with this part after you make the pull request, which is the next step.
3. Make your pull request. Please note it is important to make and commit your changes on a separate branch from your `main` branch. For more on making the pull request, you can check out this [article](https://dev.to/codecademy/how-to-contribute-to-codecademy-docs-1a77) which is also listed in the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md).

**Comment by Cesarcas1958** [comment]
Dear KTom101,

I have a question for you. I cloned the Codecademy/docs repository but I had a problem with the hard drive of my computer and lost that information. Is there any way a could clone that again? Thanks 

Enviado desde mi iPhone

**Comment by KTom101** [comment]
@Cesarcas1958 Yes, you can clone your forked repository again using `git clone`. You can follow steps off GitHub [here](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository). There is also an entry for it in Codecademy Docs [here](https://www.codecademy.com/resources/docs/git/clone).

**Comment by Cesarcas1958** [comment]
Awesome, thanks!

Thanks for the info

**Comment by Cesarcas1958** [comment]
Dear KTom101,

I started working on the issue. I have created all folders needed and also created the md file requested; however, I made a mistake with its name. I named the file "classes.md". But I suppose it is not a big deal. Now could you give instructions about what's next and how to do a pull request. Thanks

**Comment by KTom101** [comment]
@Cesarcas1958 You can go over steps within the Contribution Guide, particularly [here](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md#:~:text=How%20do%20I%20submit%20a%20Pull%20Request%20(PR)%3F). There are additional resources linked within the text so be sure to view those for more in-detail information. 

Concerning the file name, you can just rename it to `class.md`  before making the pull request. You can rename it like you would any other file.

**Comment by Cesarcas1958** [comment]
I made a pull request

**Comment by yangc95** [comment]
@Cesarcas1958 I see your [branch](https://github.com/Cesarcas1958/docs/tree/new1) but no PR has been opened for it. You can read about [creating a PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request). Let us know if you run into any issues 🙂 

cc: @KTom101

**Comment by Cesarcas1958** [comment]
I will check and try again 

Enviado desde mi iPhone

**Comment by Cesarcas1958** [comment]
I did it again. I hope it is right this time

**Comment by Cesarcas1958** [comment]
I made changes in class.md file as requested but I am having trouble to push the changes. Could you give some advice?
This is the message I am getting:
PS C:\Users\César Castellanos\Documents\GitHub\docs\content\html\concepts\attributes\terms\class> git pull origin new1
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by KTom101** [comment]
@Cesarcas1958 Did you add a remote repository before using `origin`?

`git remote add origin https://github.com/Cesarcas1958/docs.git`

You should also set an upstream too, like this:

`git remote add upstream https://github.com/Codecademy/docs.git` 

You can read more about it in the Additional Resource from the Contribution Guide on How to Contribute to Codecademy Docs [under Step 4](https://dev.to/codecademy/how-to-contribute-to-codecademy-docs-1a77#:~:text=The%20origin%20remote%20is%20the%20connection%20between%20your%20local%20repo%20and%20the%20remote%20repo.).

**Comment by KTom101** [comment]
@Cesarcas1958 I don't think I answered your question correctly, pardon my confusion. I'm re-reading your comment and I see you're trying to `git pull origin new1`. What are you trying to pull?

**Comment by Cesarcas1958** [comment]
New pull request done

**Comment by yangc95** [comment]
Hey @Cesarcas1958! Just checking in to see how this is going. I don't see the PR associated for this issue and was wondering if you needed any additional resources or help. I do see your successfully created `classes` branch but no class term was created in the [terms folder](https://github.com/Cesarcas1958/docs/tree/classes/content/html/concepts/attributes/terms).

cc: @KTom101

**Comment by Cesarcas1958** [comment]
Hello, I thought I made the PR but it didn’t go through. I was trying to do it again but I don’t know what I did that I lost the file I created. I was working on the terminal and I really don’t know what happened. Is there any way to recover that file? I did not commit anything today. If I cannot recover the file I would have to rewrite it again. Please let me know if you have any advice. Thanks 

Enviado desde mi iPhone

**Comment by KTom101** [comment]
@Cesarcas1958 Do you see something that looks like the photo below when you go to your forked repository on GitHub? You probably never actually opened the PR. If it's there you have to press the green button and follow the instructions. 

![image](https://user-images.githubusercontent.com/40783324/221085878-48cd145c-99b4-4be2-85d6-2311ad025b74.jpeg)

**Comment by yangc95** [comment]
I'd also like to add on that I do see the previously closed [PR](https://github.com/Codecademy/docs/pull/1625/files). Feel free to refer back to that and for the next PR you submit, let's keep it open 👍🏻
