### ISSUE TITLE
[Term Entry] HTML Attributes: `id`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1532]
### Reason/inspiration (optional)

Please write a new entry under:  content/html/concepts/attributes/terms/ about the global attribute `id` in HTML.

A "Syntax" section with pseudo code snippet.
An "Example" section with a HTML code snippet. If an image is added, the file should go in the `media/` folder.

To get started with the PR and entry file:

Under content/html/concepts/attributes/terms/, create a new folder called `id`. Then create a new file called `id.md` under content/html/concepts/attributes/terms/`id`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by lhotovy** [comment]
Hello, could I work on this one?

**Comment by KTom101** [comment]
@lhotovy Thanks for your interest in contributing! I've assigned you. Please feel free to check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional guidance or reach out to us if you need any help.

Also, may I ask how you came across the Codecademy Docs repo?

**Comment by lhotovy** [comment]
@KTom101 Sure, I will do that.
