### ISSUE TITLE
[Term Entry] HTML Attributes: `style`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1533]
### Reason/inspiration (optional)

Please write a new entry under:  content/html/concepts/attributes/terms/ about the global attribute `style` in HTML.

A "Syntax" section with pseudo code snippet.
An "Example" section with a HTML code snippet. If an image is added, the file should go in the `media/` folder.

To get started with the PR and entry file:

Under content/html/concepts/attributes/terms/, create a new folder called `style`. Then create a new file called `style.md` under content/html/concepts/attributes/terms/`style`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by M3RF3R** [comment]
Hi! I'm doing the Git course in Codeacademy and I'd like to contribute. Is it possible even if it's not flagged as a "first good issue"? I've been looking in the repo and can't find the termns directory inside attributes, should I just create the file style inside attributes?

**Comment by KTom101** [comment]
@M3RF3R Thank you for your interest in contributing and we're happy you've come across the docs repo! I have gone ahead and assigned you. 

Please don't hesitate to let us know if you need any help and feel free to look at the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for guidance.

**Comment by M3RF3R** [comment]
Thanks! I'll start workin right away!

**Comment by Pinto2291** [comment]
Hi everyone, I'm currently doing the learn Git and Github course in Codecademy and I am right now working on the Codecademy Entry project, I would like to work with this issue, please let me know if it is possible so I can complete my journey to become a Front End developer, thank you

**Comment by KTom101** [comment]
@Pinto2291 This issue is already assigned and a PR has been opened. Please look for an [issue](https://github.com/Codecademy/docs/issues) to work on that is not labeled "claimed".

**Comment by Pinto2291** [comment]
Sure I will 😊 thanks for letting me know

**Comment by KTom101** [comment]
@Pinto2291 You're welcome!
