### ISSUE TITLE
[Term Entry] Java Strings: `.equalsIgnoreCase()` Method

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1540]
### Reason/inspiration (optional)

Add a new term entry under the [Java: Strings](https://www.codecademy.com/resources/docs/java/strings) concept. This entry should include:

- An explanation of the method.
- A "Syntax" section with a ```pseudo code snippet showing the general syntax.
- An "Example" section with a ```java code snippet showing how it works.

A markdown file named "equalsIgnoreCase.md" should be added to a folder named "equalsIgnoreCase" and placed in the terms folder located -> `content/java/concepts/strings/terms`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by SancHard** [comment]
Hi, I would like to be assigned to this issue for the "Learn git & GitHub" certification. I already forked and cloned the docs repository onto my local device, and tried to sync it through the page and tried to use pull command via Git Bash, so I made sure that it is up to date as well.

**Comment by KTom101** [comment]
@SancHard You're assigned! Please don't hesitate to let us know if you need any help. The [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) is also a good resource for additional information on contributing.

**Comment by SancHard** [comment]
Thank you. After I got the notification, I started working on it and I believe I've did what was asked from me and submitted a pull request. However, I assume I have to approve my pull request? (workflow awaiting approval)

**Comment by KTom101** [comment]
@SancHard You don't have to worry about that. First-time contributors will need the workflow approved by a collaborator. This will be done some time during the review process.
