### ISSUE TITLE
[Term Entry] Java Strings: `.substring()` Method 

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1558]
### Reason/inspiration (optional)

Add a new term entry under the [Java: Strings](https://www.codecademy.com/resources/docs/java/strings) concept. This entry should include:

- An explanation of the method.
- A "Syntax" section with a ```pseudo code snippet showing the general syntax.
- An "Example" section with a ```java code snippet showing how it works.

A markdown file named "substring.md" should be added to a folder named "substring" and placed in the terms folder located under `content/java/concepts/strings/terms`

### Entry Type (select all that apply)

New Topic Entry, New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by haroon26** [comment]
Hello! I'm willing to contribute. Can you please assign this issue to me?

**Comment by KTom101** [comment]
@haroon26 I've assigned you! Check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing and please don't hesitate to let us know if you need any help. 

Also, may I ask how did you come across the Codecademy Docs repo?

**Comment by haroon26** [comment]
Yes, actually I'm new to open source and so I was searching through "Good First Issue" label. That's how I found this repo.
Also, I will open a PR today. Thank you.

**Comment by itsarraj** [comment]
Hello sir ,
I am new to open source contribution.
I already know java , my tech stacks & tools includes C, C++ , Python , Java, JavaScript , HTML , CSS , SQL , Bootstrap, ReactJS, ExpressJS, NodeJS & Git . I need a little help from your side to contribute to these amazing projects.
