### ISSUE TITLE
[Term Entry] Java Strings: `.toUpperCase()` Method

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1559]
### Reason/inspiration (optional)

Add a new term entry under the [Java: Strings](https://www.codecademy.com/resources/docs/java/strings) concept. This entry should include:

- An explanation of the method.
- A "Syntax" section with a ```pseudo code snippet showing the general syntax.
- An "Example" section with a ```java code snippet showing how it works.

A markdown file named "toUpperCase.md" should be added to a folder named "toUpperCase" and placed in the terms folder located under `content/java/concepts/strings/terms`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by IskakovIZh** [comment]
Hello! I would like to be assigned to this issue for the "Learn git & GitHub" certification.

**Comment by KTom101** [comment]
@IskakovIZh Thanks for your interest in contributing, I've assigned you! Check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing and please don't hesitate to let us know if you need any help!
