### ISSUE TITLE
[Term Entry] Java Strings: `.toLowerCase` Method

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1560]
### Reason/inspiration (optional)

Add a new term entry under the [Java: Strings](https://www.codecademy.com/resources/docs/java/strings) concept. This entry should include:

- An explanation of the method.
- A "Syntax" section with a ```pseudo code snippet showing the general syntax.
- An "Example" section with a ```java code snippet showing how it works.

A markdown file named "toLowerCase.md" should be added to a folder named "toLowerCase" and placed in the terms folder located under content/java/concepts/strings/terms

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by M3RF3R** [comment]
Hi! I'm practicting with git and have already started doing a contributing to the codeacademy docs. If its ok, I'd like to be assigned this one too. Thanks

**Comment by KTom101** [comment]
@M3RF3R Sure! I have assigned you!

**Comment by M3RF3R** [comment]
Great! Thanks! I'll start ASAP!
