### ISSUE TITLE
[Edit] Kotlin: HashMaps

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1561]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Please edit the [HashMaps](https://www.codecademy.com/resources/docs/kotlin/hashmap) entry under:  content/kotlin/concepts/hashmap/hashmap.md about hash maps in Kotlin.

Please add two headings after Syntax called "Accessing Items" and "Adding Items." Under both heading, include code block examples (Example heading is not required) with supporting text. 

See [Java HashMap](https://www.codecademy.com/resources/docs/java/hashmap) as an example.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by YanisaHS** [comment]
Hi! Could I be assigned to this one? 🥳

**Comment by KTom101** [comment]
@YanisaHS Sure, I've assigned you! 😁

**Comment by SSwiniarski** [comment]
@YanisaHS, It's been two weeks. Are you still working on this issue? Do you need any assistance?

**Comment by YanisaHS** [comment]
@SSwiniarski Hey! Sorry about that!!! Could you actually unassign this issue from me? Thank you for checking in! 🥳

**Comment by SSwiniarski** [comment]
@YanisaHS no problem. I'll release this so someone else can work on it.

**Comment by shdsgm** [comment]
Helo Christine @yangc95! I'd like to claim this issue to practice my GitHub skills. Best regards, Oleg.

**Comment by SSwiniarski** [comment]
@shdsgm you've been assigned.
