### ISSUE TITLE
[Bug/Error] Subject: Dead Link in SQL Joins

### ISSUE THREAD

**Issue by sgadiyar06** [Codecademy/docs#1562]
### Actual Behavior

The doc for [SQL Joins](https://www.codecademy.com/resources/docs/sql/joins) contains several links explaining subtopics in a more detailed manner. The [outer joins](https://www.codecademy.com/resources/docs/sql/commands/outer-join) hyperlink in the 'Outer Joins' section is not working and is giving a 404-error message.

### Expected Behavior

The link should not give an error message and should direct to the correct [outer joins](https://www.codecademy.com/resources/docs/sql/commands/full-outer-join) webpage.

### On what browser(s) are you seeing the problem?

Microsoft Edge

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by haroon26** [comment]
Hello @sgadiyar06! After exploring the docs, I have found that there is no explicit outer-join file in the docs. After seeing links given in `joins.md` file, I have noticed that link for `outer-join` and `full-outer-join` are same, and they are wrong. Are they both supposed to point at `full-outer-join`? If that is the case then you can assign this to me and I will fix that. Thank you!

**Comment by KTom101** [comment]
@haroon26 I've gone ahead and assigned you.  Looking at this, I recommend just correcting the link for `FULL OUTER JOIN` to `full-outer-join` and removing the linkage from `OUTER JOIN` and just placing it in backticks. This way we're not linking out twice anymore and `OUTER JOIN` is in backticks like the other joins.
