### ISSUE TITLE
[Term Entry] HTML Element: `<p>`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1566]
### Reason/inspiration (optional)

EDIT: Move existing [Paragraphs](https://www.codecademy.com/resources/docs/html/paragraphs) to Elements terms.

lease write a new entry under:  content/html/concepts/elements/terms/ about the `<p>` tag in HTML.

A "Syntax" section with pseudo code snippet.
An "Example" section with a HTML code snippet. If an image is added, the file should go in the `media/` folder.

To get started with the PR and entry file:

Under content/html/concepts/elements/terms/, create a new folder called `p`. Then create a new file called `p.md` under content/html/concepts/attributes/terms/`p`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by shyamtawli** [comment]
Hey @yangc95 Please assign me I want work on it.

**Comment by Arpit-mohankar** [comment]
hey @yangc95 can i contribute to it?

**Comment by JaceInglis** [comment]
Hey @yangc95 I'm currently working on the Git & Github course in Codecademy so I can start my new job. Any chance I can be assigned to this issue?

**Comment by KTom101** [comment]
@shyamtawli You're officially assigned. May I know how did you discover the Codecademy Docs repo?

**Comment by KTom101** [comment]
@Arpit-mohankar @JaceInglis This has been assigned, please take a look at the [Issues Tab](https://github.com/Codecademy/docs/issues) to find an unclaimed issue. Issues are typically assigned first-come-first-served.

**Comment by shyamtawli** [comment]
@KTom101 Thanks and I have made a PR,. please check it.

Searching for issues and got to know about it.

**Comment by rubenm25** [comment]
Hey! Can I contribute to this issue?

**Comment by KTom101** [comment]
@rubenm25 This issue is already assigned and is almost about done. I've assigned you to the [other issue](https://github.com/Codecademy/docs/issues/1595) you inquired about.
