### ISSUE TITLE
[Term Entry] SwiftUI View Modifier: `.kerning()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1567]
### Reason/inspiration (optional)

Please write a new entry under: content/swiftui/concepts/viewmodifier/terms/ about the modifier `.kerning()` in Swift.

A "Syntax" section with pseudo code snippet.
An "Example" section with a Swift code snippet and image to accompany. Images should go in the media/ folder.

To get started with the PR and entry file:

Under content/swiftui/concepts/viewmodifier/terms/, create a new folder called `kerning`. Then create a new file called `kerning.md` under content/swiftui/concepts/viewmodifier/terms/`kerning`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by gracekishino** [comment]
Please can I work on this issue?

**Comment by yangc95** [comment]
@gracekishino Sure! Thanks for looking into this one 🙂
