### ISSUE TITLE
[Term Entry] SwiftUI View Modifier: `.keyboardType()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1570]
### Reason/inspiration (optional)

Please write a new entry under: content/swiftui/concepts/viewmodifier/terms/ about the modifier `.keyboardType()` in Swift.

A "Syntax" section with pseudo code snippet.
An "Example" section with a Swift code snippet and image to accompany. Images should go in the media/ folder.

To get started with the PR and entry file:

Under content/swiftui/concepts/viewmodifier/terms/, create a new folder called `keyboardType`. Then create a new file called `keyboardType.md` under content/swiftui/concepts/viewmodifier/terms/`keyboardType`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Digital-Brendan** [comment]
Hey, can I be assigned to this please? Thanks :)

**Comment by yangc95** [comment]
@Digital-Brendan Assigned! Nice to have you on the Codecademy Docs repo ☺️
