### ISSUE TITLE
[Term Entry] SwiftUI View Modifier: `.overlay()`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1571]
### Reason/inspiration (optional)

Please write a new entry under: content/swiftui/concepts/viewmodifier/terms/ about the modifier `.overlay()` in Swift.

A "Syntax" section with pseudo code snippet.
An "Example" section with a Swift code snippet and image to accompany. Images should go in the media/ folder.

To get started with the PR and entry file:

Under content/swiftui/concepts/viewmodifier/terms/, create a new folder called `overlay`. Then create a new file called `overlay.md` under content/swiftui/concepts/viewmodifier/terms/`overlay`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by nickschelle** [comment]
Hello! I can work on this.

**Comment by KTom101** [comment]
@nickschelle You're assigned! Check out the [[Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md)](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing and please don't hesitate to let us know if you need any help. 

Also, may I ask how did you come across the Codecademy Docs repo?

**Comment by nickschelle** [comment]
I'm currently taking a few of your courses. One of the assignments for the git/github course is contributing to this guide. I may take a bit of time to work on this.

**Comment by KTom101** [comment]
@nickschelle Good to know! So you know we typically ask to have some sort of progress within 5-7 days. We can check back in then if you haven't made any progress.
