### ISSUE TITLE
[Term Entry] Pandas DataFrame: `.sort_values()`

### ISSUE THREAD

**Issue by caupolicandiaz** [Codecademy/docs#1575]
### Reason/inspiration (optional)

Let's write a new entry about the .sort_values() DataFrame method (in pandas).

Folder/file structure: content/pandas/dataframe/sort-values/sort-values.md

Make sure to include the following sections:

A "Syntax" section with a ```pseudo code snippet.
An "Example" section with a ```py code snippet.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by alespros** [comment]
Hi, I'm doing the _Contributing to the Codecademy Docs Repository_ project from the _Introduction to Open Source_ course. Could I be assigned to this? Thanks!

**Comment by caupolicandiaz** [comment]
@alespros You're all set!
