### ISSUE TITLE
[Term Entry] Pandas DataFrame: `.apply()`

### ISSUE THREAD

**Issue by caupolicandiaz** [Codecademy/docs#1577]
### Reason/inspiration (optional)

 Let's write a new entry about the .apply() DataFrame method (in pandas).

Folder/file structure: content/pandas/dataframe/apply/apply.md

Make sure to include the following sections:

A "Syntax" section with a ```pseudo code snippet.
An "Example" section with a ```py code snippet.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by kalebaer** [comment]
Hey, I am currently doing the "Learn Git & GitHub" course on codecademy and was wondering if I could be assigned this issue? Thanks a lot!

**Comment by caupolicandiaz** [comment]
@kalebaer You're assigned!

**Comment by SSwiniarski** [comment]
@kalebaer, It's been two weeks. Are you still working on this issue? Do you need any assistance?

**Comment by SSwiniarski** [comment]
@kalebaer, because of the inactivity, I am unassigning you so someone else can work on this.

**Comment by SSwiniarski** [comment]
@MargaretChenXiaoyue You've been assigned. Check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for more info on contributing.

**Comment by MargaretChenXiaoyue** [comment]
A pull request submitted. waiting for review

**Comment by carlosnkd** [comment]
Hi, can I get assigned to this? Working on the Learn Git and Github course

**Comment by SSwiniarski** [comment]
@carlosnkd This issue has already been assigned and has a PR issued for it. If you want to claim an issue, look for one that is unassigned and does not have the "claimed" label.
