### ISSUE TITLE
[Term Entry] Java Strings: `.getChars()` Method

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1583]
### Reason/inspiration (optional)

Add a new term entry under the [Java: Strings](https://www.codecademy.com/resources/docs/java/strings) concept. This entry should include:

- An explanation of the method.

- A "Syntax" section with a ```pseudo code snippet showing the general syntax.

- An "Example" section with a ```java code snippet showing how it works.

A markdown file named "getChars.md" should be added to a folder named "getChars" and placed in the terms folder located under content/java/concepts/strings/terms

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by njaroon** [comment]
I would like to work on this topic  for my Codecademy project.

**Comment by KTom101** [comment]
@njaroon You're good to go! Check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for more on contributing.

Also, how did you come across the Codecademy Docs repo?

**Comment by njaroon** [comment]
## Title: How to use Java Strings
## Description: Defining what Java strings are. Instructions on how to use Java strings. 
## Tag: Java Strings
## Subject: Java Strinfa
## Catalog Content: Learning how to use Java
Java Strings

In Java code, strings are variables. The information in Java Strings are bound by quotation marks. Java strings are objects that can perform certain functions. Java strings can be used to find the length of a certain text. Java strings can also convert text from uppercase to lowercase and lowercase to uppercase. 

A major benefit for using Java Strings is to use memory effectively

An example of how to use Java strings to convert text from lowercase to uppercase is:

String txt = “neel aroon”
SystemOut.println(txt.toUpperCase());

The output would be NEEL AROON. 

An example of how to use Jave Strings to find the length of text is:

String txt =”NEEL AROON”
SystemOut.println(txt.length”()); 

The output would be 9.

**Comment by njaroon** [comment]
## Title: How to use Java Strings
## Description: Defining what Java strings are. Instructions on how to use Java strings. 
## Tag: Java Strings
## Subject: Java Strinfa
## Catalog Content: Learning how to use Java
Java Strings

In Java code, strings are variables. The information in Java Strings are bound by quotation marks. Java strings are objects that can perform certain functions. Java strings can be used to find the length of a certain text. Java strings can also convert text from uppercase to lowercase and lowercase to uppercase. 

A major benefit for using Java Strings is to use memory effectively

An example of how to use Java strings to convert text from lowercase to uppercase is:

String txt = “neel aroon”
SystemOut.println(txt.toUpperCase());

The output would be NEEL AROON. 

An example of how to use Jave Strings to find the length of text is:

String txt =”NEEL AROON”
SystemOut.println(txt.length”()); 

The output would be 9.

**Comment by KTom101** [comment]
@njaroon You will need to open a pull request for this not post the entry in the comments. It won't be reviewed otherwise.

**Comment by KTom101** [comment]
@njaroon When you push the changes, did you see a message with a link to GitHub? That link takes you to where you have to go to finish the pull request. 

You can also open up your forked repo and see if there is a notification at the top that has a button that says "Compare & pull request". It will take you to the same place the link would have. If you do see it press that, fill out the fields, and then click the "Create pull request" button. 

You can see more about this from the article linked in the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) called "How to Contribute to Codecademy Docs" [in step 5](https://dev.to/codecademy/how-to-contribute-to-codecademy-docs-1a77#5-create-pull-request-on-github).

**Comment by njaroon** [comment]
Hi
After I pushed the changes in command line, I got a message stating that
everything was up to date. WHen I checked my clone of Codeacademy on
github, it gives me the option to create a pull request. It doesn't show me
a button that says 'compare and pull request' like in step 5 of How to
COntribute to Codecademy Docs.

Neel

**Comment by KTom101** [comment]
@njaroon What you saw when you opened your forked repo is the same thing. Please continue with creating the pull request if you haven't already.

**Comment by njaroon** [comment]
Ok, set up the pull request.
Neel

**Comment by KTom101** [comment]
@njaroon I've taken a look at your forked repo and I see your branch and that you opened a pull request. However, you've pushed the changes to the wrong place. You did not push to the remote repo. 

The command `git remote -v` will show you if you have the remotes set up properly. If not, you will have to run these commands to configure your repo: 
`git remote add origin https://github.com/njaroon/docs.git`
`git remote add upstream https://github.com/Codecademy/docs.git`

You can run `git remote -v` to make sure it's set up properly after. Then, you would have to push the changes again.

**Comment by Anthem-glich** [comment]
Hi,

My name is Atharva and I'm interested in contributing to this project. I came across this issue for my CodeCademy Project and I believe I can help in resolving it.

Thank you for your time and consideration.

Best regards,
Atharva Srivastava

**Comment by KTom101** [comment]
@Anthem-glich Right now this issue is claimed and being worked on by @njaroon Please look for an [issue](https://github.com/Codecademy/docs/issues) that is not marked with the "claimed" label. Issues are assigned first-come-first-served 😁

**Comment by Anthem-glich** [comment]
Thanks for your time. I will try to find other issues which are not marked with "claimed" label 😅😊

**Comment by KTom101** [comment]
@njaroon Were you able to reconfigure your Git setup so you can push the pull request to the right place? Remember we can not review your file if you don't make a pull request and it needs to be under the [Pull requests tab](https://github.com/Codecademy/docs/pulls).

**Comment by njaroon** [comment]
Hi

I haven't been able to reconfigure the git set up so I can push the pull
request. Whenever I try to configure the repo using the commands you gave
me, I keep getting a message saying "fatal: not a git repository".

I think I didn't install the command line correctly on my chromebook

Neel

**Comment by KTom101** [comment]
@njaroon You would need to be in the directory of your local repo wherever you have it saved. You can change directories using "cd <your-path>"

**Comment by njaroon** [comment]
Hi

 I think I created the pull request.

Neel

**Comment by KTom101** [comment]
@njaroon I see it is open. All you have to do now is wait for a maintainer to review it.

**Comment by njaroon** [comment]
A couple of questions.

Should I use the add a file option from Codecademy's doc section on github?
After creating the file, should I use the editor option on github or an
editor on my own computer?
Neel

**Comment by KTom101** [comment]
@njaroon I do not recommend using the add a file option. I personally use the command line which is taught in the "Learn Git & GitHub" [course](https://www.codecademy.com/learn/learn-git). For editing, you can use any editor you want like [Visual Studio](https://code.visualstudio.com/docs/languages/markdown), just make sure the file is a markdown file with the `.md` extension.
