### ISSUE TITLE
[Term Entry] Java Strings: `.intern()` Method

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1585]
### Reason/inspiration (optional)

Add a new term entry under the [Java: Strings](https://www.codecademy.com/resources/docs/java/strings) concept. This entry should include:

- An explanation of the method.

- A "Syntax" section with a ```pseudo code snippet showing the general syntax.

- An "Example" section with a ```java code snippet showing how it works.

A markdown file named "intern.md" should be added to a folder named "intern" and placed in the terms folder located under content/java/concepts/strings/terms

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by penalus** [comment]
Hello again! I got assigned another issue I think will be easier for me to complete. If it is okey I would like to make this issue availeble again.

**Comment by SSwiniarski** [comment]
@penalus That's no problem. I'm unassigning you so someone else can work on this.

**Comment by redpepper-nag** [comment]
Hi, can I be assigned this issue

**Comment by yangc95** [comment]
@redpepper-nag Assigned 🙂

**Comment by SSwiniarski** [comment]
I've unassigned @redpepper-nag as the PR was abandoned.

**Comment by coolest98** [comment]
Hi! Can you assign me this isssue? Thanks!

**Comment by SSwiniarski** [comment]
@coolest98 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

Also see [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for styling tips.

After creating a PR, maintainer(s) (with the collaborater label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by coolest98** [comment]
Thanks! Working on it...
