### ISSUE TITLE
[Term Entry] Java Strings: `.isEmpty()` Method

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1586]
### Reason/inspiration (optional)

Add a new term entry under the [Java: Strings](https://www.codecademy.com/resources/docs/java/strings) concept. This entry should include:

An explanation of the method.

A "Syntax" section with a ```pseudo code snippet showing the general syntax.

An "Example" section with a ```java code snippet showing how it works.

A markdown file named "isEmpty.md" should be added to a folder named "isEmpty" and placed in the terms folder located under content/java/concepts/strings/terms

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by JamesLDeveloper** [comment]
Hi I'd like to do this one if that's ok?

I've been doing the learn git and github lessons and part of the project I'm working on is to update / create a Codecademy doc.

Thanks

**Comment by KTom101** [comment]
@JamesLDeveloper I've assigned you! Please don't hesitate to let us know if you need any help. The [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) has very helpful information on contributing.

**Comment by JamesLDeveloper** [comment]
Thanks, I'm trying to push my new entry to the Codecademy docs repo but it says remote: Permission to Codecademy/docs.git denied

**Comment by KTom101** [comment]
@JamesLDeveloper Do you mind telling me the steps or commands you did before getting to this message?

**Comment by JamesLDeveloper** [comment]
git push https://github.com/Codecademy/docs/

**Comment by JamesLDeveloper** [comment]
I've pushed it to my own forked repo now which seems to have allowed me to create a pull request

**Comment by KTom101** [comment]
@JamesLDeveloper Glad you figured out the solution. Remember to push to your forked repo in the future.
