### ISSUE TITLE
[Term Entry] Java Strings: `.join()` Method

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1587]
### Reason/inspiration (optional)

Add a new term entry under the [Java: Strings](https://www.codecademy.com/resources/docs/java/strings) concept. This entry should include:

An explanation of the method.

A "Syntax" section with a ```pseudo code snippet showing the general syntax.

An "Example" section with a ```java code snippet showing how it works.

A markdown file named "join.md" should be added to a folder named "join" and placed in the terms folder located under content/java/concepts/strings/terms

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by mehboobali98** [comment]
Hey. I'd like to work on this. Thanks!

**Comment by yangc95** [comment]
😄 @mehboobali98 Assigned! Is this your first assigned issue, and if so, how did you find out about the Docs repo?

**Comment by SSwiniarski** [comment]
@mehboobali98 It's been two weeks. Are you still working on this issue? Do you need any assistance?

**Comment by SSwiniarski** [comment]
@mehboobali98, because of the inactivity, I am unassigning you so someone else can work on this issue.

**Comment by majorx1134** [comment]
Hey there, I would like to work on this issue as it being a part of my Codecademy course.

**Comment by SSwiniarski** [comment]
@majorx1134, you're assigned.
