### ISSUE TITLE
[Term Entry] Java Strings: `.lastIndexOf()` Method

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1588]
### Reason/inspiration (optional)

Add a new term entry under the [Java: Strings](https://www.codecademy.com/resources/docs/java/strings) concept. This entry should include:

An explanation of the method.

A "Syntax" section with a ```pseudo code snippet showing the general syntax.

An "Example" section with a ```java code snippet showing how it works.

A markdown file named "lastIndexOf.md" should be added to a folder named "lastIndexOf" and placed in the terms folder located under content/java/concepts/strings/terms

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by jaymay1979** [comment]
Can you please assign this to me. Thank you.

**Comment by KTom101** [comment]
@jaymay1979 I've assigned you. Please note that we ask to have some sort of progress within 5-7 days. If any issues occur, please let us know.

**Comment by jaymay1979** [comment]
I renamed by base branch jay_main & made a local clone. I crated another local branch called lastIndexOf then pushed the changes I made locally to my origin jay_main repo. Should I create another PR?

**Comment by yangc95** [comment]
Good workflow! Another PR would be great 🙂
