### ISSUE TITLE
[Term Entry] Java Strings: `.subSequence()` Method

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1595]
### Reason/inspiration (optional)

Add a new term entry under the [Java: Strings](https://www.codecademy.com/resources/docs/java/strings) concept. This entry should include:

- An explanation of the method.

- A "Syntax" section with a ```pseudo code snippet showing the general syntax.

- An "Example" section with a ```java code snippet showing how it works.

A markdown file named "subSequence.md" should be added to a folder named "subSequence" and placed in the terms folder located under content/java/concepts/strings/terms

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by rubenm25** [comment]
Hey! Can I contribute to this issue?

**Comment by KTom101** [comment]
@rubenm25  I've assigned you! Check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing and please don't hesitate to let us know if you need any help. 

Also, may I ask how did you come across the Codecademy Docs repo?

**Comment by rubenm25** [comment]
Thanks! I'm workin on a project on codecademy. The project is about creating and submitting an entry to Codecademy Docs on a chosen topic. I'm kinda new to this topic so just to get it right. I must create a markdown file that covers the following structure?

![Screenshot 2023-02-10 at 23 22 56](https://user-images.githubusercontent.com/64099232/218200863-e92df31e-fdf9-4595-aecb-0f080862893a.png)

Thanks,
Ruben

**Comment by KTom101** [comment]
@rubenm25 Thanks for sharing! And yes you are to create a markdown file named "subSequence.md" covering those points.
