### ISSUE TITLE
[Term Entry] Java Strings: `.toCharArray()` Method

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1596]
### Reason/inspiration (optional)

Add a new term entry under the [Java: Strings](https://www.codecademy.com/resources/docs/java/strings) concept. This entry should include:

- An explanation of the method.

- A "Syntax" section with a ```pseudo code snippet showing the general syntax.

- An "Example" section with a ```java code snippet showing how it works.

A markdown file named "toCharArray.md" should be added to a folder named "toCharArray" and placed in the terms folder located under content/java/concepts/strings/terms

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Othamae** [comment]
Hi @KTom101, I would like to work on this issue. Could you please assign it to me? Thanks!!

**Comment by KTom101** [comment]
@Othamae You've been assigned! 😁 Please check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing and please don't hesitate to let us know if you need any help. 

Also, may I ask how did you come across the Codecademy Docs repo?

**Comment by KTom101** [comment]
@Othamae That's great to hear. Thank you for your interest in contributing! ❤️
