### ISSUE TITLE
[Edit] HTML Attributes: Linking to `id` 

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1603]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Incorporate [HTML Attributes](https://www.codecademy.com/resources/docs/html/attributes), under "Unique ID Attributes," to the [`id`](https://www.codecademy.com/resources/docs/html/attributes/id) entry to reduce redundancy.

In addition, add the [`id`](https://www.codecademy.com/resources/docs/html/attributes/id) link to the first occurrence of the term ,`id`, in the [HTML Element <output>](https://www.codecademy.com/resources/docs/html/elements/output) entry.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by 0xRa369** [comment]
Can I be assigned this issue?

**Comment by yangc95** [comment]
@0xRa369 Sure! Is this your first issue, and if so, how did you decide to contribute to Docs?

I've gone ahead and assigned you to this Issue. If you have any questions or need assistance please let me know by tagging me!

**Comment by 0xRa369** [comment]
Yes, this is my first. I have been finishing the "learn git branching and collaboration course" on Codecademy and I am trying to complete the kanban project

**Comment by yangc95** [comment]
@0xRa369 Nice to hear! Good luck with the kanban project and can't wait to see your PR 😄

**Comment by SSwiniarski** [comment]
@0xRa369 It's been over two weeks, are you still working on this? Do you need assistance?

**Comment by SSwiniarski** [comment]
@0xRa369, because of inactivity I am unassigning you so someone else can work on this.

**Comment by muhiddinkurbonov** [comment]
Hi, @SSwiniarski and @yangc95 ! I'd like to work on this issue. Could you assign it to me, please? This will be my first issue. I was working on github project in codecademy.

**Comment by muhiddinkurbonov** [comment]
I've submitted my pull request, could you let me know if it's ready to merge or needs fix. Thank you!

**Comment by klaudia-miedz** [comment]
Hi, 
I would love to be assigned to this issue if it is fine. This would be my first project to complete the "Open-source project on GitHub - a portfolio project". 
Please let me know about your decision.
Many thanks,
Klaudia

**Comment by SSwiniarski** [comment]
@muhiddinkurbonov I've assigned you, but in the future you should wait for one of the maintainers to assign you to an issue before submitting a PR.

**Comment by muhiddinkurbonov** [comment]
Thank you, I'll wait to be assigned in the future!

**Comment by muhiddinkurbonov** [comment]
@SSwiniarski , is it good to close the issue now? I don't see an option here to close it.

**Comment by SSwiniarski** [comment]
@muhiddinkurbonov It will be closed when the linked PR is merged.
