### ISSUE TITLE
[Term Entry] C# Math Functions `.Exp()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1606]
### Reason/inspiration (optional)

We would like a new term entry for [C#](https://www.codecademy.com/resources/docs/c-sharp) about the `Math.Exp()` method.

The entry should go in a new file in `docs/content/c-sharp/concepts/math-functions/terms/exp/exp.md`

The entry should

- Have a syntax section illustrating the method with a ` ```pseudo ` code block.
- An example showing the method in use with a ` ```cs ` code block.
- A runnable codebyte example in a ` ```codebyte/csharp ` block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by kpetrov2** [comment]
Hi @SSwiniarski ! I'd like to be assigned to this issue please, to complete the GitHub course.
Have a nice day!

**Comment by kpetrov2** [comment]
I've made the changes, should I wait or should I do another pull request?

**Comment by yangc95** [comment]
@kpetrov2 You should be able to push your changes up to the same PR branch `[kpetrov2:MathExp-kpetrov2](https://github.com/kpetrov2/docs/tree/MathExp-kpetrov2)`. Did you need further instructions on how to do this?

**Comment by kpetrov2** [comment]
Thank you for the answer @yangc95 ! As I can see on the repo I've pushed the new commit already. I'm ready for a second review :)
Have a nice day!
