### ISSUE TITLE
[Term Entry] C# Math Functions `.Pow()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1611]
### Reason/inspiration (optional)

We would like a new term entry for [C#](https://www.codecademy.com/resources/docs/c-sharp) about the `Math.Pow()` method.

The entry should go in a new file in `docs/content/c-sharp/concepts/math-functions/terms/pow/pow.md`

The entry should

- Have a syntax section illustrating the method with a ` ```pseudo ` code block.
- An example showing the method in use with a ` ```cs ` code block.
- A runnable codebyte example in a ` ```codebyte/csharp ` block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Yash-Var** [comment]
@SSwiniarski  i want to contribute...

**Comment by SSwiniarski** [comment]
@Yash-Var, you've been assigned three issues already. Please work on those PRs before claiming any more issues.

**Comment by jingram80024** [comment]
I would like to contribute to this issue to complete my Codecademy Git & GitHub course.

**Comment by dhbrmn** [comment]
@SSwiniarski I would like to try and contribute. It would be my first ever contribution. Hope that's okay.

**Comment by SSwiniarski** [comment]
@dhbrmn, youve been assigned! Can I ask how you came across this repro?

**Comment by dhbrmn** [comment]
@SSwiniarski I was following the Learn Git & GitHub course on codecademy. Contributing to the codecademy docs is a portfolio project in the series. As for the repo itself I just searched codecademy and found it.
