### ISSUE TITLE
[Term Entry] C# Math Functions `.Round()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1612]
### Reason/inspiration (optional)

We would like a new term entry for [C#](https://www.codecademy.com/resources/docs/c-sharp) about the `Math.Round()` method.

The entry should go in a new file in `docs/content/c-sharp/concepts/math-functions/terms/round/round.md`

The entry should

- Have a syntax section illustrating the method with a ` ```pseudo ` code block.
- An example showing the method in use with a ` ```cs ` code block.
- A runnable codebyte example in a ` ```codebyte/csharp ` block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by abhaynambiar** [comment]
Hi @SSwiniarski I would like to work on this . Please assign it to me .

**Comment by yangc95** [comment]
@abhaynambiar Assigned!

**Comment by SSwiniarski** [comment]
@abhaynambiar, It's been two weeks without any activity. Are you still working on this issue? Do you need any assistance?

**Comment by abhaynambiar** [comment]
Sorry yes I am just wanted to know if the function requires a description for each function
i.e Round(Decimal)
Round(Double)

**Comment by yangc95** [comment]
@abhaynambiar I see you're referring to the overloads. I'd recommend covering all the different types in the syntax section by referring to it as a number or `num` for short. See [.Max()](https://www.codecademy.com/resources/docs/c-sharp/math-functions/max) as an example and feel free to include a note about what an overload is if this is of concern.

Let us know if you have any further questions!

**Comment by SSwiniarski** [comment]
@abhaynambiar It's been another two weeks. Are you still working on this issue?

**Comment by SSwiniarski** [comment]
@abhaynambiar, because of the inactivity, I am unassigning you so someone else can work on this.

**Comment by exampleuser10012** [comment]
@yangc95 I am interested in taking this issue on, I found out about Docs through a friend.

**Comment by KJ-82** [comment]
@yangc95 I am interested in taking this issue on. I found about Docs though a friend.

**Comment by SSwiniarski** [comment]
@KJ-82 This issue was already assigned and had a PR assigned to it. I closed your PR because it both duplicated and plagiarized @exampleuser10012's PR. If you wish to contribute in the future, find an issue that hasn't been assigned, ask to be assigned to it, _wait to be assigned the issue_ then create a PR that is _your own original work_.
