### ISSUE TITLE
[Term Entry] C# Math Functions `.Tan()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1616]
### Reason/inspiration (optional)

We would like a new term entry for [C#](https://www.codecademy.com/resources/docs/c-sharp) about the `Math.Tan()` method.

The entry should go in a new file in `docs/content/c-sharp/concepts/math-functions/terms/tan/tan.md`

The entry should

- Have a syntax section illustrating the method with a ` ```pseudo ` code block.
- An example showing the method in use with a ` ```cs ` code block.
- A runnable codebyte example in a ` ```codebyte/csharp ` block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Yash-Var** [comment]
@SSwiniarski  i want to contribute...

**Comment by SSwiniarski** [comment]
@Yash-Var it's been over two weeks, are you still working on this?

**Comment by SSwiniarski** [comment]
@Yash-Var because of inactivity I am unassigning you so someone else can work on this.

**Comment by huythai855** [comment]
Hi! Can I continue working on this issue?

**Comment by SSwiniarski** [comment]
@huythai855 You've been assigned. Check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for more info on contributing.

**Comment by SSwiniarski** [comment]
@huythai855 it's been two weeks, are you still working on this? Do you need any assistance?

**Comment by huythai855** [comment]
@SSwiniarski oh, sorry for being late ☹️ .
I've just pushed my commit and created a pull request for this issue.
