### ISSUE TITLE
[Edit] SQL: COUNT()

### ISSUE THREAD

**Issue by kazumikerr** [Codecademy/docs#1645]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Can we add **COUNT(1)** section in the COUNT() SQL document?
The result is essentially the same as COUNT(*), but I thought some people want to know different variations of code.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by kazumikerr** [comment]
I would like to work on this issue.

**Comment by KTom101** [comment]
@kazumikerr Good idea, I've assigned you.

**Comment by yangc95** [comment]
@kazumikerr Just to confirm, when you say "COUNT(1)" do you mean you wish to expand on the arguments that can be passed into to aggregate function?

**Comment by yangc95** [comment]
@kazumikerr I see! If you can also change up the note under the syntax heading, that would be great 🙂 to something like: 

> **Note:**  `*` can be used as well as a column name. However, COUNT(*) will include NULL values while the COUNT(column_name) variation will not count NULL values.

Or something to that effect.
