### ISSUE TITLE
[Term Entry] Matplotlib `pyplot`: `bar`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1658]
### Reason/inspiration (optional)

Please write a new entry under:  content/matplotlib/concepts/pyplot/terms/ about the [`.bar()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.bar.html) method in Python.

A "Syntax" section with pseudo code snippet.
An "Example" section with a Python code snippet. If images are included, they should go in the media/ folder.

To get started with the PR and entry file:

Under content/matplotlib/concepts/pyplot/terms/, create a new folder called `bar`. Then create a new file called `bar.md` under content/matplotlib/concepts/pyplot/terms/`bar`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by DooMIM** [comment]
Hey, I would like to work on this issue.

**Comment by KTom101** [comment]
@DooMIM You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing. 😁

Also, how did you find out about the Codecademy Docs repo?

**Comment by SSwiniarski** [comment]
@DooMIM The original PR you submitted had no content. Are you still working on this? Do you need assistance?

**Comment by DooMIM** [comment]
thanks for asking @SSwiniarski yes I actually need assistant. I added content but failed to push it through and got this error Fatal: could not read from remote repository. after googling the problem, I created an SSH key but the problem wasn't solved. would appreciate any hints. Thanks again

**Comment by SSwiniarski** [comment]
@yangc95, @KTom101, @caupolicandiaz, @HishamT, any of you have any idea about @DooMIM's problem?

**Comment by DooMIM** [comment]
I run git commit -m then git push origin. attached is a screenshot. 
<img width="476" alt="Screenshot 2023-02-28 at 22 11 31" src="https://user-images.githubusercontent.com/124182707/221981406-cbe112ba-7807-47fc-b953-72953bc6255f.png">

**Comment by DooMIM** [comment]
any ideas on how can I proceed. @SSwiniarski @KTom101 @yangc95 @caupolicandiaz @HishamT

**Comment by yangc95** [comment]
@DooMIM Thanks for following up! It looks like your origin remote is set to the Codecademy repository when it should be to your forked repository. See: https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories#changing-a-remote-repositorys-url

**Comment by DooMIM** [comment]
@yangc95 great! this helped solve the issue. Thanks! would it still be possible to review the pull request?

**Comment by yangc95** [comment]
> @yangc95 great! this helped solve the issue. Thanks! would it still be possible to review the pull request?

Yup! Looks like the first review is up 🙂

**Comment by DooMIM** [comment]
@SSwiniarski thanks a lot for the comments. I created a new pull request, looking forward to your feedback :) .
