### ISSUE TITLE
[Term Entry] Matplotlib `pyplot`: `boxplot`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1659]
### Reason/inspiration (optional)

Please write a new entry under:  content/matplotlib/concepts/pyplot/terms/ about the [`.boxplot()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.boxplot.html) method in Python.

A "Syntax" section with pseudo code snippet.
An "Example" section with a Python code snippet. If images are included, they should go in the media/ folder.

To get started with the PR and entry file:

Under content/matplotlib/concepts/pyplot/terms/, create a new folder called `boxplot`. Then create a new file called `boxplot.md` under content/matplotlib/concepts/pyplot/terms/`boxplot`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by astro-satyam75** [comment]
Can I be assigned to this issue?

**Comment by yangc95** [comment]
@astro-satyam75 If this is your first contribution, what brought you to Docs?

> You're assigned! You can check out the [[Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md)](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
> 
> See [[Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md)](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the  [[Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md)](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

After creating a PR, maintainer(s) (with the collaborater label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by astro-satyam75** [comment]
@yangc95 Thanks for assigning me to the issue.
This is my second contribution. 
I came across this repository on the Codeacademy's website, in the section of docs itself https://www.codecademy.com/resources/docs

**Comment by SSwiniarski** [comment]
@astro-satyam75 It's been over two weeks. Are you still working on this issue, do you need assistance?

**Comment by astro-satyam75** [comment]
@SSwiniarski  Apologies for the delay. I have created the first pull request
