### ISSUE TITLE
[Term Entry] Matplotlib `pyplot`: `pie`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1661]
### Reason/inspiration (optional)

Please write a new entry under:  content/matplotlib/concepts/pyplot/terms/ about the [`.pie()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.pie.html) method in Python.

A "Syntax" section with pseudo code snippet.
An "Example" section with a Python code snippet. If images are included, they should go in the media/ folder.

To get started with the PR and entry file:

Under content/matplotlib/concepts/pyplot/terms/, create a new folder called `pie`. Then create a new file called `pie.md` under content/matplotlib/concepts/pyplot/terms/`pie`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Nate1809** [comment]
Hello!
I would like to contribute to this entry as part of the git course in Codecademy :D

**Comment by yangc95** [comment]
@Nate1809 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

Also see [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for styling tips.
