### ISSUE TITLE
[Term Entry] Matplotlib `pyplot`: `scatter`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1662]
### Reason/inspiration (optional)

Please write a new entry under:  content/matplotlib/concepts/pyplot/terms/ about the [`.scatter()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html) method in Python.

A "Syntax" section with pseudo code snippet.
An "Example" section with a Python code snippet. If images are included, they should go in the media/ folder.

To get started with the PR and entry file:

Under content/matplotlib/concepts/pyplot/terms/, create a new folder called `scatter`. Then create a new file called `scatter.md` under content/matplotlib/concepts/pyplot/terms/`scatter`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by alekseymor** [comment]
I'd like to contribute to this. Thanks!

**Comment by yangc95** [comment]
Thanks @alekseymor, please check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for information on contributing.

Also, how did you find out about the Codecademy Docs repo?

**Comment by alekseymor** [comment]
Thank you Christine. I am currently going through the Git and Github course on codecademy (and enjoying it greatly!). That's how I came across this repo.
