### ISSUE TITLE
[Term Entry] Subject: Hexadecimal

### ISSUE THREAD

**Issue by HishamT** [Codecademy/docs#1667]
### Reason/inspiration (optional)

We would like a new entry explaining the hexadecimal number system.

To create this entry, create a new folder in /docs/content/general/concepts called hexadecimal. Inside this folder, create a new Markdown file called hexadecimal.md that will contain the contents of the entry.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by penalus** [comment]
Can I do this one please?

**Comment by HishamT** [comment]
@penalus, you got it! :grin:

**Comment by penalus** [comment]
Thanks! 😄

**Comment by SSwiniarski** [comment]
@penalus, It's been two weeks, are you still working on this issue? Do you need assistance?

**Comment by penalus** [comment]
Hey! I'm working on my assignment and I have made 3 commits so far.  I am totally new to hexadecimal as a number system(and not just as color in html/css), and I have been reading and learning a lot about bases. Can you see my commits? Or do I have to push for others to see?

**Comment by SSwiniarski** [comment]
@penalus I see you just now submitted a PR. As we review it, you can keep making commits to that branch and the changes will appear in the PR.
