### ISSUE TITLE
[Term Entry] Subject: Octal

### ISSUE THREAD

**Issue by HishamT** [Codecademy/docs#1668]
### Reason/inspiration (optional)

We would like a new entry explaining the octal number system.

To create this entry, create a new folder in /docs/content/general/concepts called octal. Inside this folder, create a new Markdown file called octal.md that will contain the contents of the entry.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by MaximilianLuft** [comment]
Hi,

I was searching for my first issue to contribute to the Codecademy Docs, so I would be happy to claim this one ;)

Regards
Max

**Comment by HishamT** [comment]
You got it!
