### ISSUE TITLE
[Edit] SwiftUI ViewModifier: Terms

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1687]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

Edit the markdowns located inside these directories:

- bold
- resizeable
- scaledToFit

For each file underneath the Syntax header, edit the pseudo code block to only include the modifier method and view that it's called on rather than nesting it inside a struct and body.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by cslylla** [comment]
I would like to make these changes!

**Comment by yangc95** [comment]
Thanks @cslylla !
