### ISSUE TITLE
[Concept Entry] Kotlin: Functions

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1688]
### Reason/inspiration (optional)

Create an concept entry for functions using Kotlin in the path: content/kotlin/concepts/functions/functions.md

The file should at least have the following:

A "Syntax" section with a ```pseudo code snippet.
An "Example" section with a ```kotlin code snippet.

See this [template](https://github.com/Codecademy/docs/blob/main/documentation/entry-template.md) as a guide.

Refer to the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for styling.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by chiragcode11** [comment]
can you assign me this this issue

**Comment by KTom101** [comment]
@chiragcode11 I've assigned you. Thanks for being interested in contributing!

**Comment by SSwiniarski** [comment]
@chiragcode11 It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by SSwiniarski** [comment]
@chiragcode11 I am unassigning you due to inactivity so someone else can work on this.

**Comment by MToome** [comment]
Hello, did I understand it correctly that it is needed to make a brief description of functions in Kotlin with examples? Like: Functions are a reusable block of code that performs a certain task.

**Comment by KTom101** [comment]
@MToome An explanation, a section on how the syntax looks, and examples should be included. You can take a look at how the entries on functions look for other languages to get an idea. For example, [C: Functions](https://www.codecademy.com/resources/docs/c/functions) and [Python: Functions](https://www.codecademy.com/resources/docs/python/functions).

Would you like to be assigned to this?

**Comment by MToome** [comment]
Yes, please

**Comment by KTom101** [comment]
@MToome I’ve assigned you! Please look at the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing. The [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) has an overview of styling tips while the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers them in detail.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

Also, feel free to ask us questions if any arise. May I ask how did you come across the Codecademy Docs repo?

**Comment by MToome** [comment]
@KTom101 Will look at them.
I come across the Codecademy Docs repo by learning git ang github at codecademy, right now I am at chapter "contributing to the Codecademy Docs Repo".
