### ISSUE TITLE
[Concept Entry] Kotlin: Objects

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1689]
### Reason/inspiration (optional)

Create an concept entry for objects using Kotlin in the path: content/kotlin/concepts/objects/objects.md

The file should at least have the following:

A "Syntax" section with a ```pseudo code snippet.
An "Example" section with a ```kotlin code snippet.

See this [template](https://github.com/Codecademy/docs/blob/main/documentation/entry-template.md) as a guide.

Refer to the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for styling.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by iAM7ander** [comment]
Hi @yangc95 , could you assign this issue to me? Cheers

**Comment by iAM7ander** [comment]
Appreciate you, thanks.

Part of the curriculum for some of these courses, figured I'd dive in.

**Comment by KTom101** [comment]
@iAM7ander Cool, thanks! 👍

**Comment by SSwiniarski** [comment]
@iAM7ander, It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by SSwiniarski** [comment]
@iAM7ander, because of inactivity, I am unassigning you so someone else can work on this issue.

**Comment by hiyanchan** [comment]
Hello, yangc95, can you assign me to this issue?

**Comment by KTom101** [comment]
@hiyanchan I’ve assigned you! Please look at the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing. The [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) has an overview of styling tips while the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers them in detail.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

Also, feel free to ask us questions if any arise. May I ask how did you come across the Codecademy Docs repo?

**Comment by SSwiniarski** [comment]
@hiyanchan, because of inactivity I am unassigning you so someone else can work on this issue.

**Comment by diosDeNada** [comment]
@SSwiniarski hello, can you  you assign to me this issue? please
I will completed in less than 1 week :)

**Comment by KTom101** [comment]
@diosDeNada You're assigned. In addition to the documents linked in the description, please also take a look at our revamped [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR,  maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by diosDeNada** [comment]
### Thank you @KTom101 
Yes, this is my first contribution here in Docs, also my first participation in a OpenSource project ever. 
Im taking the [Open Source course] (https://www.codecademy.com/learn/introduction-to-open-source) in **CodeCademy** in this moment, and the Portafolio project have a requirement to participate here. I hope being a frecuent contributor. I discover i like the OpenSource movement a lot, and I hope colud fusion that with my Front End Engineer career.

**Comment by diosDeNada** [comment]
@KTom101 The PR it was already sent. I look forward to any comments, corrections and help.
TIA.

**Comment by yangc95** [comment]
@diosDeNada I see you've created a branch on your forked repo, but I'm not sure if I see your PR.

**Comment by diosDeNada** [comment]
@yangc95 maybe now? I not sure how to use github well :(
But is my list of next classes.

**Comment by SSwiniarski** [comment]
@diosDeNada This might help: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by diosDeNada** [comment]
Thanks a lot @SSwiniarski.
I will read it right now.

**Comment by diosDeNada** [comment]
@SSwiniarski I have a problem. In the fork i created, I dont see any yellow banner that say "Compare & pull request". Neither I see it in the Docs originals.

**Comment by diosDeNada** [comment]
@SSwiniarski @yangc95 @KTom101 I think is ready now.
I follow slowly, step by step, [this documentation](https://www.codecademy.com/resources/docs/contribution-guide), and now i can see the PR in the original Docs.
I look forward to next steps. Thanks for the patience and help.
