### ISSUE TITLE
[Edit] General Data Types: Array

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1711]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

Within `content/general/concepts/data-types/terms/array/array.md`:

Change description "An array is a collection of stored data that can hold values of various data type." to "Stores data with values of a various data type in an indexed collection of elements."

Feel free to re-word as appropriate. The goal is to change the description so that it starts with a verb. This edit is needed since this concept entry has been converted into a term entry.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Lenka-Junova** [comment]
Can I make the change?

**Comment by yangc95** [comment]
@Lenka-Junova For sure! Don't hesitate to reach out if you have any pressing concerns or questions. 🙂
