### ISSUE TITLE
[Edit] General Data Types: Boolean

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1712]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

Within `content/general/concepts/data-types/terms/boolean/boolean.md`:

Change description "The boolean data type represents the logical values of true and false." to "Represents the logical values of true and false."

Feel free to re-word as appropriate. The goal is to change the description so that it starts with a verb. This edit is needed since this concept entry has been converted into a term entry.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by lameast** [comment]
Hi, could I work on this issue?

**Comment by yangc95** [comment]
@lameast assigned! Don't hesitate to reach out if you have any questions ☺️

**Comment by lameast** [comment]
I have created a pull request #1723 .
