### ISSUE TITLE
[Edit] General Data Types: Number

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1713]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

Within content/general/concepts/data-types/terms/number/number.md:

Change description "The number data type encompasses many numeric values." to "Represents many numeric values."

Encouraged to re-word as appropriate. The goal is to change the description so that it starts with a verb. This edit is needed since this concept entry has been converted into a term entry.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Letsamsiyu** [comment]
Hi Christine, 
I'd like to claim this issue to practice my GitHub skills. 
Best regards,
Martin

**Comment by yangc95** [comment]
@Letsamsiyu assigned! Let me know if you have any questions or concerns 🙂

**Comment by Letsamsiyu** [comment]
I created a pull request #1718 
I also signed the CLA but it still says "not signed yet", what am I doing wrong?
