### ISSUE TITLE
[Edit] General Data Types: String

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1714]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

Within `content/general/concepts/data-types/terms/string/string.md`:

Change description "In computer science, sequences of characters are referred to as strings. Strings can be any length and can include any character such as letters, numbers, symbols, whitespace (spaces, tabs, new lines). It is usually contained within a pair of single quotes or "double quotes". A string can be thought of as a list of characters. Like any other list, each character in a string has an index." to "Stores a sequence of indexed characters that can be of any length and is contained within a pair of single or double quotes."

Feel free to re-word as appropriate. The goal is to change the description so that it starts with a verb. This edit is needed since this concept entry has been converted into a term entry.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by bryansmaller** [comment]
I'd be happy to make this change.
