### ISSUE TITLE
[Edit] General Data Types: Void

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1715]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

Within `content/general/concepts/data-types/terms/void/void.md`:

Change description "Void types denote functions that have side effects but do not return an actual result." to "Denotes functions that have side effects but do not return an actual result."

Feel free to re-word as appropriate. The goal is to change the description so that it starts with a verb. This edit is needed since this concept entry has been converted into a term entry.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Mangelinho** [comment]
Hi Christine

Can I claim this issue as a good first issue for practicing the Git & GitHub education, please?

Regards
Magnus

**Comment by yangc95** [comment]
@Mangelinho Assigned! Don't hesitate to reach out if you have any questions 🙂

**Comment by Mangelinho** [comment]
Hi @yangc95 

I have some minor text questions about the contribution guide inside the pull request.

1. In step,

> 2. Click on your profile image in the top-right and then choose "Profile".

**Actual**
In my GitHub account it says, 

> Your profile

2. In step,

> 4. In the "GitHub Username" field, add your username (without the @).

**Actual**
In my GitHub account under "Edit profile" there are no "GitHub Username".
There is "Name"

Change guide in Pull request or maybe not issues at all? :)

**Comment by yangc95** [comment]
@Mangelinho Would you mind pointing out the line numbers you're referring to in the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md)?

**Comment by Mangelinho** [comment]
@yangc95 

The line numbers I am referring to is
> ...inside the pull request.

I.e.

> **IMPORTANT**

> If you would like to receive credit for your contribution to an entry, make sure to have your Codecademy user profile linked to your GitHub account:

> 1. Go to your Codecademy dashboard.

> 2. Click on your profile image in the top-right and then choose "Profile".

> 3. Then click "Edit Profile".

> 4. In the "GitHub Username" field, add your username (without the @).

> 5. Click "Save Changes"

> Of course, you can opt not to do this and be listed as an "Anonymous contributor", instead. :)

**Comment by yangc95** [comment]
@Mangelinho I think there's some confusion. This is in reference to the Codecademy website, not GitHub.
