### ISSUE TITLE
[Entry] Artificial Intelligence: Search Algorithm

### ISSUE THREAD

**Issue by HishamT** [Codecademy/docs#1722]
### Reason/inspiration (optional)

We seek an entry explaining the concept of a Search Algorithm in the context of Artificial Intelligence. 

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by rykunk21** [comment]
Hello @HishamT, I would like to work on this task. Would you please assign it to me?

**Comment by KTom101** [comment]
@rykunk21 You're assigned! Please check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for information on contributing.

Also, how did you find out about the Codecademy Docs repo?

**Comment by rykunk21** [comment]
@KTom101 I discovered the Codecademy Docs repo while going through the "learn Git & Github" course.

**Comment by KTom101** [comment]
@rykunk21 Cool 👍 Thanks for letting me know!
