### ISSUE TITLE
[Edit] Ruby: Various Ruby implementations

### ISSUE THREAD

**Issue by Pavan-04-08** [Codecademy/docs#1725]
## Reason/inspiration (optional)
codeacademy is well known as ruby on rails shop.. 
so it would be nice to have atleast couple paragraphs about ruby implemntations like JRuby,TruffleRuby. (as these are being used by companies )

The entry can go in file in  docs/content/ruby/ruby.md

The entry should

 - Include a simple section about why these implementations come into picture, and what are the trade offs
No need of code as it is just a surface level explaination so user can be aware of these implementations.
###  Entry Type (select all that apply)
  New Edit for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by Pavan-Nambi** [comment]
This can be `good first issue `
if anyone want to contribute , they can use below references
[What the hell is JRuby?](https://www.youtube.com/watch?v=qJqC6xm-2PI&t=784s)
[Ruby & JVM A JRuby Love Story](https://www.youtube.com/watch?v=27qhUnu9_v4&t=499s)
[TruffleRuby](https://www.graalvm.org/ruby/)

**Comment by samfram** [comment]
May I be assigned this one? Looking to make my first contribution, thanks.

**Comment by yangc95** [comment]
@samfram Yeah, I think it would be good to pick one of the concepts mentioned above. Let me know which one you decide to do and I can create a new Issue for it

**Comment by samfram** [comment]
@yangc95 I'll work on JRuby, thanks!

**Comment by yangc95** [comment]
@Pavan-04-08 I'm closing this issue since two issues are branching off this discussion. Thanks for your input!

**Comment by yangc95** [comment]
@samfram I've created the issue here. Please let me know if you are able to complete this still: https://github.com/Codecademy/docs/issues/2028

Thanks!
