### ISSUE TITLE
[Concept Entry] C# Loops

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1731]
### Reason/inspiration (optional)

We would like a new term entry for [C#](https://www.codecademy.com/resources/docs/c-sharp) about Loops.

The entry should go in a new file in docs/content/c-sharp/concepts/loops/loops.md

The entry should contain:

- Explanations the syntax of `for` loop, a `while` loop, and a `do...while` loop and explain the differences.
- Examples showing each loop in use with a ` ```cs ` code block.
- A runnable codebyte example in a ` ```codebyte/csharp ` block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by brome40** [comment]
I'd like to work on this issue.

**Comment by SSwiniarski** [comment]
@brome40, you've been assigned! Can I ask how you came across this repo?

**Comment by brome40** [comment]
@SSwiniarski Sure, I'm currently taking the Codecademy course on Git & Github which led me here. I have a decent background in C# so I thought it would be a good exercise
