### ISSUE TITLE
[Concept Entry] C# Conditionals

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1732]
### Reason/inspiration (optional)

We would like a new term entry for [C#](https://www.codecademy.com/resources/docs/c-sharp) about Conditionals.

The entry should go in a new file in docs/content/c-sharp/concepts/conditionals/conditionals.md

The entry should contain:

- Explanations the syntax of `if`, `else` and `else if` using a ` ```pseudo` code block.
- Explanation of the syntax/use of the ternary operator: i.e. `result = (condition) ? truevalue : falsevalue;` 
- Examples showing conditionals in use with a ` ```cs ` code block.
- A runnable codebyte example in a ` ```codebyte/csharp ` block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by VisnetAppel** [comment]
I would like to work on this Issue

**Comment by SSwiniarski** [comment]
@VisnetAppel, you've been assigned!

**Comment by SSwiniarski** [comment]
Closing this as it was addressed with [1916](https://github.com/Codecademy/docs/pull/1916).
