### ISSUE TITLE
[Concept Entry] C# Switch

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1733]
### Reason/inspiration (optional)

We would like a new term entry for [C#](https://www.codecademy.com/resources/docs/c-sharp) about the `switch` statement.

The entry should go in a new file in docs/content/c-sharp/concepts/switch/switch.md

The entry should contain:

- Explanations the syntax of `switch` using a ` ```pseudo` code block.
- An example showing `switch` in use with a ` ```cs ` code block.
- A runnable codebyte example in a ` ```codebyte/csharp ` block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by kylestarr** [comment]
I'd like to claim this issue.

**Comment by SSwiniarski** [comment]
@kylestarr, you've been assigned.
