### ISSUE TITLE
[Edit] HTML: Elements

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1735]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Input from [comment](https://github.com/Codecademy/docs/pull/533#issuecomment-1026074172).

Make edits to content/html/concepts/elements/elements.md:

> Some elements, like input, img, br, etc. are void elements (aka "empty" elements in the current description, elements that can never have children)
> 
> void elements can optionally be self-closing (ie have a trailing slash) and it's pretty much up to personal preference
> there is also a caveat that making all void elements self-closing improves compatibility with XHTML

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by cslylla** [comment]
I can incorporate the comments in the elements.md document.
