### ISSUE TITLE
[Edit] Python Time Module: .sleep()

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1736]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

Continuation from [comment](https://github.com/Codecademy/docs/pull/1375#issuecomment-1402356180) for changes to be made in `content/python/concepts/time-module/terms/sleep/sleep.md`:

> In the intro, let's remove the extra backtick in our keyword and take away the parenthesis surrounding "in seconds" as it's not needed in this case.
> 
> In addition, it looks like the code byte is resulting in an error.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by japhet40** [comment]
> @japhet40 would you like to take this issue on since it's your entry? If not we can keep this open for another contributor to take on.

yes i will take the issue

**Comment by japhet40** [comment]
> > @japhet40 would you like to take this issue on since it's your entry? If not we can keep this open for another contributor to take on.
> 
> yes i will take the issue

Made changes and created a PR
