### ISSUE TITLE
[Edit] Building Code History: The Final App Cheatsheet: Classes

### ISSUE THREAD

**Issue by Digital-Brendan** [Codecademy/docs#1744]
### Type of Edit (select all that apply)

Clarify unclear content and/or terms

### Description (optional)

In the `Building Code History: The Final App` Swift cheatsheet, there is some unclear text under the `Reference Types` subheading.

_"Classes are reference types, while structures are value types, classes are reference types."_ should really be _"Classes are reference types, while structures are value types."_, i.e., without the duplicated phrase.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by SSwiniarski** [comment]
I am closing this as it is not an issue with Docs.

**Comment by yangc95** [comment]
@Digital-Brendan Thank you for finding this written error nonetheless! It will be dealt with accordingly.
