### ISSUE TITLE
[Entry] Artificial Intelligence: A* Search

### ISSUE THREAD

**Issue by HishamT** [Codecademy/docs#1746]
### Reason/inspiration (optional)

We seek an entry describing the A* Search algorithm.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by SSwiniarski** [comment]
This is completed
