### ISSUE TITLE
[Term Entry] SQL: Window Functions `ROW_NUMBER()`

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1776]
### Reason/inspiration (optional)

Add a new entry under `content/sql/concepts/window-functions/terms/row-number/row-number.md` explaining the `ROW_NUMBER()` window function.

The `row_number.md` file should contain:

- Short explanation of the function
- Syntax section with a ` ```pseudo ` code block showing a general syntax
- Example section with a ` ```sql ` code block showing a concrete example of how the function can be used

In addition to the [Contributing Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md), use the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) as reference when making the PR.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by mserna24** [comment]
Hi, I was hoping that I could be assigned to this new entry?

**Comment by KTom101** [comment]
@mserna24 You're assigned. Please use the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for guidance while creating this entry.

**Comment by SSwiniarski** [comment]
@mserna24 It's been over two weeks. Are you still working on this issue? Do you need assistance?

**Comment by SSwiniarski** [comment]
@mserna24 Because of inactivity I am unassigning you so someone else can work on this issue.

**Comment by KennyCopp** [comment]
Hello, I would like to be assigned this issue. Thank you.

**Comment by SSwiniarski** [comment]
@KennyCopp If this is your first contribution, what brought you to Docs?

You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md)for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by KennyCopp** [comment]
Thanks! I'm working on a career change so I'm going through the GitHub course. If you have any advice for getting started in IT please let me know.
