### ISSUE TITLE
[Term Entry] SQL: Window Functions `LAG()`

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1777]
### Reason/inspiration (optional)

Add a new entry under content/sql/concepts/window-functions/terms/lag/lag.md explaining the LAG() window function.

The lag.md file should contain:

- Short explanation of the function

- Syntax section with a ` ```pseudo ` code block showing a general syntax

- Example section with a ` ```sql ` code block showing a concrete example of how the function can be used

In addition to the [Contributing Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md), use the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) as reference when making the PR.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by M3RF3R** [comment]
Hi! I'd like to contribute to this issue.

**Comment by SSwiniarski** [comment]
@M3RF3R You've been assigned!

**Comment by M3RF3R** [comment]
sorry, something has come up. I'm not going to be able to contribute for a little bit, in case you want to reassign this issue.

**Comment by SSwiniarski** [comment]
@M3RF3R, I unassigned you. Feel free to claim another issue when you have time again.

**Comment by freshjah** [comment]
Hello. I would like to contribute here.

**Comment by SSwiniarski** [comment]
@freshjah You've been assigned. Check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for more info on contributing.

**Comment by freshjah** [comment]
@caupolicandiaz updates have been completed. Thank you
