### ISSUE TITLE
[Term Entry] SQL: Window Functions `LEAD()`

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1778]
### Reason/inspiration (optional)

Add a new entry under content/sql/concepts/window-functions/terms/lead/lead.md explaining the LEAD() window function.

The lead.md file should contain:

- Short explanation of the function
- Syntax section with a ` ``` pseudo ` code block showing a general syntax
- Example section with a ` ```sql ` code block showing a concrete example of how the function can be used

In addition to the [Contributing Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md), use the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) as reference when making the PR.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Chopikashvili** [comment]
Hi! Can I write the entry for this window function? I need to do this for my Learn Git project.

**Comment by KTom101** [comment]
@Chopikashvili You're assigned, make sure you follow the [Contribution Guide](uhttps://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) while writing this entry.
