### ISSUE TITLE
[Term Entry] SQL: Window Functions `NTILE()`

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1779]
### Reason/inspiration (optional)

Add a new entry under content/sql/concepts/window-functions/terms/ntile/ntile.md explaining the NTILE() window function.

The ntile.md file should contain:

- Short explanation of the function
- Syntax section with a ` ```pseudo ` code block showing a general syntax
- Example section with a ` ```sql ` code block showing a concrete example of how the function can be used

In addition to the [Contributing Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md), use the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) as reference when making the PR.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by J-Raunstrup** [comment]
I'd like to work on this issue please

**Comment by SSwiniarski** [comment]
@J-Raunstrup, You've been assigned. Check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for more info on contributing.

**Comment by J-Raunstrup** [comment]
Thanks

**Comment by SSwiniarski** [comment]
@J-Raunstrup It's been two weeks, are you still working on this issue? Do you need assistance?

**Comment by J-Raunstrup** [comment]
Hello. @SSwiniarski

I am working on completing the Codecademy analyse data with sql course so i know What the NTILE() clause does. After that i Will write the description as soon as i get the chance to.

I am 67% done with the course so far.

hope i can still be assigned. Im working on understanding NTILE()

**Comment by SSwiniarski** [comment]
@J-Raunstrup It's been another two weeks. Are you working on this? Do you need assistance?

**Comment by J-Raunstrup** [comment]
Hello. I have tried to make a term entry in markdown for the NTILE SQL clause and made a pull request. Im not sure i have done this correctly. Though here is the link to the pull request.

link: https://github.com/Codecademy/docs/pull/1989

**Comment by J-Raunstrup** [comment]
Can i be added as a contributor since i wrote the entry? I would really appreciate that.

Kind regards
Jens

**Comment by J-Raunstrup** [comment]
@caupolicandiaz @SSwiniarski Can i be added as a contributor since i wrote the entry? I would really appreciate that.

Kind regards
Jens
