### ISSUE TITLE
Semantic HTML entries needed: <details>, <summary>

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#179]
Semantic HTML still lacking the following term entries:

- `<details>`
- `<summary>`

Docs page: https://www.codecademy.com/resources/docs/html/semantic-html
GitHub folder: https://github.com/Codecademy/docs/tree/main/content/html/concepts/semantic-html

**Comment by StephNathai** [comment]
Hi, can I grab this?

**Comment by sonnynomnom** [comment]
@StephNathai Absolutely!

**Comment by StephNathai** [comment]
So sorry, I just realized you require a CLA to be signed and unfortunately my employer will need to approve this CLA before I can begin. I will have to unassign myself from this ticket, apologies again.

**Comment by sonnynomnom** [comment]
No worries!

**Comment by lukeecart** [comment]
Hey @sonnynomnom I can work on this but how do I sign the Contributor License Agreement (CLA)?

**Comment by sonnynomnom** [comment]
Nice @lukeecart, all you!

**Comment by lukeecart** [comment]
@sonnynomnom I have created a PR for this. Do I need to run tests locally? I ran `npm run compile` & `npm run test` but one of the test's fail - [I've replaced my local path with **** FOLDER PATH *** ]

Not sure why that's failed
```
Codecademy Docs Content › adheres to content file structure
    Expected: "****FOLDER PATH***\\content\\c\\****FOLDER PATH***\\content\\c.md"
    Received: "****FOLDER PATH***\\content\\c\\c.md"

      52 |         } else {
      53 |           const nodeName = nodePath.split('/').slice(-1)[0];
    > 54 |           expect(childPath).toBe(path.join(nodePath, `${nodeName}.md`));
         |                             ^
      55 |         }
      56 |       });
      57 |     };
```

**Comment by lukeecart** [comment]
After going around in circles it's because paths in windows have `\\` in between whereas macs use `/` so if on line 53 of `content.test.ts` we change `nodePath.split('/'`) to `nodePath.split(path.sep).` (see https://nodejs.org/api/path.html#path_path_sep). This will work for mac and windows. I can raise an issue tomorrow for it.

**Comment by sonnynomnom** [comment]
Thanks, @lukeecart!!! Merged. Our engineer is taking a look at your new Issue, too.
