### ISSUE TITLE
[Edit] C# Math Functions: .Ceiling(), .Exp(), .Floor()

### ISSUE THREAD

**Issue by cslylla** [Codecademy/docs#1799]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Edit the markdowns located inside these directories:

- docs/content/c-sharp/concepts/math-functions/terms/ceiling/ceiling.md
- docs/content/c-sharp/concepts/math-functions/terms/exp/exp.md
- docs/content/c-sharp/concepts/math-functions/terms/floor/floor.md

For each file, create a new "Codebyte Example" section with a runnable codebyte example in a ```codebyte/csharp block.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by cslylla** [comment]
If the codebyte example is needed for these files, I would like to work on the issue. 🤓
I could open another issue for the rest of the math functions.

**Comment by KTom101** [comment]
@cslylla I don't think it would hurt to add codebyte examples. I've assigned you!
