### ISSUE TITLE
Swift entries needed: Enums, Optionals

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#180]
2 entries are needed for Swift:

- Enums
- Optionals

Codecademy Docs: https://www.codecademy.com/resources/docs/swift
GitHub folder: https://github.com/Codecademy/docs/tree/main/content/swift/concepts

**Comment by SSwiniarski** [comment]
@yangc95, are you still planning to do this?

**Comment by yangc95** [comment]
> @yangc95, are you still planning to do this?

@SSwiniarski yup! I'm still working on these two entries. Thanks for checking in
