### ISSUE TITLE
[Term Entry] Pandas DataFrame: `.isna()`

### ISSUE THREAD

**Issue by caupolicandiaz** [Codecademy/docs#1801]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Let's write a new entry about the .isna() DataFrame method (in pandas).

Folder/file structure: content/pandas/dataframe/isna/isna.md

Make sure to include the following sections:

A "Syntax" section with a pseudo code snippet. An "Example" section with a py code snippet.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by astro-satyam75** [comment]
Hi, I possess good knowledge about python and pandas. Can I be assigned to this issue? Thanks a lot!

**Comment by KTom101** [comment]
@astro-satyam75 You can work on this. Please use the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) while creating the entry. May I ask how did you come across the Codecademy Docs repository?

**Comment by astro-satyam75** [comment]
@KTom101 Thanks for assigning me to the issue.
I came across this repository on the Codeacademy's website, in the section of docs itself https://www.codecademy.com/resources/docs
