### ISSUE TITLE
[Term Entry] General SDLC: Agile

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1803]
### Reason/inspiration (optional)

The [Software Development Lifecycle](https://www.codecademy.com/resources/docs/general/software-development-life-cycle) Model to cover:

- Agile: Iterative development and continuous integration. The scrum methodology is a common implementation of the agile model in which teams work in sprints. Sprints are time-constrained periods where a team works to complete a certain goal.

Please write a new entry and expand on the above introductory paragraph under:  content/general/concepts/software-development-life-cycle/terms/ about the Agile model.

To get started with the PR and entry file:

Under content/general/concepts/software-development-life-cycle/terms/, create a new folder called `agile`. Then create a new file called `agile.md` under content/general/concepts/software-development-life-cycle/terms/`agile`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by KTom101** [comment]
@aherman91 You're assigned! Please follow the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) while working on this entry. 😁

**Comment by aherman91** [comment]
Hey @SSwiniarski, just submitted a [pull request](https://github.com/Codecademy/docs/pull/1879). Thank you!
