### ISSUE TITLE
[Term Entry] General SDLC: Big Bang

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1804]
### Reason/inspiration (optional)

The [Software Development Lifecycle](https://www.codecademy.com/resources/docs/general/software-development-life-cycle) Model to cover:

- Big Bang: Named after the physical theory, this model involves creating a product through available resources for technical development. There is little planning or documenting.

Please write a new entry and expand on the above introductory paragraph under:  content/general/concepts/software-development-life-cycle/terms/ about the Big Bang model.

To get started with the PR and entry file:

Under content/general/concepts/software-development-life-cycle/terms/, create a new folder called `big-bang`. Then create a new file called `big-bang.md` under content/general/concepts/software-development-life-cycle/terms/`big-bang`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by esand68** [comment]
@esand68 - I would like to work on this issue. Feel free to assign . This would be my first Open Source contribution!

**Comment by yangc95** [comment]
@esand68 since you have two issues assigned to you already, I'd like to see if another contributor would like to take this one instead.

@cslylla would you like to take this one on as opposed to the other SDLC model?

**Comment by esand68** [comment]
sure no problem. I'll get going on my two.

**Comment by cslylla** [comment]
@yangc95  Yes, I would like to take this issue!
