### ISSUE TITLE
[Term Entry] General SDLC: Iterative

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1805]
### Reason/inspiration (optional)

The [Software Development Lifecycle](https://www.codecademy.com/resources/docs/general/software-development-life-cycle) Model to cover:

- Iterative: Depending on the requirements of the product, the software is modified upon each iteration and changes are released as a new version of the software.

Please write a new entry and expand on the above introductory paragraph under:  content/general/concepts/software-development-life-cycle/terms/ about the Iterative model.

To get started with the PR and entry file:

Under content/general/concepts/software-development-life-cycle/terms/, create a new folder called `iterative`. Then create a new file called `iterative.md` under content/general/concepts/software-development-life-cycle/terms/`iterative`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by esand68** [comment]
@esand68   I will gladly take this on.  Looking to make my first open source contribution

**Comment by cslylla** [comment]
Is this issue still available? If so, I would like to write this article!

**Comment by yangc95** [comment]
@esand68 thanks for your patience. I assigned you to another issue but wanted to see if you'd want to take this one as well. If you'd rather take on just one issue at a time, that is great as well

**Comment by esand68** [comment]
I will happily take on both. .I just finished the codecademy git course, so
the mechanics of a pull request is still  new to me. Please bear with me
:)   Thanks Christine

**Comment by yangc95** [comment]
🙌 @esand68 that's cool with me! If anything changes let me know, otherwise this Issue is assigned to you.
