### ISSUE TITLE
[Term Entry] General SDLC: Prototype

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1806]
### Reason/inspiration (optional)

The [Software Development Lifecycle](https://www.codecademy.com/resources/docs/general/software-development-life-cycle) Model to cover:

- Agile: Iterative development and continuous integration. The scrum methodology is a common implementation of the agile model in which teams work in sprints. Sprints are time-constrained periods where a team works to complete a certain goal.

Please write a new entry and expand on the above introductory paragraph under:  content/general/concepts/software-development-life-cycle/terms/ about the Prototype model.

To get started with the PR and entry file:

Under content/general/concepts/software-development-life-cycle/terms/, create a new folder called `prototype`. Then create a new file called `prototype.md` under content/general/concepts/software-development-life-cycle/terms/`prototype`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by onekir** [comment]
@yangc95 @SSwiniarski Hi! I'd like to contribute to this issue. I have experience with Software Development Life Cycle.

**Comment by SSwiniarski** [comment]
@onekir If this is your first contribution, what brought you to Docs?

You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

Also see [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for styling tips.

After creating a PR, maintainer(s) (with the collaborater label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by SSwiniarski** [comment]
@onekir It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by onekir** [comment]
> @onekir It's been two weeks. Are you still working on this issue? Do you need assistance?

@SSwiniarski I'm still actively working on this issue and plan to complete it very soon.
