### ISSUE TITLE
[Term Entry] General SDLC: Rapid Application Development

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1807]
### Reason/inspiration (optional)

The [Software Development Lifecycle](https://www.codecademy.com/resources/docs/general/software-development-life-cycle) Model to cover:

- Rapid Application Development (RAD): Meets requirements through prototyping iteratively.

Please write a new entry and expand on the above introductory paragraph under:  content/general/concepts/software-development-life-cycle/terms/ about the Rapid Application Development model.

To get started with the PR and entry file:

Under content/general/concepts/software-development-life-cycle/terms/, create a new folder called `rapid-application-development`. Then create a new file called `rapid-application-development.md` under content/general/concepts/software-development-life-cycle/terms/`rapid-application-development`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by esand68** [comment]
I would like to work on this issue. please assign me. thanks

**Comment by Codrey** [comment]
@yangc95 Hi, if possible would you be able to assign me to this issue ignorer for me to work on it.

**Comment by yangc95** [comment]
@esand68 Thanks for your patience, would you still be interested in working on this?

**Comment by esand68** [comment]
Indeed!! My first ever open source contribution !!! Sent from my iPhoneOn Apr 24, 2023, at 5:49 PM, Christine Yang ***@***.***> wrote:﻿
@esand68 Thanks for your patience, would you still be interested in working on this?

**Comment by yangc95** [comment]
Since another contributor has claimed this Issue, @Codrey I would recommend heading over to see available or [open Issues](https://github.com/Codecademy/docs/issues?q=is%3Aissue+no%3Aassignee+is%3Aopen).

In the off chance that the current assignee is unable to complete the Issue, it may be reassigned, but that is not for certain. Thanks for understanding!
