### ISSUE TITLE
[Term Entry] General SDLC: Spiral

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1808]
### Reason/inspiration (optional)

The [Software Development Lifecycle](https://www.codecademy.com/resources/docs/general/software-development-life-cycle) Model to cover:

- Spiral: Based on the waterfall and iterative models.

Please write a new entry and expand on the above introductory paragraph under:  content/general/concepts/software-development-life-cycle/terms/ about the Spiral model.

To get started with the PR and entry file:

Under content/general/concepts/software-development-life-cycle/terms/, create a new folder called `spiral`. Then create a new file called `spiral.md` under content/general/concepts/software-development-life-cycle/terms/`spiral`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by hongquant17** [comment]
I would like to contribute to this issue. Can you assign me?

**Comment by yangc95** [comment]
@hongquant17 Thanks for your patience! I've gone ahead and assigned you this issue

> You can check out the [[Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md)](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
> 
> See [[Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md)](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the  [[Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md)](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
> 
> After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by hongquant17** [comment]
Thank you, I'll do it right away
