### ISSUE TITLE
[Term Entry] General SDLC: V

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1809]
### Reason/inspiration (optional)

The [Software Development Lifecycle](https://www.codecademy.com/resources/docs/general/software-development-life-cycle) Model to cover:

- V: Based on the waterfall model.

Please write a new entry and expand on the above introductory paragraph under:  content/general/concepts/software-development-life-cycle/terms/ about the V-shaped model.

To get started with the PR and entry file:

Under content/general/concepts/software-development-life-cycle/terms/, create a new folder called `v`. Then create a new file called `v.md` under content/general/concepts/software-development-life-cycle/terms/`v`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by hongquant17** [comment]
I'm also working on my own docs about Software Development Lifecycle Model so please respond me soon and assign me. Thank you!

**Comment by hongquant17** [comment]
@yangc95 yes, I would love to be assigned, thank you.

**Comment by SSwiniarski** [comment]
@hongquant17, It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by hongquant17** [comment]
@SSwiniarski Sorry for the delay, finishing a few last details and I'm ready to commit.
