### ISSUE TITLE
[Term Entry] General SDLC: Waterfall

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1810]
### Reason/inspiration (optional)

The [Software Development Lifecycle](https://www.codecademy.com/resources/docs/general/software-development-life-cycle) Model to cover:

- Waterfall: The goal is to create a minimum viable product (MVP). Each phase in the SDLC must be completed before moving on to the next phase.

Please write a new entry and expand on the above introductory paragraph under:  content/general/concepts/software-development-life-cycle/terms/ about the Waterfall model.

To get started with the PR and entry file:

Under content/general/concepts/software-development-life-cycle/terms/, create a new folder called `waterfall`. Then create a new file called `waterfall.md` under content/general/concepts/software-development-life-cycle/terms/`waterfall`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by gracekishino** [comment]
@yangc95 please can I work on this?

**Comment by KTom101** [comment]
@gracekishino You're assigned 🎉
