### ISSUE TITLE
[Entry] Cloud Computing: Containerization

### ISSUE THREAD

**Issue by YanisaHS** [Codecademy/docs#1821]
### Reason/inspiration (optional)

Could I be assigned to this issue? 🥳 

I'd like to add a new concept entry on containerization to the [Cloud Computing](https://www.codecademy.com/resources/docs/cloud-computing) topic.

As of now, I'm thinking about structuring it like:
- Intro/general information (no heading)
- How do containers work
- - include general info and brief explanation of orchestration/Kubernetes and Docker
- Containers vs. virtual machines
- - link to existing page on [VMs](https://www.codecademy.com/resources/docs/general/virtual-machines)
- Benefits of containerization
- - scalability, portability, security, etc.
- Who uses containers?
- - (short section) link to a few other Docs pages (e.g., cloud computing, data science, machine learning)

I'm open to changes/suggestions though, as always!

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by yangc95** [comment]
@YanisaHS that sounds like a solid outline. If I have any additional comments I'll lyk!
