### ISSUE TITLE
JavaScript entries needed: Iterators, Objects

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#183]
Update: THIS ONE IS TAKEN!

2 JavaScript entries are needed:

- Iterators
- Objects

Existing Codecademy JavaScript concepts: https://www.codecademy.com/resources/docs/javascript

**Comment by sonnynomnom** [comment]
This one is taken!

**Comment by Goku-kun** [comment]
Hey, @sonnynomnom 
I'm a little confused. Is this issue only for iterator objects, or objects and iterators separately?

If it's the latter case, then there is already a Objects entry available in the JavaScript docs. Should I improve upon it? And create a brand new entry for iterators?

**Comment by sonnynomnom** [comment]
Hi @Goku-kun, this one is actually taken, so no need to worry about this one!
