### ISSUE TITLE
[Concept Entry] C: Loops

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1832]
### Reason/inspiration (optional)

Add a new entry under content/c/concepts/loops/loops.md explaining Loops in C.

The loops.md file should contain:

- General explanation of what loops are
- Explanations of the different types of loops in C include the `for` loop, `while` loop, `do...while` loop, and nested loop
- ` ```pseudo ` blocks showing a general syntax of each type of loop
- ` ```c ` code blocks giving examples for each type of loop

In addition to the [Contributing Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md), use the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) as reference while making the PR.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by braanj** [comment]
I would like to work on this entry!

**Comment by KTom101** [comment]
@braanj You've been assigned! Please make sure to follow the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) when making the PR. 

Also, how did you find out about the Docs repo?

**Comment by braanj** [comment]
@KTom101 Thanks!
I've been following Codecademy for quite some time.
