### ISSUE TITLE
[Term Entry] C# Strings `.StartsWith()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1836]
### Reason/inspiration (optional)

We would like a new term entry for [C#](https://www.codecademy.com/resources/docs/c-sharp) about the `String.StartsWith()` method.

The entry should go in a new file in docs/content/c-sharp/concepts/strings/terms/startswith/startswith.md

The entry should

- Have a syntax section illustrating the method with a ` ```pseudo ` code block.
- An example showing the method in use with a ` ```cs ` code block.
- A runnable codebyte example in a ` ```codebyte/csharp ` block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by imran5963** [comment]
I wanted to work on this project  to resolve the issue kindly give me permission to do it .

**Comment by SSwiniarski** [comment]
@imran5963 It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by SSwiniarski** [comment]
@imran5963 Because of inactivity I am unassigning you so someone else can work on this issue.

**Comment by kobrius11** [comment]
Hello, iam new to github, but i think i understand this assignment, can i work on it please

**Comment by KTom101** [comment]
You're assigned, please refer to the [[Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md)](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) as well as the documents mentioned in description while writing the entry. Once you submit a PR, wait for someone from the team (they will have the "Collaborator" badge in the top right-hand corner of comments) to review it.

Can I ask how did you come across the Codecademy Docs repo?

**Comment by kobrius11** [comment]
Hello, i made a pr, waiting for someone to review, thanks for letting me be a part of this.
I came across codeacademy from google and facebook ads, bought myself pro membership, and came across Introduction to Open Source course, thats how I found this repository.
