### ISSUE TITLE
[Edit] C# Math Functions: .Max(), .Pow(), .Sqrt()

### ISSUE THREAD

**Issue by cslylla** [Codecademy/docs#1846]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Edit the markdowns located inside these directories:

docs/content/c-sharp/concepts/math-functions/terms/max/max.md
docs/content/c-sharp/concepts/math-functions/terms/pow/pow.md
docs/content/c-sharp/concepts/math-functions/terms/sqrt/sqrt.md
For each file, create a new "Codebyte Example" section with a runnable codebyte example in a ```codebyte/csharp block.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by cslylla** [comment]
If the codebyte example is needed for these files, I would like to work on the issue.

**Comment by KTom101** [comment]
@cslylla You're assigned to this.
