### ISSUE TITLE
SQL entry needed: Procedures

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#185]
1 SQL entry needed:

- Procedures

**Comment by rexdivakar** [comment]
Hey @sonnynomnom  are you looking for SQL Procedures with docs ? if so please assign this to me !

**Comment by sonnynomnom** [comment]
@rexdivakar Yep, it's yours!

**Comment by Dusch4593** [comment]
Hi @rexdivakar! Brandon from the Free Team 😄 Just wanted to check in and ask if you were still working on a PR for this issue?

**Comment by SSwiniarski** [comment]
@Dusch4593, per our meeting, I'll take over from @rexdivakar for this entry.
