### ISSUE TITLE
[Term Entry] Java Errors: `ConcurrentModificationException` 

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1867]
### Reason/inspiration (optional)

Add a new entry under content/java/concepts/errors/terms/concurrentmodificationexception/concurrentmodificationexception.md explaining the `ConcurrentModificationException` Exception. 

The concurrentmodificationexception.md file should include a short explanation of the exception.

In addition to the [Contributing Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md), use the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) as reference when making the PR.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Toseef-Ahmad** [comment]
**Hy**, I am New here as a contributor, can you assign me this **Issue**.

**Comment by KTom101** [comment]
@Toseef-Ahmad Assigned, please use the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) as a guideline while creating the PR. Also, how did you find out about the Codecademy Docs repo?

**Comment by Toseef-Ahmad** [comment]
Sure, I will follow the guidelines, I find it by learning the GIT & GITHUB course from **Codecademy**

**Comment by Toseef-Ahmad** [comment]
@KTom101 Please can you Review my PR?
