### ISSUE TITLE
[Concept Entry] Kotlin Enums

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1870]
### Reason/inspiration (optional)

We would like a new term entry for [Kotlin](https://www.codecademy.com/resources/docs/kotlin) about Enums.

The entry should go in a new file in docs/content/kotlin/concepts/enums/enums.md

The entry should:

- Describe what an enum is.
- Have a syntax section illustrating the creation of an enum with a  ` ```pseudo ` code block.
- An example showing an enum in use in a code block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by MinalGhate** [comment]
Hey, can you assign me this issue

**Comment by SSwiniarski** [comment]
@MinalGhate You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

Also see [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for styling tips.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by SSwiniarski** [comment]
@MinalGhate It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by SSwiniarski** [comment]
@MinalGhate because of inactivity I am unassigning you so someone else can work on this issue.

**Comment by arisdelacruz** [comment]
Can I try this one?

thanks

**Comment by SSwiniarski** [comment]
@arisdelacruz, You're assigned!

**Comment by arisdelacruz** [comment]
@SSwiniarski 

I just created a pull request for enums

Just wonderin' though, how 'bout the other nitty-gritty feats of enums?

Shall I include them also?

Thanks

**Comment by arisdelacruz** [comment]
@SSwiniarski 

per my research, so far

- enums class properties and functions 
- enums as Anonymous Classes
- use of when expression

dunno if this is exhaustive of the info available so far

thanks

**Comment by SSwiniarski** [comment]
@arisdelacruz feel free to add those details, but try to be concise.
