### ISSUE TITLE
[Concept Entry] Kotlin Operators

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1871]
### Reason/inspiration (optional)

We would like a new term entry for [Kotlin](https://www.codecademy.com/resources/docs/kotlin) about Operators.

The entry should go in a new file in docs/content/kotlin/concepts/operators/operators.md

The entry should:

- List operators with a description (possibly in a markdown table)
- Group operators by type (Arithmetic, Bitwise, Logical, Comparison etc.)

For examples of what we're looking for, see the Operators entries for [C++](https://www.codecademy.com/resources/docs/cpp/operators), [Java](https://www.codecademy.com/resources/docs/java/operators), [C#](https://www.codecademy.com/resources/docs/c-sharp/operators)

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by JuanGabrielTerrazasSarmiento** [comment]
Hi! I'd like to contribute to this Concept Entry.

**Comment by yangc95** [comment]
@JuanGabrielTerrazasSarmiento If this is your first contribution, what brought you to Docs?

> You're assigned! You can check out the [[Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md)](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
> 
> See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the  [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
