### ISSUE TITLE
[Concept Entry] C Enums

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1872]
### Reason/inspiration (optional)

We would like a new term entry for [C](https://www.codecademy.com/resources/docs/c) about Enums.

The entry should go in a new file in docs/content/c/concepts/enums/enums.md

The entry should:

- Describe what an enum is.
- Have a syntax section illustrating the creation of an enum with a  ` ```pseudo ` code block.
- An example showing an enum in use in a ` ```c ` code block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
@RodMe27 I just noticed that you went ahead and did a PR for this issue without first claiming it. That fortunately wasn't an issue in this case, as no one else tried to claim this issue, but in future you need to post on an issue claiming it and wait for a maintainer to assign it to you before moving forward on a PR. This is because otherwise we may have multiple people working on the same issue.

**Comment by yangc95** [comment]
@RodMe27 I see you're a first-time contributor! Great to have you. What brought you to the Docs repo?

**Comment by RodMe27** [comment]
@yangc95 I was doing the Github course on Codeacademy and would like to contribute with the language I have used the most. :)
