### ISSUE TITLE
[Concept Entry] PHP Switch

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1874]
### Reason/inspiration (optional)

We would like a new term entry for [PHP](https://www.codecademy.com/resources/docs/php) about the `switch case` statement.

The entry should go in a new file in docs/content/php/concepts/switch/switch.md

The entry should:

- Describe what a `switch case` statement is.
- Have a syntax section illustrating the creation of an `switch case` with a  ` ```pseudo ` code block.
- An example showing `switch case` in use in a ` ```php ` code block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by apostoliadel** [comment]
Hi there! I'm interested in working on this issue. Could I please be assigned to it? Thank you!

**Comment by SSwiniarski** [comment]
@apostoliadel You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

Also see [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for styling tips.
