### ISSUE TITLE
[Entry] SASS: Create new SASS entry

### ISSUE THREAD

**Issue by ta-erin** [Codecademy/docs#1877]
### Reason/inspiration (optional)

Hi,

I noticed there's no entry in the docs on SASS.

Would it be helpful to add one? If so, can it be assigned to me?

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by yangc95** [comment]
@ta-erin We do have sass as a supported code block so I think it would be good to mention. I'm thinking this entry can either be places as a concept under general or css.

I'm wondering what @caupolicandiaz and @KTom101 think about this and which topic it would fall best under.

**Comment by KTom101** [comment]
@yangc95 I feel under CSS would work best.

**Comment by yangc95** [comment]
@KTom101 Sounds good! @ta-erin, let's create this concept entry under the CSS topic.

Let us know if you have any further questions!

> You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
> 
> Also see [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for styling tips.

After creating a PR, maintainer(s) (with the collaborater label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by KTom101** [comment]
> @KTom101 Sounds good! @ta-erin, let's create this concept entry under the CSS topic.
> 
> Let us know if you have any further questions!
> 
> > You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
> > Also see [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for styling tips.
> 
> After creating a PR, maintainer(s) (with the collaborater label) will add in comments/suggestions to address any revisions prior to approving.

@ta-erin In addition to @yangc95 comment, the file path would be `content/css/concepts/sass/sass.md`. Please add the contents in the `sass.md` file.

**Comment by SSwiniarski** [comment]
@ta-erin It's been over two weeks. Are you still working on this issue? Do you need assistance?

**Comment by ta-erin** [comment]
@SSwiniarski - sorry for the delay. 

I've hit a busy period at work - we have a big release coming up. 

If you need to reassign I totally understand, if not I would love to finish this next week, after our release!

Thanks

**Comment by SSwiniarski** [comment]
@ta-erin It's been another three weeks. Are you still working on this issue?

**Comment by SSwiniarski** [comment]
@ta-erin because of inactivity, I am unassigning you so someone else can work on this issue.

**Comment by lloan** [comment]
Hi, I'd like to contribute by taking this one up.

**Comment by SSwiniarski** [comment]
@lloan You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@lloan It's been two weeks. Are you still working on this entry? Note that in another week this will be unassigned due to inactivity.

**Comment by lloan** [comment]
@SSwiniarski #2662
