### ISSUE TITLE
[Concept Entry] R Switch

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1878]
### Reason/inspiration (optional)

We would like a new term entry for [R](https://www.codecademy.com/resources/docs/r) about the `switch()` function.

The entry should go in a new file in docs/content/r/concepts/switch/switch.md

The entry should:

- Describe what the `switch()` function is.
- Have a syntax section illustrating the use of the `switch()` function with a  ` ```pseudo ` code block.
- An example showing the `switch()` function in use in a ` ```r ` code block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Markierra** [comment]
Hi, I would like to give this a shot!

**Comment by SSwiniarski** [comment]
@Markierra It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by Markierra** [comment]
Hi, sorry for the delay!  I actually was going through a module on code academy and it instructed me to find an issue to fix. Unfortunately, my skillset doesn’t align with the skillset needed to complete the objectives at this time. Thank you for following up and I wish you the best of luck on your project. Sent from Mail for Windows From: SSwiniarskiSent: Wednesday, April 26, 2023 9:53 AMTo: Codecademy/docsCc: Markierra; MentionSubject: Re: [Codecademy/docs] [Concept Entry] R Switch (Issue ***@***.*** It's been two weeks. Are you still working on this issue? Do you need assistance?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by SSwiniarski** [comment]
@Markierra Ok, I'll remove you from this issue. Keep an eye on the issues for one that you're more comfortable with.

**Comment by Masonkate** [comment]
Can I be assigned to this issue?

**Comment by braanj** [comment]
Hello,
I'd like to add this term entry!

**Comment by SSwiniarski** [comment]
@braanj You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?
