### ISSUE TITLE
C++ entry needed: Pointers

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#188]
1 C++ entry needed: 

- Pointers

**Comment by bhagyamudgal** [comment]
Can I work on this?

**Comment by sonnynomnom** [comment]
@bhagyamudgal Absolutely! Make sure to take a look at [C Pointers](https://www.codecademy.com/resources/docs/c/pointers), [Learn C++ course](https://www.codecademy.com/learn/learn-c-plus-plus), and the [Learn C++ Cheatsheet](https://www.codecademy.com/learn/learn-c-plus-plus/modules/learn-cpp-references-and-pointers/cheatsheet).

**Comment by bhagyamudgal** [comment]
@sonnynomnom Sure.

**Comment by sonnynomnom** [comment]
Done.
