### ISSUE TITLE
[Entry] AI: BEAM Search

### ISSUE THREAD

**Issue by HishamT** [Codecademy/docs#1889]
### Reason/inspiration (optional)

An entry describing the BEAM Search algorithm is requested.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Msdhart87** [comment]
Hello, I am interested in working on this issue. I was referred by Codecademy.

**Comment by HishamT** [comment]
@Msdhart87, you got it!

**Comment by Msdhart87** [comment]
Thanks so much, I’ll get right on it! Sent from my iPhoneOn Apr 13, 2023, at 12:34 PM, Hisham Touma ***@***.***> wrote:﻿
Assigned #1889 to @Msdhart87.

**Comment by HishamT** [comment]
Hey @Msdhart87, just checking in. What is the status of this entry? Are you still working on it? :grin:

**Comment by HishamT** [comment]
Hey @Msdhart87, due to inactivity, this entry will now be generated internally. However, you are still welcome to request to work on other available issues. Thank you.
