### ISSUE TITLE
[Entry] AI: Greedy Best First Search

### ISSUE THREAD

**Issue by HishamT** [Codecademy/docs#1890]
### Reason/inspiration (optional)

An entry describing the Greedy Best First Search algorithm is requested.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by yangc95** [comment]
@HishamT I'd like to take this on!

**Comment by HishamT** [comment]
You got it!

**Comment by yangc95** [comment]
Closing this one as it's completed
