### ISSUE TITLE
[Term Entry] PHP String Functions `echo()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1893]
### Reason/inspiration (optional)

We would like a new term entry for [PHP](https://www.codecademy.com/resources/docs/php) about the `echo()` function.

The entry should go in a new file in docs/content/php/concepts/string-functions/terms/echo/echo.md

The entry should

- Have a syntax section illustrating the function with a ` ```pseudo ` code block.
- An example showing the function in use with a ` ```php ` code block.
- A runnable codebyte example in a ` ```codebyte/php` block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by sriharshamajeti** [comment]
I would like to work on this.

**Comment by tokyohmachine** [comment]
Hello, I'm a student of the Codecademy course and I would like to contribute to the project by working on this issue. I have experience with echo and I think I can write a helpful entry for the Codecademy Docs. Could you please assign this issue to me? Thank you!

**Comment by SSwiniarski** [comment]
@tokyohmachine You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

Also see [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for styling tips.

After creating a PR, maintainer(s) (with the collaborater label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by tokyohmachine** [comment]
I finished. Any feedback?

**Comment by SSwiniarski** [comment]
@tokyohmachine Any comments will be made on the PR when it is reviewed.

**Comment by tokyohmachine** [comment]
I make the commit again, then the pull request. Sorry for the delay.
