### ISSUE TITLE
[Term Entry] PHP String Functions `implode()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1896]
### Reason/inspiration (optional)

We would like a new term entry for [PHP](https://www.codecademy.com/resources/docs/php) about the `implode()` function.

The entry should go in a new file in docs/content/php/concepts/string-functions/terms/implode/implode.md

The entry should

- Have a syntax section illustrating the function with a ` ```pseudo ` code block.
- An example showing the function in use with a ` ```php ` code block.
- A runnable codebyte example in a ` ```codebyte/php` block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by freshjah** [comment]
I would like to work on this. Thanks

**Comment by SSwiniarski** [comment]
@freshjah, It's been over two weeks. Are you still working on this issue? Do you need assistance?

**Comment by freshjah** [comment]
I Got sidetracked a bit and will complete it this week. Apologies for the
delay

**Comment by SSwiniarski** [comment]
@freshjah It's been another two weeks. Are you still working on this?

**Comment by freshjah** [comment]
I worked on it and uploaded...a few days ago.

**Comment by SSwiniarski** [comment]
@freshjah can you link to your pull request? I'm not seeing it [here](https://github.com/Codecademy/docs/pulls).

**Comment by SSwiniarski** [comment]
@freshjah Yes, it's there now.
