### ISSUE TITLE
[Term Entry] PHP String Functions `ltrim()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#1897]
### Reason/inspiration (optional)

We would like a new term entry for [PHP](https://www.codecademy.com/resources/docs/php) about the `ltrim()` function.

The entry should go in a new file in docs/content/php/concepts/string-functions/terms/ltrim/ltrim.md

The entry should

- Have a syntax section illustrating the function with a ` ```pseudo ` code block.
- An example showing the function in use with a ` ```php ` code block.
- A runnable codebyte example in a ` ```codebyte/php` block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by conmcdon721** [comment]
Hey there! I could work on this if you'd like.

**Comment by SSwiniarski** [comment]
@conmcdon721 If this is your first contribution, what brought you to Docs?

You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md)for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by conmcdon721** [comment]
> @conmcdon721 If this is your first contribution, what brought you to Docs?

It is indeed my first contribution! It's my first time contributing to the Codecademy docs _and_ my first time contributing to a project of this scope.
