### ISSUE TITLE
[Edit] Cybersecurity: Spear Phishing

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#1900]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

Please edit headings to AP Style for [Spear Phishing](https://www.codecademy.com/resources/docs/cybersecurity/spear-phishing)

Related PR: [#1633](https://github.com/Codecademy/docs/pull/1633)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by mssonger** [comment]
Hello @yangc95 , I'm happy to work on this issue next. I'm working through https://www.codecademy.com/courses/learn-git/kanban_projects/contributing-to-the-codecademy-docs-repository . Thank  you.

**Comment by yangc95** [comment]
@mssonger thanks for letting me know! Feel free to head over to the Issues tab and check for open and unassigned issues 🙂
