### ISSUE TITLE
[Term Entry] Java: Errors `ArithmeticException`

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#1908]
### Reason/inspiration (optional)

This is assigned.

Add a new entry under content/java/concepts/errors/terms/arithmeticexception/arithmeticexception.md explaining the `ArithmeticException`.

The ArithmeticException.md file should include a short explanation of the exception.

In addition to the [Contributing Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md), use the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) as reference when making the PR.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by tgreencc** [comment]
Can I be assigned this issue?

**Comment by KTom101** [comment]
@tgreencc Assigned!

**Comment by SSwiniarski** [comment]
Closing this as it was resolved by [1933](https://github.com/Codecademy/docs/pull/1933).
