### ISSUE TITLE
Java entry needed: HashMap

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#191]
Java entry needed:

- HashMap

**Comment by AnushaNathRoy** [comment]
@sonnynomnom I would like to take up this issue

**Comment by sonnynomnom** [comment]
Please take it @AnushaNathRoy!

**Comment by AnushaNathRoy** [comment]
@sonnynomnom 
My PR is up for review:
https://github.com/Codecademy/docs/pull/427
