### ISSUE TITLE
[Entry] Go: Generics

### ISSUE THREAD

**Issue by Pavan-Nambi** [Codecademy/docs#1926]
### Reason/inspiration (optional)

New Concept Entry of generics for go

The entry should go in a new file in docs/content/go/concepts/generics/generics.md

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Pavan-04-08** [comment]
i would like this to be self assigned

**Comment by SSwiniarski** [comment]
@Pavan-04-08 It's been over two weeks. Are you still working on this issue?

**Comment by SSwiniarski** [comment]
@Pavan-04-08, because of inactivity I am unassigning you so someone else can work on this issue.

**Comment by mfa34** [comment]
can i take sir ? @SSwiniarski

**Comment by SSwiniarski** [comment]
@mfa34 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by mfa34** [comment]
@SSwiniarski i added new entry sir. You can check my pull request, Sir.
