### ISSUE TITLE
[Edit] C# Loops: add foreach loops

### ISSUE THREAD

**Issue by Adiantum-f** [Codecademy/docs#1927]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Edit the C# loops entry to include foreach loop.

content/c-sharp/concepts/loops/loops.md

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Adiantum-f** [comment]
I'd be happy to do it.

**Comment by SSwiniarski** [comment]
@Adiantum-f I've assigned you.
