### ISSUE TITLE
C entry needed: Preprocessors

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#193]
1 C entry needed:

- Preprocessors in C

**Comment by Vivek-Prajapatii** [comment]
Hello @sonnynomnom , I am new to the open source community. I would like to take up this issue. Please brief me on the issue.

**Comment by sonnynomnom** [comment]
Hi @Vivek-Prajapatii, I assigned you the Java ArrayList one! So focus on that one, and then when you are done and no one else is willing to take this, then you can tackle this one later down the road.

**Comment by Dusch4593** [comment]
Hi @bhagyamudgal ! Brandon from the Free Team 😄 Just wanted to check in and ask if you were still working on a PR for this issue?

**Comment by bhagyamudgal** [comment]
@Dusch4593 I am not working on this issue. You can give it to someone else.
