### ISSUE TITLE
[Small Edit] PHP: add laravel

### ISSUE THREAD

**Issue by Pavan-04-08** [Codecademy/docs#1939]
### Type of Edit (select all that apply)

Clarify unclear content and/or terms

### Description (optional)

This should go in this file `https://github.com/Codecademy/docs/content/php/php.md`

https://www.codecademy.com/resources/docs/php

As the most popular php framework we would like to have some note about laravel here 
I see symfony not laravel
if you are more enthusiastic add about codeIgniter too!

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by lucagalassi** [comment]
Could this be assigned to me? Thanks :)
