### ISSUE TITLE
C entry needed: Compiling

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#194]
1 C entry needed: 

- Compiling

Codecademy Doc C topic: https://www.codecademy.com/resources/docs/c

**Comment by Vivek-Prajapatii** [comment]
Hello @sonnynomnom , I am new to the open source community. I would like to take up this issue. Please brief me on the issue.

**Comment by sonnynomnom** [comment]
Hi @Vivek-Prajapatii, I assigned you the Java ArrayList one! So tackle that one first, and then when you are done and no one else is willing to take this, then you can take this one on.

**Comment by bhagyamudgal** [comment]
Can I take this one?

**Comment by sonnynomnom** [comment]
You can @bhagyamudgal!

**Comment by SSwiniarski** [comment]
This has been done for a while.
