### ISSUE TITLE
[Term Entry] General Developer Tools: Version Control

### ISSUE THREAD

**Issue by caupolicandiaz** [Codecademy/docs#1944]
### Reason/inspiration (optional)

Version Control / Version Control Systems

Please write a new entry that explains the purpose of version control systems, the process in broad strokes, notes some of the common applications, and any other material that might be relevant, etc. 

To get started with the PR and entry file:

Under content/general/concepts/developer-tools/terms, create a new folder called version-control. Then create a new file called `version-control.md` under content/general/concepts/developer-tools/terms/version-control.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by DiogoBarros03** [comment]
Hi @caupolicandiaz. I would like to work on this issue.

**Comment by yangc95** [comment]
You're assigned! You can check out the [[Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md)](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

See [[Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md)](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the  [[Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md)](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

After creating a PR, maintainer(s) (with the collaborater label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by DiogoBarros03** [comment]
Hello @yangc95! I'm trying to improve my skills with CodeAcademy and in the Git Course it suggested this Project.
I could just skip but I feel that will give me an idea how working with GitHub feels like. It's getting better skills... with a plus ! Helping is great and I'm here to do what I can ! :)

**Comment by yangc95** [comment]
@DiogoBarros03 Love to hear that! Codecademy Docs is a great hands-on experience for learning git and GitHub ☺️ don't hesitate to reach out to any of us maintainers if you need any assistance!
