### ISSUE TITLE
[Edit] Subject: Spelling error

### ISSUE THREAD

**Issue by gladstone28** [Codecademy/docs#1954]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

    corrected error in spelling changed dahses to dashes

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by nadocodes** [comment]
Hi,
I would like to work on this issue... would you be able to provide specific typos/locations of this or will I have to find these typos myself?

**Comment by KTom101** [comment]
@gladstone28 I see you made a branch with this same correction. Were you trying to make a pull request and opened this issue by mistake?

**Comment by Mcdonnellpatrick** [comment]
I would like to work on this issue, same query as poster above. Do you have a list of locations or do I need to go check for these myself? 

I am new to Github, but was sent here through Codecademy's course. Thanks.

**Comment by KTom101** [comment]
@nadocodes @Mcdonnellpatrick I believe this issue was made by a community contributor by mistake when they meant to make a pull request. Please look for another unclaimed issue to work on or check back regularly for new issues from the [issues tab](https://github.com/Codecademy/docs/issues).

**Comment by KTom101** [comment]
@gladstone28 I'm closing this out due to no response. We can open this back up later if needed or you can make a pull request directly if this is a small change you've found. Thank you.

**Comment by gladstone28** [comment]
I am new Yes, I made and error. It's OK to close. I will improve.

**Comment by gladstone28** [comment]
Ok, thank you.
________________________________
