### ISSUE TITLE
[Entry] Subject: Entry Name GIT LOG [GIT]

### ISSUE THREAD

**Issue by filipacosta430** [Codecademy/docs#1996]
### Reason/inspiration (optional)

I was looking for git commands on Codecademy Docs, and I realized you don't mean anything about git log.
If you considered it is usefull, I woul like to contribute to git log on Codecademy Docs.

If so, can I be assigned to this issue?

I knew about Codecademy Docs from Codecademy Pro.

best regards,
Filipa

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by RaffyRod** [comment]
I want this one please!!

**Comment by KTom101** [comment]
@RaffyRod Since @filipacosta430 opened the issue and requested to be assigned in the description, this will be assigned to them. Please check to see if there is another unclaimed issue you would like to work on. You can also check back regularly for new [issues](https://github.com/Codecademy/docs/issues).

**Comment by KTom101** [comment]
@filipacosta430 Before I assign you where were you thinking of adding the information on `git log`? Under Git: [Commit](https://www.codecademy.com/resources/docs/git/commit)? 

@yangc95 @SSwiniarski I'm also curious about where you think this should go.

**Comment by KTom101** [comment]
@filipacosta430 I will assign this to you. Please make a new concept entry under `docs/content//git/concepts/log/log.md`. In addition to the [Contributing Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md), use the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) as reference when making the PR.


If for any reason you feel you can not work on this anymore, let us know so we can reassign. Please note we would like to see some progress in 5-7 days. Once a PR is submitted, please wait for someone marked with the "collaborator" badge (like myself) to view your work.

**Comment by filipacosta430** [comment]
i'm sorry for my delay, but I got sick, and I couldn't.
I'm feeling well right now, but I have my work delayed, so I will not be able to solve this issue. You can assign to someone else.

I'm really sorry.!

**Comment by RaffyRod** [comment]
@KTom101 I can take it since @filipacosta430 is not able to do it.

**Comment by KTom101** [comment]
@filipacosta430 Thanks for letting us know!

**Comment by KTom101** [comment]
@RaffyRod Yes, you can work on this.

**Comment by RaffyRod** [comment]
@KTom101  @yangc95 @SSwiniarski  added https://github.com/Codecademy/docs/pull/2236 for this one.
