### ISSUE TITLE
TEST [Concept Entry] JavaScript Statements

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2005]
### Reason/inspiration (optional)

We would like a new term entry for JavaScript about Statements.

The entry should go in a new file in `docs/content/javascript/concepts/statements/statements.md` (note the dashes rather than underscores)

The entry should:

- Describe statements in JavaScript with an intro paragraph (2-3 sentences). Include headers like semicolons and keywords (linking out to internal doc entries as appropriate) 
- Include code blocks where appropriate such as to show an exampel of a statement.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by jrood** [comment]
this was a test
