### ISSUE TITLE
[Concept Entry] JavaScript Window

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2007]
### Reason/inspiration (optional)

We would like a new term entry for JavaScript about the Window object.

The entry should go in a new file in `docs/content/javascript/concepts/window/window.md`

The entry should:

- Have an introductory paragraph (2-3 sentences). Describe the window object in terms of the browser. Include headers like object model.
- Include syntax (although not necessarily a header for this) of what calling a method on the window would look like.
- Segway into window functions where a terms table will eventually appear.

Please refer to the [entry template](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Suecalle** [comment]
@yangc95 , Im interested in taking this issue on .

**Comment by SSwiniarski** [comment]
@Suecalle You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

Also see [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for styling tips.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

If this is your first contribution, how did you come across this repo?

**Comment by Suecalle** [comment]
Im doing  learn Git & GitHub course and one of the projects is contributing to this repo.

**Comment by SSwiniarski** [comment]
@Suecalle because of inactivity I am unassigning you so someone else can work on this.

**Comment by SSwiniarski** [comment]
I'm taking this on myself because there are a number of term PRs already submitted that are supposed to live under this concept.
