### ISSUE TITLE
[Term Entry] JavaScript Window setTimeout()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2008]
### Reason/inspiration (optional)

We would like a new term entry for JavaScript's Window Functions.

The entry should go in a new file in `docs/content/javascript/concepts/window/terms/setTimeout/setTimeout.md`

The entry should:

- Have a syntax section illustrating the setTimeout() function.
- An example showing how to use this function..

Please refer to the [term template](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by RaffyRod** [comment]
@yangc95  I would like to work on this one

**Comment by SSwiniarski** [comment]
@RaffyRod You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

Also see [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for styling tips.

After creating a PR, maintainer(s) (with the collaborater label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by RaffyRod** [comment]
@SSwiniarski will start working on it
