### ISSUE TITLE
[Concept Entry] Cybersecurity Phishing

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2009]
### Reason/inspiration (optional)

We would like a new term entry for [Cybersecurity](https://www.codecademy.com/resources/docs/cybersecurity) about Phishing

The file should be located at `docs/content/cybersecurity/concepts/phishing/phishing.md`

The entry should:

- Describe the concept of phishing. 
- Explain baisc countermeasures to fight phishing. 
- Mention the difference between phishing and [spear phishing](https://www.codecademy.com/resources/docs/cybersecurity/spear-phishing) or whaling.. 
- Link mentions of other cybersecurity concepts to their entries where appropriate.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by cslylla** [comment]
I would like to work on this issue ☺️

**Comment by SSwiniarski** [comment]
@cslylla  It's been two weeks. Are you still working on this issue? Do you need assistance?
