### ISSUE TITLE
[Concept Entry] Cybersecurity Ransomware

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2010]
### Reason/inspiration (optional)

We would like a new term entry for [Cybersecurity](https://www.codecademy.com/resources/docs/cybersecurity) about Ransomware 

The file should be located at `docs/content/cybersecurity/concepts/ransomware/ransomware.md`

The entry should: 

- Describe the concept of ransomware. 
- Explain baisc countermeasures to fight ransomware. 
- Link mentions of other cybersecurity concepts to their entries where appropriate. 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by JohnSteeleCG** [comment]
Hello 👋 I would like to give this a try.

**Comment by SSwiniarski** [comment]
@JohnSteeleCG You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

Also see [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for styling tips.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

If this is your first time contributing, how did you come across this repo?

**Comment by JohnSteeleCG** [comment]
It's my second contribution but my first Concept Entry 😄
