### ISSUE TITLE
[Term Entry] PHP String Functions strpos()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2013]
### Reason/inspiration (optional)

We would like a new term entry for [PHP](https://www.codecademy.com/resources/docs/php) about the `strpos()` function.

The entry should go in a new file in `docs/content/php/concepts/string-functions/terms/strpos/strpos.md`

The entry should

- Have a syntax section illustrating the function with a ` ```pseudo ` code block.
- An example showing the function in use with a ` ```php ` code block.
- A runnable codebyte example in a ` ```codebyte/php` block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by KTom101** [comment]
@Nrj27 You're now officially assigned. I see this fixes one of the problems @SSwiniarski stated. Please make the remainder corrections for your [PR](https://github.com/Codecademy/docs/pull/2533) so that the review process can continue, thank you.

**Comment by SSwiniarski** [comment]
@Nrj27 I am unassigning you since you closed the PR you submitted.

**Comment by Judis07** [comment]
Hello, I would like to contribute on this issue. Thanks

**Comment by SSwiniarski** [comment]
@Judis07 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by caupolicandiaz** [comment]
https://github.com/Codecademy/docs/pull/2618

**Comment by SSwiniarski** [comment]
@caupolicandiaz wrong PR, (2618)[https://github.com/Codecademy/docs/pull/2618] was `stripos()` not `strpos()`

**Comment by arisdelacruz** [comment]
is this still being done by someone else

can i take this one

thanks

**Comment by SSwiniarski** [comment]
@arisdelacruz this is being done by @Judis07.
