### ISSUE TITLE
[Term Entry] PHP String Functions stripos()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2014]
### Reason/inspiration (optional)

We would like a new term entry for [PHP](https://www.codecademy.com/resources/docs/php) about the `stripos()` function.

The entry should go in a new file in docs/content/php/concepts/string-functions/terms/stripos/stripos.md

The entry should

- Have a syntax section illustrating the function with a ` ```pseudo ` code block.
- An example showing the function in use with a ` ```php ` code block.
- A runnable codebyte example in a ` ```codebyte/php` block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Jess-G95** [comment]
Hi, I'd like to work on this please. Thanks!

**Comment by SSwiniarski** [comment]
@Jess-G95 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by Jess-G95** [comment]
Thanks! 

To answer your question about how I came across this repo: I have been a developer for about 18 months but was looking for ways to gain experience in technical writing. I came across [this repo](https://github.com/dharmelolar/technical-writing-resources#open-source-projectsprograms-technical-writers-can-contribute-to) with technical writing resources which listed Codecademy Docs.

**Comment by Jess-G95** [comment]
I see the instructions say to put the `stripos()` function in a new file in docs/content/php/concepts/string-functions/terms/echo/echo.md but that file already exists with the `echo()` function. Am I right in assuming that the new entry for `stripos()` would need to be in docs/content/php/concepts/string-functions/terms/stripos/stripos.md?

**Comment by SSwiniarski** [comment]
@Jess-G95 you got it. That was an error in the issue description. I'll fix that now.
