### ISSUE TITLE
[Concept Entry] AI Convolutional Neural Networks (CNN)

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2016]
### Reason/inspiration (optional)

We would like a new concept entry for Convolutional Neural Networks (CNN)

The entry should go in a new file in docs/content/ai/concepts/neural-networks/terms/convolutional-neural-networks/convolutional-neural-networks.md

The entry should
- Describe what a CNN is.
- Describe its relation to AI.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by kapoorsaumitra** [comment]
I'd like to work on this issue

**Comment by yangc95** [comment]
@kapoorsaumitra You're assigned! You can check out the [Contribution Guide](<https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md>) for additional information on contributing.


See [Content Standards](<https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md>) for an overview of styling tips that the [Style Guide](<https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md>) covers in detail.


After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by SSwiniarski** [comment]
@kapoorsaumitra It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by kapoorsaumitra** [comment]
I'm still working on this!
