### ISSUE TITLE
[Concept Entry] AI Recurrent Neural Networks (RNN)

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2017]
### Reason/inspiration (optional)

We would like a new concept entry for Recurrent Neural Networks (RNN)

The entry should go in a new file in docs/content/ai/concepts/neural-networks/terms/recurrent-neural-networks/recurrent-neural-networks.md

The entry should
- Describe what a RNN is.
- Describe its relation to AI.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by tuhinaww** [comment]
@codecademy-docs @SSwiniarski Can I work on this?

**Comment by SSwiniarski** [comment]
@tuhinaww You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment]
@tuhinaww It's been two weeks. Are you still working on this entry? Do you need assistance?

**Comment by tuhinaww** [comment]
Hi, I apologize due to some unavoidable situation I won't be able to work on this issue anymore.

**Comment by SSwiniarski** [comment]
@tuhinaww thanks for letting us know.

**Comment by Aproposofgenius** [comment]
Hello, if this is still available can I claim it?

**Comment by SSwiniarski** [comment]
@Aproposofgenius You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by apropos0** [comment]
Hi @SSwiniarski the MR is still pending a second review, is there someone I could @ for help?

**Comment by SSwiniarski** [comment]
@apropos0 be patient. One of the other maintainers will review it. There's just a high volume of reviews.

**Comment by keerthana1702** [comment]
Hello @SSwiniarski sir, can I work on it?

**Comment by SSwiniarski** [comment]
@keerthana1702 there is already someone assigned to this and a PR is being reviewed. Please find an unclaimed issue to take on.
