### ISSUE TITLE
[Concept Entry] AI Gradient Descent

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2018]
### Reason/inspiration (optional)

We would like a new concept entry for Gradient Ascent

The entry should go in a new file in docs/content/ai/concepts/search-algorithms/terms/gradient-descent/gradient-descent.md

The entry should
- Describe the method of Gradient Descent
- Describe its relation to AI.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by YanisaHS** [comment]
Should this be Gradient Descent (instead of Ascent)? I think it's more common to be introduced to gradient descent first.

Also, can you assign it to me? ☺️ And confirm it's alright if I switch it to Gradient DEscent? (I'll still mention what gradient descent vs ascent is)

**Comment by HishamT** [comment]
@YanisaHS, please note the changes made to the location and file names of this entry.
