### ISSUE TITLE
[Concept Entry] R Conditionals

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2020]
### Reason/inspiration (optional)

We would like a new concept entry for Conditionals

The entry should go in a new file in docs/content/r/concepts/conditionals/conditionals.md

The entry should
- Describe conditional statements such as if-else
- Review the use of comparison operators such as: <,>,==           
- Review the use of logical operators such as: and, or

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by jdagz28** [comment]
I would like to work on this issue

**Comment by SSwiniarski** [comment]
@jdagz28  It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by jdagz28** [comment]
Yes. Still working on this one.
