### ISSUE TITLE
[Concept Entry] R Strings

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2021]
### Reason/inspiration (optional)

We would like a new concept entry for Strings

The entry should go in a new file in docs/content/r/concepts/strings/strings.md 

The entry should
- Have a section that describes strings
- A syntax psuedo block for strings
- One or more example blocks for the use of strings 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Roshanbhadauriya** [comment]
Hey!
I would like to on this assignment.

**Comment by SSwiniarski** [comment]
@Roshanbhadauriya You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

Also see [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for styling tips.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

If this is your first contribution, how did you come across this repo?
