### ISSUE TITLE
[Concept Entry] R Matrices

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2022]
### Reason/inspiration (optional)

We would like a new concept entry for Matrices

The entry should go in a new file in docs/content/r/concepts/matrices/matrices.md 

The entry should 
- A "Syntax" section with a ```pseudo code snippet that describes the common structure(s) of matrices.
- A section about accessing and updating elements in a matrix (with example ```r snippet).
- A section about common operations with matrices (with example ```r snippet).

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Yashi11** [comment]
Hey!!
May I help in this one under Social Summer of Code 2023??
Regards

**Comment by KTom101** [comment]
@Yashi11 Hi 👋 Thanks for your interest. As to not waste your time, I just want to make sure that this qualifies for the program you mentioned (SSOC).  Were you given a list of repos you could contribute to or can you contribute to any repo?

Again, just making sure in case you're doing this just for participation in the program.

**Comment by KTom101** [comment]
@Yashi11 Another participant shared with me how these issues are showing up on `quine.sh` which I understand is being used for the program. 

I've gone ahead and assigned you. Please make sure you have reviewed all the documents linked out in the issue description and the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) before submitting a PR. After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by Yashi11** [comment]
Yup...I checked ig this repo doesnt come under SSOC. Though I would love to contribute here after the program ends. Sorry for the trouble. ☺

**Comment by KTom101** [comment]
@Yashi11 That's alright, I've unassigned you and you can come back later on to contribute on your own if you choose!

Do you know if there is an email address to contact an administrator of SSOC? I think there may be some confusion on what contributions qualify since you're not the only participant that has come to us.

**Comment by KTom101** [comment]
@Yashi11 Hi, I'm reaching out again in case you still wanted to work on this. Our team reached out to a few people working with SSOC and it looks like it's ok for participants to work on this. Just let me know if you still want to 😄.

**Comment by Yashi11** [comment]
Yeah sure....that will be awesome.

**Comment by KTom101** [comment]
@Yashi11 You're re-assigned! 🎉

**Comment by Yashi11** [comment]
Hey! I have added the corresponding PR for this issue. Do et me know if any changes are required, I will be happy to help.
Regards.
