### ISSUE TITLE
[Term Entry] Swift Dictionaries .removeValue()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2023]
### Reason/inspiration (optional)

We would like a new term entry for Swift Dictionaries

The entry should go in a new file in docs/content/swift/concepts/dictionaries/terms/removeValue/removeValue.md 

The entry should 
- A "Syntax" section with a ```pseudo code snippet that describes the Swift Dictionary method, `.removeValue()`.
- A "Example" section (with example ```swift snippet).

Please refer to the [term template](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
@filming If this is your first contribution, what brought you to Docs?

You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by filming** [comment]
Hello!

> @filming If this is your first contribution, what brought you to Docs?

I was brought here from Codecademy's "Learn Git & Github" course.

> After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

Alright that's great, thank you.
