### ISSUE TITLE
[Term Entry] Swift Dictionaries .removeAll()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2024]
### Reason/inspiration (optional)

We would like a new term entry for Swift Dictionaries

The entry should go in a new file in docs/content/swift/concepts/dictionaries/terms/removeAll/removeAll.md 

The entry should 
- A "Syntax" section with a ```pseudo code snippet that describes the Swift Dictionary method, `.removeAll()`.
- A "Example" section (with example ```swift snippet).

Please refer to the [term template](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Dophey** [comment]
Hi there, I would like to claim this issue if possible :)

**Comment by yangc95** [comment]
@Dophey If this is your first contribution, what brought you to Docs?

You're assigned! You can check out the [[Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md)](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

> See [[Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md)](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the  [[Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md)](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
> 
> After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
