### ISSUE TITLE
[Term Entry] Swift Dictionaries .updateValue()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2025]
### Reason/inspiration (optional)

We would like a new term entry for Swift Dictionaries

The entry should go in a new file in docs/content/swift/concepts/dictionaries/terms/updateValue/updateValue.md 

The entry should 
- A "Syntax" section with a ```pseudo code snippet that describes the Swift Dictionary method, `.updateValue()`.
- A "Example" section (with example ```swift snippet).

Please refer to the [term template](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by WiggleXO** [comment]
Hi, I would like to work on this issue please :)

**Comment by SSwiniarski** [comment]
@WiggleXO You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

Also see [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for styling tips.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
