### ISSUE TITLE
[Concept Entry] Ruby: JRuby

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#2028]
### Reason/inspiration (optional)

Please write a new entry under:
content/ruby/concepts/ about the JRuby.

- An introductory paragraph (2-3 sentences) explaining what JRuby is (an implementation of Ruby on JVM).
- Link out to appropriate entries.
- Break down concept into digestible sections with headers. 

To get started with the PR and entry file:

Under content/ruby/concepts/, create a new folder called `jruby`. Then create a new file called `jruby.md`. The full path should be: content/ruby/concepts/jruby/jruby.md

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by yangc95** [comment]
@samfram I created the issue based on the discussion in Issue [1725](https://github.com/Codecademy/docs/issues/1725).

If you can run by here what headers you'll be covering, we can continue from there. Thanks!

**Comment by KN-Srilekha** [comment]
@yangc95 I am interested in this issue.

**Comment by yangc95** [comment]
@Saif-Alm Due to inactivity, I'm marking this issue as unassigned. If you decide to work on this Issue, please let us know and we can get started again 🙂

**Comment by Saif-Alm** [comment]
@yangc95 I never requested an assignment for this issue. I believe you have mistaken me for someone else, please double-check. Thanks!

**Comment by yangc95** [comment]
Whoops! Thanks for catching that.

@samfram, the previous message was meant for you:

> Due to inactivity, I'm marking this issue as unassigned. If you decide to work on this Issue, please let us know and we can get started again

**Comment by neilwrobinson** [comment]
Hi Christine @yangc95, could you please assign this to me?

I wrote a JRuby concept post, I would love to add this. 

I have two main sections on Why Should you use JRuby and JRuby Trade-offs. 

Thanks,

Neil

**Comment by yangc95** [comment]
could you please assign this to me?
> 
> I have two main sections on Why Should you use JRuby and JRuby Trade-offs. 
> 

@neilwrobinson That would be great! Your expertise is much appreciated ☺️ Those headers would work well for blog format, but since Docs is for information purposes rather than having an agenda to convince the reader of something:

I'd suggest going one step further and using headers that explain the technicalities of JRuby. Like for trade offs, talk about interpreter differences which can be thought of as a trade off, but perhaps with another wording and adjust the headers accordingly

**Comment by neilwrobinson** [comment]
Information purposes! Got it. I will adjust my writing. 

I will explain the technicalities and interpreter differences as well. 

Christine, thanks so much for the feedback. 😊
