### ISSUE TITLE
[Term Entry] SwiftUI Views Spacer()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2047]
### Reason/inspiration (optional)

We would like a new term entry for SwiftUI Views

The entry should go in a new file in docs/content/swiftui/concepts/views/terms/spacer/spacer.md 

The entry should 
- A "Syntax" section with a ```pseudo code snippet that describes the SwiftUI View, `Spacer()`.
- A "Example" section (with example ```swift snippet) with respective image (goes in media/ folder).

Please refer to the [term template](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by jlewr** [comment]
Hi @codecademy-docs - I'd be interesting in taking this on. I'm following the 'Contributing to the Codecademy Docs' project as part of the iOS Developer Career Path. :)

**Comment by SSwiniarski** [comment]
@jlewr You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by jlewr** [comment]
Completed draft entry and submitted pull request here: https://github.com/Codecademy/docs/pull/2174

**Comment by NataliaIstratii** [comment]
hy. i'm interested in taking this issue on.

**Comment by bruce0221** [comment]
Hi codecademy-docs, 
For project (contribute to Codecademy Docs) under IOS developer career course, need to  contribute an entry.
Please let me work on this issue ( SwiftUI Views Spacer())

**Comment by SSwiniarski** [comment]
@bruce0221, this issue has already been assigned and has a PR open for it. Please look at the [issues list](https://github.com/Codecademy/docs/issues) and find an unclaimed issue to request.
