### ISSUE TITLE
[Concept Entry] SwiftUI Fonts

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2048]
### Reason/inspiration (optional)

We would like a new concept entry for SwiftUI 

The edit should go in an existing file in docs/content/swiftui/concepts/fonts/fonts.md 

The entry should
- Explain `Font` `struct` (structure) in SwiftUI.
- Include header with section about standard fonts like `.largeTitle` (type property).
- Include an example with accompanying image (in media/ folder)

Please refer to the [entry template](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by gracekishino** [comment]
Please can I work on this issue?

**Comment by SSwiniarski** [comment]
@gracekishino You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by SSwiniarski** [comment]
@gracekishino It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by gracekishino** [comment]
> @gracekishino It's been two weeks. Are you still working on this issue? Do you need assistance?

@SSwiniarski sorry for the delay! It's taking me a bit more time to research this one, but I think I can make a pull request in the next few days.
