### ISSUE TITLE
[Concept Entry] Kotlin Sets

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2049]
### Reason/inspiration (optional)

The new file will go under the content/kotlin/concepts/set/sets.md

In the “sets.md” file  provide explanations on the different was to create a set  e.g. `setOf()` (immutable) and `mutableSetOf()` (mutable) . Also include examples in ` ```kotlin ` code snippets.

In addition to the [Contributing Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md), use the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) as reference when making the PR.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by mfa34** [comment]
Can i take @codecademy-docs  ?

**Comment by SSwiniarski** [comment]
@mfa34, You're assigned!

Note that we limit people to claiming no more than three open issues at once. Please submit some PRs before you claim any new issues.
