### ISSUE TITLE
[Concept Entry] Kotlin Sequences

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2050]
### Reason/inspiration (optional)

Please provide an entry on Kotlin Sequences. 

The new file will go under the content/kotlin/concepts/sequences/sequences.md

In the “sequences.md” file please provide an explanation on Kotlin Sequences and include any examples in  ` ```kotlin ` code snippets.

In addition to the [Contributing Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md), use the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) as reference when making the PR.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Judis07** [comment]
@codecademy-docs I would like to work on this issue. 
Thanks

**Comment by SSwiniarski** [comment]
@Judis07, you're assigned.
