### ISSUE TITLE
[Concept Entry] AI Sigmoid Function

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2054]
### Reason/inspiration (optional)

We would like a new concept entry for the Sigmoid Activation Function

The entry should go in a new file in docs/content/ai/concepts/neural-networks/terms/sigmoid-activation-function/sigmoid-activation-function.md

The entry should
- Describe what the sigmoid activation function is.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by YanisaHS** [comment]
Hi!! Can I be assigned to this one? 🥳

**Comment by KTom101** [comment]
@YanisaHS You've been assigned! 🎉

**Comment by SSwiniarski** [comment]
@YanisaHS It's been two weeks. Are you still working on this issue.? Note that in another week this issue will be unassigned due to inactivity.

**Comment by YanisaHS** [comment]
@SSwiniarski Yep! Should be done in the next day or two 😄
