### ISSUE TITLE
[Concept Entry] AI Linear Function

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2055]
### Reason/inspiration (optional)

We would like a new concept entry for the Linear Activation Function

The entry should go in a new file in docs/content/ai/concepts/neural-networks/terms/linear-activation-function/linear-activation-function.md

The entry should
- Describe what the linear activation function is.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Himasnhu-AT** [comment]
@codecademy-docs  
Hi, I would like to work on this. please assign it to me

**Comment by KTom101** [comment]
@Himasnhu-AT I've assigned this to you. This will be your second assignment. 

So you know, contributors can be assigned to up to 3 issues at a time and will have to submit pull requests for the ones they're assigned to before being assigned to any additional issues. 🙂

**Comment by Himasnhu-AT** [comment]
@KTom101 I've sent a PR.
Let me know if their ar any improvenments/updates I have to do. 
Thank-you for assigning it to me.

**Comment by SSwiniarski** [comment]
Reposted as [2700](https://github.com/Codecademy/docs/issues/2700) because I can't unlink the closed PR.
