### ISSUE TITLE
[Concept Entry] AI Gaussian Function

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2057]
### Reason/inspiration (optional)

We would like a new concept entry for the Gaussian Activation Function

The entry should go in a new file in docs/content/ai/concepts/neural-networks/terms/gaussian-activation-function/gaussian-activation-function.md

The entry should
- Describe what the Gaussian activation function is.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
@yangc95 You've claimed this issue for several months. Are you still intending to work on it, or should we release it for someone else to claim?

**Comment by yangc95** [comment]
@SSwiniarski Going to be selfish with this one and keep it 😆 thanks for being patient with this. I'm currently looking at a wide range of sources to make this easily understandable whilst also covering the concept at large

**Comment by yangc95** [comment]
@SSwiniarski  Apologies as I was unable to complete this assignment. However it's free for the taking now! Thank you for your patience nonetheless

**Comment by arirays** [comment]
I would like to write this entry! 🚀

**Comment by DevGat718** [comment]
ill take this!

**Comment by SSwiniarski** [comment]
@arirays You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@DevGat718, @arirays claimed this first.

**Comment by DevGat718** [comment]
copy

**Comment by SSwiniarski** [comment]
@arirays It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by arirays** [comment]
Yes, I'm still working on this issue.
