### ISSUE TITLE
[Concept Entry] HTML Quotations

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2065]
### Reason/inspiration (optional)

We would like a new term entry for [HTML](https://www.codecademy.com/resources/docs/html) about the Quotations. 

The entry should go in a new file in `docs/content/html/concepts/quotations/quotations.md` 

The entry should have

- An introduction to quotations in HTML.
- Cover long and short quotation tags.
- Provide example with html code blocks.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Roshanbhadauriya** [comment]
I want to work on this issue.

**Comment by yangc95** [comment]
@Roshanbhadauriya If this is your first contribution, what brought you to Docs?

> You're assigned! You can check out the [[Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md)](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
> 
> See [[Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md)](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the  [[Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md)](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
> 
> After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by Roshanbhadauriya** [comment]
@yangc95 I have completed my task.

**Comment by Hassan-fayez** [comment]
can i please wokr on this issue

**Comment by yangc95** [comment]
@Hassan-fayez This issue is already claimed and the assignee has already opened a valid pull request.

Please head to [open and unclaimed issues](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee) if you would like to contribute!
