### ISSUE TITLE
[Concept Entry] General Scope

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2066]
### Reason/inspiration (optional)

We would like a new term entry for [General](https://www.codecademy.com/resources/docs/general) about the Scope. 

The entry should go in a new file in `docs/content/general/concepts/scope/scope.md` 

The entry should have

- An introduction on scope.
- Pseudocode as an example to demonstrate scope. Suggest using common types/structures that relate to more than one programming language.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by rugj84** [comment]
@codecademy-docs Im interested in taking this issue. I found about Docs taking the course of Git & Github.

**Comment by SSwiniarski** [comment]
@rugj84 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by yangc95** [comment]
@rugj84 In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!
