### ISSUE TITLE
Feature Request: Page section URLs and table of contents

### ISSUE THREAD

**Issue by kaifee-haque** [Codecademy/docs#208]
- Add support for URL suffixes to link directly to page sections. For example, `https://en.wikipedia.org/wiki/Instant-runoff_voting#Global_use` links to the "Global use" section. Makes it easier for users to access related subtopics from other entries.
- Automatically generate a table of contents for each entry that contains a list of all H2 headers, possibly below the introduction section. Allows users to quickly find the content they're looking for.

[EDIT]: just realized that the actual code for Docs isn't contained in this repo. I'll submit this suggestion to the Google Forms page.

**Comment by sonnynomnom** [comment]
This is great feedback @kaifee-haque!
