### ISSUE TITLE
[Term Entry] PHP Math Functions pi()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2089]
### Reason/inspiration (optional)

We would like a new term entry for [PHP](https://www.codecademy.com/resources/docs/php) about the `pi()` function.

The entry should go in a new file in `docs/content/php/concepts/math-functions/terms/pi/pi.md`

The entry should:

- Have a syntax section illustrating the function with a ` ```pseudo ` code block. 
- An example showing the function in use with a ` ```php ` code block. 
- A runnable codebyte example in a ` ```codebyte/php` block. 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by estrellagl** [comment]
Hi, I'd like to contribute to this.

**Comment by SSwiniarski** [comment]
@estrellagl You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

If you're new to Docs, how did you find this repo?

**Comment by SSwiniarski** [comment]
@estrellagl  It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by SSwiniarski** [comment]
@estrellagl Because of inactivity I'm unassigning you so someone else can work on this.

**Comment by arisdelacruz** [comment]
@SSwiniarski Can i work on this? Thanks

**Comment by SSwiniarski** [comment]
@arisdelacruz You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by arisdelacruz** [comment]
@SSwiniarski good day.

just wonderin' if the M_PI function is included,
or, is this done on a separate entry

thanks

**Comment by SSwiniarski** [comment]
@arisdelacruz `M_PI` is a constant, not a function, but you can mention it in the entry, and that it gives identical results.

**Comment by arisdelacruz** [comment]
just created a pull request

crossing my fingers now, hehe

Thanks
