### ISSUE TITLE
[Concept Entry] Cybersecurity DDoS Attack

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2090]
### Reason/inspiration (optional)

We would like a new term entry for [Cybersecurity](https://www.codecademy.com/resources/docs/cybersecurity) about the concept of a DDoS Attack.

The file should be located at `docs/content/cybersecurity/concepts/cyber-attack/terms/ddos-attack/ddos-attack.md`

The entry should:

- Describe the concept of a DDoS attack. 
- Explain basic countermeasures to fight a DDoS attack. 
- Link mentions of other cybersecurity concepts to their entries where appropriate.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by jgarrels** [comment]
Hi there! I'd like to work on this issue as part of the portfolio project for the Introduction to Open Source course on codecademy (https://www.codecademy.com/learn/introduction-to-open-source).

**Comment by SSwiniarski** [comment]
@jgarrels You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by jgarrels** [comment]
Sorry for the delay - I'm still working on it, but had to prioritize university assignments the last week. At the moment I don't need assistance. I'm hoping to finish by next weekend (June 4th) - would that be okay?

**Comment by SSwiniarski** [comment]
@jgarrels that's fine, we just want to keep tabs on things so issues aren't abandoned.

**Comment by SSwiniarski** [comment]
@jgarrels because of inactivity I am unassigning this issue so someone else can work on it. Please feel free to claim another issue when you have time to work on it.

**Comment by Rosh1101** [comment]
@SSwiniarski Hey there, I'm a developer with 7 years on hand experience. I would love to take this opportunity. I would love to get assigned with this work.

**Comment by KTom101** [comment]
@Rosh1101 You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our revamped [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

Also, feel free to head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by SSwiniarski** [comment]
@Rosh1101 It's been two weeks. Are you still working on this entry? Note that in another week this will be unassigned due to inactivity.

Also assuming you are working on this, we'd like to change the path of the entry to the following: `docs/content/cybersecurity/concepts/cyber-attack/terms/ddos-attack/ddos-attack.md`

**Comment by SSwiniarski** [comment]
@Rosh1101 I am unassigning you due to inactivity.

**Comment by CBID2** [comment]
I’ll do this @SSwiniarski

**Comment by SSwiniarski** [comment]
@CBID2, you're assigned!
