### ISSUE TITLE
[Concept Entry] Cybersecurity Penetration Testing

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2091]
### Reason/inspiration (optional)

We would like a new term entry for [Cybersecurity](https://www.codecademy.com/resources/docs/cybersecurity) about Penetration Testing.

The file should be located at `docs/content/cybersecurity/concepts/penetration-testing/penetration-testing.md`

The entry should:

- Describe the concept and purpouse of penetration testing. 
- Explain who would conduct penetration testing. 
- Link mentions of other cybersecurity concepts to their entries where appropriate.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by git-megan** [comment]
Hi, I'd like to work on this issue

**Comment by yangc95** [comment]
@git-megan If this is your first contribution, what brought you to Docs?

> You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
> 
> See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
> 
> After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by git-megan** [comment]
Thanks @yangc95 ! I'm excited to work on this. Yes, this is my first contribution. I am familiar with git, GitHub, and markdown, but I haven't contributed to an Open Source project yet and would like to do more of this. @JoshuaKGoldberg recommended this project as a great place to start, and Docs seems like a good way to give back and share knowledge.

**Comment by yangc95** [comment]
Referred by an OG! It's a pleasure @git-megan glad to have you on this repo. Thanks for sharing and welcome to Docs 🤩
