### ISSUE TITLE
[Term Entry] Python:NumPy built-in functions .amax()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2093]
### Reason/inspiration (optional)

We would like a new term entry for [Python:NumPy](https://www.codecademy.com/resources/docs/numpy) about the `.amax()` function.

The entry should go in a new file in `docs/content/numpy/concepts/built-in-functions/terms/amax/amax.md`

The entry should:

- Mention the equivalent `ndarray.max()` method. 
- Have a syntax section illustrating the method with a ` ```pseudo ` code block. 
- An example showing the method in use with a ` ```py ` code block. 
- A runnable codebyte example in a ` ```codebyte/python` block. 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by 2003Aditya** [comment]
can i try on this one

**Comment by SSwiniarski** [comment]
@2003Aditya  It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by SSwiniarski** [comment]
@2003Aditya I am unassigning you due to inactivity so someone else can work on this.

**Comment by mark-nettleton** [comment]
Hello-
I'd like to take on this one please :)

**Comment by SSwiniarski** [comment]
@mark-nettleton You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@mark-nettleton it's been two weeks. Are you still working on this issue? Do you need assistance? In another week this will be unassigned due to inactivity.
