### ISSUE TITLE
[Term Entry] Python:NumPy built-in functions .amin()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2094]
### Reason/inspiration (optional)

We would like a new term entry for [Python:NumPy](https://www.codecademy.com/resources/docs/numpy) about the `.amin()` function.

The entry should go in a new file in `docs/content/numpy/concepts/built-in-functions/terms/min/amin.md`

The entry should:

- Mention the equivalent `ndarray.min()` method.
- Have a syntax section illustrating the function with a ` ```pseudo ` code block. 
- An example showing the function in use with a ` ```py ` code block. 
- A runnable codebyte example in a ` ```codebyte/python` block. 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by 2003Aditya** [comment]
can i try once on this I am new but i will try solve this.

**Comment by 2003Aditya** [comment]
Sorry to disturb you but i can't find this **docs/content/numpy/concepts/built-in-functions/terms/min/amin.md**

**Comment by yangc95** [comment]
@2003Aditya No worries! Look for `docs/content/numpy/concepts/built-in-functions/terms/`

Then, create a `amin` folder there. Create the `amin.md` file and you should be good to start writing the entry.

**Comment by SSwiniarski** [comment]
@2003Aditya  It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by teona-pavliukova** [comment]
@SSwiniarski Hi, I am interested in taking this issue on. I am new to Docs, I've heard about them from GitHub Codecademy course I am currently completing (this is a Portfolio project there).

**Comment by SSwiniarski** [comment]
@teona-pavliukova You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!
