### ISSUE TITLE
[Term Entry] JavaScript Window clearTimeout()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2096]
### Reason/inspiration (optional)

We would like a new term entry for JavaScript's Window Functions.

The entry should go in a new file in `docs/content/javascript/concepts/window/terms/clearTimeout/clearTimeout.md` (note the dashes rather than underscores)

The entry should:

- Have a syntax section illustrating the clearTimeout() function.
- An example showing how to use this function.

Please refer to the [term template](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Masonkate** [comment]
Can I be assigned to this issue?

**Comment by SSwiniarski** [comment]
@Masonkate  It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by SSwiniarski** [comment]
@Masonkate because of inactivity I am unassigning you from this issue so someone else can work on it.

**Comment by Nessvah** [comment]
Hi! I'm available to work on this issue. Let me know if I can be assigned to this.

**Comment by SSwiniarski** [comment]
@Nessvah You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by Nessvah** [comment]
@SSwiniarski sorry for the delay! Got caught up on some work. I'm going to work on it today! Will have it ready by tomorrow.
