### ISSUE TITLE
[Term Entry] JavaScript Window confirm()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2097]
### Reason/inspiration (optional)

We would like a new term entry for JavaScript's Window Functions.

The entry should go in a new file in `docs/content/javascript/concepts/window/terms/confirm/confirm.md` (note the dashes rather than underscores)

The entry should:

- Have a syntax section illustrating the confirm() function.
- An example showing how to use this function.

Please refer to the [term template](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Masonkate** [comment]
@codecademy-docs I'm interested in this issue, can I work on this? Thanks!

**Comment by SSwiniarski** [comment]
@Masonkate You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

If you're new to Docs, how did you find this repo?

**Comment by SSwiniarski** [comment]
@Masonkate  It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by SSwiniarski** [comment]
@Masonkate because of inactivity I am unassigning you from this issue so someone else can work on it.

**Comment by DaltonAC** [comment]
I would like to contribute to this docs section. I have created a markdown that meets the criteria for confirm().

**Comment by KTom101** [comment]
@DaltonAC I see you've already opened a PR for this [here](https://github.com/Codecademy/docs/pull/2311). In the future, please refrain from opening PRs for an issue before being assigned. This is to prevent having two people working on the same issue.
