### ISSUE TITLE
[Concept Entry] SwiftUI Drag and Drop

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2100]
### Reason/inspiration (optional)

We would like a new concept entry for dragging and dropping in SwiftUI.

The edit should go in an existing file in docs/content/swiftui/concepts/drag-and-drop/drag-and-drop.md 

The entry should:

- Explain what drag and drop is in SwiftUI, starting with an introductory pararaph (2-3 sentences).
- Include headers with sections on the `DropDelegate` protocol, behavior (DropProposal), and state (DropInfo) for drag and dropping.
- See for reference material: [Apple Documentation on Drag and Drop](https://developer.apple.com/documentation/swiftui/drag-and-drop)

Please refer to the [entry template](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by oswaldjunius** [comment]
i am interested in taking on this issue, please can you assign it to me thank you

**Comment by Masonkate** [comment]
@codecademy-docs  I am interested in taking on this issue, please can you assign it to me thank you

**Comment by SSwiniarski** [comment]
@oswaldjunius You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

If you're new to Docs, how did you find this repo?

**Comment by SSwiniarski** [comment]
@oswaldjunius  It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by SSwiniarski** [comment]
@oswaldjunius because of inactivity I am unassigning you so someone else can work on this issue.

**Comment by bruce0221** [comment]
Dear Codecademy, 
 I'm studying IOS developer career path course, and need to work on a project "create and submit an entry to [Codecademy Docs]". 
Can you assign this issue to me ?

**Comment by SSwiniarski** [comment]
@bruce0221 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@bruce0221 It's been two weeks. Are you still working on this entry? Do you need assistance? Note that in another week this issue will be unassigned due to inactivity.

**Comment by bruce0221** [comment]
> @bruce0221 It's been two weeks. Are you still working on this entry? Do you need assistance? Note that in another week this issue will be unassigned due to inactivity.

@SSwiniarski  Sorry about that I'm working on it.

**Comment by arirays** [comment]
hi, I would like this entry 💛

**Comment by SSwiniarski** [comment]
@arirays You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment]
@arirays It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by arirays** [comment]
@SSwiniarski Yes I'm still working on my entry and will PR soon. Thank you for the reminder ☺️
