### ISSUE TITLE
[Concept Entry] SwiftUI Layouts

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2102]
### Reason/inspiration (optional)

We would like a new concept entry for SwiftUI Layouts.

The edit should go in an existing file in docs/content/swiftui/concepts/layouts/layouts.md 

The entry should:

- Explain what view layouts are in SwiftUI, starting with an introductory pararaph.
- Overview on custom layouts.
- Feel free to briefly mention available views in [view terms](https://www.codecademy.com/resources/docs/swiftui/views).

Please refer to the [entry template](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by anceldev** [comment]
Hi @codecademy-docs  I would like to work on this. I'm reading some documentation about it.

**Comment by SSwiniarski** [comment]
@anceldev You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@anceldev It's been two weeks. Are you still working on this issue? Do you need assistance? In another week this will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@anceldev This is being unassigned due to inactivity so someone else can work on it.

**Comment by gracekishino** [comment]
@codecademy-docs please can I work on this issue?

**Comment by SSwiniarski** [comment]
@gracekishino You're assigned!
