### ISSUE TITLE
[Concept Entry] SwiftUI Search

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2104]
### Reason/inspiration (optional)

We would like a new concept entry for SwiftUI Search.

The edit should go in an existing file in docs/content/swiftui/concepts/search/search.md 

The entry should:

- Explain how to create a Search Interface in SwiftUI, starting with an introductory pararaph.
- Include headers with sections on how to create a search interface by applying searchable view modifier.
- Not a requirement to go into too much detal about tokens or queries; a general overview is sufficient! See: [Apple Docs on Search](https://developer.apple.com/documentation/swiftui/adding-a-search-interface-to-your-app)

Please refer to the [entry template](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by oswaldjunius** [comment]
Hi i would really like to take on this challenge, please assign it, thank you

**Comment by Masonkate** [comment]
I am interested in taking on this issue, please can you assign it to me thank you

**Comment by SSwiniarski** [comment]
@oswaldjunius You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

If you're new to Docs, how did you find this repo?

**Comment by SSwiniarski** [comment]
@Masonkate you've been assigned three issues. Please work on those before claiming any new ones.

**Comment by SSwiniarski** [comment]
@oswaldjunius  It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by SSwiniarski** [comment]
@oswaldjunius because of inactivity I am unassigning you from this issue so someone else can work on it.

**Comment by gracekishino** [comment]
Please can I work on this issue?

**Comment by KTom101** [comment]
@gracekishino You're assigned, thanks! ❤️

**Comment by gracekishino** [comment]
@SSwiniarski yes still working on this and hoping to submit a pull request today. Sorry for the delay! 🙏🏼
