### ISSUE TITLE
[Concept Entry] SwiftUI Tables

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2105]
### Reason/inspiration (optional)

We would like a new concept entry for SwiftUI Tables.

The edit should go in an existing file in docs/content/swiftui/concepts/tables/tables.md 

The entry should:

- Explain what tables are in SwiftUI, starting with an introductory pararaph.
- Include headers with sections on how to create a table.
- Go over table structure, rows, and columns (Keep it technical and precise).

Please refer to the [entry template](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by tomislavzvonarek** [comment]
good first issue

**Comment by abedalAhmad** [comment]
hello, I am interested in working on this issue if that is possible, I learned about docs through the Codecademy iOS career path

**Comment by yangc95** [comment]
@tomislavzvonarek are you still working on this issue?

@abedalAhmad, thanks for your interest! We are currently reevaluating the previous contributor's entry to determine if it is still valid or not. I will reach out by tagging your handle if this issue needs reassigning.

**Comment by yangc95** [comment]
@abedalAhmad I've reassigned this issue to you!

You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

**Comment by abedalAhmad** [comment]
Thank you @yangc95 , I think I will have questions since its my first time, but ill try my best to do it myself : )

**Comment by abedalAhmad** [comment]
Hello @yangc95 I didn't find tables in the folders, also I'm a bit confused I don't know what to do, do I need to write real code or just edit a text file? I might skip this and go learn more and come later so feel free to assign it to someone else for now 
Thanks very much

**Comment by SSwiniarski** [comment]
@arirays You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment]
@arirays It's been two weeks, are you still working on this issue? Note that in a week you'll be unassigned due to inactivity.

**Comment by arirays** [comment]
@SSwiniarski yes I'm working on this issue. I'll make PR this weekend. Thanks!
