### ISSUE TITLE
[Concept Entry] SwiftUI Widgets

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2106]
### Reason/inspiration (optional)

We would like a new concept entry for Widgets in SwiftUI.

The edit should go in an existing file in docs/content/swiftui/concepts/widgets/widgets.md 

The entry should:

- Explain what widgets are in SwiftUI, starting with an introductory pararaph (2-3 sentences).
- Include headers with sections on how to create a widget using the Widget Extension template.
- Not a requirement to go into too much detail about WidgetKit; a general overview is sufficient! See: [Apple Documentation on Wedgets](https://developer.apple.com/documentation/widgetkit/building_widgets_using_widgetkit_and_swiftui)

Please refer to the [entry template](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by JaseTheJap** [comment]
Hi! 👋  I would like to take on this issue.

**Comment by yangc95** [comment]
@JaseTheJap If this is your first contribution, what brought you to Docs?

> You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
> 
> See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
> 
> After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
