### ISSUE TITLE
[Concept Entry] SwiftUI UIKit

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2107]
### Reason/inspiration (optional)

We would like a new concept entry for UIKit.

The edit should go in an existing file in docs/content/swiftui/concepts/uikit/uikit.md 

The entry should:

- Explain what UIKit is, starting with an introductory pararaph (2-3 sentences).
- Include how is relates to SwiftUI.
- Not a requirement to go into too much detail about WidgetKit; a general overview is sufficient! See: [Apple Documentation on Wedgets](https://developer.apple.com/documentation/widgetkit/building_widgets_using_widgetkit_and_swiftui)

Please refer to the [entry template](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by pjo42685** [comment]
Hello. I'm here for part of my iOS developer path courses. I would like to claim this topic if possible.

Thank you.

**Comment by yangc95** [comment]
@pjo42685 That's awesome! Would you be able to link me to the page in the iOS developer path course that brought you here?

**Comment by SSwiniarski** [comment]
@pjo42685  It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by SSwiniarski** [comment]
@pjo42685 Ok, I will unassign you so someone else can work on this.

**Comment by yangc95** [comment]
@gab394 You're assigned! You can check out the [Contribution Guide](<https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md>) for additional information on contributing.


See [Content Standards](<https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md>) for an overview of styling tips that the [Style Guide](<https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md>) covers in detail.


After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving


What brought you to Docs?

**Comment by gab394** [comment]
I'm here for the ios developer portfolio project.
