### ISSUE TITLE
[Concept Entry] AI Large Language Models

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2108]
### Reason/inspiration (optional)

We would like a new topic entry for Large Language Models (LLMs).

The entry should go in a new file in docs/content/ai/concepts/ai-models/models/ai-large-language-models/ai-large-language-modelsmd

The entry should
- Describe what a Large Language Model is.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Hassan-fayez** [comment]
hi can i work on this issue please

**Comment by SSwiniarski** [comment]
@Hassan-fayez You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

If you're new to Docs, how did you find this repo?

**Comment by HishamT** [comment]
@Hassan-fayez, thank you for your interest in taking on this entry. Please note the change made to the location required for the entry.
