### ISSUE TITLE
[Concept Entry] AI Diffusion Models

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2109]
### Reason/inspiration (optional)

We would like a new topic entry for a Diffusion Model.

The entry should go in a new file in docs/content/ai/concepts/ai-models/models/ai-diffusion-models/ai-diffusion-models.md

The entry should
- Describe what a Diffusion Model is.
- Explain how it is used for image generation.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by DevGat718** [comment]
@yoiang I'll take this one

**Comment by yangc95** [comment]
I think you may have tagged someone else by mistake @DevGat718

If this is your first contribution, what brought you to Docs?

> You're assigned! You can check out the [[Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md)](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
> 
> See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
> 
> After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by DevGat718** [comment]
I’m working on a git/GitHub projectSent from my iPhoneOn May 10, 2023, at 11:23, Christine Yang ***@***.***> wrote:﻿
I think you may have tagged someone else by mistake @DevGat718
If this is your first contribution, what brought you to Docs?

You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See Content Standards for an overview of styling tips that the Style Guide covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by HishamT** [comment]
@DevGat718, thank you for your interest in taking on this entry. Please note the change made to the location required for the entry.

**Comment by DevGat718** [comment]
hey @HishamT i'm trying to make the doc entry but docs/content/ai/concepts/ai-models/models/ai-diffusion-models path doesn't exist how do I make it ? by adding pull requests for each folder or do you guys update it. Its my 1st time doing this I'm a bit lost. 

any guidance is greatly appreciated.

**Comment by HishamT** [comment]
Hey @DevGat718, you are supposed to create the directories and the file inside them. Make sure to create this path:

docs/content/ai/concepts/ai-models/models/ai-diffusion-models/ai-diffusion-models.md

**Comment by DevGat718** [comment]
@HishamT copy

**Comment by SSwiniarski** [comment]
@DevGat718 I't been two weeks since you were assigned. Are you still working on this issue? Do you need assistance?

**Comment by DevGat718** [comment]
@SSwiniarski no im good, ill get to in still working.

**Comment by SSwiniarski** [comment]
@DevGat718 It's been another two weeks, are you still intending to work on this?

**Comment by SSwiniarski** [comment]
@DevGat718 I am unassigning this due to inactivity so someone else can work on it.

**Comment by DevGat718** [comment]
sorry I was busy with work training started a new job etc.

can I have it back please? @SSwiniarski

**Comment by SSwiniarski** [comment]
@DevGat718 If you think you can get to it in the next week, I'll reassign you.

**Comment by DevGat718** [comment]
copy that
