### ISSUE TITLE
Python entry needed: Decorators

### ISSUE THREAD

**Issue by kaifee-haque** [Codecademy/docs#211]
Python entry needed for the following concept:
- Decorators

**Comment by Goku-kun** [comment]
Hi @kaifee-haque 
I'd like to take up this entry. Could you assign it to me?

**Comment by kaifee-haque** [comment]
Hi @Goku-kun, no assignment necessary. Feel free to submit a PR!

**Comment by sonnynomnom** [comment]
All you @Goku-kun, and thanks for making an issue @kaifee-haque!
