### ISSUE TITLE
Python entry: PIP

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#213]
Python enty needed:

- PIP

**Comment by mdwiltfong** [comment]
Hello @sonnynomnom ,

Hope you're doing well! I'm interested in tackling the PIP entry, but I'm not sure where to place it. Do you think it would be it's own "concept," or is there a particular concept that PIP would be added to? 

Thanks

**Comment by mdwiltfong** [comment]
Actually, I see that npm is it's own category in JavaScript. Therefore I think PIP would be in it's own category as well.

**Comment by mdwiltfong** [comment]
I have generated a [PR ](https://github.com/Codecademy/docs/pull/271)that will add a new entry addressing `pip`

**Comment by sonnynomnom** [comment]
Updated the issue for just PIP.
