### ISSUE TITLE
[Term Entry] AI Covolution

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2133]
### Reason/inspiration (optional)

We would like a new term entry for the concept of Convolution.

The entry should go in a new file in docs/content/ai/concepts/neural-networks/terms/convolution/convolution.md

The entry should
- Describe what Convolution is.
- Explain how it is used in a Convolutional Neural Network.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by harshitcompcode** [comment]
Assign me this issue

**Comment by KTom101** [comment]
@harshitcompcode This is your third assignment 😄

**Comment by SSwiniarski** [comment]
@harshitcompcode It's been two weeks. Are you still working on this issue? Note that in another week this will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@harshitcompcode I am unassigning you due to inactivity.

**Comment by YanisaHS** [comment]
@SSwiniarski hi! Could I be assigned to this one? 🥳 thanks!

**Comment by SSwiniarski** [comment]
@YanisaHS you're assigned. Yes, why don't we expand on the existing entry.
