### ISSUE TITLE
[Term Entry] Python Built-in Functions divmod()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2138]
### Reason/inspiration (optional)

We would like a new term entry on the `divmod()` Python: [Built-in Function](https://www.codecademy.com/resources/docs/python/built-in-functions). The entry should go in a new file under docs/content/python/concepts/built-in-functions/terms/divmod/divmod.md

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ```pseudo code snippet.
- An "Example" section with a ```py code snippet.
- A “Codebyte Example” section with a ```codebyte/python snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
@reeveng we want people to claim an issue here before writing a PR, because otherwise we can have two people working on the same issue. That fortunately wasn't an issue in this case. If you'd respond here, I can add you to the assignees so we can better keep track of things.

**Comment by reeveng** [comment]
> @reeveng we want people to claim an issue here before writing a PR, because otherwise we can have two people working on the same issue. That fortunately wasn't an issue in this case. If you'd respond here, I can add you to the assignees so we can better keep track of things.

My bad, I'd like to take this ticket up is possible :+1:
