### ISSUE TITLE
[Term Entry] Python Built-in Functions exec()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2140]
### Reason/inspiration (optional)

We would like a new term entry on the `exec()` Python: [Built-in Function](https://www.codecademy.com/resources/docs/python/built-in-functions). The entry should go in a new file under docs/content/python/concepts/built-in-functions/terms/exec/exec.md

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ```pseudo code snippet.
- An "Example" section with a ```py code snippet.
- A “Codebyte Example” section with a ```codebyte/python snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by mluzaic** [comment]
@codecademy-docs I am interested to contribute on the in the exec() built-in function. I found out about it through codeacademy.

**Comment by SSwiniarski** [comment]
@mluzaic You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@mluzaic It's been two weeks. Are you still working on this entry? Do you need assistance?

**Comment by mluzaic** [comment]
@SSwiniarski Hi, it will be ready next week. No assistance required so far.

**Comment by SSwiniarski** [comment]
@mluzaic Please note that in another week this will be unassigned due to inactivity.

**Comment by mluzaic** [comment]
@SSwiniarski Hi, I created a PR to close #2472.

**Comment by SSwiniarski** [comment]
@ginkof, this issue was assigned to @mluzaic, and there is already a PR being reviewed on this issue. Please look for an unclaimed issue to ask for.
