### ISSUE TITLE
[Term Entry] Python Built-in Functions format()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2141]
### Reason/inspiration (optional)

We would like a new term entry on the `format()` Python: [Built-in Function](https://www.codecademy.com/resources/docs/python/built-in-functions). The entry should go in a new file under docs/content/python/concepts/built-in-functions/terms/format/format.md

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ```pseudo code snippet.
- An "Example" section with a ```py code snippet.
- A “Codebyte Example” section with a ```codebyte/python snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by bcsamrudh** [comment]
Could I work on this Issue!

**Comment by KTom101** [comment]
@bcsamrudh Assigned!

**Comment by SSwiniarski** [comment]
@bcsamrudh I am unassigning you due to inactivity on your PR.

**Comment by SSwiniarski** [comment]
I am closing this issue and re-posing it since GitHub won't let me unlink the closed PR.
