### ISSUE TITLE
[Term Entry] Python Built-in Functions hash()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2144]
### Reason/inspiration (optional)

We would like a new term entry on the `hash()` Python: [Built-in Function](https://www.codecademy.com/resources/docs/python/built-in-functions). The entry should go in a new file under docs/content/python/concepts/built-in-functions/terms/hash/hash.md

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ```pseudo code snippet.
- An "Example" section with a ```py code snippet.
- A “Codebyte Example” section with a ```codebyte/python snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by pasb94** [comment]
@codecademy-docs I am interested on working on this issue. I found out about Docs through Codecademy Learn Git & GitHub course.

**Comment by yangc95** [comment]
@pasb94 Thanks for your interest in this!

> You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
> See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
> After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good issues that will help expand Docs!

**Comment by pasb94** [comment]
Hi Christine

Thanks for assigning me this issue, I am starting my studies in programming
and will need some help. I can't find the hash function in the codecademy
"built-in functions" page, but in other sources. May I use another source?
Or am I searching in the wrong place?

Thanks for your time and help and kind regards

Patrick S.

**Comment by yangc95** [comment]
Yeah, no problem @pasb94 ! The reason you can't find it is because you will be creating the entry for this function. You may use other sources for research purposes to create the entry that will be displayed on Docs.

Hope this helps

**Comment by SSwiniarski** [comment]
@pasb94 It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by SSwiniarski** [comment]
You can look at the python documentation: http://docs.python.org/2/library/functions.html#hash
You might also check out this Sack Overflow thread: https://stackoverflow.com/questions/17585730/what-does-hash-do-in-python
Also look at the other Python built-in function entries to see how an entry is structured.

Remember that you entry needs to be original work, not just a copy from another website.

**Comment by pasb94** [comment]
Thank you very much!
