### ISSUE TITLE
[Term Entry] Python Built-in Functions hex()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2145]
### Reason/inspiration (optional)

We would like a new term entry on the `hex()` Python: [Built-in Function](https://www.codecademy.com/resources/docs/python/built-in-functions). The entry should go in a new file under docs/content/python/concepts/built-in-functions/terms/hex/hex.md

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ```pseudo code snippet.
- An "Example" section with a ```py code snippet.
- A “Codebyte Example” section with a ```codebyte/python snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Maternowsky** [comment]
I would like to be assigned this issue.

**Comment by KTom101** [comment]
@Maternowsky You're assigned! Please use the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) as well as the documentation linked in the description as resources while creating this entry. 

Is this your first contribution to Codecademy Docs? Where did you find out about the Docs repository?

**Comment by Maternowsky** [comment]
Yes this is my first contribution. I found the repository searching in the explore tab.
