### ISSUE TITLE
[Term Entry] Python Built-in Functions id()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2146]
### Reason/inspiration (optional)

We would like a new term entry on the `id()` Python: [Built-in Function](https://www.codecademy.com/resources/docs/python/built-in-functions). The entry should go in a new file under docs/content/python/concepts/built-in-functions/terms/id/id.md

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ```pseudo code snippet.
- An "Example" section with a ```py code snippet.
- A “Codebyte Example” section with a ```codebyte/python snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Luffy0001** [comment]
@codecademy-docs I am interested in this, I found out about it through codeacademy.

**Comment by yangc95** [comment]
@Luffy0001 I can assign you to this Issue. Moving forward, make sure to comment on an Issue first and be assigned prior to submitting a PR. Thanks for your cooperation

> You're assigned! You can check out the [Contribution Guide](<https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md>) for additional information on contributing.
> 
> 
> See [Content Standards](<https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md>) for an overview of styling tips that the [Style Guide](<https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md>) covers in detail.
> 
> 
> After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving
> 
> 
> [If this is a first time contributor] What brought you to Docs?

**Comment by SSwiniarski** [comment]
@Luffy0001 Are you still working on this issue? Do you need assistance?

**Comment by SSwiniarski** [comment]
@Luffy0001 Because of inactivity I am unassigning you so someone else can work on this issue.

**Comment by Churreesha** [comment]
@SSwiniarski I would like a chance to contribute to this doc please. I found out about this through the Learn Git and GitHub course on Codecademy. This is the only task I have left in this course, after this task I will be able to complete the course and get my certificate! 😊

**Comment by SSwiniarski** [comment]
@Churreesha You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by Churreesha** [comment]
@SSwiniarski Thank you so much for this opportunity! I greatly appreciate it! ❤️
