### ISSUE TITLE
[Term Entry] Python Built-in Functions oct()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2149]
### Reason/inspiration (optional)

We would like a new term entry on the `oct()` Python: [Built-in Function](https://www.codecademy.com/resources/docs/python/built-in-functions). The entry should go in a new file under docs/content/python/concepts/built-in-functions/terms/oct/oct.md

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ```pseudo code snippet.
- An "Example" section with a ```py code snippet.
- A “Codebyte Example” section with a ```codebyte/python snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by EngOmarAhmedIOS** [comment]
I will fix this issue. please a assign this issue to me.

**Comment by SSwiniarski** [comment]
@EngOmarAhmedIOS You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

If this is your first time contributing, what brought you to this repo?

**Comment by EngOmarAhmedIOS** [comment]
I fixed the issue, please check my pull request

**Comment by SSwiniarski** [comment]
@EngOmarAhmedIOS I see the PR. Just a note for the future: we like people to wait until they're assigned by a maintainer to an issue before submitting a PR. Otherwise we can run into situations where two people end up working on the same issue, This wasn't an issue in this case, but we'd like to avoid this going forward.

**Comment by EngOmarAhmedIOS** [comment]
ok 👌, my bad sorry @SSwiniarski
