### ISSUE TITLE
[Term Entry] Python Built-in Functions property()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2151]
### Reason/inspiration (optional)

We would like a new term entry on the `property()` Python: [Built-in Function](https://www.codecademy.com/resources/docs/python/built-in-functions). The entry should go in a new file under docs/content/python/concepts/built-in-functions/terms/property/property.md

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ```pseudo code snippet.
- An "Example" section with a ```py code snippet.
- A “Codebyte Example” section with a ```codebyte/python snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by rafiya2003** [comment]
can I work on this?

**Comment by SSwiniarski** [comment]
@rafiya2003 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@rafiya2003 It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by SSwiniarski** [comment]
@rafiya2003 Because of inactivity I am unassigning you so someone else can work on this issue.

**Comment by hkorble** [comment]
@SSwiniarski 
Hello. I am interested in working on this. Thanks!

**Comment by SSwiniarski** [comment]
@hkorble You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by hkorble** [comment]
I am struggling to find this entry from the file tree. I don't see it in Python Built-In Functions.

**Comment by SSwiniarski** [comment]
@hkorble That is because this issue wants you to create a new entry.

**Comment by SSwiniarski** [comment]
@hkorble you've been unassigned due to inactivity on your PR.

**Comment by dhrey112** [comment]
Kindly assign this to me. Thanks

**Comment by SSwiniarski** [comment]
@shouryagautam You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by dhrey112** [comment]
> @dhrey112 Issues are generally assigned on a first come first served basis. @shouryagautam asked for assignment first. However, there are plenty of unclaimed issues left to choose from.

Alright, I will look for another issue. Thanks

**Comment by echeng166** [comment]
Can I work on this? Thanks!

**Comment by SSwiniarski** [comment]
@echeng166 this issue has already been assigned and has a PR under review. When looking for an issue to work on, look for unassigned issues that do not have a "claimed" tag on them.
