### ISSUE TITLE
General entry: What is an NFT?

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#218]
Requesting 1 new entry in the [General](https://www.codecademy.com/resources/docs/general) topic: 

- Name: "What is an NFT?"
- Length: 500-100 words
- Folder: https://github.com/Codecademy/docs/tree/main/content/general/concepts

**Comment by EugeneGohh** [comment]
I'm back! Can I take over this since @rexdivakar does not have any PR bout it?

**Comment by Dusch4593** [comment]
@EugeneGohh sure! I'll reassign to you. 

@rexdivakar You're still assigned to #185; did you still want to create a PR for that one?
