### ISSUE TITLE
[Term Entry] PHP Math Functions atan()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2205]
### Reason/inspiration (optional)

We would like a new term entry for [PHP](https://www.codecademy.com/resources/docs/php) about the `atan()` function.

The entry should go in a new file in `docs/content/php/concepts/math-functions/terms/atan/atan.md`

The entry should 

- Have a syntax section illustrating the function with a ` ```pseudo ` code block. 
- An example showing the function in use with a ` ```php ` code block. 
- A runnable codebyte example in a ` ```codebyte/php` block. 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by ZapeeoSheikh** [comment]
Please assign me this under the label of SSOC'23 and GSSOC'23.

**Comment by SSwiniarski** [comment]
@ZapeeoSheikh you've already been assigned three issues. We do not assign people to more than three open issues at a time. Complete some PRs for the issue you have been assigned, then you can claim another open issue.

**Comment by yangc95** [comment]
@ZapeeoSheikh We'll see if those tags can be added! Just to confirm, would you be able to provide the information for this initiative? Thanks!

**Comment by hitesh-gitdev** [comment]
Hello! Would love to take up this task. Could you please assign the task to me? Thank you!

**Comment by SSwiniarski** [comment]
@hitesh-gitdev You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!
