### ISSUE TITLE
[Concept Entry] Cybersecurity Disaster Recovery

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2209]
### Reason/inspiration (optional)

We would like a new term entry for [Cybersecurity](https://www.codecademy.com/resources/docs/cybersecurity) about the concept of Disaster Recovery.

The file should be located at `docs/content/cybersecurity/concepts/disaster-recovery/disaster-recovery.md`

The entry should:

- Describe the concept of disaster recovery. 
- Explain basic elements of disaster recovery, and why it is vital. 
- Link mentions of other cybersecurity concepts to their entries where appropriate.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by EdwardDL97** [comment]
Hello! Could I please get assigned this issue?

**Comment by SSwiniarski** [comment]
@EdwardDL97 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by EdwardDL97** [comment]
Would like someone to take this assignment. Working on another assignment

**Comment by KTom101** [comment]
@EdwardDL97 Alright, thanks for letting us know! 😄

**Comment by harshitcompcode** [comment]
Assign me this issue

**Comment by KTom101** [comment]
@harshitcompcode You're assigned! 🎉

**Comment by SSwiniarski** [comment]
@harshitcompcode I am unassigning you from this issue due to inactivity.

**Comment by cslylla** [comment]
I would like to write this document! Could I please get assigned?

**Comment by SSwiniarski** [comment]
@cslylla, you're assigned!

**Comment by SSwiniarski** [comment]
@cslylla It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by harshitcompcode** [comment]
@SSwiniarski assign me this issue back, I will complete these within a week .I was caught up with my end semester exams. I am really sorry

**Comment by SSwiniarski** [comment]
@harshitcompcode, at the moment it is assigned to @cslylla, who should have a chance to complete it.

**Comment by cslylla** [comment]
@SSwiniarski I am still working on this entry. I can finish it in a few days if that is okay.
