### ISSUE TITLE
[Concept Entry] General Conditionals

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2210]
### Reason/inspiration (optional)

We would like a new concept entry for Conditionals in General.

The entry should go in a file in docs/content/general/concepts/conditionals/conditionals.md

The entry should: 

- Explain what conditionals are without necessarily using a specific programming language, starting with an introductory paragraph (2-3 sentences). 
- Include headers with sections on if else and switch case conditionals. 
- Create a section that links out to conditionals in different languages.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by VishakhaSi** [comment]
Went through the path, the folder named "conditional" is not present. Adding an open file there.

**Comment by SSwiniarski** [comment]
@VishakhaSi we prefer you to wait until your officially assigned before working on an issue. This prevents multiple people from working on the same issue. Fortunately, you're the first person to express interest, so I can assign you.

You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by VishakhaSi** [comment]
Have added the metadata and made the changes.
