### ISSUE TITLE
[Concept Entry] General Control Flow

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2211]
### Reason/inspiration (optional)

We would like a new concept entry for Control Flow in General.

The entry should go in a file in docs/content/general/concepts/control-flow/control-flow.md

The entry should: 

- Explain what control flow is without necessarily using a specific programming language, starting with an introductory paragraph (2-3 sentences). 
- Include headers with sections on different ways to control flow in a program. 
- Links out to appropriate entries that are mentioned in this entry.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by DianaWMD** [comment]
Hi I'm interested to take on this issue. it'll help me finish codecademy entry project

**Comment by SSwiniarski** [comment]
@DianaWMD You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!
