### ISSUE TITLE
[Concept Entry] Swift Errors

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2212]
### Reason/inspiration (optional)

We would like a new concept entry for Errors in Swift. This will segueway to list all the error terms in Swift.

The entry should go in a file in docs/content/swift/concepts/errors/errors.md

The entry should: 

- Explain what errors are in Swift, starting with an introductory paragraph (2-3 sentences). 
- Go over how Swift throws errors and some common reasons for them. For example, go over the Error protocol and (briefly) how to handle errors.
- Links out to entries as needed.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by OlidenGrande** [comment]
@yoiang Hello, I'm interested in taking this issue on

**Comment by JoaoCMoreira** [comment]
@codecademy-docs can this issue be assigned to me? thanks

**Comment by yangc95** [comment]
@JoaoCMoreira You're assigned! You can check out the [Contribution Guide](<https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md>) for additional information on contributing.


See [Content Standards](<https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md>) for an overview of styling tips that the [Style Guide](<https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md>) covers in detail.


After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving


What brought you to Docs?

**Comment by JoaoCMoreira** [comment]
> What brought you to Docs?

Codecademy's IOS Developer Path

**Comment by yangc95** [comment]
@JoaoCMoreira Cool! Could you provide me with that link from that path which brought you here? Thanks in advance :smiling

**Comment by JoaoCMoreira** [comment]
@yangc95 https://www.codecademy.com/learn/paths/ios-developer

**Comment by yangc95** [comment]
@JoaoCMoreira Thanks for that! Just need to confirm one more thing. Was this the specific page (within the path) that brought you here: https://www.codecademy.com/paths/ios-developer/tracks/learn-git-github-for-ios-development/modules/collaborating-with-the-github-community/kanban_projects/contributing-to-the-codecademy-docs-repository

**Comment by JoaoCMoreira** [comment]
> @JoaoCMoreira Thanks for that! Just need to confirm one more thing. Was this the specific page (within the path) that brought you here: https://www.codecademy.com/paths/ios-developer/tracks/learn-git-github-for-ios-development/modules/collaborating-with-the-github-community/kanban_projects/contributing-to-the-codecademy-docs-repository

yes

**Comment by andrewperk** [comment]
@JoaoCMoreira Hello, what made you tag me in this post? I don't mind, I'm just wondering why me, haha. Thank you.

**Comment by JoaoCMoreira** [comment]
@andrewperk my mistake:)

**Comment by SSwiniarski** [comment]
@JoaoCMoreira It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by JoaoCMoreira** [comment]
> @JoaoCMoreira It's been two weeks. Are you still working on this issue? Do you need assistance?

@SSwiniarski Still working on this. Been busier than usual at work lately.

**Comment by SSwiniarski** [comment]
@JoaoCMoreira Please note that in another week this will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@JoaoCMoreira I am unassigning you due to inactivity so someone else can work on this.

**Comment by raschuh** [comment]
@codecademy-docs @yangc95 Hi! I'd like to take this on. I just discovered about the Docs and contributions today after reading an email from Codecademy encouraging me to contribute to the Docs.

**Comment by SSwiniarski** [comment]
@raschuh You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!
