### ISSUE TITLE
[Concept Entry] Swift Functions

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2213]
### Reason/inspiration (optional)

We would like a new concept entry for Functions in Swift.

The entry should go in a file in docs/content/swift/concepts/functions/functions.md

The entry should: 

- Explain what functions are in Swift, starting with an introductory paragraph (2-3 sentences). 
- Go over how to create a function with the keyword `func`.  
- Include function defining, calling, return, and parameters.
- Links out to entries as needed.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by EngOmarAhmedIOS** [comment]
I want to work on this issue because I am studying iOS (with codeadmey) so this will help me master the concept because I will explain it. 

Thank you in advance.

**Comment by SSwiniarski** [comment]
@EngOmarAhmedIOS You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by SSwiniarski** [comment]
@EngOmarAhmedIOS It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by EngOmarAhmedIOS** [comment]
> @EngOmarAhmedIOS It's been two weeks. Are you still working on this issue? Do you need assistance?

I was waiting for the other issue to be completed to start a new one, but if it not necessary to wait I will start and finish this issue in the next couple of days.
