### ISSUE TITLE
[Concept Entry] Swift Subscripts

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2214]
### Reason/inspiration (optional)

We would like a new concept entry for Subscripts in Swift.

The entry should go in an file in docs/content/swift/concepts/subscripts/subscripts.md

The entry should: 

- Explain what subscripts are used for in Swift, starting with an introductory paragraph (2-3 sentences).
- Go over how to create a subscript with the keyword `subscript`.
- Links out to entries (like classes, structures, and enums) as needed.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by jtapia201** [comment]
@codecademy-docs I'd like to help with this issue

**Comment by yangc95** [comment]
@jtapia201 You're assigned! You can check out the [Contribution Guide](<https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md>) for additional information on contributing.


See [Content Standards](<https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md>) for an overview of styling tips that the [Style Guide](<https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md>) covers in detail.


After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving


What brought you to Docs?

**Comment by SSwiniarski** [comment]
@jtapia201 Just checking that you saw this assignment and you are working on this issue.

**Comment by KTom101** [comment]
@jtapia201 I see you removed your assignment, does this mean you no longer want to work on this?

**Comment by gracekishino** [comment]
Please can I work on this issue?

**Comment by SSwiniarski** [comment]
@gracekishino since @jtapia201 seems to have bowed out, you're assigned!

**Comment by jtapia201** [comment]
@SSwiniarski @KTom101 Yes sorry I removed myself I didn't have enough time to work on this project and will opt for an easier one when I'm ready to try another issue

**Comment by KTom101** [comment]
@jtapia201 That is alright, thanks for letting us know!

**Comment by gracekishino** [comment]
@jtapia201 I'd be happy to help if you want any support for an issue when you have more time!
