### ISSUE TITLE
[Concept Entry] SQL Math Functions

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2215]
### Reason/inspiration (optional)

We would like a new concept entry for Math Functions in SQL.

The entry should go in a file in docs/content/sql/concepts/math-functions/math-functions.md

The entry should: 

- Explain what math functions are in SQL and what they’re used for, starting with an introductory paragraph (2-3 sentences).
- Links out to entries as needed.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by nikolaspoczekaj** [comment]
Hey, I'd like to contribute to this. If you dont mind I can do all the SQL Term Entries as well.

**Comment by SSwiniarski** [comment]
@nikolaspoczekaj You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.

See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

Note we only want people to claim three unassigned issues at a time. Once PRs are made you can claim others.

**Comment by nikolaspoczekaj** [comment]
Alright, thanks @SSwiniarski !
