### ISSUE TITLE
[Term Entry] SQL Math Functions CEILING

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2217]
### Reason/inspiration (optional)

We would like a new term entry for the Math Function, `CEILING`, in SQL.

The entry should go in a file in docs/content/sql/concepts/math-functions/terms/ceiling/ceiling.md

The entry should: 

- Explain what the math function `CEILING` is in SQL and what it’s used for, starting with an introductory paragraph (2-3 sentences).
- Include SQL database compatibility as a note.
- Links out to entries as needed.

Please refer to the [entry templates (term entry template in particular)](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by nikolaspoczekaj** [comment]
I'd like to contribute to this.
