### ISSUE TITLE
[Edit] Emojicode Bold Big O

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2221]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

Please bold any mentions of big-o notation. For instance, if the text includes "O(x)" to some effect, we'lll go ahead and use a pair of two asterisks, e.g., **O(x)**.

The entry should change the following file:

- `content/emojicode/concepts/dictionaries/dictionaries.md`

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by milan-lakhani** [comment]
Hey, can I take on this issue please?

**Comment by SSwiniarski** [comment]
@milan-lakhani You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@milan-lakhani It's been two weeks. Are you still working on this issue? Do you need assistance?
