### ISSUE TITLE
[Term Entry] SQL Math Functions EXP

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2258]
### Reason/inspiration (optional)

We would like a new term entry for the Math Function, `EXP`, in SQL.

The entry should go in a file in docs/content/sql/concepts/math-functions/terms/exp/exp.md

The entry should: 

- Explain what the math function `EXP` is in SQL and what it’s used for, starting with an introductory paragraph (2-3 sentences).
- Include SQL database compatibility as a note.
- Links out to entries as needed.

Please refer to the [entry templates (term entry template in particular)](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by rafiya2003** [comment]
can I work on this?

**Comment by ZapeeoSheikh** [comment]
Please assign me this under the label of SSOC'23 and GSSOC'23.

**Comment by SSwiniarski** [comment]
@ZapeeoSheikh You've already been assigned three issues. We don't assign people to more than three open issues at a time. Once you complete PRs for the issues you have been assigned, you can claim another open issue.

**Comment by SSwiniarski** [comment]
@rafiya2003 It's been two weeks. Are you still working on this issue? Do you need assistance? Note that in another week this will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@rafiya2003 I am unassigning you due to inactivity so someone else can work on this.

**Comment by mahrukh98** [comment]
@SSwiniarski I would like to work on this issue.

**Comment by SSwiniarski** [comment]
@mahrukh98 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by Peachtaco** [comment]
@SSwiniarski Hello, I would like to work on this issue please.

**Comment by mahrukh98** [comment]
Hi @Peachtaco, sorry I'm working on it.

**Comment by SSwiniarski** [comment]
@Peachtaco please check to see if an issue is already claimed before trying to claim it. There are plenty of unclaimed issues for you to choose from.

**Comment by SSwiniarski** [comment]
@mahrukh98 It's been two weeks. Are you still working on this issue? Note that in another week this will be unassigned due to inactivity.

**Comment by mahrukh98** [comment]
Yes, i'm on it. Hopefully will push the changes by tomorrow.

**Comment by SSwiniarski** [comment]
@mahrukh98 because of inactivity I am unassigning this issue so someone else can work on it.

**Comment by andyguo0228** [comment]
@SSwiniarski Hello, I would like to be assigned this issue to work on.

**Comment by SSwiniarski** [comment]
@andyguo0228 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!
