### ISSUE TITLE
[Term Entry] SQL Math Functions SIN

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2261]
### Reason/inspiration (optional)

We would like a new term entry for the Math Function, `SIN`, in SQL.

The entry should go in a file in docs/content/sql/concepts/math-functions/terms/sin/sin.md

The entry should: 

- Explain what the math function `SIN` is in SQL and what it’s used for, starting with an introductory paragraph (2-3 sentences).
- Include SQL database compatibility as a note.
- Links out to entries as needed.

Please refer to the [entry templates (term entry template in particular)](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by NikhilRaikwar** [comment]
I hope you're doing well. I would like to request the assignment of an issue to me. The issue involves creating a new term entry for the SQL math function SIN.

The task requires adding a term entry in the file sin.md located at docs/content/sql/concepts/math-functions/terms/sin/. The entry should provide an explanation of the SIN function in SQL, its usage, and include compatibility information for various SQL database systems. Furthermore, relevant links to related entries should be included.

I have thoroughly reviewed the content standards and I am confident in my ability to complete this task efficiently. I kindly request your consideration in assigning this issue to me.

**Comment by KTom101** [comment]
@NikhilRaikwar You're assigned. Thank you for taking the time to look at the documentation 🙏 If you haven't already, please also take a look at our revamped [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).

Is this your first contribution to Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by NikhilRaikwar** [comment]
@KTom101 I create a PR pls review it. #2319
