### ISSUE TITLE
[Term Entry] SQL Math Functions COS

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2262]
### Reason/inspiration (optional)

We would like a new term entry for the Math Function, `COS`, in SQL.

The entry should go in a file in docs/content/sql/concepts/math-functions/terms/cos/cos.md

The entry should: 

- Explain what the math function `COS` is in SQL and what it’s used for, starting with an introductory paragraph (2-3 sentences).
- Include SQL database compatibility as a note.
- Links out to entries as needed.

Please refer to the [entry templates (term entry template in particular)](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by nikolaspoczekaj** [comment]
I'd like to contribute to this.

**Comment by ZapeeoSheikh** [comment]
Please assign me this under the label of SSOC'23 and GSSOC'23.

**Comment by SSwiniarski** [comment]
@nikolaspoczekaj You're assigned!

**Comment by SSwiniarski** [comment]
@ZapeeoSheikh You're already assigned to three issues. We don't have people assigned to more than three open issues at a time. Complete some PRs for the issues you have been assigned to, then you can claim other open issues.
