### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by gaetgu** [Codecademy/docs#227]
I am in the middle of a project using Codecademy Docs, and the website has been acting up for a while. At first I thought it was just an issue with the server (because of multiple 404s and 503s), but now I see it has been removed from the `Resources` tab? 

I checked commits and blog posts to see if there was anything about taking it down, but I didn't see anything. Any help would be greatly appreciated!

**Comment by lukeecart** [comment]
@gaetgu Hey, yeah. "Docs crashed yesterday and will be down til Tuesday" -  according to sonnynomnom who said this in the `add summary & details semantic html elements` PR

**Comment by gaetgu** [comment]
👍🏽 Alright then. Thanks for letting me know!
