### ISSUE TITLE
[Term Entry] PHP Math Functions log()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2270]
### Reason/inspiration (optional)

We would like a new term entry for [PHP](https://www.codecademy.com/resources/docs/php) about the `log()` function.

The entry should go in a new file in `docs/content/php/concepts/math-functions/terms/log/log.md`

The entry should 

- Have a syntax section illustrating the function with a ` ```pseudo ` code block. 
- An example showing the function in use with a ` ```php ` code block. 
- A runnable codebyte example in a ` ```codebyte/php` block. 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by tanbirali** [comment]
Can I work on this issue?

**Comment by KTom101** [comment]
@tanbirali You're assigned. In addition to the documents linked in the description, please also take a look at our revamped Contribution Guide. After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

Is this your first contribution to Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by tanbirali** [comment]
@KTom101 No this is not my first Docs contribution.
I am a participant in social summer of Code event and they use this platform `quine.sh` where I found this issue to work on.

**Comment by KTom101** [comment]
@tanbirali I see! Thank you for deciding to make another contribution to Codecademy Docs then! 😁

**Comment by tanbirali** [comment]
You are welcome as beginner to open source I think documentation issues are something very helpful to understand how things work.
