### ISSUE TITLE
[Concept Entry] Git Revert

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2275]
### Reason/inspiration (optional)

We would like a new concept entry for [Git](https://www.codecademy.com/resources/docs/git) about the revert command.

The entry should go in a new file in `docs/content/git/concepts/revert/revert.md`

The entry should 

- Have an introductory paragraph (2-3 sentences) about what reverting is and does. 
- An example showing the command in use.
- Feel free to include additional context and headers (up for review).

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by EdwardDL97** [comment]
Hello! Can I please get assigned this topic?

**Comment by SSwiniarski** [comment]
@EdwardDL97 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@EdwardDL97 It's been two weeks. Are you still working on this issue? Do you need assistance?

**Comment by EdwardDL97** [comment]
Hello @SSwiniarski. I am still working on the issue and plan to finish it this weekend.  No assistance is needed at this time. Thank you.

**Comment by SSwiniarski** [comment]
@EdwardDL97 just note that in another week this issue will be unassigned due to inactivity.

**Comment by EdwardDL97** [comment]
Hello @SSwiniarski. This is my first time doing a pull request and just want to make sure I did everything right. Is there anything else that needs to be done on my end so someone can review it?

**Comment by SSwiniarski** [comment]
@EdwardDL97 Nope, be patient and one of the maintainers will review it. There are just four of us reviewing all the PRs, so occasionally it may take some time to get to things.
