### ISSUE TITLE
[Edit] Subject: Missing components in HTML Forms code snippet 

### ISSUE THREAD

**Issue by CBID2** [Codecademy/docs#2301]
### Type of Edit (select all that apply)

Clarify unclear content and/or terms, Add new content (definitions, codeblocks, etc.)

### Description (optional)

The code snippet in the [Inputs chapter](https://www.codecademy.com/resources/docs/html/elements/input) is missing some key information. For example, the labels need a `for` and `id` attributes, the password input is missing a `name` value, and the email input needs an `id`.  If possible, I would like to add them to the entry once #2242 is merged. 

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Himasnhu-AT** [comment]
@CBID2 @yoiang Hi, I'm new to open-source. I would like to work on this issue. please assign it to me?

**Comment by CBID2** [comment]
> @CBID2 @yoiang Hi, I'm new to open-source. I would like to work on this issue. please assign it to me?
> 
> 

Hi @Himasnhu-AT. I don't think I have the power to do this, and I wanted to work on this issue myself. Sorry 😔
However, if you want to get started in open source. Join me here at [LinksHub](https://github.com/rupali-codes/LinksHub). I'm one of the maintainers there.

**Comment by Himasnhu-AT** [comment]
@CBID2 Ok thnx

**Comment by KTom101** [comment]
@CBID2 I accidentally overlooked the part where you said you wanted to make the edits to this entry. I've assigned this to you, now. Thank you for your continued interest in contributing!

**Comment by KTom101** [comment]
@Himasnhu-AT Take a look at the issues that are currently [unclaimed](https://github.com/Codecademy/docs/issues?page=1&q=is%3Aissue+is%3Aopen+no%3Aassignee). If there is nothing right now you wish to work on, please check back regularly. We are always adding new issues. 

Or, you can let us know in the [discussion thread](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion) if there is something missing from Docs you would like to add 😄

**Comment by CBID2** [comment]
> @CBID2 I accidentally overlooked the part where you said you wanted to make the edits to this entry. I've assigned this to you, now. Thank you for your continued interest in contributing!

Thanks @KTom101! I just finished the PR. Here it is: #2325
