### ISSUE TITLE
[Bug/Error] Subject: Broken Link in Content-Standards documentation

### ISSUE THREAD

**Issue by codewithfan** [Codecademy/docs#2306]
### Actual Behavior

In the [content standards markdown file](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), at the bottom of the file, the concept entry template link directs to a file called "entry-template.md", when it should link to [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md)

https://github.com/Codecademy/docs/assets/85418632/33ffb727-e76c-43fe-a9b3-80d56c7249be

### Expected Behavior

The concept entry template hyperlink in the file should direct to [concept-entry-template.md](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md).

### On what browser(s) are you seeing the problem?

Other (not listed here)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by MMMMMMMZ** [comment]
It opened on my Windows device / chrome might be a Mac / chrome problem

**Comment by KTom101** [comment]
@codewithfan This appears to have been [fixed](https://github.com/Codecademy/docs/pull/2290) already. If you try it now, it should lead to the correct place.

**Comment by codewithfan** [comment]
@KTom101 It works now on my end! 

Thank you! Remarkable for being super quick about it 🔥

**Comment by KTom101** [comment]
@codewithfan No problem! Thank you for reaching out. I'll go ahead and close this out since this has been resolved 😄
