### ISSUE TITLE
Next.js description is inaccurate 

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Codecademy/docs#231]
> Typical React apps use the client-side browser to upload content, Next.js is unique in that it is a React framework built on top of Node.js. This helps curtail certain issues such as a user not having access to JavaScript. This also enables Next.js to render content on the server-side before it can be viewed by the client.

* Most popular React frameworks can SSR (Server Side Render) and are built on Node.js
* What is "certain" doing in the sentence? (odd grammar choice)

**Comment by bhagyamudgal** [comment]
@JoshuaKGoldberg Yeah you are right.

**Comment by Dusch4593** [comment]
I'm going to move forward on this issue and work on a small PR. Gonna give these new workflows a whirl!
