### ISSUE TITLE
General entry: What is GraphQL?

### ISSUE THREAD

**Issue by EugeneGohh** [Codecademy/docs#232]
I am making a general entry about [GraphQL](https://graphql.org/). This issue is open to anyone who wants to contribute.

Here is a blueprint I have made:

* A brief history of GraphQL
* What is GraphQL?
* Why use GraphQL?
* How GraphQL works under the hood?
* Who is using GraphQL?

**Comment by mdwiltfong** [comment]
Definitely interested in this. Coming from an eCommerce background I would like to add something about Shopify's GraphQL APIs.

**Comment by EugeneGohh** [comment]
> Definitely interested in this. Coming from an eCommerce background I would like to add something about Shopify's GraphQL APIs.

Sure! I have made a PR for this. Here #242.

**Comment by Dusch4593** [comment]
[#242](https://github.com/Codecademy/docs/pull/242) is merged. Closing this issue.
