### ISSUE TITLE
[Entry] Subject: Create the src term entry under HTML attributes

### ISSUE THREAD

**Issue by CBID2** [Codecademy/docs#2326]
### Reason/inspiration (optional)

I noticed that this attribute has not been discussed in the HTML attributes chapter. I would like to work on this please.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by diosDeNada** [comment]
Hello. Can you assign me this issue? :)

**Comment by SSwiniarski** [comment]
@CBID2 You've been assigned.

@diosDeNada, @CBID2 suggested this issue and asked to be assigned to it. Please look at the issues list for another unclaimed issue.
