### ISSUE TITLE
[Term Entry] JavaScript Dates .getTime()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2335]
### Reason/inspiration (optional)

.getTime()

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by cguttweb** [comment]
Could I be assigned to this issue please?
