### ISSUE TITLE
[Term Entry] JavaScript Dates .getUTCHours()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2340]
### Reason/inspiration (optional)

We would like a new term entry for JavaScript [Dates](https://www.codecademy.com/resources/docs/javascript/dates) about the `.getUTCHours()` method. The entry should go in a new file in `docs/content/javascript/concepts/dates/terms/getUTCHours/getUTCHours.md`

The entry should
    - Have an introductory paragraph about what the method is and does.
    - An example showing the method in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue. 

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by cguttweb** [comment]
Hello could I be assigned this please?

**Comment by KTom101** [comment]
@cguttweb You're assigned 😁
