### ISSUE TITLE
[Term Entry] <track>

### ISSUE THREAD

**Issue by CBID2** [Codecademy/docs#2343]
### Reason/inspiration (optional)

I noticed that there is no information about the `<track>` element in the Attributes entry. I’d like to write about this. 

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by yangc95** [comment]
@CBID2 I think you meant to write in the description that you want to add this term (track) to the HTML Elements entry. I think that's a great idea 👍

**Comment by CBID2** [comment]
> @CBID2 I think you meant to write in the description that you want to add this term (track) to the HTML Elements entry. I think that's a great idea 👍 

Yes that's correct @yangc95

**Comment by yangc95** [comment]
@CBID2 Cool! You're assigned! You can check out the [Contribution Guide](<https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md>) for additional information on contributing.

(As a reminder)
See [Content Standards](<https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md>) for an overview of styling tips that the [Style Guide](<https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md>) covers in detail.


After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving

**Comment by CBID2** [comment]
Thanks @yangc95! :) In the meantime, can you check out [this pull request](https://github.com/Codecademy/docs/pull/2330)? I'm really eager to get it merged! :)

**Comment by CBID2** [comment]
Hi, @yangc95! :) I made the pull request! :) It's #2468! :)

**Comment by CBID2** [comment]
@SSwiniarski, where's the live article? You usually post it in the issues.

**Comment by SSwiniarski** [comment]
@CBID2 It's listed [here](https://github.com/Codecademy/docs/pull/2468#issuecomment-1589693457) in the PR comments.
