### ISSUE TITLE
[Edit] PHP String Functions: hex2bin(), ltrim(), str_repeat()

### ISSUE THREAD

**Issue by cslylla** [Codecademy/docs#2347]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Edit the markdowns located inside these directories:

docs/content/php/concepts/string-functions/terms/hex2bin/hex2bin.md
docs/content/php/concepts/string-functions/terms/ltrim/ltrim.md
docs/content/php/concepts/string-functions/terms/str-repeat/str-repeat.md

Create a new "Example" section for each file with an example in a ```php block.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
@cslylla Consider yourself assigned. Feel free to open new issues for the other missing examples. If you want to be assigned to them, keep them to three open issues at a time.
