### ISSUE TITLE
[Term Entry] JavaScript Array.prototype.findLast()

### ISSUE THREAD

**Issue by codewithfan** [Codecademy/docs#2350]
### Reason/inspiration (optional)

Share the new ES2023 JavaScript array feature, .findLast(), as it still needs to be added to the Docs. I would love to work on this issue.

It can be found in the [Ecma TC39](https://github.com/tc39/proposal-array-find-from-last) repo.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
@codewithfan You're assigned. Make sure to include in the entry it's a new feature.

**Comment by SSwiniarski** [comment]
@codewithfan It's been two weeks, are you still working on this issue? Note that this will be unassigned due to inactivity in another week.

**Comment by codewithfan** [comment]
Yes please! Still working on it.

**Comment by SSwiniarski** [comment]
@codewithfan It's been another week. I'll give you a couple more days to submit a PR, otherwise I'll unassign this.
