### ISSUE TITLE
[Term Entry] Python Built-in Functions staticmethod

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2387]
### Reason/inspiration (optional)

Please note the  `@staticmethod`  decorator is mentioned [here](https://www.codecademy.com/resources/docs/python/classes#:~:text=Bird%20already%20ate.-,Static%20Methods,-It%20is%20also). But there is no mention on how to call the `staticmethod` as a regular function so we would like to have a new entry under Python’s [Built-in Functions](https://www.codecademy.com/resources/docs/python/built-in-functions) on this.

The entry should: 

- Explain why/when the `staticmethod` is used as a regular function

Be sure to include the following sections:

- A "Syntax" section with a ```pseudo code snippet.
- An "Example" section with a ```py code snippet.

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by H-zaarour** [comment]
Hi there I'm Houssam an undergraduate at AOU studying computer science along with courses at your platform I would like to be given the chance to solve this issue.

**Comment by SSwiniarski** [comment]
@H-zaarour You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@H-zaarour It's been two weeks. Are you still working on this issue. Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@H-zaarour I am unassigning you due to inactivity.

**Comment by Aproposofgenius** [comment]
Hello @SSwiniarski, if this is still open can I pick this up/claim?

**Comment by SSwiniarski** [comment]
@Aproposofgenius You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by Aproposofgenius** [comment]
This is my first time contributing to open-source but used to the PR process from work, I believe I received an email from Codecademy about docs and finally got a chance to check it out =) 
PR: https://github.com/Codecademy/docs/pull/2665
