### ISSUE TITLE
[Concept Entry] Discrete Math Congruences

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2390]
### Reason/inspiration (optional)

We would like a new concept entry for Congruences

The entry should go in a new file in docs/content/discrete-math/concepts/congruences/congruences.md

The entry should describe the following:
- a divides b
- a is congruent to b mod n
- linear congruence
- Reflexive Property
- Symmetric Property
- Transitive Property"

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by alimalim77** [comment]
Hello @codecademy-docs Please assign the issue to me. I have worked on Discrete Math Proof which is lefty for second review. Meanwhile, i can start working on this. I have read and understood the rules and standards from the contribution Docs.

**Comment by yangc95** [comment]
@alimalim77 You're assigned! You can check out the [Contribution Guide](<https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md>) for additional information on contributing.


See [Content Standards](<https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md>) for an overview of styling tips that the [Style Guide](<https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md>) covers in detail.


After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by alimalim77** [comment]
@yangc95 I just wanted to confirm it using LaTeX works according to the Codecademy Website Standards. The mathematics involved would require symbols and formulae to be added. Please let me know, if I should continue with it or find other option

**Comment by yangc95** [comment]
@alimalim77 Yeah, that should work. LaTex code blocks use `tex`. So you'll do "```tex" for those code blocks

**Comment by alimalim77** [comment]
<img width="932" alt="image" src="https://github.com/Codecademy/docs/assets/52186295/3e1d9be4-51ef-4b92-8fcd-0eefd7304a3a">
I am not sure, is that what you mean?
