### ISSUE TITLE
[Concept Entry] Discrete Math Proofs

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2391]
### Reason/inspiration (optional)

We would like a new concept entry for Mathematical Proofs

The entry should go in a new file in docs/content/discrete-math/concepts/proofs/proofs.md

The entry should describe the following:
-Conjecture
-Base Case

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by alimalim77** [comment]
Hello @codecademy-docs 
Can I be assigned for this issue?

**Comment by KTom101** [comment]
@alimalim77 You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our revamped [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by alimalim77** [comment]
@KTom101 Hey, just wanted to confirm there is no folder for discrete. Going to create one with .md file for the topic
