### ISSUE TITLE
[Term Entry] Discrete Math Proofs Induction

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2392]
### Reason/inspiration (optional)

We would like a new concept entry for the concept of Proof by Induction

The entry should go in a new file in docs/content/discrete-math/concepts/proofs/terms/proof-by-induction/proof-by-induction.md

The entry should describe the following:
- Base case
- Inductive step

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by newkprime** [comment]
I am doing the Codecademy GitHub unit and I would like to do this entry. I have been trying to figure out why the tasks for this are "2 out of 3".

**Comment by KTom101** [comment]
@newkprime The tasks are for the maintainers; you don't have to do anything about that. For the file path, you can just create it. We are currently in the process of adding the main "Discrete Math" hub to the site so this is why the file path does not exist currently. 

For your PR, please make sure you view the documentation linked in the description as well as the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) for additional information on contributing.

**Comment by SSwiniarski** [comment]
@newkprime It's been two weeks. Are you still working on this entry? Note that in another week this will be unassigned due to inactivity.

**Comment by newkprime** [comment]
@SSwiniarski Finishing the last example now. The days really got away from on this one.
