### ISSUE TITLE
[Concept Entry] Discrete Math Enumerations/Counting Theory

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2394]
### Reason/inspiration (optional)

We would like a new concept entry for the concept of Enumeration

The entry should go in a new file in docs/content/discrete-math/concepts/enumeration/enumeration.md

The entry should describe the following:

-Define Counting Theory
-Define Enumeration
-Principle of Inclusion and Exclusion
-Product Rule
-Sum Rule

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by harshitcompcode** [comment]
Assign me this issue

**Comment by KTom101** [comment]
@harshitcompcode I've assigned this to you. This will be your second assignment.
 
So that you know, contributors can be assigned to up to 3 issues at a time and will have to submit pull requests for the ones they're assigned to before being assigned to any additional issues. 🙂

**Comment by SSwiniarski** [comment]
@harshitcompcode It's been two weeks. Are you still working on this issue? Note that in another week this will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@harshitcompcode I am unassigning you due to inactivity.

**Comment by sreeharsha-rav** [comment]
I would like to work on this issue. I found out about codecademy docs through learning on codecademy.

**Comment by KTom101** [comment]
@sreeharsha-rav You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

**Comment by SSwiniarski** [comment]
@sreeharsha-rav It's been two weeks. Are you still working on this issue. Note that in another week this will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@sreeharsha-rav I am unassigning you due to inactivity.

**Comment by arisdelacruz** [comment]
@SSwiniarski 

Can I try to work on this one? Thanks

**Comment by harshitcompcode** [comment]
@SSwiniarski Give it back to me

**Comment by SSwiniarski** [comment]
@arisdelacruz, You're assigned. @harshitcompcode, @arisdelacruz came in ahead of you.

**Comment by arisdelacruz** [comment]
@SSwiniarski 

thanks

**Comment by arisdelacruz** [comment]
Hi, guys. Good day. Just a heads up. I'm finalizing my entry for the discrete math assignment.

Tbh, this even more challenging for me than the kotlin assignment, but, this is even more interesting.

I know I can do this with your help. Thanks.

**Comment by arisdelacruz** [comment]
@SSwiniarski 

just created a pull request, thanks

Just wonderin' though if an entry for the foundational "AND" and "OR" is needed

**Comment by SSwiniarski** [comment]
@KTom101, @yangc95, @caupolicandiaz What do you think of @arisdelacruz's suggestion?

**Comment by yangc95** [comment]
@arisdelacruz It seems that would be part of a "Propositional Logic" concept entry. Were you suggesting to create an issue on this to cover those logical operators?

I'd stick with covering the list of items mentioned in the description for this entry. But maybe it's a good idea to swap the order of sum and product rule. If there are additional headers that you think would be beneficial to this entry feel free to run it by us!

**Comment by arisdelacruz** [comment]
@yangc95

uh, not really referring to the logical operators, but more of expounding on the premises of the sum and product rule.

Most of the references that I was able to read refer to these as "Choices", addresses the need on how to combine the numbers correctly.

**Comment by yangc95** [comment]
@arisdelacruz I see, in which case, yes! Feel free to mention it in the context of the sum and product rules

**Comment by arisdelacruz** [comment]
Thank you @yangc95
