### ISSUE TITLE
[Term Entry] PHP Math Functions atanh()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2398]
### Reason/inspiration (optional)

We would like a new term entry for [PHP](https://www.codecademy.com/resources/docs/php) about the `atanh()` function.

The entry should go in a new file in `docs/content/php/concepts/math-functions/terms/atanh/atanh.md`

The entry should 

- Have a syntax section illustrating the function with a ` ```pseudo ` code block. 
- An example showing the function in use with a ` ```php ` code block. 
- A runnable codebyte example in a ` ```codebyte/php` block. 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by NikhilRaikwar** [comment]
I hope you're doing well. I would like to request the assignment of an issue to me. The issue involves creating a new term entry for the PHP math function atanh().

The task requires adding a term entry in the file atanh.md located at docs/content/php/concepts/math-functions/terms/atanh/. The entry should include a syntax section with a pseudocode block illustrating the function, an example showing the function in use with a PHP code block, and a runnable codebyte example for further clarity.

I have thoroughly reviewed the content standards and I am confident in my ability to complete this task efficiently. I kindly request your consideration in assigning this issue to me.

**Comment by KTom101** [comment]
@NikhilRaikwar I've assigned this to you. This will be your second assignment. 

As a reminder, contributors can be assigned to up to 3 issues at a time and will have to submit pull requests for the ones they're assigned to before being assigned to any additional issues. 🙂

**Comment by SSwiniarski** [comment]
@NikhilRaikwar It's been two weeks. Are you still working on this issue? Note that in another week this will be unassigned due to inactivity.

**Comment by NikhilRaikwar** [comment]
Ya @SSwiniarski I will working on it.

**Comment by SSwiniarski** [comment]
@NikhilRaikwar Glad to hear it. Try and submit a PR in the next week.

**Comment by NikhilRaikwar** [comment]
Yes Sir

**Comment by SSwiniarski** [comment]
@NikhilRaikwar Since we haven't seen a PR I'm going to unassign you due to inactivity.

**Comment by Dijok243** [comment]
@SSwiniarski Hi, I am interested to work on this issue, I found out about Docs through the newsletter and decided to give it a try.

**Comment by SSwiniarski** [comment]
@Dijok243 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!
