### ISSUE TITLE
[Term Entry] PHP Math Functions is_finite()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2399]
### Reason/inspiration (optional)

We would like a new term entry for [PHP](https://www.codecademy.com/resources/docs/php) about the `is_finite()` function.

The entry should go in a new file in `docs/content/php/concepts/math-functions/terms/is-finite/is-finite.md` (Note the path uses dashes, not underscores.)

The entry should 

- Have a syntax section illustrating the function with a ` ```pseudo ` code block. 
- An example showing the function in use with a ` ```php ` code block. 
- A runnable codebyte example in a ` ```codebyte/php` block. 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by LewisMK** [comment]
Hello, I am a technical writer and new to open source. I would like to contribute to your repo by working on this issue. @codecademy-docs

**Comment by KTom101** [comment]
@LewisMK You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

I see you said you're new to open source. How did you find out about contributing to Codecademy Docs?

**Comment by LewisMK** [comment]
@KTom101 thank you very much. I will go through all the materials and requirements. 

I found out about Codecademeny Docs through a Twitter post on open source contributions.
