### ISSUE TITLE
`what-is-git.md` description is too long

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#243]
The description for the "What is Git?" entry inside of `content/general/content/what-is-git/`, is too long and needs to be shortened. 

Per the `terms-entry-template.md`: 

> Description: 'A brief description' # Required; ideally under 150 characters (used in search engine results and content previews)

The character count of the description for "What is Git?" is currently 522 characters.

**Comment by lukeecart** [comment]
@Dusch4593 Can we close this issue now?
