### ISSUE TITLE
[Term Entry] JavaScript Dates .setHours()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2430]
### Reason/inspiration (optional)

We would like a new term entry for JavaScript [Dates](https://www.codecademy.com/resources/docs/javascript/dates) about the `.setHours()` method. The entry should go in a new file in `docs/content/javascript/concepts/dates/terms/setHours/setHours.md`

The entry should
    - Have an introductory paragraph about what the method is and does.
    - An example showing the method in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Yashi11** [comment]
Hey!!
May I help in this one under Social Summer of Code 2023??
Regards

**Comment by SSwiniarski** [comment]
@Yashi11 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment]
@Yashi11 Also note that we limit folks to claiming no more than three open issues at a time. Please submit PRs for your claimed issues before attempting to claim any new ones.

**Comment by SSwiniarski** [comment]
@Yashi11 It's been two weeks. Are you still working on this entry? Note that in another week this will be unassigned due to inactivity.

**Comment by Yashi11** [comment]
Yeah. Will be working this weekend.

**Comment by Yashi11** [comment]
> @Yashi11 It's been two weeks. Are you still working on this entry? Note that in another week this will be unassigned due to inactivity.

Yeah. Will be working this weekend.

**Comment by SSwiniarski** [comment]
@Yashi11 I'm giving you a little extra time since you said you're working on it. Please submit a PR in the next couple of days.

**Comment by Yashi11** [comment]
> @Yashi11 I'm giving you a little extra time since you said you're working on it. Please submit a PR in the next couple of days.

You may assign this to someone else as I am caught up in something and cannot work on this anymore. Sorry for that.

**Comment by SSwiniarski** [comment]
@Yashi11 Ok, I am unassigning you.

**Comment by NickUsey** [comment]
@SSwiniarski for this one it says that they would like a new entry for the Dates page for ".setHours( )". Do they mean ".getHours()"?

**Comment by SSwiniarski** [comment]
@NickUsey No, it means `.setHours()`, we already have a entry for `.getHours()`

**Comment by eskuode** [comment]
Hi, I would like to do it.

**Comment by SSwiniarski** [comment]
@eskuode You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?
