### ISSUE TITLE
[Concept Entry] Java Date

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2437]
### Reason/inspiration (optional)

Please add a new entry on the `Date` class provided under the `java.util` package. This will be a new concept entry which will open the opportunity to add `Date `methods as term entries down the line.

The new file will go under `content/java/concepts/date/date.md` and include information on what the `Date` class is and how an object of the `Date` class can be constructed. 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by dakshdeepHERE** [comment]
claim

**Comment by KTom101** [comment]
@dakshdeepHERE I have assigned this to you. Please also remember you're assigned to two [ugc](https://github.com/Codecademy/ugc) issues. Open up pull requests before requesting to be assigned to any more issues.

**Comment by dakshdeepHERE** [comment]
@KTom101 they are almost done I'm just making diagrams

**Comment by KTom101** [comment]
@dakshdeepHERE Entry is live 🎉 https://www.codecademy.com/resources/docs/java/date

<img width="812" alt="Screenshot 2023-06-21 at 2 24 16 PM" src="https://github.com/Codecademy/docs/assets/40783324/8637a28c-796e-42ba-a30a-a748b78b3bf3">
