### ISSUE TITLE
[Term Entry] Go Math Functions Cos()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2440]
### Reason/inspiration (optional)

We would like a new term entry for [Go](https://www.codecademy.com/resources/docs/go) about the `Cos()` function.

The entry should go in a new file in `docs/content/go/concepts/math-functions/terms/cos/cos.md`

The entry should 

- Have a syntax section illustrating the function with a ` ```pseudo ` code block. 
- An example showing the function in use with a ` ```go ` code block. 
- A runnable codebyte example in a ` ```codebyte/golang` block. 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by 4hbab** [comment]
@codecademy-docs could you please assign me to this issue?

**Comment by KTom101** [comment]
@4hbab You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our revamped [[Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide)](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by 4hbab** [comment]
@KTom101 Hey, Yes I looked at the revamped contribution guide.

Yes this is my first contribution to Codecademy Docs. I found it from the website Quine.sh

**Comment by KTom101** [comment]
@4hbab Thanks for letting us know! We've been noticing an increase in people coming from quine.sh 😄

**Comment by SSwiniarski** [comment]
Closing as fulfilled by https://github.com/Codecademy/docs/pull/2487
