### ISSUE TITLE
[Concept Entry] Swift Collections

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2443]
### Reason/inspiration (optional)

We would like a new concept entry for Swift about Collections. The entry should go in a new file in docs/content/swift/concepts/collections/collections.md

The entry should
    - Have an introductory paragraph about what the concept.
    - Code blocks or codebytes displaying different aspects of the concept.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by d-fontanez** [comment]
Hello, can I please be assigned this issue?

**Comment by Korbokid** [comment]
Can i get this issue assigned to me?

**Comment by SSwiniarski** [comment]
@Korbokid You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment]
@Korbokid It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by diosDeNada** [comment]
Hello @SSwiniarski, if @Korbokid does not appear, I would appreciate it if you assigned me this Issue. Now I know how to work with Docs :)

**Comment by SSwiniarski** [comment]
@Korbokid I am unassigning you due to inactivity so @diosDeNada can work on it.

**Comment by SSwiniarski** [comment]
@diosDeNada You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by diosDeNada** [comment]
@swiniarski gracias. I gonna work on this the weekend.

**Comment by diosDeNada** [comment]
@SSwiniarski sorry, but i need to decline :( 
They increased the workload at my place, and I won't have time to do this and continue on my path in CC.

**Comment by SSwiniarski** [comment]
@diosDeNada No problem. Thanks for letting us know.

**Comment by Imabyrd** [comment]
Hi may I please be assigned this task

**Comment by SSwiniarski** [comment]
@Imabyrd You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment]
@Imabyrd It's been two weeks. Are you still working on this entry? Note that in another week this will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@Imabyrd I am unassigning this due to inactivity.

**Comment by RazBalin** [comment]
Hey guys. I'd like to have a _swift_ go at it.. 
let me know if possible :)

**Comment by SSwiniarski** [comment]
@RazBalin You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by RazBalin** [comment]
Thank you! 
It is my first contribution to Docs, and in general. I came across this repo during the course 'Introduction to Open Source' on Codecademy. I have recently created a PR request from my fork, under a new branch, as requested in the guidelines. I sincerely hope I did not do any mistakes with the process :'D

RB

**Comment by mshannahj** [comment]
Can I get this issue assigned to me

**Comment by SSwiniarski** [comment]
@mshannahj this issue is already assigned and has a PR submitted for it. Please look for an issue without the "claimed" tag to claim.

**Comment by caupolicandiaz** [comment]
I've reopened this issue because of the lack of progress by the previous contributor

**Comment by cslylla** [comment]
I would like to work on this issue!

**Comment by SSwiniarski** [comment]
@cslylla You're assigned.

**Comment by cslylla** [comment]
I am still working on this issue, I can submit the PR at the end of the week.

**Comment by SSwiniarski** [comment]
@cslylla It's been a while. If we haven't seen a PR in the next few days, this will be unassigned due to inactivity.

**Comment by cslylla** [comment]
@SSwiniarski Thank you for the reminder! I have just submitted a PR. Sorry for the delay, it took me longer than I expected!
