### ISSUE TITLE
[Concept Entry] Swift Extentions

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2444]
### Reason/inspiration (optional)

We would like a new concept entry for Swift about Extensions. The entry should go in a new file in docs/content/swift/concepts/extensions/extensions.md

The entry should
    - Have an introductory paragraph about what the concept.
    - Code blocks or codebytes displaying different aspects of the concept.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by raschuh** [comment]
Hi! I'd like to take this on.

**Comment by KTom101** [comment]
@raschuh You're assigned. Please make sure you take a look at our revamped [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) as well as the documents listed in the description.

Have you contributed to Codecademy Docs before? If not, we're curious about where you heard about contributing to Docs.

**Comment by raschuh** [comment]
@KTom101 This would be my second contribution and I submitted a PR for the first one yesterday (Issue #2212). :)
