### ISSUE TITLE
[Concept Entry] Swift Methods

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2445]
### Reason/inspiration (optional)

We would like a new concept entry for Swift about Methods. The entry should go in a new file in docs/content/swift/concepts/methods/methods.md

The entry should
    - Have an introductory paragraph about what the concept.
    - Code blocks or codebytes displaying different aspects of the concept.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by AlexWontCook** [comment]
Hello,
  

  
Please can you unassign me from this issue? I was intending to issue another request but have had some stuff come up so won’t be able to resolve in a timely manner, thanks
  

  
Alex
  
  
  
  
  
  
  

  
  
>

**Comment by SSwiniarski** [comment]
@AlexWontCook You've been unassigned.

**Comment by Wakodono** [comment]
Hi, I'd very much like to work on this issue. I came across the repo while doing some projects on Codecademy 👨🏾‍💻

**Comment by SSwiniarski** [comment]
@Wakodono You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!
