### ISSUE TITLE
[Term Entry] Swift Arrays .filter()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2446]
### Reason/inspiration (optional)

We would like a new term entry for Swift [Arrays](https://www.codecademy.com/resources/docs/swift/arrays) about the .filter() method. The entry should go in a new file in docs/content/swift/concepts/arrays/terms/filter/filter.md

The entry should
    - Have an introductory paragraph about what the method is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the method in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by MandyDoree** [comment]
Hi! Can I be assigned to this issue?

**Comment by KTom101** [comment]
@MandyDoree You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our revamped [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by MandyDoree** [comment]
@KTom101 Thank you!

Yes, it is my first contribution to Codecademy Docs. I am using Codecademy to expand my skills (I have been in software development as QA for a while but automation made me realize I like coding way more than I expected) and this opportunity showed up in my Git course.

So please let me know if you have any additional advice, apart from the resources I can already find in the issue. And don't be shy with giving feedback!
