### ISSUE TITLE
[Term Entry] Swift Arrays .shuffle()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2448]
### Reason/inspiration (optional)

We would like a new term entry for Swift [Arrays](https://www.codecademy.com/resources/docs/swift/arrays) about the .shuffle() method. The entry should go in a new file in docs/content/swift/concepts/arrays/terms/shuffle/shuffle.md

The entry should
    - Have an introductory paragraph about what the method is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the method in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by dev-03960** [comment]
Is this issue is still open to resolve and if it is open then I can resolve this please assign me under the SSOC

**Comment by KTom101** [comment]
@dev-03960 I've assigned this to you. This will be your second assignment. 
So that you know, contributors can be assigned to up to 3 issues at a time and will have to submit pull requests for the ones they're assigned to before being assigned to any additional issues. 🙂

**Comment by dev-03960** [comment]
Thank you for assigning me the task I will do it as my best
