### ISSUE TITLE
[Entry] Subject: Emoji 

### ISSUE THREAD

**Issue by CBID2** [Codecademy/docs#2474]
### Reason/inspiration (optional)

I was perusing through the [Markdown entry](https://www.codecademy.com/resources/docs/markdown) and found that it could use more entries. For one, I've seen a lot of `md.` files use emojis, so I'd love to write an entry on this topic! :) 

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by KTom101** [comment]
@CBID2 I think this is a good thing to add. Can you also include a list of some of the emoji short codes in your entry?

**Comment by CBID2** [comment]
> @CBID2 I think this is a good thing to add. Can you also include a list of some of the emoji short codes in your entry?

Sure @KTom101! :)

**Comment by CBID2** [comment]
Hi @yangc95 and @SSwiniarski! :) I created a pull request for this issue! :) It's number #2475! :)
