### ISSUE TITLE
[Entry] Subject: IDS using Snort in cloud computing

### ISSUE THREAD

**Issue by SimranLahrani842** [Codecademy/docs#2483]
### Reason/inspiration (optional)

Step wise will be xplained in windows ..
IDS is an important topic in cloud computing and in cybersecurity.

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by SimranLahrani842** [comment]
> @SimranLahrani842 Are you requesting to be assigned this issue?

Yes sir assign me please

**Comment by KTom101** [comment]
@SimranLahrani842 Is this going to be a tutorial on Intrusion Detection using Snort? If you're planning on showing it step-by-step, then this would be more suited for [UGC](https://github.com/Codecademy/ugc) content. Let me know and we can transfer this issue to the ugc repo.

**Comment by SimranLahrani842** [comment]
> @SimranLahrani842 Is this going to be a tutorial on Intrusion Detection using Snort? If you're planning on showing it step-by-step, then this would be more suited for [UGC](https://github.com/Codecademy/ugc) content. Let me know and we can transfer this issue to the ugc repo.

As I have implemented I ll write down the steps in a doc format and upload it.
Please assign me this issue @KTom101

**Comment by KTom101** [comment]
@SimranLahrani842 I've opened this issue in the UGC repo. Please add a comment under the issue [here](https://github.com/Codecademy/ugc/issues/58) so I can officially assign you.

**Comment by KTom101** [comment]
@SimranLahrani842 Closing this out since you've been assigned to this under the UGC repo!

**Comment by SimranLahrani842** [comment]
> @SimranLahrani842 Closing this out since you've been assigned to this under the UGC repo!

Ugc is not included in the ssoc program.
Please assign me here itself in cc folder i ll write.
@KTom101

**Comment by KTom101** [comment]
@SimranLahrani842 Feel free to take a look at other unclaimed issues under Docs. This specific issue would have to be created under UGC due to the nature of the content. I can go ahead and unassign you from the UGC one.

**Comment by SimranLahrani842** [comment]
> @SimranLahrani842 Feel free to take a look at other unclaimed issues under Docs. This specific issue would have to be created under UGC due to the nature of the content. I can go ahead and unassign you from the UGC one.

Already added to ugc folder please check..
