### ISSUE TITLE
[Entry] Subject: depth first search in AI

### ISSUE THREAD

**Issue by SimranLahrani842** [Codecademy/docs#2484]
### Reason/inspiration (optional)

Depth first search will be explained along with program . And it's working will be explained properly.

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
@SimranLahrani842 are you requesting to be assigned this issue?

**Comment by SimranLahrani842** [comment]
> @SimranLahrani842 are you requesting to be assigned this issue?

Yes mam please assign me

**Comment by SimranLahrani842** [comment]
> > @SimranLahrani842 are you requesting to be assigned this issue?
> 
> Yes sir  please assign me

**Comment by KTom101** [comment]
@SimranLahrani842 I'm assigning this to you. The structure of your entry can be similar to that of the [Breadth First Search entry](https://www.codecademy.com/resources/docs/ai/search-algorithms/breadth-first-search). Please write your file in markdown and place it in the following file path: `content/ai/concepts/search-algorithms/terms/depth-first-search/depth-first-search.md`.

In addition to the [Contributing Guide](https://www.codecademy.com/resources/docs/contribution-guide), use the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) as reference when making the PR.

Would this be your first contribution to Codecademy Docs? If so, how did you find out about the Docs repo?

**Comment by SimranLahrani842** [comment]
> @SimranLahrani842 I'm assigning this to you. The structure of your entry can be similar to that of the [Breadth First Search entry](https://www.codecademy.com/resources/docs/ai/search-algorithms/breadth-first-search). Please write your file in markdown and place it in the following file path: `content/ai/concepts/search-algorithms/terms/depth-first-search/depth-first-search.md`.
> 
> In addition to the [Contributing Guide](https://www.codecademy.com/resources/docs/contribution-guide), use the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) as reference when making the PR.
> 
> Would this be your first contribution to Codecademy Docs? If so, how did you find out about the Docs repo?

I got to know from quine website...ok sir I ll use the same template.

**Comment by SSwiniarski** [comment]
@SimranLahrani842 It's been two weeks. Are you still working on this issue? Note that in another week this will be unassigned due to inactivity.

**Comment by SimranLahrani842** [comment]
> @SimranLahrani842 It's been two weeks. Are you still working on this issue? Note that in another week this will be unassigned due to inactivity.

Yes sir I ll finish it off ..please check my other pr in ugc folder please sir
@KTom101 @SSwiniarski

**Comment by SimranLahrani842** [comment]
> @SimranLahrani842 It's been two weeks. Are you still working on this issue? Note that in another week this will be unassigned due to inactivity.

Please review my PR #2594  @KTom101 and @SSwiniarski
