### ISSUE TITLE
[Edit] Subject: Attributes

### ISSUE THREAD

**Issue by CBID2** [Codecademy/docs#2491]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

 Now that the entry for the [src attribute](https://www.codecademy.com/resources/docs/html/attributes/src) is created, STBs src example in [the attributes entry](https://www.codecademy.com/resources/docs/html/attributes)
is ready to be removed just like you suggested @yangc95:) 

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by elliezub** [comment]
I would like to be assigned to this issue

**Comment by SSwiniarski** [comment]
@elliezub You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment]
@CBID2 you may want to go over the edit in more detail with @elliezub, since they may not have seen your conversations with @yangc95.

**Comment by elliezub** [comment]
Thank you for assigning me! Chrissy invited me to contribute here, I'll contact her to get some more details about the edit. :)

**Comment by CBID2** [comment]
> Thank you for assigning me! Chrissy invited me to contribute here, I'll contact her to get some more details about the edit. :)

Hey @elliezub! :) I DMed you more information about this issue on Twitter. Check them out. :)
