### ISSUE TITLE
[Term Entry] JavaScript Dates .setTime()

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#2501]
### Reason/inspiration (optional)

We would like a new term entry for JavaScript [Dates](https://www.codecademy.com/resources/docs/javascript/dates) about the `.setTime()` method. The entry should go in a new file in `docs/content/javascript/concepts/dates/terms/setTime/setTime.md`

The entry should
    - Have an introductory paragraph about what the method is and does.
    - An example showing the method in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by burty197** [comment]
Hi , I would like to contribute to this please

**Comment by SSwiniarski** [comment]
@ShivangRawat30, we've gone through a review so we're going to keep the PR, but you are **not** supposed to submit a PR for an issue you have not been assigned. There was someone already waiting to contribute to this issue. Do **not** do this again, we have assignments to prevent this situation, where two people are working on the same issue.

**Comment by SSwiniarski** [comment]
@burty197 can you request another issue? I'm sorry but we had another user go ahead an submit a PR before they were assigned this issue. Tag me so I can make sure you get assigned to the new issue.
