### ISSUE TITLE
[Term Entry] PHP Date Functions date_diff()

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#2506]
### Reason/inspiration (optional)

We would like a new term entry for [PHP](https://www.codecademy.com/resources/docs/php) about the `date_diff()` function.

The entry should go in a new file in `docs/content/php/concepts/date-functions/terms/date-diff/date-diff.md` (Note the dashes rather than underscores)

The entry should 

- Have a syntax section illustrating the function with a ` ```pseudo ` code block. 
- An example showing the function in use with a ` ```php ` code block. 
- A runnable codebyte example in a ` ```codebyte/php` block. 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by bitsalt** [comment]
I'd like to start with this issue. Thanks.

**Comment by KTom101** [comment]
@bitsalt You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our revamped [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by bitsalt** [comment]
@KTom101 yes, this is my first contribution. I started my career as a technical writer. After 20 years of programming (and now some SRE/automation work), I'd like to get back to writing something other than code. I've used Codecademy a few times, but didn't find the Docs until I was recently searching for opportunities to contribute documentation. My writing samples are...a bit old. :-D
