### ISSUE TITLE
[Concept Entry] SQL Subqueries

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#2508]
### Reason/inspiration (optional)

We would like a new concept entry for [SQL] about subqueries.
The entry should go in a new file in docs/content/sql/concepts/subqueries/subqueries.md

The entry should
  - Have an introductory paragraph about what subqueries are.
  - Have examples showing different use cases:
    - Used in place of a scalar.
    - Used in plase of a table.
    - Used in a WHERE clause.
     
Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by NikhilRaikwar** [comment]
I hope this message finds you well. I would like to request the assignment of an issue to me. The issue involves creating a new concept entry for SQL about subqueries.

The task requires adding the entry to a new file located at docs/content/sql/concepts/subqueries/subqueries.md. The entry should include:

1. An introductory paragraph explaining what subqueries are and their purpose in SQL.
2. Examples demonstrating different use cases:
   - Using subqueries in place of a scalar.
   - Using subqueries in place of a table.
   - Using subqueries in a WHERE clause.
   
I have thoroughly reviewed the content standards and I am confident in my ability to complete this task efficiently. I kindly request your consideration in assigning this issue to me.

**Comment by KTom101** [comment]
@NikhilRaikwar Thanks for requesting, you're assigned.
