### ISSUE TITLE
General entry: What is Cloud Computing?

### ISSUE THREAD

**Issue by EugeneGohh** [Codecademy/docs#251]
Requesting 1 new entry in the [General](https://www.codecademy.com/resources/docs/general) topic:

- Name: "What is Cloud Computing?"
- Folder: https://github.com/Codecademy/docs/tree/main/content/general/concepts

**Comment by bhagyamudgal** [comment]
Can I work on this?

**Comment by EugeneGohh** [comment]
> Can I work on this?

Sure mate.

**Comment by EugeneGohh** [comment]
@bhagyamudgal 

Feel free to use this as a head start if needed (Just a sugesstion):

- What is Cloud Computing?
- A brief history about Cloud Computing
- Why adopt Cloud Computing?
- How does Cloud Computing work?
- Companies that have moved to the Cloud?

**Comment by bhagyamudgal** [comment]
@EugeneGohh Thanks it will help me alot.

**Comment by EugeneGohh** [comment]
This issue is related to PR #252 .
