### ISSUE TITLE
[Term Entry] Python Built-in Functions format() 

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#2525]
### Reason/inspiration (optional)

We would like a new term entry on the format() Python: [Built-in Function](https://www.codecademy.com/resources/docs/python/built-in-functions). The entry should go in a new file under `docs/content/python/concepts/built-in-functions/terms/format/format.md`

> **Note:** This is for the built-in `format()` function, **not** the [string `.format()` method](https://www.codecademy.com/resources/docs/python/strings/format).

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo`` code snippet.
- An "Example" section with a ` ```py `code snippet.
- A “Codebyte Example” section with a ` ```codebyte/python ` snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by David-OC17** [comment]
@SSwiniarski I would like to be assigned with this issue and help with the project. I learned about the docs repo through a CodeAcademy course. I have experience using Pyhton and I think I could implement the format( ) function.

**Comment by KTom101** [comment]
@David-OC17 You're assigned. Thank you for your interest in contributing to Codecademy Docs. 

In addition to the documents linked in the description, please also take a look at our revamped [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

**Comment by ajitexl** [comment]
i need to do assined me for some , I am very new in open source.

**Comment by echeng166** [comment]
Can I work on this? Thanks!

**Comment by SSwiniarski** [comment]
@ajitexl & @echeng166  This issue is already assigned and has a PR being reviewed. Please look for open issues without the "claimed" tag when looking for places to contribute.
