### ISSUE TITLE
[Edit] Subject: GitHub

### ISSUE THREAD

**Issue by CBID2** [Codecademy/docs#2527]
### Reason/inspiration (optional)

I didn’t see Good First Issues in the GitHub chapter, so I’d like to add it. I think readers would benefit from it because they often ask how to find issues in projects.

### Entry Type (select all that apply)

- Add new content (definitions, codeblocks, etc.)
### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
@yangc95, @KTom101, @caupolicandiaz, What do you think about this. I'm inclined that it may be to GitHub-centric to be under open source. Maybe have a GitHub entry under Git?

**Comment by CBID2** [comment]
> @yangc95, @KTom101, @caupolicandiaz, What do you think about this. I'm inclined that it may be to GitHub-centric to be under open source. Maybe have a GitHub entry under Git?

Now that I think about @SSwiniarski, it does sound GitHub associated. I'm willing to add my entry in that section if it's more appropriate.

**Comment by KTom101** [comment]
@SSwiniarski @CBID2 Yes, I agree that this is more GitHub oriented than open source. We currently have a [GitHub entry](https://www.codecademy.com/resources/docs/general/github) under general. Maybe this could be added there or as a term entry. I'm also thinking that the GitHub entry might should be moved to be a concept entry under Git. 

cc @yangc95 @caupolicandiaz

**Comment by CBID2** [comment]
> @SSwiniarski @CBID2 Yes, I agree that this is more GitHub oriented than open source. We currently have a [GitHub entry](https://www.codecademy.com/resources/docs/general/github) under general. Maybe this could be added there or as a term entry. I'm also thinking that the GitHub entry might should be moved to be a concept entry under Git. 
> 
> cc @yangc95 @caupolicandiaz 

Then it's settled @KTom. I'll add it to GitHub

**Comment by KTom101** [comment]
@CBID2 Sounds good, I've assigned you to this.

**Comment by CBID2** [comment]
> @CBID2 Sounds good, I've assigned you to this.

Hi @KTom101! :) I made the PR. It's #2575
