### ISSUE TITLE
[Edit] PHP String Functions: str_replace(), str_shuffle(), str_len()

### ISSUE THREAD

**Issue by cslylla** [Codecademy/docs#2530]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Edit the markdowns located inside these directories:

docs/content/php/concepts/string-functions/terms/str_replace/str_replace.md
docs/content/php/concepts/string-functions/terms/str_shuffle/str_shuffle.md
docs/content/php/concepts/string-functions/terms/str_len/str_len.md

Create a new "Example" section for each file with an example in a ```php block.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by cslylla** [comment]
I would like to work on this issue.

**Comment by phuongtrieu97coder** [comment]
I would like to work on this issue

**Comment by SSwiniarski** [comment]
@phuongtrieu97coder, @cslylla is already assigned to this issue. Please look through our open issues and select one that is unclaimed.

**Comment by SSwiniarski** [comment]
@cslylla It's been two weeks. Are you still working on this issue? Note that in another week this will be unassigned due to inactivity.

**Comment by cslylla** [comment]
@SSwiniarski Thank you for the reminder. I have just submitted the PR.
