### ISSUE TITLE
[Term Entry] JavaScript Dates .setUTCMilliseconds()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2550]
### Reason/inspiration (optional)

We would like a new term entry for JavaScript [Dates](https://www.codecademy.com/resources/docs/javascript/dates) about the `.setUTCMilliseconds()` method. The entry should go in a new file in `docs/content/javascript/concepts/dates/terms/setUTCMilliseconds/setUTCMilliseconds.md`

The entry should
    - Have an introductory paragraph about what the method is and does.
    - An example showing the method in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by zk497** [comment]
Hello, I would like to work on this issue.

**Comment by KTom101** [comment]
@zk497 You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our revamped [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by zk497** [comment]
@KTom101 Alright, I will do that. 

Yes, this is my first contribution to Codecademy Docs. Surprisingly, I found out about this through an Instagram reel.

**Comment by KTom101** [comment]
@zk497 That's so cool! Do you mind me asking who posted the reel?

**Comment by zk497** [comment]
@KTom101 Not at all. However, I just double-checked and realized that the page actually shared Codecademy's post on their story. My bad. 

Anyways, it still helped me find out about this!

This is the page - `thecodedose`

**Comment by SSwiniarski** [comment]
@zk497 It's been two weeks. Are you still working on this issue? Note that in another week this issue will be unassigned due to inactivity.

**Comment by Judis07** [comment]
Hello, I can  contribute and work on this issue if the issue is still open. 
Thanks.

**Comment by SSwiniarski** [comment]
@zk497 I am unassigning you due to inactivity.

**Comment by SSwiniarski** [comment]
@Judis07 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?
