### ISSUE TITLE
[Term Entry] PHP Arrays array_flip()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2557]
### Reason/inspiration (optional)

We would like a new term entry for [PHP](https://www.codecademy.com/resources/docs/php) about the `array_flip()` function.

The entry should go in a new file in `docs/content/php/concepts/arrays/terms/array-flip/array-flip.md` (Note the dashes rather than underscores)

The entry should 

- Have a syntax section illustrating the function with a ` ```pseudo ` code block. 
- An example showing the function in use with a ` ```php ` code block. 
- A runnable codebyte example in a ` ```codebyte/php` block. 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by braanj** [comment]
Hello @codecademy-docs, I'd love to work on this term entry.

**Comment by SSwiniarski** [comment]
@braanj You're assigned. I noticed that this is the third issue I've assigned you. Note that we generally only permit people to claim three open issues at a time. Once you submit some PRs for the issues you've already claimed, you can claim more issues.
