### ISSUE TITLE
[Concept Entry] SwiftUI Animation

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2566]
### Reason/inspiration (optional)

We would like a new concept entry for SwiftUI about Animation. The entry should go in a new file in docs/content/swiftui/concepts/animation/animation.md

The entry should
    - Have an introductory paragraph about the concept.
    - Code blocks or codebytes displaying different aspects of the concept.
    - Internal linking as applicable.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by EngOmarAhmedIOS** [comment]
I would like to do this entry about animations

**Comment by Efury1** [comment]
Hi, I would like to work on this. Can I have it assigned? :)

**Comment by KTom101** [comment]
@Efury1 You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our revamped [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by Efury1** [comment]
Thank you, I'll start tonight 🥳

**Comment by SSwiniarski** [comment]
@Efury1 It's been over three weeks since you were assigned. Are you still working on this issue? Note that in another week this will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@Efury1 I am unassigning you due to inactivity.

**Comment by EngOmarElsayed** [comment]
Hey I want to take this doc

**Comment by SSwiniarski** [comment]
@EngOmarElsayed, You're assigned.
