### ISSUE TITLE
[Entry] Subject: JavaScript Storage

### ISSUE THREAD

**Issue by SimranLahrani842** [Codecademy/docs#2593]
### Reason/inspiration (optional)

Difference between both the storage and their code in console along with output.

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by yangc95** [comment]
@SimranLahrani842 I think this is a good idea! However, we're going to need to break this down into its concepts and terms. I've gone ahead an named this Storage for the object that can be accessed in the browser. You can go into localStorage and sessionStorage objects here. Hope this helps!

**Comment by yangc95** [comment]
I'm also making a note here that this entry will be populated with the methods for the storage objects like `setItem(key, value)`, `getItem(key)`, etc.

**Comment by vito588p** [comment]
@yangc95 
Hello! I'm interested in taking this issue on, the differences between cookies, local storage, and session storage, as well as the methods. Additionally, I'm wondering if JSON should be included in this discussion. 

This is my first attempt at contributing to the Codecademy doc, and I've followed the Contribute walkthrough carefully.

**Comment by SimranLahrani842** [comment]
> I'm also making a note here that this entry will be populated with the methods for the storage objects like `setItem(key, value)`, `getItem(key)`, etc.

Ok mam please add claimed tag and assign me this.

**Comment by yangc95** [comment]
@vito588p Thanks for your interest! This issue is assigned to @SimranLahrani842. Separate term entries will be created of which you can definitely keep an eye out for.

When those term entry issues come up, for sure! You can include JSON data within the entry.

**Comment by SSwiniarski** [comment]
@SimranLahrani842 its been two weeks. Are you still working on this issue? Because there are a number of term entries waiting for this concept, if we don't hear from you in a few days, we'll need to unassign you so one of the maintainers can get this issue submitted quickly.

**Comment by SSwiniarski** [comment]
@SimranLahrani842 I'm going to unassign you so one of the maintainers can submit a PR for this issue.
