### ISSUE TITLE
[Term Entry] JavaScript Arrays: `.some()` method 

### ISSUE THREAD

**Issue by acerslee** [Codecademy/docs#2597]
### Reason/inspiration (optional)

I'm looking for an opportunity to break into contributing into an open-source project. I also want to contribute to the software engineering community with knowledge I feel that can be of use for someone.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Jaswilltech** [comment]
Hello, I am working GitHub Best Practices in Codecademy and building my portfolio, could I please have this issue assigned to me? 
Thanks,
Jasmin

**Comment by vivzzx** [comment]
Hello! I'm looking for my first opportunity to contribute to a project and the community. I'm also working on Github practices at Web Dev Path. So if you have a place for me, I'll be happy to help. ☺️

**Comment by KTom101** [comment]
@acerslee Was there a specific method we don't have yet that you wanted to add?

**Comment by acerslee** [comment]
@KTom101 yes the some array method
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some

**Comment by KTom101** [comment]
@acerslee Thanks for the clarification. Yes, you can add the `some()` method. 

If you haven't already, please check out the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) for additional information on contributing. See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail. After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by KTom101** [comment]
@Jaswilltech @vivzzx Thank you both for your interest. This issue has been assigned to the person who created it. Please take a look at the [issues tab](https://github.com/Codecademy/docs/issues) to see if there is another issue you want to work on.
