### ISSUE TITLE
[Entry] Subject: IDS using snort

### ISSUE THREAD

**Issue by SimranLahrani842** [Codecademy/docs#2599]
### Reason/inspiration (optional)

IDS its meaning and how it can be implemented using snort tool.
Detail step wise explaination will be given as I have implemented it myself.
I ll write ids.md file and put it in cc folder.
Was previously given in ugc GitHub but that's not included in ssoc.
Please assign me.

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by yangc95** [comment]
@SimranLahrani842 I've closed this issue as this issue doesn't follow Docs standards for an entry. If you'd like to take on an Issue, head over to the Issues tab for available one. Thanks!
