### ISSUE TITLE
[Edit] Subject: Typo in the Open Source Repository Docs

### ISSUE THREAD

**Issue by eshan-one** [Codecademy/docs#2603]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

Inside the Introduction to Open Source Course, there is a typo. 
- 
![Open Soruce Repo docs](https://github.com/Codecademy/docs/assets/108228113/77be15aa-2718-4ed0-9656-c88fa4106429)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by newkprime** [comment]
I am working on the Codecademy GitHub unit and would like to fix this issue. @eshan-one

**Comment by eshan-one** [comment]
Alright.. But I'm not a maintainer. I've claimed this issue but not sure how the maintainer will reply. Can you help with this?

**Comment by dakshdeepHERE** [comment]
@eshan-one if you've created this entry then you'll probably be assigned for this. But from next time don't forget to mention below that you've claimed it. Or what I do is if I'm about to create an issue I first solve the issue and keep my PR ready for the issue. After creating the issue I directly link my PR with the issue.

**Comment by eshan-one** [comment]
Alright. @dakshdeepHERE Thanks for the clarification! Will do the necessary next time

**Comment by eshan-one** [comment]
Happy to help! 😃
