### ISSUE TITLE
[Entry] Subject: Algorithm (Adding Kadane's algorithm)

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#2607]
### Reason/inspiration (optional)

I will add Kadane's algorithm in the Algorithm folder. Will add `kadane.md` in algorithm terms folder.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by KTom101** [comment]
@dakshdeepHERE I'm note sure if I'm familiar with Kaden's algorithm. Did you possibly mean Kadane's algorithm?

**Comment by dakshdeepHERE** [comment]
> @dakshdeepHERE I'm note sure if I'm familiar with Kaden's algorithm. Did you possibly mean Kadane's algorithm?

Yes correct sorry for the typo
