### ISSUE TITLE
[Term Entry] JavaScript Dates .setUTCSeconds()

### ISSUE THREAD

**Issue by codecademy-aditya** [Codecademy/docs#2620]
### Reason/inspiration (optional)

We would like a new term entry for JavaScript [Dates](https://www.codecademy.com/resources/docs/javascript/dates) about the `.setUTCSeconds()` method. The entry should go in a new file in `docs/content/javascript/concepts/dates/terms/setUTCSeconds/setUTCSeconds.md`

The entry should
    - Have an introductory paragraph about what the method is and does.
    - An example showing the method in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by GKerridge4** [comment]
@codecademy-aditya Hey, I am interested in taking on this issue. I'm hoping it can teach me more about javascript!

**Comment by DavidCs9** [comment]
Hello, I would like to address this issue. I'm learning a lot from your app, and I would like to contribute as well.

**Comment by KTom101** [comment]
@DavidCs9 Since @GKerridge4 asked first, I'm assigning this to them. Please look for another [unclaimed issue](https://github.com/Codecademy/docs/issues?page=1&q=is%3Aissue+is%3Aopen+no%3Aassignee) you would like to work on.

**Comment by KTom101** [comment]
@GKerridge4 You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our revamped [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by GKerridge4** [comment]
Hey, @KTom101 Thank you! 🎉 I'm really excited to get started on this. This is my first contribution to Codecademy Docs. I found out from doing the 'Learn Git & GitHub' course as I wanted more details so support with the Front-End Engineer career path.

**Comment by KTom101** [comment]
@GKerridge4 That's great! We'll be looking forward to your PR. 😁
