### ISSUE TITLE
[Term Entry] PHP Math Functions dechex()

### ISSUE THREAD

**Issue by codecademy-aditya** [Codecademy/docs#2622]
### Reason/inspiration (optional)

We would like a new term entry for [PHP](https://www.codecademy.com/resources/docs/php) about the `dechex()` function.

The entry should go in a new file in `docs/content/php/concepts/math-functions/terms/dechex/dechex.md`

The entry should 

- Have a syntax section illustrating the function with a ` ```pseudo ` code block. 
- An example showing the function in use with a ` ```php ` code block. 
- A runnable codebyte example in a ` ```codebyte/php` block. 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by brandon-kong** [comment]
I'd like to take on this feature!

**Comment by KTom101** [comment]
@brandon-kong Assigned

**Comment by SSwiniarski** [comment]
@brandon-kong It's been two weeks. Are you still working on this issue? Note that in another week this issue will be unassigned due to inactivity.

**Comment by brandon-kong** [comment]
Bumping this for maintainers
