### ISSUE TITLE
[Term Entry] Swift Arrays .isEmpty()

### ISSUE THREAD

**Issue by codecademy-aditya** [Codecademy/docs#2630]
### Reason/inspiration (optional)

We would like a new term entry for Swift [Arrays](https://www.codecademy.com/resources/docs/swift/arrays) about the .isEmpty() method. The entry should go in a new file in docs/content/swift/concepts/arrays/terms/isEmpty/isEmpty.md

The entry should
    - Have an introductory paragraph about what the method is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the method in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by noahtq** [comment]
Hello there!

I could make this Term Entry for Swift Arrays .isEmpty()

**Comment by KTom101** [comment]
@noahtq You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our revamped [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.
