### ISSUE TITLE
[Concept Entry] SwiftUI Navigation

### ISSUE THREAD

**Issue by codecademy-aditya** [Codecademy/docs#2634]
### Reason/inspiration (optional)

We would like a new concept entry for SwiftUI about Navigation. The entry should go in a new file in docs/content/swiftui/concepts/navigation/navigation.md

The entry should
    - Have an introductory paragraph about the concept.
    - Code blocks or codebytes displaying different aspects of the concept.
    - Internal linking as applicable.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by matthewogtong** [comment]
Hi! Can I be assigned this issue, please?

**Comment by KTom101** [comment]
@matthewogtong You're assigned 🎉

**Comment by SSwiniarski** [comment]
@matthewogtong It's been two weeks. Are you still working on this issue? Note that in another week this will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@matthewogtong I am unassigning you due to inactivity.

**Comment by EngOmarElsayed** [comment]
hey 👋 I want to take this issue and solve it.
