### ISSUE TITLE
[Term Entry] C# Array `.CopyTo()` 

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#2638]
### Reason/inspiration (optional)

We would like a new term entry for [C#](https://www.codecademy.com/resources/docs/c-sharp) about the `Array.CopyTo()` method.

The entry should go in a new file in `docs/content/c-sharp/concepts/arrays/terms/copyto/copyto.md`

The entry should

Have a syntax section illustrating the method with a ` ```pseudo ` code block.
An example showing the method in use with a ` ```cs ` code block.
A runnable codebyte example in a ` ```codebyte/csharp ` block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
Reposting this because I can't unlink the closed PR from the original issue.

**Comment by dakshdeepHERE** [comment]
claim

**Comment by SSwiniarski** [comment]
@dakshdeepHERE, you're assigned.

**Comment by dakshdeepHERE** [comment]
@SSwiniarski I had one doubt. When we are already linking example for code then adding codeblock isn't redundant also vice versa.

**Comment by SSwiniarski** [comment]
@dakshdeepHERE What do you mean "linking example for code"? We don't link out for examples, we place them in code blocks in the entry. I don't think I understand what you're asking.

**Comment by dakshdeepHERE** [comment]
> @dakshdeepHERE What do you mean "linking example for code"? We don't link out for examples, we place them in code blocks in the entry. I don't think I understand what you're asking.

Like let's take this PR as an example
<img width="226" alt="image" src="https://github.com/Codecademy/docs/assets/94860622/d31d7968-02c7-4f0d-8a5c-a3ceae2e0d43">
Here the code sample is given 
After this the codebyte is attached too
<img width="260" alt="image" src="https://github.com/Codecademy/docs/assets/94860622/dbcc8d7c-6278-4ae5-8b88-b0819776eaa2">
Both are same code then why don't we remove the example section and add only the codebyte?

**Comment by SSwiniarski** [comment]
@dakshdeepHERE that's the case. The example shouldn't be the same as the codebyte.

**Comment by dakshdeepHERE** [comment]
> @dakshdeepHERE that's the case. The example shouldn't be the same as the codebyte.

Exactly that's what I was thinking.
