### ISSUE TITLE
[Edit] PHP String Functions: explode(), strtolower(), substr()

### ISSUE THREAD

**Issue by cslylla** [Codecademy/docs#2640]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting, Add new content (definitions, codeblocks, etc.)

### Description (optional)

Edit the markdowns located inside these directories:

docs/content/php/concepts/string-functions/terms/explode/explode.md
docs/content/php/concepts/string-functions/terms/strtolower/strtolower.md
docs/content/php/concepts/string-functions/terms/substr/substr.md

Create a new "Example" section for each file with an example in a ```php block.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by cslylla** [comment]
I would like to work on this issue!

**Comment by KTom101** [comment]
@cslylla I've assigned you.
