### ISSUE TITLE
[Entry] Subject: <address> tag

### ISSUE THREAD

**Issue by CBID2** [Codecademy/docs#2641]
### Reason/inspiration (optional)

I recently learned about the `<address>` element through a blog post I recently published, and I think it would be a good idea to add it to the [Semantic HTML entry](https://www.codecademy.com/resources/docs/html/semantic-html) so that learners know a new way to implement contact information in the footer of their projects.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
@CBID2 did you also want to claim this issue?

**Comment by CBID2** [comment]
> @CBID2 did you also want to claim this issue?

Yes @SSwiniarski

**Comment by SSwiniarski** [comment]
@CBID2 You're assigned!

**Comment by CBID2** [comment]
> @CBID2 You're assigned!

Thanks @SSwiniarski
