### ISSUE TITLE
[Term Entry] JavaScript Array.prototype.toReversed()

### ISSUE THREAD

**Issue by codewithfan** [Codecademy/docs#2649]
### Reason/inspiration (optional)

Add the new ES2023 JavaScript array feature, .toReversed(). I would love to work on this issue!

Reference [Ecma TC39 Repo](https://github.com/tc39/proposal-change-array-by-copy) and [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toReversed).

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by codewithfan** [comment]
I would like to be assigned this issue and work on it.

**Comment by KTom101** [comment]
@codewithfan Thank you for making these new issues! I've assigned this one to you.

**Comment by codewithfan** [comment]
Update, still going to work on this issue :) super busy with work lately.

**Comment by KTom101** [comment]
@codewithfan Thanks! Appreciate the update.

**Comment by SSwiniarski** [comment]
@codewithfan It's been over three weeks since you were assigned this issue. Are you still working on it? Note that in another week it will be unassigned due to inactivity.

**Comment by codewithfan** [comment]
Yes! Will have a PR by Friday @SSwiniarski. Thank you for the reminder!

**Comment by SSwiniarski** [comment]
@codewithfan I'm giving you a couple more days to submit a PR.
