### ISSUE TITLE
[Term Entry] JavaScript Array.prototype.toSorted()

### ISSUE THREAD

**Issue by codewithfan** [Codecademy/docs#2650]
### Reason/inspiration (optional)

Add the new ES2023 JavaScript array feature, .toSorted(). Open for anyone to tackle this issue!

Reference [Ecma TC39 Repo](https://github.com/tc39/proposal-change-array-by-copy) and [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSorted).

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Nostromos** [comment]
I'd like to work on this!

**Comment by KTom101** [comment]
@Nostromos You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our revamped [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by Nostromos** [comment]
@KTom101 Thank you. I will review the revamped guide and will come back if I have questions or when I have a PR ready.

As for **your** question, this is my first contribution. I'm working on a bunch of courses/paths in codecademy and realized that I needed to relearn git. One of the later portfolio projects for "Learning Git & Github" is contributing to the docs.

**Comment by Nostromos** [comment]
@KTom101 @yangc95 Any way we can chat very quickly about this before I go any further? I have a ~basically~ fully written entry but it may dive a bit deeper than your average term entry. It won't be as general as the MDN one, but more applicable for the codecademy audience IMO.

I view the audience as learners, so they're going to see a method name and intuit how it should function. The tricky thing about this method is that it doesn't behave intuitively for things like arrays of numbers/integers or mixed arrays that include integers and numbers OR integers, numbers, and numbers as strings. 

As a result, I find myself wanting to include multiple examples of how to deal with what I view as the most common use cases:

- arrays of strings
- arrays of numbers
- mixed arrays

While also trying to ensure that the codebytes address all the examples. 

Should I submit a PR before we have this discussion or is it ok to address this stuff now? I'd just prefer not to do a bunch of work on examples and codebytes if it ends up getting cut for being too much for learners.

**Comment by KTom101** [comment]
@Nostromos For the `.toSorted()` method I recommended focusing on what `.toSorted()` does and how it differs from the [.sort()](https://www.codecademy.com/resources/docs/javascript/arrays/sort) method, and also where it's supported. The use cases you mentioned seems more fitting to have under `.sort()` instead.

However, if you already have this written, you can make a PR for it and we can review it.

**Comment by Nostromos** [comment]
@codewithfan PR here in case you're interested or have thoughts: https://github.com/Codecademy/docs/pull/2716
