### ISSUE TITLE
[Term Entry] JavaScript Array.prototype.toSpliced()

### ISSUE THREAD

**Issue by codewithfan** [Codecademy/docs#2651]
### Reason/inspiration (optional)

Add the new ES2023 JavaScript array feature, .toSpliced(). Open for anyone to tackle this issue!

Reference [Ecma TC39 Repo](https://github.com/tc39/proposal-change-array-by-copy) and [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSpliced).

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by brandon-kong** [comment]
I'd like to tackle this feature!

**Comment by KTom101** [comment]
@brandon-kong You're assigned 🎉

**Comment by SSwiniarski** [comment]
@brandon-kong It's been two weeks. Are you still working on this entry? Note that in another week this issue will be unassigned due to inactivity.

**Comment by brandon-kong** [comment]
> @brandon-kong It's been two weeks. Are you still working on this entry? Note that in another week this issue will be unassigned due to inactivity.

Still working on this entry! Expect it to be ready for review by the end of the day/tomorrow

**Comment by SSwiniarski** [comment]
@brandon-kong This is being unassigned due to inactivity.

**Comment by Armstrong2035** [comment]
Hello @SSwiniarski @KTom101

Can I take this on?

**Comment by SSwiniarski** [comment]
@Armstrong2035 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?
