### ISSUE TITLE
[Term Entry] JavaScript Array.prototype.with()

### ISSUE THREAD

**Issue by codewithfan** [Codecademy/docs#2652]
### Reason/inspiration (optional)

Add the new ES2023 JavaScript array feature .with(). Open for anyone to tackle this issue!

Reference [Ecma TC39 Repo](https://github.com/tc39/proposal-change-array-by-copy) and [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/with).

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by drewbie1234** [comment]
I will tackle the issue please.

This is the first real issue I'm tackling so apologies if I get the process wrong at any point

**Comment by codewithfan** [comment]
The maintainers will be able to assign you @drewbie1234

**Comment by yangc95** [comment]
Thanks @codewithfan!

@drewbie1234 You're assigned! You can check out the [Contribution Guide](<https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md>) for additional information on contributing.


See [Content Standards](<https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md>) for an overview of styling tips that the [Style Guide](<https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md>) covers in detail.


After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.


What brought you to Docs?

**Comment by SSwiniarski** [comment]
@drewbie1234, It's been two weeks. Are you still working on this issue? Note that in another week this issue will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@drewbie1234 This is being unassigned due to inactivity.

**Comment by Armstrong2035** [comment]
Hello @SSwiniarski @yangc95 I would like to take this on, please.

**Comment by SSwiniarski** [comment]
@Armstrong2035 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment]
@Armstrong2035 Note that we generally limit users to claiming three open issues at one time. Wait until after you've summitted a PR on the issues you've already claimed before claiming any new issues.

**Comment by Armstrong2035** [comment]
@SSwiniarski This is my first time contributing. I found this repo through an email from codecademy

**Comment by Armstrong2035** [comment]
Hello, @SSwiniarski 

Thank you for assigning this to me. 

I did a pull request, and all checks have been passed. 

Please, what next should I do?

**Comment by SSwiniarski** [comment]
> Hello, @SSwiniarski
> 
> Thank you for assigning this to me.
> 
> I did a pull request, and all checks have been passed.
> 
> Please, what next should I do?

@Armstrong2035 wait for a maintainer review and resolve any comments they have on your submission.
