### ISSUE TITLE
[Entry] Subject: Minimax algorithm in ai

### ISSUE THREAD

**Issue by SimranLahrani842** [Codecademy/docs#2654]
### Reason/inspiration (optional)

Minimax is a kind of backtracking algorithm that is used in decision making and game theory to find the optimal move for a player, assuming that your opponent also plays optimally. It is widely used in two player turn-based games such as Tic-Tac-Toe, Backgammon, Mancala, Chess, etc.
In Minimax the two players are called maximizer and minimizer. The maximizer tries to get the highest score possible while the minimizer tries to do the opposite and get the lowest score possible.

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Sancerro** [comment]
I'm interested in this issue. Currently a sophomore in college studying AI and data engineering. It will be my first issue though

**Comment by KTom101** [comment]
@SimranLahrani842 Were you working on this issue. If not, I will assign this to @Sancerro

**Comment by KTom101** [comment]
@Sancerro Let's give @SimranLahrani842 a chance to answer first before I assign you. Thank you for your patience.

**Comment by Sancerro** [comment]
Of course, I'll be waiting for it.

**Comment by KTom101** [comment]
@Sancerro Since there hasn't been a response, I can assign this to you if you still want it.

**Comment by Kadif-Ravik** [comment]
I'd like to be assigned

**Comment by WernerGomindes** [comment]
I am a software developer @WernerGomindes wanting to get this issue.

**Comment by SSwiniarski** [comment]
@WernerGomindes sorry for the delay, I am assigning this issue to you if you still want it.

**Comment by SSwiniarski** [comment]
@WernerGomindes it's been two weeks. Are you working on this issue? In another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@WernerGomindes this is being unassigned due to inactivity.

**Comment by arirays** [comment]
Hi, I'd like to write this entry!

**Comment by SSwiniarski** [comment]
@arirays, you're assigned.
