### ISSUE TITLE
[Term Entry] JavaScript Array.prototype.some()

### ISSUE THREAD

**Issue by codewithfan** [Codecademy/docs#2658]
### Reason/inspiration (optional)

Conversating about codewars problems with a colleague, they had to use the .some() method. I checked to see if the Docs had it, and I feel it's good to know! One may use this on their coding journey. 

**I would love to tackle this one.**

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by eskuode** [comment]
I would love to tackle this one.

**Comment by Elimodo** [comment]
hello codewithfan I would like to try out this problem. please assign. Thanks.

**Comment by prakhar3062** [comment]
@codewithfan  i would like to contribute

**Comment by SSwiniarski** [comment]
@Elimodo, You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment]
@prakhar3062 Issues are generally assigned as first-come, first-served. There are plenty of other unclaimed issues for you to choose.

**Comment by SSwiniarski** [comment]
Closing this as it duplicated an earlier issue.
