### ISSUE TITLE
[Term Entry] JavaScript Array.prototype.every()

### ISSUE THREAD

**Issue by codewithfan** [Codecademy/docs#2659]
### Reason/inspiration (optional)

Since creating Issue #2658, why not add another array method that tests for all elements instead of some? 

I would love to work on this one! 💯  

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by tomkin-heart** [comment]
Hello @codewithfan :) I'd like to try to work on that issue. 
I found out about Docs through Codecademy.

**Comment by yangc95** [comment]
@tomkin-heart You're assigned! You can check out the [Contribution Guide](<https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md>) for additional information on contributing.


See [Content Standards](<https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md>) for an overview of styling tips that the [Style Guide](<https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md>) covers in detail.


After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by tomkin-heart** [comment]
hello @yangc95, do i understand right, that i have to add a documentation about JavaScript Array.prototype.every() to Codecademy/docs/content/javascript/concepts/terms ?
Cause in all helps and links i don't find the project itself. Should i create it myself? Shell i make it similar like in all other javascript array methods in docs?

**Comment by codewithfan** [comment]
Hi @tomkin-heart, 

To answer your first question, yes to the file location. You will have the opportunity to create a new markdown file for the array method. Templates can be found in the documentation folder. 

I reference the other methods just in case my formatting is correct 👍🏾 .

**Comment by tomkin-heart** [comment]
<img width="1440" alt="Screenshot 2023-07-11 at 18 47 24" src="https://github.com/Codecademy/docs/assets/121643652/0eb598f1-743e-4a76-ab61-760693c9185c">

Hi, i've made a PR yesterday and i doubt if i made it right.. here's what i see, can you help please?
