### ISSUE TITLE
[Term Entry] JavaScript Array.prototype.at()

### ISSUE THREAD

**Issue by codewithfan** [Codecademy/docs#2660]
### Reason/inspiration (optional)

An array method that has a purpose and place in the Docs. Allows firs time contributors to dive into the web and learn a new method to tack onto their tool belt.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by sumitdethe27** [comment]
I want to work on this issue.

**Comment by KTom101** [comment]
@sumitdethe27 You're assigned

**Comment by sumitdethe27** [comment]
@KTom101 thankyou

**Comment by SSwiniarski** [comment]
@sumitdethe27 It's been two weeks. Are you still working on this issue? Note that in another week this issue will be unassigned due to inactivity.

**Comment by sumitdethe27** [comment]
@SSwiniarski sorry for the delay, will give a pr asap.

**Comment by lloan** [comment]
Can the `claimed` label be added to avoid confusion? I personally thought this was still up for grabs.

**Comment by SSwiniarski** [comment]
@lloan sorry, that was an oversight.
