### ISSUE TITLE
[Entry] Subject: Text-align Center 

### ISSUE THREAD

**Issue by CBID2** [Codecademy/docs#2678]
### Reason/inspiration (optional)

Hi there! I just wanted to let you know that `<center>` has been  [depreciated ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center), so here’s a solution to this issue:

1. Remove this [entry](https://www.codecademy.com/resources/docs/html/elements/center)
2. I will create a new entry on text-align center in the CSS section.

Doing this will ensure that students are provided with the correct information.

### Entry Type (select all that apply)

New Topic Entry, New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by lydia274** [comment]
Hi Christine, I hope you are well! I would love to work on this issue, could you please assign it to me? Thank you!

**Comment by CBID2** [comment]
> Hi Christine, I hope you are well! I would love to work on this issue, could you please assign it to me? Thank you!

Hi @lydia274! :) I'm doing wonderful! :) I can't assign it to you because I'm not a maintainer. I also volunteered to work on this entry. How about I tag your name so you can review it once I create the pull request? :)

**Comment by KTom101** [comment]
@CBID2  We already have an entry for `text-align` in CSS here: https://www.codecademy.com/resources/docs/css/typography/text-align

Also, it is noted in the body paragraph that `<center>` is deprecated, and `text-align` is linked out as an alternative.

**Comment by KTom101** [comment]
@lydia274 Please take a look to see if there is another [unclaimed issue](https://github.com/Codecademy/docs/issues?page=1&q=is%3Aissue+is%3Aopen+no%3Aassignee) you want to work on. If there is nothing right now you wish to work on, please check back regularly. We are always adding new issues.

**Comment by KTom101** [comment]
@CBID2 I'm closing this out since we have this already.

**Comment by CBID2** [comment]
Ok thanks @KTom101.
