### ISSUE TITLE
[Concept Entry] SwiftUI Layouts

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2681]
### Reason/inspiration (optional)

We would like a new concept entry for SwiftUI about Layouts. The entry should go in a new file in docs/content/swiftui/concepts/layouts/layouts.md

The entry should
    - Have an introductory paragraph about the concept.
    - Code blocks or codebytes displaying different aspects of the concept.
    - Internal linking as applicable.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by gracekishino** [comment]
@codecademy-docs I think this is a duplicate issue? I'm currently working on the same concept entry for #2102

**Comment by SSwiniarski** [comment]
This is a duplicate. I'm closing it.
