### ISSUE TITLE
[Concept Entry] SwiftUI Buttons

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2684]
### Reason/inspiration (optional)

We would like a new concept entry for SwiftUI about Buttons. The entry should go in a new file in docs/content/swiftui/concepts/buttons/buttons.md

The entry should
    - Have an introductory paragraph about the concept.
    - Code blocks or codebytes displaying different aspects of the concept.
    - Internal linking as applicable.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by kevveth** [comment]
@codecademy-docs I am interested in taking on this issue.

**Comment by KTom101** [comment]
@kevveth You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our revamped [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by kevveth** [comment]
@KTom101 This is my first time contributing, and I'm looking forward it. I am currently studying Swift through Codecademy's offered course and I've reached the Git & Github for iOS development section. I'm currently working on a project that asks of me to create an entry for Codecademy docs.

**Comment by thinknotes** [comment]
I am also in the same situation as @kevveth i.e. I am studying Swift through Codecademy and working on a project that requires me to enter the docs. Since all the issues have been assigned already, what are my options?  Should I wait for a new entry or can I pick an issue which has been assigned to somebody else? Thank You

**Comment by KTom101** [comment]
@thinknotes We add new issues every week. Check back regularly. The issue must be [unclaimed](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee) for you to be assigned. We assign on a first-come-first-serve basis.

You could also open up an issue for something you want to work on but don't currently see in Codecademy Docs. Just mention in the description or in a comment you would like the issue to be assigned to yourself. A maintainer (with the collaborator badge) will review your issue and make sure it's alright before assigning it to you.
