### ISSUE TITLE
[Term Entry] Cybersecurity Malware adware

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2686]
### Reason/inspiration (optional)

We would like a new term entry for [Cybersecurity](https://www.codecademy.com/resources/docs/cybersecurity) about adware.

The entry should go in a new file in `docs/content/cybersecurity/concepts/malware/terms/adware/adware.md`

The entry should: 

- Explain what adware is.
- Explain why it's harmful.
- Explain how it infects a PC, and how to prevent it.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by arisdelacruz** [comment]
hello, good day

Can I work on this one?

thanks

**Comment by KTom101** [comment]
@arisdelacruz You're assigned 🎉

**Comment by arisdelacruz** [comment]
@KTom101 

Thank you

**Comment by arisdelacruz** [comment]
@KTom101 

just created a pull request

thanks
