### ISSUE TITLE
[Term Entry] Cybersecurity Malware trojan

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2688]
### Reason/inspiration (optional)

We would like a new term entry for [Cybersecurity](https://www.codecademy.com/resources/docs/cybersecurity) about trojans.

The entry should go in a new file in `docs/content/cybersecurity/concepts/malware/terms/trojan/trojan.md`

The entry should: 

- Explain what a trojan is.
- Explain why it's harmful.
- Explain how it infects a PC, and how to prevent it.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by KTom101** [comment]
@csrordzhn You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our revamped [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by csrordzhn** [comment]
Hi, this will be my first contribution to Codecademy Docs. It is part of my assignment on the iOS Developer Path in Codecademy.

**Comment by CBID2** [comment]
I'd like to work on this @SSwiniarski

**Comment by SSwiniarski** [comment]
@CBID2 You're assigned!
