### ISSUE TITLE
[Term Entry] Cybersecurity Malware keylogger

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2689]
### Reason/inspiration (optional)

We would like a new term entry for [Cybersecurity](https://www.codecademy.com/resources/docs/cybersecurity) about keyloggers.

The entry should go in a new file in `docs/content/cybersecurity/concepts/malware/terms/keylogger/keylogger.md`

The entry should: 

- Explain what a keylogger is.
- Explain why it's harmful.
- Explain how it can be placed on a system.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by SriSha21** [comment]
can I please be assigned this issue?
