### ISSUE TITLE
[Term Entry] Cybersecurity Malware rootkit

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2690]
### Reason/inspiration (optional)

We would like a new term entry for [Cybersecurity](https://www.codecademy.com/resources/docs/cybersecurity) about rootkits.

The entry should go in a new file in `docs/content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md`

The entry should: 

- Explain what a rootkit is.
- Explain why it's harmful.
- Explain how it can be placed on a system.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by frhadjmli** [comment]
Hey there, I'm interested in taking this issue on.

**Comment by KTom101** [comment]
@frhadjmli You're assigned

**Comment by frhadjmli** [comment]
@KTom101 Just one more thing is this path correct ? 
- `docs/content/cybersecurity/concepts/malware/terms/trojan/trojan.md` 
shouldn't it be like : 
- `docs/content/cybersecurity/concepts/malware/terms/rootkit/rootkit.md`
