### ISSUE TITLE
[Term Entry] Cybersecurity Cyber-Attack Cross-Site Scripting

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2691]
### Reason/inspiration (optional)

We would like a new term entry for [Cybersecurity](https://www.codecademy.com/resources/docs/cybersecurity) about Cross-Site Scripting (XSS).

The entry should go in a new file in `docs/content/cybersecurity/concepts/cyber-attack/terms/cross-site-scripting/cross-site-scripting.md`

The entry should: 

- Explain what cross-site scripting is is.
- Explain why it's harmful.
- Explain how it can be protected against.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by ariana124** [comment]
Hello, I'd like to work on this issue.

**Comment by KTom101** [comment]
@ariana124 You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

**Comment by YounosN** [comment]
I want to work on this issue, as I have been configuring and deploying IPSes (Intrusion Prevention Systems) fields for many years.
