### ISSUE TITLE
[Term Entry] Cybersecurity Cyber-Attack Supply Chain Attack

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2692]
### Reason/inspiration (optional)

We would like a new term entry for [Cybersecurity](https://www.codecademy.com/resources/docs/cybersecurity) about Supply Chain Attacks.

The entry should go in a new file in `docs/content/cybersecurity/concepts/cyber-attack/terms/supply-chain-attack/supply-chain-attack.md`

The entry should: 

- Explain what a supply chain attack is.
- Explain why it's harmful.
- Explain how it can be protected against.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by SUSHIBUN** [comment]
I'm in the process of the course "Learn Git & GitHub", I'm working on the project "Codecademy Entry" now. Can I be assigened this issue?

**Comment by SSwiniarski** [comment]
@SUSHIBUN You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SUSHIBUN** [comment]
I meet the "Error in user YAML: (<unknown>): did not find expected key while parsing a block mapping at line 1 column 1" in .md file, when I open it on github. The file is
[supply-chain-attack.md](https://github.com/Codecademy/docs/files/11991412/supply-chain-attack.md)
Can someone help me figure it out please?

**Comment by SSwiniarski** [comment]
@SUSHIBUN It's the apostrophes in your description.
