### ISSUE TITLE
[Term Entry] JavaScript Storage .setItem(key, value)

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2693]
### Reason/inspiration (optional)

We would like a new term entry for JavaScript [Storage](https://www.codecademy.com/resources/docs/javascript/storage) about the .setItem() method. The entry should go in a new file in docs/content/javascript/concepts/storage/terms/setItem.md

The entry should
    - Have an introductory paragraph about what the method is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the method in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Manikanta528** [comment]
@codecademy-docs i can work on this term entry. Assign me

**Comment by KTom101** [comment]
@Manikanta528 You're assigned

**Comment by Manikanta528** [comment]
@KTom101 The Storage concept entry hasn't been made yet #2593 
Should I wait for that or go ahead with this term entry?

**Comment by KTom101** [comment]
@Manikanta528 That's a great question! It's alright to create the term entry in the meantime. We will just wait for the concept entry to be finished first before merging this.

**Comment by Manikanta528** [comment]
Okay
