### ISSUE TITLE
[Term Entry] AI Linear Activation Function

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#2700]
### Reason/inspiration (optional)

(Repost since closed PR can't be unlinked from prior issue)

We would like a new concept entry for the Linear Activation Function

The entry should go in a new file in `docs/content/ai/concepts/neural-networks/terms/linear-activation-function/linear-activation-function.md`

The entry should

- Describe what the linear activation function is.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by dakshdeepHERE** [comment]
claim

**Comment by SSwiniarski** [comment]
@dakshdeepHERE, You're assigned!

**Comment by dakshdeepHERE** [comment]
@SSwiniarski I have a pending PR which is waiting for the second review, the first one is completed by @KTom101 [LINK](https://github.com/Codecademy/docs/pull/2635)

**Comment by SSwiniarski** [comment]
@dakshdeepHERE It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by dakshdeepHERE** [comment]
Yes @SSwiniarski I started working on it but it's on halt due to my college reports and my portfolio development. Don't worry I will finish it under a week. Most of the work is already done.

**Comment by SSwiniarski** [comment]
@dakshdeepHERE It's been another week. Do you have a PR? I'm giving you a few more days.

**Comment by dakshdeepHERE** [comment]
> * linear activation function

almost done will push the PR by Friday

**Comment by SSwiniarski** [comment]
@dakshdeepHERE I am unassigning this due to inactivity.

**Comment by shanmukha-m-k** [comment]
Hi sir , I would like to be assigned this task

**Comment by SSwiniarski** [comment]
@shanmukha-m-k You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?
