### ISSUE TITLE
Python entry needed: Files

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#273]
One new Python entry about the topic Files.

**Comment by Tawishi** [comment]
I would like to take up this issue @sonnynomnom

**Comment by sonnynomnom** [comment]
Hi @Tawishi I think I just assigned you another issue!

**Comment by Tawishi** [comment]
> Hi @Tawishi I think I just assigned you another issue!

I have raised a PR for the previously assigned issue. Can I take up this issue now?

**Comment by FriskySaga** [comment]
Mind if I tackle on this issue?

**Comment by shiningflutes** [comment]
Would like to take this issue!

**Comment by sonnynomnom** [comment]
@shiningflutes all you! thanks!

**Comment by sonnynomnom** [comment]
@Tawishi sorry! giving it to a new contributor

**Comment by Dusch4593** [comment]
Hi @shiningflutes! Brandon from the Free Team 😄 Just wanted to check in and ask if you were still working on a PR for this issue?

**Comment by shiningflutes** [comment]
hi @Dusch4593 , yes am still interested! Will be sending in soon, was busy with work sorry

**Comment by Dusch4593** [comment]
> hi @Dusch4593 , yes am still interested! Will be sending in soon, was busy with work sorry

No worries, take your time! Many thanks! 🙏

**Comment by shiningflutes** [comment]
> > hi @Dusch4593 , yes am still interested! Will be sending in soon, was busy with work sorry
> 
> No worries, take your time! Many thanks! 🙏

Thank you! Will be uploading soon - doing some finishing touches!
