### ISSUE TITLE
[Term Entry] JavaScript Dates .toUTCString()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2749]
### Reason/inspiration (optional)

We would like a new term entry for JavaScript [Dates](https://www.codecademy.com/resources/docs/javascript/dates) about the `.toUTCString()` method. The entry should go in a new file in `docs/content/javascript/concepts/dates/terms/toUTCString/toUTCString.md`

The entry should:

    - Have an introductory paragraph about what the method is and does.
    - An example showing the method in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by raghuwar-jangir** [comment]
I am interested in taking this issue on.

**Comment by KTom101** [comment]
@raghuwar-jangir You're officially assigned, now. Please make the changes I mentioned in the PR.

Also, how did you find out about contributing to the Docs repository?

**Comment by SSwiniarski** [comment]
@raghuwar-jangir because of inactivity on your PR I am unassigning this issue so someone else can work on it.

**Comment by ekoulemaneng** [comment]
@SSwiniarski @KTom101  I'm a new contributor and I'd like to be assigned the task of solving this issue.

**Comment by KTom101** [comment]
@ekoulemaneng You're assigned. If you haven't already, please take a look at the documentation linked in the description and the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).

You've said you're a new contributor, where is it that you found out about contributing to Codecademy Docs?

**Comment by ekoulemaneng** [comment]
@KTom101 I'm a Codecademy learner and I'm studying Git & Github curriculum.
