### ISSUE TITLE
Python String methods needed: .find() and .format()

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#275]
**Note**: _Before creating a new issue, please ensure that a similar issue hasn't already been posted in the ["Issues" tab](https://github.com/Codecademy/docs/issues)._

## Description

Python string methods:

- `.find()`
- `.format()`

They will live here: https://www.codecademy.com/resources/docs/python/strings (Scroll down)

## Type of Issue(s)

- [x] One or more new entries/terms requested.
- [ ] Typo and/or bug within one or more existing entries.
- [ ] Unclear definition/explanation of term(s).
- [ ] Out-of-date information (new release, deprecated package, etc.).
- [ ] Recommend change(s) to documentation (such as existing text or new text)

## Type of Recommended Change(s)

- [x] Adding between one and three new entries (max 3 per pull request)
- [ ] Editing one or more existing entries (fixing a typo, bug, issues, etc)
- [ ] Updating the documentation

## Checklist

- [x] A similar issue hasn't already been created.
- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.

**Comment by wanjuntham** [comment]
Hi @sonnynomnom , may I take this?

**Comment by sonnynomnom** [comment]
@wanjuntham absolutely!

**Comment by wanjuntham** [comment]
@sonnynomnom Could you or your team help to review #367 ?
