### ISSUE TITLE
[Concept Entry] C# Inheritance

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2759]
### Reason/inspiration (optional)

We would like a new term entry for [C#](https://www.codecademy.com/resources/docs/c-sharp) about Inheritance.

The entry should go in a new file in `docs/content/c-sharp/concepts/inheritance/inheritance.md`

The entry should 

- Explain what inheritance is and how it is used.
- Explain the syntax for inheriting classes.
- Explain the difference between private and protected modifiers.
- Provide a code example of inheritance.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Rastecov** [comment]
Hi Codecademy, I can do that.

**Comment by SSwiniarski** [comment]
@Rastecov You're assigned, but in the future wait until a maintainer officially assigns you to an issue before submitting a PR.

**Comment by Rastecov** [comment]
> @Rastecov You're assigned, but in the future wait until a maintainer officially assigns you to an issue before submitting a PR.

Ok Thank you
