### ISSUE TITLE
[Concept Entry] C# Interfaces

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2760]
### Reason/inspiration (optional)

We would like a new term entry for [C#](https://www.codecademy.com/resources/docs/c-sharp) about Interfaces.

The entry should go in a new file in `docs/content/c-sharp/concepts/interfaces/interfaces.md`

The entry should 

- Explain what a interface is and how it is used.
- Explain the syntax for creating a interface and implementing an interface.
- Provide an example of an interface in use..

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by mrrahulkaran** [comment]
I am interested taking this issue

**Comment by tanciu** [comment]
i would like to try

**Comment by KTom101** [comment]
@mrrahulkaran You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by KTom101** [comment]
@tanciu Since @mrrahulkaran asked first, they have been assigned. Please look for another [unclaimed issue](https://github.com/Codecademy/docs/issues?page=1&q=is%3Aissue+is%3Aopen+no%3Aassignee) to be assigned to. Or check back for new issues if nothing else interests you. We add new issues every week. 🙂

**Comment by SSwiniarski** [comment]
@mrrahulkaran It's been two weeks. Are you still working on this issue? Note that in another week this will be unassigned due to inactivity.

**Comment by tanciu** [comment]
Hi , unfortunately I quit due to my schedule. Thank you.

În dum., 30 iul. 2023 la 9:41 a.m. SSwiniarski ***@***.***> a
scris:

**Comment by SSwiniarski** [comment]
@tanciu I'm sorry to hear that, but you were never assigned this issue.

**Comment by Ivan-Tulcan** [comment]
Hello! I know this issue has been already assigned to other contributor but I would also like to do it.

**Comment by SSwiniarski** [comment]
@mrrahulkaran I am unassigning you due to inactivity.

**Comment by SSwiniarski** [comment]
@Ivan-Tulcan You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@Ivan-Tulcan I am unassigning this due to inactivity.

**Comment by manviii27** [comment]
@SSwiniarski Can I be assigned to this issue? I'd like to work on it.

**Comment by SSwiniarski** [comment]
@manviii27 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!
