### ISSUE TITLE
[Entry Request] What is an Object?

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#277]
## Description

Create a "What is an Object?" entry in the General section.

General section: https://www.codecademy.com/resources/docs/general

## Type of Entry Request

- One or more new entries/terms requested.

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by pavankalyan-codes** [comment]
Hey I can work on this. Pls assign this to me.

**Comment by sonnynomnom** [comment]
done!

**Comment by sonnynomnom** [comment]
How did you find this by the way?

**Comment by pavankalyan-codes** [comment]
Found it while sorting with hacktoberfest label

**Comment by sonnynomnom** [comment]
Nice @pavankalyan-codes, looking forward! Each PR will get two reviews from the team. 

Remember, we want it to be detailed and high-quality! Best of luck!
