### ISSUE TITLE
[Bug/Error] Subject: Typo in the CODE OF CONDUCT

### ISSUE THREAD

**Issue by droffilc1** [Codecademy/docs#2775]
### Actual Behavior

There is a type error in the code of conduct

### Expected Behavior

For the typo to be fixed

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by hitesh-gitdev** [comment]
Hi, I'm Hitesh and currently finishing up a refresher course on Git and GitHub. I would like to work on this issue. My guess is the word "Plagerism" is what needs to be fixed?

**Comment by hitesh-gitdev** [comment]
Ah, no worries! I'll pick up another issue then. Thanks @SSwiniarski!
