### ISSUE TITLE
[Edit] JavaScript promises: Async-await

### ISSUE THREAD

**Issue by acerslee** [Codecademy/docs#2786]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Like callbacks and promise chaining, async-await is another method where we can make asynchronous calls to make promises.

We want to include this method as part of the promises, where it can be easier for some users to understand.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by tiseysoft** [comment]
Hi Alex, I would like to be assigned this task.

**Comment by KTom101** [comment]
@acerslee Thank you for opening this issue. Were you looking to add this as a section within the current [Promise](https://www.codecademy.com/resources/docs/javascript/promise) entry? Also were you planning on working on this yourself?

**Comment by acerslee** [comment]
@KTom101 yes to both

**Comment by SSwiniarski** [comment]
@acerslee I've officially assigned you this issue. @tiseysoft, there are many other open issues that are open to being claimed. Generally with user-submitted issues, the user who submitted it generally gets first crack at it.
