### ISSUE TITLE
[Entry Request] `git diff` command

### ISSUE THREAD

**Issue by namendjo** [Codecademy/docs#2793]
### Reason/inspiration (optional)

Hello CC team,

As part of the course [learn-git-and-github](https://www.codecademy.com/learn/learn-git), I'd like to create a new entry for the `git diff` command since it seems to be unavailable on this [page](https://www.codecademy.com/resources/docs/git).

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by LewisMK** [comment]
@namendjo I would like to contribute to this issue.

**Comment by namendjo** [comment]
Hey @LewisMK, 2 options for you:

(1) I will make a first version. Once validated and published, you could have a look on it and see what you can add.
(2) There are a bunch of other commands that are not yet referenced in codecademy-docs. You can work on one of them.

**Comment by SSwiniarski** [comment]
@namendjo Two things:

1) Maintainers generally assign issues.
2) If you want to be assigned an issue you've submitted, please state so in the description or in a comment.

I'm assigning you officially, but please bear those points in mind, because open issues are fair game to be claimed whoever submits them.

**Comment by namendjo** [comment]
Thanks @SSwiniarski. I should have emphasized from the start that I wanted to be assigned on it.

**Comment by LewisMK** [comment]
@namendjo sorry, I thought you were the maintainer for this issue.
