### ISSUE TITLE
[Entry Request] What is UUID?

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#280]
## Description

Write a "What is UUID?" (universally unique identifier) entry in the General topic.

General topic: https://www.codecademy.com/resources/docs/general

## Type of Entry Request

- One or more new entries/terms requested.

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by jason1985** [comment]
Hi may I work on this?
Thanks

**Comment by sonnynomnom** [comment]
Hi Jason, absolutely! 

May I ask how you found this Issue?

**Comment by jason1985** [comment]
Thank you.
I found this issue by going to `github.com/issues` and searching `is:open is:issue label:hacktoberfest`.

**Comment by sonnynomnom** [comment]
Awesome @jason1985! Looking forward.

Each PR will get two reviews from the team. We are looking for high-quality writing so please take a look at our README and Contribution Guide. Best of luck!
