### ISSUE TITLE
[Entry Request] General: Routing

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#281]
## Description

Write a "Routing" entry in the General topic.

General topic: https://www.codecademy.com/resources/docs/general

## Type of Entry Request

- One or more new entries/terms requested.

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by parth93QA** [comment]
Can I work on this ?

**Comment by sonnynomnom** [comment]
Hi @parth93QA, absolutely!

May I ask how you found this issue/repo?

**Comment by parth93QA** [comment]
Hi I was searching for some cheatsheets online for nodejs that's when I found your resources page  and then found your open issues during hacktober fest

**Comment by sonnynomnom** [comment]
Amazing!

**Comment by Dusch4593** [comment]
Re-opened for anyone who'd like to make a PR for this issue!

**Comment by SSwiniarski** [comment]
@Dusch4593, I'll take this one over.
