### ISSUE TITLE
[Entry Request] General: QR Code

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#282]
## Description

Write a "QR Code" entry in the General topic.

General topic: https://www.codecademy.com/resources/docs/general

## Type of Entry Request

- One or more new entries/terms requested.

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by Punit-Choudhary** [comment]
Hey @sonnynomnom,

I would love to contribute to Codecademy.
Could you please assign this issue to me 🙂 

Thanks

**Comment by sonnynomnom** [comment]
@Punit-Choudhary Hi Punit, all you!

How did you find us by the way?

**Comment by Punit-Choudhary** [comment]
I saw Codecademy's [post on Linkedin](https://www.linkedin.com/posts/codecademy_docs-is-a-new-resource-for-community-driven-activity-6850882670755377153-MozO)
I am student at Codecademy and Chapter Leader of [Rajasthani Geeks](https://community.codecademy.com/rajasthani-geeks/)
Thank you for giving me this opportunity 💜

**Comment by sonnynomnom** [comment]
Oh wow, nice!

Yeah, take a jab at it. Make sure to read through the README file and the Contribution Guide thoroughly. And remember, it's about quality, not quantity!

**Comment by Punit-Choudhary** [comment]
Hello 👋 

Can I include Images or gifs to elaborate content?

Thanks

**Comment by sonnynomnom** [comment]
Absolutely! Take a look at the contribution guide to see where to add the images.

**Comment by Punit-Choudhary** [comment]
Hey, Is there any word limit?

**Comment by sonnynomnom** [comment]
500-1000 is perfect

**Comment by Dusch4593** [comment]
Hi @Punit-Choudhary! Brandon from the Free Team 😄 Just wanted to check in and ask if you were still working on a PR for this issue?

**Comment by Punit-Choudhary** [comment]
Hey, @Dusch4593 I am sorry for the delay.
I was stuck between my Semester Exams, I am almost done with the issue, need to check for grammatical mistakes.
Thanks

**Comment by Dusch4593** [comment]
Hi @Punit-Choudhary! Brandon from the Free Team 😄 Just checking in to see if you were still working on this issue?

**Comment by ethan-master-coding** [comment]
@Dusch4593 No reply in a month. Can I be assigned?

**Comment by Punit-Choudhary** [comment]
Hey, I am sorry I completely forgot about this. I would make a pull request by Wednesday for sure.

**Comment by Punit-Choudhary** [comment]
Hey @Dusch4593, I need a suggestion.
Should I include code to generate QR in Python or Javascript using **third-party** packages?
Thank you

**Comment by ethan-master-coding** [comment]
@Punit-Choudhary As long as it's free, safe, and trusted the answer is probably yes. In the [IDE entry](https://www.codecademy.com/resources/docs/general/ide) it as links to IDEs other than CC workspaces.

**Comment by Dusch4593** [comment]
@ethan-master-coding @Punit-Choudhary

I think that we should refrain from using language-specific code snippets in General entries whenever possible. However, we should definitely link out to QR-related tools that are reputable, safe, and accessible (preferably free 😄).

**Comment by Dusch4593** [comment]
Hey @Punit-Choudhary just checking in to see how things are going with the PR for this issue? If you have any questions, let me know 😄

**Comment by Dusch4593** [comment]
Hey @Punit-Choudhary , hope all is well! 😄 Since [there hasn't been much activity on this issue/PR](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md#:~:text=PRs%20will%20be%20marked%20as%20invalid%20if%20there%20is%20no%20consistent%20activity%20within%20a%202%2Dweek%20period%20on%20the%20contributor%27s%20part%20and%20content%20does%20not%20meet%20or%20pass%20standard%20formatting%2C%20quality%2C%20and%20plagiarism%20checks.) as of late, I'm going to unassign you and re-open this issue. If you'd still like to work on this one, please ask to be reassigned if nobody else has yet claimed it. Otherwise, feel free to check out [the rest of the "Issues" tab](https://github.com/Codecademy/docs/issues) (we've been adding some in recent weeks and intend to add more).

**Comment by Dusch4593** [comment]
Hi @HajarJuhari! 👋🏻 I'd be happy to assign you! 😄

> Also, if I am to understand this request, is the entry is the same as an introductory article for QR codes?

This entry wouldn't necessarily have the same length or structure as an article. For this particular entry, I think it should be structured in a way that answers a few of the following questions:

- What is a QR code and what are they used for?
- What do they look like?
- What are some common use cases for QR codes?

**Comment by mpicozza** [comment]
Hey @Dusch4593 I am looking for an issue for a portfolio project in my Codecademy course. With years of real life experience integrating QR codes into aspects of my small business, I'm confident I can cover the necessary information effectively. Figure this could be an issue worth requesting. Thanks!

**Comment by Dusch4593** [comment]
Hi @mpicozza! Thank you for your interest in contributing to Codecademy Docs! 🎉 

I've assigned this issue to you 😄 🦞

**Comment by yangc95** [comment]
Hi @mpicozza, thanks for your interest! The issue, however, is currently assigned to @HajarJuhari.

The exception is that the contributor is unable to complete the issue according to standards. We will give a few more days before considering reassignment.

In the meantime, feel free to browse an unassigned issues and thank you for your interest in Docs!

**Comment by HajarJuhari** [comment]
@SSwiniarski Hi. I'm still working on it. Can you give me time till 2 December? Been working on other Codecademy courses for a while.

**Comment by easoftwareGit** [comment]
I would like to contribute to this issue. 
Can you please add me?

**Comment by SSwiniarski** [comment]
@easoftwareGit, we still have @HajarJuhari assigned.

@HajarJuhari, are you still working on this?

**Comment by HajarJuhari** [comment]
Hi @SSwiniarski, I'm sorry but I'm running into a lot of problems lately. I don't think I can finish in the near time. To ensure things move along quicker, I think it's better to assign this issue to @easoftwareGit. 

I sincerely apologize for the inconvenience.  

Hopefully, one day I can contribute when things settled down.

**Comment by easoftwareGit** [comment]
Thanks for assigning me a task.

This is my first contribution to Docs.

I see there are 6 tasks marked as done, but I cannot find them.
Also, what are the remaining tasks?
What one do I need to do>

**Comment by SSwiniarski** [comment]
You need to fork this repository, create a branch of that fork for a QR Code entry. The entry should go in a new file in docs/content/general/concepts/qr-code/qr-code.md.

For guidance on writing the entry, please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/).

Once the entry is written create a PR and the maintainers will review it, and possibly ask for edits before merging.

**Comment by easoftwareGit** [comment]
Thanks. Will do.

**Comment by easoftwareGit** [comment]
I am done with writing and have the text in Markdown format. Reading the
description in the Create Pull Request form, I am supposed to run `yarn
format path/to/markdown/file.md` to make sure the markdown file is
formatted correctly. I do not have yarn installed, I am using npm.

Anyway, there is not much formatting needed in my markdown file. Since this
is my first contribution, I am asking for more guidance.

Thanks

**Comment by SSwiniarski** [comment]
@easoftwareGit You can simply create a PR and we can go from there. The maintainers will go over your contribution and guide you through anything that needs to be done in order to merge it.
