### ISSUE TITLE
[Term Entry] Java Date before

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#2834]
### Reason/inspiration (optional)

We would like a new term entry under Java [Date](https://www.codecademy.com/resources/docs/java/date) for the Java Date `.before()` method. 
Provide the entry in a markdown file under `docs/content/java/concepts/date/terms/before/before.md`

The entry should
    - Have an introductory paragraph about what the method is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the method in use.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by mfa34** [comment]
@christian-dinh i am interested in taking this issue.

**Comment by KTom101** [comment]
@mfa34 You're assigned. Be sure to look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) as well as the documentation listed in the description.

**Comment by mfa34** [comment]
Thank you.
