### ISSUE TITLE
[Concept Entry] Java Calendar

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#2839]
### Reason/inspiration (optional)

Please add a new concept entry on the `Calendar` class provided under the `java.util` package. 

The new file will go under content/java/concepts/calendar/calendar.md and include information on what the `Calendar` class is and how an object of the `Calendar` class can be constructed.

Please refer to the entry templates, content standards, and markdown style guide when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by ChiragAgg5k** [comment]
Hi, I would like to take this issue

**Comment by SSwiniarski** [comment]
@ChiragAgg5k You're assigned.
