### ISSUE TITLE
[Entry Request] General: Unit Testing

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#284]
## Description

Write a "Unit Testing" entry in the General topic.

General topic: https://www.codecademy.com/resources/docs/general

## Type of Entry Request

- One or more new entries/terms requested.

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by ManishS6** [comment]
@sonnynomnom I would like to work on this
Please assign this task to me

**Comment by sonnynomnom** [comment]
@ManishS6 all you!

**Comment by sonnynomnom** [comment]
how did you find this by the way @ManishS6?

**Comment by ManishS6** [comment]
@sonnynomnom https://github.com/issues?q=is%3Aopen+is%3Aissue+label%3AHacktoberfest I use this link and keeping refreshing every few minutes until I find something interesting.

**Comment by sonnynomnom** [comment]
Gotcha! Good luck. Make sure to read through our README and Contribution Guide and remember, it's about quality, not quantity.

**Comment by ManishS6** [comment]
@sonnynomnom on it.

**Comment by Dusch4593** [comment]
Hi @ManishS6! Brandon from the Free Team 😄 Just wanted to check in and ask if you were still working on a PR for this issue?

**Comment by ManishS6** [comment]
@Dusch4593 I totally forgot about this Issue. Sorry for that, I'll unassign myself.

**Comment by Dusch4593** [comment]
> @Dusch4593 I totally forgot about this Issue. Sorry for that, I'll unassign myself.

@ManishS6 No worries! If you're ever interested in coming back I'm positive there will be an open issue that interests you! Thank you!

**Comment by Vivek-Prajapatii** [comment]
hey @Dusch4593  may i take this issue ?
interested in it.

**Comment by Dusch4593** [comment]
> hey @Dusch4593 may i take this issue ? interested in it.

Since we're currently working with you on #480, let's leave this issue open for someone else for now. 😄
