### ISSUE TITLE
[Term Entry] Go Math Function Sqrt() entry sqrt.md contains a typographical error

### ISSUE THREAD

**Issue by Don-Booth** [Codecademy/docs#2841]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

There is a typographical error in [content/go/concepts/math-functions/terms/sqrt/sqrt.md](https://github.com/Codecademy/docs/blob/726ef60d335dd1fc927daa9d5f072b08d13ecf80/content/go/concepts/math-functions/terms/sqrt/sqrt.md) whereby 'excepts' was used instead of 'accepts'.

In the syntax section of the document, the following:

`Sqrt()` excepts an argument of type `float64` and returns a value of type `float64`.

should be changed to:

`Sqrt()` accepts an argument of type `float64` and returns a value of type `float64`.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Don-Booth** [comment]
I would like to have this issue assigned to myself so I can fix it.

Thanks!

**Comment by KTom101** [comment]
@Don-Booth You're assigned
