### ISSUE TITLE
[Entry Request] Python: Modulo

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#285]
## Description

Write a "Modulo" entry in the Python topic.

General topic: https://www.codecademy.com/resources/docs/python

## Type of Entry Request

- One or more new entries/terms requested.

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by EugeneGohh** [comment]
Can I work on this?

**Comment by sonnynomnom** [comment]
Yes @EugeneGohh lol
