### ISSUE TITLE
[Edit] Go Map Iteration Example

### ISSUE THREAD

**Issue by k1nho** [Codecademy/docs#2855]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

The current map content for Go shows how to access individual elements. It would be nice to demonstrate that maps can also be iterated to obtain all the (key, val) pairs held by the map.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by KTom101** [comment]
@k1nho I've assigned you to edit the existing Go[Map](https://www.codecademy.com/resources/docs/go/map) entry to include information and an example on iteration. You can check out the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide)for additional information on contributing.  See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

 After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval. Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by k1nho** [comment]
Indeed, this is my 1st contribution to Codecademy Docs. I found about Docs through the folks at [Open-Sauced](https://opensauced.pizza/)
