### ISSUE TITLE
Add information about depreciation 

### ISSUE THREAD

**Issue by CBID2** [Codecademy/docs#2857]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Center is no longer used to center elements so I think there should be a note providing this information and a link to the text-align center entry. 
Note: I want to do this change 

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by CBID2** [comment]
@KTom101, check this out

**Comment by KTom101** [comment]
@CBID2 This is mentioned already in the body paragraph of the [<center>](https://www.codecademy.com/resources/docs/html/elements/center) entry. Were you looking to change it to a blockquote?

**Comment by CBID2** [comment]
> @CBID2 This is mentioned already in the body paragraph of the [<center>](https://www.codecademy.com/resources/docs/html/elements/center) entry. Were you looking to change it to a blockquote?

Yeah @KTom101

**Comment by KTom101** [comment]
@CBID2 I assigned you.

**Comment by CBID2** [comment]
> @CBID2 I assigned you.

@KTom101, I decided to turn the paragraph about `text-align: center` into a note instead. I felt that it would encourage them to not use the `<center>` tag as opposed to turning the deprecation paragraph into a blockquote.
