### ISSUE TITLE
[Term Entry] Subject: MDX

### ISSUE THREAD

**Issue by CBID2** [Codecademy/docs#2872]
### Reason/inspiration (optional)

I've been working with MDX lately. It's an extension to Markdown that lets people include JSX in Markdown documents, and I would love to add this as a concept entry to the Markdown section. 

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by CBID2** [comment]
> Hi @CBID2   I am interested in taking on this issue. I am using Codecademy to learn about Git & GitHub thanks.
Hi @NenoSto. I'm not a maintainer so I don't have the power to assign it to you. Also, I mentioned in the issue that I want to work on it. However, I'd love to have your review once I submit the PR. Here's how you can do that: https://www.freecodecamp.org/news/code-review-tips/

**Comment by KTom101** [comment]
@CBID2 I assigned you to this.
