### ISSUE TITLE
[Entry Request] Python: Dates

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#288]
## Description

Write a "Dates" entry in the Python topic.

General topic: https://www.codecademy.com/resources/docs/python

## Type of Entry Request

- One or more new entries/terms requested.

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by ramanic** [comment]
Can I do this?

**Comment by sonnynomnom** [comment]
@ramanic all you! how did you hear about this by the way

**Comment by ramanic** [comment]
Thanks, I was just looking for good first issues and ended up here.

**Comment by sonnynomnom** [comment]
Gotcha! Good luck. 

Make sure to read through our README and Contribution Guide and remember, it's about quality, not quantity.

**Comment by sonnynomnom** [comment]
Did you find this through Hacktoberfest btw?

**Comment by ramanic** [comment]
Yup, I wanted to get started in open source. Hacktoberfest looks to be a great opportunity.

**Comment by sonnynomnom** [comment]
Awesome!
