### ISSUE TITLE
[Term Entry] Swift Protocols Encodable

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2884]
### Reason/inspiration (optional)

We would like a new term entry for Swift [Protocols](https://www.codecademy.com/resources/docs/swift/protocols) about the Encodable protocol. The entry should go in a new file in docs/content/swift/concepts/protocols/terms/encodable/encodable.md

The entry should
    - Have an introductory paragraph about what the protocol is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - A basic example showing the protocol in use

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by GrayGhostDev** [comment]
# Requesting Permission to Participate
=============================

I am requesting permission to contribute to this issue. 
Thank you.

**Comment by KTom101** [comment]
@GrayGhostDev You've been assigned. Thank you for your patience.

**Comment by SSwiniarski** [comment]
@GrayGhostDev It's been two weeks. Are you still working on this issue? Note that in another week this will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@GrayGhostDev I am unassigning this due to inactivity.

**Comment by gracekishino** [comment]
Please can I work on this issue?
