### ISSUE TITLE
[Entry Request] Python: Scope

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#292]
## Description

Write a high-quality "Scope" entry in the Python topic.

General topic: https://www.codecademy.com/resources/docs/python

Please read through the README file and Contribution Guide.

## Type of Entry Request

- One or more new entries/terms requested.

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by siolavL** [comment]
Hello! May I work on this?

**Comment by sonnynomnom** [comment]
Absolutely @siolavL!

May I ask how you found this repo/Issue?

**Comment by Dusch4593** [comment]
This issue is open for assignment to anyone who is interested! 😄

**Comment by Vivek-Prajapatii** [comment]
may i take it?

**Comment by Dusch4593** [comment]
@Vivek-Prajapatii Sure! You're assigned! Be sure to take a look at the [CONTRIBUTING.md guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) and [the entry template](https://github.com/Codecademy/docs/blob/main/documentation/entry-template.md) while you work on your changes.
