### ISSUE TITLE
[Entry Request] C++: Methods

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#294]
## Description

Write a high-quality "Methods" entry in C++. 

C++ topic: https://www.codecademy.com/resources/docs/cpp

## Type of Bug Request

- Typo and/or bug within one or more existing entries.
- Unclear explanation of term(s).
- Out-of-date information (new release, deprecated package, etc).
- Updating the documentation

## Type of Entry Request

- One or more new entries/terms requested.
- Recommend change(s) to documentation (such as existing text or new text)

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by vishalram14** [comment]
Hey, shall I work on this?

**Comment by sonnynomnom** [comment]
Hi @vishalram14! Absolutely.

May I ask how you found this Issue?

**Comment by vishalram14** [comment]
Searched using hacktoberfest label, filtered the results by choosing open issues that were recently updated.

**Comment by vishalram14** [comment]
I am extremely sorry to inform you that I have to back out of this , kindly reassign somebody else

**Comment by vishalram14** [comment]
Sorry to inform you that I would like to opt out of this.

**Comment by sonnynomnom** [comment]
All good!

**Comment by DarrylBrooks97** [comment]
I'd like to work on this !

**Comment by DarrylBrooks97** [comment]
Yeah I found it through https://goodfirstissues.com/ filtered with Hacktoberfest

**Comment by sonnynomnom** [comment]
Awesome! Take a look at the README file and the Contribution Guide and take your time on your Pull Request!

**Comment by DarrylBrooks97** [comment]
Hey I believe this issue has already been resolved [here](https://github.com/Codecademy/docs/tree/main/content/cpp/concepts/functions) 'methods' in cpp are called 'functions'

**Comment by DarrylBrooks97** [comment]
Hey there isn't a section on Codecademy for C++ 'Methods'

**Comment by sonnynomnom** [comment]
Yep, you have to research and write it!

We do have one lesson on classes & objects here: 

https://www.codecademy.com/courses/learn-c-plus-plus/lessons/cpp-classes-and-objects/exercises/cpp-class-members
