### ISSUE TITLE
[Entry] Subject: Bayesian Hyperparameter Optimization

### ISSUE THREAD

**Issue by will-r-smith** [Codecademy/docs#2942]
### Type of Edit

Add new content.

### Description

- Basic description of the concept of Bayesian optimization.
- Types of surrogate functions.
- Simple implementation in Python using `hyperopt`.

### Motivation

Following on from completing the Data Scientist: Machine Learning career path, I explored more efficient hyperparameter tuning methods and studied Bayesian optimization. I have since used the method using `hyperopt` on a project at work and feel like I have a solid understanding of the mathematics behind the method and how to implement it.

I would like to select this for my contribution to Docs.

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by will-r-smith** [comment]
I'd like to work on this issue if possible. If not then I could add content on simpler hyperparameter tuning methods instead as these are also missing from the docs.

**Comment by KTom101** [comment]
@will-r-smith Thank you for this issue. I think it's a good idea. I'm comtemplating on where this should live within our current structure but I will assign you in the meantime.

If you haven't already, please review the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide)for additional information on contributing. Also  see the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.

@SSwiniarski @yangc95 Any thoughts on where we would want this to live?

**Comment by SSwiniarski** [comment]
@KTom101, @yangc95 would it fit under algorithms?

**Comment by will-r-smith** [comment]
I was thinking of putting it under ai/machine_learning in a new folder called hyperparameter_tuning. Then it leaves it open to include grid search and random search algorithms in the same folder. Thoughts?

**Comment by SSwiniarski** [comment]
@will-r-smith sounds good, but we don't have unlimited nesting. Either this would have to be a term under machine learning, or we'd need to add a hyperparameter tuning concept under AI for this to live under. We can't nest another folder under machine learning. @yangc95, @KTom101, your thoughts?

**Comment by will-r-smith** [comment]
Ah I see. In which case I reckon a folder under AI.

**Comment by will-r-smith** [comment]
But you let me know which you guys think is best.

**Comment by KTom101** [comment]
@will-r-smith @SSwiniarski Let's create a Hyperparameter Tuning concept under AI so the file path will be `content/ai/concepts/hyperparametertuning/hyperparametertuning.md` and then Bayesian Optimization can live under it as a term `content/ai/concepts/hyperparametertuning/terms/bayesianoptimization/ bayesianoptimization.md`

**Comment by SSwiniarski** [comment]
@will-r-smith @KTom101 That sounds good, though the paths should be:

`content/ai/concepts/hyperparameter-tuning/hyperparameter-tuning.md`
`content/ai/concepts/hyperparameter-tuning/terms/bayesian-optimization/ bayesian-optimization.md`

**Comment by SSwiniarski** [comment]
Closing this issue that @will-r-smith created because they abandoned the PR.
