### ISSUE TITLE
[Entry Request] C++: Inheritance

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#295]
## Description

Write a high-quality "Inheritance" entry in C++. 

C++ topic: https://www.codecademy.com/resources/docs/cpp

## Type of Bug Request

- Typo and/or bug within one or more existing entries.
- Unclear explanation of term(s).
- Out-of-date information (new release, deprecated package, etc).
- Updating the documentation

## Type of Entry Request

- One or more new entries/terms requested.
- Recommend change(s) to documentation (such as existing text or new text)

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by sammy8825** [comment]
I would like to work on this issue. 
Can you assign it to me ??

**Comment by sonnynomnom** [comment]
@sammy8825 Yep, all you! May I ask how you found this issue?

**Comment by sammy8825** [comment]
I didn't get u sorry

**Comment by sammy8825** [comment]
Found through hacktober quest.

**Comment by sonnynomnom** [comment]
yep! @sammy8825

**Comment by Dusch4593** [comment]
Hi @sammy8825! Brandon from the Free Team 😄 Just wanted to check in and ask if you were still working on a PR for this issue?

**Comment by SSwiniarski** [comment]
@Dusch4593, I'll take this over if there's no response by the time I finish [281](https://github.com/Codecademy/docs/issues/281).
