### ISSUE TITLE
[Term Entry] Swift Protocols Decodable

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2958]
### Reason/inspiration (optional)

We would like a new term entry for Swift [Protocols](https://www.codecademy.com/resources/docs/swift/protocols) about the Decodable protocol. The entry should go in a new file in docs/content/swift/concepts/protocols/terms/decodable/decodable.md

The entry should
    - Have an introductory paragraph about what the protocol is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - A basic example showing the protocol in use

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by sdwinston** [comment]
I would like to work on this issue to complete the Learn Git & GitHub course on Codecademy.

**Comment by KTom101** [comment]
@sdwinston You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by sdwinston** [comment]
@KTom101 thank you! This is my first contribution to Codecademy Docs. I'm a pro member and this is a portfolio project for one of the courses.

**Comment by SSwiniarski** [comment]
@sdwinston It's been two weeks. Are you still working on this issue? Note that in another week this issue will be unassigned due to inactivity.

**Comment by sdwinston** [comment]
Confirming the pull request will be submitted today.
