### ISSUE TITLE
[Term Entry] Swift Protocols Encoder

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2959]
### Reason/inspiration (optional)

We would like a new term entry for Swift [Protocols](https://www.codecademy.com/resources/docs/swift/protocols) about the Encoder protocol. The entry should go in a new file in docs/content/swift/concepts/protocols/terms/encoder/encoder.md

The entry should
    - Have an introductory paragraph about what the protocol is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - A basic example showing the protocol in use

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by ReprogramAkash** [comment]
Hi, I would like to work on this.

**Comment by KTom101** [comment]
@ReprogramAkash You're assigned

**Comment by SSwiniarski** [comment]
@ReprogramAkash It's been two weeks. Are you still working on this issue. Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@ReprogramAkash this issue has been unassigned due to inactivity.

**Comment by BBrandl948** [comment]
Hi, I would like to work on this

**Comment by SSwiniarski** [comment]
@BBrandl948 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by BBrandl948** [comment]
Yes, this is my first time I try to contribute. It is one part of the iOS developer course called portfolio exercise.

**Comment by BBrandl948** [comment]
After starting to write down some collected information I came to the point to suggest to change the topic from Encoding to Encodeable. This protocol covers both protocols Encodeable and Decodeable. Would this be an opportunity for you too?

**Comment by SSwiniarski** [comment]
I think I'd defer to @yangc95 on this question.

**Comment by yangc95** [comment]
@BBrandl948 Yes, that would work well! Thank you for the suggestion 🙂

**Comment by yangc95** [comment]
> It should be Codeable instead of Encodeable...After You made the changes in the documents title, I have to fork the docs repo again and download it into my local GitHub app. Then I change the content of the specific document...Thank you in advance for your support.

Thanks for bringing that up! Let's keep things modular here and cover Encoder actually instead of Encodable since there is already an Encodable entry. Decodable will be covered in a separate entry but Codable will have its own entry and link out to the existing Encodable and Decodable entries.

If you'd like to take on creating a Codable entry let me know and we can create an issue for that!

**Comment by BBrandl948** [comment]
Thanks for your reply. I will add some Information to the Encoder document. If you are satisfied with my work, I will start to add the Codeable Entry. I think I got a better understanding of the workflow now. Thanks for your assistance.

**Comment by BBrandl948** [comment]
I already started a pull request for this topic. If I made any mistake please let me know.

**Comment by yangc95** [comment]
@BBrandl948 I could not find a pull request that is related to the `Encoder` protocol.

Are you referencing this edit to the `Encodable` protocol: https://github.com/Codecademy/docs/pull/3293

**Comment by BBrandl948** [comment]
Yes I reference to the Encodable protocol.

**Comment by BBrandl948** [comment]
@SSwiniarski I was waiting for the second review which took place recently. As I read there is another possible Correction. I will work on this as fast as possible. I think we can finish this issue afterwards.

**Comment by SSwiniarski** [comment]
@BBrandl948 I am unassigning this due to inactivity.

**Comment by arirays** [comment]
Can I work on this issue?

**Comment by BBrandl948** [comment]
I was waiting for further reviewing changes I have made about two weeks ago?

**Comment by BBrandl948** [comment]
<img width="1042" alt="Bildschirmfoto 2023-10-26 um 11 04 07" src="https://github.com/Codecademy/docs/assets/140916052/e4a967b1-8e60-4b51-8c52-5e4f7e3060be">

**Comment by BBrandl948** [comment]
I think so I never worked on another issue? I don't know what went wrong. If I made a mistake please let me know.

**Comment by SSwiniarski** [comment]
@BBrandl948 can you link to that issue here?

**Comment by BBrandl948** [comment]
https://github.com/Codecademy/docs/pull/3293

**Comment by yuduth8899** [comment]
is this issue still open? i want to take this issue

**Comment by SSwiniarski** [comment]
@yuduth8899 apparently there's already a PR open for this issue.

**Comment by SSwiniarski** [comment]
Closed because PR was merged.
