### ISSUE TITLE
[Term Entry] Swift Protocols Decoder

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2960]
### Reason/inspiration (optional)

We would like a new term entry for Swift [Protocols](https://www.codecademy.com/resources/docs/swift/protocols) about the Decoder protocol. The entry should go in a new file in docs/content/swift/concepts/protocols/terms/decoder/decoder.md

The entry should
    - Have an introductory paragraph about what the protocol is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - A basic example showing the protocol in use

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by ReprogramAkash** [comment]
Hi, I would like to work on this.

**Comment by KTom101** [comment]
@ReprogramAkash You're assigned

**Comment by SSwiniarski** [comment]
@ReprogramAkash This issue has been unassigned due to inactivity.

**Comment by ShadowMatrix78** [comment]
@SSwiniarski I am interested in taking this issue on. I found out about docs through a course on Codecademy

**Comment by KTom101** [comment]
@ShadowMatrix78 I've assigned you 🎉 In addition to the documents linked in the description, please also take a look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.

**Comment by caupolicandiaz** [comment]
@ShadowMatrix78 I've unassigned this issue because of the lack of progress on the PR

**Comment by marjoriekohn** [comment]
Can I work on this?

**Comment by caupolicandiaz** [comment]
@marjoriekohn It's all yours!
