### ISSUE TITLE
[Term Entry] Swift Protocols SingleValueEncodingContainer

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2963]
### Reason/inspiration (optional)

We would like a new term entry for Swift [Protocols](https://www.codecademy.com/resources/docs/swift/protocols) about the SingleValueEncodingContainer protocol. The entry should go in a new file in docs/content/swift/concepts/protocols/terms/singlevalueencodingcontainer/singlevalueencodingcontainer.md

The entry should
    - Have an introductory paragraph about what the protocol is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - A basic example showing the protocol in use

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by turtelneck** [comment]
Hi, I'd like to work on this.

**Comment by KTom101** [comment]
@turtelneck You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by turtelneck** [comment]
Thanks! Learned about it in the Codecademy iOS Dev Career Path during the section about GitHub.

**Comment by KTom101** [comment]
@turtelneck Awesome, we look forward to seeing your PR!

**Comment by caupolicandiaz** [comment]
I'm reopening this due to lack of progress

**Comment by marjoriekohn** [comment]
I would like to work on this

**Comment by caupolicandiaz** [comment]
@marjoriekohn It's all yours

**Comment by SSwiniarski** [comment]
@marjoriekohn It's been over two weeks. Are you still working on this issue? Note that in the next few days if we don't see a PR this will be unassigned due to inactivity.

**Comment by marjoriekohn** [comment]
I am still working on this and will submit a PR by EOD
