### ISSUE TITLE
[Term Entry] Java Calendar compareTo()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#2969]
### Reason/inspiration (optional)

Please add the `compareTo()` method as a new term entry for the [Calendar](https://www.codecademy.com/resources/docs/java/calendar) class. Provide the entry in a markdown file and place under the file path `content/java/concepts/calendar/terms/compareTo/compareTo.md`

The entry should have the following:

–  An introductory paragraph about what the method is and does.
–  A syntax section with a pseudo code block with an explanation of it.
–  An example showing the method in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by ReyhanPatria** [comment]
Hi! I'd like be assigned to this please.

**Comment by KTom101** [comment]
@ReyhanPatria You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by ReyhanPatria** [comment]
Hi @KTom101 ! Yes this is my first contribution to codecademy docs, I've known about Codecademy for a while, but I found out about this through browsing GitHub. I thought it'll be a good start to begin contributing to open source repos.

**Comment by KTom101** [comment]
@ReyhanPatria That's great! We look forward to seeing your PR for this. 😁

**Comment by Shashankappu** [comment]
made changes please review @SSwiniarski
