### ISSUE TITLE
[Entry Request] C++: Encapsulation

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#297]
## Description

Write a high-quality "Encapsulation" entry in C++. 

C++ topic: https://www.codecademy.com/resources/docs/cpp

## Type of Bug Request

- Typo and/or bug within one or more existing entries.
- Unclear explanation of term(s).
- Out-of-date information (new release, deprecated package, etc).
- Updating the documentation

## Type of Entry Request

- One or more new entries/terms requested.
- Recommend change(s) to documentation (such as existing text or new text)

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by bhagyamudgal** [comment]
Can I take this one?

**Comment by sonnynomnom** [comment]
Yep, all you @bhagyamudgal! Don't forget to create a new branch for this one.

**Comment by bhagyamudgal** [comment]
@sonnynomnom Sure Sonny.

**Comment by sonnynomnom** [comment]
It's live!
