### ISSUE TITLE
[Entry Request] C++: Constructors

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#298]
## Description

Write a high-quality "Constructors" entry in C++. 

C++ topic: https://www.codecademy.com/resources/docs/cpp

## Type of Bug Request

- Typo and/or bug within one or more existing entries.
- Unclear explanation of term(s).
- Out-of-date information (new release, deprecated package, etc).
- Updating the documentation

## Type of Entry Request

- One or more new entries/terms requested.
- Recommend change(s) to documentation (such as existing text or new text)

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by TusharSharmaIN** [comment]
assign this to me.

**Comment by sonnynomnom** [comment]
Hi @TusharSharmaIN, sure. You can take this on. May I ask how you found this issue?

**Comment by Dusch4593** [comment]
Hi @TusharSharmaIN! Brandon from the Free Team 😄 Just wanted to check in and ask if you were still working on a PR for this issue?

**Comment by SSwiniarski** [comment]
@Dusch4593, since @TusharSharmaIN hasn't responded, I'll take this one over.
