### ISSUE TITLE
[Entry Request] Java: Random

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#299]
## Description

Write a high-quality "Random" entry in Java. 

Java topic: https://www.codecademy.com/resources/docs/java

## Type of Bug Request

- Typo and/or bug within one or more existing entries.
- Unclear explanation of term(s).
- Out-of-date information (new release, deprecated package, etc).
- Updating the documentation

## Type of Entry Request

- One or more new entries/terms requested.
- Recommend change(s) to documentation (such as existing text or new text)

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by divya-ganesh** [comment]
I'd like to work on this issue. May I please be assigned? 
Thanks :)

**Comment by sonnynomnom** [comment]
Yes you can! @divya-ganesh 

May I ask how you found this Issue?

**Comment by divya-ganesh** [comment]
Thank you!! I found a post on r/learnprogramming and I'm just learning about the opensource world and I'm looking for places to contribute. 
Will definitely do my best with this topic!

**Comment by sonnynomnom** [comment]
Oh wow niiice. Yep, we have two people on the team review your entry. So definitely take your time and no rush!
