### ISSUE TITLE
[Entry Request] Java: Constructors

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#300]
## Description

Write a high-quality "Constructors" entry in Java. 

Java topic: https://www.codecademy.com/resources/docs/java

## Type of Bug Request

- Typo and/or bug within one or more existing entries.
- Unclear explanation of term(s).
- Out-of-date information (new release, deprecated package, etc).
- Updating the documentation

## Type of Entry Request

- One or more new entries/terms requested.
- Recommend change(s) to documentation (such as existing text or new text)

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by divya-ganesh** [comment]
I'd like to work on this issue.

**Comment by sonnynomnom** [comment]
Hi @divya-ganesh, I gave you another entry to start. So maybe focus on that for now and swing back down the road if this one is still untaken? Thanks!

**Comment by divya-ganesh** [comment]
Okay! Thank you so much for the opportunity though! I really appreciate  it :)

**Comment by ashishkamathi** [comment]
I would love to contribute can you please assign to me..?

**Comment by sonnynomnom** [comment]
Yep, @ashishkamathi! May I ask how you found this issue?

**Comment by sonnynomnom** [comment]
Awesome! Yeah we are are looking for a new **constructors.md** file that go over constructors in Java.

Here's an example of **arrays.md** in Java: https://www.codecademy.com/resources/docs/java/arrays

Make sure to read through the README and Contribution Guide thoroughly. Your entry will be reviewed by two maintainers! So it's about quality not just quantity.

**Comment by sonnynomnom** [comment]
It's live! https://www.codecademy.com/resources/docs/java/constructors
