### ISSUE TITLE
[Concept Entry] JavaScript: Accessors

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#3002]
### Reason/inspiration (optional)

We would like a new concept entry for JavaScript about Accessor methods. The entry should go in a new file in docs/content/javascript/concepts/accessors/accessors.md

The entry should
    - Have an introductory paragraph about the concept.
    - Code blocks or codebytes displaying different aspects of the concept.
    - Internal linking as applicable.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Judis07** [comment]
Hello @yangc95 I would like to work on this issue.

**Comment by KTom101** [comment]
@Judis07 You're assigned
