### ISSUE TITLE
[Concept Entry] JavaScript: Mutators

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#3003]
### Reason/inspiration (optional)

We would like a new concept entry for JavaScript about Mutator methods. The entry should go in a new file in docs/content/javascript/concepts/mutators/mutators.md

The entry should
    - Have an introductory paragraph about the concept.
    - Code blocks or codebytes displaying different aspects of the concept.
    - Internal linking as applicable.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Judis07** [comment]
Hello @yangc95 I would like to be assigned this issue.

**Comment by KTom101** [comment]
@Judis07 This will be your third issue.

So that you know, contributors can be assigned to up to 3 issues at a time and will have to submit pull requests for the ones they're assigned to before being assigned to any additional issues. 🙂

**Comment by Judis07** [comment]
@KTom101 Thanks for the heads up. 👍

**Comment by Judis07** [comment]
HI @KTom101 due to other commitments, I am no longer able to work on this issue. Please unassign me so that someone else can work on it. Thank you

**Comment by Jaytrindade** [comment]
Hello @yangc95 I would like to be assigned this issue.

**Comment by Jaytrindade** [comment]
Hello @yangc95! I would like to assigned this issue.

**Comment by KTom101** [comment]
@Jaytrindade You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by SSwiniarski** [comment]
@Jaytrindade It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@Jaytrindade This issue has been unassigned due to inactivity.

**Comment by carlos-ds** [comment]
Hi @SSwiniarski @KTom101 I'd like to take this one if that's ok?
I was wondering if you also have pointers on what exactly should be covered? Are we talking about _setters_ when we say _mutators_, or should this also cover _mutating methods_ for objects and arrays?

**Comment by SSwiniarski** [comment]
@carlos-ds, you're assigned. I'll defer to @yangc95 on the details since she drafted the issue.

**Comment by yangc95** [comment]
> I was wondering if you also have pointers on what exactly should be covered? Are we talking about _setters_ when we say _mutators_, or should this also cover _mutating methods_ for objects and arrays?

@carlos-ds that's a great question! Let's cover setters here for objects. Also see this entry on accessors: https://www.codecademy.com/resources/docs/javascript/accessors

Feel free to go more in depth here and thanks for sticking closely to the scope that is being determined!

**Comment by carlos-ds** [comment]
@yangc95 Ok, much clearer now, thanks for the response! I'll try to open a PR by the end of this month at the latest.

**Comment by SSwiniarski** [comment]
@carlos-ds It's been two weeks since you were assigned. Just checking that you're still working on the issue. Normally, in another week it would be unassigned for inactivity.

**Comment by carlos-ds** [comment]
@SSwiniarski yes, I'm still working on this. Another week should be good, should have a PR ready by then.
