### ISSUE TITLE
[Entry Request] Java: Bitwise Operators

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#301]
## Description

Write a high-quality "Bitwise Operators" entry in Java. 

Java topic: https://www.codecademy.com/resources/docs/java

## Type of Bug Request

- Typo and/or bug within one or more existing entries.
- Unclear explanation of term(s).
- Out-of-date information (new release, deprecated package, etc).
- Updating the documentation

## Type of Entry Request

- One or more new entries/terms requested.
- Recommend change(s) to documentation (such as existing text or new text)

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by rishikeshreddyakkireddy** [comment]
Can you assign this to me, I want to work on this issue.

**Comment by sonnynomnom** [comment]
Yep, you can! May I ask how you found this Issue?

**Comment by rishikeshreddyakkireddy** [comment]
@sonnynomnom I have been searching for repositories in git using label:hacktoberfest and found the issue

**Comment by sonnynomnom** [comment]
Awesome. Looking forward!

**Comment by Dusch4593** [comment]
Hi @rishikeshreddyakkireddy! Brandon from the Free Team 😄 Just wanted to check in and ask if you were still working on a PR for this issue?

**Comment by SSwiniarski** [comment]
@Dusch4593, since @rishikeshreddyakkireddy hasn't responded, I'll take this on.

**Comment by SSwiniarski** [comment]
@Dusch4593: Actually, this seems to be covered by the existing operators entry in Java. We should probably just close it.

**Comment by KTom101** [comment]
@SSwiniarski Thanks for pointing this out. It appears this was resolved through [PR #382](https://github.com/Codecademy/docs/pull/382) right after this request was made. I'm closing the issue!
