### ISSUE TITLE
Formatting Error in MDX

### ISSUE THREAD

**Issue by CBID2** [Codecademy/docs#3011]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

Hi there! I just got the [MDX entry](https://www.codecademy.com/resources/docs/markdown/mdx) merged, and now I noticed that the explanation for the second example is within the first code snippet. Can I fix it? 

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by KTom101** [comment]
@CBID2 Yes you can, thank you.
