### ISSUE TITLE
[Entry] Subject: HTML Layout

### ISSUE THREAD

**Issue by Sushilverma002** [Codecademy/docs#3018]
### Reason/inspiration (optional)

It is the important concept in HTML and i feel it must be there in HTML section. 
key point cover as follows:-

these are tag should be covered in html layout section.
header,nav,section,article,aside,etc 
folder location -> content/html/concepts.

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by manviii27** [comment]
@yangc95 I am interested in taking this issue on. I found out about Docs through social media

**Comment by SSwiniarski** [comment]
@manviii27 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by KTom101** [comment]
@SSwiniarski @manviii27 @Sushilverma002 I'm going to have to unassign this issue and close it out. We already have these tags under [Semantic HTML](https://www.codecademy.com/resources/docs/html/semantic-html) as term entries.

Apologies for any confusion. Please check the other [issues](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee), if you still wish to work on something.
