### ISSUE TITLE
CSS Fonts : Fonts in CSS

### ISSUE THREAD

**Issue by sandeepgopan** [Codecademy/docs#3027]
### Reason/inspiration (optional)

CSS font is a big topic that will be a helpful topic to add to CSS.
Proper knowledge of how to use different font families and fonts based on languages will help(eg: Arabic, Chinese, English).

Will be happy to write about this topic.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by moayed-mustafa** [comment]
Hey @sandeepgopan. I just discovered the Codecademy docs and would love to contribute by taking this issue.

**Comment by SSwiniarski** [comment]
@moayed-mustafa, @sandeepgopan already expressed interest in writing this issue.

@sandeepgopan, you're assigned.
