### ISSUE TITLE
[Entry] Subject: Information Technology 

### ISSUE THREAD

**Issue by CBID2** [Codecademy/docs#3029]
### Reason/inspiration (optional)

I've been studying the fundamentals of tech support and noticed that the Docs project does not have an entry on Information Technology, so I would like to add an entry on this topic.  

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
@CBID2, you're assigned!
