### ISSUE TITLE
[Entry] Subject: HTML Symbols

### ISSUE THREAD

**Issue by Sushilverma002** [Codecademy/docs#3041]
### Reason/inspiration (optional)

want to add Symbols content under HTML. the location will be CONTENT/HTML.

POINTS:-
Some Mathematical Symbols Supported by HTML
Some Greek Letters Supported by HTML
Some Other Entities Supported by HTML

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by SSwiniarski** [comment]
@Sushilverma002 we already have an [HTML entities](https://www.codecademy.com/resources/docs/html/entities) entry.

**Comment by Sushilverma002** [comment]
@SSwiniarski Yes i would like to add some Greek letter supported by HTML.
see:-
![image](https://github.com/Codecademy/docs/assets/114687502/8800ec32-9cc6-454a-935b-5c1d2cac368c)

**Comment by Sushilverma002** [comment]
@SSwiniarski please respond sir.

**Comment by SSwiniarski** [comment]
@rveliza, @Sushilverma002 has first crack at this issue.

@Sushilverma002 you're assigned. Please make a PR with separate entries for Greek and Math symbols as terms under the HTML entities concept.

**Comment by yangc95** [comment]
@Sushilverma002 continuing with this issue discussion, I see that there is an extensive list of different entities. This issue covers: Mathematical Symbols, Greek Letters, and others (not mentioned).

Did you have any plans to create additional issues surrounding entities or were you also going to open up a separate pull request that relates to this issue, but cover mathematical symbol HTML entities?

Just making sure so we know how this term folder is going to be expanded upon further.

Thanks for your initiative in covering all the different HTML entities 🙂
