### ISSUE TITLE
[Term Entry] PHP Arrays `array_replace()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#3046]
### Reason/inspiration (optional)

We would like a new term entry for [PHP](https://www.codecademy.com/resources/docs/php) about the `array_replace()` function.

The entry should go in a new file in `docs/content/php/concepts/arrays/terms/array-replace/array-replace.md` (Note the dashes rather than underscores.)

The entry should 

- Have a syntax section illustrating the function with a ` ```pseudo ` code block. 
- An example showing the function in use with a ` ```php ` code block. 
- A runnable codebyte example in a ` ```codebyte/php` block. 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by PriyansuMaurya** [comment]
I would like to work on this issue.

**Comment by manviii27** [comment]
@SSwiniarski Can I be assigned to this issue? I would like to work on it.

**Comment by SSwiniarski** [comment]
@PriyansuMaurya You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by PriyansuMaurya** [comment]
Is this alright?


---
Title: 'array_replace()'
Description: 'Used to replace the values of an array with values from one or more arrays.'
Subjects:
  - 'Computer Science'
  - 'Web Development'
Tags:
  - 'Arrays'
  - 'Methods'
  - 'Functions'
CatalogContent:
  - 'learn-php'
  - 'paths/computer-science'
---

The **`array_replace()`** function in PHP is used to replace the values of an array with values from one or more arrays.

## Syntax

```pseudo
array_replace(array $array, array ...$replacements): array
```

- `$array` (array): The original array that will be used as the base.
- `$replacements` (array): One or more arrays containing the replacement values.

> **Note:** If multiple arrays contain the same key, the value from the last array in the argument list will overwrite the previous ones.

## Example

Consider the following arrays:

```php
<?php
$array1 = ['a' => 1, 'b' => 2, 'c' => 3];
$array2 = ['b' => 10, 'c' => 20, 'd' => 30];

$replacedArray = array_replace($array1, $array2);
print_r($replacedArray);
?>
```

**Output:**

```
Array
(
    [a] => 1
    [b] => 10
    [c] => 20
    [d] => 30
)
```

## Codebyte Example

In the following PHP code, the `array_replace()` function is demonstrated by replacing values in the `$baseArray` with values from the `$replacementArray`. The resulting array is then printed.

```codebyte/php
<?php
$baseArray = ['red', 'green', 'blue'];
$replacementArray = [1 => 'yellow', 2 => 'purple'];

$replacedArray = array_replace($baseArray, $replacementArray);
print_r($replacedArray);
?>
```

When executed, this code will output:

```
Array
(
    [0] => red
    [1] => yellow
    [2] => purple
)
```

**Comment by PriyansuMaurya** [comment]
> @PriyansuMaurya You should submit this in a PR to have it reviewed.

Alright 👍
