### ISSUE TITLE
[Entry Request] Java: Errors

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#305]
## Description

Write a high-quality "Errors" entry in Java. 

It should include some of the most common errors, exceptions, and even some debugging techniques.

Java topic: https://www.codecademy.com/resources/docs/java

## Type of Bug Request

- Typo and/or bug within one or more existing entries.
- Unclear explanation of term(s).
- Out-of-date information (new release, deprecated package, etc).
- Updating the documentation

## Type of Entry Request

- One or more new entries/terms requested.
- Recommend change(s) to documentation (such as existing text or new text)

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [ ] Assignee is added

**Comment by KanhaKorgaonkar** [comment]
Hi I would like to work on this issue, please assign it to me thanks!

**Comment by KanhaKorgaonkar** [comment]
Hi! @sonnynomnom thanks! I found this on the Hacktoberfest discord server.

**Comment by KanhaKorgaonkar** [comment]
Hey @sonnynomnom I am really sorry but I couldn’t make much progress so far, so I am un-assigning myself from this issue. Thanks!

**Comment by dhruvy1** [comment]
Hi @sonnynomnom could I please be assigned this issue?

**Comment by sonnynomnom** [comment]
Absolutely @dhruvy1!

**Comment by Dusch4593** [comment]
Hi @dhruvy1! Brandon from the Free Team 😄 Just wanted to check in and ask if you were still working on a PR for this issue?

**Comment by dhruvy1** [comment]
Hi @Dusch4593 sorry, I was not able to finish this one as it has a wider scope than I originally thought. Please unassign me and ill try a different issue later :)

**Comment by Dusch4593** [comment]
> Hi @Dusch4593 sorry, I was not able to finish this one as it has a wider scope than I originally thought. Please unassign me and ill try a different issue later 😃

@dhruvy1 No worries! There's tons of open issues with more on the way. And we look forward to working with you on one of them! 😃

**Comment by SSwiniarski** [comment]
@Dusch4593, I'll tackle this one
