### ISSUE TITLE
[Term Entry] Go Strings `CutPrefix()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#3063]
### Reason/inspiration (optional)

We would like a new term entry for [Go](https://www.codecademy.com/resources/docs/go) about the `CutPrefix()` function.

The entry should go in a new file in `docs/content/go/concepts/strings/terms/cutprefix/cutprefix.md`

The entry should 

- Have a syntax section illustrating the function with a ` ```pseudo ` code block. 
- An example showing the function in use with a ` ```go ` code block. 
- A runnable codebyte example in a ` ```codebyte/golang` block. 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by manviii27** [comment]
@SSwiniarski Can I be assigned to this issue? I would like to work on it.

**Comment by IAmRiteshKoushik** [comment]
Hey, I would like to work on this issue. Can I have the assignment ?

**Comment by SSwiniarski** [comment]
@IAmRiteshKoushik You've been assigned three issues, that is the maximum we allow anyone to have at once. Please submit PRs for these already claimed issues before attempting to claim any more.

**Comment by Jamesllllllllll** [comment]
I'd like to work on this issue.

**Comment by SSwiniarski** [comment]
@Jamesllllllllll, You're assigned.

**Comment by Jamesllllllllll** [comment]
Hey @SSwiniarski - for string functions like CutPrefix() the Go version used in Codecademy's Codebyte components will need to be updated. It is currently version 1.17.6, and CutPrefix() is in version 1.2 and newer.

I found the version by doing the following in a Codecademy Codebyte component:

![Codecademy Go Version](https://github.com/Codecademy/docs/assets/125431058/3f7a5ff2-221c-4074-b9b9-c611bf8e4e05)

The following error was returned when trying to use the `CutPrefix()` string function:

```
# command-line-arguments
./main.go:6:14: undefined: strings.CutPrefix
```

![CutPrefix Error](https://github.com/Codecademy/docs/assets/125431058/806ec007-9da5-410c-b162-4ca39d8eca48)

I was able to run the same code locally with success with version 1.2:

![Go Run Success](https://github.com/Codecademy/docs/assets/125431058/a2946d33-4553-4dee-8996-b6ba8b2f42dc)

**Comment by SSwiniarski** [comment]
@Jamesllllllllll We can just leave out the codebyte then.
