### ISSUE TITLE
[Entry Request] Java: Files

### ISSUE THREAD

**Issue by sonnynomnom** [Codecademy/docs#307]
## Description

Write a high-quality "Files" entry in Java (how to read and write files)

Java topic: https://www.codecademy.com/resources/docs/java

## Type of Bug Request

- Typo and/or bug within one or more existing entries.
- Unclear explanation of term(s).
- Out-of-date information (new release, deprecated package, etc).
- Updating the documentation

## Type of Entry Request

- One or more new entries/terms requested.
- Recommend change(s) to documentation (such as existing text or new text)

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by Devanshi0510** [comment]
Hi!
Can you assign this to me?

**Comment by Dusch4593** [comment]
Hi @Devanshi0510! Brandon from the Free Team 😄 Just wanted to check in and ask if you were still working on a PR for this issue?

**Comment by Devanshi0510** [comment]
Sorry, I'm not.

**Comment by Dusch4593** [comment]
No worries! Did you still want to make one or pass to another contributor?

**Comment by Devanshi0510** [comment]
Another contributor can take it.

**Comment by Vivek-Prajapatii** [comment]
may i take this issue? 
i'm interested

**Comment by Dusch4593** [comment]
@Vivek-Prajapatii I just assigned #292 to you. Why don't you work on that one first? (Going forward, I'd like to the assignments to be one issue:one contributor at a time.

**Comment by KabirCampwala** [comment]
Hi! I can do this one.

**Comment by Dusch4593** [comment]
@KabirCampwala Absolutely! You are assigned!

**Comment by aalic1** [comment]
Can I get assigned this issue?

**Comment by KabirCampwala** [comment]
@Dusch4593 You can assign this issue to @aalic1

**Comment by Dusch4593** [comment]
Reassigned to @aalic1!

**Comment by ethan-master-coding** [comment]
@Dusch4593 since the PR was closed due to a lack of activity by the OP should we unassign them?

**Comment by Dusch4593** [comment]
@ethan-master-coding You want?
