### ISSUE TITLE
Correcting the way infinity is represented in Go math functions documentation

### ISSUE THREAD

**Issue by Dilandds** [Codecademy/docs#3088]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

---
Title: 'Documentation Update for Tan Function in Go' 
Description: 'Correcting the way infinity is represented in Go math functions documentation.'
Subjects: 
  - 'Code Foundations'
  - 'Computer Science'
Tags: 
  - 'Numbers'
  - 'Hyperbolic Functions'
  - 'Mathematics'
  - 'Documentation'
CatalogContent: 
  - 'paths/computer-science'
---

In the documentation found under `docs/content/go/concepts/math-functions/terms/tan/tan.md`, there's a discrepancy in the way the results for certain inputs to the `Tan` function are represented.This generates a erro in go `undefined: Inf'.

**Current Representation**:
- The result of `Tan(-Inf)` is `NaN`
- The result of `Tan(+Inf)` is `NaN`
- The result of `Tan(NaN)` is `NaN`

**Proposed Update**:
- The result of `Tan(math.Inf(+1))` is `NaN`
- The result of `Tan(math.Inf(-1))` is `NaN`
- The result of `Tan(NaN)` is `NaN`

This change aligns the representation with the correct way to specify positive and negative infinity in Go.

## Codebyte Example (if applicable)

We can currently support:

- Python
- JavaScript
- Ruby
- C++
- C#
- Go
- PHP

See [content-standards.md](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for more details!

```go
// Example showing the correct representation
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Println(math.Tan(math.Inf(+1))) // Outputs: NaN
	fmt.Println(math.Tan(math.Inf(-1))) // Outputs: NaN
	fmt.Println(math.Tan(math.NaN()))   // Outputs: NaN
}


### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by douglas-narcizo** [comment]
Hi, if this issue is still not assigned, I think I can offer myself to do the task.

**Comment by SSwiniarski** [comment]
@douglas-narcizo You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by douglas-narcizo** [comment]
> If this is your first time contributing, can you let us know how you came across this repo?

Sure!
I am taking Codecademy's **"Learn Git & GitHub"** course… and contributing do Docs is a part of my portfolio project for this course.

**Comment by SSwiniarski** [comment]
Closing this as the PR was closed as unnecessary.
