### ISSUE TITLE
[Term Entry] Lua Strings char()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3110]
### Reason/inspiration (optional)

Please add the `char()` function as a new term entry as part of the string functions terms. Provide the entry in a markdown file and place under the file path `content/lua/concepts/strings/terms/char/char.md`

The entry should have the following:

� An introductory paragraph about what the function is and does.
� A syntax section with a pseudo code block with an explanation of it.
� An example showing the function in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by McDuckson** [comment]
@codecademy-docs I'm interested in taking this issue on, kindly ask to sign me for it, this will be my first one, I found about Docs through codecademy courses.
