### ISSUE TITLE
[Term Entry] Lua Strings reverse()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3112]
### Reason/inspiration (optional)

Please add the `reverse()` function as a new term entry as part of the string functions terms. Provide the entry in a markdown file and place under the file path `content/lua/concepts/strings/terms/reverse/reverse.md`

The entry should have the following:

� An introductory paragraph about what the function is and does.
� A syntax section with a pseudo code block with an explanation of it.
� An example showing the function in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Brag2gr8** [comment]
kindly assign this to me

**Comment by Brag2gr8** [comment]
@SSwiniarski I'm having trouble creating a pull to the main branch after updating my forked repo. I don't know if I did something wrong

**Comment by Brag2gr8** [comment]
Nvm, sorted it out..
forgive me, I haven't spent much time on git.

here is my PR, #3156
