### ISSUE TITLE
[Term Entry] Lua Tables clear()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3113]
### Reason/inspiration (optional)

Please add the `clear()` function as a new term entry as part of the tables functions terms. Provide the entry in a markdown file and place under the file path `content/lua/concepts/tables/terms/clear/clear.md`

The entry should have the following:

� An introductory paragraph about what the function is and does: "Clears all Indexes and Values from a table."
� A syntax section with a pseudo code block with an explanation of it.
� An example showing the function in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by ShatilKhan** [comment]
I've already made a PR, check it out and let me know.

**Comment by SSwiniarski** [comment]
@ShatilKhan I've assigned you to this issue. While it is generally first come first served, we want users to wait until they're officially assigned before creating a PR. This is to avoid multiple people working on the same issue.
