### ISSUE TITLE
[Term Entry] Lua Tables clone()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3114]
### Reason/inspiration (optional)

Please add the `clone()` function as a new term entry as part of the tables functions terms. Provide the entry in a markdown file and place under the file path `content/lua/concepts/tables/terms/clone/clone.md`

The entry should have the following:

� An introductory paragraph about what the function is and does. "Returns a shallow copy of the provided table. A shallow copy refers to an independent clone separate from its original table."
� A syntax section with a pseudo code block with an explanation of it.
� An example showing the function in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by ShatilKhan** [comment]
I'd like to work on this, please assign this to me.
My first pull request for  @codecademy-docs   was merged today. I look forward to contributing more.

**Comment by SSwiniarski** [comment]
@ShatilKhan You're assigned!

**Comment by ShatilKhan** [comment]
Hey, I've made a PR for this issue.
#3138

**Comment by SSwiniarski** [comment]
Closing because this isn't a standard Lua function.
