### ISSUE TITLE
[Term Entry] Lua Tables find()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3117]
### Reason/inspiration (optional)

Please add the `find()` function as a new term entry as part of the tables functions terms. Provide the entry in a markdown file and place under the file path `content/lua/concepts/tables/terms/find/find.md`

The entry should have the following:

� An introductory paragraph about what the function is and does: "Returns the requested needle�s index if found or returns `nil` if the needle does not exist within the provided haystack table."
� A syntax section with a pseudo code block with an explanation of it.
� An example showing the function in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
@ryck715 It's been two weeks. Are you still working on this issue. Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@ryck715 I am unassigning this due to inactivity.

**Comment by T-Mwangi** [comment]
hey @SSwiniarski due to inactivity, can I take on this issue.
thanks

**Comment by rabinnepal** [comment]
hey can i have this issue thanks

**Comment by SSwiniarski** [comment]
@rabinnepal, @T-Mwangi claimed this one first.

**Comment by SSwiniarski** [comment]
@T-Mwangi It's been two weeks. Are you still working on this issue. Note that in another week it will be unassigned due to inactivity.

**Comment by T-Mwangi** [comment]
Hey @SSwiniarski I'm done with the write up, but haven't gone through the documentation guide to verify everything is done according to any specified rules. Once I've read though it all, and corrected what's necessary, I can make a PR.

**Comment by SSwiniarski** [comment]
@T-Mwangi because we haven't seen a PR I am unassigning this due to inactivity.

**Comment by T-Mwangi** [comment]
hey @SSwiniarski I know I don't have much standing to ask this, but can I get an extension on the docs? I have been busy with work this last week and this week, but I am planning on having some down time on the 30-31st of this month, in which I can dedicate to finishing the editing. My GitHub account does have proof that the assignment has been worked on, and is nearly done.

thanks for the opportunity

**Comment by SSwiniarski** [comment]
@T-Mwangi I'll reassign you for another week.

**Comment by T-Mwangi** [comment]
Thanks

**Comment by SSwiniarski** [comment]
@T-Mwangi I am unassigning you because your PR was for the string .find() method not the tables .find() method.

**Comment by moha230** [comment]
Hi is it possible to assign me this issue . Thank you

**Comment by SSwiniarski** [comment]
@moha230 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?
