### ISSUE TITLE
[Term Entry] Lua Tables foreach()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3118]
### Reason/inspiration (optional)

Please add the `foreach()` function as a new term entry as part of the tables functions terms. Provide the entry in a markdown file and place under the file path `content/lua/concepts/tables/terms/foreach/foreach.md`

The entry should have the following:

� An introductory paragraph about what the function is and does: "Iterates through the provided table using the provided callback function. The provided function will receive two parameters, which are **Index** and **Value** from the current table iteration."
� A syntax section with a pseudo code block with an explanation of it.
� An example showing the function in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Vijaykv5** [comment]
Hey I would like to work on this issue. May you can assign me :)

**Comment by SSwiniarski** [comment]
@Vijaykv5 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment]
@Vijaykv5 It's been two weeks. Are you still working on this issue. Note that in another week it will be unassigned due to inactivity.

**Comment by Vijaykv5** [comment]
> @Vijaykv5 It's been two weeks. Are you still working on this issue. Note that in another week it will be unassigned due to inactivity.

Yeah I'll be adding a PR soon

**Comment by Vijaykv5** [comment]
<img width="994" alt="Screenshot 2023-09-17 at 10 02 38 AM" src="https://github.com/Codecademy/docs/assets/94985341/b3686371-0872-4942-9a8a-5623ceb5a64c">

I'm getting this **error** while commiting. May you help me with this @SSwiniarski

**Comment by SSwiniarski** [comment]
@yangc95, @KTom101, @caupolicandiaz Any idea why this is happening to @Vijaykv5

**Comment by KTom101** [comment]
@Vijaykv5 Try fixing the error mentioned at the bottom first and see what happens. It's complaining that a subheading skipped a level and was labeled h3 (###) instead of h2 (##). See if you can find it, make the change, add this new change, and then try re-committing.

**Comment by SSwiniarski** [comment]
@Vijaykv5 are you having any luck submitting your PR? This is the point where we usually unassign an issue due to inactivity.

**Comment by Vijaykv5** [comment]
@SSwiniarski I tried fixing the issue in above I mentioned but not got ran into errors

**Comment by SSwiniarski** [comment]
Is it the same error?

**Comment by Vijaykv5** [comment]
Yes @SSwiniarski

**Comment by Vijaykv5** [comment]
I'll try once again and after that if won't work ,I'll Unassign myself today within 2hrs

**Comment by Vijaykv5** [comment]
Hey Added the PR please check and Let me know :)
