### ISSUE TITLE
[Term Entry] Lua Tables freeze()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3119]
### Reason/inspiration (optional)

Please add the `freeze()` function as a new term entry as part of the tables functions terms. Provide the entry in a markdown file and place under the file path `content/lua/concepts/tables/terms/freeze/freeze.md`

The entry should have the following:

� An introductory paragraph about what the function is and does: "Freezes the provided table, and makes it `read-only`."
� A syntax section with a pseudo code block with an explanation of it.
� An example showing the function in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by ShatilKhan** [comment]
I'd like to take on this issue.
Can you assign it to me?

**Comment by SSwiniarski** [comment]
@ShatilKhan You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by ShatilKhan** [comment]
Hi @SSwiniarski,  Thanks for assigning me the issue!
I have contributed to some other documentations before.
I look forward to working with the codeacademy docs.
I actually came across this repo while I was searching for great active documentations to contribute to. This repo seemed like a great option!

**Comment by ShatilKhan** [comment]
Please check my PR on this issue here #3129 & let me know.
