### ISSUE TITLE
[Term Entry] Luau Tables isfrozen()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3167]
### Reason/inspiration (optional)

Please add the `isfrozen()` function as a new term entry as part of the tables functions terms. Provide the entry in a markdown file and place under the file path `content/luau/concepts/tables/terms/isfrozen/isfrozen.md`

The entry should have the following:

– An introductory paragraph about what the function is and does: "Returns a **boolean** based on whether the table is in `read-only` mode or not."
– A syntax section with a pseudo code block with an explanation of it.
– An example showing the function in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by 0umkbe** [comment]
I'd like to work on this issue!

**Comment by KTom101** [comment]
@0umkbe You're assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by KTom101** [comment]
@0umkbe That's great! Thank you for deciding to make a contribution.
