### ISSUE TITLE
[Term Entry] Lua Tables pack()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3170]
### Reason/inspiration (optional)

We would like a new term entry for Lua [Tables](https://www.codecademy.com/resources/docs/lua/tables) about the pack() function. The entry should go in a new file in docs/content/lua/concepts/tables/terms/pack/pack.md

The entry should
    - Have an introductory paragraph about what the function is and does: "Packs the provided values into an `Array`."
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the function in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by phuongtrieu97coder** [comment]
I'd like to work on this issue

**Comment by SSwiniarski** [comment]
@phuongtrieu97coder you've already been assigned three issues, which is the maximum we allow people to claim at once. Please submit PRs for the issues you've already been assigned before trying to claim another issue.

**Comment by phuongtrieu97coder** [comment]
@SSwiniarski I'd like to work on this issue
