### ISSUE TITLE
[Term Entry] Lua Tables unpack()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3171]
### Reason/inspiration (optional)

We would like a new term entry for Lua [Tables](https://www.codecademy.com/resources/docs/lua/tables) about the unpack() function. The entry should go in a new file in docs/content/lua/concepts/tables/terms/unpack/unpack.md

The entry should
    - Have an introductory paragraph about what the function is and does: "Unpacks values from the provided table as a tuple."
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the function in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by phuongtrieu97coder** [comment]
I'd like to work on this issue

**Comment by SSwiniarski** [comment]
@phuongtrieu97coder You're assigned, but note we only allow people to claim three open issues at a time. Please complete PRs for the issues you've been assigned before claiming any more issues.
