### ISSUE TITLE
[Term Entry] Lua Tables remove()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3173]
### Reason/inspiration (optional)

We would like a new term entry for Lua [Tables](https://www.codecademy.com/resources/docs/lua/tables) about the remove() function. The entry should go in a new file in docs/content/lua/concepts/tables/terms/remove/remove.md

The entry should
    - Have an introductory paragraph about what the function is and does: "Removes the value of the specified index and clears the index from the Array."
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the function in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by jamalabd** [comment]
@codecademy-docs Hey I would like to pick up this issue.

**Comment by SSwiniarski** [comment]
@jamalabd You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by jamalabd** [comment]
Thanks! Yes, this is my first time contributing. I saw the docs mentioned on the Codecademy website and figured it would be a good chance to improve my skills.

**Comment by SSwiniarski** [comment]
@jamalabd It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by jamalabd** [comment]
@SSwiniarski  Thank you, I have recently created a PR for this.
