### ISSUE TITLE
[Term Entry] Lua Tables sort()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3174]
### Reason/inspiration (optional)

We would like a new term entry for Lua [Tables](https://www.codecademy.com/resources/docs/lua/tables) about the sort() function. The entry should go in a new file in docs/content/lua/concepts/tables/terms/sort/sort.md

The entry should
    - Have an introductory paragraph about what the function is and does: "Compares each Index/Value pair within the provided `Array` using the specified comparison function. The comparison function must return `true` or `false`, ideally, by comparing values with a `>` or `<` **operator."
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the function in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by ShatilKhan** [comment]
Hey @SSwiniarski,  I'd like to take this on. I've done my previous docs contribution a few days ago.

**Comment by SSwiniarski** [comment]
@ShatilKhan you're assigned!

**Comment by ShatilKhan** [comment]
Please review the PR & let me know about any changes.
