### ISSUE TITLE
[Edit] HTML Add Media: Elements

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3178]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to make an edit for HTML Elements. The entry should go in the existing file in docs/content/html/concepts/elements/elements.md

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Bear in mind:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media should accurately represent the existing content and fit in-line.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by ChristinBergmann** [comment]
contributing to this issue for codecademy learning process

**Comment by yangc95** [comment]
@ChristinBergmann You're assigned! You can check out the [Contribution Guide](<https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md>) for additional information on contributing. 
 

See [Content Standards](<https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md>) for an overview of styling tips that the [Style Guide](<https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md>) covers in detail. 
 

After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by SSwiniarski** [comment]
@ChristinBergmann It's been two weeks. Are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@ChristinBergmann I am unassigning this due to inactivity.

**Comment by arun-sagar-s-a** [comment]
@SSwiniarski Hi, I can work on this.

**Comment by arun-sagar-s-a** [comment]
I would greatly appreciate, if someone can help me understand, how exactly is. 
https://www.codecademy.com/resources/docs/html/elements/col
and
https://raw.githubusercontent.com/Codecademy/docs/main/media/rendered-col-tag.png
will work.

**Comment by arun-sagar-s-a** [comment]
https://github.com/Codecademy/docs/pull/3484

**Comment by arun-sagar-s-a** [comment]
## Highlight
In case anyone faced something similar 👇🏼 
### Error: Cannot find module 'prettier' from 'Yourpath/Codecademy/docs'
make sure to **install** the prettier package by opening your terminal in your project's **root directory** and running the following command: `npm install --save-dev prettier.` 😄

**Comment by Arv4ix** [comment]
@yangc95 I am interested in taking this issue on

**Comment by SSwiniarski** [comment]
@Arv4ix this issue has already been assigned and there is a PR submitted for it. You need to find/wait for an unclaimed issue.

**Comment by yangc95** [comment]
> ## Highlight
> In case anyone faced something similar 👇🏼
> 
> ### Error: Cannot find module 'prettier' from 'Yourpath/Codecademy/docs'
> make sure to **install** the prettier package by opening your terminal in your project's **root directory** and running the following command: `npm install --save-dev prettier.` 😄

@arun-sagar-s-a this is great! I suggest posting this here: https://github.com/Codecademy/docs/discussions/categories/q-a

You can create a new discussion and then answer it with your solution

**Comment by SSwiniarski** [comment]
@arun-sagar-s-a I unassigned this issue because the PR did not address it.

**Comment by cjparsonson** [comment]
I'd like to take on this issue as my first contribution, if you're still looking to assign it?

**Comment by SSwiniarski** [comment]
@cjparsonson You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by cjparsonson** [comment]
@SSwiniarski thank you very much, I'll take a look through and start working.

I actually found the repo through the Codecademy Git course, I'm a student with ITOnlineLearning which uses Codecademy as it's platform.

**Comment by cjparsonson** [comment]
@SSwiniarski 

I thought it might be a good idea to check in with you to see if you can give me an example of what you're looking for.

I did see that a previous pull request was rejected, and an example given for the html/iframes md file. However in this case the image helps to explain a concept which could be difficult to visualize purely through HTML. However for elements, the code markup in markdown does a great job. Would you like a small picture showing the end result (ie what the page looks like in the browser, this might explain attributes) or an image of elements in a code editor?

**Comment by arun-sagar-s-a** [comment]
![image](https://github.com/Codecademy/docs/assets/51088722/50ec042c-87ae-468d-9b1f-0f265afec3ca)

@SSwiniarski doesn't this picture (which is what the page looks like in a browser) along with the explanation in my PR help understand?

**Comment by SSwiniarski** [comment]
@arun-sagar-s-a You did not address this issue. You added your own term entry, which is not what this issue was asking for. We're reviewing your PR without regard to this issue, so just look at the comments on your PR and address them there.

**Comment by arun-sagar-s-a** [comment]
@SSwiniarski  sure will address the comment, 
If I haven’t mistaken I added my own entry because the entry col doesn’t exist to just add media and the description did mention “The entry should go in the existing file in docs/content/html/concepts/elements/elements.md” I just chose to add it as it would be easier to do the whole thing.

**Comment by cjparsonson** [comment]
Just submitted a pull request.

Happy to make any changes needed, please just let me know when you can.
