### ISSUE TITLE
[Edit] HTML Add Media: File Paths

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3181]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to make an edit for HTML File Paths. The entry should go in the existing file in docs/content/html/concepts/file-paths/file-paths.md

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Bear in mind:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media should accurately represent the existing content and fit in-line.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by bstout1** [comment]
I will work on this issue!

**Comment by SSwiniarski** [comment]
@bstout1 It's been two weeks. Are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by kkkeevvvin** [comment]
Hello everyone
I'm new to here, and I would like to work on this issue.
BUT, I couldn't find anything I can do in the given path in description, everything seems good...
Could somebody help me? thx a ton.

**Comment by SSwiniarski** [comment]
@bstout1 You've been unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@kkkeevvvin, you're assigned. The goal is to provide an illustrative image for the entry.

**Comment by kkkeevvvin** [comment]
#3483

**Comment by SSwiniarski** [comment]
@kkkeevvvin It's been two weeks, are you still working on this issue? Note that in a week this will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
Unassigned because PR did not address the issue.

**Comment by javastudent2133** [comment]
Hi, Can I work on this? 
I am a Codecademy student and would like to help in my understanding of git and github.

**Comment by SSwiniarski** [comment]
@javastudent2133 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by javastudent2133** [comment]
Thank you for the opportunity. I came across this repo while completing a codecademy course on git/GitHub. This is seemed like a good opportunity to be a contributor and learn about about git.

**Comment by SSwiniarski** [comment]
@javastudent2133 It's been two weeks, are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@javastudent2133 I am unassigning this due to inactivity.

**Comment by DharaniThangavel97** [comment]
I am new to this , and I came to known about this through a codecademy course named Git and GitHub . Now I am interested to take this issue.

**Comment by SSwiniarski** [comment]
@DharaniThangavel97 it's been two weeks. Are you still working on this issue? In another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@DharaniThangavel97 this is being unassigned due to inactivity.

**Comment by nicky-diaz** [comment]
@SSwiniarski I am interested in taking this issue on, I am doing this as part of a codeacademy course, is there any clarification you can give me about this problem? what about the file paths need to be changed? Thanks!

**Comment by SSwiniarski** [comment]
@nicky-diaz you're assigned. The issue is to add an illustrative image or images to the entry, reflecting the content.

**Comment by Sowens2007** [comment]
@SSwiniarski  Hi there, I am a Codecademy student looking for my first project/issue. I am currently on the Git/GitHub course and it says I need to find an issue from Docs to contribute to. So far, I have only been taught html, css, and Markdown. There are not very many issues available currently using html; the majority are for Dart and Java currently and I do not understand them enough to contribute. 

I know that this is assigned, however has it been completed? Please let me know if I can take this one over. Thank you.

**Comment by SSwiniarski** [comment]
@Sowens2007, this is assigned an there is a PR open for it. Please look for an unclaimed issue,
