### ISSUE TITLE
[Concept Entry] Luau: Conditionals

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#3205]
### Reason/inspiration (optional)

We want a new concept entry for [Luau](https://www.codecademy.com/resources/docs/luau) about Conditionals.
The file should be located at `content/luau/concepts/conditionals/conditionals.md`

The entry should:

- Describe what conditionals are.
- Have a section the syntax of `if`, `else`, `elseif` statements.
- Provide code examples for each.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by noahpgordon** [comment]
I'll do this.

**Comment by SSwiniarski** [comment]
@noahpgordon, You're assigned!
