### ISSUE TITLE
[Concept Entry] Luau: Data Types

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#3206]
### Reason/inspiration (optional)

We want a new concept entry for [Luau](https://www.codecademy.com/resources/docs/luau) about Data Types.
The file should be located at `content/luau/concepts/data-types/data-types.md`

The entry should:

- Describe what data types are and how Luau uses them.
- Describe the basic data types.
- Describe how Luau handles type conversion.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by smolnaim** [comment]
Hello @SSwiniarski! I would like to take this issue on. Let me know, thanks!

**Comment by SSwiniarski** [comment]
@smolnaim You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by smolnaim** [comment]
@SSwiniarski Thank you! I appreciate the links too. Yes, it's my first time contributing. I've just finished Codecademy's Git course and contributing is part of the final project. I'm very excited, so thanks again!

**Comment by smolnaim** [comment]
@SSwiniarski I've sent the pull request. Please let me know if it's okay. I would appreciate feedback. Thank you!

**Comment by smolnaim** [comment]
@SSwiniarski [Here](https://github.com/smolnaim/docs/pull/1) it is. Let me know if I put it in the wrong place, it's my first PR so I might have messed up. Thanks!

**Comment by SSwiniarski** [comment]
@smolnaim You created a pull request to your own repository. You need to create a PR for Codecademy/docs.

**Comment by SSwiniarski** [comment]
@smolnaim I'll have to unassign this because no PR has been produces in the Codecademy/docs repository.

**Comment by deenovita** [comment]
Hello, may I get assigned to this issue? Thank you

**Comment by SSwiniarski** [comment]
@deenovita You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!
