### ISSUE TITLE
[Concept Entry] Luau: Iterators

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#3208]
### Reason/inspiration (optional)

We want a new concept entry for [Luau](https://www.codecademy.com/resources/docs/luau) about Iterators.
The file should be located at `content/luau/concepts/iterators/iterators.md`

The entry should:

- Describe what iterators are.
- Have a section the syntax of `while` and `for` loops.
- Give code examples of each type of loop.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by noahpgordon** [comment]
I'll take this.

**Comment by SSwiniarski** [comment]
@noahpgordon, you're assigned.
