### ISSUE TITLE
[Concept Entry] Luau: Operators

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#3209]
### Reason/inspiration (optional)

We want a new concept entry for [Luau](https://www.codecademy.com/resources/docs/luau) about Operators.
The file should be located at `content/luau/concepts/operators/operators.md`

The entry should:

- Describe what operators are.
- Have sections for arithmetic, compound, logical and relational operators.
- List each operator and what it does.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by noahpgordon** [comment]
I'll volunteer for this.

**Comment by KTom101** [comment]
@noahpgordon I've assigned you 🎉 In addition to the documents linked in the description, please also take a look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already.  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.

May I ask how did you find out about contributing to docs?

**Comment by noahpgordon** [comment]
I took the Codecademy course on Git and Github. I'm looking to build a portfolio for applying to technical writing positions and this seems to be a good way to begin doing that.
