### ISSUE TITLE
[Concept Entry] Luau: Strings

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#3210]
### Reason/inspiration (optional)

We want a new concept entry for [Luau](https://www.codecademy.com/resources/docs/luau) about Strings.
The file should be located at `content/luau/concepts/strings/string.md`

The entry should:

- Describe what strings are.
- Have a section on the syntax of declaring strings.
- Describe the concatenation operator and escape characters.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by cslylla** [comment]
I would like to work on this issue.

**Comment by SSwiniarski** [comment]
@cslylla, You're assigned.

**Comment by cslylla** [comment]
@SSwiniarski Do you know if `lua` or `luau` is a [supported code block](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md#supported-codebyte-blocks)?
Or is it okay to use `pseudo`-code blocks throughout the whole entry?

**Comment by SSwiniarski** [comment]
@cslylla I don't believe they are.
