### ISSUE TITLE
[Edit] HTML Add Media: Headings

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3229]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to make an edit for HTML Headings. The entry should go in the existing file in docs/content/html/concepts/headings/headings.md

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Bear in mind:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media should accurately represent the existing content and fit in-line.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
@lewis-pass You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment]
@lewis-pass It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by Satya-Prakash-Dwivedi** [comment]
Hello @SSwiniarski  , is this issue still open.
I would like to work on it

**Comment by SSwiniarski** [comment]
@Satya-Prakash-Dwivedi You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment]
@lewis-pass You've been unassigned due to inactivity.

**Comment by Satya-Prakash-Dwivedi** [comment]
@SSwiniarski  thanks for assigning it to me. 
Yes this is my first time, actually I came across this reop , while searching for good first issue for html.

**Comment by Satya-Prakash-Dwivedi** [comment]
Why I am unable to send a pull request. I have made the required changes in a specific branch, created by me.

**Comment by SSwiniarski** [comment]
@Satya-Prakash-Dwivedi what's happening when you try to create a pull request?

**Comment by SSwiniarski** [comment]
@Satya-Prakash-Dwivedi It's been two weeks. Are you still working on this issue. Note that in another week it will be unassigned due to inactivity.

**Comment by Satya-Prakash-Dwivedi** [comment]
Yes , I am still working.  Now I will make sure I will do it asap.

**Comment by Satya-Prakash-Dwivedi** [comment]
![image](https://github.com/Codecademy/docs/assets/111746703/ee4cbe38-d36e-422f-b598-71a93a67660e)

It shows this everytime when i try to push a branch.

**Comment by Satya-Prakash-Dwivedi** [comment]
@SSwiniarski is the apporach wrong of pushing the branch

**Comment by SSwiniarski** [comment]
@Satya-Prakash-Dwivedi yes. You need to create a [pull request](https://git-scm.com/docs/git-request-pull) so it can be reviewed by maintainers.

**Comment by SSwiniarski** [comment]
@Satya-Prakash-Dwivedi are you having problems producing a pull request?

**Comment by Satya-Prakash-Dwivedi** [comment]
Yes, whenever i try to merge a pr, it shows that permission denied. But i am learning git , on go , so i think i made a wrong pr.

**Comment by SSwiniarski** [comment]
@Satya-Prakash-Dwivedi You can't merge a PR yourself. That is the job of the repo maintainers. You need to create a pull request so we can give feedback on your proposed edits.

**Comment by SSwiniarski** [comment]
@Satya-Prakash-Dwivedi because of a lack of a pull request I am unassigning this issue.

**Comment by OhWilko** [comment]
Hi, I would like to work on this issue. I found this repo through the Codecademy Github course!

**Comment by dancikmad** [comment]
Hi, I am interested on taking this issue. I found out about the repo through the Codecademy platform.

**Comment by bertholo** [comment]
Hello, I'm interested on taking this issue, can you please assign it to me? :)

**Comment by SSwiniarski** [comment]
@OhWilko You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment]
@dancikmad, @bertholo, this was claimed first by @OhWilko
