### ISSUE TITLE
Missing JavaScript code in Codebyte Example in `.concat()` entry

### ISSUE THREAD

**Issue by EugeneGohh** [Codecademy/docs#323]
## Description
After refreshing my tab multiple times & tried it in my phone, I can say this is a bug in the Codebyte Example in `.concat()` entry. The following code presented in [`.concat()` entry](https://www.codecademy.com/resources/docs/javascript/arrays/concat?utm_source=facebook&utm_medium=organic-social&utm_campaign=Docs&utm_content=fb_10_06_21_concat_doc&fbclid=IwAR1pwqZ_tswuELP9yDAPJPhQNyVOie6ZgR-W_AFjuocg2XZpitGx2wGwqGo) is the following:

```
const balls1 = [`⚽`, `���8���<$��Ӱ�6��7B&��3"��	���	>A�����~	`];

const balls = balls1.concat(balls2);

console.log(balls);
```

After running the piece of code, it'll result in an error. Here is a [link](https://github.com/Codecademy/docs/blob/main/content/javascript/concepts/arrays/terms/concat/concat.md) to where the entry is located in the Codecademy Docs repository.

## Type of Bug Request

- Typo and/or bug within one or more existing entries.

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [ ] Assignee is added

**Comment by sonnynomnom** [comment]
Updated!
