### ISSUE TITLE
[Edit] HTML Add Media: Quotations

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3232]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to make an edit for HTML Quotations. The entry should go in the existing file in docs/content/html/concepts/quotations/quotations.md

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Bear in mind:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media should accurately represent the existing content and fit in-line.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by maxx-l** [comment]
Hi, I am interest to work on this issue but unsure about what it's expected.  Do you want me to add more example of the used of links? or a image to illustrate a previous written example? is there a page with a example?

**Comment by MartynaBee** [comment]
Can i please be assigned this?

**Comment by douglas-narcizo** [comment]
If you need someone else to help on this, you can count on me!

**Comment by SSwiniarski** [comment]
@sanjay78632, @MartynaBee You need to wait to be officially assigned an issue before writing a PR. This is to prevent exactly what happened here, two people trying to write the same issue. I closed the first issue because @sanjay78632 did not even comment asking to be assigned. I am assigning @MartynaBee, but I note that the PR submitted was not exactly what the issue was requiring. Please review the comments on the PR and rewrite it accordingly.

**Comment by SSwiniarski** [comment]
> If you need someone else to help on this, you can count on me. Found some typos on the article too!

@douglas-narcizo This issue has been claimed, but feel free to draft a PR to fix any typos. Those are always welcome.

**Comment by douglas-narcizo** [comment]
> > If you need someone else to help on this, you can count on me. Found some typos on the article too!
> 
> @douglas-narcizo This issue has been claimed, but feel free to draft a PR to fix any typos. Those are always welcome.

Ok, I'll wait for the @MartynaBee  's work to get done, and if the typos were still there, I'll fix them.
For now, I'm looking for some other issues so I can proceed with my homework.

**Comment by MartynaBee** [comment]
@SSwiniarski I have attempted to update, hopefully with what was requested. Please let me know if it needs further correction!
