### ISSUE TITLE
[Term Entry] Python Strings .encode()

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#3272]
### Reason/inspiration (optional)

We would like a new term entry on the `.encode()` method for Python: [Strings](https://www.codecademy.com/resources/docs/python/strings). The entry should go in a new file under `docs/content/python/concepts/strings/terms/encode/encode.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```py `code snippet.
- A “Codebyte Example” section with a ` ```codebyte/python ` snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by eliseetal** [comment]
Please may I take this one?
Thanks!

**Comment by KTom101** [comment]
@eliseetal You're assigned 🎉  In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by SSwiniarski** [comment]
@eliseetal It's been over two weeks, are you still working on this entry? Note in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@eliseetal This issue has been unassigned due to inactivity.

**Comment by reganmarie** [comment]
Could I be assigned to this issue?

**Comment by SSwiniarski** [comment]
@reganmarie You're assigned.

**Comment by reganmarie** [comment]
Thank you @SSwiniarski! 😊
