### ISSUE TITLE
[Term Entry] Python Strings .isalnum()

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#3274]
### Reason/inspiration (optional)

We would like a new term entry on the `.isalnum()` method for Python: [Strings](https://www.codecademy.com/resources/docs/python/strings). The entry should go in a new file under `docs/content/python/concepts/strings/terms/isalnum/isalnum.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```py `code snippet.
- A “Codebyte Example” section with a ` ```codebyte/python ` snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by SSwiniarski** [comment]
@siam1113 please in the future wait to be officially assigned to an issue before writing a PR. We've had situations where we've had to close someone's PR because they never actually claimed an issue, and someone else subsequently claimed the issue.

**Comment by siam1113** [comment]
> @siam1113 please in the future wait to be officially assigned to an issue before writing a PR. We've had situations where we've had to close someone's PR because they never actually claimed an issue, and someone else subsequently claimed the issue.

Sorry for that. Definitely I will keep this in mind going forward.
