### ISSUE TITLE
[Term Entry] Python Strings .ljust()

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#3284]
### Reason/inspiration (optional)

We would like a new term entry on the `.ljust()` method for Python: [Strings](https://www.codecademy.com/resources/docs/python/strings). The entry should go in a new file under `docs/content/python/concepts/strings/terms/ljust/ljust.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```py `code snippet.
- A “Codebyte Example” section with a ` ```codebyte/python ` snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by LucianoDeben** [comment]
Hi, Can I be assigned to this issue?

**Comment by KTom101** [comment]
@LucianoDeben You're assigned 🎉  In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by caupolicandiaz** [comment]
I've reopened this issue to due to lack of progress by the previous contributor

**Comment by laisvigas** [comment]
@caupolicandiaz, If possible, I would like to be assigned to this issue as well.

**Comment by AfiyaBanu** [comment]
@caupolicandiaz  I am interested in taking this issue on, I got this doc through my friend

**Comment by AfiyaBanu** [comment]
@caupolicandiaz I am interested in taking this issue on, I got this doc through my friend

**Comment by caupolicandiaz** [comment]
> @caupolicandiaz, If possible, I would like to be assigned to this issue as well.

I'm going to assign this another contributor since you currently have several issues in process. We generally don't assign more than 3 to a contributor at a time

**Comment by caupolicandiaz** [comment]
> @caupolicandiaz I am interested in taking this issue on, I got this doc through my friend

You've been assigned. Let us know if you have any questions. Thanks

**Comment by Atharva1723** [comment]
Can you assign this issue to me as the current assignee is offline more than a week ?

**Comment by SSwiniarski** [comment]
@Atharva1723 This issue is currently assigned and a PR has already been submitted for it.

**Comment by caupolicandiaz** [comment]
This issue has been reopened due to lack of progress by the previous contributor.

**Comment by Atharva1723** [comment]
> This issue has been reopened due to lack of progress by the previous contributor.
I would like to work on the issue .Can I be assigned

**Comment by SSwiniarski** [comment]
@Atharva1723, you're assigned.
