### ISSUE TITLE
[Edit] HTML Add Media: Tables

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#3287]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to make an edit for HTML Tables. The entry should go in the existing file in docs/content/html/concepts/tables/tables.md

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Bear in mind:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media should accurately represent the existing content and fit in-line.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by TadasRuzga** [comment]
Hi, can I be assigned to this

**Comment by CBID2** [comment]
I'm interested in doing this issue.

**Comment by Moddinu** [comment]
I would like to work on this issue , to add some images to the markdown content.

**Comment by yangc95** [comment]
@Moddinu You're assigned! You can check out the [Contribution Guide](<https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md>) for additional information on contributing. 
 
See [Content Standards](<https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md>) for an overview of styling tips that the [Style Guide](<https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md>) covers in detail. 
 
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving. 
 
What brought you to Docs?

**Comment by Moddinu** [comment]
The git code academy course :)

**Comment by ndumidoescode** [comment]
I would like to be assigned to this issue for the Kanban Projects.

**Comment by SSwiniarski** [comment]
@ndumidoescode this is already assigned and a PR has been submitted for it.

**Comment by Moddinu** [comment]
Ok, thanks for the update.

**Comment by ndumidoescode** [comment]
@SSwiniarski understood, thank you.

**Comment by SSwiniarski** [comment]
Unassigning this issue as PR was withdrawn.

**Comment by SSwiniarski** [comment]
@ndumidoescode are you still interested in claiming this PR?

**Comment by ndumidoescode** [comment]
Thank you @SSwiniarski, but I'm currently assigned to another issue at the moment.

**Comment by thambiduraic** [comment]
please assign to the task for me.

**Comment by SSwiniarski** [comment]
@thambiduraic You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by thambiduraic** [comment]
contribution guide is not properly open . It's raise an 404 error message, so please check and solve the error.
![Screenshot (220)](https://github.com/Codecademy/docs/assets/74646258/a799fac6-ed58-4428-9232-f294479e131c)

**Comment by SSwiniarski** [comment]
@thambiduraic Heres the correct link: [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md)

**Comment by SSwiniarski** [comment]
@thambiduraic It's been two weeks. Are you still working on this entry. Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@thambiduraic I am unassigning this due to inactivity.

**Comment by Brag2gr8** [comment]
kindly assign to me

**Comment by SSwiniarski** [comment]
@Brag2gr8 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!
