### ISSUE TITLE
[Edit] HTML Add Media: Videos

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#3288]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to make an edit for HTML Videos. The entry should go in the existing file in docs/content/html/concepts/videos/videos.md

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Bear in mind:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media should accurately represent the existing content and fit in-line.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by rusliabdulgani** [comment]
i'm interisting to this issue

**Comment by rusliabdulgani** [comment]
@christian-dinh i'm interisting to this issue

**Comment by KTom101** [comment]
@rusliabdulgani You're assigned 🎉  In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by rusliabdulgani** [comment]
Thank you @KTom101 , yet this is my first contribution..

**Comment by rusliabdulgani** [comment]
Hi @KTom101 what should i do now? the pull request look like already accepted, could you please follow up ?

**Comment by KTom101** [comment]
@rusliabdulgani As mentioned by @SSwiniarski you are supposed to wait for a second review. There is a high volume of PRs at this time so your patience is critical. 

Also, it looks like you closed out the PR. Did you do this by accident? The PR needs to remain open so that it remains visible under the pull request tab.

**Comment by rusliabdulgani** [comment]
i think i had a wrong steps before so i close the PR, but actually i create new PR after that for the same issue.. 
ok well noted

**Comment by SSwiniarski** [comment]
@rusliabdulgani I do not see an open PR for this issue. If there is one, could you link to it? If not, I'm going to unassign this issue so someone else can work on it.

**Comment by SSwiniarski** [comment]
@rusliabdulgani due to a lack of a PR I am unassigning this due to inactivity.

**Comment by SSwiniarski** [comment]
@tf-ahunter You should _not_ submit PRs before you are officially assigned an issue. This has caused situations in the past where we've had to reject someone's work. In this case I'll assign you because no one else is involved in this issue.

**Comment by SSwiniarski** [comment]
@tf-ahunter Unassigned because the PR did not address the issue.

**Comment by DakuwoN** [comment]
I will gladly take this one if you could add the hacktoberfest label? I am 1/4 trying to get some more :D

**Comment by SSwiniarski** [comment]
@DakuwoN You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment]
@DakuwoN I added the hactoberfest label, but it's unlikely that the PR will be reviewed and merged in two days.

**Comment by DakuwoN** [comment]
Hey thanks @SSwiniarski I figured I'd try anyhow, I am trying the best I can before the last day! :D Thank you, so this issue seems to me that we need to embed a video on this page?

**Comment by SSwiniarski** [comment]
@DakuwoN I think we'd prefer just an image.

**Comment by DakuwoN** [comment]
Ok @SSwiniarski so I am not sure if I am on the same page as the issue. We want to insert an image onto this file? But where at? What should the image display? I understand the file type. "Bear in mind:

Add supplemental media (preferred .png or .gif, <1MB).
Media should accurately represent the existing content and fit in-line."

Represent the existing content? Basically, just kind of embed a gif file, that gives the user an example of what it would look like? I would assume this file could go beneath the example heading?

**Comment by SSwiniarski** [comment]
@DakuwoN Yes, give the reader an example of what it would look like.
