### ISSUE TITLE
[Edit] HTML Add Media: class

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#3289]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like an edit a term within the HTML Attributes entry. The entry lives in docs/content/html/concepts/attributes/terms/class.md

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Bear in mind:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media should accurately represent the existing content and fit in-line.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by douglas-narcizo** [comment]
Hi folks! If possible, I would like to be assigned to this issue.

**Comment by SSwiniarski** [comment]
@douglas-narcizo You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by douglas-narcizo** [comment]
Guys, I'm considering on use a window frame on my images, as I think it would look good for the examples.
I will attach it here for evaluation.
Do you think it's a bad idea or go against any styling preference? I didn't find any restrictions on the Styling Guide.
<img width="717" alt="image" src="https://github.com/Codecademy/docs/assets/144618521/a93f4a67-18a9-4c4a-bc25-b0148da89039">

**Comment by SSwiniarski** [comment]
> Guys, I'm considering on use a window frame on my images, as I think it would look good for the examples. I will attach it here for evaluation. Do you think it's a bad idea or go against any styling preference? I didn't find any restrictions on the Styling Guide. <img alt="image" width="717" src="https://user-images.githubusercontent.com/144618521/269075561-a93f4a67-18a9-4c4a-bc25-b0148da89039.png">

@douglas-narcizo I think that would be fine.
