### ISSUE TITLE
[Term Entry] Python Strings .maketrans()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3330]
### Reason/inspiration (optional)

We would like a new term entry on the `.maketrans()` method for Python: [Strings](https://www.codecademy.com/resources/docs/python/strings). The entry should go in a new file under `docs/content/python/concepts/strings/terms/maketrans/maketrans.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```py `code snippet.
- A “Codebyte Example” section with a ` ```codebyte/python ` snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by will-underwood** [comment]
I would like to work on this issue/entry. I found out about contributing to Codecademy Docs through the project in the Learn Git & Github course that I am currently taking on Codecademy. It is my first time contributing to a repository like this outside of the simple Git practice exercises.

I have already worked through the Learn Python 3 unit, but I'm not familiar with this method, so I will need to do some research to understand it and then describe it in my own words.

Thank you.

**Comment by KTom101** [comment]
@will-underwood Thank you for waiting patiently to be assigned. If you haven't already, please make sure you look at the documentation linked in the description and also at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) before you begin your work!

**Comment by SSwiniarski** [comment]
@will-underwood It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@will-underwood This issue has been unassigned due to inactivity.

**Comment by manviii27** [comment]
@SSwiniarski can I work on this issue? Also it'd be great if you could assign the 'hacktoberfest' label to this issue

**Comment by SSwiniarski** [comment]
@manviii27 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!
