### ISSUE TITLE
[Term Entry] Python Strings .rindex()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3332]
### Reason/inspiration (optional)

We would like a new term entry on the `.rindex()` method for Python: [Strings](https://www.codecademy.com/resources/docs/python/strings). The entry should go in a new file under `docs/content/python/concepts/strings/terms/rindex/rindex.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```py `code snippet.
- A “Codebyte Example” section with a ` ```codebyte/python ` snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by deenovita** [comment]
Hello, may I work on this?

**Comment by kom-senapati** [comment]
I would love to work on this issue.

**Comment by KTom101** [comment]
@deenovita Since you asked first, you have been assigned.

**Comment by KTom101** [comment]
@kom-senapati I've assigned this to the first person who asked, please take a look at the other [unassigned issues](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee) to see if there is anything else that interests you.

**Comment by deenovita** [comment]
> @deenovita Since you asked first, you have been assigned.

Thank you!

**Comment by deenovita** [comment]
I have added the term entry. Let me know if there are any changes I need to make. Thank you!

**Comment by SSwiniarski** [comment]
Closing because it was resolved with [3357](https://github.com/Codecademy/docs/pull/3357)
