### ISSUE TITLE
[Concept Entry] SwiftUI Slider

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3334]
### Reason/inspiration (optional)

We would like a new concept entry for SwiftUI about the Slider view. The entry should go in a new file in docs/content/swiftui/concepts/slider/slider.md

The entry should
    - Have an introductory paragraph about the concept.
    - Code block(s) displaying different aspects of the concept.
    - Gif to accompany the code block.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by gracekishino** [comment]
@codecademy-docs please can I work on this?

**Comment by KTom101** [comment]
@gracekishino You're assigned 🎉

**Comment by gracekishino** [comment]
Just updating that I'm still working on this (been a bit ill this week so that's why it's taking a little longer), and hope to create a pull request within the next few days.
