### ISSUE TITLE
[Edit] HTML Add Media: style

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3336]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like an edit a term within the HTML Attributes entry. The entry lives in docs/content/html/concepts/attributes/terms/style.md

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Bear in mind:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media should accurately represent the existing content and fit in-line.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by kitttrick** [comment]
Can I please contribute to this issue?

**Comment by KTom101** [comment]
@kitttrick You're assigned 🎉  In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by SSwiniarski** [comment]
@kitttrick It's been two weeks. Are you still working on this entry. Note that in another week it will be unassigned due to inactivity.

**Comment by kitttrick** [comment]
Apologies! My changes are now waiting for review
