### ISSUE TITLE
[Edit] HTML Add Media: applet

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3337]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like an edit a term within the HTML Elements entry. The entry lives in docs/content/html/concepts/elements/terms/applet.md

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Bear in mind:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media should accurately represent the existing content and fit in-line.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by onanahauwa** [comment]
@codecademy-docs Hi, I would like to work on this as a first issue on codecademy. I'll be waiting for your response. Thank you

**Comment by KTom101** [comment]
@onanahauwa You're assigned 🎉  In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by onanahauwa** [comment]
@KTom101 Hello, and many thanks. Through codecademy.com, I discovered Docs. I'm eager to get started because this is kind of like a project that will help me gain more GitHub experience.

**Comment by SSwiniarski** [comment]
@onanahauwa It's been two weeks. Are you still working ion this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@onanahauwa This issue has been unassigned due to inactivity.

**Comment by TF-PMcardle** [comment]
@codecademy-docs Hi, I would like to work on this as a first issue on codecademy. Thank you

**Comment by SSwiniarski** [comment]
@TF-PMcardle You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@TF-PMcardle It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@TF-PMcardle I am unassigning this due to inactivity.

**Comment by bertholo** [comment]
Hello, i am very interested on taking this issue, can you please assign it to me? :)

**Comment by SSwiniarski** [comment]
@bertholo You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment]
@rajagrol101214 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@rajagrol101214 It's been over two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@rajagrol101214 This is being unassigned due to inactivity.

**Comment by Blanco248** [comment]
@SSwiniarski I will gladly take this issue over!

**Comment by evadome** [comment]
Hello! I would like to work on this one as my first issue on codecademy. 
Thank you

**Comment by SSwiniarski** [comment]
@evadome, @Blanco248 is already assigned this issue.

**Comment by SSwiniarski** [comment]
@Blanco248 It's been two weeks. Are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@Blanco248 This is being unassigned due to inactivity.

**Comment by fa125had** [comment]
Hello, 
I have an open pr on another topic, waiting for feedback, but if it's ok i would like to work on this issue too.
thanks.

**Comment by fa125had** [comment]
Hello, 
I have still one open PR on another topic waiting for the feedback/merge,
but if it's possible I like to work on this issue too.
thanks.

**Comment by SSwiniarski** [comment]
@fa125had You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by fa125had** [comment]
@SSwiniarski thank you

**Comment by ismailkatilo** [comment]
@codecademy-docs I'd like to work on this issue, Please assign it to me

**Comment by ismailkatilo** [comment]
@SSwiniarski Could you assign this to me please?
