### ISSUE TITLE
[Edit] C++: Defining Operators for your custom class

### ISSUE THREAD

**Issue by hazeltonbw** [Codecademy/docs#3342]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

I would like to add content for defining your own operators in C++. 
This is useful as it makes working with your own custom classes much easier. 

Unlike other programming languages, in C++ you can't just "print" a user defined class unless you create a print function. 
However, in C++, you can overload an operator to do just that! 

```c++
#include <iostream>
using namespace std;
struct Person {
    string name;
    string address;
    string SSN;
};

// Custom operator for struct Person that prints a `Person`s information
ostream& operator<<(ostream &output_stream, const Person& person) {
    return output_stream << "Name: " << person.name << "\t" << 
"Address: " << person.address << "\t" << "SSN: " << person.SSN;
}
```

Here we are returning a reference to an **ostream** using the **ostream** from the `cout` statement.
i.e. `cout << p;`
`cout` is an `ostream` object, `p` is a `Person` object, and we use the overloaded operator `<<` 
It may help to think of the function call like this:
`ostream& operator<<(ostream &to_the_left_of_operator, const Person& to_the_right_of_operator) {// code }`

With the custom operator defined, printing a Person object is a lot more intuitive. 

```c++
Person p = {"Brandon", "123 Fake Street", "123456789"};
cout << p << endl; // calls overloaded operator function above
// Name: Brandon   Address: 123 Fake Street        SSN: 123456789
```

Creating a new object of type Person using user input is just as easy now as well.

```c++
istream& operator>>(istream& input_stream, Person& person) {
    cout << "Please enter a name for the new person:\n";
    getline(input_stream, person.name);
    cout << "Please enter an address for the new person:\n";
    getline(input_stream, person.address);
    cout << "Please enter a SSN for the new person:\n";
    getline(input_stream, person.SSN);
    return input_stream;
}

Person p;
cin >> p; // calls overloaded operator function above
```

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by KTom101** [comment]
@hazeltonbw We already have an entry on overloading functions and operators [here](https://www.codecademy.com/resources/docs/cpp/overloading) were you looking to edit that?

**Comment by shivend7195** [comment]
I want to work on this issue 'typo' Can you guide me on how should I approach this and assign me? @hazeltonbw 
As I am a beginner I think can read the whole and check if there is any typo.

**Comment by shivend7195** [comment]
update: wants to work and started looking for typos but still haven't found the issue for which tagged for

**Comment by hazeltonbw** [comment]
> @hazeltonbw We already have an entry on overloading functions and operators [here](https://www.codecademy.com/resources/docs/cpp/overloading) were you looking to edit that?

I see! Sorry I must have missed it when I originally was considering adding this.
I feel like adding the custom print and user input overload would be a nice touch :) 
Let me know what you think! 

Thanks
Brandon

**Comment by hazeltonbw** [comment]
> update: wants to work and started looking for typos but still haven't found the issue for which tagged for

This tag must've been automatically added when I created the issue and doesn't pertain to any issue! 
Sorry 'bout that.

**Comment by shivend7195** [comment]
It's totally alright :)
 and Thanks for writing back. 
 Please do consider me if in the future anything beginner-friendly

**Comment by KTom101** [comment]
@hazeltonbw You can add those in as additional examples.
