### ISSUE TITLE
[Edit] SQL Commands: ORDER BY

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#3346]
### Type of Edit (select all that apply)

Clarify unclear content and/or terms

### Description (optional)

This edit is for the SQL Commands: [ORDER BY](https://www.codecademy.com/resources/docs/sql/commands/order-by) entry located under the file path: `docs/content/sql/concepts/commands/terms/order-by`

Edit the current syntax/pseudocode section so that there is mention that multiple columns can be specified (by separating with a comma) when sorting. 

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by kevuschka** [comment]
I could do that.

**Comment by KTom101** [comment]
@kevuschka Next time please wait until you're assigned first before working on an issue.
