### ISSUE TITLE
[Entry Request] General: Unit Testing

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#335]
## Description

Write a "Unit Testing" entry in the General topic.

General topic: https://www.codecademy.com/resources/docs/general

## Type of Entry Request

- One or more new entries/terms requested.

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [ ] Assignee is added

**Comment by Aashishkushwaha** [comment]
Hi @Dusch4593, I want to contribute to this topic, can you assign this to me?

**Comment by Aashishkushwaha** [comment]
Hi @Dusch4593, I've raised the PR ( PR #363 ) which will close this issue. Please review the PR & do the needful. Thanks 👍

**Comment by sonnynomnom** [comment]
Need someone on this Issue again!

**Comment by sonnynomnom** [comment]
Just realized this is a duplicate too. There's another issue on this already. Closing.
