### ISSUE TITLE
🕸️ [Hacktoberfest] Test: 10th Anniversary Livestream 🎃

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#3350]
### Reason/inspiration (optional)

PLEASE DO NOT COMMENT ON THIS THREAD

We would like a new concept entry for General about Hacktoberfest. The entry should go in a new file in `docs/content/general/concepts/hacktoberfest/hacktoberfest.md`

The entry should
    - Have an introductory paragraph about the concept.
    - Internal linking as applicable.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Shiv10122003** [comment]
hello , i want to contribute

**Comment by yangc95** [comment]
@KTom101 Can I be assigned to this issue?
