### ISSUE TITLE
[Edit] UI and UX Design: Double Diamond Diagram - broken link

### ISSUE THREAD

**Issue by llbaker121** [Codecademy/docs#3352]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

There is a broken/incorrect link in the UI and UX Design entry for Double Diamond Diagram.  At the bottom of the entry, the link for  [formalized by the British Design Council](https://www.designcouncil.org.uk/our-work/skills-learning/resources/11-lessons-managing-design-global-brands) is invalid.  

Two possible replacements are:  [designcouncil.org Double Diamond entry](https://www.designcouncil.org.uk/our-resources/the-double-diamond/) or the [designcouncil.org 11 Lessons pdf](https://www.designcouncil.org.uk/fileadmin/uploads/dc/Documents/ElevenLessons_Design_Council%2520%25282%2529.pdf)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by mustangvoyager** [comment]
@mustangvoyager	I would like to take this one on. I’m working through the Learn Git and GitHub course and I think this would be a good one for me to work through the pull request process.  Thank you.

**Comment by KTom101** [comment]
@llbaker121 Were you planning on working on this issue yourself? 

I'm also considering removing the link altogether to avoid having another broken link from a third-party website in the future. @SSwiniarski @yangc95 @caupolicandiaz does one of you have an opinion on this?

**Comment by KTom101** [comment]
@mustangvoyager Since this issue was made by a community member, let's wait to see if they wanted to work on this themselves. If not, I will assign you.

**Comment by mustangvoyager** [comment]
@KTom101	I understand. Thanks for the consideration.

**Comment by mustangvoyager** [comment]
@KTom101	A possible solution would be to include the first link as an overview, and then to add language telling people to click on the 2nd link - the 11 lessons - for a (much) deeper dive.

I was not familiar with the Double Diamond design process model, despite having designed industrial controls and human-machine interfaces earlier in my career. I found this information interesting; perhaps others will as well.

**Comment by llbaker121** [comment]
@KTom101 No, I was not planning on working on this issue.  Feel free to assign it out as needed.
Thanks!

**Comment by JulianAshby** [comment]
Hello, By any chance, would this project still be available to work on.

**Comment by caupolicandiaz** [comment]
@JulianAshby You've been assigned. Let us know if you have any questions.

**Comment by KTom101** [comment]
@caupolicandiaz @JulianAshby Apologies for the confusion but since @mustangvoyager asked first I'm assigning this to them. If for some reason they can't complete it then I will assign this to you.

**Comment by KTom101** [comment]
@mustangvoyager You can proceed with making the correction by just removing the link. We do not want to link out to a third-party website at this time.

**Comment by mustangvoyager** [comment]
Got it. Thanks
