### ISSUE TITLE
[Entry] Subject: Cherry-Pick 

### ISSUE THREAD

**Issue by CBID2** [Codecademy/docs#3359]
## Description
The `cherry-pick` command is something that coding newbies often learn when learning Git. 

## Benefit
Adding this entry to the Git chapter would help these individuals learn how to use Git effectively. 

## Additional information
I'm participating in Hacktoberfest this year, so I would like to work on this entry as one of my four pull requests. 

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by KTom101** [comment]
@CBID2 Did you want to work on this?

**Comment by KTom101** [comment]
@CBID2 You're assigned
