### ISSUE TITLE
[Entry Request] General: Open Source

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#336]
## Description

Write an "Open Source" entry in the General topic.

General topic: https://www.codecademy.com/resources/docs/general

## Type of Entry Request

- One or more new entries/terms requested.

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by Dusch4593** [comment]
Hi @griffincosgrove! Just wanted to check in and ask if you were still working on a PR for this issue?

**Comment by griffincosgrove** [comment]
Ah crap think I wrote something out and forgot to actually PR it. Will post here and you can use whatever you like

**Comment by griffincosgrove** [comment]
@SSwiniarski here is my definition.
'Open Source Software is free software that is licensed under permissive licenses that generally allow for the inspection, modification, and dissemination of the underlying source code, depending on the license. Anyone is able to offer improvements back to the software via a Pull Request. Open Source software is the opposite of proprietary or closed source software such as Microsoft Windows.'
