### ISSUE TITLE
[Term Entry] Python Strings .strip()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3365]
### Reason/inspiration (optional)

We would like a new term entry on the `.strip()` method for Python: [Strings](https://www.codecademy.com/resources/docs/python/strings). The entry should go in a new file under `docs/content/python/concepts/strings/terms/strip/strip.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```py `code snippet.
- A “Codebyte Example” section with a ` ```codebyte/python ` snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by laisvigas** [comment]
Hi, can I work on this issue? Thanks!

**Comment by Peafly78** [comment]
I would like to work on this issue to be able to complete my Codecademy Git and GitHub course. Please assign it to me. Thanks!

**Comment by KTom101** [comment]
@laisvigas Since you asked first, I'm assigning this to you. Please use the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) as well as the documentation linked in the description as resources while creating this entry. 

Is this your first contribution to Codecademy Docs? If so, where did you find out about contributing to Docs?

**Comment by KTom101** [comment]
@Peafly78 I've assigned this to the person who asked first. Assignment is based on first-come-first-served. If you haven't already, please take a look at the other [unassigned issues](https://github.com/Codecademy/docs/issues?page=1&q=is%3Aissue+is%3Aopen+no%3Aassignee).

**Comment by laisvigas** [comment]
@KTom101 Yes, this is my first time contributing to Codecademy Docs. I first learned about the opportunity to contribute when Codecademy posted about it on LinkedIn. I will certainly utilize the Contribution Guide and the documentation linked in the description as valuable resources while creating this entry. Thank you!
