### ISSUE TITLE
[Concept Entry] Rust Variables

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3369]
### Reason/inspiration (optional)

We would like a new concept entry for Rust about Variables. The entry should go in a new file in docs/content/rust/concepts/variables/variables.md

The entry should
    - Have an introductory paragraph about the concept.
    - Code block(s) displaying different aspects of the concept.
    - Gif to accompany the code block.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by moha230** [comment]
Hello @KTom101 can this issue be assigned to me . Thank you

**Comment by KTom101** [comment]
@moha230 You're assigned! 🎉
