### ISSUE TITLE
[Concept Entry] Rust Conditionals

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3370]
### Reason/inspiration (optional)

We would like a new concept entry for Rust about Conditionals. The entry should go in a new file in docs/content/rust/concepts/conditionals/conditionals.md

The entry should
    - Have an introductory paragraph about the concept.
    - Code block(s) displaying different aspects of the concept.
    - Gif to accompany the code block.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by ELAKIYA-SEKAR** [comment]
I want to work on this issue @yangc95 @codecademy-docs

**Comment by KTom101** [comment]
@ELAKIYA-SEKAR  After you make PRs for the issues you're currently assigned to you can be assigned to another issue.

**Comment by Captainnik53** [comment]
@KTom101 Can you please assign this issue to me if it still open?

**Comment by KTom101** [comment]
@Captainnik53 You're assigned
