### ISSUE TITLE
[Concept Entry] Rust Functions

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3371]
### Reason/inspiration (optional)

We would like a new concept entry for Rust about Functions. The entry should go in a new file in docs/content/rust/concepts/functions/functions.md

The entry should
    - Have an introductory paragraph about the concept.
    - Code block(s) displaying different aspects of the concept.
    - Gif to accompany the code block.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by ELAKIYA-SEKAR** [comment]
I want to work on this issue @yangc95

**Comment by KTom101** [comment]
@ELAKIYA-SEKAR Once you make PRs for the issues you're currently assigned to you can be assigned to another issue.

**Comment by vrun1208** [comment]
Hi @yangc95!, If no one is assigned to this issue, I want to work on this one

**Comment by KTom101** [comment]
@vrun1208 You're assigned 🎉  In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by vrun1208** [comment]
Thanks @KTom101 for assigning me! Yes, This is my first contribution to Codecademy docs. Actually I was surfing on opensauced (open source platform provides insights to open source projects) where I found out this repo and I recently started learning Rust so here I am 🚀

**Comment by KTom101** [comment]
@vrun1208 That's great! Thank you for deciding to make a contribution to Codecademy Docs 🚀
