### ISSUE TITLE
[Concept Entry] Rust Comments

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3372]
### Reason/inspiration (optional)

We would like a new concept entry for Rust about Comments. The entry should go in a new file in docs/content/rust/concepts/comments/comments.md

The entry should
    - Have an introductory paragraph about the concept.
    - Code block(s) displaying different aspects of the concept.
    - Gif to accompany the code block.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by codewithfan** [comment]
I would love to tackle this issue!

**Comment by KTom101** [comment]
@codewithfan Yes, it does! Thanks for catching that, you've been assigned.

**Comment by SSwiniarski** [comment]
@stefanintech It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by stefanintech** [comment]
Yes please! Still will work on the issue.

**Comment by SSwiniarski** [comment]
@stefanintech This is being unassigned due to inactivity.

**Comment by manviii27** [comment]
@SSwiniarski can I work on this issue?

**Comment by SanchitMahajan236** [comment]
Can you please assign me this issue ?

**Comment by SSwiniarski** [comment]
@manviii27 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@manviii27 Note that this is your third issue assignment. We don't allow people to claim more than three open issues at a time. Please submit PRs for the issues you've already claimed before asking to claim any more.

**Comment by SSwiniarski** [comment]
@SanchitMahajan236 this has been assigned to @manviii27

**Comment by SSwiniarski** [comment]
@manviii27 It's been two weeks. Are you still working on this issue? Note that in another week this will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@manviii27 This is being unassigned due to inactivity.

**Comment by cdcalderontenorio** [comment]
Hi, may I work on this Concept Entry?

**Comment by SSwiniarski** [comment]
@cdcalderontenorio You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?
