### ISSUE TITLE
[Concept Entry] Rust Data Types

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3373]
### Reason/inspiration (optional)

We would like a new concept entry for Rust about Data Types. The entry should go in a new file in docs/content/rust/concepts/data-types/data-types.md

The entry should
    - Have an introductory paragraph about the concept.
    - Code block(s) displaying different aspects of the concept.
    - Gif to accompany the code block.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by ELAKIYA-SEKAR** [comment]
i want to work on this issue @KTom101

**Comment by KTom101** [comment]
@ELAKIYA-SEKAR You're assigned 🎉  In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by SSwiniarski** [comment]
@ELAKIYA-SEKAR It's been two weeks. Are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@ELAKIYA-SEKAR This is being unassigned due to inactivity.

**Comment by manviii27** [comment]
@SSwiniarski can I work on this issue?

**Comment by SanchitMahajan236** [comment]
Can you please assign me this issue ?

**Comment by SSwiniarski** [comment]
@manviii27 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@SanchitMahajan236 this has been assigned to @manviii27

**Comment by SSwiniarski** [comment]
@manviii27 It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@manviii27 This is being unassigned due to inactivity.

**Comment by DharaniThangavel97** [comment]
Am a new to this codecademy and I came to know about this in the course Git and Github . I am interested to solve this issue.

**Comment by moha230** [comment]
@SSwiniarski can this issue be assigned to me

**Comment by ishg-153** [comment]
Closing this Issue so that it can be freshly opened.
