### ISSUE TITLE
[Concept Entry] Rust Loops

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3374]
### Reason/inspiration (optional)

We would like a new concept entry for Rust about Loops. The entry should go in a new file in docs/content/rust/concepts/loops/loops.md

The entry should
    - Have an introductory paragraph about the concept.
    - Code block(s) displaying different aspects of the concept.
    - Gif to accompany the code block.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Captainnik53** [comment]
@KTom101 Can you please assign this issue to me?

**Comment by KTom101** [comment]
@Captainnik53 You're assigned 🎉  In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by Captainnik53** [comment]
@KTom101 Thank you for assigning me this issue. I will try my best to provide a quality contribution :)

Yes, it's my first contribution to this repo. I found out about the docs while scrolling through list of repos on hacktoberfest website.

**Comment by KTom101** [comment]
@Captainnik53 Cool! Thank you for deciding to make a contribution to Codecademy Docs 🚀

**Comment by SSwiniarski** [comment]
@Captainnik53 It's been over two weeks, if we don't see a PR in the next few days this will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@Captainnik53 I am unassigning this due to inactivity.

**Comment by moha230** [comment]
can this be assigned to me

**Comment by SSwiniarski** [comment]
@moha230 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?
