### ISSUE TITLE
[Concept Entry] Rust Structs

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3375]
### Reason/inspiration (optional)

We would like a new concept entry for Rust about Structs. The entry should go in a new file in docs/content/rust/concepts/structs/structs.md

The entry should
    - Have an introductory paragraph about the concept.
    - Code block(s) displaying different aspects of the concept.
    - Gif to accompany the code block.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by bharathgaddam1712** [comment]
In the rust section content file is not added.

**Comment by KTom101** [comment]
@bharathgaddam1712 This is because the Rust topic is new and there are no concept entries yet. A "concepts" folder will need to be added. Did you want to work on this?

**Comment by bharathgaddam1712** [comment]
YES!! I want to work on this

**Comment by KTom101** [comment]
@bharathgaddam1712 You're assigned 🎉  In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.

How did you find out about being able to contribute to Codecademy Docs?

**Comment by bharathgaddam1712** [comment]
![image](https://github.com/Codecademy/docs/assets/134089638/20abea18-468e-40bf-aac3-4bfce5418741)
This image shows the contribution made.Please merge my pull request under Hacktoberfest if it added some value to your repo.
