### ISSUE TITLE
[Concept Entry] Rust Collections

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3376]
### Reason/inspiration (optional)

We would like a new concept entry for Rust about Collections. The entry should go in a new file in docs/content/rust/concepts/collections/collections.md

The entry should
    - Have an introductory paragraph about the concept.
    - Code block(s) displaying different aspects of the concept.
    - Gif to accompany the code block.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by ELAKIYA-SEKAR** [comment]
I want to work on this issue @KTom101

**Comment by KTom101** [comment]
@ELAKIYA-SEKAR This will be your third assignment! Please make sure you open PRs for the issues you're assigned to before requesting to be assigned to another issue. 😊

**Comment by SSwiniarski** [comment]
@ELAKIYA-SEKAR  It's been two weeks. Are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@ELAKIYA-SEKAR This is being unassigned due to inactivity.

**Comment by SanchitMahajan236** [comment]
I would love to contribute to this issue. Can you please assign me this issue ?

**Comment by SSwiniarski** [comment]
@SanchitMahajan236 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@SanchitMahajan236 It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by SanchitMahajan236** [comment]
@SSwiniarski I was busy with my exams, so will be generating a PR in one or two days.

**Comment by SSwiniarski** [comment]
@SanchitMahajan236 This is being unassigned due to inactivity.

**Comment by SHARATH-20-07-2002** [comment]
@jrood I'm Interested in this Assign me.

**Comment by manojritgithub** [comment]
@jrood i am interested in this issue, i found this Docs randomly.

**Comment by SSwiniarski** [comment]
@SHARATH-20-07-2002 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@manojritgithub, @SHARATH-20-07-2002 claimed this before you.

**Comment by SSwiniarski** [comment]
@SHARATH-20-07-2002 It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by moha230** [comment]
Can I be assigned this issue

**Comment by SSwiniarski** [comment]
@moha230 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by moha230** [comment]
Hi @SSwiniarski request for more time I got sick if you could add more time so I can complete the entry. Thank you

**Comment by SSwiniarski** [comment]
@moha230 we normally give three weeks, but we can give you another week.
