### ISSUE TITLE
[Concept Entry] Rust Operators

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3377]
### Reason/inspiration (optional)

We would like a new concept entry for Rust about Operators. The entry should go in a new file in docs/content/rust/concepts/operators/operators.md

The entry should
    - Have an introductory paragraph about the concept.
    - Code block(s) displaying different aspects of the concept.
    - Gif to accompany the code block.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by ELAKIYA-SEKAR** [comment]
I want to work on this issue @KTom101 @codecademy-docs

**Comment by KTom101** [comment]
@ELAKIYA-SEKAR You're assigned.

**Comment by SSwiniarski** [comment]
@ELAKIYA-SEKAR  It's been two weeks. Are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by manviii27** [comment]
@SSwiniarski can I work on this issue?

**Comment by SanchitMahajan236** [comment]
Can you please assign me this issue ? I would love to contribute

**Comment by SSwiniarski** [comment]
@manviii27 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@moha230, @SanchitMahajan236 this has been assigned to @manviii27

**Comment by SSwiniarski** [comment]
@manviii27 It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@manviii27 This is being unassigned due to inactivity.

**Comment by dharniel45** [comment]
can I work on this issue @codecademy-docs @SSwiniarski

**Comment by SSwiniarski** [comment]
@dharniel45 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment]
@dharniel45 it's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by dharniel45** [comment]
Yes @SSwiniarski would complete it today

**Comment by SSwiniarski** [comment]
@dharniel45 This is being unassigned due to inactivity.

**Comment by dharniel45** [comment]
Hello @SSwiniarski could you please reassign, the week is not over yet. so I can make the submission. I am finally done

**Comment by SSwiniarski** [comment]
@dharniel45 I've reassigned you. Please submit a PR within the next two days.

**Comment by SSwiniarski** [comment]
@dharniel45 Unassigning you because no PR was forthcoming.

**Comment by juliajobczyk** [comment]
Hi can I please be assigned? This would be my first issue.

**Comment by SSwiniarski** [comment]
@juliajobczyk You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@juliajobczyk Ok, I'll unassign you.

**Comment by nithin-sudarsan** [comment]
Hey @SSwiniarski @codecademy-docs Can this issue be assigned to me? I'd like to work on it!

**Comment by dancikmad** [comment]
Hi, I can see that this issue has been here for a while. I been assigned 2 issues this week, 1 is under the review in my PR now and for another one I am about to make a PR this week. 

I can take this issue if it's still available and clear out this overdue deadline.

**Comment by letsbuildanything** [comment]
Hey @dancikmad, @nithin-sudarsan,
Are either of you still interested in working on this issue?

**Comment by Johnnie-kay** [comment]
Hello @letsbuildanything, I'm interested in working on this concept entry if the other writers are not active at the moment.

**Comment by ishg-153** [comment]
@Johnnie-kay Are you still interested in working on this issue?

**Comment by Johnnie-kay** [comment]
Hello, @ishg-153  I am still very interested to get assigned on this issue, thanks.

**Comment by ishg-153** [comment]
@Johnnie-kay You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

**Comment by Johnnie-kay** [comment]
@ishg-153 I have created a PR for this issue #3377, Please review it, so i can make the required corrections an dclose this issue.
