### ISSUE TITLE
[Entry Request] General: Modulo

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#338]
## Description

Write a "Modulo" entry in the General topic.

General topic: https://www.codecademy.com/resources/docs/general

## Type of Entry Request

- One or more new entries/terms requested.

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by mairagee524** [comment]
Ooh, I'd like to work on this if you still need help!

**Comment by Dusch4593** [comment]
Thanks, @mairagee524, I'll assign you to this one! 🙏🏻

**Comment by Dusch4593** [comment]
Hi @mairagee524! Just wanted to check in and ask if you were still working on a PR for this issue?

**Comment by SSwiniarski** [comment]
@Dusch4593, since @mairagee524 hasn't responded, I'll take this one on.
