### ISSUE TITLE
[Term Entry] Lua Coroutines .running()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3381]
### Reason/inspiration (optional)

We would like a new term entry on the `.running()` method for Lua: [Coroutines](https://www.codecademy.com/resources/docs/lua/coroutines). The entry should go in a new file under `docs/content/lua/concepts/coroutines/terms/running/running.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```lua `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by krushnarout** [comment]
I believe I can handle this assignment. Can I be assigned to it?

**Comment by aherman91** [comment]
@krushnarout you are assigned! You now have three open issues with us. Please create a PR on one of these issues before asking for new assignments.

**Comment by krushnarout** [comment]
@praTeek271 Hey this issue is assign to me. Why you made a PR without any permission ?

**Comment by krushnarout** [comment]
Hello @aherman91 , @praTeek271 has submitted a pull request for an issue that was assigned to me. Despite my ongoing work on this particular issue, they created the pull request without consulting with me or requesting to take over the assigned task. I am nearing completion of my work.

**Comment by SSwiniarski** [comment]
@krushnarout I closed @praTeek271's submissions. Sorry we didn't catch this earlier.

**Comment by krushnarout** [comment]
> @krushnarout I closed @praTeek271's submissions. Sorry we didn't catch this earlier.

Thank you
