### ISSUE TITLE
[Term Entry] Lua Coroutines .yield()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3384]
### Reason/inspiration (optional)

We would like a new term entry on the `.yield()` method for Lua: [Coroutines](https://www.codecademy.com/resources/docs/lua/coroutines). The entry should go in a new file under `docs/content/lua/concepts/coroutines/terms/yield/yield.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```lua `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by krushnarout** [comment]
can I be assigned to this?

**Comment by KTom101** [comment]
@krushnarout You've been assigned. 🎉
