### ISSUE TITLE
[Term Entry] Lua Math .asin()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3387]
### Reason/inspiration (optional)

We would like a new term entry on the `.asin()` method for Lua: [Math](https://www.codecademy.com/resources/docs/lua/mathematical-library). The entry should go in a new file under `docs/content/lua/concepts/mathematical-library/terms/asin/asin.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```lua `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Manmit124** [comment]
I hope you're doing well. I've created a pull request (#3423) for adding documentation to the project. I'd greatly appreciate it if you could take a look at it and provide your feedback.

Please let me know if there are any specific areas you'd like me to address or if you have any questions about the changes I've made.

Thank you for your time and consideration.

**Comment by SSwiniarski** [comment]
@Manmit124 In the future do not submit a PR before being officially assigned an issue. This is to prevent multiple people working on the same issue. We've had instances before where we had to close someone's PR because they weren't assigned an issue but someone else was.

**Comment by caupolicandiaz** [comment]
This issue has been reopened due to lack of progress by the previous contributor

**Comment by laisvigas** [comment]
@caupolicandiaz,can I be assigned to this issue?

**Comment by caupolicandiaz** [comment]
> @caupolicandiaz,can I be assigned to this issue?

You've been assigned
