### ISSUE TITLE
[Term Entry] Lua Math .deg()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3391]
### Reason/inspiration (optional)

We would like a new term entry on the `.deg()` method for Lua: [Math](https://www.codecademy.com/resources/docs/lua/mathematical-library). The entry should go in a new file under `docs/content/lua/concepts/mathematical-library/terms/deg/deg.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```lua `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by bcsamrudh** [comment]
@aherman91 Can I pick this up?

**Comment by caupolicandiaz** [comment]
This issue has been reopened due to lack of progress by the previous contributor

**Comment by laisvigas** [comment]
Can I be assigned to this issue, @caupolicandiaz?

**Comment by caupolicandiaz** [comment]
> Can I be assigned to this issue, @caupolicandiaz?

You're all set
