### ISSUE TITLE
[Term Entry] Lua Math .exp()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3392]
### Reason/inspiration (optional)

We would like a new term entry on the `.exp()` method for Lua: [Math](https://www.codecademy.com/resources/docs/lua/mathematical-library). The entry should go in a new file under `docs/content/lua/concepts/mathematical-library/terms/exp/exp.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```lua `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by DustyDogCodex** [comment]
Hi!

I would like to work on this issue. If no one else has been assigned, please assign this issue to me so I can help you resolve it.

Thanks!

**Comment by KTom101** [comment]
@DustyDogCodex You're assigned 🎉  In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.
Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by DustyDogCodex** [comment]
@KTom101 Hi Kyra! Thanks for assigning this issue to me. This is indeed my first contribution to Codecademy Docs. I found this issue through https://goodfirstissues.com/! I'm just a wee developer trying to sharpen my skills and this is a good way for me to practice and give back to the community :)
Is there a timeline for completing these issues btw?

**Comment by DustyDogCodex** [comment]
hi @KTom101 ! 

I have submitted a PR that will close this issue. Please review it when you get a chance and let me know if there is something I need to redo. 

Thanks again for giving me an oppurtunity to contribute to your project!
