### ISSUE TITLE
[Term Entry] Lua Math .floor()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3393]
### Reason/inspiration (optional)

We would like a new term entry on the `.floor()` method for Lua: [Math](https://www.codecademy.com/resources/docs/lua/mathematical-library). The entry should go in a new file under `docs/content/lua/concepts/mathematical-library/terms/floor/floor.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```lua `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by DustyDogCodex** [comment]
hi!

I can work on this issue for you. If no one else has been assigned, please assign this issue to me and I can resolve this for you.

Thanks!

**Comment by KTom101** [comment]
@DustyDogCodex I've assigned this to you. This will be your second assignment. 

So that you know, contributors can be assigned to up to 3 issues at a time and will have to submit pull requests for the ones they're assigned to before being assigned to any additional issues. 🙂

**Comment by DustyDogCodex** [comment]
Hi @KTom101 !

Hope you're having a good day! I have submitted a PR for this issue with a new file that contains an intro to this function. Please review it when you get a chance and let me know if I need to change anything.

Thanks!
