### ISSUE TITLE
[Term Entry] SQL Commands CROSS JOIN

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3395]
### Reason/inspiration (optional)

Add a term entry on the SQL Command `CROSS JOIN`. The entry will live under the file path `docs/content/sql/concepts/commands/terms/cross-join/cross-join.md`

The entry should describe what the command does. Ensure you include the following:

- A "Syntax" section with a ` ```pseudo` code snippet
- An "Example" section with a ` ```sql` code snippet

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by reganmarie** [comment]
Could I be assigned to this issue?

**Comment by KTom101** [comment]
@reganmarie You've been assigned

**Comment by reganmarie** [comment]
Thank you @KTom101 ! 😊

**Comment by KTom101** [comment]
@reganmarie You're welcome!
