### ISSUE TITLE
[Term Entry] SwiftUI ViewModifier .dropDestination()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3397]
### Reason/inspiration (optional)

We would like a new term entry for SwiftUI [ViewModifier](https://www.codecademy.com/resources/docs/swiftui/viewmodifier) about the .dropDestination() modifier. The entry should go in a new file in docs/content/swiftui/concepts/viewmodifier/terms/dropDestination/dropDestination.md

The entry should
    - Have an introductory paragraph about what the modifier is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the modifier in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by marjoriekohn** [comment]
I would like to work on this :)

**Comment by aherman91** [comment]
@marjoriekohn you're assigned!
