### ISSUE TITLE
[Edit] C++ Add Notes: C++ Classes

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3398]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to make an edit for C++ Classes. The entry should go in the existing file in docs/content/c++/concepts/classes/classes.md

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Do the following:
1) Add a note (2-3 sentences) to the end of the entry about overloading.
2) Link to the overloading entry: https://www.codecademy.com/resources/docs/cpp/overloading

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by krushnarout** [comment]
Hi! @KTom101 I would like to work on this issue. Please assign me.

**Comment by DevThazin** [comment]
Hi! Can you please assign me this issue.

**Comment by karikapatel29** [comment]
Hi ! I would like to contribute. Please assign me to this issue

**Comment by hiwotAmali** [comment]
Hello, I really would like to work on this issue, as I am learning 'Git and GitHub '  at  Codecademy , which includes learning how to contribute for open source projects.

**Comment by iceXshadow** [comment]
Hey, can I be assigned this issue. I would like to work on this as I am learning C++ at Codeacademy

**Comment by danpeq** [comment]
I found about docs in the Git & Github course, I have been trying to find some issue to be able to collaborate with what I am studying (JavaScript, CSS, HTTP, React) but I have not been able to find it so far

**Comment by yangc95** [comment]
@krushnarout You're assigned! I see this is your second issue.

> You can check out the [Contribution Guide](<https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md>) for additional information on contributing.
>  
> See [Content Standards](<https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md>) for an overview of styling tips that the [Style Guide](<https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md>) covers in detail.
>  
> After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

For all others who have commented along this thread, please wait for additional available issues to come out. Thanks for all of your patience!
