### ISSUE TITLE
[Edit] C++ Add Notes: C++ Functions

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3399]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to make an edit for C++ Functions. The entry should go in the existing file in docs/content/c++/concepts/functions/functions.md

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Do the following:
1) Add a note (2-3 sentences) to the end of the entry about overloading.
2) Link to the overloading entry: https://www.codecademy.com/resources/docs/cpp/overloading

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by bcsamrudh** [comment]
@aherman91 can you assign the issue to me

**Comment by bcsamrudh** [comment]
@aherman91 I just visited this link: https://www.codecademy.com/resources/docs/cpp/overloading. 
Could you please brief me on what i should do.

**Comment by yangc95** [comment]
Nice to see you on the repo again @bcsamrudh! I'll assign you to this issue.

@DevThazin feel free to check out any available open issues for now! Thanks for your interest
