### ISSUE TITLE
[Edit] Go [Edit] Go: Composition

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3400]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

This edit is for the Go [Composition](https://www.codecademy.com/resources/docs/go/composition) located under the file path `docs/content/go/concepts/composition/composition.md` 

Currently, the entry does not show struct embedding and how the fields and methods of the embedded type are inherited by the created type. Be sure to include:

- A "Syntax" section with a ` ```pseudo` code snippet
- An "Example" section with a ` ```go` code snippet

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Jamesllllllllll** [comment]
I'd like to take this one on, please!

**Comment by KTom101** [comment]
@Jamesllllllllll You've been assigned.
