### ISSUE TITLE
[Edit] Git [Edit] Git: Pull Requests

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3401]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

This edit is for the Git: [Pull Requests](https://www.codecademy.com/resources/docs/git/pull-requests) entry located under the file path: `docs/content/git/concepts/pull-requests/pull-requests.md`

Clarify when exactly a fork is needed. Currently it sounds like a fork is always needed but there are instances where you wouldn't need a fork (like when collaborating with someone and you both have write access to the repository). Explain this in the entry. If needed, you can add a blockquoted note under the step explaining this.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Rhythm-08** [comment]
Hello,I would like to take this issue

**Comment by Kadif-Ravik** [comment]
as would I

**Comment by KTom101** [comment]
@Rhythm-08 Since you asked first, I'm assigning this to you. Please use the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) as well as the documentation linked in the description as resources while creating this entry.

Is this your first contribution to Codecademy Docs? If so, where did you find out about contributing to Docs?

**Comment by KTom101** [comment]
@Kadif-Ravik I've assigned this to the person who asked first. Assignment is based on first-come-first-served. If you haven't already, please take a look at the other [unassigned issues](https://github.com/Codecademy/docs/issues?page=1&q=is%3Aissue+is%3Aopen+no%3Aassignee).

**Comment by Kadif-Ravik** [comment]
No worries, I left a comment because I was within like ten minutes.
Missed it by thaaat much.🙃

**Comment by SSwiniarski** [comment]
@Rhythm-08  It's been two weeks. Are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@Rhythm-08 This is being unassigned due to inactivity.

**Comment by Beunwwoit** [comment]
Hello, if the issue/topic is still available, I'd like to be assigned to it.
Thank you in advance 😁
