### ISSUE TITLE
[Edit] Python [Edit] Python Strings: Split

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3402]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

This edit is for the Python Strings: [Split](https://www.codecademy.com/resources/docs/python/strings/split) method located under the file path `docs/content/python/concepts/strings/terms/split/split.md`

Edit the syntax section to clarify that the second parameter in the `split()` method is the maximum number of splits. Also include the default when a number isn't given.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by christina-ml** [comment]
Hi @codecademy-docs @aherman91 Can I be assigned to this issue?

**Comment by salim923** [comment]
Hi @codecademy-docs @aherman91 , I would like to work on it. Can you please assign me this issue?

**Comment by KTom101** [comment]
@christina-ml Since you asked first, I'm assigning this to you. Please use the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) as well as the documentation linked in the description as resources while creating this entry.

Is this your first contribution to Codecademy Docs? If so, where did you find out about contributing to Docs?

**Comment by KTom101** [comment]
@salim923 I've assigned this to the person who asked first. Assignment is based on first-come-first-served. If you haven't already, please take a look at the other [unassigned issues](https://github.com/Codecademy/docs/issues?page=1&q=is%3Aissue+is%3Aopen+no%3Aassignee).

**Comment by christina-ml** [comment]
@KTom101 Thank you for assigning me to this issue.
Yes, this is my first time contributing to Codecademy Docs, and I found out about the docs from attending the Contributing to Docs during Hacktoberfest 2023 (afternoon session) event today! Thank you so much for going over how to navigate through the repository and finding an issue.

**Comment by KTom101** [comment]
@christina-ml That's great! And you're welcome. Thank you for deciding to make a contribution to Docs.
