### ISSUE TITLE
[Edit] CSS [Edit] CSS Animations: @keyframes

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3403]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like an edit a term within the CSS Animations entry. The entry lives in docs/content/css/concepts/animations/terms/@keyframes/@keyframes.md

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media (images, gifs) should accurately represent the existing code blocks in the example sections and fit in-line.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Jamesllllllllll** [comment]
I would like to take this one on, please!

**Comment by KTom101** [comment]
@Jamesllllllllll You've been assigned!

**Comment by Jamesllllllllll** [comment]
@KTom101 Thank you!

I coded a little "progress" bar in CSS - do we prefer with or without?

![Keyframes-Example-1-Progress](https://github.com/Codecademy/docs/assets/125431058/56fff3a6-0d0c-414c-bf68-c3de6d35e877)

Here is a version with no progress bar:

![Keyframes-Example-1-No-Progress](https://github.com/Codecademy/docs/assets/125431058/5f474226-846d-42a9-bd71-5dd47e18d598)

I have the same 2 versions for the example in the second code block.

**Comment by KTom101** [comment]
@Jamesllllllllll You can leave the progress bar in for now so we can see how it looks in the entry and then we can make adjustments if needed.

**Comment by Jamesllllllllll** [comment]
Thank you, @KTom101 !
