### ISSUE TITLE
[Edit] CSS [Edit] CSS Animations: animation-direction

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3406]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like an edit a term within the CSS Animations entry. The entry lives in docs/content/css/concepts/animations/terms/animation-direction/animation-direction.md

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media (images, gifs) should accurately represent the existing code blocks in the example sections and fit in-line.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by maryamkhan14** [comment]
Hi! May I pick this up?

**Comment by KTom101** [comment]
@maryamkhan14 You're assigned.

**Comment by krushnarout** [comment]
If someone leaves or is unable to work on this issue, please assign it to me. Thank you.

**Comment by SSwiniarski** [comment]
@maryamkhan14  It's been two weeks. Are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@maryamkhan14 This is being unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@djnelson You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@djnelson It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by djnelson** [comment]
@SSwiniarski I'm still working on it. I will have it completed and a pull request created before the end of this week.

**Comment by djnelson** [comment]
@SSwiniarski Ran into a color issue converting from CSS animation to GIF format. Will have it resolved by EOD tomorrow.

**Comment by SSwiniarski** [comment]
@djnelson This is being unassigned due to inactivity.

**Comment by Kadif-Ravik** [comment]
@SSwiniarski I'd like to take this one as well.

**Comment by SSwiniarski** [comment]
@Kadif-Ravik, you're assigned.
