### ISSUE TITLE
[Edit] HTML: Images - Images not displaying

### ISSUE THREAD

**Issue by Jamesllllllllll** [Codecademy/docs#3416]
### Type of Edit

Fix grammar, spelling, formatting

### Description

The images are not displaying on this page: https://www.codecademy.com/resources/docs/html/images

I believe the error is caused by a Markdown formatting issue. There is a space between the square brackets (alt text) and the parentheses (image link).

Example:
```
// This:
![image example] (https://raw.githubusercontent.com/Codecademy/docs/main/media/html-image-example.png)

// Instead of this:
![image example](https://raw.githubusercontent.com/Codecademy/docs/main/media/html-image-example.png)
```

The author ( @cchaseT42 ) of the image additions may want to make the fix since it is very recent.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by krushnarout** [comment]
Hi, I want to work on this. please assign me.

**Comment by yangc95** [comment]
@Jamesllllllllll thanks for putting this issue in

@SarthakD15 I've assigned you to this issue

**Comment by SarthakD15** [comment]
Thanks @yangc95

**Comment by SarthakD15** [comment]
#3420 
Hey @yangc95 @Jamesllllllllll I have resolved the issue with displaying images. 
Please review this PR :)
Thank you !

**Comment by SarthakD15** [comment]
Hey,
You may close this issue now as it got resolved !
#3420 : Merged PR
