### ISSUE TITLE
[Edit] UI and UX Design: Button - Hyperlinks of resources are not displaying correctly

### ISSUE THREAD

**Issue by krushnarout** [Codecademy/docs#3426]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

The hyperlinks of resources are not displaying correctly on this page: https://www.codecademy.com/resources/docs/uiux/button

The error is caused by Markdown formatting. There is a space between the square brackets [Resource Title] and the parentheses (URL).

The square brackets [Resources] and the parentheses (image link) should in the following manner:

```
[Resource Title](URL)
```

I would like to work on this issue. can I be assigned to this?

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by krushnarout** [comment]
Hi! I want to work on this issue. Please assign this to me. Thank you

**Comment by yangc95** [comment]
@krushnarout Thanks for noticing this! Please tag me once you open the PR and we can get that in ASAP 🙂
