### ISSUE TITLE
[Bug/Error] Subject: Change Twitter logo to X

### ISSUE THREAD

**Issue by blindaks** [Codecademy/docs#3452]
### Actual Behavior

We should change the old twitter logo on the website.

### Expected Behavior

The logo should be X in placeof bird.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by chinmay7016** [comment]
hey @yangc95 pls assign me this task i will work on it

**Comment by KTom101** [comment]
@chinmay7016 This is for the icon in the footer, correct? Someone from the engineering team would have to make this change.

**Comment by blindaks** [comment]
> @blindaks This is for the icon in the footer, correct? Someone from the engineering team would have to make this change.

I would love to work on this if you could please assign this to me.

**Comment by blindaks** [comment]
> @blindaks Thank you for sharing this. Unfortunately, you will not be able to change this on your end. I will be sharing this with the engineering team.
> 
> cc @aherman91

Okay no issues
