### ISSUE TITLE
[Edit] Documentation: Style Guide

### ISSUE THREAD

**Issue by cslylla** [Codecademy/docs#3453]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Lua is now a supported language for code blocks. This should be included in the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md#docs-style-guide).

Update the documentation/style-guide.md file to:
- include `lua` in the [Supported Code Blocks](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md#supported-code-blocks) section

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by cslylla** [comment]
I would like to update this entry (if necessary).

**Comment by DooMIM** [comment]
Hello @cslylla I would like to fix those edits.

**Comment by Kadif-Ravik** [comment]
is this issue still open?

**Comment by vrun1208** [comment]
Hi @cslylla, Hope you are well!
If no one is working on this issue, I would like to work on this one🚀

**Comment by KTom101** [comment]
@cslylla It is supported, but it wasn't added to the documentation. Can you update the style guide so that Lua is listed as a supported code language instead?

**Comment by KTom101** [comment]
@DooMIM @Kadif-Ravik @vrun1208 Since this issue was created by a community member and they asked to be assigned to it, I assigned this to them. Please check back regularly for more issues. 😄

**Comment by Kadif-Ravik** [comment]
I have been, I keep getting told first come first serve.
