### ISSUE TITLE
[Edit] Subject: cryptojacking adding term in Cyber-security

### ISSUE THREAD

**Issue by xlo-u** [Codecademy/docs#3465]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Cryptojacking is a type of cyberattack where a hacker uses a target’s computing power to mine cryptocurrency without the target’s knowledge or consent.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
Closing this issue as the author abandoned it.
