### ISSUE TITLE
[Concept Entry] Git Config

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3488]
### Reason/inspiration (optional)

We would like a new concept entry for Git about Config. The entry should go in a new file in docs/content/git/concepts/config/config.md

The entry should
    - Have an introductory paragraph about the concept.
    - Code blocks displaying different aspects of the concept.
    - Internal linking as applicable.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by arun-sagar-s-a** [comment]
Hi @bndiep  I think I'll take this up. (will raise a PR by this weekend)

**Comment by SSwiniarski** [comment]
@arun-sagar-s-a you've already claimed too many issues. Submit PRs for the other issues you've claimed before claiming another one.

**Comment by AlexArdelean21** [comment]
I'd like to take this issue. I need it to complete the GitHub course.

**Comment by SSwiniarski** [comment]
@AlexArdelean21 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment]
@AlexArdelean21 It's been two weeks, are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by AlexArdelean21** [comment]
The first review on my PR was completed 2 days ago, not sure what I should do now.
![Screenshot 2023-10-25 214551](https://github.com/Codecademy/docs/assets/146313498/7d9efed2-3f07-4d1f-802f-9e871a20d04a)

**Comment by SSwiniarski** [comment]
@AlexArdelean21 can you link to your PR here? 

Also, another maintainer will review your PR, you don't have to do anything until then.

**Comment by AlexArdelean21** [comment]
Sure! https://github.com/Codecademy/docs/pull/3672
