### ISSUE TITLE
[Concept Entry] Git Mv

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3491]
### Reason/inspiration (optional)

We would like a new concept entry for Git about Mv. The entry should go in a new file in docs/content/git/concepts/mv/mv.md

The entry should
    - Have an introductory paragraph about the concept.
    - Code blocks displaying different aspects of the concept.
    - Internal linking as applicable.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by arun-sagar-s-a** [comment]
Hi @bndiep I'll work on this, please assign (I'll raise a PR by this weekend)

**Comment by SSwiniarski** [comment]
@arun-sagar-s-a you should never submit a PR before you've been assigned an issue, you've already been assigned three issues, and you weren't eligible to take another. Since you've already submitted a PR I'm just going to unassign one of the issues I've already assigned to give someone else a chance.

**Comment by arun-sagar-s-a** [comment]
@SSwiniarski Apologise won't do that again!
