### ISSUE TITLE
[Term Entry] Lua Math .mininteger()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3499]
### Reason/inspiration (optional)

We would like a new term entry on the `.mininteger()` method for Lua: [Math](https://www.codecademy.com/resources/docs/lua/mathematical-library). The entry should go in a new file under `docs/content/lua/concepts/mathematical-library/terms/mininteger/mininteger.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```lua `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Khalid-debugg** [comment]
assign this to me, please

**Comment by Khalid-debugg** [comment]
assign this to me, please

**Comment by KTom101** [comment]
@Khalid-debugg You're assigned In addition to the documents linked in the description, please also take a look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.

Also, how did you find out about contributing to Codecademy Docs?

**Comment by Khalid-debugg** [comment]
Just to be clear mininteger in Lua programming language is a constant in the math library and is not a method that can be called mininteger(), am I right? Therefore it is not considered a term. please clarify this point to me ASAP. @KTom101

**Comment by Khalid-debugg** [comment]
And I found out about contributing to Codecademy Docs from Github search.
