### ISSUE TITLE
[Term Entry] Lua Math .modf()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3500]
### Reason/inspiration (optional)

We would like a new term entry on the `.modf()` method for Lua: [Math](https://www.codecademy.com/resources/docs/lua/mathematical-library). The entry should go in a new file under `docs/content/lua/concepts/mathematical-library/terms/modf/modf.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```lua `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by SusheelThapa** [comment]
@bndiep Can you assign this issue to me?

**Comment by Aloneking789** [comment]
i can't find modf.md

**Comment by KTom101** [comment]
@SusheelThapa I've assigned you 🎉 In addition to the documents linked in the description, please also take a look at our [[Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.

Also, how did you find out about contributing to Codecademy Docs?

**Comment by KTom101** [comment]
@Aloneking789 This has been assigned to the first contributor who commented. Assignment is based on first-come-first-serve. There is no "modf.md" because the person assigned to the issue has to create it themselves and add information on the method.

You can take a look to see if there is any other [unclaimed issue](https://github.com/Codecademy/docs/issues?page=1&q=is%3Aissue+is%3Aopen+no%3Aassignee) you want to work on. Check back regularly for more issues being added.
