### ISSUE TITLE
[Term Entry] Kotlin Math .abs()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3511]
### Reason/inspiration (optional)

We would like a new term entry on the `.abs()` method for Kotlin: [Math](https://www.codecademy.com/resources/docs/kotlin/math-methods). The entry should go in a new file under `docs/content/kotlin/concepts/math-methods/terms/abs/abs.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```kotlin `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by VividhPandey003** [comment]
Hey I would like to work on this. Could you please assign this issue to me.

**Comment by Khalid-debugg** [comment]
Due to the inactivity of the assignee can you assign this to me, please?

**Comment by SSwiniarski** [comment]
@VividhPandey003 It's been two weeks, are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@Khalid-debugg, @VividhPandey003 still has some time to produce a PR.

**Comment by VividhPandey003** [comment]
@SSwiniarski could you please review my PR once and let me know if there are any reviews/changes to be made. Sorry for the delay, was stuck in some prior deadlines. Thanks. Would love to contribute more in future.😄
