### ISSUE TITLE
[Term Entry] Kotlin Math .floor()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3524]
### Reason/inspiration (optional)

We would like a new term entry on the `.floor()` method for Kotlin: [Math](https://www.codecademy.com/resources/docs/kotlin/math-methods). The entry should go in a new file under `docs/content/kotlin/concepts/math-methods/terms/floor/floor.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```kotlin `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by tanbirali** [comment]
I will like to work on this.

**Comment by SriGanesh737** [comment]
@codecademy-docs please check my pr and merge it .

**Comment by SriGanesh737** [comment]
@yangc95 can you please tell me why you made my pr invalid so i can change or do something please .

**Comment by yangc95** [comment]
@SriGanesh737, another contributor commented on this issue to claim it first. We follow first-come-first-serve with issues, and creating a PR without being assigned first creates disarray within the repository. Thanks for understanding this process.

As for the entry itself that you submitted, I recommend comparing with the term entry template that can be found here, and seeing how the entry can be improved upon for faster review+merge: https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md

**Comment by SriGanesh737** [comment]
Thanks for informing, can you please assign me the issues #3520,#3521 where I asked first for working, please assign as soon as possible so that I can work on them, Thank You.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
