### ISSUE TITLE
[Edit] CSS [Edit] CSS Animations: animation-play-state

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3528]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like an edit a term within the CSS Animations entry. The entry lives in docs/content/css/concepts/animations/terms/animation-play-state/animation-play-state.md

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media (images, gifs) should accurately represent the existing code blocks in the example sections and fit in-line.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
@Kadif-Ravik, @luv2027 already claimed this issue.

@luv2027 you should not submit PRs for issues that you've not been assigned to yet. It worked out this time, but we've had to reject PRs in the past when multiple people started working on the same PR.

**Comment by DakuwoN** [comment]
I will gladly accept this if needed :D

**Comment by SSwiniarski** [comment]
@DakuwoN this has already been assigned and there is a PR for this issue.

**Comment by tjdpower** [comment]
could this be labeled as claimed then, if someone is working on it? I clicked as it is one of the only "good for beginning" posts that isn't already "claimed"

Unfortunate, but such is life, no?

**Comment by SSwiniarski** [comment]
This should have been closed per @yangc95's comments on https://github.com/Codecademy/docs/pull/3548.
