### ISSUE TITLE
[Edit] CSS [Edit] CSS Background: background-blend-mode

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3532]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like an edit a term within the CSS Animations entry. The entry lives in docs/content/css/concepts/animations/terms/background-blend-mode/background-blend-mode.md

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media (images, gifs) should accurately represent the existing code blocks in the example sections and fit in-line.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by arun-sagar-s-a** [comment]
can I work on this! @bndiep  (I'm in IST time, I'll raise a PR by this weekend)

**Comment by antriksh-9** [comment]
Hey @bndiep I want to work on this issue.
Please assign it to me.

**Comment by SSwiniarski** [comment]
@arun-sagar-s-a You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment]
@antriksh-9, @arun-sagar-s-a claimed this one first.

**Comment by SSwiniarski** [comment]
@antriksh-9, since @arun-sagar-s-a submitted a PR for a fourth issue without being assigned, I am reassigning this issue to you.

**Comment by SSwiniarski** [comment]
@arun-sagar-s-a you are no longer assigned to this issue.

**Comment by antriksh-9** [comment]
Hey @SSwiniarski according to the issue description the background-blend-mode file should be inside terms folder but it isn't there.
Please look into this.

**Comment by SSwiniarski** [comment]
> docs/content/css/concepts/animations/terms/background-blend-mode/background-blend-mode.md

The issue should have pointed to docs/content/css/concepts/**background**/terms/background-blend-mode/background-blend-mode.md
