### ISSUE TITLE
[Edit] CSS [Edit] CSS Background: background-origin

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3536]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like an edit a term within the CSS Animations entry. The entry lives in docs/content/css/concepts/animations/terms/background-origin/background-origin.md

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media (images, gifs) should accurately represent the existing code blocks in the example sections and fit in-line.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by adeyinkaezra123** [comment]
Hi, can I work on this issue?

**Comment by luv2027** [comment]
heya @bndiep, Can I work on this issue?

**Comment by yangc95** [comment]
@adeyinkaezra123 Thanks for your patience and nice to see you're contributing again!

You're assigned! You can check out the [Contribution Guide](<https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md>) for additional information on contributing. 
 
See [Content Standards](<https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md>) for an overview of styling tips that the [Style Guide](<https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md>) covers in detail. 
 
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.

**Comment by Mstanic05** [comment]
Can you assign this to me!
