### ISSUE TITLE
[Entry Edit Request] General: Git topic should include 'distributed' in description

### ISSUE THREAD

**Issue by griffincosgrove** [Codecademy/docs#354]
## Description
For the entry for the the [general topic Git](https://www.codecademy.com/resources/docs/general/what-is-git) the word distributed is missing from the description. Git is not just a version control system, it is a distributed version control system. This also appears in the [Git](https://git-scm.com/) home page, "Git is a free and open source distributed version control system"

## Type of Bug Request

- Unclear explanation of term(s).

## Type of Entry Request

- Recommend change(s) to documentation (such as existing text or new text)

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by griffincosgrove** [comment]
small and but important change, i would love to open a PR for this as long as there is agreement/approval

**Comment by sonnynomnom** [comment]
Fixed and closing!
