### ISSUE TITLE
[Edit] Subject: Greedy Best First Search Algorithm

### ISSUE THREAD

**Issue by Sahilkumar19** [Codecademy/docs#3565]
### Type of Edit (select all that apply)

Clarify unclear content and/or terms

### Description (optional)

Greedy Best First Search is not properly explained.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [X ] Issue is assigned

**Comment by AlstrupJacob** [comment]
@codecademy-docs @SSwiniarski I would like to work on this

**Comment by Sahilkumar19** [comment]
> @codecademy-docs @SSwiniarski I would like to work on this

I have raises it for myself but my PR is not passing the checks

**Comment by SSwiniarski** [comment]
@AlstrupJacob, @Sahilkumar19 created this issue and has first chance at it.

**Comment by Sahilkumar19** [comment]
> @AlstrupJacob, @Sahilkumar19 created this issue and has first chance at it.

Thanks, will work on it

**Comment by AlstrupJacob** [comment]
#3572

**Comment by Sahilkumar19** [comment]
> @AlstrupJacob, @Sahilkumar19 created this issue and has first chance at it.

I have made a PR but it's showing like this
![merging](https://github.com/Codecademy/docs/assets/124178990/fb12be97-2d58-4e61-8109-594157b117e6)

**Comment by SSwiniarski** [comment]
> > @AlstrupJacob, @Sahilkumar19 created this issue and has first chance at it.
> 
> I have made a PR but it's showing like this ![merging](https://user-images.githubusercontent.com/124178990/274859850-fb12be97-2d58-4e61-8109-594157b117e6.png)

@Sahilkumar19 Don't worry. This is normal. It will need to be reviewed before it's merged.

**Comment by Sahilkumar19** [comment]
> > > @AlstrupJacob, @Sahilkumar19 created this issue and has first chance at it.
> > 
> > 
> > I have made a PR but it's showing like this ![merging](https://user-images.githubusercontent.com/124178990/274859850-fb12be97-2d58-4e61-8109-594157b117e6.png)
> 
> @Sahilkumar19 Don't worry. This is normal. It will need to be reviewed before it's merged.

Thanks ! you mean now someone will review it and then will think of merging

**Comment by DakuwoN** [comment]
If available I can take this issue.

**Comment by Sahilkumar19** [comment]
> If available I can take this issue.

**Comment by SSwiniarski** [comment]
@DakuwoN there is already an open PR for this issue.

**Comment by DakuwoN** [comment]
Yessir. Thank you
