### ISSUE TITLE
[Edit] Subject: A* search

### ISSUE THREAD

**Issue by Sahilkumar19** [Codecademy/docs#3596]
### Type of Edit (select all that apply)

Clarify unclear content and/or terms, Add new content (definitions, codeblocks, etc.)

### Description (optional)

Some properties of A* search algorithm are missing like optimality and the completeness.Also some terms are unclear.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
@Sahilkumar19 Generally you should ask to be assigned an issue and wait to be officially assigned before producing a PR. Even if you submit the issue, it should still be vetted by a maintainer before you work on it.

**Comment by Sahilkumar19** [comment]
> @Sahilkumar19 Generally you should ask to be assigned an issue and wait to be officially assigned before producing a PR. Even if you submit the issue, it should still be vetted by a maintainer before you work on it.

Got it , Thanks!

**Comment by SSwiniarski** [comment]
Closing because PR was rejected.
