### ISSUE TITLE
[Edit] Java: Math Methods

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#3601]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] 
Issue created from idea presented in PR #2948

We would like an edit to a concept within Java Math Methods. The entry lives in `docs/content/java/concepts/math-methods/math-methods.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

The edit should:

1. Add a markdown table of common math constants
2. Include a header with text to introduce the table

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by narcissus123** [comment]
[@yangc95](https://github.com/yangc95) I am interested in taking this issue on.

**Comment by KTom101** [comment]
@narcissus123 You're assigned.

**Comment by narcissus123** [comment]
Thank you for assigning me to this issue.

**Comment by SSwiniarski** [comment]
PR was merged.
