### ISSUE TITLE
[Entry Request] Git: add and status commands

### ISSUE THREAD

**Issue by Pandz18** [Codecademy/docs#361]
## Description
- I want to create a git status and git add (git concept) files which shows what the commands are and how they can be used. 

## Type of Entry Request

- One or more new entries/terms requested.
- Recommend change(s) to documentation (such as existing text or new text)

## Checklist

- [X] The issue is appropriately titled.
- [X] Description is clear and includes supporting text, files, etc.
- [X] A similar issue hasn't already been created.
- [X] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by Dusch4593** [comment]
@Pandz18 Assigned you! Thank you for requesting this entry 😄
