### ISSUE TITLE
[Enhancement] Add border on hover to topics

### ISSUE THREAD

**Issue by singodiyashubham87** [Codecademy/docs#3615]
### Actual Behavior

On hovering it just changes the color as of now.

### Expected Behavior

I want a border to be shown too on hover so that it'll enhance the UX of the website.

Kindly assign me the issue.

### On what browser(s) are you seeing the problem?

Brave

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by SSwiniarski** [comment]
@singodiyashubham87 I'm going to close this issue because this repo deals with the content of Docs, not the functionality of the website.
