### ISSUE TITLE
[Term Entry] Kotlin Math .min()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3626]
### Reason/inspiration (optional)

We would like a new term entry on the `.min()` method for Kotlin: [Math](https://www.codecademy.com/resources/docs/kotlin/math-methods). The entry should go in a new file under `docs/content/kotlin/concepts/math-methods/terms/min/min.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```kotlin `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by marjoriekohn** [comment]
I would like to work on this issue. May I be assigned?

**Comment by nobunagaaa** [comment]
Can i be assigned this?

**Comment by SSwiniarski** [comment]
@parthasdey2304 I had to close your PR because you submitted it without being assigned and people claimed this issue before you. You should _never_ submit a PR without being assigned.
