### ISSUE TITLE
[Term Entry] Kotlin Math .truncate()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3634]
### Reason/inspiration (optional)

We would like a new term entry on the `.truncate()` method for Kotlin: [Math](https://www.codecademy.com/resources/docs/kotlin/math-methods). The entry should go in a new file under `docs/content/kotlin/concepts/math-methods/terms/truncate/truncate.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```kotlin `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by noahpgordon** [comment]
Hi Rahul, I noticed that you requested 6 open issues in Kotlin Math term entries. Mind if I take this one on? Thanks in advance.

**Comment by rahul0x00** [comment]
> Hi Rahul, I noticed that you requested 6 open issues in Kotlin Math term entries. Mind if I take this one on? Thanks in advance.

4*, but yeah sure you can take this one
