### ISSUE TITLE
[Edit] CSS [Edit] CSS Borders: border

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3638]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] We would like an edit to a term within CSS Borders. The term entry lives in docs/content/css/concepts/borders/terms/border/border.md

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media (images, gifs) should accurately represent the existing code blocks in the example sections and fit in-line. ex: [See last image here](https://www.codecademy.com/resources/docs/html/attributes/title)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Kritika30032002** [comment]
assign me this

**Comment by SSwiniarski** [comment]
@Kritika30032002 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by ishg-153** [comment]
Hey @Kritika30032002. I see you have this issue to work on as well. You can get in at least one of the issues to start with.
**Note:** If you don't respond with a PR or an update within a week, this issue will be unassigned from you.

**Comment by ishg-153** [comment]
@Kritika30032002 Since there was no response from your end on any of the issues, I am unassigning you.

**Comment by ROOHITH** [comment]
I am new to contribution what should I do ?

**Comment by SSwiniarski** [comment]
@ROOHITH you should claim an issue, then write a PR addressing the issue and submit it to the repo, where maintainers will review it, and after you address their comments, the PR will be merged. You can also check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md), the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md).

Did you want to claim this issue?

**Comment by Jamesllllllllll** [comment]
@ROOHITH - do you want to take this issue?

If not, I will gladly take it on! Thanks.

**Comment by ROOHITH** [comment]
@Jamesllllllllll  you can take it.

**Comment by ishg-153** [comment]
@Jamesllllllllll You're assigned!🎉
