### ISSUE TITLE
[Edit] CSS [Edit] CSS Borders: border-width

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3645]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] We would like an edit to a term within CSS Borders. The term entry lives in docs/content/css/concepts/borders/terms/border-width/border-width.md

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media (images, gifs) should accurately represent the existing code blocks in the example sections and fit in-line. ex: [See last image here](https://www.codecademy.com/resources/docs/html/attributes/title)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by YashSalunke12** [comment]
Assign me this issue

**Comment by stevielee3333** [comment]
Could you assign this to me please?

**Comment by SSwiniarski** [comment]
@stevielee3333, @YashSalunke12 claimed this issue first.

**Comment by YashSalunke12** [comment]
@SSwiniarski Hey, you didn't assign me this issue! I've claimed this issue first.

**Comment by SSwiniarski** [comment]
@YashSalunke12 Sorry, that was an error on my part.

**Comment by YashSalunke12** [comment]
@SSwiniarski Hey, I've cloned this project locally! but can you help me with how to run this project locally?
