### ISSUE TITLE
[Edit] CSS [Edit] CSS Colors: hsla()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3649]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] We would like an edit to a term within CSS Colors. The term entry lives in docs/content/css/concepts/colors/terms/hsla/hsla.md

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media (images, gifs) should accurately represent the existing code blocks in the example sections and fit in-line. ex: [See last image here](https://www.codecademy.com/resources/docs/html/attributes/title)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by dhakalmahima188** [comment]
@codecademy-docs please assign this to me

**Comment by stevielee3333** [comment]
Please may you assign this to me?

**Comment by SSwiniarski** [comment]
@dhakalmahima188 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment]
@sanarawal7, @dhakalmahima188 claimed this issue first.

**Comment by ishg-153** [comment]
Hey @dhakalmahima188. I see you have this issue to work on as well. You can get in at least one of the issues to start with.
**Note:** If you don't respond with a PR or an update within a week, this issue will be unassigned from you.

**Comment by ishg-153** [comment]
@dhakalmahima188 Since there was no response from your end, I have unassigned you.

**Comment by y-Ouarhim** [comment]
Hello,
I would like to be assigned.
PS: where can I point out a modification to be made in the docs repository.

**Comment by SSwiniarski** [comment]
@y-Ouarhim You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment]
> Hello, I would like to be assigned. PS: where can I point out a modification to be made in the docs repository.

@y-Ouarhim you can suggest modifications by opening your own issue.

**Comment by y-Ouarhim** [comment]
Hello,
I am working on it, thank you for indulging me.
Ouarhim Younes.

Le dim. 26 nov. 2023, 19:07, SSwiniarski ***@***.***> a
écrit :

**Comment by SSwiniarski** [comment]
@y-Ouarhim This is being unassigned due to inactivity.

**Comment by Jamesllllllllll** [comment]
Happy to work on this one.

**Comment by johnoleary317** [comment]
I'm looking for a first experience contributing as part of the Git and Github courses.

**Comment by dawsarqawasmi** [comment]
hey I would like to be assigned for this issue

**Comment by SSwiniarski** [comment]
@johnoleary317, @dawsarqawasmi, @Jamesllllllllll claimed this one first.
