### ISSUE TITLE
[Edit] Subject: Fork under git concepts

### ISSUE THREAD

**Issue by singodiyashubham87** [Codecademy/docs#3650]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

I want to add the forking topic under git concepts directory.

Kindly assign me this issue.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by Emmanueldlc24** [comment]
@yangc95 I am interested in taking this issue on.

**Comment by Kosyenka** [comment]
I am also interested in taking this issue on. I found out about docs through Codecademy, this is my learn GIT project assignment.

**Comment by KTom101** [comment]
@singodiyashubham87 You've been assigned. You can add the entry under the file path `content/git/concepts/fork/fork.md`. 

Please look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) for additional information on contributing. See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail. After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval. 

Is this your first contribution to Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by KTom101** [comment]
@Kosyenka @Emmanueldlc24 This issue was created by a community member (instead of a maintainer). Since they asked to be assigned within the description, they were assigned to this issue. Please check back regularly for [unassigned issues](https://github.com/Codecademy/docs/issues?page=1&q=is%3Aissue+is%3Aopen+no%3Aassignee) to work on.
