### ISSUE TITLE
[Doc/Error] Subject: No Shields Badges In the readme.md

### ISSUE THREAD

**Issue by mohitd404** [Codecademy/docs#3658]
### Actual Behavior

no visitors count in repository, No lisence badge.

### Expected Behavior

Shield badges in a README.md file work by embedding image links that display important project information like build status or licenses. They use Markdown syntax and can be customized to show dynamic data. You can use services like shields.io or create custom badges to enhance your README's visual appeal and provide quick project details to visitors.

![shie b](https://github.com/Codecademy/docs/assets/146939900/a5ea614b-a7a5-4785-bf9e-fcf6be9619af)

### On what browser(s) are you seeing the problem?

Chrome

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by Pratikdate** [comment]
assign i will add it

**Comment by mohitd404** [comment]
kindly assign this issue to me !! I would love to work on it !! Thank you !

**Comment by scottfinamore** [comment]
This would be a great first issue for me to work on if I may, thank you.

**Comment by dakshdeepHERE** [comment]
@mohitd404 You're assigned! 🚀You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by dakshdeepHERE** [comment]
@mohitd404 Thank you for the suggestion, We will discuss about this more internally. 🚀
