### ISSUE TITLE
[Edit] Subject: Updating python.md

### ISSUE THREAD

**Issue by 0Armaan025** [Codecademy/docs#3679]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

First, if you are reading this, you are amazing! 🔥

I love python! 💖 and while reading out "python.md", I felt like it was blank, not interesting enough or precise.
I thought why not level it up? 🔥

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by KNBahir** [comment]
@0Armaan025 I am willing to take this issue on, kindly let me to

**Comment by KTom101** [comment]
@0Armaan025 I'm closing this since you closed the PR out. Also in the future, wait to be assigned first. We're currently not looking for changes like the ones you wanted to make. Thanks.
