### ISSUE TITLE
Typo fix to animation-iteration-count.md

### ISSUE THREAD

**Issue by DanWSDev** [Codecademy/docs#3685]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

Correct inifinite to infinite on line 26. I previously made note of this in a pull request and showed how to fix it. Can you assign me to this?  

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by caupolicandiaz** [comment]
@DanWSDev I apologize if my previous comments were not clear. Your edit clearly addresses an error, but this is a very minor update. We understand that there are many contributors interested in participating in hacktober and earning credit for contributions. But, we generally prefer that PRs have a more substantial scope. I would advise that you review some other edits to better understand what our expectations are:
https://github.com/Codecademy/docs/pull/3657/files
https://github.com/Codecademy/docs/pull/3450/files

**Comment by DanWSDev** [comment]
> @DanWSDev I apologize if my previous comments were not clear. Your edit clearly addresses an error, but this is a very minor update. We understand that there are many contributors interested in participating in hacktober and earning credit for contributions. But, we generally prefer that PRs have a more substantial scope. I would advise that you review some other edits to better understand what our expectations are:
> https://github.com/Codecademy/docs/pull/3657/files
> https://github.com/Codecademy/docs/pull/3450/files

I don't mind about credit at all but I just want it to be fixed because it is still incorrect. Yes I understand that it is very minor but still needs to be fixed in future.

**Comment by caupolicandiaz** [comment]
Generally, we offer such edits *first* to the original/main/most recent contributor.

**Comment by DanWSDev** [comment]
> Generally, we offer such edits _first_ to the original/main/most recent contributor.

Sure that is totally fine with me I just wanted to help out when I noticed it.
