### ISSUE TITLE
FEATURE :- Always Display 'Back to Top' Button for Improved Navigation

### ISSUE THREAD

**Issue by Abhishek19-dev** [Codecademy/docs#3695]
### Actual Behavior

The project's documentation (docs.gpt) currently includes a "Back to Top" button located at the end of the page. While it serves its purpose in assisting users to return to the top of the document when they are already at the bottom, it becomes inaccessible as users scroll down the page. This means that when readers are in the middle or towards the end of a long document, they lose the convenience of quickly navigating back to the top, as the button is no longer visible. This can result in a less user-friendly experience, especially for users who frequently refer to different sections of the documentation.
<img width="1438" alt="Screenshot 2023-10-21 at 10 53 02 AM" src="https://github.com/Codecademy/docs/assets/145835714/7407ccb0-1c2e-4352-94b0-3416073ab34b">

### Expected Behavior

Back to top buttton fixed on bottom right side for easy navigation

<img width="857" alt="Screenshot 2023-10-21 at 10 55 13 AM" src="https://github.com/Codecademy/docs/assets/145835714/2cfd498d-09ee-4a59-883e-90a04febec8a">

### On what browser(s) are you seeing the problem?

Chrome

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by KNBahir** [comment]
@Abhishek19-dev I am willing to take this Issue on, Kindly Assign it to me.

**Comment by Emmanueldlc24** [comment]
@Abhishek19-dev I would like the opportunity work on this issue, I was introduced to docs through Codecademy

**Comment by KTom101** [comment]
@Abhishek19-dev @Emmanueldlc24 This repository only pertains to the contents of Docs. Members of the community can not change any features of the site. I will be sure to pass on your feedback to the engineering team. Thanks.
