### ISSUE TITLE
[Edit] Subject: Updating Context of Use Topic in UI and UX Design Concepts

### ISSUE THREAD

**Issue by sneha-github96** [Codecademy/docs#3697]
### Type of Edit (select all that apply)

Clarify unclear content and/or terms in the following doc: https://www.codecademy.com/resources/docs/uiux/context-of-use

### Description (optional)

Add missing hyperlinks for the following terms: field studies and diary studies.
Move "source" to Resources section.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by sneha-github96** [comment]
Would love to work on this, please assign it to me.

**Comment by KTom101** [comment]
@sneha-github96 You don't have to move the source to a it's own section. But you can add the hyperlinks.

Is this your first contribution to Codecademy Docs? If so, how did you find out about contributing to the Docs repository?

**Comment by sneha-github96** [comment]
@KTom101 Sure, I'll add the hyperlinks. 
Yes. I'm new to the open-source world, and I found out about Codecademy docs through this repo: https://github.com/dharmelolar/technical-writing-resources (stumbled upon it on my Twitter feed).

Thanks!
