### ISSUE TITLE
[Entry] Subject: Linked Lists in C Language

### ISSUE THREAD

**Issue by Carloscode5** [Codecademy/docs#3701]
### Reason/inspiration (optional)

I would like to contribute a whole section on data structures to the Codecademy Docs C Concepts. More specifically on Linked List in C Language. I would like to open this issue and be assigned to it since I did not see anywhere in the C Concepts of such subject.

Thank you very much.

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Carloscode5** [comment]
I would like to be assigned this issue. Created issue and would love to create section on Linked Lists. Heard about Docs from Codecademy Git & GitHub Course. :)

**Comment by SSwiniarski** [comment]
@Carloscode5 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by Carloscode5** [comment]
@SSwiniarski Thank you, I went ahead and pushed my contributions to the remote and awaiting review. I learned about this repo from Codecademy's Learn Git & GitHub Course. Let me know what further instructions I should partake in.
Be well, talk soon!

**Comment by ishg-153** [comment]
Hi @Carloscode5. You said your contribution is in, but I can't see your PR. You may need to create another PR.

**Comment by Carloscode5** [comment]
Hi there, I went back and double checked and actually hadn't completed a
PR. It is now up for your review.

Thank you for your patience and catch up soon!

Best,

Carlos Valenzuela

**Comment by Carloscode5** [comment]
Hi @SSwiniarski I just wanted to check back and see if there was anything more you needed from my contribution on Linked Lists #3701 ?

**Comment by SSwiniarski** [comment]
@Carloscode5 Yes, you need to address the maintainer comments on your PR so it can go forward for a second review.

**Comment by Carloscode5** [comment]
Thank you!Best,Carlos ValenzuelaOn Nov 7, 2023, at 8:51 AM, SSwiniarski ***@***.***> wrote:﻿
@Carloscode5 Yes, you need to address the maintainer comments on your PR so it can go forward for a second review.

**Comment by rajvee18** [comment]
i would love contribute, regarding this issue. I am doing learn git and github course on codecademy and doing a portfolio project in that course. Please assign this issue.

**Comment by SSwiniarski** [comment]
@rajvee18 this is already assigned and an open PR is associated with it.

**Comment by rajvee18** [comment]
@SSwiniarski thank you

**Comment by Carloscode5** [comment]
Thank you SSwiniarskiBest,Carlos ValenzuelaOn Jan 11, 2024, at 12:13 PM, rajvee18 ***@***.***> wrote:﻿
@SSwiniarski thank you

**Comment by ishg-153** [comment]
@Carloscode5 This issue is being unassigned due to lack of activity.

**Comment by Carloscode5** [comment]
Hi Ishwari,Are you able to hold it til Friday end of week?I have been busy with other projects I’ll get it updated.Let me know and thank you so much!Best,Carlos ValenzuelaOn Jun 18, 2024, at 11:03 AM, Ishwari Garge ***@***.***> wrote:﻿
@Carloscode5 This issue is being unassigned due to lack of activity.

**Comment by mamtawardhani** [comment]
@Carloscode5, would you be able to submit an entry for this issue by the end of this week? If yes, I'll re-assign it to you, but let me know only if you are confident about the deadline for submission. 😃

**Comment by cigar-galaxy82** [comment]
I would to work on this issue

**Comment by mamtawardhani** [comment]
@cigar-galaxy82 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
