### ISSUE TITLE
[Entry] Subject: Stash under git

### ISSUE THREAD

**Issue by Vidip-Ghosh** [Codecademy/docs#3708]
### Reason/inspiration (optional)

I would like to add information about the use of `git stash` in GitHub. 
We use `git stash` whenever we want to switch between the branches with the changes being done. Stash saves our work in a working directory. So, our changes doesn't get lost. 
Kindly assign this to me under hacktoberfest. 

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Khalid-debugg** [comment]
assign this to me, please

**Comment by parthasdey2304** [comment]
would you please assign that issue to me.

**Comment by SSwiniarski** [comment]
@Vidip-Ghosh You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment]
@parthasdey2304, @Vidip-Ghosh created this issue and asked to be assigned. People are generally assigned to their own issues.

**Comment by parthasdey2304** [comment]
ok sir I understood.

**Comment by SSwiniarski** [comment]
Issue closed as it duplicated another issue.
