### ISSUE TITLE
[Edit]JavScritp: Data Types - Typo in BigInt Description

### ISSUE THREAD

**Issue by llbaker121** [Codecademy/docs#3720]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

The BigInt information on [JavaScript Data Types ](https://www.codecademy.com/resources/docs/javascript/data-types?page_ref=catalog)in  Docs needs to be updated to correctly show the values for the min/max integer values.  The 1 should not be in the superscript like it is now.  I can not get the mark up here to show it but for reference:

[integer limits and BigInt info from MDN web docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by SSwiniarski** [comment]
@mcamilletti1 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by mcamilletti1** [comment]
Ok awesome thanks! I came across this repo in the Codecademy Git & Github course :)
