### ISSUE TITLE
[Term Entry] Kotlin Strings .drop()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3722]
### Reason/inspiration (optional)

We would like a new term entry on the `drop()` method for Kotlin: [Strings](https://www.codecademy.com/resources/docs/kotlin/strings). The entry should go in a new file under `docs/content/kotlin/concepts/strings/terms/drop/drop.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```kotlin `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by MarkDGraham** [comment]
@codecademy-docs May I take this issue?

**Comment by MarkDGraham** [comment]
@SSwiniarski I came across this repo from a post on LinkedIn stating how to get experience with little work experience. They stated that GitHub's contribution is the most open and diverse way to get experience with professional code and resources. It also stated a list of resources to utilize for a first-time contributor citing this repo as the best contribution starter.
