### ISSUE TITLE
[Edit] CSS [Edit] CSS: cursor

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3739]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] We would like an edit to the CSS cursor concept. The entry lives in docs/content/css/concepts/cursor/cursor.md

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media (images, gifs) should accurately represent the existing code blocks in the example sections and fit in-line. ex: [See last image here](https://www.codecademy.com/resources/docs/html/attributes/title)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by DanWSDev** [comment]
Can you please assign this to me.

**Comment by KTom101** [comment]
@DanWSDev you're being assigned since you asked first. Please understand that this issue is asking for an image showing what the example in the code block would look like. 

Also, where did you find out about being able to contribute to Codecademy Docs?

**Comment by KTom101** [comment]
@Khalid-debugg Assignment is first-come-first-served. Please stay tuned for another issue to work on as we are always adding more issues.

**Comment by Mstanic05** [comment]
Can you assign this to me please!
