### ISSUE TITLE
[Edit] CSS [Edit] CSS: display

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3740]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] We would like an edit to the CSS display concept. The entry lives in docs/content/css/concepts/display/display.md

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media (images, gifs) should accurately represent the existing code blocks in the example sections and fit in-line. ex: [See last image here](https://www.codecademy.com/resources/docs/html/attributes/title)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by MarkDGraham** [comment]
@codecademy-docs May I resolve this issue?

**Comment by Kadif-Ravik** [comment]
I'd like to be assigned to this.

**Comment by Khalid-debugg** [comment]
Can you assign this to me, please?

**Comment by KTom101** [comment]
@Kadif-Ravik Since you're already assigned to three other issues. This will be assigned to the other contributor.

**Comment by KTom101** [comment]
@Khalid-debugg You're assigned.

**Comment by KTom101** [comment]
@Khalid-debugg Also know that this issue is only asking for you to add an image showing what the example in the code block would look like.

**Comment by Mstanic05** [comment]
Can you assign this to me!
