### ISSUE TITLE
[Edit] CSS [Edit] CSS Filter Functions: brightness()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3744]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] We would like an edit to a term within CSS Filter Functions. The term entry lives in docs/content/css/concepts/filter-functions/terms/brightness/brightness.md

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media (images, gifs) should accurately represent the existing code blocks in the example sections and fit in-line. ex: [See last image here](https://www.codecademy.com/resources/docs/html/attributes/title)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Atharva1723** [comment]
Can I work on this issue ?

**Comment by KTom101** [comment]
@Atharva1723 You're assigned. Please note that this issue is only asking for you to add an image showing what the example in the code block would look like.

**Comment by Atharva1723** [comment]
@KTom101  But how will the users will be able to see difference in the image due to brightness ? The increase in the brightness will not affect the image ?

**Comment by Mstanic05** [comment]
Can you assign this to me!

**Comment by ishg-153** [comment]
> @KTom101 But how will the users will be able to see difference in the image due to brightness ? The increase in the brightness will not affect the image ?

Hi @Atharva1723, I'd suggest that you display the image as is and then with the brightness filter applied to show the difference. If you have any other ideas feel free to run with that. I hope this helps!

**Comment by Atharva1723** [comment]
> > @KTom101 But how will the users will be able to see difference in the image due to brightness ? The increase in the brightness will not affect the image ?
> 
> Hi @Atharva1723, I'd suggest that you display the image as is and then also with the brightness filter applied to show the difference. If you have any other idea feel free to run with it. I hope this helps!

I have tried doing that but the image is not affected In short the differences are very minor and not visible . I have tried black image and red

**Comment by ishg-153** [comment]
> I have tried doing that but the image is not affected In short the differences are very minor and not visible . I have tried black image and red

I understand. Can you try with a couple of different images, with different colors. You can increase the brightness percentage if need be. Just make sure to update that in the example code block.

**Comment by ishg-153** [comment]
Hey @Atharva1723. How far along are you with this edit entry?  

**Note:** If you don't respond with a PR or an update within a week, this issue will be unassigned from you.
