### ISSUE TITLE
[Edit] CSS [Edit] CSS Filter Functions: contrast()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3745]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] We would like an edit to a term within CSS Filter Functions. The term entry lives in docs/content/css/concepts/filter-functions/terms/contrast/contrast.md

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media (images, gifs) should accurately represent the existing code blocks in the example sections and fit in-line. ex: [See last image here](https://www.codecademy.com/resources/docs/html/attributes/title)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by 08Uzair** [comment]
Please assign this to me  i will complete my  work in 1-2 hrs

**Comment by kazmanii** [comment]
I would like to work on this task

**Comment by KTom101** [comment]
@08Uzair You're assigned. Know that this issue is only asking for you to add an image showing what the code block example would look like.

Is this your first contribution to Codecademy Docs? If so, could you let us know where you learned about contributing to Codecademy Docs?

**Comment by 08Uzair** [comment]
Can you explain this issue more  clearly as said I navigated to the given path` docs/content/css/concepts/filter-functions/terms/contrast/contrast.md `here i am not seeing code block example where i have been asked to add am image

**Comment by 08Uzair** [comment]
Can you explain this issue more clearly as said I navigated to the given path`
    docs/content/css/concepts/filter-functions/terms/contrast/contrast.md `here i am not seeing code block example where i
    have been asked to add am image

**Comment by Mstanic05** [comment]
Can you assign this to me!

**Comment by KTom101** [comment]
@08Uzair It's for the code block under the subheading named "Example 1". You're to add an image showing what the contrast would look like at 200%.

**Comment by KTom101** [comment]
@Mstanic05 This is currently assigned. Please check back regularly for [unassigned issues](https://github.com/Codecademy/docs/issues?page=1&q=is%3Aissue+is%3Aopen+no%3Aassignee).

**Comment by ishg-153** [comment]
@08Uzair Since there was no response from your end, I am unassigning you.

**Comment by AlaTino** [comment]
Hi, I would like to work on this issue as my project for the **Learn Git & GitHub** course

**Comment by ishg-153** [comment]
@AlaTino You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. I hope you have fun!
