### ISSUE TITLE
[Edit] Subject: Fix Typo

### ISSUE THREAD

**Issue by sneha-github96** [Codecademy/docs#3780]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

Fix typo in the description of [Corner Radius](https://www.codecademy.com/resources/docs/uiux/corner-radius) doc.
The corner radius indicates the amount of rounding on the **cornders** of a shape. 

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by sneha-github96** [comment]
Please assign it to me.

**Comment by dakshdeepHERE** [comment]
@sneha-github96 You are assigned ! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!
