### ISSUE TITLE
[Suggestion] Adding a CODEOWNERS file 

### ISSUE THREAD

**Issue by CBID2** [Codecademy/docs#3789]
### Actual Behavior

This isn’t a bug issue, but I’m thinking it would beneficial to add a CODEOWNERS.yml file to this repository 

## Benefits
This would make it easier for the maintainers to automatically assigned to issues related to reviewing the content or fixing bug without having to scramble through GitHub notifications. 

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by yuduth8899** [comment]
Hi... Please assign this issues to me

**Comment by CBID2** [comment]
> Hi... Please assign this issues to me

I want to work on this @yuduth8899

**Comment by yuduth8899** [comment]
i want to work on this

**Comment by CBID2** [comment]
> i want to work on this

Hi @yuduth8899. I expressed interest in working on this myself.

**Comment by SSwiniarski** [comment]
I'm closing this as it doesn't seem to sync with our current workflow.
