### ISSUE TITLE
[Term Entry] Kotlin Datetime .daysUntil()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3811]
### Reason/inspiration (optional)

We would like a new term entry on the `.daysUntil()` method for Kotlin: [Datetime](https://www.codecademy.com/resources/docs/kotlin/datetime). The entry should go in a new file under `docs/content/kotlin/concepts/datetime/terms/daysUntil/daysUntil.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```kotlin `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by AlstrupJacob** [comment]
hi id like to handle this issue please

**Comment by AlstrupJacob** [comment]
#3827

**Comment by SSwiniarski** [comment]
@AlstrupJacob I am assigning this issue to you, but I should note that you should _never_ submit a PR before being officially assigned an issue, if another person had asked to claim this issue, we might have had to reject your PR.

**Comment by AlstrupJacob** [comment]
> @AlstrupJacob I am assigning this issue to you, but I should note that you should _never_ submit a PR before being officially assigned an issue, if another person had asked to claim this issue, we might have had to reject your PR.

im sorry, i understand
