### ISSUE TITLE
[Term Entry] Kotlin Datetime .Month()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3813]
### Reason/inspiration (optional)

We would like a new term entry on the `.Month()` method for Kotlin: [Datetime](https://www.codecademy.com/resources/docs/kotlin/datetime). The entry should go in a new file under `docs/content/kotlin/concepts/datetime/terms/Month/Month.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```kotlin `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by DanWSDev** [comment]
can you please assign me to this please.

**Comment by SSwiniarski** [comment]
@DanWSDev you've been assigned the maximum of three issues. Please submit PRs for the issues you've been assigned before asking to claim any more.

**Comment by philipphdt** [comment]
@SSwiniarski Hi, could you please assign this issue to me? I'd like to work on it for my Codecademy project.

**Comment by KTom101** [comment]
@philipphdt You're assigned. Thank you for taking the time to look at the documentation. If you haven't already, please also take a look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).

Is this your first contribution to Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by philipphdt** [comment]
@KTom101 Hi Kyra, thank you! Yes, this is my first contribution to the documentation. It's actually a project task for my "Codecademy iOS Developer Career Path."
