### ISSUE TITLE
[Term Entry] Kotlin Datetime .plus()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3818]
### Reason/inspiration (optional)

We would like a new term entry on the `.plus()` method for Kotlin: [Datetime](https://www.codecademy.com/resources/docs/kotlin/datetime). The entry should go in a new file under `docs/content/kotlin/concepts/datetime/terms/plus/plus.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```kotlin `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by christopher-spencer** [comment]
I'm down to work on this!

**Comment by dakshdeepHERE** [comment]
@christopher-spencer  You're assigned! 🚀You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by telfort92** [comment]
Hello I would like to work on this issue

**Comment by dakshdeepHERE** [comment]
@telfort92 this issue is already claimed

**Comment by imsumith01** [comment]
@dakshdeepHERE Hi! Not seeing anybody assigned to this, can I take it?

**Comment by dakshdeepHERE** [comment]
@telfort92 You're assigned! 🚀You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by dakshdeepHERE** [comment]
I think the last assigned author deleted their comment so I'm assigning this to you @telfort92. If @telfort92 fails to push PR for this @imsumith01 we will assign it to you. Feel free to check other issues for now. ☺️🚀

**Comment by telfort92** [comment]
@dakshdeepHERE I came across this repo as part of my IOS dev career path on Codecademy. It's my first time contributing, so I have no idea (yet) of what I'm doing. But I'm willing to take on the challenge. if you could show me an example of what exactly I'm supposed to do, I will then do the rest.

**Comment by telfort92** [comment]
Already got an idea, I will submit the PR over the weekend.

**Comment by SSwiniarski** [comment]
@imsumith01 do you still want to claim this issue?

**Comment by andersooi** [comment]
Hello, I am interested in taking on this issue. Is it possible to assign it to me?

**Comment by dakshdeepHERE** [comment]
@SSwiniarski if @imsumith01 doesn't take this issue then we can assign @andersooi.

**Comment by SSwiniarski** [comment]
@imsumith01 has had long enough to reply. @andersooi, you're assigned!
