### ISSUE TITLE
[Edit] Kotlin: removePrefix - fix entry style

### ISSUE THREAD

**Issue by IvanT98** [Codecademy/docs#3820]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

The Kotlin [removePrefix](https://www.codecademy.com/resources/docs/kotlin/strings/removePrefix) method term entry needs to be updated to match the overall style of the other term entries for Kotlin Strings.

I propose to do the following:
- Add the missing dot to the mentions of the removePrefix method in the description and example (3 occurrences in total, ```removePrefix``` should be ```.removePrefix```).
- Simplify syntax code snippet from ```val modifiedString = originalString.removePrefix(prefixToRemove)``` to ```String.removeSuffix(suffix)```.
- Update variables names in the syntax section to match the new snippet.
- Update example code snippet to use the same originalString variable value ("HelloWorld.jpg") as the [removeSuffix](https://www.codecademy.com/resources/docs/kotlin/strings/removeSuffix) method term entry page. The example code snippet will also be updated to reflect the change to the originalString variable.
- (Optional) Remove empty line between suffix and modifiedString variables in the example code snippet and add an empty line after the modifiedString variable to honor [Kotlin style guide](https://developer.android.com/kotlin/style-guide#vertical).

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by IvanT98** [comment]
I would be happy to also fix the issue

**Comment by SSwiniarski** [comment]
@IvanT98 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by IvanT98** [comment]
@SSwiniarski Thank you.

I have came across this repo while doing the "Collaborating with the GitHub Community" part of the Codeacademy "Learn Git & GitHub" course
