### ISSUE TITLE
[CSS Styling on project task] Subject: Learn Git & GitHub Module

### ISSUE THREAD

**Issue by AniitaYoung** [Codecademy/docs#3835]
### Reason/inspiration (optional)

Whilst trying to do this project when I click on the expand button of one of the options the text is so large that it takes up a lot of space and isn't consistent with the other boxes styling. 

Please see image attached. 
<img width="817" alt="Screenshot 2023-11-01 112728" src="https://github.com/Codecademy/docs/assets/140521143/eb9953df-1f4b-4aab-84e4-adbdf2b71f85">

As I am also on the part of the course that requires me to contribute to a Codecademy Doc, please can this be assigned to me as all other issues are too advanced/already assigned :) 

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by AniitaYoung** [comment]
Please can this be assigned to me :)

**Comment by KTom101** [comment]
@AniitaYoung This repository is only for content on Codecademy Docs. At this time community contributors can't make changes to the lessons/modules. 

I have passed on your feedback to the team.

cc @HishamT
