### ISSUE TITLE
[Edit] Markdown: Paragraphs

### ISSUE THREAD

**Issue by pikkukurkku** [Codecademy/docs#3852]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

I have noticed a typo in the text. I would love to work on it as my very first contribution. 

![image](https://github.com/Codecademy/docs/assets/143491239/9c13c150-5fcd-4f9c-95b4-35f1987b3013)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by pikkukurkku** [comment]
Please assign to me.

**Comment by dakshdeepHERE** [comment]
@pikkukurkku  You're assigned. Thank you for taking the time to look at the documentation. If you haven't already, please also take a look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).

Is this your first contribution to Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by pikkukurkku** [comment]
Thank you for assigning. It's one of the exercises in the Learn GitHub: Best Practices course.
