### ISSUE TITLE
[Entry] Create Git reset command 

### ISSUE THREAD

**Issue by Pandz18** [Codecademy/docs#386]
## Description

Hey, I would like to create a file for the `git reset` command.

## Type of Entry Request

- One or more new entries/terms requested.

## Checklist

- [X] The issue is appropriately titled.
- [X] Description is clear and includes supporting text, files, etc.
- [X] A similar issue hasn't already been created.
- [X] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by Dusch4593** [comment]
@Pandz18 after we've finished with #374 you can go ahead and work on this one!

**Comment by Dusch4593** [comment]
Hi @Pandz18! How are you? 😄 Just wanted to check in and ask if you were still working on a PR for this issue?

**Comment by Pandz18** [comment]
> Hi @Pandz18! How are you? 😄 Just wanted to check in and ask if you were still working on a PR for this issue?

Hi @Dusch4593 , I'm great and how about you? Yes I'm trying to work on the issue but I'm currently busy with my University exams, as soon as I'm done, I'll try to finish as soon as possible. Sorry for the inconvenience.

**Comment by aedwardg** [comment]
This looks like it was closed in #514

**Comment by Dusch4593** [comment]
> This looks like it was completed in #514

Good catch! 😌 This issue wasn't linked to the PR, which is why it didn't close when #514 was merged. Closing now.
