### ISSUE TITLE
[Term Entry] Kotlin Datetime .todayIn()

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#3866]
### Reason/inspiration (optional)

We would like a new term entry on the `.todayIn()` method for Kotlin: [Datetime](https://www.codecademy.com/resources/docs/kotlin/datetime). The entry should go in a new file under `docs/content/kotlin/concepts/datetime/terms/todayIn/todayIn.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```kotlin `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by aa-arroyo** [comment]
Hi, I would like to work on this. Could you assign this task to me?

**Comment by ishg-153** [comment]
@aa-arroyo You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by aa-arroyo** [comment]
I have been learning/practicing on Codecademy for a few years now (on and off). I am currently working on the "Learn Git & GitHub" course, which is the reason I am here today.

I appreciate the opportunity to work on this task.

**Comment by aa-arroyo** [comment]
Hi. Do I have to submit a PR if I wish for someone to see if my entry looks okay and point out mistakes? It is my first time working with Kotlin, and I want to avoid submitting an entry with fundamental errors. If possible, I would like guidance based on my latest commit/push (3aae63d).

Thank you.

**Comment by ishg-153** [comment]
> Hi. Do I have to submit a PR if I wish for someone to see if my entry looks okay and point out mistakes? It is my first time working with Kotlin, and I want to avoid submitting an entry with fundamental errors. If possible, I would like guidance based on my latest commit/push ([3aae63d](https://github.com/Codecademy/docs/commit/3aae63d99646c031573bc4085642079f087a7797)).
> 
> Thank you.

Hey @aa-arroyo! Yes, you can submit a PR and we can suggest changes to it if necessary.
