### ISSUE TITLE
[Term Entry] Kotlin Datetime .toInstant()

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#3867]
### Reason/inspiration (optional)

We would like a new term entry on the `.toInstant()` method for Kotlin: [Datetime](https://www.codecademy.com/resources/docs/kotlin/datetime). The entry should go in a new file under `docs/content/kotlin/concepts/datetime/terms/toInstant/toInstant.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```kotlin `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by leoclarkribeiro** [comment]
Hi there, can I please be assigned to this issue?
Thank you.

**Comment by ishg-153** [comment]
@leoclarkribeiro You're assigned!🎉  You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by leoclarkribeiro** [comment]
Great! Thanks, @ishg-153 👍 
I am on the Front-End Engineer career path and decided to take the Git & Github course to make sure I learn about the real-world workflow of coding.
That's how I got here :)

**Comment by leoclarkribeiro** [comment]
Hello again,
I have submitted my 1st pull request.
I have to be honest. This was a very cool exercise and I enjoyed it a lot.

But it was a bit overwhelming knowing that these were real Codecademy documents and that I had no knowledge about the subject of the documents.

So, the content is not mine.
I just copied from Kotlin lang Org.

I hope that is ok.
I am looking forward to the team's feedback.
Cheers!

**Comment by ishg-153** [comment]
Hey @leoclarkribeiro! It's great that you enjoyed contributing to docs and I can understand how it can be overwhelming. But we expect contributors to create original content and not use plagiarised work. However, it is completely fine to use other resources to help develop your entry. I would recommend that you edit your current PR and then we will move forward with its review.

**Comment by leoclarkribeiro** [comment]
> Hey @leoclarkribeiro! It's great that you enjoyed contributing to docs and I can understand how it can be overwhelming. But we expect contributors to create original content and not use plagiarised work. However, it is completely fine to use other resources to help develop your entry. I would recommend that you edit your current PR and then we will move forward with its review.

Great! Thanks, @ishg-153.
I have edited and revised the entry and current PR.
Please let me know if I need to do anything else.
