### ISSUE TITLE
[Concept Entry] Kotlin Serialization

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#3868]
### Reason/inspiration (optional)

We would like a new concept entry for Kotlin about the serialization standard library. The entry should go in a new file in docs/content/kotlin/concepts/serialization/serialization.md

The entry should
- Have an introductory paragraph about the concept.
- Code block(s) displaying different aspects of the concept.
- A concluding header, Functions, future terms will be listed below this header

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Kadif-Ravik** [comment]
Id like to be assigned to this.

**Comment by ishg-153** [comment]
@Kadif-Ravik You're assigned!🎉 

I see that you have another issue assigned to you that still has an open PR. Make sure to keep working on that as well. 

**Note:** This is your third assigned issue. Make sure to create PRs for these issues before requesting more.

**Comment by Kadif-Ravik** [comment]
@SSwiniarski Yes, sorry for the delay.
