### ISSUE TITLE
[Term Entry] Kotlin Serialization .decodeFromByteArray()

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#3869]
### Reason/inspiration (optional)

We would like a new term entry on the `.decodeFromByteArray()` method for Kotlin: [Serialization](https://www.codecademy.com/resources/docs/kotlin/serialization). The entry should go in a new file under `docs/content/kotlin/concepts/serialization/terms/decodeFromByteArray/decodeFromByteArray.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```kotlin `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Fejiro001** [comment]
would love to take this issue, thank you

**Comment by ishg-153** [comment]
@Fejiro001 You're assigned!🎉

I see this is your third assigned live issue. Make sure to create PRs for these issues before requesting more.

**Comment by SSwiniarski** [comment]
@Fejiro001 note there was an error in the original issue. Entry should be located at `docs/content/kotlin/concepts/serialization/terms/decodeFromByteArray/decodeFromByteArray.md`.

**Comment by Fejiro001** [comment]
> @Fejiro001 note there was an error in the original issue. Entry should be located at `docs/content/kotlin/concepts/serialization/terms/decodeFromByteArray/decodeFromByteArray.md`.

Ok
I'll change location of the file and create a pull request for it

**Comment by SSwiniarski** [comment]
@Fejiro001 It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by Fejiro001** [comment]
> @Fejiro001 It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

Sorry, yes I am.  By tomorrow I will send a pull request
