### ISSUE TITLE
[Entry] Python: String Methods isupper() and islower()

### ISSUE THREAD

**Issue by balapriyac** [Codecademy/docs#387]
## Description

I found that the existing docs on Python strings has entries for `lower()` and `upper()` methods. 
It would be good to add the related methods `islower()` and `isupper()` for checking if all characters in the string are in lower case or upper case, respectively.

## Type of Entry Request

- One or more new entries/terms requested.

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by balapriyac** [comment]
Hi @Dusch4593, it was suggested by one of the reviewers on the team that it would be good to get an issue assigned, and then start working on it. I just submitted this issue. It would be great if you could assign me this one. Thank you.

**Comment by Dusch4593** [comment]
@balapriyac Let's do it! Assigned!

**Comment by Dusch4593** [comment]
Hi @balapriyac! Just wanted to check in and ask if you were still working on a PR for this issue?

**Comment by balapriyac** [comment]
Hi @Dusch4593 , I'm sorry that I totally forgot about this. Apologies for the delay. Shall send in the PR soon.
