### ISSUE TITLE
[Term Entry] Kotlin Serialization .decodeFromString()

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#3871]
### Reason/inspiration (optional)

We would like a new term entry on the `.decodeFromString()` method for Kotlin: [Serialization](https://www.codecademy.com/resources/docs/kotlin/serialization). The entry should go in a new file under `docs/content/kotlin/concepts/serialization/terms/decodeFromString/decodeFromString.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```kotlin `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by phuongtrieu97coder** [comment]
I'd like to work on this issue

**Comment by ishg-153** [comment]
@phuongtrieu97coder You're assigned!🎉

**Comment by phuongtrieu97coder** [comment]
@ishg-153 I'm sorry I'm no longer being able to work on this issue. You can delete my comment from this issue

**Comment by ishg-153** [comment]
> @ishg-153 I'm sorry I'm no longer being able to work on this issue. You can delete my comment from this issue

No worries! Thanks for letting me know.

**Comment by christopher-spencer** [comment]
I can work on this if it's available!

**Comment by ishg-153** [comment]
@christopher-spencer You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

**Comment by SSwiniarski** [comment]
@christopher-spencer note there was an error in the original issue. Entry should be located at `docs/content/kotlin/concepts/serialization/terms/decodeFromString/decodeFromString.md`
