### ISSUE TITLE
[Concept Entry] Rust Strings

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#3875]
### Reason/inspiration (optional)

We would like a new concept entry for Rust about the strings. The entry should go in a new file in docs/content/rust/concepts/strings/strings.md

The entry should
- Have an introductory paragraph about the concept.
- Code block(s) displaying different aspects of the concept.
- A concluding header, Functions, future terms will be listed below this header

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by marjoriekohn** [comment]
Can I work on this issue?

**Comment by ishg-153** [comment]
@marjoriekohn You're assigned!🎉

**Note:** This is your third assigned issue. Make sure to create PRs for these issues before requesting more.

**Comment by dharniel45** [comment]
can I work on this issue @christian-dinh

**Comment by SSwiniarski** [comment]
@dharniel45 You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@dharniel45 It's been two weeks. Are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by dharniel45** [comment]
Yes I am still working on it @SSwiniarski

**Comment by SSwiniarski** [comment]
@dharniel45 Since it's been another week with no movement, this is being unassigned due to inactivity.

**Comment by dharniel45** [comment]
Hello @SSwiniarski could you please reassign, the week is not over yet. so I can make the submission. I am finally done

**Comment by SSwiniarski** [comment]
@dharniel45 I've reassigned you, please submit a PR within the next two days.

**Comment by SSwiniarski** [comment]
@dharniel45 I am unassigning you because no PR was forthcoming.

**Comment by SSwiniarski** [comment]
[Reposting issue](https://github.com/Codecademy/docs/issues/4206) to get rid of link to closed PR.
