### ISSUE TITLE
[Concept Entry] Rust Generics

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#3878]
### Reason/inspiration (optional)

We would like a new concept entry for Rust about the generics. The entry should go in a new file in docs/content/rust/concepts/generics/generics.md

The entry should
- Have an introductory paragraph about the concept.
- Code block(s) displaying different aspects of the concept.
- A concluding header, Functions, future terms will be listed below this header

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by marjoriekohn** [comment]
Can I work on this issue?

**Comment by ishg-153** [comment]
@marjoriekohn You're assigned!🎉

**Comment by ishg-153** [comment]
Hi @marjoriekohn! How far along are you with this entry? 

**Note:** If you don't respond with a PR or an update within a week, this issue will be unassigned from you.

**Comment by ishg-153** [comment]
@marjoriekohn This issue has been unassigned from you due to a lack of progress on the PR.

**Comment by SSwiniarski** [comment]
[Reposting](https://github.com/Codecademy/docs/issues/4207) issue to get rid of link to closed PR.
