### ISSUE TITLE
[Concept Entry] Rust Threads

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#3879]
### Reason/inspiration (optional)

We would like a new concept entry for Rust about the threads. The entry should go in a new file in docs/content/rust/concepts/threads/threads.md

The entry should
- Have an introductory paragraph about the concept.
- Code block(s) displaying different aspects of the concept.
- A concluding header, Functions, future terms will be listed below this header

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by marjoriekohn** [comment]
Can I work on this issue?

**Comment by ishg-153** [comment]
@marjoriekohn You're assigned!🎉

I see that you have other issues assigned to you that still have open PRs. Make sure to keep working on those as well.

**Comment by ishg-153** [comment]
Hi @marjoriekohn! I see you have this issue to work on as well. You can get in a PR for at least one of the issues to start with. 

**Note:** If you don't respond with a PR or an update within a week, this issue will be unassigned from you.

**Comment by andersooi** [comment]
Hi, I am interested in taking up this issue. Is it possible to assign this to me?
