### ISSUE TITLE
[Concept Entry] D3 Scaling

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#3881]
### Reason/inspiration (optional)

We would like a new concept entry for D3 about the scaling. The entry should go in a new file in docs/content/d3/concepts/scaling/scaling.md

The entry should
- Have an introductory paragraph about the concept.
- Code block(s) displaying different aspects of the concept.
- Add an image for the associated output if applicable
- A concluding header, Functions, future terms will be listed below this header

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by caupolicandiaz** [comment]
Closing this to fast-track this concept internally and avoid a bottleneck with the related entries
