### ISSUE TITLE
[Term Entry] D3 Scaling .range()

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#3887]
### Reason/inspiration (optional)

We would like a new term entry on the `.range()` method for [D3](https://www.codecademy.com/resources/docs/d3): Scaling. The entry should go in a new file under `docs/content/d3/concepts/scaling/terms/range/range.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```js `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by DanWSDev** [comment]
Can you assign this to me please.

**Comment by ishg-153** [comment]
@DanWSDev You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. 

Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

**Comment by vrun1208** [comment]
I want to take this one!

**Comment by ishg-153** [comment]
@vrun1208 You're assigned!🎉 

**Note:** This is your third assigned issue. Make sure to create PRs for these issues before requesting more.
