### ISSUE TITLE
[Term Entry] UI and UX Design UIUX (User Research) Competitive Analysis

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#3888]
### Reason/inspiration (optional)

We would like a new term entry on the `competitive-analysis` term for [UIUX](https://www.codecademy.com/resources/docs/uiux): Competitive Analysis. The entry should go in a new file under `docs/content/uiux/concepts/competitive-analysis/competitive-analysis.md`.

The entry should describe the term and how it is used. Be sure to include images to aid understanding, if required.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by DanWSDev** [comment]
Can you assign this to me please

**Comment by ishg-153** [comment]
@DanWSDev You're assigned!🎉

**Comment by SanchitMahajan236** [comment]
Can you please assign me this issue

**Comment by ishg-153** [comment]
@SanchitMahajan236 You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

**Comment by SSwiniarski** [comment]
@SanchitMahajan236 It's been over two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by christaton** [comment]
Hello @SSwiniarski, I'd like to be assigned to this for my first issue contribution. I'm working through the Learn GitHub course on Codecademy. Thanks!

**Comment by SSwiniarski** [comment]
@christaton You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!
