### ISSUE TITLE
[Term Entry] UI and UX Design UIUX (User Research) Focus Groups

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#3889]
### Reason/inspiration (optional)

We would like a new term entry on the `focus-group` term for [UIUX](https://www.codecademy.com/resources/docs/uiux): Focus group. The entry should go in a new file under `docs/content/uiux/concepts/focus-group/focus-group.md`.

The entry should describe the term and how it is used. Be sure to include images to aid understanding, if required.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by DanWSDev** [comment]
Can you assign this to me please

**Comment by ishg-153** [comment]
@DanWSDev You're assigned!🎉

**Note:** This is your third assigned issue. Make sure to create PRs for these issues before requesting more issues.

**Comment by ShatilKhan** [comment]
@ishg-153 please assign this one to me
I've made pr for my other assigned issue

**Comment by avdhoottt** [comment]
@ShatilKhan You're assigned! You can check out the Contribution Guide for additional information on contributing.
See Content Standards for an overview of styling tips that the Style Guide covers in detail.
After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.

If this is your first time contributing, can you let us know how you came across this repo?
