### ISSUE TITLE
[Term Entry] UI and UX Design UIUX (Ideation) Journey Maps

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3952]
### Reason/inspiration (optional)

We would like a new term entry on the `journey-map` term for [UIUX](https://www.codecademy.com/resources/docs/uiux): Journey Maps. The entry should go in a new file under `docs/content/uiux/journey-map/journey-map.md`.

The entry should describe the term and how it is used within UX. Be sure to include images to aid understanding of how journey maps look.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by SSwiniarski** [comment]
Closing this as it is a duplicate issue
