### ISSUE TITLE
[Term Entry] D3 Selection .selectAll()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3955]
### Reason/inspiration (optional)

We would like a new term entry on the `.selectAll()` method for [D3](https://www.codecademy.com/resources/docs/d3): Selection. The entry should go in a new file under `docs/content/d3/concepts/selection/terms/selectAll/selectAll.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```js `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by pravintargaryen** [comment]
@codecademy-docs assign this to me

**Comment by craglin** [comment]
@codecademy-docs I am looking for a topic for my first contribution. Based on my past experience with D3, I would be happy to make this contribution.

**Comment by KTom101** [comment]
@craglin Great, you're assigned! How did you find out about contributing to Codecademy Docs? 

In addition to the documents linked in the description, please also take a look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already. After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.

**Comment by craglin** [comment]
@KTom101 Thanks a bunch! I'm actually working my way through the Git training module with Codecademy and was browsing for issues that I could use for my portfolio project. I will be sure to review the guide to ensure my submission is in compliance.

**Comment by SSwiniarski** [comment]
@craglin It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.
