### ISSUE TITLE
[Edit] CSS Background: background-position

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#3979]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

(This a repost of an open issue because it couldn't be unlinked from a closed PR)

We would like an edit a term within the CSS Background entry. The entry lives in docs/content/css/concepts/background/terms/background-position/background-position.md

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:

1. Add supplemental media (preferred .png or .gif, <1MB).
2. Media (images, gifs) should accurately represent the existing code blocks in the example sections and fit in-line.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Grzesieg** [comment]
I'd like to work on that one.

**Comment by ishg-153** [comment]
@Grzesieg You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by SSwiniarski** [comment]
@Grzesieg It's been two weeks. Are you still working on this issue? In another week it will be unassigned due to inactivity.

**Comment by Grzesieg** [comment]
Hi, yes I will provide an update today.
