### ISSUE TITLE
[Entry Edit] JavaScript: Data Types

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#398]
## Description

Would someone be open to making some edits to the existing entry for JavaScript: Data Types, including:

* Replace usage of 1st- and 2nd-person pronouns with neutral, manual-like language.

* Perhaps one code block or code byte example of each data type?

_**Note** : Don't worry about the table in [the live page for Data Types](https://www.codecademy.com/resources/docs/javascript/data-types). We'll take care of that one! 😄_ 

## Type of Bug Request

- Typo and/or bug within one or more existing entries.
- Unclear explanation of term(s)

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by gracenn1998** [comment]
I think can take this one, could you please assign this to me?

**Comment by Dusch4593** [comment]
@gracenn1998 assigned! And yes, the link you provided points to the correct file that needs to be edited. 

P.S. If you haven't seen my updated comment already, the table no longer needs to be edited for this issue. We noticed that it's not rendering correctly on [the live web page](https://www.codecademy.com/resources/docs/javascript/data-types). But my team and I are gonna take a look at that. We'll just need your help with the following: 

Replace usage of 1st- and 2nd-person pronouns with neutral, manual-like language.

Perhaps one code block or code byte example of each data type?
