### ISSUE TITLE
[Topic Request] Data Science

### ISSUE THREAD

**Issue by noahpgordon** [Codecademy/docs#3989]
### Reason/inspiration (optional)

While most of the course topics on the main Codecademy page are Topics in Docs, the page on [Data Science](https://www.codecademy.com/resources/docs/general/data-science) is currently a Concept within [General](https://www.codecademy.com/resources/docs/general).

Considering the number of courses on data science within Codecademy, I think it makes sense to create a Topic for data science to boost visibility. This would also allow unifying a number of current Concepts and Terms within General under Data Science, such as [Database](https://www.codecademy.com/resources/docs/general/database), [Relational Database](https://www.codecademy.com/resources/docs/general/relational-database), [Semantic Technologies](https://www.codecademy.com/resources/docs/general/semantic-technologies), [XML](https://www.codecademy.com/resources/docs/general/xml), [CSV](https://www.codecademy.com/resources/docs/general/csv), and all the term pages within these.

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
@noahpgordon some of us maintainers had a discussion and we agreed that this is a good idea. Did you want to take on this issue?

**Comment by noahpgordon** [comment]
@SSwiniarski I'm happy to do it, but I probably won't edit the Data Science entry. I would just rearrange files from General.

**Comment by SSwiniarski** [comment]
@noahpgordon You're assigned. You don't have to edit the body of the Data Science entry, but we would like you to move it and edit the metadata to reflect a Topic. (The topic entry template is [here](https://github.com/Codecademy/docs/blob/main/documentation/topic-entry-template.md).)
