### ISSUE TITLE
[Term Entry] PHP Math Functions: octdec()

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#3994]
### Reason/inspiration (optional)

We would like a new term entry for [PHP Math Functions](https://www.codecademy.com/resources/docs/php/math-functions) about the `octdec()` function.

The entry should go under the file path: `docs/content/php/concepts/math-functions/terms/octdec/octdec.md` 

The entry should 

- Have a syntax section illustrating the function with a ` ```pseudo ` code block. 
- An example showing the function in a ` ```php ` code block. 
- A runnable codebyte example in a ` ```codebyte/php` block. 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by pravintargaryen** [comment]
@KTom101 please assign this to me

**Comment by avdhoottt** [comment]
@viktoriaseprenyi You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.
