### ISSUE TITLE
[Term Entry] JavaScript Dates: .toDateString()

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#3995]
### Reason/inspiration (optional)

We would like a new term entry for JavaScript [Dates](https://www.codecademy.com/resources/docs/javascript/dates) about the `.toDateString()` method. The entry should go in a new file in `docs/content/javascript/concepts/dates/terms/toDateString/toDateString.md`

The entry should
    - Have an introductory paragraph about what the method is and does.
    - Have a syntax section illustrating the function in a ` ```pseudo ` code block. 
    - An example showing the function in a ` ```js ` code block. 
    - A runnable codebyte example in a ` ```codebyte/javascript` block. 

    
Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by pravintargaryen** [comment]
@KTom101 assign this to me

**Comment by yeipkwa** [comment]
@KTom101 Hello, I am interested in working on this issue if it's still available. I am currently taking the introduction to open source course, and would love to get a little bit more practice by contributing to docs again.

**Comment by ishg-153** [comment]
@yeipkwa You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.
