### ISSUE TITLE
[Term Entry] JavaScript Dates: .toJSON()

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#3996]
### Reason/inspiration (optional)

We would like a new term entry for JavaScript [Dates](https://www.codecademy.com/resources/docs/javascript/dates) about the `.toJSON()` method. The entry should go in a new file in `docs/content/javascript/concepts/dates/terms/toJSON/toJSON.md`

The entry should
    - Have an introductory paragraph about what the method is and does.
    - Have a syntax section illustrating the function in a ` ```pseudo ` code block. 
    - An example showing the function in a ` ```js ` code block. 
    - A runnable codebyte example in a ` ```codebyte/javascript` block. 

    
Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by noahpgordon** [comment]
I'll do this.

**Comment by markhjensen** [comment]
Happy to try my hand at this

**Comment by ishg-153** [comment]
@noahpgordon You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

**Comment by ishg-153** [comment]
@markhjensen We appreciate your interest in contributing to Codecademy Docs but @noahpgordon asked to be assigned to this particular issue before you. Please feel free to look through [available issues](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+-label%3Aclaimed) and ask to be assigned to the ones you find interesting.
