### ISSUE TITLE
[Entry] JavaScript Dates: .toLocaleString()

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#3997]
### Reason/inspiration (optional)

We would like a new term entry for JavaScript [Dates](https://www.codecademy.com/resources/docs/javascript/dates) about the `.toLocaleString()` method. The entry should go in a new file in `docs/content/javascript/concepts/dates/terms/toLocaleString/toLocaleString.md`

The entry should:
    - Have an introductory paragraph about what the method is and does.
    - Have a syntax section illustrating the function in a ` ```pseudo ` code block. 
    - An example showing the function in a ` ```js ` code block. 
    - A runnable codebyte example in a ` ```codebyte/javascript` block. 

    
Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by pravintargaryen** [comment]
@KTom101 assign this to me

**Comment by viktoriaseprenyi** [comment]
@KTom101 Hello, please assign me to this, thank you! :)

**Comment by avdhoottt** [comment]
@pravintargaryen You're assigned!🚀You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

**Comment by avdhoottt** [comment]
@pravintargaryen You already have 4 issues claimed. Please create a PR for them and try to merge them to get assigned to any other issue.

**Comment by avdhoottt** [comment]
@prachika5 You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

**Comment by SSwiniarski** [comment]
@prachika5 It's been over two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@prachika5 This is being unassigned due to inactivity.

**Comment by brendlers** [comment]
@KTom101 I am interested in taking this isue on, I found out about Docs through the tutorial.

**Comment by brendlers** [comment]
@SSwiniarski  I am interested in taking this issue on, I found out about Docs through the tutorial.

**Comment by SSwiniarski** [comment]
@brendlers You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment]
@brendlers It's been two weeks. Are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by kpoultney** [comment]
If/when this entry goes inactive, may I claim it? Thank you :)

**Comment by brendlers** [comment]
Yes, you can claim it. Thank you in advance!
________________________________
Von: Kyleigh Poultney ***@***.***>
Gesendet: Montag, 29. Januar 2024 17:42
An: Codecademy/docs ***@***.***>
Cc: Sebastian R.R.T. Brendler ***@***.***>; Mention ***@***.***>
Betreff: Re: [Codecademy/docs] [Entry] JavaScript Dates: .toLocaleString() (Issue #3997)


If/when this entry goes inactive, may I claim it? Thank you :)

**Comment by SSwiniarski** [comment]
@kpoultney You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by kpoultney** [comment]
Thanks so much, getting started today!

**Comment by ishg-153** [comment]
@kpoultney Unassigning this issue as you won't be working on it anymore

**Comment by BiocideTM** [comment]
Can you assign this issue to me please?

**Comment by ishg-153** [comment]
@BiocideTM You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by BiocideTM** [comment]
Through the Git & GitHub course :)

**Comment by letsbuildanything** [comment]
@BiocideTM you've been unassigned due to inactivity.

**Comment by lamiaelhbari** [comment]
Hi **@ishg-153** , I'm interested in taking on this issue .

**Comment by letsbuildanything** [comment]
@lamiaelhbari you're assigned! 🎉
