### ISSUE TITLE
[Term Entry] JavaScript Dates: .toLocaleTimeString()

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#3998]
### Reason/inspiration (optional)

We would like a new term entry for JavaScript [Dates](https://www.codecademy.com/resources/docs/javascript/dates) about the `.toLocaleTimeString()` method. The entry should go in a new file in `docs/content/javascript/concepts/dates/terms/toLocaleTimeString/toLocaleTimeString.md`

The entry should:
    - Have an introductory paragraph about what the method is and does.
    - Have a syntax section illustrating the function in a ` ```pseudo ` code block. 
    - An example showing the function in a ` ```js ` code block. 
    - A runnable codebyte example in a ` ```codebyte/javascript` block. 

    
Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by pravintargaryen** [comment]
@KTom101 assign this to me

**Comment by mirashevaibhav** [comment]
I am intrested to take this issue on

**Comment by ishg-153** [comment]
@mirashevaibhav You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by ishg-153** [comment]
@pravintargaryen We don't assign more than 3 active issues at a time. Please submit PRs for existing ones before asking to be assigned to more issues.

**Comment by SSwiniarski** [comment]
@mirashevaibhav It's been over two weeks. Are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@mirashevaibhav This is being unassigned due to inactivity.

**Comment by Prathima-Goutham** [comment]
@KTom101 Kindly assign this to me. I am fairly new to the JavaScript. Still will do my best in taking a shot at creating toLocaleTimeString() function.

Thanks

**Comment by SSwiniarski** [comment]
@Prathima-Goutham You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by Prathima-Goutham** [comment]
[toLocalTimeString.md](https://github.com/Codecademy/docs/files/13831878/toLocalTimeString.md)
Kindly provide your feedback on above code. Not sure if the out put of the above file was expected output of this exercise. I would eagerly wait for your input.

Thanks

**Comment by SSwiniarski** [comment]
@Prathima-Goutham, this is not what you're supposed to do here. You are supposed to create a new branch on your copy of the repository, and write a new entry for this function, then submit a pull request for review. You may want to check out the the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md).

**Comment by SSwiniarski** [comment]
@Prathima-Goutham if we don't see a PR in a few days, this issue will be unassigned.

**Comment by Prathima-Goutham** [comment]
@SSwiniarski this issue has been completed and I can see its closed now. Kindly let me know if I have miss understood the process.

Thanks,
Prathima

**Comment by SSwiniarski** [comment]
@Prathima-Goutham can yo provide a link to the closed PR?

**Comment by Prathima-Goutham** [comment]
@SSwiniarski 
https://github.com/Codecademy/docs/compare/main...Prathima-Goutham:docs:Prathima-Goutham-patch-1

Please see this in here, I have done the code change which was verified.

**Comment by SSwiniarski** [comment]
@Prathima-Goutham, I linked the PR to this issue.

**Comment by mirashevaibhav** [comment]
> @mirashevaibhav You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.
> 
> I see this is your first time contributing to Codecademy Docs. How did you find out about us?
 
 Thanks for assigning this task for me
