### ISSUE TITLE
[Term Entry] JavaScript Dates: .toTimeString()

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#3999]
### Reason/inspiration (optional)

We would like a new term entry for JavaScript [Dates](https://www.codecademy.com/resources/docs/javascript/dates) about the `.toTimeString()` method. The entry should go in a new file in `docs/content/javascript/concepts/dates/terms/toTimeString/toTimeString.md`

The entry should:
    - Have an introductory paragraph about what the method is and does.
    - Have a syntax section illustrating the function in a ` ```pseudo ` code block. 
    - An example showing the function in a ` ```js ` code block. 
    - A runnable codebyte example in a ` ```codebyte/javascript` block. 

    
Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by pravintargaryen** [comment]
@KTom101 assign this to me

**Comment by ishg-153** [comment]
@pravintargaryen You already have 3 active issues assigned and one active PR. We can't assign you any more issues until you submit PRs for the existing ones.

**Comment by ishg-153** [comment]
@PRathamesh3013 You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by SSwiniarski** [comment]
@PRathamesh3013 It's been over two weeks. Are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@PRathamesh3013 This is being unassigned due to inactivity.

**Comment by avdhoottt** [comment]
@SSwiniarski I would like to complete this entry.

**Comment by SSwiniarski** [comment]
@avdhoottt You're assigned.
