### ISSUE TITLE
[Term Entry] PHP Array Functions: array_pad()

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#4000]
### Reason/inspiration (optional)

We would like a new term entry for [PHP Array Functions](https://www.codecademy.com/resources/docs/php/arrays) about the `.array_pad()` method. The entry should go in a new file in `docs/content/php/concepts/arrays/terms/array-pad/array-pad.md`

The entry should:
    - Have an introductory paragraph about what the method is and does.
    - Have a syntax section illustrating the function in a ` ```pseudo ` code block. 
    - An example showing the function in a ` ```php ` code block. 
    - A runnable codebyte example in a ` ```codebyte/php` block. 

    
Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by pravintargaryen** [comment]
@KTom101 assign this to me

**Comment by SSwiniarski** [comment]
@pravintargaryen It's been over two weeks. Are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by andersooi** [comment]
Hi! I'm interested in taking on this issue if it is available.

**Comment by SSwiniarski** [comment]
@andersooi, @pravintargaryen still has some time to produce a PR.

**Comment by SSwiniarski** [comment]
@pravintargaryen this is being unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@andersooi do you still want to claim this issue?

**Comment by andersooi** [comment]
Hi @SSwiniarski I’ve been assigned another issue. Is it okay to work on both issues or would you rather have me complete the other first?

**Comment by SSwiniarski** [comment]
@andersooi, You're assigned!
