### ISSUE TITLE
[Term Entry] UI and UX Design UIUX (Psychology) Fitt's Law

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4022]
### Reason/inspiration (optional)

"We would like a new term entry on the `fitts-law` term for [UIUX](https://www.codecademy.com/resources/docs/uiux): Fitt's Law. The entry should go in a new file under `docs/content/uiux/concepts/fitts-law/fitts-law.md`.

The entry should describe the term and how it is used within UX. Also include: 
- An "Example" section that explains fitt's law
- add images to aid understanding of fitt's law (if required).

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Abraham-Felix** [comment]
@codecademy-docs Hello, I would like to contribute to this issue. I got invited by Codecademy's LinkedIn profile to Docs.

**Comment by avdhoottt** [comment]
@Abraham-Felix You're assigned!🚀 You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by Abraham-Felix** [comment]
> @Abraham-Felix You're assigned!🚀 You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md) for additional information on contributing. See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail. After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
> 
> In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!
> 
> If this is your first time contributing, can you let us know how you came across this repo?

Fantastic! I appreciate you entrusting me with this assignment. 🙂 Rest assured, I'll give it my all, and please don't hesitate to provide corrections as needed to ensure it aligns perfectly with the company standards.

I discovered this documentation as a result of the following comment --> [Linkedin's Comment](https://www.linkedin.com/feed/update/urn:li:activity:7137961092969832448?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7137961092969832448%2C7137975739018092544%29&replyUrn=urn%3Ali%3Acomment%3A%28activity%3A7137961092969832448%2C7138169076861816834%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287137975739018092544%2Curn%3Ali%3Aactivity%3A7137961092969832448%29&dashReplyUrn=urn%3Ali%3Afsd_comment%3A%287138169076861816834%2Curn%3Ali%3Aactivity%3A7137961092969832448%29)

**Comment by SSwiniarski** [comment]
@Abraham-Felix It's been over two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by DGonzo512** [comment]
Hello, I would like to work on this issue. Thank you!

**Comment by SSwiniarski** [comment]
@DGonzo512 It's been two weeks. Are you still working on this issue? Note that in another week this will be unassigned due to inactivity.

**Comment by DGonzo512** [comment]
Working on this! I had a work issue pop up that pulled me away, but I will have it completed.

**Comment by DGonzo512** [comment]
PR added!
