### ISSUE TITLE
[Term Entry] UI and UX Design UIUX (Psychology) Hick's Law

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4023]
### Reason/inspiration (optional)

"We would like a new term entry on the `hicks-law` term for [UIUX](https://www.codecademy.com/resources/docs/uiux): Hick's Law. The entry should go in a new file under `docs/content/uiux/concepts/hicks-law/hicks-law.md`.

The entry should describe the term and how it is used within UX. Also include: 
- An "Example" section that explains hick's law
- add images to aid understanding of hick's law (if required).

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by A-Kiwams** [comment]
Can you assign me this issue? Already working on one and about finishing.

**Comment by A-Kiwams** [comment]
Noted

**Comment by A-Kiwams** [comment]
Regarding the statement, "add images to aid understanding of hick's law (if required)."

Can the image be picked up online and referenced? or should it be designed from scratch? @avdhoottt

**Comment by ishg-153** [comment]
Hey @A-Kiwams! If you are going to use a diagram, design it from scratch. But if it's an image of a website that you will modify to show how Hicks law works, I'd say try to use screenshots from the Codecademy website to avoid any issues. I hope that answers your question.

**Comment by A-Kiwams** [comment]
Alright. Thanks.

**Comment by SSwiniarski** [comment]
@A-Kiwams It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by A-Kiwams** [comment]
On it

**Comment by SSwiniarski** [comment]
@A-Kiwams This is being unassigned due to inactivity.

**Comment by CBID2** [comment]
I'll do it @SSwiniarski

**Comment by SSwiniarski** [comment]
@CBID2, you're assigned!

**Comment by alopezgurria** [comment]
Hi @KTom101! As previously discussed, @CBID2 is giving up this issue, can I be assigned on it?

**Comment by KTom101** [comment]
@alopezgurria You're assigned. Please look at the documentation linked in the description as well as the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already.  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Also, is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by alopezgurria** [comment]
> @alopezgurria [...] Also, is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

@KTom101 Thank you so much. Yes thus is my first contribution. I am studying Codecademy iOs dev path.
