### ISSUE TITLE
[Entry Request] General: What is Functional Programming?

### ISSUE THREAD

**Issue by aweliego** [Codecademy/docs#404]
## Description

I would like to create a "What is Functional Programming?" entry in the General topic.

General topic: https://www.codecademy.com/resources/docs/general

## Type of Entry Request

- One or more new entries/terms requested.

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by aweliego** [comment]
Would love to work on that, if someone can assign it to me as I understood that's the best practice :)

**Comment by Dusch4593** [comment]
@aweliego You got it! Assigned!
