### ISSUE TITLE
[Edit] documentation/style-guide.md - Demonstrate image tag best practices

### ISSUE THREAD

**Issue by Jamesllllllllll** [Codecademy/docs#4050]
### Type of Edit (select all that apply)

Clarify unclear content and/or terms

### Description (optional)

**It would be helpful to include the desired image tag qualities in the Style Guide.** 

The [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) and [Curriculum Markdown Style Guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) do not demonstrate best practices for using the Markdown **image tag**.

The full options for a Markdown image tag are described in this example:

```md
![Alt text](https://example.url "Title text")
```

I have written some entries that have been accepted that have both _descriptive_ and _non-descriptive_ Alt text.

For example: I added and image to the [Keyframes entry](https://github.com/Codecademy/docs/blob/main/content/css/concepts/animations/terms/keyframes/keyframes.md) with non-descriptive Alt text and I included Title text:

```md
![Keyframes example 1](https://raw.githubusercontent.com/Codecademy/docs/main/media/css-keyframes-example-1.gif 'Keyframes example 1')
```

---

**Given my recent experience contributing to the Codecademy Docs, it seems that descriptive Alt text and no Title text is desired.** 

I would suggest adding something like this under [Writing Entries](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md#writing-entries):

- Image tags must use Alt text that describes the image and not include title text after the url:
  - Good: `![Descriptive Alt Text](https://example.url)`
  -  Bad: `![Non-descriptive Alt Text](https://example.url "Example image")`

I would like to work on this issue if it is accepted.

### Code of Conduct

- [x] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Kadif-Ravik** [comment]
can i get this one?

**Comment by PatrickOlaniyan** [comment]
@Jamesllllllllll I am interested in taking this issue on,

**Comment by Jamesllllllllll** [comment]
Hey @yangc95 & @SSwiniarski - do suggestions like this get discussed & resolved here in the repo issues? If not I can close the issue.

Thanks

**Comment by SSwiniarski** [comment]
@Jamesllllllllll I've asked the team about this, we'll get back when there's a consensus.

**Comment by SSwiniarski** [comment]
@Jamesllllllllll We agree that this should be added to the style guide. Here's language from our in-house style guide:

> Be as descriptive as possible for diagrams and gifs, particularly when they exemplify new concepts. Don’t worry about making alt text too long; alt text should be as long as it needs to be!

Did you want to be assigned this?

**Comment by Jamesllllllllll** [comment]
> @Jamesllllllllll We agree that this should be added to the style guide. Here's language from our in-house style guide:
> 
> > Be as descriptive as possible for diagrams and gifs, particularly when they exemplify new concepts. Don’t worry about making alt text too long; alt text should be as long as it needs to be!
> 
> Did you want to be assigned this?

Sure! I will work on this in a new PR.

**Comment by SSwiniarski** [comment]
@Jamesllllllllll, you're assigned.

@mirarad, @PatrickOlaniyan we generally give assignments to user-submitted issues first to the author if they want it.
