### ISSUE TITLE
[Edit] CSS [Edit] CSS Position: left()

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#4072]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] We would like an edit to a term within CSS Position. The term entry lives in docs/content/css/concepts/position/terms/left/left.md

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media (images, gifs) should accurately represent the existing code blocks in the example sections and fit in-line. ex: [See last image here](https://www.codecademy.com/resources/docs/html/attributes/title)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Kadif-Ravik** [comment]
can i take this one

**Comment by ishg-153** [comment]
@Kadif-Ravik You already have three active assigned issues. That's the maximum we assign at a time. Please create PRs for these issues before asking to be assigned to more.

**Comment by bpashley95** [comment]
Could I take this edit please? :)

**Comment by ishg-153** [comment]
@bpashley95 You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by johnnylau1011** [comment]
Please assign me!

**Comment by scottfinamore** [comment]
Still looking for my first issue to complete, I would like to try this if its still available. Thank you.

**Comment by SSwiniarski** [comment]
@johnnylau1011 It's been two weeks. Are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by jamesrosenrosen** [comment]
Can I be assigned to this please?
=======================

Still looking for my first edit.

**Comment by jamesrosenrosen** [comment]
I have had no time to work on this, please feel free to reassign if there is interest.

**Comment by Jamesllllllllll** [comment]
Hey @SSwiniarski - since @jamesrosenrosen asked for this issue to be reassigned, could I take this one on?

Thanks

**Comment by ishg-153** [comment]
Hey @jamesrosenrosen, unassigning you as per your request.

**Comment by ishg-153** [comment]
@Jamesllllllllll are you still interested in taking on this issue?

**Comment by jamesrosenrosen** [comment]
No thank you.On 15 May 2024, at 08:42, Ishwari Garge ***@***.***> wrote:﻿
@Jamesllllllllll are you still interested in taking on this issue?

**Comment by lmaszuchin** [comment]
Hello, I would like to be assigned this please as I wish to complete it for credit to my git/github course.
Thank you

**Comment by Jamesllllllllll** [comment]
Hey @ishg-153 - I will pass on this one. Please go ahead and assign it to @lmaszuchin

**Comment by letsbuildanything** [comment]
@lmaszuchin You’re assigned :tada:  In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.
Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by molivier1988** [comment]
I'm currently doing the Front End Web Development and git courses, so being able to contribute here would be a great learning experience but I can see there's lots of volunteers in this thread. But I'll ask anyway, please can I be assigned to this task?

**Comment by ishg-153** [comment]
@lmaszuchin it's been 3weeks. Please revert within 2 days if you are working on this issue.

**Comment by ishg-153** [comment]
@molivier1988 If @lmaszuchin doesn't respond will you still be interested in taking this on?

**Comment by molivier1988** [comment]
Yes I would love to.

Thanks

**Comment by ishg-153** [comment]
@lmaszuchin You are being unassigned due to lack of activity.

**Comment by ishg-153** [comment]
@molivier1988 You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. I hope you have fun!

**Comment by ishg-153** [comment]
@molivier1988 It's been 2 weeks. Are you working on this issue?

**Comment by ishg-153** [comment]
@molivier1988 Unassigning you.

**Comment by Sahan-A-2003** [comment]
can I be assign to this issue

**Comment by ishg-153** [comment]
@Sahan-A-2003 You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by Sahan-A-2003** [comment]
I find out about codecademy by YouTube.

**Comment by Sriparno08** [comment]
Hey @Sahan-A-2003, it's been two weeks and there's no PR from your side. Are you still working on this issue?

**Comment by Sriparno08** [comment]
Hey @Sahan-A-2003, you are unassigned due to inactivity.

**Comment by Diyana-nikk** [comment]
Hi can I claim this?

**Comment by chmstpromotheus** [comment]
Hi,

I would like to claim issue #4072. 

Thanks in advance,

Mahammad

**Comment by Sriparno08** [comment]
Hey @Diyana-nikk, you're assigned!

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Hey @chmstpromotheus, the current assignee is assigned for claiming the issue first. Please go through the 'Issues' tab and claim another issue that interests you. Remember that issues are assigned on a first-come-first-serve basis.
