### ISSUE TITLE
[Edit] CSS [Edit] CSS Position: position()

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#4073]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] We would like an edit to a term within CSS Position. The term entry lives in docs/content/css/concepts/position/terms/position/position.md

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media (images, gifs) should accurately represent the existing code blocks in the example sections and fit in-line. ex: [See last image here](https://www.codecademy.com/resources/docs/html/attributes/title)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Kadif-Ravik** [comment]
id like this one

**Comment by ishg-153** [comment]
@Kadif-Ravik You're assigned!🎉 

**Note:** This is your third assigned issue. Create PRs for these issues before requesting more. I see that you have other issues assigned to you that still have open PRs. Make sure to keep working on those as well.
