### ISSUE TITLE
[Entry] Subject: git-mergetool

### ISSUE THREAD

**Issue by CBID2** [Codecademy/docs#4096]
### Reason/inspiration (optional)

I want to add this entry to the Git section because merge conflicts is something developers or people who code often encounter, so having this information would help them.  

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by Jlbanks-Dev** [comment]
I would like to be assigned this please!

**Comment by Jlbanks-Dev** [comment]
Please assign this to me!

**Comment by avdhoottt** [comment]
@Jlbanks-Dev You're assigned!🚀 You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by CBID2** [comment]
Hi @avdhoott. I wrote in my issue form that I wanted to work on this

**Comment by CBID2** [comment]
> Please assign this to me!

@Jlbanks-Dev, I wrote in the issue that I wanted to work on this. I found this another issue that’s free for the taking: https://github.com/Codecademy/docs/issues/3808

**Comment by Jlbanks-Dev** [comment]
I'm very sorry they can take me off and assign you! I did not mean to impose!

**Comment by avdhoottt** [comment]
@CBID2 Sorry, I didn't read that. You are assigned!! @Jlbanks-Dev You can get assigned to other [issues](https://github.com/Codecademy/docs/issues), sorry for the confusion.

**Comment by CBID2** [comment]
> @CBID2 @avdhoottt I'm very sorry they can take me off and assign you! I did not mean to impose! 

All good @Jlbanks-Dev! 😁
