### ISSUE TITLE
[Term Entry] Java ArrayList: .sort()

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#4102]
### Reason/inspiration (optional)

We want to add the `.sort()` method as a new term entry for [ArrayList](https://www.codecademy.com/resources/docs/java/array-list). Provide the entry in a markdown file and place it under the file path `content/java/concepts/array-list/terms/sort/sort.md`

The entry should have the following:
– An introductory paragraph about what the method does.
– A syntax section with a pseudo code block explaining it.
– An example showing the method in use.

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Brag2gr8** [comment]
kindly assign to me

**Comment by KTom101** [comment]
@Brag2gr8 You've been assigned

**Comment by SSwiniarski** [comment]
Closing because related PR was merged.
