### ISSUE TITLE
[Term Entry] Java ArrayList: .subList()

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#4104]
### Reason/inspiration (optional)

We want to add the `.subList()` method as a new term entry for [ArrayList](https://www.codecademy.com/resources/docs/java/array-list). Provide the entry in a markdown file and place it under the file path `content/java/concepts/array-list/terms/subList/subList.md`

The entry should have the following:
– An introductory paragraph about what the method does.
– A syntax section with a pseudo code block explaining it.
– An example showing the method in use.

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Jlbanks-Dev** [comment]
Can you assign this to me please!

**Comment by Kinaata** [comment]
@KTom101 Could you assign me to this issue?

**Comment by KTom101** [comment]
@Jlbanks-Dev You're assigned. Be sure to look at the documentation linked in the description and the [contribution guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already. 

Would this be your first official assignment? If so, how is it you found out about contributing to Codecademy Docs?

**Comment by KTom101** [comment]
@Kinaata The other contributor asked first. We will be adding more issues soon, please continue to check back.

**Comment by Jlbanks-Dev** [comment]
@KTom101  This is my first official assignment. I've taken multiple courses on Codecademy and that's how I found out about contributing to the docs.
