### ISSUE TITLE
[Bug]: Improve pull request template 

### ISSUE THREAD

**Issue by CBID2** [Codecademy/docs#4113]
### Actual Behavior

When I was reviewing the checklist in the form for my PR #4112, I went to the Description section to link the issue that corresponds to my contribution. Even though it the checkbox briefly says where to link the issue, this can still cause new open source contributors to have a hard time create an effective PR because they tend to be not familiar with how to format their links. 

### Expected Behavior

I anticipated that the Issue section would appear in the Description as mentioned.

## Proposed Solution
I would like to add an issue section underneath the Description section of the `PULL_REQUEST_TEMPLATE.md` file. Doing this would make it easier for contributors to link the issues that are addressed in their Pull Requests. 

### On what browser(s) are you seeing the problem?

Chrome

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by alopezgurria** [comment]
Please Can I be assigned this issue ?

**Comment by CBID2** [comment]
> Hi! Please Can I be assigned this issue ?

Hi @alopezgurria I wanted to work on this issue.

**Comment by KTom101** [comment]
@CBID2 I assigned you to this issue. Please make sure you follow the same formatting in the `PULL_REQUEST_TEMPLATE.md` file and be descriptive in explaining how the issue can be added.

**Comment by KTom101** [comment]
@alopezgurria Since @CBID2 opened this issue and requested to be assigned, this issue will go to them. Please routinely check the issues tab for new issues to work on. We are always adding new issues.

**Comment by CBID2** [comment]
> @alopezgurria Since @CBID2 opened this issue and requested to be assigned, this issue will go to them. Please routinely check the issues tab for new issues to work on. We are always adding new issues.

Hey @KTom101. You can unassign me from this [issue](https://github.com/Codecademy/docs/issues/4023) and give it to @alopezgurria. :) I lost interest in it

**Comment by alopezgurria** [comment]
> > @alopezgurria Since @CBID2 opened this issue and requested to be assigned, this issue will go to them. Please routinely check the issues tab for new issues to work on. We are always adding new issues.
> 
> Hey @KTom101. You can unassign me from this [issue](https://github.com/Codecademy/docs/issues/4023) and give it to @alopezgurria. :) I lost interest in it.

Thank you @CBID2 :)
Hi @KTom101, could you unassign @CBID2 and assign me to the issue ? Thanks in advance.

**Comment by KTom101** [comment]
@alopezgurria Can you add a comment under the [issue](https://github.com/Codecademy/docs/issues/4023) asking to be assigned so I can assign you?

**Comment by CBID2** [comment]
> @alopezgurria Can you add a comment under the [issue](https://github.com/Codecademy/docs/issues/4023) asking to be assigned so I can assign you?

Hi @KTom101! :) I accidentally unassigned myself from this issue. Can you put my name back there please?

**Comment by alopezgurria** [comment]
> @alopezgurria Can you add a comment under the [issue](https://github.com/Codecademy/docs/issues/4023) asking to be assigned so I can assign you?

Yes, I just did, thank you !

**Comment by KTom101** [comment]
@CBID2 I re-added your name.
