### ISSUE TITLE
[Entry] Subject: Common Sorting Algos in Java

### ISSUE THREAD

**Issue by JustinhSE** [Codecademy/docs#4128]
### Reason/inspiration (optional)

Sorting methods were heavily tested on in my Data Structures class and are missing from the Docs. Sorting algos like Selection, Insertion, Heap, Counting(which is very hard to understand online), Merge & Quick Sort.  

This entry should include conceptually discussion about each sorting method, in-place or out of place sorting, pseudocode for implementations & discussion of time complexity. 
### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by JustinhSE** [comment]
@yangc95 I would like to be assigned to this issue

**Comment by dakshdeepHERE** [comment]
@JustinhSE you'll have to create separate entries for each sorting algorithm. The algo can go into the algorithm folder in the general folder.

**Comment by dakshdeepHERE** [comment]
We already have selection sort entry present there. Please checkout the [entry](https://github.com/Codecademy/docs/blob/main/content/general/concepts/algorithm/terms/selection-sort/selection-sort.md) first if you can work like then we can assign you this issue.

**Comment by JustinhSE** [comment]
@dakshdeepHERE thanks I will create another issue for this than.
