### ISSUE TITLE
[Bug/Error] Subject:  Git Bash Failed to Open a New Terminal at the Current Location

### ISSUE THREAD

**Issue by MThompson963-2202** [Codecademy/docs#4130]
### Actual Behavior

Git Bash was not opening a new terminal window at the current location when using the sh command or any similar responding command. Instead, it shows in the command line interface of Git Bash completed Lingua Franca project. I uninstalled and reinstalled Git multiple times and it kept showing the lingua franca project in the prompt. 
An example command I used (git-cmd.exe instead of git-bash.exe) and change the starting directory in the settings and it did not work. As I have mentioned nothing I did was working.
The new terminal window opens at the root directory and shows the files from the Lingua Franca project, which is not related to the current project I wanted to work on.
![Git Bash Issue](https://github.com/Codecademy/docs/assets/154823621/0029a237-8c6f-479d-9f64-594e78c7f232)

### Expected Behavior

I expected to open a new Git Bash terminal window at the same location as the current one, without any error messages or unrelated files. I searched through my Program files and found missing components from Git in another application. I simply copied it and paste in the Git folder and it worked as it ought to.
![Git Bash Resolve](https://github.com/Codecademy/docs/assets/154823621/ac83585a-6a6d-4fe1-8494-6efe55c79e1a)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by johnnylau1011** [comment]
Can I take this?

**Comment by MThompson963-2202** [comment]
Hey, I just reported a bug and I didn’t mean to assign it to anyone for fixing. If you are interested in working on any other issues or pull requests that I have assigned, please let me know and I will reassign them to you. Similarly, if you have any tasks that you assign and I request them, feel free to assign them to me.

**Comment by dhumale1s** [comment]
@MThompson963-2202 Hey, if you have any issues or PR that you have been assigned to, and would like to reassign them to someone else, then please let me know.

**Comment by SSwiniarski** [comment]
Closing as this seems resolved, and is not related to the Docs repository.
