### ISSUE TITLE
[Edit] Data types: Adding codebyte for `data-type.md`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4134]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] We would like an edit to the data types file. The term entry lives in docs/content/javascript/concepts/data-types/data-types.md.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add interesting codebytes showing all kinds of data types mentioned in the data-types.md file.
2) You can be creative with the codebyte snippet or stay on the point. 

### Codebyte Example

<img width="534" alt="image" src="https://github.com/Codecademy/docs/assets/94860622/218d7eeb-b165-492a-8f7b-fd0696afbcdf">

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Blanco248** [comment]
@dakshdeepHERE I would be happy to work on this

**Comment by kamlesh-ops** [comment]
@dakshdeepHERE sir I would like to take up this issue.

**Comment by kamlesh-ops** [comment]
Yes, this would be my first assignment. I got to know about Codecademy while surfing online for open-source projects, and then found some good first issues here and decided to step up :)
