### ISSUE TITLE
[Edit] Arrays: Adding codebyte for `.findLastIndex()`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4138]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] We would like an edit to the findLastIndex entry. The term entry lives in docs/content/javascript/concepts/arrays/terms/findLastIndex/findLastIndex.md.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a codebyte which shows how we can use `.findLastIndex()`.
2) You can be creative with the codebyte snippet but make sure you don't deviate a lot from the entry.

### Codebyte Example

<img width="534" alt="image" src="https://github.com/Codecademy/docs/assets/94860622/218d7eeb-b165-492a-8f7b-fd0696afbcdf">

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Jamesllllllllll** [comment]
Happy to take this one on.

**Comment by kamlesh-ops** [comment]
Hi @dakshdeepHERE sir. I would like to work on this issue. I'm new to docs and discovered this while surfing open-source projects online.

**Comment by dakshdeepHERE** [comment]
You're assigned @Jamesllllllllll 🚀

**Comment by dakshdeepHERE** [comment]
Sorry @kamlesh-ops James claimed it first.

**Comment by Jamesllllllllll** [comment]
Hey @dakshdeepHERE - I won't be able to add a Codebyte as `findLastIndex()` isn't supported in the Codebyte's Node runtime, which is v14.19.1. It requires [at least Node v18 according to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findLastIndex#browser_compatibility) (Node is at the end of the compatibility table)

**Comment by SSwiniarski** [comment]
Closing in response to @Jamesllllllllll's comment.
