### ISSUE TITLE
[Edit] Dates: Adding codebyte for the entry `.getTime()`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4139]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] We would like an edit to the getTime entry. The term entry lives in Codecademy/docs/content/javascript/concepts/dates/terms/getTime/getTime.md.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a codebyte which shows how we can use `.getTime()`.
2) You can be creative with the codebyte snippet but make sure you don't deviate a lot from the entry.

### Codebyte Example

<img width="534" alt="image" src="https://github.com/Codecademy/docs/assets/94860622/218d7eeb-b165-492a-8f7b-fd0696afbcdf">

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Jamesllllllllll** [comment]
Happy to take this one on!!

**Comment by kamlesh-ops** [comment]
Hi @dakshdeepHERE sir. I would like to work on this issue.

**Comment by dakshdeepHERE** [comment]
You're assigned @Jamesllllllllll

**Comment by dakshdeepHERE** [comment]
Hello @kamlesh-ops as James asked before you I will have to assign him. Please check the issues section for more issues. 🚀

**Comment by kamlesh-ops** [comment]
sure sir

**Comment by dakshdeepHERE** [comment]
Thank you for understanding @kamlesh-ops, also there's no need for calling `Sir` sounds weird. Looking forward to your contributions. 🚀

**Comment by dakshdeepHERE** [comment]
@R-Juhasz nope but its been claimed. Please check any unclaimed issue or wait for new slots of issues.

**Comment by dakshdeepHERE** [comment]
@Jamesllllllllll yep that's the case. Thanks for spotting it out!
