### ISSUE TITLE
[Entry Edit] React: Components

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#414]
## Description

Would someone be open to making some edits to the existing entry for [React: Components](https://www.codecademy.com/resources/docs/react/components), including:

- Adding hyperlinks to `state` and `props` with the Docs entry links for [state](https://www.codecademy.com/resources/docs/react/state) and [props](https://www.codecademy.com/resources/docs/react/props), respectively.

- Adding an alternate arrow function definition below the existing code in the code snippet in the "Function Components"

```js
const arrowFunc = (prop1, prop2) => {
  ...
}
```

## Type of Edit Request

- Typo and/or bug within one or more existing entries.
- Unclear explanation of term(s)

## Checklist

- [x] The issue is appropriately titled.
- [x] Description is clear and includes supporting text, files, etc.
- [x] A similar issue hasn't already been created.
- [x] No more than 3 entries requested.

## For Maintainers

- [x] Labels are added
- [x] Assignee is added

**Comment by Emiliano-Russo** [comment]
i'll do it!

**Comment by Dusch4593** [comment]
@Emiliano-Russo You got it!
