### ISSUE TITLE
[Edit] Dates: Adding codebyte for the entry `.getUTCDate()`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4140]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] We would like an edit to the `getUTCDate.md` entry. The term entry lives in docs/content/javascript/concepts/dates/terms/getUTCDate/getUTCDate.md.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a codebyte which shows how we can use `.getUTCDate()`.
2) You can be creative with the codebyte snippet but make sure you don't deviate a lot from the entry.

### Codebyte Example

<img width="534" alt="image" src="https://github.com/Codecademy/docs/assets/94860622/218d7eeb-b165-492a-8f7b-fd0696afbcdf">

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Abdouhaji** [comment]
@dakshdeepHERE Hi, I am interested in taking this issue on, kindly assign to to me.

**Comment by dakshdeepHERE** [comment]
@Abdouhaji You're assigned 🚀. Be sure to look at the documentation linked in the description and the [contribution guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already. 

Would this be your first official assignment? If so, how is it you find out about contributing to Codecademy Docs?

**Comment by Abdouhaji** [comment]
@dakshdeepHERE On it! Checked the docs and the guide. This is the first official assignment, discovered while diving into the Data Scientist path on Codecademy—keen on Python, JS, SQL, and aiming to delve deeper into ML, AI, and deep learning. Excited to contribute! Thanks for the opportunity!

**Comment by amal-george-8895** [comment]
Hi, I am interested in taking this issue on, kindly assign.

**Comment by ishg-153** [comment]
@Abdouhaji There has been no new PR created by you as requested by @dakshdeepHERE. Hence, I am unassigning you from this issue.

**Comment by ishg-153** [comment]
@amal-george-8895 are you still interested in taking on this issue?

**Comment by Johnnie-kay** [comment]
Hello @ishg-153. I am interested to close this issue, assign me on it, I see the other contributors are not active about it.

**Comment by ishg-153** [comment]
@Johnnie-kay You already have 3 active issues assigned to you. We don't assign more than 3 issues at a time. Please create PRs for these issues before asking to be assigned to more.

**Comment by Johnnie-kay** [comment]
@ishg-153 I have created PRs for the other issues... Can I get assigned on this now ?

**Comment by adrmac** [comment]
Hello, I am interested in taking on this issue as part of an assignment for the Codecademy web development skill path.

**Comment by letsbuildanything** [comment]
@adrmac You’re assigned :tada:  In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.
Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.
