### ISSUE TITLE
[Edit] Dates: Addding Codebyte for the entry `.getUTCDay()`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4141]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] We would like an edit to the `.getUTCDay.md` entry. The term entry lives in docs/content/javascript/concepts/dates/terms/getUTCDay/getUTCDay.md.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a codebyte which shows how we can use `.getUTCDay()`.
2) You can be creative with the codebyte snippet but make sure you don't deviate a lot from the entry.

### Codebyte Example

<img width="534" alt="image" src="https://github.com/Codecademy/docs/assets/94860622/218d7eeb-b165-492a-8f7b-fd0696afbcdf">

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by aminaradoni24** [comment]
@dakshdeepHERE I am interested in taking this issue on.

**Comment by dakshdeepHERE** [comment]
@aminaradoni24 You're assigned 🚀. Be sure to look at the documentation linked in the description and the [contribution guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already. 

Would this be your first official assignment? If so, how is it you find out about contributing to Codecademy Docs?

**Comment by aminaradoni24** [comment]
@dakshdeepHERE thank you. Yes in this project is my first official assignment. I found out through Cocademy platform.

**Comment by SSwiniarski** [comment]
Closing as associated PR was merged
