### ISSUE TITLE
[Entry] Algorithms: Adding Counting Sort

### ISSUE THREAD

**Issue by JustinhSE** [Codecademy/docs#4144]
### Reason/inspiration (optional)

In the Algorithms Folder, I would like to add the following Sorting Algo:
- Counting Sort

Within this doc, there should be 
- A brief explanation of the sorting algorithm (including time complexity):
- graphical/photographic representation 
- example code of sorting algo
- explanation of the sorting code 

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by JustinhSE** [comment]
@dakshdeepHERE can I be assigned this please?

**Comment by dakshdeepHERE** [comment]
@JustinhSE you can only be assigned to max 3 issue at a time.

**Comment by dakshdeepHERE** [comment]
You created more than 3 issues so you can't be assigned to other issues.

**Comment by JustinhSE** [comment]
Oh I don't want to be assigned to all of them.

**Comment by dakshdeepHERE** [comment]
Then comment on the issue you want to be assigned @JustinhSE. I will assign you there.

**Comment by JustinhSE** [comment]
Just trying to give more opportunity to others who may want to chip in on the other algos. @dakshdeepHERE Thanks for informing me, I will do that now,

**Comment by dakshdeepHERE** [comment]
@JustinhSE  You're assigned. Be sure to look at the documentation linked in the description and the [contribution guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already.

**Comment by dakshdeepHERE** [comment]
@JustinhSE make sure you add the entries in the general folder and inside it in the algorithm folder's concept.

**Comment by JustinhSE** [comment]
Thanks, I will! Just to note @dakshdeepHERE , the other algos are good first issues for students!
