### ISSUE TITLE
[Entry] Algorithms: Adding Insertion Sort

### ISSUE THREAD

**Issue by JustinhSE** [Codecademy/docs#4146]
### Reason/inspiration (optional)

In the Algorithms Folder, I would like to add the following Sorting Algo:
- Insertion Sort

Within this doc, there should be 
- A brief explanation of the sorting algorithm (including time complexity):
- graphical/photographic representation 
- example code of sorting algo
- explanation of the sorting code 

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by arirays** [comment]
Hi, can I write this entry? thank you!

**Comment by dakshdeepHERE** [comment]
@arirays You're assigned!

**Comment by ishg-153** [comment]
Hi @arirays. How far along are you with this entry?

I see you have multiple issues to work on as well. You can get in at least one of the issues to start with.

Note: If you don't respond with a PR or an update within a week, this issue will be unassigned from you.

**Comment by brennapacheco** [comment]
If Ari can’t finish it, can I have this entry?

**Comment by arirays** [comment]
Hi Brenna, 
I can't write it on time so it's better if you have it. Thank you! 😃

**Comment by ishg-153** [comment]
@brennapacheco You're assigned!🎉 

You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by brennapacheco** [comment]
Thanks, guys! I'm currently taking the iOS Path Course at Codecademy, and I discovered the opportunity to contribute here. I plan to complete it by Feb 4th.

**Comment by letsbuildanything** [comment]
@brennapacheco are you still working on this entry? please note that in the next week, it will be unassigned due to inactivity.

**Comment by ishg-153** [comment]
@brennapacheco This is being unassigned due to lack of activity.

**Comment by cigar-galaxy82** [comment]
Hi @ishg-153 I would like to work on this entry

**Comment by ishg-153** [comment]
@cigar-galaxy82 You're assigned!🎉

**Comment by ishg-153** [comment]
@cigar-galaxy82 How's this entry coming along?

**Comment by Sriparno08** [comment]
Hey @cigar-galaxy82, it's been over a month and there's no PR from your side. Are you still working on this issue?

**Comment by cigar-galaxy82** [comment]
Yes @Sriparno08 I will push a PR by Saturday

**Comment by Sriparno08** [comment]
Great, @cigar-galaxy82!
