### ISSUE TITLE
[Entry] Algorithms: Adding Bubble Sort

### ISSUE THREAD

**Issue by JustinhSE** [Codecademy/docs#4147]
### Reason/inspiration (optional)

In the Algorithms Folder, I would like to add the following Sorting Algo:
- BubbleSort

Within this doc, there should be 
- A brief explanation of the sorting algorithm (including time complexity):
- graphical/photographic representation 
- example code of sorting algo
- explanation of the sorting code 

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by arirays** [comment]
I'd like to write this entry. Thanks!

**Comment by dakshdeepHERE** [comment]
@arirays You're assigned !

**Comment by ishg-153** [comment]
Hi @arirays. How far along are you with this entry?

I see you have multiple issues to work on as well. You can get in at least one of the issues to start with.

Note: If you don't respond with a PR or an update within a week, this issue will be unassigned from you.

**Comment by SSwiniarski** [comment]
@arirays This is being unassigned due to inactivity.

**Comment by JorisBolwerk** [comment]
Hey, I would love to write this entry!

**Comment by SSwiniarski** [comment]
@JorisBolwerk You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!
