### ISSUE TITLE
[Entry] Algorithms: Adding Merge Sort

### ISSUE THREAD

**Issue by JustinhSE** [Codecademy/docs#4148]
### Reason/inspiration (optional)

In the Algorithms Folder, I would like to add the following Sorting Algo:
- MergeSort

Within this doc, there should be 
- A brief explanation of the sorting algorithm (including time complexity):
- graphical/photographic representation 
- example code of sorting algo
- explanation of the sorting code 

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by JustinhSE** [comment]
@dakshdeepHERE can I be assigned here

**Comment by dakshdeepHERE** [comment]
@JustinhSE  You're assigned. Be sure to look at the documentation linked in the description and the [contribution guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already.
