### ISSUE TITLE
[Entry] Algorithms: Adding QuickSort

### ISSUE THREAD

**Issue by JustinhSE** [Codecademy/docs#4149]
### Reason/inspiration (optional)

In the Algorithms Folder, I would like to add the following Sorting Algo:
- QuickSort

Within this doc, there should be 
- A brief explanation of the sorting algorithm (including time complexity):
- graphical/photographic representation 
- example code of sorting algo
- explanation of the sorting code 

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by JustinhSE** [comment]
@dakshdeepHERE can I be assigned here

**Comment by dakshdeepHERE** [comment]
@JustinhSE  You're assigned. Be sure to look at the documentation linked in the description and the [contribution guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already.

**Comment by SSwiniarski** [comment]
@JustinhSE it's been two weeks. Are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by JustinhSE** [comment]
Yes, I was just working on the other pr’s. @SSwiniarski thanks for the notice.

**Comment by JustinhSE** [comment]
@SSwiniarski I am trying to create a visual for quicksort since it is a complicated algo to understand. I should be done by the end of next week.

**Comment by SSwiniarski** [comment]
@JustinhSE Where are you at with this?
