### ISSUE TITLE
[Edit] Strings: Adding codebyte for the entry `.toUpperCase()`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4154]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] We would like an edit to the `toUpperCase.md` entry. The term entry lives in docs/content/javascript/concepts/strings/terms/toUpperCase/toUpperCase.md.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a codebyte which shows how we can use `.toUpperCase()`.
2) You can be creative with the codebyte snippet but make sure you don't deviate a lot from the entry.

### Codebyte Example

<img width="534" alt="image" src="https://github.com/Codecademy/docs/assets/94860622/218d7eeb-b165-492a-8f7b-fd0696afbcdf">

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by stanleyluong** [comment]
I would like to be assigned this issue.

**Comment by dakshdeepHERE** [comment]
@stanleyluong  You're assigned. Be sure to look at the documentation linked in the description and the [contribution guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already. 

Would this be your first official assignment? If so, how is it you find out about contributing to Codecademy Docs?

**Comment by stanleyluong** [comment]
codecademy web development certificate brought me here

**Comment by dakshdeepHERE** [comment]
Thats amazing @stanleyluong, goodluck with the entry. 🚀

**Comment by ishg-153** [comment]
@stanleyluong This Issue was unassigned as its corresponding PR was closed.

**Comment by ivaaane** [comment]
Can I be assigned?
_Please I need to complete the Git course_

**Comment by MIB909** [comment]
hello! can you please assign me to this issue

**Comment by mamtawardhani** [comment]
Hey @ivaaane You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.
Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by ivaaane** [comment]
@mamtawardhani Thanks you so much! I'm contributing for the final project in the course [Learn Git and GitHub](https://www.codecademy.com/learn/learn-git).

**Comment by MIB909** [comment]
hello can I now  be assigned to the issue be able to finish my Git and Github project .

**Comment by ishg-153** [comment]
@MIB909 This PR is already assigned to @ivaaane. 

I suggest you ask to be assigned to one of the [available issues](https://github.com/Codecademy/docs/issues?q=is%3Aopen+is%3Aissue+-label%3A%22claimed%22) and once assigned you can create a PR for that issue.
