### ISSUE TITLE
[Edit] Statements: Adding codebyte for the entry `statements`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4155]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] We would like an edit to the `statements.md`  entry. The term entry lives in Codecademy/docs/content/javascript/concepts/statements/statements.md.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a codebyte for all the types of statements that if present in the entry. 
2) You can be creative with the codebyte snippet but make sure you don't deviate a lot from the entry.

### Codebyte Example

<img width="534" alt="image" src="https://github.com/Codecademy/docs/assets/94860622/218d7eeb-b165-492a-8f7b-fd0696afbcdf">

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Nnamdingozi** [comment]
Hi, @dakshdeepHERE , I interested in taking this issue on. I'm currently taking a codecademy course and would like to consolidate my knowledge of contributing to open source by tackling this issue. 
Hope to hear from you soonest.
Ngozi

**Comment by dakshdeepHERE** [comment]
@Nnamdingozi You're assigned. Be sure to look at the documentation linked in the description and the [contribution guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already. 

Would this be your first official assignment? If so, how is it you find out about contributing to Codecademy Docs?

**Comment by Nnamdingozi** [comment]
HI @dakshdeepHERE, thanks for your reply. The Codecademy-entry project on Codecademy full-stack engineer course requires contribution to open source to test our  knowledge of markdown syntax. The guideline on how to contribute to Codecademy docs was included in a Youtube  video attached to the course. That is how I got to know about contributing to Codecademy docs.

**Comment by dakshdeepHERE** [comment]
@Nnamdingozi I hope this helps you with experiencing Git. Good luck with the entry.

**Comment by Nnamdingozi** [comment]
Thanks a lot
