### ISSUE TITLE
[Edit] Map: Adding codebyte for the entry `.set()`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4156]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] We would like an edit to the `set.md` entry. The term entry lives in docs/content/javascript/concepts/map/terms/set/set.md.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a codebyte which shows how we can use `.set()`.
2) You can be creative with the codebyte snippet but make sure you don't deviate a lot from the entry.

### Codebyte Example

<img width="534" alt="image" src="https://github.com/Codecademy/docs/assets/94860622/218d7eeb-b165-492a-8f7b-fd0696afbcdf">

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by sigltech** [comment]
can I be assigned this issue?

**Comment by avdhoottt** [comment]
@sigltech You're assigned 🚀. Be sure to look at the documentation linked in the description and the [contribution guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already. 

Would this be your first official assignment? If so, how is it you find out about contributing to Codecademy Docs?

**Comment by sigltech** [comment]
Yes, It will be, did some searching around and because I use codecademy, I thought i'd see if there was anything I could contribute to 😄

**Comment by sigltech** [comment]
@avdhoottt Just to clarify, it seems there is already a codebyte in the `.set()` entry. Do you want another one, or would you like it edited?

**Comment by dakshdeepHERE** [comment]
@sigltech the last header which says chaining change that codebyte to a normal code snippet with the output block. After that in the end create a header name `Codebyte example` and add code snippet which is runnable with ```codebyte/js tag and show how we can use `.set()`

**Comment by SSwiniarski** [comment]
@sigltech It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by R-Juhasz** [comment]
can i be assigned this issue for codecademy contribution project?

**Comment by SSwiniarski** [comment]
@R-Juhasz, @sigltech is still assigned this issue.

**Comment by SSwiniarski** [comment]
@sigltech This is being unassigned due to inactivity.

@R-Juhasz do you still want to be assigned?

**Comment by R-Juhasz** [comment]
yes please

**Comment by R-Juhasz** [comment]
> @sigltech This is being unassigned due to inactivity.
> 
> @R-Juhasz do you still want to be assigned?

yes please

**Comment by SSwiniarski** [comment]
@R-Juhasz You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!
