### ISSUE TITLE
[Edit] Bitwise Operator: Adding codebyte for the entry `Bitwise Operators`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4162]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] We would like an edit to the `bitwise-operator.md` entry. The term entry lives in docs/content/javascript/concepts/bitwise-operators/bitwise-operators.md.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a codebyte that shows how we can use the Bitwise operator that is mentioned in the entry.
2) You can be creative with the codebyte snippet but make sure you don't deviate a lot from the entry.

### Codebyte Example

<img width="534" alt="image" src="https://github.com/Codecademy/docs/assets/94860622/218d7eeb-b165-492a-8f7b-fd0696afbcdf">

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Yinnie01** [comment]
Hello Codecademy, please I will like to work on this issue. Please assign to me.

**Comment by dakshdeepHERE** [comment]
@Yinnie01 You're assigned. Be sure to look at the documentation linked in the description and the [contribution guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already. 

Would this be your first official assignment? If so, how is it you find out about contributing to Codecademy Docs?

**Comment by Yinnie01** [comment]
@dakshdeepHERE I have submitted this for review. I am still awaiting feedback, please 😊

**Comment by SSwiniarski** [comment]
@Yinnie01 you closed your PR. Does that mean you're no longer working on this issue?

**Comment by Yinnie01** [comment]
This must have been a mistake on my part.

I didn't mean to close my PR.

Is there a way that I can reopen it?

**Comment by Yinnie01** [comment]
My pull request is #4179 and I just checked it - it is still open and
awaiting review

**Comment by SSwiniarski** [comment]
@Yinnie01 according to the notifications you deleted your branch, so you'd have to open a new branch and submit a new PR.

**Comment by SSwiniarski** [comment]
@Yinnie01 I see the link you made to the other PR. Since it was merged I'm closing this issue.
