### ISSUE TITLE
[Edit] Subject: Java/HashMaps - additional methods

### ISSUE THREAD

**Issue by JustinhSE** [Codecademy/docs#4172]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Addition of the following built-in methods: 

- map.containsKey(___)
- map.containsValue(___)
- map.replace(____ , _____) 
	- replaces a current element
- map.putIfAbsent(_____,______) 
	- if the element isn't there, insert it

Expectation:
explanation of each method and codebyte of each method being shown

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by Abdouhaji** [comment]
@JustinhSE I am interested in taking this issue on, kindly assign it to me.

**Comment by JustinhSE** [comment]
@dakshdeepHERE

**Comment by dakshdeepHERE** [comment]
@JustinhSE these are methods that we can apply on hashmap. So for each of these methods we will have to create separate term entries. In hashmap folder we will have to create a folder called terms and put all these methods entries in it.

**Comment by dakshdeepHERE** [comment]
I will close this Issue and create separate ones for these methods. @Abdouhaji please check the new issue that I will create based on this issue.

**Comment by dakshdeepHERE** [comment]
@Abdouhaji please checkout the new issues. Thank you for creating this @JustinhSE 🚀
