### ISSUE TITLE
[Edit] Subject:  Java/ Set - TreeSet

### ISSUE THREAD

**Issue by JustinhSE** [Codecademy/docs#4173]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Add `treeSet` implementation:

ex. Set<String> set = new TreeSet<>();

Expectation:
- define what a tree set is
- show why this may be helpful for a string set
- show code snippet of this 'why' in action

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by JakubLiszcz** [comment]
I am interested in taking this issue on.

**Comment by JustinhSE** [comment]
@dakshdeepHERE

**Comment by JakubLiszcz** [comment]
@JustinhSE please assignet to me this issue and check my pull request

**Comment by JustinhSE** [comment]
@JakubLiszcz Please wait for a maintainers approval

**Comment by SSwiniarski** [comment]
@JakubLiszcz I've assigned you. However, in the future DO NOT submit a PR before you are officially assigned an issue. We've had to reject PRs in the past because of this.

**Comment by JakubLiszcz** [comment]
@SSwiniarski OK! I apologize for that.
