### ISSUE TITLE
[Entry] Java: Java/ Boolean Logic

### ISSUE THREAD

**Issue by JustinhSE** [Codecademy/docs#4175]
### Reason/inspiration (optional)

Add the topic of boolean logic.
For example: what !false, &&, ||, true, false, if(boolean variable) in as a statement means.

- Use a codebyte to show the example 
- define what each symbol does

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by noahpgordon** [comment]
I'll take this.

**Comment by dakshdeepHERE** [comment]
@noahpgordon You're assigned!

**Comment by AbhiPrakash97** [comment]
I am interested @dakshdeepHERE

**Comment by dakshdeepHERE** [comment]
@AbhiPrakash97 please check out other issues this is already claimed
