### ISSUE TITLE
[Edit] Subject: Java/ArrayList - toArray()

### ISSUE THREAD

**Issue by JustinhSE** [Codecademy/docs#4176]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

toArray() method

- Define what this does
- When you are allowed to use this method
- Show code snippet (before/after) 

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by dakshdeepHERE** [comment]
@JustinhSE again this will go into terms. I will close this issue and re open it after refactoring.

**Comment by dakshdeepHERE** [comment]
@JustinhSE This entry already exist [here](https://github.com/Codecademy/docs/blob/main/content/java/concepts/array-list/terms/toArray/toArray.md)
