### ISSUE TITLE
[Entry] Subject: Java/ PrintWriter

### ISSUE THREAD

**Issue by JustinhSE** [Codecademy/docs#4177]
### Reason/inspiration (optional)

- Instantiate the object in Java 
- show how it uses a FileWriter object 
- explain how it helps you write to a file
- show codebyte snippet (with before and after results)

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Yahavarshini** [comment]
I am interested

**Comment by JustinhSE** [comment]
@dakshdeepHERE

**Comment by dakshdeepHERE** [comment]
@JustinhSE Wait for this issue. I'll have to talk with the team about this. If this should go here or in the ugc repo.

**Comment by dakshdeepHERE** [comment]
@Yahavarshini you want to be assigned?

**Comment by yuvi1309** [comment]
I am interested.

**Comment by dakshdeepHERE** [comment]
@yuvi1309 You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

**Note:** This is your third assigned issue. Make sure to create PRs for these issues before requesting more.

**Comment by ishg-153** [comment]
@yuvi1309 This issue is being unassigned due to a lack of activity on its corresponding PR.

**Comment by sardul3** [comment]
Interested

**Comment by letsbuildanything** [comment]
@sardul3 You’re assigned :tada:  In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.
Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by ishg-153** [comment]
@sardul3 It's been a week. Are you working on this Issue?

**Comment by ishg-153** [comment]
@sardul3 If you don't respond with a PR or an update soon, this issue will be unassigned from you.

**Comment by ishg-153** [comment]
@sardul3 You are being unassigned due to lack of response.

**Comment by Sriparno08** [comment]
Hey @cigar-galaxy82, are you still working on this issue?

**Comment by cigar-galaxy82** [comment]
Hi @Sriparno08, yes working on it will create a PR today.
