### ISSUE TITLE
[Entry] Java Hashmap: Create the term entry `map.containsKey()`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4180]
### Reason/inspiration (optional)

We want to add the `.containsKey()` method as a new term entry for [HashMap](https://www.codecademy.com/resources/docs/java/hashmap). Provide the entry in a markdown file and place it under the file path `content/java/concepts/array-list/terms/containsKey/containsKey.md`

The entry should have the following:
– An introductory paragraph about what the method does.
– A syntax section with a pseudo code block explaining it.
– An example showing the method in use.

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by andersooi** [comment]
Hi, I am interested in taking on this issue!

**Comment by dakshdeepHERE** [comment]
@andersooi You're assigned. Be sure to look at the documentation linked in the description and the [contribution guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already. 

Would this be your first official assignment? If so, how is it you find out about contributing to Codecademy Docs?

**Comment by andersooi** [comment]
Hi @dakshdeepHERE just wanted to check if it would be better to park the new entry under `concepts/map/terms/containsKey/containsKey.md` instead?

**Comment by dakshdeepHERE** [comment]
@andersooi correct
