### ISSUE TITLE
[Entry] Java Hashmap: Create the term entry `map.containsValue()`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4181]
### Reason/inspiration (optional)

We want to add the `.containsValue()` method as a new term entry for [HashMap](https://www.codecademy.com/resources/docs/java/hashmap). Provide the entry in a markdown file and place it under the file path `content/java/concepts/map/terms/containsValue/containsValue.md`

The entry should have the following:
– An introductory paragraph about what the method does.
– A syntax section with a pseudo code block explaining it.
– An example showing the method in use.

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Sahillather002** [comment]
pls assign

**Comment by dakshdeepHERE** [comment]
@Sahillather002 You're assigned. Be sure to look at the documentation linked in the description and the [contribution guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already. 

Would this be your first official assignment? If so, how is it you find out about contributing to Codecademy Docs?

**Comment by juliajobczyk** [comment]
Can I also be assigned please?

**Comment by SSwiniarski** [comment]
@Sahillather002 It's been two weeks. Are you still working on this issue? Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment]
@Sahillather002 this is being unassigned due to inactivity.

**Comment by itskarelleh** [comment]
Hi! I would like to be assigned this issue.

**Comment by SSwiniarski** [comment]
@itskarelleh You're assigned!
