### ISSUE TITLE
[Entry] Java Hashmap: Create the term entry `map.putIfAbsent()`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4183]
### Reason/inspiration (optional)

We want to add the `.putIfAbsent()` method as a new term entry for [HashMap](https://www.codecademy.com/resources/docs/java/hashmap). Provide the entry in a markdown file and place it under the file path `content/java/concepts/map/terms/putIfAbsent/putIfAbsent.md`

The entry should have the following:
– An introductory paragraph about what the method does.
– A syntax section with a pseudo code block explaining it.
– An example showing the method in use.

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by avdhoottt** [comment]
@dakshdeepHERE Please assign this to me. I would like to work on this issue.

**Comment by dakshdeepHERE** [comment]
You are assigned @avdhoottt

**Comment by johnnylau1011** [comment]
Please assign this to me.

**Comment by dakshdeepHERE** [comment]
Hey @johnnylau1011 this issue is already assigned and claimed. Please check other unclaimed issues.
