### ISSUE TITLE
[Concept Entry] Rust Strings

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#4206]
### Reason/inspiration (optional)

(Reposting issue because old issue couldn't be unlinked from closed PR)

We would like a new concept entry for Rust about the strings. The entry should go in a new file in `docs/content/rust/concepts/strings/strings.md`

The entry should

- Have an introductory paragraph about the concept.
- Code block(s) displaying different aspects of the concept.
- A concluding header, Functions, future terms will be listed below this header

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Lauttich** [comment]
Hello @SSwiniarski, I am interested in taking this issue on, I found out about Docs through the Codecademy "Learn Git & GitHub"-course, which I'm doing to improve my skills for my currently ongoing apprenticeship in software development. Also I want to build a portfolio for future jobs etc.
Thank you in advance!

**Comment by Lauttich** [comment]
@SSwiniarski awesome, thanks! I'll start working on it this weekend.
