### ISSUE TITLE
[Term Entry] UIUX: Design Sprint (in design methodologies concept)

### ISSUE THREAD

**Issue by ishg-153** [Codecademy/docs#4219]
### Reason/inspiration (optional)

`content/uiux/concepts/design-methodologies/terms/design-sprint/design-sprint.md`

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by aavveett** [comment]
pls assign this to me

**Comment by ishg-153** [comment]
Hi @aavveett, I apologize for the mixup but this issue is assigned.
