### ISSUE TITLE
[Entry] Python: namedtuple()

### ISSUE THREAD

**Issue by avdhoottt** [Codecademy/docs#4231]
### Reason/inspiration (optional)

We would like a new term entry on the `namedtuple()` method for [Collection Module](https://www.codecademy.com/resources/docs/python/collections-module). The entry should go in a new file under `docs/content/python/concepts/collections-module/terms/namedtuple/namedtuple.md`.

The entry should have the following:
– An introductory paragraph about what the method does.
– A syntax section with a pseudo code block explaining it.
– An example showing the method in use.
– A codebyte of the method.

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by l2es** [comment]
Hello
Can I take the issue ?

**Comment by dakshdeepHERE** [comment]
@l2es  You're assigned. Be sure to look at the documentation linked in the description and the [contribution guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already. 

Would this be your first official assignment? If so, how is it you find out about contributing to Codecademy Docs?
