### ISSUE TITLE
[Entry] Python: deque()

### ISSUE THREAD

**Issue by avdhoottt** [Codecademy/docs#4233]
### Reason/inspiration (optional)

We would like a new term entry on the `deque()` method for [Collection Module](https://www.codecademy.com/resources/docs/python/collections-module). The entry should go in a new file under `docs/content/python/concepts/collections-module/terms/deque/deque.md`.

The entry should have the following:
– An introductory paragraph about what the term does.
– A syntax section with a pseudo code block explaining it.
– An example showing the method in use.
– A codebyte of the method.

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by JacTimDav** [comment]
I would like to work on this.

**Comment by dakshdeepHERE** [comment]
@JacTimDav You're assigned. Be sure to look at the documentation linked in the description and the [contribution guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already. 

Would this be your first official assignment? If so, how is it you find out about contributing to Codecademy Docs?

**Comment by JacTimDav** [comment]
This is my first assignment; I found out about it through the "Codecademy:  Learn Git and Github" course.

**Comment by JacTimDav** [comment]
Hi @dakshdeepHERE , to clarify, is the assignment to create an entry describing deque objects or just to explain the deque() method that instantiates the object?

**Comment by JacTimDav** [comment]
Hi @avdhoottt @dakshdeepHERE , I just wanted to follow up on my previous comment last week.

**Comment by dakshdeepHERE** [comment]
@JacTimDav it is to explain the `deque()` method. You can also show how to deque objects in the example part.

**Comment by dakshdeepHERE** [comment]
Let me know it if you have any further questions.

**Comment by PavanSusarla** [comment]
I would  like to work on this.
