### ISSUE TITLE
[Entry] Arrays: Creating new concept entry `list.md`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4235]
### Reason/inspiration (optional)

We would like a new term entry on the `list` term for [dart](https://www.codecademy.com/resources/docs/dart). The entry should go under the following path `docs/content/dart/concepts/list/list.md`.

The entry should describe the term and how it is used within Dart. Also include: 
- Add a "Syntax" section.
- An "Example" section that explains lists in Dart.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by stefansphtr** [comment]
Hello, I would like to contribute to this issue

**Comment by Only-Codes** [comment]
Hi @dakshdeepHERE - I would like to claim this issue please?

It will be my first contribution to an Open Source project - I'm currently working through the GitHub course on Codecademy.

**Comment by KTom101** [comment]
@Only-Codes you're assigned. In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already.  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.
