### ISSUE TITLE
[Entry] Classes: Creating New concept entry `classes.md`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4236]
### Reason/inspiration (optional)

We would like a new term entry on the `Classes` concept for [dart](https://www.codecademy.com/resources/docs/dart). The entry should go under the following path `docs/content/dart/concepts/classes/classes.md`.

The entry should describe the term and how it is used within Dart. Also include: 
- Add a "Syntax" section.
- An "Example" section that explains classes in Dart.
- Make sure to explain what abstract classes are in its section.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by GeeRios** [comment]
Please assign this issue to me.

**Comment by ishg-153** [comment]
@GeeRios You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs.  Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by SSwiniarski** [comment]
@GeeRios It's been two weeks. Are you still working on this entry. Note that in another week it will be unassigned due to inactivity.

**Comment by GeeRios** [comment]
Yes, i've made a pull request and have been waiting for a review

**Comment by SSwiniarski** [comment]
@GeeRios sorry, the PR wasn't linked so I didn't see it here.
