### ISSUE TITLE
[Entry] User input: Creating new concept entry `user-input.md`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4238]
### Reason/inspiration (optional)

We want a new concept entry on the `User Input` for [dart](https://www.codecademy.com/resources/docs/dart). The concept entry should go under the following path `docs/content/dart/concepts/user-input/user-input.md`.

The entry should describe the term and how it is used within Dart. Also include: 
- Add a "Syntax" section.
- An "Example" section that explains user input in Dart.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by wilkeraug** [comment]
Hey @dakshdeepHERE i would like to tackle this one, please.

**Comment by KTom101** [comment]
@wilkeraug you're assigned.

**Comment by ishg-153** [comment]
@wilkeraug This Issue is being unassigned from you due to inactivity.

**Comment by Johnnie-kay** [comment]
Hello @ishg-153 please assign me on this issue. Thanks

**Comment by ishg-153** [comment]
@Johnnie-kay are you still interested to work on this issue?

**Comment by Johnnie-kay** [comment]
@ishg-153 yes I'm still interested to work on the issue. Thanks 👍

**Comment by mamtawardhani** [comment]
@Johnnie-kay You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by ishg-153** [comment]
@Johnnie-kay It's been 2 weeks since you were assigned to this issue. Are you still working on the entry?

**Note:** If you don't respond with a PR or an update within a week, this issue will be unassigned from you.

**Comment by Johnnie-kay** [comment]
Hello @ishg-153 sorry for the delay and inactivity, I had an issue with my hardware. Please assign other contributors, once i get it sorted out i will work on other issues, thanks.

**Comment by ishg-153** [comment]
Hey @Johnnie-kay You ae being unassigned.

**Comment by davialano** [comment]
I'm interested in this issue, can I colaborate it?
