### ISSUE TITLE
[Entry] Type conversion: Creating new concept entry `type-conversion.md`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4239]
### Reason/inspiration (optional)

We would like a new term entry on the `Type conversion` term for [Dart](https://www.codecademy.com/resources/docs/dart). The entry should go under the following path `docs/content/dart/concepts/type-conversion/type-conversion.md`.

The entry should describe the term and how it is used within Dart. Also include: 
- Add a "Syntax" section.
- An "Example" section that explains type conversion in Dart.
- Explain how different types of type conversion are there with example code snippets.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by vinothsiva7** [comment]
Hi, I like to work on this issue.

**Comment by Vino-Siva** [comment]
Hi, I like to work on this issue.

**Comment by ishg-153** [comment]
@Vino-Siva You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by Vino-Siva** [comment]
> @Vino-Siva You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.
> 
> I see this is your first time contributing to Codecademy Docs. How did you find out about us?

Thanks. I'm doing Full-stack and iOS developer career paths in Codecademy. This is for my portfolio project.

**Comment by Vino-Siva** [comment]
> @Vino-Siva You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.
> 
> I see this is your first time contributing to Codecademy Docs. How did you find out about us?

Hi. Your reference link for [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md) is pointing to https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md instead of https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md.

**Comment by Vino-Siva** [comment]
New concept entry for type conversion in dart #4322
