### ISSUE TITLE
[Entry] Strings: New concept entry `strings.md` 

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4240]
### Reason/inspiration (optional)

We would like a new term entry on the `Strings` term for [Dart](https://www.codecademy.com/resources/docs/dart). The entry should go under the following path `docs/content/dart/concepts/strings/strings.md`.

The entry should describe the term and how it is used within Dart. Also include: 
- Add a "Syntax" section.
- An "Example" section that explains strings in Dart.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by a-ogutrax** [comment]
Hi @dakshdeepHERE 
I am interested in taking this issue on. I found out about Docs through Codecademy, through the Learn Git and GitHub course, this would be my first issue.

**Comment by dakshdeepHERE** [comment]
@a-ogutrax You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

**Note:** This is your third assigned issue. Make sure to create PRs for these issues before requesting more.

**Comment by a-ogutrax** [comment]
Hi Daksha!

Thank you so much for assigning me to that task.
I did have one question though, your comment left noted the following:
"*Note:* This is your third assigned issue. Make sure to create PRs for
these issues before requesting more."

But, this is the first one I've ever signed up for. Was this just a copy &
paste error?

Thank you.

Regards,
a-ogutrax
