### ISSUE TITLE
[Entry] Queues: Create new concept entry `queue.md`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4241]
### Reason/inspiration (optional)

We would like a new term entry on the `queue` term for [Dart](https://www.codecademy.com/resources/docs/dart). The entry should go under the following path `docs/content/dart/concepts/queue/queue.md`.

The entry should describe the term and how it is used within Dart. Also include: 
- Add a "Syntax" section.
- An "Example" section that explains queues in Dart.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by KrisHaroun** [comment]
@dakshdeepHERE I am interested in taking this issue on. I am a beginner and this will be my first contribution :)

**Comment by dakshdeepHERE** [comment]
@KrisHaroun You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

**Note:** This is your third assigned issue. Make sure to create PRs for these issues before requesting more.
