### ISSUE TITLE
[Entry] Iterable: New concept entry `iterable.md`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4245]
### Reason/inspiration (optional)

We would like a new term entry on the `Iterable` term for [Dart](https://www.codecademy.com/resources/docs/dart). The entry should go under the following path `docs/content/dart/concepts/iterable/iterable.md`.

The entry should describe the term and how it is used within Dart. Also include: 
- Add a "Syntax" section.
- An "Example" section that explains iterables in Dart.
- Explain how iterables are different from lists in Dart.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by AlessioAltomonte** [comment]
@dakshdeepHERE Hi there, Can I please be assigned on this issue? I'd like to give my contribution on this. Thanks

**Comment by dakshdeepHERE** [comment]
@AlessioAltomonte You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs.  Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by AlessioAltomonte** [comment]
@dakshdeepHERE many thanks for the oppotunity, it's my first time contributing on a GitHub project. 
Please be aware that the "Contribution Guide" link doesn't work? 

I found about you through the Codecademy Git&Github Course. 

Thanks
