### ISSUE TITLE
[Entry] Data types: Create new concept entry `data-types.md`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4246]
### Reason/inspiration (optional)

We would like a new term entry on the `Data types` concept for [Dart](https://www.codecademy.com/resources/docs/dart). The entry should go under the following path `docs/content/dart/concepts/data-types/data-types.md`.

The entry should describe the term and how it is used within Dart. Also include: 
- Add a "Syntax" section.
- An "Example" section that explains Data types in Dart.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by wilkeraug** [comment]
Hi. I would like to take this issue.

**Comment by dakshdeepHERE** [comment]
@wilkeraug  You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions before approval.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by wilkeraug** [comment]
Hey. Just to comment that I haven't forgotten about this and a PR will be created yesterday to address this issue, @dakshdeepHERE
