### ISSUE TITLE
[Entry] Constructors: Create new concept entry `constructors.md`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4247]
### Reason/inspiration (optional)

We would like a new term entry on the `Constructors` term for [Dart](https://www.codecademy.com/resources/docs/dart). The entry should go under the following path `docs/content/dart/concepts/constructors/contructors.md`.

The entry should describe the term and how it is used within Dart. Also include: 
- A section that explains constructors in Dart.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by vjurcutiu** [comment]
Hello, I would like to contribute to this issue.

**Comment by dakshdeepHERE** [comment]
@vjurcutiu You're assigned. In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already.  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by vjurcutiu** [comment]
Hi @dakshdeepHERE, thanks for the assignment. This is my first contribution to Codeacademy. I found the repo through Quine. Will start working on this and keep you updated.
