### ISSUE TITLE
[Entry] Conditionals: Create new concept entry `conditionals.md`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4248]
### Reason/inspiration (optional)

We would like a new term entry on the `Conditional` concept for [Dart](https://www.codecademy.com/resources/docs/dart). The entry should go under the following path `docs/content/dart/concepts/conditionals/conditionals.md`.

The entry should describe the term and how it is used within Dart. Also include: 
- Explain different types of conditional present in dart with code snippets present under each type.
- Make sure to include `Conditional Expressions` with the common conditionals.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by madhuri-kawade** [comment]
## New Concept Entry for Existing Topic - Dart Conditional Concept

I'd like to contribute a new entry on the Conditional concept for Dart. The entry will be located under `docs/content/dart/concepts/conditionals/conditionals.md`. The entry will cover the following:

### Explanation of the Term
[Provide a brief description of the Conditional concept and its use within Dart.]

### Types of Conditionals in Dart
1. **If Statement:**
   ```dart
   if (condition) {
       // code block
   } else {
       // alternative code block
   }

**Comment by dakshdeepHERE** [comment]
@madhuri-kawade You're assigned. In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already.  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by ishg-153** [comment]
@madhuri-kawade This issue is being unassigned due to inactivity.

**Comment by Johnnie-kay** [comment]
@ishg-153  please assign me on issue if the other contributors are inactive.

**Comment by mamtawardhani** [comment]
@Johnnie-kay I just assigned you an issue, would you like to work on this as well?

**Comment by mamtawardhani** [comment]
@Johnnie-kay sure you can take this up. Please refer to the contribution guide shared in the above comment. Thank you! 😃

**Comment by ishg-153** [comment]
@Johnnie-kay It's been 2 weeks since you were assigned to this issue. Are you still working on the entry?

**Note:** If you don't respond with a PR or an update within a week, this issue will be unassigned from you.
