### ISSUE TITLE
[Concept Entry] Loops: Create new concept entry `loops.md`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4249]
### Reason/inspiration (optional)

We would like a new term entry on the `Loops` concept for [Dart](https://www.codecademy.com/resources/docs/dart). The entry should go under the following path `docs/content/dart/concepts/loops/loops.md`.

The entry should describe the term and how it is used within Dart. Also include: 
- Explain different types of loops present in Dart.
- Make sure to add `for-in` and `forEach` loops with other common loops.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by kamlesh-ops** [comment]
@dakshdeepHERE I would like to take up this issue.

**Comment by ishg-153** [comment]
@kamlesh-ops You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see that you have other issues assigned to you. Make sure to create PRs on those as well.

**Comment by kamlesh-ops** [comment]
@ishg-153 Sure. btw I have already made a PR to my previous assignment.

**Comment by SSwiniarski** [comment]
@kamlesh-ops It's been two weeks. Are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by kamlesh-ops** [comment]
Hello @dakshdeepHERE @SSwiniarski 
I was unaware that this issue was assigned and I got busy with other tasks. I deeply regret the inconvenience.
I have made the PR. Please give it a review and please ping me if there are any issues.

**Comment by ishg-153** [comment]
This Issue's corresponding PR has been merged.
