### ISSUE TITLE
[Entry] Inheritance : Creating new concept entry `inheritance.md`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4250]
### Reason/inspiration (optional)

We would like a new term entry on the `Inheritance` concept for [Dart](https://www.codecademy.com/resources/docs/dart). The entry should go under the following path `docs/content/dart/concepts/inheritance/inheritance.md`.

The entry should describe the term and how it is used within Dart. Also include: 
- Explain the concept of inheritance in Dart.
- Make sure you explain this concept of object-oriented programming with suitable code snippets.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by juliajobczyk** [comment]
can I be assigned please

**Comment by dakshdeepHERE** [comment]
@juliajobczyk You're assigned. In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already.  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by juliajobczyk** [comment]
yes it would be my first contribution

**Comment by mamtawardhani** [comment]
Hey @juliajobczyk As I can see this issue is assigned to you. Do you not want to continue with this issue anymore?

**Comment by juliajobczyk** [comment]
no can i be unassigned please.

**Comment by mamtawardhani** [comment]
@dakshdeepHERE could you please unassign @juliajobczyk from this issue?

**Comment by ishg-153** [comment]
@juliajobczyk You've been unassigned.

**Comment by Johnnie-kay** [comment]
@ishg-153 i will like to take on this issue.

**Comment by ishg-153** [comment]
@Johnnie-kay It's been 2 weeks since you were assigned to this issue. Are you still working on the entry?

**Note:** If you don't respond with a PR or an update within a week, this issue will be unassigned from you.

**Comment by Sriparno08** [comment]
Hey @cigar-galaxy82, are you still working on this issue?

**Comment by Sriparno08** [comment]
How's the entry going along, @cigar-galaxy82?
