### ISSUE TITLE
[Concept Entry] Methods: New concept entry `methods.md`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4252]
### Reason/inspiration (optional)

We would like a new term entry on the `Methods` concept for [Dart](https://www.codecademy.com/resources/docs/dart). The entry should go under the following path `docs/content/dart/concepts/methods/methods.md`.

The entry should describe the term and how it is used within Dart. Also include: 
- There should be "## Syntax" and "## Example" headings in this entry.
- Explain briefly what methods are in Dart with suitable code snippets.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by kamlesh-ops** [comment]
@dakshdeepHERE I would like to take up this issue.

**Comment by ishg-153** [comment]
@kamlesh-ops You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

**Note:** This is your third assigned issue. Make sure to create PRs for these issues before requesting more.

**Comment by kamlesh-ops** [comment]
@ishg-153 surely

**Comment by SSwiniarski** [comment]
@kamlesh-ops It's been two weeks. Are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by brandk94** [comment]
@dakshdeepHERE Hello, I would be willing to take on this issue. Thank you.

**Comment by ishg-153** [comment]
@brandk94 You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by brandk94** [comment]
I was going through the "Learn GitHub: Best Practices" module and I came across this portfolio project. I figured that I should work on this to get some real-world experience since graduating college.
