### ISSUE TITLE
[Entry] Switch: Create new concept entry `switch.md`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#4253]
### Reason/inspiration (optional)

We would like a new term entry on the `Switch` concept for [Dart](https://www.codecademy.com/resources/docs/dart). The entry should go under the following path `docs/content/dart/concepts/switch/switch.md`.

The entry should describe the term and how it is used within Dart. Also include: 
- Have an introductory paragraph about the switch statement.
- Have a syntax section illustrating the function in a ```pseudo code block.
- An example showing the switch in a ```dart code block.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by BaldurLogi** [comment]
@dakshdeepHERE I’m interested in taking this issue on 👍

**Comment by KTom101** [comment]
@BaldurLogi You're assigned. In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already.  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by BaldurLogi** [comment]
@KTom101 yes, this is my first contribution to Codecademy docs and happy I can contribute to it. I followed the Codecademy walkthrough step-by-step from the iOS course :)
