### ISSUE TITLE
Fix punctuations

### ISSUE THREAD

**Issue by Helfese** [Codecademy/docs#4256]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

Check lines 7, 69, and 146

Fixed in PR #4255

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by ishg-153** [comment]
This issues corresponding PR has been merged, hence closing this.
