### ISSUE TITLE
Map: New concept entry map.md #4244[Edit] Subject: Entry Nameth 

### ISSUE THREAD

**Issue by Glenda9031** [Codecademy/docs#4266]
### Type of Edit (select all that apply)

Clarify unclear content and/or terms

### Description (optional)

This is my first open-source project.  I would like to take on this project to gain experience with contributing to open-source.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by Glenda9031** [comment]
This is my first open-source project.

**Comment by Glenda9031** [comment]
I would like to work on this open-source project. I believe I accidentally closed this entry.

**Comment by Jamesllllllllll** [comment]
Hey @Glenda9031 !

To help the maintainers of this repo - could you describe the changes you intend to make? It's not clear which entry you would like to edit.

Typically, there are new issues opened every week by the maintainers. You can them ask to claim the issues and make a PR with your work.

You can also search for unclaimed issues by going to the **issues** tab, and using this search: `is:issue is:open -label:claimed`

Cheers!

**Comment by Glenda9031** [comment]
Good morning! 

Ok. This is my first opportunity to participate in open-source so I appreciate any feedback and suggestions!  I will follow-up today and state what entry and/or correction I will use for this claim.
Thank you,
Glenda J. Reed

    On Thursday, January 25, 2024 at 09:52:35 AM CST, James Keezer ***@***.***> wrote:  
 
 


Hey @Glenda9031 !

To help the maintainers of this repo - could you describe the changes you intend to make? It's not clear which entry you would like to edit.

Typically, there are new issues opened every week by the maintainers. You can them ask to claim the issues and make a PR with your work.

You can also search for unclaimed issues by going to the issues tab, and using this search: is:issue is:open -label:claimed

Cheers!

**Comment by Jamesllllllllll** [comment]
Sounds good @Glenda9031 !

Unless you are creating your own issue to edit something, it's best to find an issue posted by the maintainers that you would like to take on and leave a comment. It's first-come-first-served, so it's a good idea to check often - they often get claimed quickly! :)

**Comment by Glenda9031** [comment]
Ok. Should I address the maintainers when I find an issue?

**Comment by dakshdeepHERE** [comment]
@Glenda9031  as @Jamesllllllllll once go through other issues and get familiar with the issue template. Another way is to let us maintainers know what thing you want to work on, and then we will create the issue so you can claim it yourself. I'll close this issue now.
