### ISSUE TITLE
Displaying Markdown in your Browser

### ISSUE THREAD

**Issue by F-Viedge** [Codecademy/docs#4280]
### Reason/inspiration (optional)

I'd like to add some information and links to ariticles under the Markdown label to help learners display their .md files and check their formatting.

Here are my sources 

https://github.com/simov/markdown-viewer?tab=readme-ov-file
https://medium.com/@6unpnp/install-markdown-viewer-a-chrome-extension-cc2c43232438#:~:text=In%20order%20to%20see%20the,Viewer%20(Velichkov%2C%202023).

I'd busy with the GitHub course and I'm battling to find and issue that I can I can contribute to...

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by dakshdeepHERE** [comment]
@F-Viedge we can't open this issue for this repo. if you wanna contribute then please check for any other open issue.
