### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by Helfese** [Codecademy/docs#4293]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

Check PR #4292

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by shahrbanou90** [comment]
@ Helfese I am interested in taking this issue on, I found out about Docs through a friend.

**Comment by ishg-153** [comment]
The PR related to this is merged. So closing this Issue.
@Helfese I would encourage you to look for existing issues you can contribute to [here](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+-label%3Aclaimed), and ask to be assigned to an issue you find interesting.
