### ISSUE TITLE
[Term Entry] Dart List .indexWhere()

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#4308]
### Reason/inspiration (optional)

We would like a new term entry under Dart [List](https://www.codecademy.com/resources/docs/dart/concept/list) for the Dart List `.indexWhere()` method. 
Provide the entry in a markdown file under `docs/content/dart/concept/list/terms/indexWhere/indexWhere.md`

The entry should
    - Have an introductory paragraph about what the method is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the method in use.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by cysiupe** [comment]
@christian-dinh Hi, I'm CodeCademy student and I would like to fix that issue as my first contribution. Can you assign me on this one ? Thanks!

**Comment by KTom101** [comment]
@cysiupe You're assigned. In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already.  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Did you find out about contributing to Codecademy Docs from one of our courses?

**Comment by cysiupe** [comment]
Morning,

Yes, I'm currently a Codecademy student. In one of my courses about GIT and
GitHub I found a challenge with the first contribution for Codecademy Docs.

Kind regards,
Krzysztof

śr., 14 lut 2024 o 20:46 Kyra Thompson ***@***.***>
napisał(a):
