### ISSUE TITLE
[Term Entry] Dart List .insertAll()

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#4310]
### Reason/inspiration (optional)

We would like a new term entry under Dart [List](https://www.codecademy.com/resources/docs/dart/concept/list) for the Dart List `.insertAll()` method. 
Provide the entry in a markdown file under `docs/content/dart/concept/list/terms/insertAll/insertAll.md`

The entry should
    - Have an introductory paragraph about what the method is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the method in use.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by laislemos801** [comment]
Hi! I would like to work in this project :)

**Comment by avdhoottt** [comment]
@laislemos801 Do you want to work on this issue?

**Comment by avdhoottt** [comment]
@laislemos801 You're assigned!! In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already.  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by laislemos801** [comment]
Sure, I'll take a look at the Contribution Guide!
Yes, it's my first contribution. I found out about Codecademy Docs from the Learn Git and Github course! It's requested to submit an entry on a chosen topic, so I ended up choosing this one.
I'll start working on the issue right away :) Thanks for the assignment!
