### ISSUE TITLE
[Term Entry] Dart List .setAll()

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#4316]
### Reason/inspiration (optional)

We would like a new term entry under Dart [List](https://www.codecademy.com/resources/docs/dart/concept/list) for the Dart List `.setAll()` method. 
Provide the entry in a markdown file under `docs/content/dart/concept/list/terms/setAll/setAll.md`

The entry should
    - Have an introductory paragraph about what the method is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the method in use.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by MustafaDemiroglu** [comment]
sorry but i didn`t get it

**Comment by ishg-153** [comment]
@fa125had We are glad to see you contribute to Codecademy Docs. But please refrain for creating PRs for issues without getting them assigned.

I'm going ahead and assigning this issue to you this time.

In future, ask to be assigned to a issue you find interesting and wait to be assigned before creating a PR. It is possible that someone else was already assigned and had created a PR, this can cause problems and your PR would have to be closed in such cases.

**Comment by fa125had** [comment]
Thank you for your assist, Ishwari.

I'm new to contribution, sorry for the inconvenience.

should I ask to be assigned in the issue tab via message? or if not, could you guid me how I can ask for that.


________________________________

**Comment by Sriparno08** [comment]
Hey @fa125had, you can go to the issue tab and ask to be assigned by commenting something like 'I would like to work on this'.

**Comment by fa125had** [comment]
Hi @Sriparno08 
Thanks
