### ISSUE TITLE
[Term Entry] Java ArrayList .forEach()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4338]
### Reason/inspiration (optional)

Please add the `.forEach()` method as a new term entry for [ArrayList](https://www.codecademy.com/resources/docs/java/array-list)�. Provide the entry in a markdown file and place under the file path `content/java/concepts/array-list/terms/forEach/forEach.md`

The entry should have the following:
�	An introductory paragraph about what the method is and does.
�	A syntax section with a pseudo code block with an explanation of it.
�	An example showing the method in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by hakdo99** [comment]
@codecademy-docs Hi! I'd like to work on this issue. Can you assign it to me? Thanks!

**Comment by avdhoottt** [comment]
@hakdo99 You're assigned!! In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already.  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by hakdo99** [comment]
@avdhoottt Yes, this is my first contribution! I learned about contributing to Docs when I searched on Google for technical writing open source projects and found this list of resources that contains Codeacademy Docs: https://github.com/dharmelolar/technical-writing-resources?tab=readme-ov-file
I've just created my PR for this issue, please review it when you have time! Thanks!
