### ISSUE TITLE
[Edit] JavaScript : Map

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#434]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

[javascript/concepts/map/map.md](https://github.com/Codecademy/docs/blob/main/content/javascript/concepts/map/map.md)

Would be great if we could include the functionality that in maps, values can be amended/changed.

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Assignee(s) added

**Comment by Dusch4593** [comment]
I can take this one on!

**Comment by Dusch4593** [comment]
I'm also noticing that most of the what's covered in the current version the [JavaScript: Maps entry in Docs] can be separated into term entries (like one for `.set()`, `.get()`, `.size`, etc.).

I can create 2-3 term entries to start and files issues for the rest.

**Comment by yangc95** [comment]
> I'm also noticing that most of the what's covered in the current version the [JavaScript: Maps entry in Docs] can be separated into term entries (like one for `.set()`, `.get()`, `.size`, etc.).
> 
> I can create term entries currently mentioned to start and file issues for the rest.

I only saw this just now, but I enjoyed going through all the entries! Thanks @Dusch4593 for taking on this issue 😄
