### ISSUE TITLE
[Term Entry] Java ArrayList .iterator()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4340]
### Reason/inspiration (optional)

Please add the `.iterator()` method as a new term entry for [ArrayList](https://www.codecademy.com/resources/docs/java/array-list)�. Provide the entry in a markdown file and place under the file path `content/java/concepts/array-list/terms/iterator/iterator.md`

The entry should have the following:
�	An introductory paragraph about what the method is and does.
�	A syntax section with a pseudo code block with an explanation of it.
�	An example showing the method in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by JMKniss** [comment]
@codecademy-docs I'm interested in being assigned this issue. I am working on the Codecademy Git and GitHub Course.

**Comment by KTom101** [comment]
@JMKniss You're assigned. In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already.  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by letsbuildanything** [comment]
@JMKniss Are you still working on this issue? Note that there's a chance you could be unassigned next week for inactivity. Let me know if you need help. Thanks!

**Comment by mamtawardhani** [comment]
Unassigning the issue due to the inactivity of @JMKniss

**Comment by Ksusha77** [comment]
@codecademy-docs  I'm interested in taking this issue on, I'm currently working on GitHub codecadamy course

**Comment by mamtawardhani** [comment]
Hey @Ksusha77! You're assigned. In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already. After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by ishg-153** [comment]
@Ksusha77 It's been 2 weeks since you were assigned to this issue. Are you still working on the entry?

**Note:** If you don't respond with a PR or an update within a week, this issue will be unassigned from you.

**Comment by DarkFire414** [comment]
@KTom101 I'm interested in taking this issue, I'm currently working on Git and GitHub Codeacademy Course.

**Comment by mamtawardhani** [comment]
Hey @KTom101 You're assigned. In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already. After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.
