### ISSUE TITLE
[Term Entry] Java ArrayList .listiterator()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4341]
### Reason/inspiration (optional)

Please add the `.listiterator()` method as a new term entry for [ArrayList](https://www.codecademy.com/resources/docs/java/array-list)�. Provide the entry in a markdown file and place under the file path `content/java/concepts/array-list/terms/listiterator/listiterator.md`

The entry should have the following:
�	An introductory paragraph about what the method is and does.
�	A syntax section with a pseudo code block with an explanation of it.
�	An example showing the method in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by dejongbaba** [comment]
Hello, please can you assign this task to me ?

**Comment by KTom101** [comment]
@dejongbaba You're assigned. In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already.  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by letsbuildanything** [comment]
@dejongbaba Are you still working on this issue? Note that there's a chance you could be unassigned next week for inactivity. Let me know if you need help. Thanks!

**Comment by dejongbaba** [comment]
> @dejongbaba Are you still working on this issue? Note that there's a chance you could be unassigned next week for inactivity. Let me know if you need help. Thanks!

Apologies, for long weeks of inactivity, I'm still working on the issue, would raise a pr to the effect before the week runs out.

**Comment by mamtawardhani** [comment]
Unassigning this issue to due long inactivity of @dejongbaba

**Comment by selenahuang017** [comment]
Hi! Can I get assigned this task? This is my first contribution.

**Comment by mamtawardhani** [comment]
Hey @selenahuang017, sure you can take up this issue. Please refer to the Contribution Guide shared in the above comment. Thank you 😃

**Comment by selenahuang017** [comment]
Hi @mamtawardhani i had a quick question, I am looking at the ListIterator oracle docs for all related methods related to the ListIterator. Should I include them here, or is this doc only describing how to create the ListIterator for an arraylist?

**Comment by mamtawardhani** [comment]
@selenahuang017 this is a term entry only for listiterator for an array list 😃

**Comment by selenahuang017** [comment]
@mamtawardhani so to better clarify, I just need to explain how it's created and as an example maybe iterate through the list and print it?

**Comment by selenahuang017** [comment]
I submitted a first draft for review :)
