### ISSUE TITLE
[Term Entry] Java ArrayList .removeAll()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4342]
### Reason/inspiration (optional)

Please add the `.removeAll()` method as a new term entry for [ArrayList](https://www.codecademy.com/resources/docs/java/array-list)�. Provide the entry in a markdown file and place under the file path `content/java/concepts/array-list/terms/removeAll/removeAll.md `

The entry should have the following:
�	An introductory paragraph about what the method is and does.
�	A syntax section with a pseudo code block with an explanation of it.
�	An example showing the method in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by rraunaku** [comment]
Hi, I am a Codecademy working on the Git and GitHub course and I would like to work on this issue.

**Comment by phuongtrieu97coder** [comment]
i'd like to work on this issue

**Comment by bpicoCode** [comment]
Hi, I'd like to take on this issue!

**Comment by KTom101** [comment]
@bpicoCode You're assigned! 😄

**Comment by letsbuildanything** [comment]
@bpicoCode Are you still working on this issue? Note that there's a chance you could be unassigned next week for inactivity. Let me know if you need help. Thanks!

**Comment by bpicoCode** [comment]
@letsbuildanything Lost track of this. Will aim to get it done by the end of the week!

**Comment by mamtawardhani** [comment]
Closing this issue since the entry has been merged 🚀
