### ISSUE TITLE
[Term Entry] Java ArrayList .replaceAll()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4345]
### Reason/inspiration (optional)

Please add the `.replaceAll()` method as a new term entry for [ArrayList](https://www.codecademy.com/resources/docs/java/array-list)�. Provide the entry in a markdown file and place under the file path `content/java/concepts/array-list/terms/replaceAll/replaceAll.md`

The entry should have the following:
�	An introductory paragraph about what the method is and does.
�	A syntax section with a pseudo code block with an explanation of it.
�	An example showing the method in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by dasputekrishna** [comment]
“good first issue”

**Comment by avdhoottt** [comment]
@dasputekrishna Do you want to work on this issue?

**Comment by andrewnotermans** [comment]
@codecademy-docs Hello, can you assign me on this issue?

**Comment by manviii27** [comment]
@SSwiniarski can i work on this?

**Comment by dancikmad** [comment]
I am interested in taking this issue on, I been studying through codecademy for 3 years now

**Comment by SSwiniarski** [comment]
@andrewnotermans, you're assigned.

@manviii27, @dancikmad, @andrewnotermans claimed this first.

**Comment by letsbuildanything** [comment]
@andrewnotermans Are you still working on this issue? Note that there's a chance you could be unassigned next week for inactivity. Let me know if you need help. Thanks!

**Comment by CodedByCoffee** [comment]
I want to work on this issue :)

**Comment by letsbuildanything** [comment]
@CodedByCoffee You're assigned! 🎉

**Comment by CodedByCoffee** [comment]
@letsbuildanything Yes this is my first time :) I am taking a Codecademy course on open source at my company, so this is part of a lab assignment actually.
