### ISSUE TITLE
[Term Entry] Java ArrayList .retainAll()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4346]
### Reason/inspiration (optional)

Please add the `.retainAll()` method as a new term entry for [ArrayList](https://www.codecademy.com/resources/docs/java/array-list). Provide the entry in a markdown file and place under the file path `content/java/concepts/array-list/terms/retainAll/retainAll.md`

The entry should have the following:
�	An introductory paragraph about what the method is and does.
�	A syntax section with a pseudo code block with an explanation of it.
�	An example showing the method in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by devesh-2002** [comment]
May I take up this issue?

**Comment by avdhoottt** [comment]
@devesh-2002 You're assigned!! In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already.  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by devesh-2002** [comment]
Thank you!
Yes, this is my first contibution to Codeacademy Docs. I was actually just scrolling through the issues, and felt like I could start by this issue.

**Comment by mamtawardhani** [comment]
The entry has been merged so closing this issue.
