### ISSUE TITLE
[Term Entry] Python Math Module floor()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4347]
### Reason/inspiration (optional)

"We would like a new term entry on the `math.floor()` function for [Python- Math Module](https://www.codecademy.com/resources/docs/python/math-module): `math.floor()`. The entry should go in a new file under `docs/content/python/concepts/math-module/terms/math-floor/math-floor.md.

The entry should include the following:
- A descrition of the function
- A `## Syntax` section that includes the syntax of the function and its details
- An `## Example` section that includes a ` ```python ``` ` codeblock and ` ```shell ``` ` that shows the example output.
- A `## Codebyte Example` that includes a ` ```codebyte/python ``` ` runnable codeblock

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by andrewnotermans** [comment]
@codecademy-docs Hello, I am enrolled to Git and Github course and have reached the project part about working on Docs. I am interested in taking this issue on.

**Comment by ishg-153** [comment]
@evankart I am assigning you this issue this time.
Please ask to be assigned to the issue you are interested in first and only create a PR for it once you are assigned.

**Comment by evankart** [comment]
ahh I'm sorry @ishg-153 and @andrewnotermans ! I'm new here and didn't realize others were waiting to work on this issue. Will definitely ask to be assigned going forward.
