### ISSUE TITLE
[Term Entry] Python Math Module comb()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4348]
### Reason/inspiration (optional)

"We would like a new term entry on the `math.comb()` function for [Python- Math Module](https://www.codecademy.com/resources/docs/python/math-module): `math.comb()`. The entry should go in a new file under `docs/content/python/concepts/math-module/terms/math-comb/math-comb.md.

The entry should include the following:
- A descrition of the function
- A `## Syntax` section that includes the syntax of the function and its details
- An `## Example` section that includes a ` ```python ``` ` codeblock and ` ```shell ``` ` that shows the example output.
- A `## Codebyte Example` that includes a ` ```codebyte/python ``` ` runnable codeblock

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by avdhoottt** [comment]
@Huyrose1994 You're assigned!! In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already.  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by PavanSusarla** [comment]
I would like to work on this

**Comment by letsbuildanything** [comment]
@Huyrose1994, Are you still working on this issue? Note that there's a chance you could be unassigned next week for inactivity. Let me know if you need help. Thanks!

**Comment by ishg-153** [comment]
@Huyrose1994 Since there was no response from your end, I am unassigning you.

**Comment by mamtawardhani** [comment]
@PavanSusarla are you still interested in taking this issue? Let me know 😃

**Comment by aSagCoder** [comment]
Hi there, I am also interested in this issue and would love to contribute to it!

**Comment by mamtawardhani** [comment]
Hey @aSagCoder! You're assigned!! In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already. After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by ishg-153** [comment]
@aSagCoder It's been 2 weeks since you were assigned to this issue. Are you still working on the entry?

**Note:** If you don't respond with a PR or an update within a week, this issue will be unassigned from you.

**Comment by aSagCoder** [comment]
@ishg-153  Hi, sorry for the late response! I am still working on it and will hopefully be able to submit a PR within the next few days.
