### ISSUE TITLE
[Term Entry] Python Math Module remainder()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4349]
### Reason/inspiration (optional)

"We would like a new term entry on the `math.remainder()` function for [Python- Math Module](https://www.codecademy.com/resources/docs/python/math-module): `math.remainder()`. The entry should go in a new file under `docs/content/python/concepts/math-module/terms/math-remainder/math-remainder.md.

The entry should include the following:
- A descrition of the function
- A `## Syntax` section that includes the syntax of the function and its details
- An `## Example` section that includes a ` ```python ``` ` codeblock and ` ```shell ``` ` that shows the example output.
- A `## Codebyte Example` that includes a ` ```codebyte/python ``` ` runnable codeblock

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Piergiulio** [comment]
Good evening, I'm doing at the moment a course on Git and GitHub with CodeCademy and I will be interested to take on this issue

**Comment by Piergiulio** [comment]
@avdhoottt , Thank you very much for the information and looking forward to start working on the issue tonight. This is my first contribution and I found out about contributing to Docs trough the Git and GitHub course I'm doing with Codecademy
