### ISSUE TITLE
[Edit] os.path.join

### ISSUE THREAD

**Issue by jeremyngcode** [Codecademy/docs#4351]
### Type of Edit (select all that apply)

Clarify unclear content and/or terms

### Description (optional)

In the `.join()` method from this [page](https://www.codecademy.com/resources/docs/python/os-path-module/join), it seems that the explanation is missing some nuance as to how this method behaves, one example being that if any argument begins with a `/`, then all previous arguments will be skipped. 

However, I do understand also if Codecademy has intentionally kept it simple. If this is the case, then I believe the `/` in `"learn-python-3/lessons/"` should be removed in order to align with the explanation given above it which says "Before being added to the returned value, each subsequent `path_` string is prepended with a forward-slash `/`", because if not, then there would be a double forward-slash in the path string.

If a more elaborate explanation for the `.join()` method isn't desired, then this should be a quick fix. I can expand on this also if that is ok with the team.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by RobinNap** [comment]
@jeremyngcode Would I be able to take this issue?

**Comment by jeremyngcode** [comment]
Hi @RobinNap, this issue isn't opened by the team, it's opened by me.

**Comment by scottfinamore** [comment]
I am still waiting to complete my first issue on Codecademy's GitHub. May I please work on this issue for the completion of my program? Thank you!

**Comment by nbarnhouse** [comment]
Hi @codecademy-docs I would like to work on this.

**Comment by kinggizz202** [comment]
Hello, may i please take on this issue. Thanks
