### ISSUE TITLE
[Bug/Error] Subject: CodeByte example issue using namedtuple defaults parameter

### ISSUE THREAD

**Issue by l2es** [Codecademy/docs#4356]
### Actual Behavior

From the namedtuple python collections module docs :
https://www.codecademy.com/resources/docs/python/collections-module/namedtuple
When you run the Codebyte Example you get this error :

```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    myNamedTuple = namedtuple('myNamedTuple', ['a', 'b', 'c'], defaults=[0, 2, 4])
TypeError: namedtuple() got an unexpected keyword argument 'defaults'`
```

After some research, it seems that the Python version used by the workspace does not support the defaults parameter. The defaults parameter requires at least Python version 3.7.0.

### Expected Behavior

The CodeByte output should be

```
('a', 'b', 'c')
---
myNamedTuple(a=0, b=1, c=2)
2
{'a': 0, 'b': 1, 'c': 2}
---
myNamedTuple(a=0, b=1, c=3)
---
{'a': 0, 'b': 2, 'c': 4}`
```

### On what browser(s) are you seeing the problem?

Chrome

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by l2es** [comment]
I can take the issue to remove references to defaults if needed

**Comment by ogumbaiyke** [comment]
Hi.


Can i work on bug/error? Thanks

**Comment by WorananH** [comment]
I am interested in taking this issue on, I found out about Docs through a friend.

**Comment by Electromagnet83** [comment]
Can I work on this error?

**Comment by StephRP12** [comment]
Could I work on this?

**Comment by ShreeManekar** [comment]
from collections import namedtuple

myNamedTuple = namedtuple('myNamedTuple', ['a', 'b', 'c'])
myNamedTuple.__new__.__defaults__ = (0, 1, 2)
nt = myNamedTuple()
print(nt)
print(nt._asdict())
nt2 = myNamedTuple(c=3)
print(nt2._asdict())

try this code

**Comment by cigar-galaxy82** [comment]
Hi @ishg-153 this issue is assigned to you
