### ISSUE TITLE
[Term Entry] Dart Maps .values()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4368]
### Reason/inspiration (optional)

"We would like a new term entry under Dart [Maps](https://www.codecademy.com/resources/docs/dart/concept/map) for the Dart Map `.values()` method. 
Provide the entry in a markdown file under `docs/content/dart/concepts/map/terms/values/values.md`

The entry should
    - Have an introductory paragraph about what the method is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the method in use.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by lamalamalana** [comment]
Hi, I'd be happy to get assigned on this issue and work on it. May I? Thanks in advance.

**Comment by lamalamalana** [comment]
@codecademy-docs I've noticed that the folder stucture in the current Docs repository is slightly different to the one mentioned in the issue description, so I would suggest it to be changed to docs\content\dart\concepts\list\terms\values\values.md

**Comment by lamalamalana** [comment]
@codecademy-docs Hi, I'd just like to bring to your attention that https://www.codecademy.com/resources/docs/dart/concept/map is broken. Also, as a student of the web development course, there are currently no open issues that seem appropriate for my knowledge (no css, html, javascript ...). Just a suggestion, but perhaps the issues could be a bit more generic if the point is for students to get familiar with the workflow of contributing to an open source project. Thanks!

**Comment by ishg-153** [comment]
Hey @lamalamalana, Thank you for pointing out the issue with `maps` concept entry, I will look into it. About more beginner-friendly issues, we keep a mix of intermediate and beginner-level issues, both of which can be written with a little bit of research. 
Keep your eyes peeled as new issues get uploaded every Monday, that's today! You should find something to work on in this week's lot!

Please let me know if you are interested in working on this issue.

**Comment by AverageCodeTechnician** [comment]
Hi, I'd like to take on this issue for the CodeAcademy team. There's a good website that helps explain this issue.

**Comment by AverageCodeTechnician** [comment]
Greetings Daksha

Yes, as a matter of fact this is my first contribution to Codecademy Docs.
I'm sorry this is taking so long; I'm nervous and don't want to make
crucial mistakes.
 In college we have to watch out for plagiarism so we therefore have to
cite our sources. Do I have to cite my sources as well? And if so, should
they be cited; with MLA or APA formatting? Do we cite in our markdown file
or do we submit them to somebody?
 The term entry for Dart [.length()] has been done and I looked into the
raw markdown code. It looks similar to the syntax used in a file from the
Docs Documentation folder. Is there a way to respectfully copy how that
work was done?

The link to the instructional video is here:
https://www.youtube.com/watch?v=sPijoK5Scdg
<https://www.youtube.com/watch?v=sPijoK5Scdg>
The link to the Documentation file is here:
https://raw.githubusercontent.com/Codecademy/docs/main/content/dart/concepts/map/terms/length/length.md

Yours truly,

Enrique A.

**Comment by AverageCodeTechnician** [comment]
I deleted my repo because I thought that was what I was supposed to do but, no worries I still have the .md file needed to turn in my work with. Am I still assigned to this task?

**Comment by VeraLK** [comment]
Hey there! Can I take upon the issue please? I'd love to try and contribute as I am new it that but I'd be happy to learn new skills :) Thanks

**Comment by mamtawardhani** [comment]
@VeraLK are you still interested in taking up this issue? Let me know 😃

**Comment by Sriparno08** [comment]
Hey @mamtawardhani, it's been almost a month and @VeraLK hasn't responded yet. So, I'm assigning this issue to myself.
