### ISSUE TITLE
[Term Entry] Dart Maps .containsValue()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4370]
### Reason/inspiration (optional)

"We would like a new term entry under Dart [Maps](https://www.codecademy.com/resources/docs/dart/concept/map) for the Dart Map `.containsValue()` method. 
Provide the entry in a markdown file under `docs/content/dart/concepts/map/terms/containsValue/containsValue.md`

The entry should
    - Have an introductory paragraph about what the method is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the method in use.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by aaron-ross-sanchez** [comment]
Hello!
I would like to tackle this issue if possible!
Thank you!

**Comment by ishg-153** [comment]
@aaron-ross-sanchez You're assigned!🎉

**Note:** This is your third assigned issue. Make sure to create PRs for these issues before requesting more.

**Comment by ishg-153** [comment]
@aarosan Since there was no response from your end, I am unassigning you.
