### ISSUE TITLE
[Term Entry] Dart Maps .forEach()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4372]
### Reason/inspiration (optional)

"We would like a new term entry under Dart [Maps](https://www.codecademy.com/resources/docs/dart/concept/map) for the Dart Map `.forEach()` method. 
Provide the entry in a markdown file under `docs/content/dart/concepts/map/terms/forEach/forEach.md`

The entry should
    - Have an introductory paragraph about what the method is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the method in use.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by ishg-153** [comment]
@aaron-ross-sanchez You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by aaron-ross-sanchez** [comment]
Thank you! I found out about this repository through the good first issues website: https://goodfirstissues.com/index.html

**Comment by aaron-ross-sanchez** [comment]
@ishg-153 I just wanted to check to see that this was for the Dart Map .forEach() method, and not .length()

> "We would like a new term entry under Dart [Maps](https://www.codecademy.com/resources/docs/dart/concept/map) for the Dart Map `.length()` method.

**Comment by ishg-153** [comment]
@aarosan Since there was no PR from your end, I am unassigning you.

**Comment by arisdelacruz** [comment]
Uhm, sorry, is this for the .forEach() method or the .length() method? Thanks

**Comment by Sriparno08** [comment]
Hey @avdhoottt, are you still working on this issue?

**Comment by avdhoottt** [comment]
@Sriparno08 yes, I'll make a PR for that.

**Comment by Sriparno08** [comment]
How's the entry going along, @avdhoottt?
