### ISSUE TITLE
[Term Entry] Dart Maps .remove()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4374]
### Reason/inspiration (optional)

"We would like a new term entry under Dart [Maps](https://www.codecademy.com/resources/docs/dart/concept/map) for the Dart Map `.remove()` method. 
Provide the entry in a markdown file under `docs/content/dart/concepts/map/terms/remove/remove.md`

The entry should
    - Have an introductory paragraph about what the method is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the method in use.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by dancikmad** [comment]
Hi, I would love to be assigned this issue and work on it.

**Comment by ishg-153** [comment]
@dancikmad You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by dancikmad** [comment]
@ishg-153 Thank you! I found out about contributing to codecademy docs after taking a wide range of courses on the platform! 

I will start working on this issues now! 🚀
