### ISSUE TITLE
[Term Entry] Dart String .length()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4376]
### Reason/inspiration (optional)

"We would like a new term entry under Dart [Strings](https://www.codecademy.com/resources/docs/dart/concept/strings) for the Dart Strings `.length()` method. 
Provide the entry in a markdown file under `docs/content/dart/concepts/strings/terms/lenght/length.md`

The entry should
    - Have an introductory paragraph about what the method is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the method in use.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by manviii27** [comment]
@SSwiniarski can i work on this?

**Comment by ishg-153** [comment]
@manviii27 You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

**Comment by letsbuildanything** [comment]
@manviii27, are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by PaulNica** [comment]
Hi there, I would like to take on this issue as a part of my **Learn Git & Github** project.

**Comment by letsbuildanything** [comment]
@PaulNica You’re assigned :tada:  In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.
Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by PaulNica** [comment]
@letsbuildanything Thank you! Yes, this is my first contribution and I am a bit nervous, but let's hope for the best. This is one of the final projects in the "Learning Git & Github" course and I want to do it right. Most Issues I was "comfortable" working on were taken so I had to go outside my comfort zone and try something different.
