### ISSUE TITLE
[Edit] Git [Edit] Git: Pull Requests

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4377]
### Type of Edit (select all that apply)

Clarify unclear content and/or terms

### Description (optional)

Edit the section "Method 1: Fork" under the existing Git: [Pull Requests](https://www.codecademy.com/resources/docs/git/pull-requests) entry to include an explaination of exactly when a fork is needed. This can be added at the end of the section as a blockquoted bolded note (> *Note:* ).

The entry lives in `docs/main/content/git/concepts/pull-requests/pull-requests.md`

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by liye0** [comment]
@codecademy-docs I would like to be assigned to this issue.

**Comment by ParkerSwift** [comment]
Can I work on this as well?

**Comment by ishg-153** [comment]
@liye0 You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by ishg-153** [comment]
@ParkerSwift ,@liye0 asked to be assigned first.

**Comment by liye0** [comment]
> @liye0 You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.
> 
> I see this is your first time contributing to Codecademy Docs. How did you find out about us?

I'm doing this for the portfolio project for the Learn Git and Github lessons on Code Academy.
