### ISSUE TITLE
[Edit] JavaScript [Edit] JavaScript Arrays: .slice()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4378]
### Type of Edit (select all that apply)

Clarify unclear content and/or terms

### Description (optional)

Edit the intro to JavaScript Arrays: [.slice()](https://www.codecademy.com/resources/docs/javascript/arrays/slice) entry to clarify what a shallow copy is. The existing definition is worded in a way that can be confusing for beginners.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by fa125had** [comment]
Hello, 
I like to work on this issue if it's possible.
thank you

**Comment by ishg-153** [comment]
@fa125had You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

**Comment by fa125had** [comment]
@ishg-153 Thank you

**Comment by willphan1712000** [comment]
Hello, I do not know if I can work on this issue. I am currently in Learn Git and Github course.
