### ISSUE TITLE
[Edit] CSS [Edit] CSS Typography: font-style

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4416]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like an edit to a term within CSS `font-style`. The term entry lives in `content/css/concepts/typography/terms/font-style/font-style.md`

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media (images, gifs) should accurately represent the existing code blocks in the example sections and fit in-line. ex: [See last image here](https://www.codecademy.com/resources/docs/html/attributes/title)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by SarahCarlock** [comment]
@codecademy-docs  I am interested in working on this issue.

**Comment by ishg-153** [comment]
@SarahCarlock You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by SarahCarlock** [comment]
@ishg-153 Thank you! I've been working through several of the tutorials and this was a next step during the Git & GitHub lesson.

**Comment by AnjaliRadhe** [comment]
@codecademy-docs Could I please work on this issue? thank you.

**Comment by mark1usya** [comment]
Let me take up this issue

**Comment by nmatesa** [comment]
I am interested in taking up this issue.

**Comment by PaulNica** [comment]
Hi there, I would like to take on this issue as a part of my **Learn Git & Github** project.

**Comment by BenjamiLudvik** [comment]
Hello, I'm 76 years old and I'm still learning, now I'm working on "Codecademy" with Git & Github. I chose this issue as part of further learning in the Git & Github project.

**Comment by letsbuildanything** [comment]
@BenjamiLudvik 
It's truly wonderful to hear about your commitment to learning at 76. I wanted to kindly inform you that this issue has already been `merged`. However, there are many other issues that have not been `claimed` available for you to explore and contribute to. Keep up the fantastic work, and don't hesitate to ask if you need any assistance!

**Comment by tatianamores** [comment]
I am interested in taking this issue on. I found out about Docs through a course
