### ISSUE TITLE
[Edit] CSS [Edit] CSS Typography: text-align

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4418]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like an edit to a term within CSS `text-align`. The term entry lives in `content/css/concepts/typography/terms/text-align/text-align.md`

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media (images, gifs) should accurately represent the existing code blocks in the example sections and fit in-line. ex: [See last image here](https://www.codecademy.com/resources/docs/html/attributes/title)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by dancikmad** [comment]
Hi, I would love to work on this issue.

**Comment by kamlesh-ops** [comment]
Hii
Can I take up this issue?

**Comment by ishg-153** [comment]
@dancikmad You're assigned!🎉 

You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

**Note**: I see that you have other issues assigned to you that still have open PRs or need PRs to be created. Make sure to keep working on those as well.

**Comment by ishg-153** [comment]
@kamlesh-ops, @dancikmad asked to be assigned first.

**Comment by dancikmad** [comment]
@ishg-153 This is pretty much done, I will review it and probably tmr will create a PR that closes this Issue.

**Comment by mark1usya** [comment]
Can I try take up this issue?

**Comment by dancikmad** [comment]
Hi, this has been left for a while together with my other tasks due to being busy with working on some back-end projects.

I should be able to submit a PR this weekend hopefully.

**Comment by PaulNica** [comment]
Hi there, I would like to take on this issue as a part of my **Learn Git & Github** project.

**Comment by ishg-153** [comment]
@dancikmad Since there was no response from your end, I am unassigning you.

**Comment by mamtawardhani** [comment]
@PaulNica @mark1usya @kamlesh-ops any of you are still interested in taking up this issue? Let me know 😃

**Comment by andres3204** [comment]
I would like to work on this issue!

**Comment by mamtawardhani** [comment]
Hey @andres3204! You're assigned!🎉

You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.
