### ISSUE TITLE
[Edit] CSS [Edit] CSS Typography: text-decoration

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4419]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like an edit to a term within CSS `text-decoration`. The term entry lives in `content/css/concepts/typography/terms/text-decoration/text-decoration.md`

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media (images, gifs) should accurately represent the existing code blocks in the example sections and fit in-line. ex: [See last image here](https://www.codecademy.com/resources/docs/html/attributes/title)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by dancikmad** [comment]
Hi, I finished my working on 2 of my issues assigned.

I would love to work on this issue.

**Comment by kamlesh-ops** [comment]
Hii 
Can I take up this issue?

**Comment by ishg-153** [comment]
@dancikmad You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

**Comment by ishg-153** [comment]
@kamlesh-ops , @dancikmad was here first.

**Comment by Vishal-5121** [comment]
Hi, I finished my working on 2 of my issues assigned.

**Comment by VeraLK** [comment]
Hey there! Can I work on this issue please?

**Comment by dancikmad** [comment]
@ishg-153 Hi, I am finished with the task. I probably will create a PR tonight that closes this issue

**Comment by mark1usya** [comment]
Hello, I would like to try

**Comment by nmatesa** [comment]
I'd be interested in working on this issue for the Codecademy Docs Repository in the 'Learn Git & GitHub' course.

**Comment by RebeccaCrecelius** [comment]
Hello. CSS is my favorite language of all time! May I please be assigned this issue.

**Comment by ishg-153** [comment]
@dancikmad Since there was no response from your end, I am unassigning you.

**Comment by ishg-153** [comment]
@RebeccaCrecelius You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by RebeccaCrecelius** [comment]
@ishg-153 Thank you for assigning me. Do you have a timeframe in which you would like for this to be completed?

I am taking courses at Codecademy. My main focus is the Front-End Engineer Path, but I am also completing the Learn Git & GitHub course.

**Comment by RebeccaCrecelius** [comment]
I am really confused by this project. Is there anywhere contributors get together to discuss contributions?

**Comment by ishg-153** [comment]
Hey @RebeccaCrecelius! What do you need help with?

**Comment by RebeccaCrecelius** [comment]
@ishg-153 in general, I do not understand. I was looking to contribute with HTML and/ or CSS. However, it seems as though this project is supposed to be written in Markdown. Is that correct?

**Comment by ishg-153** [comment]
@RebeccaCrecelius, yes! The term is written in a `.md` file, but it is about CSS text-decoration property. And you are only expected to add an image of the already existing example in the current entry.

Please let me know if you will be able to work on this issue.

**Comment by RebeccaCrecelius** [comment]
@ishg-153 Thank you for clarifying. Yes, I would still like to work on the entry. I will look at it again tomorrow and let you know if I have any trouble.

**Comment by RebeccaCrecelius** [comment]
@ishg-153 I just submitted the updates. I did notice there was some content which seemed a bit confusing. It is regarding the p tag being set to center. I was not sure if that was a typo or if it was something to be updated later, so I did not change it. Looking forward to the review.

**Comment by ishg-153** [comment]
Hey @RebeccaCrecelius, thanks for pointing that out. You can go ahead and make a change to that sentence so that it is more related to the example below it. (i.e the text-decoration property and its `underline` value)

**Comment by RebeccaCrecelius** [comment]
@ishg-153 Sounds good. I will update it soon.

**Comment by RebeccaCrecelius** [comment]
@ishg-153 I am not sure if this is because my first commit has yet to be reviewed and merged, but I made the changes to the text. It now matches the example. When running git log, I am showing the commit was successful. However, I am not getting the option to compare an pull. The branch I am working on is currently four commits ahead of the main branch.

**Comment by Sriparno08** [comment]
Unassigning the author due to inactivity.

**Comment by Sriparno08** [comment]
Hey @ummagohil, you're assigned!

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

**Comment by ummagohil** [comment]
Can't link the issue but PR can be seen here: https://github.com/Codecademy/docs/pull/5527
