### ISSUE TITLE
[Edit] Subject: Erroneous link in Codecademy Docs file/document -> Docs/JavaScript/Objects

### ISSUE THREAD

**Issue by S1791** [Codecademy/docs#4427]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

There is a broken link in https://www.codecademy.com/resources/docs/javascript/objects

In the section Object classes the sentence:

"An additional step can be made to optimize this procedure through the use of a [constructor](https://www.codecademy.com/resources/docs/javascript/constructor)."

The link refers to the constructor doc but is missing an "s" in the link.

Current link: https://www.codecademy.com/resources/docs/javascript/constructor
Correct link: https://www.codecademy.com/resources/docs/javascript/constructors

I hope I categorized this correct.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by zkhOlga** [comment]
Dear Team, I would like to work on this issue

**Comment by ishg-153** [comment]
@zkhOlga I am assigning the issue to you this time but in the future wait to be assigned to an issue you would like to work on before creating a PR. Not doing so can cause a lot of confusion.

**Comment by S1791** [comment]
@ishg-153: no probs letting @zkhOlga fixing this. I wouldn't know how to anyway (noob as I am). At least not yet...
