### ISSUE TITLE
[Concept Entry] Numpy: New Concept Entry for `math-methods.md`

### ISSUE THREAD

**Issue by avdhoottt** [Codecademy/docs#4446]
### Reason/inspiration (optional)

We would like a new concept entry for Numpy about the Math Methods. The entry should go in a new file in `docs/content/numpy/concepts/math-methods/math-methods.md`

The entry should
- Have an introductory paragraph about the concept.
- Code block(s) displaying different aspects of the concept.
- A concluding header, Functions, and future terms will be listed below this header

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by gitsoft145** [comment]
@avdhoottt I am interested in taking this issue  on, This is my first issue that i need to contribute to codeacademy docs.

**Comment by ogumbaiyke** [comment]
Hi. I am interested. Can I work on this issue?

**Comment by lukesobo** [comment]
I am also interested in working on this issue or any new issue!

**Comment by ishg-153** [comment]
This Issue has been completed by #4513 PR.
