### ISSUE TITLE
[Concept Entry] Java Deque Deque

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4451]
### Reason/inspiration (optional)

"We would like a new concept entry for [Java](https://www.codecademy.com/resources/docs/java) on Deque.
Provide the entry in a markdown file under `docs/content/java/concepts/deque/deque.md`

The entry should
    - Have an introductory paragraph about the deque data structure.
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the use of deque.
    - Explain the equivalent method for stacks and queue.
Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Great-Visions-Code** [comment]
I would like to take on this issue please. This would be my first contribution. Thank you.

**Comment by natikaggarwal** [comment]
Hello, I would like to request being assigned to this issue. I am new to open source contributions, and I would like to contribute to this library!

**Comment by Preran-D** [comment]
Hello I would like to contribute for this library - java deque.

**Comment by 3nk1dev** [comment]
Hi, I'm doing the github course and would like to add this content

**Comment by Kmerica** [comment]
@codecademy-docs I would be interested in taking this issue on.

**Comment by letsbuildanything** [comment]
@natikaggarwal, Are you still working on this issue? It's been over a month, and there's a chance you could be unassigned next week for inactivity. Let me know if you need help. Thanks!

**Comment by ishg-153** [comment]
@natikaggarwal Since there was no response from your end, I am unassigning you.

**Comment by mamtawardhani** [comment]
@Preran-D @Kmerica are either of you still interested in taking up this issue? Let me know 😃

**Comment by zottima** [comment]
@mamtawardhani if neither of them is responding, I'd be interested in taking this issue. :)

**Comment by ishg-153** [comment]
@zottima You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by ishg-153** [comment]
@zottima It's been 2 weeks since you were assigned to this issue. Are you still working on the entry?

**Note:** If you don't respond with a PR or an update within a week, this issue will be unassigned from you.

**Comment by zottima** [comment]
Yes, I am.

**Comment by ishg-153** [comment]
@zottima Please try to create a PR in a weeks time.

**Comment by zottima** [comment]
@ishg-153 I'll need a couple more days. Hope that's okay.

**Comment by ishg-153** [comment]
@zottima Will you be able to create a PR by end of this week?

**Comment by zottima** [comment]
Yes, should have it ready tomorrow.

**Comment by zottima** [comment]
@ishg-153 I cannot push my branch, I get 403, no write access.

**Comment by ishg-153** [comment]
Hey @zottima can you make sure you are pushing the commit to a separate branch of your fork of this repository?

**Comment by zottima** [comment]
Oh, didn't know I had to use fork. Might be good to include that fact in the readme. :)

**Comment by ishg-153** [comment]
@zottima Thank you for pointing that out! I'll make sure we make this change.
