### ISSUE TITLE
[Concept Entry] Python Deque Deque

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4452]
### Reason/inspiration (optional)

"We would like a new concept entry for [Python](https://www.codecademy.com/resources/docs/python) on Deque.
Provide the entry in a markdown file under `docs/content/python/concepts/deque/deque.md`

The entry should
    - Have an introductory paragraph about the deque data structure.
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the use of deque.
    - Explain the equivalent method for stacks and queue.
Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by kamlesh-ops** [comment]
Hii
I would like to take up the issue.
Thanks

**Comment by Aquacoder345** [comment]
Hi, I would like to take this issue. This is for my Git/Github course I am taking.

**Comment by Aquacoder345** [comment]
@codecademy-docs Hi, I would like to take this issue. I am doing the Git/Github course

**Comment by Aquacoder345** [comment]
@dakshdeepHERE thank you!
