### ISSUE TITLE
[Concept Entry] C++ Deque Deque

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4453]
### Reason/inspiration (optional)

"We would like a new concept entry for [C++](https://www.codecademy.com/resources/docs/cpp) on Deque.
Provide the entry in a markdown file under `docs/content/cpp/concepts/deque/deque.md`

The entry should
    - Have an introductory paragraph about the deque data structure.
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the use of deque.
    - Explain the equivalent method for stacks and queue.
Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by diwiw** [comment]
@codecademy-docs I am interested in taking this issue on, I found it through Docs when I was looking for a new Issue for my git course on codecademy. I have experience with C++ projects, thus I would love to put my knowledge here and also learn or correct my informations.

**Comment by kimikatiti** [comment]
@codecademy-docs Hello there, I am interested in working on this issue as I recently completed Codecademy's Learn C++ course and feel like this will expand on both my knowledge base on Git and Github (currently working through the GitHub course) as well as my experience in C++ and Markdown. I see that someone else already placed a request ahead of me, so if there is another C++ related issue I can dive into, it'd be my pleasure! Thank you.

**Comment by ishg-153** [comment]
@dakshdeepHERE Are you still working on the entry?

**Comment by Sriparno08** [comment]
Hey @dakshdeepHERE, are you still working on this issue?

**Comment by mamtawardhani** [comment]
Hey @diwiw @kimikatiti are any of you still interested in taking up this issue?

**Comment by avdhoottt** [comment]
> Hey @avdhoottt, are you still working on this issue?

Sorry for the delay. Yes, I'll make a PR for this issue.
