### ISSUE TITLE
[Concept Entry] C# Deque Deque

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4454]
### Reason/inspiration (optional)

"We would like a new concept entry [C#](https://www.codecademy.com/resources/docs/c-sharp) on Deque.
Provide the entry in a markdown file under `docs/content/c-sharp/concepts/deque/deque.md`

The entry should
    - Have an introductory paragraph about the deque data structure.
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the use of deque.
    - Explain the equivalent method for stacks and queue.
Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by kimikatiti** [comment]
I'd like to tackle this issue.

**Comment by kimikatiti** [comment]
I would like to take on this issue

**Comment by sadeghrastegar** [comment]
I'm interested in keeping this issue on.

**Comment by ishg-153** [comment]
@kimikatiti You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by ishg-153** [comment]
@sadeghrastegar, @kimikatiti was here first. Please feel free to ask to be assigned to any other [available issue](https://github.com/Codecademy/docs/issues?q=is%3Aopen+is%3Aissue+-label%3A%22claimed%22) that interests you.

**Comment by kimikatiti** [comment]
> @kimikatiti You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.
> 
> I see this is your first time contributing to Codecademy Docs. How did you find out about us?

Thank you so much @ishg-153 - I completed the Git and GitHub course but I need to finish the Contribute to Docs portfolio project, which is why I'm here! :)

**Comment by kimikatiti** [comment]
> @sadeghrastegar, @kimikatiti was here first. Please feel free to ask to be assigned to any other [available issue](https://github.com/Codecademy/docs/issues?q=is%3Aopen+is%3Aissue+-label%3A%22claimed%22) that interests you.

I might not complete this assignment in time as well @ishg-153 --you may assign it to someone else.

**Comment by letsbuildanything** [comment]
@sadeghrastegar, are you still interested in working on this issue?

**Comment by kingsleyndife** [comment]
@letsbuildanything I am interested in taking this project. This is my first entry.

**Comment by kingsleyndife** [comment]
@letsbuildanything I am interested in taking this project. This is my first entry.

**Comment by r-bellamy** [comment]
I would like this issue please.

**Comment by doroodianMostafa** [comment]
Hi, I am a student of codecademy and working on Learn Git & GitHub course. I would like to work on this project. Thanks!
@codecademy-docs

**Comment by letsbuildanything** [comment]
@kingsleyndife You’re assigned :tada:  In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.
Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by letsbuildanything** [comment]
@r-bellamy and @doroodianMostafa, @kingsleyndife got here first. Please look for the other unclaimed issues.
Thank you!

**Comment by ishg-153** [comment]
@kingsleyndife It's been 2 months since you were assigned this Issue. Since there was no response from your end, I am unassigning you.

**Comment by mamtawardhani** [comment]
@doroodianMostafa @r-bellamy @kingsleyndife @sadeghrastegar 
are any of you still interested in taking up this issue? Let me know 😃

**Comment by kingsleyndife** [comment]
i am not interested in the issue 
thank  you

**Comment by wiki-152** [comment]
@ishg-153 @letsbuildanything @codecademy-docs Hi, I would like take this issue.

**Comment by ishg-153** [comment]
@wiki-152 You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by Sriparno08** [comment]
Hey @wiki-152, it's been a month and there's no PR from your side. Are you still working on this issue?

**Comment by Sriparno08** [comment]
Hey @wiki-152, you're unassigned due to inactivity.

**Comment by Johnnie-kay** [comment]
Hello @Sriparno08, please assign this issue to me let's close it.

**Comment by Sriparno08** [comment]
Hey @Johnnie-kay, this issue is already assigned to another contributor.

**Comment by VishalPatel9921** [comment]
i am interesting taking in this issue on, I found out Docs through a friend

**Comment by Sriparno08** [comment]
Hey @VishalPatel9921, this issue is already assigned to another contributor.
