### ISSUE TITLE
[Term Entry] Dart Queue .contains()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4458]
### Reason/inspiration (optional)

"We would like a new term entry under Dart [Queue](https://www.codecademy.com/resources/docs/dart/concept/queue) for the Dart Queue `.contains()` method. 
Provide the entry in a markdown file under `docs/content/dart/concepts/queue/terms/contains/contains.md`

The entry should
    - Have an introductory paragraph about what the method is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the method in use.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by VeraLK** [comment]
Hello there! I'm new to contributing but I'd like to give it a try :) Can I be assinged to this isuue please?

**Comment by Arya-Winters** [comment]
Hello,

I was wondering if this issue has been assigned or not?

If not, may I be assigned to it? I am currently completing the Git&Github course on CodeAcademy and need to contribute to docs for part of it.

Thanks!

**Comment by ishg-153** [comment]
@VeraLK You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by ishg-153** [comment]
@Arya-Winters, @VeraLK was here first. Please feel free to ask to be assigned to any other available issues that interest you.

**Comment by VeraLK** [comment]
@ishg-153 Thank you for assigning me! I'll do it th first thing in the morning :) I found through my course in Codecademy and I have been serching for an issue to contribute for about a week now! I am so happy that I finally can try and do it because this was the last task that I have to do to finish my course :)

**Comment by letsbuildanything** [comment]
@VeraLK It's been three weeks. Are you still working on this entry? 
 If you're facing any challenges, please feel free to let us know.

**Comment by ishg-153** [comment]
@VeraLK Since there was no response from your end, I am unassigning you.

**Comment by mamtawardhani** [comment]
HEy @Arya-Winters are you still interested in taking up this issue? Let me know 😃

**Comment by arisdelacruz** [comment]
Hello. Good day. Just wonderin' if this task is already done. Thanks

**Comment by mamtawardhani** [comment]
> You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.
> 
> I see this is your first time contributing to Codecademy Docs. How did you find out about us?

Hello @arisdelacruz, no this issue is still open, would you like to take this up?

**Comment by arisdelacruz** [comment]
Yeah, I'll take this one. Thanks, @mamtawardhani

**Comment by mamtawardhani** [comment]
Great @arisdelacruz! You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by arisdelacruz** [comment]
Thanks, @mamtawardhani . If my memory serves me right, this will be my 16th contribution to docs. Just had a hiatus, but, I'm back. Thank you for assigning me.

**Comment by arisdelacruz** [comment]
Btw, @mamtawardhani , just saw an entry on .contains() made by Vera Key, two (2) months ago. Would like to clarify on this. Thanks.

**Comment by mamtawardhani** [comment]
> Btw, @mamtawardhani , just saw an entry on .contains() made by Vera Key, two (2) months ago. Would like to clarify on this. Thanks.

@arisdelacruz the entry submitted by the author was empty, so it was closed by the author

**Comment by arisdelacruz** [comment]
Hi. Good day. Finishing my entry now. Thanks.

**Comment by arisdelacruz** [comment]
@Sriparno08 meaning the empty entry was closed?

**Comment by Sriparno08** [comment]
Hey @arisdelacruz, it seems that the term entry has already been created. So, I've closed this issue. Apologies for the confusion.

**Comment by arisdelacruz** [comment]
@Sriparno08 it's okay. I'll just work on another entry. Thanks for the heads up.
