### ISSUE TITLE
[Term Entry] UI and UX Design UIUX (Ideation) User Stories

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4461]
### Reason/inspiration (optional)

"We would like a new term entry on the `user-story` term for [UIUX](https://www.codecademy.com/resources/docs/uiux): User Stories. The entry should go in a new file under `docs/content/uiux/concepts/user-story/user-story.md`.

The entry should describe the term and how it is used within UX. Also include: 
- An "Example" section that explains user stories
- add images to aid understanding of user stories (if required).

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by MattPahuta** [comment]
Hello there. I'd be happy to take this on. Thanks.

**Comment by MattPahuta** [comment]
Thanks @ishg-153! I'm Codecademy Pro member, working through the frontend engineer career path, and have been meaning to start contributing to the Docs for a while now.

**Comment by rodasamortin** [comment]
Hi, @ishg-153. I'm happy to contribute here. 🙋🏽‍♀️ Thanks.

**Comment by ishg-153** [comment]
Hey @rodasamortin, @MattPahuta is already working on this. Please take a look at available issues and ask to be assigned to one based on your interests.
