### ISSUE TITLE
[Bug/Error] HTML Trailing Slashes : Best practice to not include XHTML-style trailing slashes in the HTML docs.

### ISSUE THREAD

**Issue by YS-Abstract** [Codecademy/docs#447]
### Type of Edit (select all that apply)

Clarify unclear content and/or terms

### Description (optional)

According to [MDN HTML Guidelines](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/HTML#trailing_slashes), 

> Don't include XHTML-style trailing slashes for empty elements, as they are unnecessary and slow things down. They can also break old browsers if you are not careful (although from what we can recall, this hasn't been a problem since Netscape 4).

It's only a matter of style, but removing the trailing slashes improves the clarity and consistency of the code - especially since they are not referenced in the curriculum. 

The pages where I have found trailing slashes include:
- [Attributes](https://www.codecademy.com/resources/docs/html/attributes)
- [Forms](https://www.codecademy.com/resources/docs/html/forms)
- [Images](https://www.codecademy.com/resources/docs/html/images)
- [Links](https://www.codecademy.com/resources/docs/html/links)
- [Videos](https://www.codecademy.com/resources/docs/html/videos)

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by r3vert** [comment]
Can I work on this?

**Comment by Dusch4593** [comment]
@r3vert I'm actually going to reserve this issue for later time since a lot of flies may need to be edited.

**Comment by SSwiniarski** [comment]
@Dusch4593, want me to go though all these?

**Comment by Dusch4593** [comment]
Sure! Appreciate it 🙏🏻

**Comment by Dusch4593** [comment]
Closing this issue since [it has been settled](https://github.com/Codecademy/docs/pull/533#issuecomment-1026074172) that the utility of removing trailing slashes is not significant enough to warrant going forward with file edits.
