### ISSUE TITLE
[Term Entry] Python:NumPy built-in-functions Correlation Coefficient

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4475]
### Reason/inspiration (optional)

"We would like a new term entry on the `built-in-functions` term for [Numpy](https://www.codecademy.com/resources/docs/numpy): corrcoef. The entry should go in a new file under `docs/content/numpy/concepts/built-in-functions/terms/correlation-coefficient/correlation-coefficient.md`.

The entry should describe the term and how it is used within statistical analysis. Also include: 
- An "Example" section that explains readers how to use the Correlation Coefficient statistical function.
- Should contain informations for functions and syntax.
- Should have a python codebyte with working code snippet showcasing this function.
Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by paww81** [comment]
I would like to work on this issue!

**Comment by luca1iu** [comment]
@caupolicandiaz, I would like to work on this issue!

**Comment by caupolicandiaz** [comment]
@paww81 You've been assigned. Please contact a maintainer if you have any questions. Thanks

**Comment by mamtawardhani** [comment]
Hey @paww81, following up on the status of this entry since it has been more than a month, please let me know the status and when can you submit this PR. 
Also, just to inform you that if you don't respond within 3 days, you will be unfortunately unassigned from this issue.

**Comment by ishg-153** [comment]
@paww81 Since there was no response from your end, I am unassigning you.

**Comment by mamtawardhani** [comment]
@luca1iu are you still interested in taking up this issue? Let me know 😃

**Comment by Raghupanduru** [comment]
i am interested in taking this issue on.

**Comment by mamtawardhani** [comment]
Hey @Raghupanduru You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by Raghupanduru** [comment]
i found it through infosys springboard

**Comment by Sriparno08** [comment]
Hey @mamtawardhani, the user doesn't exist anymore on GitHub. So, I'm assigning this issue to myself.
