### ISSUE TITLE
[Term Entry] Python:NumPy built-in-functions Variance

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4476]
### Reason/inspiration (optional)

"We would like a new term entry on the `built-in-functions` term for [Numpy](https://www.codecademy.com/resources/docs/numpy): Variance. The entry should go in a new file under `docs/content/numpy/concepts/built-in-functions/terms/variance/variance.md`.

The entry should describe the term and how it is used within statistical analysis. Also include: 
- An "Example" section that explains readers how to use the variance statistical function.
- Should contain informations for functions and syntax.
- Should have a python codebyte with working code snippet showcasing this function.
Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by manviii27** [comment]
@SSwiniarski can I work on this?

**Comment by luca1iu** [comment]
Hi @caupolicandiaz, I would like to work on this issue!

**Comment by caupolicandiaz** [comment]
@luca1iu You're assigned! Please message a maintainer if you have any questions.

@manviii27 Normally we assign issues to the first person to make a request. However, since you're already assigned to one of these issues I gave this assignment to the other contributor.
