### ISSUE TITLE
[Term Entry] Python:NumPy built-in-functions Singular Value Decomposition

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4479]
### Reason/inspiration (optional)

"We would like a new term entry on the `built-in-functions` term for [Numpy](https://www.codecademy.com/resources/docs/numpy): Singular Value Decomposition. The entry should go in a new file under `docs/content/numpy/concepts/built-in-functions/terms/svd/svd.md`.

The entry should describe the term and how it is used within statistical analysis. Also include: 
- An "Example" section that explains readers how to use the svd function to find the singular value decomposition of a matrix.
- Should contain informations for functions and syntax.
- Should have a python codebyte with working code snippet showcasing this function.
Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by manviii27** [comment]
@SSwiniarski can I work on this?

**Comment by luca1iu** [comment]
Hi @caupolicandiaz, I would like to work on this issue!

**Comment by caupolicandiaz** [comment]
@manviii27 You've been assigned. Please message a maintainer if you have any questions. Thanks

**Comment by letsbuildanything** [comment]
@manviii27 It's been two weeks. Are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by letsbuildanything** [comment]
@luca1iu Are you still interested to work on this issue?

**Comment by doroodianMostafa** [comment]
Hi there, I would like to work on this issue as my contribution to the Github community for my task on the course "Learn Git and Github".

**Comment by letsbuildanything** [comment]
@doroodianMostafa You’re assigned :tada:  In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.
Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.
