### ISSUE TITLE
[Edit] JavaScript : Arrays

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#448]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Amend:

- how to update elements in an array
- nested arrays

https://www.codecademy.com/resources/docs/javascript/arrays

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by r3vert** [comment]
Can I work on this?

**Comment by Dusch4593** [comment]
@r3vert since you are assigned to a few other open issues, let's assign this one to another contributor.

**Comment by r3vert** [comment]
ok i am fine with that

**Comment by SSwiniarski** [comment]
I'll take this on.
