### ISSUE TITLE
[Term Entry] Python:NumPy built-in-functions Matrix Norm

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4482]
### Reason/inspiration (optional)

"We would like a new term entry on the `built-in-functions` term for [Numpy](https://www.codecademy.com/resources/docs/numpy): Matrix Norm. The entry should go in a new file under `docs/content/numpy/concepts/built-in-functions/terms/norm/norm.md`.

The entry should describe the term and how it is used within statistical analysis. Also include: 
- An "Example" section that explains readers how to use the linalg.norm function to find the norm of a vector or matrix .
- Should contain informations for functions and syntax.
- Should have a python codebyte with working code snippet showcasing this function.
Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Travis-Torres** [comment]
Hello!

I would like to be assigned this issue.

**Comment by leopeq21** [comment]
i would love to be assigned to work on this issue.

**Comment by Travis-Torres** [comment]
@letsbuildanything Thank you! Yes it is my first time, it is part of a portfolio project in Codecademy for learning Git & Github.

**Comment by letsbuildanything** [comment]
Dear @leopeq21, kindly review the remaining unclaimed issues. This particular issue has already been claimed. Thank you!

**Comment by user-name-sathya** [comment]
I would like to be assigned this issue.

**Comment by salar-jafari** [comment]
Hello Codecademy, 

I would like to be assigned this issue. Coming from Codecademy lessons.
