### ISSUE TITLE
[Term Entry] Go: Pointers Go

### ISSUE THREAD

**Issue by Mayer-04** [Codecademy/docs#4488]
### Reason/inspiration (optional)

I would like to contribute by creating an article on pointers in the Go programming language for the Codecademy platform. This resource will aim to enhance understanding of this important topic in Go development. I hope to help the community better grasp the handling of pointers in this language!

I propose adding detailed documentation on `pointers in Go` to the Codecademy documentation to provide knowledge on **efficient memory management** and advanced data manipulation.
Pointers in Go are a crucial and widely used topic in common applications, which is why I want to contribute and add value to this area.

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by VijayVPatil** [comment]
I would like to work on this issue

**Comment by leopeq21** [comment]
I would like to work on this issue as my first portfolio from code academy

**Comment by PardoHub** [comment]
Hi,

I'm ready to work on this issue, please assign! 🤖

**Comment by mamtawardhani** [comment]
@VijayVPatil You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.
Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by Mayer-04** [comment]
I proposed this topic and I would like to work on this issue.

**Comment by ishg-153** [comment]
@Mayer-04 You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?
