### ISSUE TITLE
[Term Entry] HTML Tags : <main>

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#449]
### Entry Type (select all that apply)

New Term for Existing Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by r3vert** [comment]
Can I work on this?

**Comment by Dusch4593** [comment]
Hey @r3vert, hope you're doing well! Wanted to check in and ask if you were still working on a PR for this issue?

**Comment by r3vert** [comment]
I am very sorry but i am currently busy right now

**Comment by Dusch4593** [comment]
No worries!

**Comment by Dusch4593** [comment]
I'll actually take this one on 😃

**Comment by Dusch4593** [comment]
After some research, I think this term entry should go with the ones for the "Semantic HTML" concept (instead of "HTML Tags") since it the `<main>` is used to signify the main content within the `<body>`.
