### ISSUE TITLE
[Edit] SwiftUI: Colors

### ISSUE THREAD

**Issue by AlexandraMasson** [Codecademy/docs#4495]
### Reason/inspiration (optional)

Using and Defining Custom Colors in Swift UI

I would like to add information to the current Colors Doc for Swift UI. It current shows how to use RBG to select colors, however I would like to add to the content under Colors as to how to add your own custom color using HexCode, what 
modifiers to use in addition where to define it under Xcode. 
[Codecademy Docs Colors - CustomColors.pdf](https://github.com/Codecademy/docs/files/14763733/Codecademy.Docs.Colors.-.CustomColors.pdf)

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Dan-Tyas** [comment]
I would be happy to help on this and so i can use this as part of my Portfolio.

**Comment by AlexandraMasson** [comment]
> I would be happy to help on this and so i can use this as part of my Portfolio.

Hi Dan, I submitted the issue as I’m trying to get it assigned as Swift issues don’t come up quite often on Codecademy Docs and trying to cross this task off my Git hub. Happy if you want to add some more to it once I update it.

**Comment by Danielmnm1** [comment]
Hi, I would like to help out on this issue, I am now doing the codecademy swift developer course and as part of the course I need to contribute on Docs. I would be very happy to help.

**Comment by Sriparno08** [comment]
Hey @AlexandraMasson, you're assigned! The edit needs to made to `docs/content/swiftui/concepts/colors/colors.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Hey @Dan-Tyas, @Danielmnm1, and @Jfri3ss, please go to the 'Issues' tab if you want to contribute and claim an issue that interests you. Please note that the issues are assigned on a first-come-first-serve basis.

**Comment by Sriparno08** [comment]
Hey @AlexandraMasson, it's been a week since you were assigned to this issue and you haven't submitted a PR yet. Are you still working on this PR? If you are, please open a PR so that we can review it.

Please note that if there's no response from your side after a week, you'll unfortunately be unassigned from this issue.

**Comment by AlexandraMasson** [comment]
Yes! Working on this today. It’s been a while since I did the GitHub class I needed a refresher as I’m anxious not to screw this up, but I’ll start this today. Alexandra | Masson TechnologiesOn Jun 25, 2024, at 12:01 PM, Sriparno Roy ***@***.***> wrote:﻿
Hey @AlexandraMasson, it's been a week since you were assigned to this issue and you haven't submitted a PR yet. Are you still working on this PR? If you are, please open a PR so that we can review it.
Please note that if there's no response from your side after a week, you'll unfortunately be unassigned from this issue.

**Comment by Sriparno08** [comment]
Great, @AlexandraMasson! 👍
