### ISSUE TITLE
[Term Entry] HTML Tags : <audio>

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#450]
### Entry Type (select all that apply)

New Term for Existing Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by r3vert** [comment]
Can I work on this?

**Comment by Dusch4593** [comment]
Hey @r3vert, hope you're doing well! Wanted to check in and ask if you were still working on a PR for this issue?

**Comment by r3vert** [comment]
I am very sorry but i am currently busy right now

**Comment by Dusch4593** [comment]
No worries!

**Comment by Vivek-Prajapatii** [comment]
May I go ahead with it?

**Comment by ethan-master-coding** [comment]
@Dusch4593 We can close this. [Audio entry](https://www.codecademy.com/resources/docs/html/tags/audio)

**Comment by yangc95** [comment]
Thanks @ethan-master-coding !
