### ISSUE TITLE
[Edit] Subject: The Digital Public Goods Alliance

### ISSUE THREAD

**Issue by laroper** [Codecademy/docs#4500]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

Link to the document that needs editing is: 
https://www.codecademy.com/emodules/emod-continuing-your-open-source-journey/articles/open-source-and-digital-public-goods

The Digital Public Goods Alliance

-In the second paragraph - second sentence - acronym for Digital Public Goods Alliance is DGPA's

-The Acronym should be DPGA's

Browser - Firefox 123.0.1 (64-bit)

![Screenshot 2024-03-29 at 10-51-28 Open Source and Digital Public Goods Codecademy](https://github.com/Codecademy/docs/assets/165287449/b670cf49-a2de-4ad3-bb39-15523bd91525)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by MattPahuta** [comment]
I'd be happy to take this. Thanks.

**Comment by salar-jafari** [comment]
i would like to take this issue and working on this, coming from codecademy lessons

**Comment by V-Ngassa** [comment]
Good day. I'm from the Codecademy Full stack development course and contribution to Docs is one of my last milestones. I would like to work on this issue.

**Comment by user-name-sathya** [comment]
@laroper I would like to take this issue and working on this, came from codecademy lessons.

**Comment by ishg-153** [comment]
Hey @laroper! We appreciate your interest in contributing to Codecademy Docs. The typo that you have mentioned, is not part of Docs so we can't move forward with this issue. Nonetheless, I have intimated this typo to the team to make sure it gets fixed.

If you are still interested in contributing to Docs I suggest you ask to be assigned to one of the [available issues](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+-label%3Aclaimed).

**Comment by amal-george-8895** [comment]
Hi,

I haven't been assigned any issues  till now.

I'm still waiting   for new issues arise.

Thank you.
With Regards,
Amal George
