### ISSUE TITLE
[Entry] HTML Tags : <embed/>

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#451]
### Entry Type (select all that apply)

New Term for Existing Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by r3vert** [comment]
Can I work on this?

**Comment by yangc95** [comment]
> Can I work on this?

Would love to assign you more issues! You can work on your currently assigned issues (including this one) and submit a pull request (PR) for each one through your forked branch, each PR submitted on a different branch. Or if you wish to group some of these issues into one PR, keep a max of 3 added/changed files.

See you on the flip 🏄 (PR side)!
