### ISSUE TITLE
[Edit] JavaScript : Loops

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#452]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

"Looping Through Objects" needed underneath "Looping Through Arrays"

https://www.codecademy.com/resources/docs/javascript/loops

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by KabirCampwala** [comment]
Can you assign this to me?

**Comment by yangc95** [comment]
@KabirCampwala, assigned! Let's get you started with these two issues first. Reach out if you have any questions by tagging me 😌
