### ISSUE TITLE
[Term Entry] Python:Pandas dataframe at

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4520]
### Reason/inspiration (optional)

"We would like a new term entry in the `dataframe` concept for [Pandas](https://www.codecademy.com/resources/docs/pandas): at. The entry should go in a new file under `docs/content/pandas/concepts/dataframe/terms/at/at.md`.

The entry should describe the term and how it is used. Also include: 
- An "Example" section that explains to readers how to use the trace function to find the trace of a square matrix.
- Should contain information for functions and syntax.
- Should have a Python codebyte with a working code snippet showcasing this function.
Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by KarinaNi** [comment]
Can I attempt this?

**Comment by ishg-153** [comment]
@KarinaNi You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by mamtawardhani** [comment]
Hey @KarinaNi following up on the status of this entry since it has been more than a month, please let me know the status and when can you submit this PR. 
Also, just to inform you that if you don't respond within 3 days, you will be unfortunately unassigned from this issue.
Thanks 😄

**Comment by KarinaNi** [comment]
yes ill try to do this within 2 days. I was waiting for the error on the previous issue.

**Comment by ishg-153** [comment]
@KarinaNi It's been a week, if you can't make a PR for this issue, please let us know.

**Comment by KarinaNi** [comment]
Hi, I will do it as soon as possible.

**Comment by mamtawardhani** [comment]
@KarinaNi since your PR of the `.scatter()` has been merged, would you like to take up this entry? Let me know 😃

**Comment by KarinaNi** [comment]
yes please id like to take this @mamtawardhani

**Comment by ishg-153** [comment]
@KarinaNi You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

**Comment by ishg-153** [comment]
@KarinaNi It's been 2 weeks since you were assigned to this issue. Are you still working on the entry?

**Note:** If you don't respond with a PR or an update within a week, this issue will be unassigned from you.

**Comment by KarinaNi** [comment]
Hi, I am working on this PR. sorry for the delay.

**Comment by KarinaNi** [comment]
Hi, you may unassign me im having a difficult time. I apologize

**Comment by aSagCoder** [comment]
Hi, I'd like to give this a try if that's okay!
