### ISSUE TITLE
[Term Entry] Python:Pandas dataframe pop

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4522]
### Reason/inspiration (optional)

"We would like a new term entry in the `dataframe` concept for [Pandas](https://www.codecademy.com/resources/docs/pandas): pop The entry should go in a new file under `docs/content/pandas/concepts/dataframe/terms/pop/pop.md`.

The entry should describe the term and how it is used. Also include: 
- An "Example" section that explains to readers how to use the trace function to find the trace of a square matrix.
- Should contain information for functions and syntax.
- Should have a Python codebyte with a working code snippet showcasing this function.
Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by JenHunnisett** [comment]
Hiya, I'm doing some codecademy courses to try to blow the cobwebs off my coding skills, please can I be assigned this issue?
Thanks!

**Comment by mamtawardhani** [comment]
Hey @JenHunnisett! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by JenHunnisett** [comment]
Thankyou @mamtawardhani, this will be my 2nd contribution, I'm working through some codecademy courses and wanted to get involved in OS contributions to help ym learning progress.
