### ISSUE TITLE
[Term Entry] Python:Pandas built-in-functions unique

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4525]
### Reason/inspiration (optional)

"We would like a new term entry in the `built-in-functions` concept for [Pandas](https://www.codecademy.com/resources/docs/pandas): unique. The entry should go in a new file under `docs/content/pandas/concepts/built-in-functions/terms/unique/unique.md`.

The entry should describe the term and how it is used. Also include: 
- An "Example" section that explains to readers how to use the trace function to find the trace of a square matrix.
- Should contain information for functions and syntax.
- Should have a Python codebyte with a working code snippet showcasing this function.
Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Petit-Nic** [comment]
I'd like to claim this entry as my project for the Github portfolio project.

**Comment by Petit-Nic** [comment]
Bumping the request. I saw some people posting more recently on other issues and already get assigned.

**Comment by Sriparno08** [comment]
Hey @Petit-Nic, you're assigned!

You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) to get help with creating your entry.

**Comment by Sriparno08** [comment]
Hey @Petit-Nic, are you still working on this issue? If you are, please open a PR as soon as possible.

Please note that if there is no response from your side after a week, then you will unfortunately be unassigned from this issue.

**Comment by mamtawardhani** [comment]
@Sriparno08 we've received this PR, however since the issue wasn't linked to the PR, it didn't close. Closing it now. Thank you! 😄

**Comment by Sriparno08** [comment]
Great! Thanks for notifying me, @mamtawardhani! 👍
