### ISSUE TITLE
[Entry] Python Built-in Functions : print()

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#453]
### Entry Type (select all that apply)

New Term for Existing Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by r3vert** [comment]
can I work on this?

**Comment by KabirCampwala** [comment]
I would love to work on this!

**Comment by yangc95** [comment]
@r3vert, thanks for being so diligent! However, I'm going to give this one to @KabirCampwala ☺️

r3vert, definitely finish up your open PR [456](https://github.com/Codecademy/docs/pull/456) so we can assign you some of the issues you want to take on!
