### ISSUE TITLE
[Concept Entry] Postgresql constants

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4533]
### Reason/inspiration (optional)

We would like a new entry on the `Constants` concept under PostgreSQL. The entry should go in a new file under `docs/content/postgresql/concepts/constants/constants.md`.

The entry should include:

- An introductory paragraph that describes the concept
- A ‘Syntax’ section that includes the syntax for the concept (if applicable)
- An ‘Example’ section that shows the concept in use

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by Dan-Tyas** [comment]
Could i be assigned this issue please?

**Comment by Sriparno08** [comment]
Hey @Dan-Tyas, you're assigned!

You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) to get help with creating your entry.

**Comment by Dan-Tyas** [comment]
I've added the required fodler/file and made a change to the tag.md file to include another tag. Please could you review the changes at your earliest convenience. Thanks.
