### ISSUE TITLE
[Concept Entry] Postgresql column-references

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4536]
### Reason/inspiration (optional)

We would like a new entry on the `Column References` concept under PostgreSQL. The entry should go in a new file under `docs/content/postgresql/concepts/column-references/column-references.md`.

The entry should include:

- An introductory paragraph that describes the concept
- A ‘Syntax’ section that includes the syntax for the concept (if applicable)
- An ‘Example’ section that shows the concept in use

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by ogumbaiyke** [comment]
Hi. Please can l contribute and work on this issue. 

This is a requirement for me to complete the Git and Github course.

**Comment by mamtawardhani** [comment]
@ogumbaiyke 
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by ogumbaiyke** [comment]
Greetings.

Okay , I will do that now.

Yes, this is my first contribution to Codecademy Docs. I found out about contributing to Docs through codecademy online course, Git and Github to be precise. one of the requirement include contributing to Docs.
