### ISSUE TITLE
[Concept Entry] Postgresql positional-parameters

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4537]
### Reason/inspiration (optional)

We would like a new entry on the `Positional Parameters` concept under PostgreSQL. The entry should go in a new file under `docs/content/postgresql/concepts/positional-parameters/positional-parameters.md`.

The entry should include:

- An introductory paragraph that describes the concept
- A ‘Syntax’ section that includes the syntax for the concept (if applicable)
- An ‘Example’ section that shows the concept in use

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by amarachi-nwokocha** [comment]
Hello, can I work on this ? 

If yes, please point me to docs/content/postgresql/concepts/positional-parameters i cant seem to find it

**Comment by amarachi-nwokocha** [comment]
Hello, please merge my pull request here at #4544 
Thank you!
