### ISSUE TITLE
[Edit] Java: Data Types

### ISSUE THREAD

**Issue by Artaraba** [Codecademy/docs#4548]
### Actual Behavior

When trying to determine what the data type "byte" was, I followed a specific path (Java > Manipulating Variables > Introduction >Data Types) and on the list at this location all data types are listed however you are not able to click on the code to see the definitions. (A page about the different data types < specific data type). I apologize if this is confusing or not a good report, this is the first time for contacting anyone in a development environment.

### Expected Behavior

At the location above I was expecting to see a defined list of terms. The way the terms are listed is fine as far as I am concerned. I believe that it would be more helpful to newer students to computer science as a whole (like me). 

### On what browser(s) are you seeing the problem?

Microsoft Edge

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Johnnie-kay** [comment]
Hello @Artaraba , can you describe this issue again. I might know how to solve and close it. Thankyou.

**Comment by Sriparno08** [comment]
Hey @Johnnie-kay, the suggestion is to define each data type in the bulleted list in the [`Data Types`](https://www.codecademy.com/resources/docs/javascript/data-types) concept entry under Java. For this, you need to go to the `docs/content/java/concepts/data-types/data-types.md` file and add definitions to each of the data types.

You can reference the `Primitive Data Types` section in the [`Data Types`](https://www.codecademy.com/resources/docs/javascript/data-types) concept entry under JavaScript for inspiration.

So, do you want to work on this issue?

**Comment by Johnnie-kay** [comment]
@Sriparno08 I understand now, Yes i would want to work on it. Thanks

**Comment by Sriparno08** [comment]
Hey @Johnnie-kay, you're assigned!

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.
