### ISSUE TITLE
[Concept Entry] Python Plotly

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4555]
### Reason/inspiration (optional)

We would like a new entry on the Plotly library under Python. The entry should go in a new file under `docs/content/plotly/plotly.md`

The entry should include:

- An introductory paragraph that provides an overview of the Plotly library and its capabilities within Python.
- An ## Installation block
- A short description of the plotly modules

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by joseandersonramos** [comment]
Hello @codecademy-docs, I am interested in this issue.

**Comment by letsbuildanything** [comment]
@joseandersonramos You’re assigned :tada:  In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.
Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by mamtawardhani** [comment]
Hey @joseandersonramos!
Please recheck the path once, it has been updated. Thanks!

**Comment by joseandersonramos** [comment]
> @joseandersonramos You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval. Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

Thank you very much!. I knew about contributing to Docs in the Git and GitHub course!

**Comment by joseandersonramos** [comment]
> Hey @joseandersonramos! Please recheck the path once, it has been updated. Thanks!

Received, thanks!
