### ISSUE TITLE
[Term Entry] Python Plotly .scatter()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4558]
### Reason/inspiration (optional)

We would like a new term entry in the `Data Visualization` concept for Plotly: `.scatter()`. The entry should go in a new file under `docs/content/plotly/concepts/express/terms/scatter/scatter.md`

The entry should describe the term and how it is used. Also include:

- An introductory paragraph that describes the concept
- A 'Syntax' section that includes the syntax for the concept (if applicable)
- An 'Example' section that shows the concept in use

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by KarinaNi** [comment]
the plotly folder does not exist in https://github.com/Codecademy/docs/tree/main/content could you please update the correct location or let me know what is going wrong, and once that is done, I would like to be assigned this issue.

**Comment by mamtawardhani** [comment]
Hey @KarinaNi!

You can go ahead and create the directory named "plotly" as per the given path: `docs/content/plotly/concepts/express/terms/scatter/scatter.md`

**Comment by KarinaNi** [comment]
Its my second contribution to Codecademy Docs I think. I have been an avid Codecademy user over the years, loved how they taught concepts with hands on immediate exercises. I did a course on Github on codecademy they asked me to do contributions here, I did two. I have recently been finding some open source to contribute to, so I came here to see if there are any issues I can help with. @mamtawardhani

**Comment by mamtawardhani** [comment]
@KarinaNi That's good to hear!
You can take up this issue!

**Comment by KarinaNi** [comment]
Okay so there are some tests that are failing in this PR.  @mamtawardhani
```
format:verify
lint:md
I ran 
yarn test result: Tests: 4849 passed, 4849 total
yarn format: all: Ran successfully
yarn format:verify : Ran successfully
yarn lint: error message as below
```

**The error message:**


```
Oops! Something went wrong! :(

ESLint: 8.57.0

ESLint couldn't find the plugin "eslint-plugin-import".

(The package "eslint-plugin-import" was not found when loaded as a Node modulecs".)

It's likely that the plugin isn't installed correctly. Try reinstalling by run

    npm install eslint-plugin-import@latest --save-dev

The plugin "eslint-plugin-import" was referenced from the config file in ".esl

error Command failed with exit code 2.                                    rg/c
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.                                    s co
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.                                                                s co

```

How do I debug this? I went to https://www.npmjs.com/package/@codecademy/eslint-config?activeTab=versions the latest version is 8.0.0 how to resolve this issue, any steps would be highly appreciated

**Comment by KarinaNi** [comment]
Okay so there are some tests that are failing in this PR.  @mamtawardhani
```
format:verify
lint:md
I ran 
yarn test result: Tests: 4849 passed, 4849 total
yarn format: all: Ran successfully
yarn format:verify : Ran successfully
yarn lint: error message as below
```

**The error message:**


```
Oops! Something went wrong! :(

ESLint: 8.57.0

ESLint couldn't find the plugin "eslint-plugin-import".

(The package "eslint-plugin-import" was not found when loaded as a Node modulecs".)

It's likely that the plugin isn't installed correctly. Try reinstalling by run

    npm install eslint-plugin-import@latest --save-dev

The plugin "eslint-plugin-import" was referenced from the config file in ".esl

error Command failed with exit code 2.                                    rg/c
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.                                    s co
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.                                                                s co

```

How do I debug this? I went to https://www.npmjs.com/package/@codecademy/eslint-config?activeTab=versions the latest version is 8.0.0 how to resolve this issue, any steps would be highly appreciated

**Comment by mamtawardhani** [comment]
Hey @KarinaNi! It looks like you're encountering an ESLint error related to the `eslint-plugin-import` plugin not being found or installed correctly. Here's how you can fix it:

1. Open your terminal or command prompt.
2. Navigate to your project directory where ESLint is configured to run.
3. Run the following command to reinstall the "eslint-plugin-import" plugin:
npm install eslint-plugin-import@latest --save-dev

This command will install the latest version of the "eslint-plugin-import" plugin as a development dependency in your project.

4. After the installation is complete, try running ESLint again to see if the issue has been resolved:
eslint . --ext .js

Replace .js with the file extension(s) you want ESLint to check (e.g., .js, .jsx, .ts, .tsx).

If you're using Yarn instead of npm, you can use the following command to reinstall the plugin:
yarn add eslint-plugin-import@latest --dev

After reinstalling the plugin, ESLint should be able to find and use the "eslint-plugin-import" plugin without any issues.

**Comment by KarinaNi** [comment]
Hi, I already ran the installation command yesterday and i got the following error 

```
npm ERR! code ERESOLVE                                          g
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @codecademy/eslint-config@3.1.0
npm ERR! Found: eslint@8.57.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
npm ERR!   node_modules/@eslint-community/eslint-utils
npm ERR!     @eslint-community/eslint-utils@"^4.2.0" from eslint@8.57.0
npm ERR!   peer eslint@"*" from @typescript-eslint/experimental-utils@4.4.1
npm ERR!   node_modules/@typescript-eslint/experimental-utils
npm ERR!     @typescript-eslint/experimental-utils@"4.4.1" from @typescript-eslint/eslint-plugin@4.4.1
npm ERR!     node_modules/@codecademy/eslint-config/node_modules/@typescript-eslint/eslint-plugin
npm ERR!       @typescript-eslint/eslint-plugin@"4.4.1" from @codecademy/eslint-config@3.1.0
npm ERR!       node_modules/@codecademy/eslint-config
npm ERR!         dev @codecademy/eslint-config@"^3.1.0" from the root project
npm ERR!   5 more (eslint-config-prettier, eslint-plugin-react, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^6.5.1" from @codecademy/eslint-config@3.1.0npm ERR! node_modules/@codecademy/eslint-config
npm ERR!   dev @codecademy/eslint-config@"^3.1.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: eslint@6.8.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@"^6.5.1" from @codecademy/eslint-config@3.1.0
npm ERR!   node_modules/@codecademy/eslint-config
npm ERR!     dev @codecademy/eslint-config@"^3.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
```

**Comment by KarinaNi** [comment]
Reinstalled yarn, upgraded yarn, added eslint through yarn, and yarn lint does not throw any errors in the command prompt. But there are the same errors that i posted. Any idea what I am missing?

**Comment by mamtawardhani** [comment]
@dakshdeepHERE @Sriparno08 Could you help solve the above issue, please?

**Comment by mamtawardhani** [comment]
Hey @KarinaNi! Are you still working on this? Since it has been a month now, and this needs to be closed as soon as possible. Please do let me know 😃

**Comment by KarinaNi** [comment]
Hi! @mamtawardhani  Please assist me. I have already submitted a pull request last month. I already pushed al the changes. Could you tell me where did I get stuck? 
![image](https://github.com/Codecademy/docs/assets/32227493/629280cd-5005-43db-be47-95e505e67c3d)

**Comment by mamtawardhani** [comment]
Checking this @KarinaNi

**Comment by KarinaNi** [comment]
Give me an hour I'll reply sorry about the delay

**Comment by KarinaNi** [comment]
so my steps were i had already forked the repo because i had contributed before, i cloned it made changes committed, and pushed it. And created a pull request filled all forms and I believe i was done. Then there were some checks that weren't working then somehow it ended up passing and yes that was my steps sorry for the delay @dakshdeepHERE

**Comment by mamtawardhani** [comment]
@dakshdeepHERE could you check this?

**Comment by KarinaNi** [comment]
I plan on contributing to the docs again, so before i work on the next issue, could you please tell me any steps i should change so this issue doesn't happen?

**Comment by mamtawardhani** [comment]
Hey @KarinaNi, I guess you have created the PR directly from the main docs, instead of the forked one on your side, could you please check that and raise a PR for this as soon as possible?

**Comment by KarinaNi** [comment]
okay I try to create a PR from my side right? the forked one. i will try to do it.
