### ISSUE TITLE
[Term Entry] Python Plotly .pie()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4559]
### Reason/inspiration (optional)

We would like a new term entry in the `Data Visualization` concept for Plotly: `.pie()`. The entry should go in a new file under `docs/content/plotly/concepts/express/terms/pie/pie.md`

The entry should describe the term and how it is used. Also include:

- An introductory paragraph that describes the concept
- A 'Syntax' section that includes the syntax for the concept (if applicable)
- An 'Example' section that shows the concept in use, include an output image as well.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by mamtawardhani** [comment]
Hey @rui-sa!
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by mamtawardhani** [comment]
Hey @rui-sa! Are you still working on this? Since it has been a month now, and this needs to be closed as soon as possible. Please do let me know 😃

**Comment by Getrealtoday** [comment]
Hi could I have a crack at this? This will be my first issue. It will forms part of an off platform project for me thank you.

**Comment by mamtawardhani** [comment]
Hey @Getrealtoday, sure thing you can take this up! 😄 
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by Getrealtoday** [comment]
Hi @mamtawardhani yes this will be my first contribution. I found about contributing to Docs via a Git/GitHub off Platform project

**Comment by Getrealtoday** [comment]
Hi @mamtawardhani I have some personal issue that's occupying me and would need a lot more time. Please re assign to someone thank you.

**Comment by ishg-153** [comment]
@Getrealtoday You are being unassigned as requested.

**Comment by jmarsden8** [comment]
@mamtawardhani I would like to work on this issue as part of an assignment. This is my first contribution & I found out about Docs through the Codecademy course. Thank you.

**Comment by mamtawardhani** [comment]
Hey @jmarsden8 Hey @negarvahid You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

**Comment by Sriparno08** [comment]
Hey @jmarsden8, are you still working on this issue?

Please note that if there's no response from your side in a week, then you will be unassigned from this issue unfortunately.

**Comment by mamtawardhani** [comment]
Hey @jmarsden8 the entry actually exists, but the author has added the image in a wrong folder and is unresponsive since a couple of weeks. Let me know how should we proceed?

**Comment by Sriparno08** [comment]
Hey @mamtawardhani, since the author has been unresponsive for over a week, you can go ahead and make the changes yourself.
