### ISSUE TITLE
[Term Entry] Python Plotly .box()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4560]
### Reason/inspiration (optional)

We would like a new term entry in the `Data Visualization` concept for Plotly: `.box()`. The entry should go in a new file under `docs/content/plotly/concepts/express/terms/box/box.md`

The entry should describe the term and how it is used. Also include:

- An introductory paragraph that describes the concept
- A 'Syntax' section that includes the syntax for the concept (if applicable)
- An 'Example' section that shows the concept in use

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by scottfinamore** [comment]
May I be assigned this issue please?

Thank you

**Comment by mamtawardhani** [comment]
Hey @scottfinamore, you're assigned!

You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) to get help with creating your entry.

**Comment by mamtawardhani** [comment]
Hey @scottfinamore! Please review the path once, it has been updated. Thanks!

**Comment by mamtawardhani** [comment]
@scottfinamore are you still working on this? Since it has been a month now, and this needs to be closed as soon as possible. Please do let me know 😃

**Comment by scottfinamore** [comment]
Im in the middle of moving and this issue is a bit out of my league at the moment. Thank you for assigning it to me but perhaps it should go to someone with the bandwidth to handle this right now. Thank you.

**Comment by mamtawardhani** [comment]
Alright, no worries @scottfinamore.

**Comment by minadas482** [comment]
Hello @mamtawardhani, could you please assign me this issue?
I found Codecademy Docs while taking the Codecademy learn git and github course.

**Comment by mamtawardhani** [comment]
Hey, @minadas482, sure you can take up this issue 😃 

You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) to get help with creating your entry.

**Comment by minadas482** [comment]
Done @mamtawardhani
Please review the Pull Request #4781

**Comment by mamtawardhani** [comment]
> Done @mamtawardhani Please review the Pull Request #4781

Will do it, tthanks for the submission! 😃
