### ISSUE TITLE
[Term Entry] Python Plotly .violin()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4561]
### Reason/inspiration (optional)

We would like a new term entry in the `Data Visualization` concept for Plotly: `.violin()`. The entry should go in a new file under `docs/content/plotly/concepts/express/terms/violin/violin.md`

The entry should describe the term and how it is used. Also include:

- An introductory paragraph that describes the concept
- A 'Syntax' section that includes the syntax for the concept (if applicable)
- An 'Example' section that shows the concept in use

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by saqlainmahmood98** [comment]
Hi can I be assigned to this issue, I need to complete this for my course with Codecademy.

**Comment by mamtawardhani** [comment]
Hey @saqlainmahmood98! 
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by saqlainmahmood98** [comment]
Yes this will be my first contribution, I found out about contributing to Docs through the git and github course with Codecademy.
