### ISSUE TITLE
[Term Entry] Python Plotly .histogram()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4562]
### Reason/inspiration (optional)

We would like a new term entry in the `Data Visualization` concept for Plotly: `.histogram()`. The entry should go in a new file under `docs/content/plotly/concepts/express/terms/histogram/histogram.md`

The entry should describe the term and how it is used. Also include:

- An introductory paragraph that describes the concept
- A 'Syntax' section that includes the syntax for the concept (if applicable)
- An 'Example' section that shows the concept in use

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by meli-imelda** [comment]
Hello @codecademy-docs, I am interested in this issue

**Comment by mamtawardhani** [comment]
Hey @meli-imelda!
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.
Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by mamtawardhani** [comment]
Hey @meli-imelda! Please review the path once, it has been updated. Thanks!

**Comment by mamtawardhani** [comment]
@meli-imelda are you still working on this? Since it has been a month now.

**Comment by mamtawardhani** [comment]
Due to the inactivity of the contributor, I am unassigning this issue.

**Comment by ngetachew14** [comment]
Hello! @codecademy-docs 
I would like to take this!

**Comment by mamtawardhani** [comment]
hey @ngetachew14! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by mamtawardhani** [comment]
@ngetachew14 any updates?

**Comment by ishg-153** [comment]
@ngetachew14 you are being unassigned due to lack of activity.

**Comment by romanwilk** [comment]
Hello @codecademy-docs, I am interested to take this issue on. First time contributor, this is  a part  of my github learning process.

**Comment by mamtawardhani** [comment]
Hey @romanwilk You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by romanwilk** [comment]
Hey @mamtawardhani ! Thanks for assignemend. I found out about Codecadamey Docs from my  Codecademy Computer Science learnig path. And abour Codecademy just from www, looking for platform to study programming.
