### ISSUE TITLE
[Term Entry] Python Plotly .create_gantt()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4563]
### Reason/inspiration (optional)

We would like a new term entry in the `Data Visualization` concept for Plotly: `.create_gantt()`. The entry should go in a new file under `docs/content/plotly/concepts/figure-factory/terms/create-gantt/create-gantt.md`

The entry should describe the term and how it is used. Also include:

- An introductory paragraph that describes the concept
- A 'Syntax' section that includes the syntax for the concept (if applicable)
- An 'Example' section that shows the concept in use

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by rgo444** [comment]
Hi! @codecademy-docs, I would like to take this entry :raising_hand:

**Comment by mamtawardhani** [comment]
Hey @rgo444! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the Contribution Guide. After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by rgo444** [comment]
Thanks @mamtawardhani ! This is my first contribution to CD. As part of the Learn Git & GitHub course I was required to contribute to one doc :+1:

I'll take a look at the Contribution Guide and get going on my doc. Thank you!

**Comment by rgo444** [comment]
Hi @mamtawardhani! I have corrected all the issues except for the create-gantt.md file. I've tried a lot of things and looked up online but I can seem to find what the issue is. The file is not present on my local repo branch, but when I type in  "git push" command it suddenly comes back. Any recommendations on what I could do here?
