### ISSUE TITLE
[Term Entry] Python Plotly .heatmap()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4564]
### Reason/inspiration (optional)

We would like a new term entry in the `Data Visualization` concept for Plotly: `.heatmap()`. The entry should go in a new file under `docs/content/plotly/concepts/graph-objects/terms/heatmap/heatmap.md`

The entry should describe the term and how it is used. Also include:

- An introductory paragraph that describes the concept
- A 'Syntax' section that includes the syntax for the concept (if applicable)
- An 'Example' section that shows the concept in use

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by meli-imelda** [comment]
Hello @codecademy-docs, I am interested in this issue

**Comment by letsbuildanything** [comment]
@meli-imelda You’re assigned :tada:  In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.
Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by mamtawardhani** [comment]
Hey @meli-imelda! Please review the path once, it has been updated. Thanks!

**Comment by mamtawardhani** [comment]
Unassigning @meli-imelda due to long-term inactivity.

**Comment by evuntsova** [comment]
Hi @codecademy-docs , I am interested in taking this issue. Could you please assign it to me? Thanks

**Comment by mamtawardhani** [comment]
Hey @evuntsova! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by evuntsova** [comment]
Thank you! I'm excited to work on this issue. I'm currently pursuing the Git and GitHub certification, so this is a great opportunity for me.

I found out about contributing to Docs through the course materials and community forums.

Looking forward to contributing!

Cheers!

**Comment by mamtawardhani** [comment]
@evuntsova good to hear that, waiting for your entry! 😄

**Comment by ishg-153** [comment]
@evuntsova It's been a month since you were assigned to this issue. Are you still working on the entry?

**Note:** If you don't respond with an update within 2 days, this issue will be unassigned from you.

**Comment by ashdawn04** [comment]
If available, I would like to work on this issue.

**Comment by ishg-153** [comment]
@evuntsova You are being unassigned due to lack of activity.

**Comment by georgeholt1** [comment]
Hi @codecademy-docs, could I be assigned this issue please?

**Comment by mamtawardhani** [comment]
Hey @georgeholt1 You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by georgeholt1** [comment]
This is my first contribution, yes. I found it through the "Learn Git & GitHub" course.
