### ISSUE TITLE
[Term Entry] Dart Type Conversion .toString()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4565]
### Reason/inspiration (optional)

We would like a new term entry under Dart for the Dart Type Conversion `.toString()` method.
Provide the entry in a markdown file under `docs/content/dart/concepts/type-conversion/terms/toString/toString.md`

The entry should
- Have an introductory paragraph about what the method is and does.
- A syntax section with a pseudo code block with an explanation of it.
- An example showing the method in use.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Vizhou19** [comment]
Hi, I want to help on this issue as I am learning Git and GitHub, please.

**Comment by mamtawardhani** [comment]
Hey @Vizhou19! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by Vizhou19** [comment]
I found out Contribution to Docs because I was learning how to use Git and GitHub on Codecademy
