### ISSUE TITLE
[Term Entry] Dart Type Conversion .toStringAsFixed()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4568]
### Reason/inspiration (optional)

We would like a new term entry under Dart for the Dart Type Conversion `.toStringAsFixed()` method.
Provide the entry in a markdown file under `docs/content/dart/concepts/type-conversion/terms/toStringAsFixed/toStringAsFixed.md`

The entry should
- Have an introductory paragraph about what the method is and does.
- A syntax section with a pseudo code block with an explanation of it.
- An example showing the method in use.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by alvaro347** [comment]
Hello, I am interested in taking this term entry issue.

**Comment by ishg-153** [comment]
@alvaro347 You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by alvaro347** [comment]
Hello @ishg-153 thank you! I'm already working on it.

I was going through the "Web Development" skill path from CodeCademy, and this is one of the portfolio projects.
