### ISSUE TITLE
[Term Entry] Dart Type Conversion .toDouble()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4569]
### Reason/inspiration (optional)

We would like a new term entry under Dart for the Dart Type Conversion `.toDouble()` method.
Provide the entry in a markdown file under `docs/content/dart/concepts/type-conversion/terms/toDouble/toDouble.md`

The entry should
- Have an introductory paragraph about what the method is and does.
- A syntax section with a pseudo code block with an explanation of it.
- An example showing the method in use.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by alvaro347** [comment]
Hello! I'm interested in taking this term entry.

**Comment by mamtawardhani** [comment]
Hey @alvaro347! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by alvaro347** [comment]
Thank you! I'm currently working on it following the guides from the link. 

Yes, it's my first contribution. I was going through the "Web Development" skill path from CodeCademy, and this is one of the portfolio projects.
