### ISSUE TITLE
[Edit] React : State

### ISSUE THREAD

**Issue by r3vert** [Codecademy/docs#457]
### Type of Edit

Add new content (definitions, codeblocks, etc.)

### Description

Now that hooks have been the default way of using state since 2019 I propose that we add a part showing how use state with `useState()` since react beginners will be using it.

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by r3vert** [comment]
I would work on this

**Comment by Dusch4593** [comment]
@r3vert Since you are already assigned to a few other open issues, let's assign this one to another contributor 😄

**Comment by r3vert** [comment]
I am fine with that

**Comment by yangc95** [comment]
@r3vert @Dusch4593 I'm thinking about linking the [hooks](https://www.codecademy.com/resources/docs/react/hooks) entry to the current [React state](https://www.codecademy.com/resources/docs/react/state) entry. Class components are still used (not obsolete).

Down the line, I do think it would be helpful for the hooks entry to have a terms table with all the available hooks.

**Comment by Dusch4593** [comment]
> @r3vert @Dusch4593 I'm thinking about linking the [hooks](https://www.codecademy.com/resources/docs/react/hooks) entry to the current [React state](https://www.codecademy.com/resources/docs/react/state) entry. Class components are still used (not obsolete), so for the most part I'm going to leave the state entry as is.
> 
> Down the line, I do think it would be helpful for the hooks entry to have a terms table with all the available hooks.

I love the idea for a Hooks table! 🎉 Also, I'm wondering if we should mention [property initializers](https://reactjs.org/blog/2015/01/27/react-v0.13.0-beta-1.html#es7-property-initializers) in the next edit for this entry? I personally love this syntax b/c you don't have to use `super()` or `constructor()`; ES7 intuitively does that in the background, I think. Also, method binding is handled (pun intended) a bit differently.
