### ISSUE TITLE
[Term Entry] Dart Type Conversion .toInt()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4570]
### Reason/inspiration (optional)

We would like a new term entry under Dart for the Dart Type Conversion `.toInt()` method.
Provide the entry in a markdown file under `docs/content/dart/concepts/type-conversion/terms/toInt/toInt.md`

The entry should
- Have an introductory paragraph about what the method is and does.
- A syntax section with a pseudo code block with an explanation of it.
- An example showing the method in use.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by VivianVanilla** [comment]
Hi I would like to work on this! Currently I'm trying got complete the *Learn Git & Github* course, and the portfolio assignment calls for me to work on a issue!

**Comment by Sriparno08** [comment]
Hey @VivianVanilla, you're assigned!

You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) to get help with creating your entry.
