### ISSUE TITLE
[Term Entry] Dart Type Conversion .parse()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4571]
### Reason/inspiration (optional)

We would like a new term entry under Dart for the Dart Type Conversion `.parse()` method.
Provide the entry in a markdown file under `docs/content/dart/concepts/type-conversion/terms/parse/parse.md`

The entry should
- Have an introductory paragraph about what the method is and does.
- A syntax section with a pseudo code block with an explanation of it.
- An example showing the method in use.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Mhidayah19** [comment]
Hi i am interested in taking this issue on. I found out about Docs through the course

**Comment by Mhidayah19** [comment]
Yes this is my first contribution to Codecademy Docs. I found out through the iOS developer course in Codecademy
