### ISSUE TITLE
[Concept Entry] Postgresql subscripts

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4587]
### Reason/inspiration (optional)

We would like a new entry on the `Subscripts` concept under PostgreSQL. The entry should go in a new file under `docs/content/postgresql/concepts/subscripts/subscripts.md`.

The entry should include:

- An introductory paragraph that describes the concept
- A �Syntax� section that includes the syntax for the concept (if applicable)
- An �Example� section that shows the concept in use

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by ishg-153** [comment]
Hey @Ayush9026, You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by mamtawardhani** [comment]
@Ayush9026, following up on the status of this entry since it has been more than a month, please let me know the status and when can you submit this PR. Thanks 😄

**Comment by ishg-153** [comment]
@Ayush9026 Since there was no response from your end, I am unassigning you.

**Comment by nbarnhouse** [comment]
Hi @codecademy-docs I would like to work on this.

**Comment by ishg-153** [comment]
Hey @nbarnhouse You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.
