### ISSUE TITLE
[Concept Entry] Postgresql functions

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4589]
### Reason/inspiration (optional)

We would like a new entry on the `Functions` concept under PostgreSQL. The entry should go in a new file under `docs/content/postgresql/concepts/functions/functions.md`.

The entry should include:

- An introductory paragraph that describes the concept
- A �Syntax� section that includes the syntax for the concept (if applicable)
- An �Example� section that shows the concept in use

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Ayush9026** [comment]
Thanks,  @mamtawardhani , for assigning the issue and sharing the contribution guide. I've reviewed it. Yes, this is my first contribution to Codecademy Docs. I'm an open-source contributor to projects like Kubernetes and others.  I am interested in one role at Codecademy.

**Comment by Ayush9026** [comment]
Thanks, @mamtawardhani , for assigning the issue and sharing the contribution guide. I've reviewed it. Yes, this is my first contribution to Codecademy Docs. I'm an open-source contributor to projects like Kubernetes and others.

**Comment by mamtawardhani** [comment]
@Ayush9026, following up on the status of this entry since it has been two weeks now, please let me know the status and when can you submit this PR. Thanks 😄

**Comment by hakdo99** [comment]
Hi @mamtawardhani , I'd like to work on this issue!

**Comment by mamtawardhani** [comment]
Hey @hakdo99 You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by Sriparno08** [comment]
Hey @hakdo99, are you still working on this issue?

Note: If you don't respond in a week, you will be unassigned from this issue unfortunately.

**Comment by hakdo99** [comment]
Hi! Sorry for my late response. I'll complete it the issue this week.

**Comment by Sriparno08** [comment]
Okay, @hakdo99. 👍
