### ISSUE TITLE
[Concept Entry] TensorFlow math

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4594]
### Reason/inspiration (optional)

We would like a new entry on the `Math` concept under TensorFlow. The entry should go in a new file under `docs/content/tensorflow/concepts/math/math.md`.

The entry should include:

- An introductory paragraph that describes the concept
- Explain the math module in tensorflow

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Himasnhu-AT** [comment]
hi @codecademy-docs , 
I would love to work on this issue.

**Comment by mamtawardhani** [comment]
Hey @Himasnhu-AT!
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by mamtawardhani** [comment]
Unassigning the issue due to inactivity of @Himasnhu-AT

**Comment by heeirthan01** [comment]
Hi, would you be able to assign this issue to me please?

**Comment by mamtawardhani** [comment]
Hey, @heeirthan01, sure you can take up this issue. Please refer to the Contribution Guide shared in the above comment. Thank you! 😃

**Comment by ishg-153** [comment]
@heeirthan01 It's been 3 weeks since you were assigned to this issue. Are you still working on the entry?

**Note:** If you don't respond with a PR or an update within a week, this issue will be unassigned from you.

**Comment by Sriparno08** [comment]
Hey @heeirthan01, you are unassigned due to inactivity.

**Comment by Brodes4JC** [comment]
Hello! I was interested in potentially taking up this issue, but wanted to clarify before I did: is this issue aimed at explaining the tf.math module for using tensorflow with python (the public API for tf._api.v2.math namespace)?

**Comment by CodeZeus-dev** [comment]
Hi @codecademy-docs and @mamtawardhani ! I've noticed a period of inactivity on this issue, and I would be interested in being assigned the current issue. Thank you!

**Comment by mamtawardhani** [comment]
Hey @CodeZeus-dev Sure, you can take this up!
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by mamtawardhani** [comment]
Hey @Brodes4JC if you are still interested in picking an issue, please refer to the [open issues](https://github.com/Codecademy/docs/issues) and let us know if anything interests you. Thank you! 😃

**Comment by CodeZeus-dev** [comment]
> Hey @CodeZeus-dev Sure, you can take this up! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.
> 
> Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

Thank you very much @mamtawardhani ! I found out about Docs through a Github collection, called choosing-projects.

**Comment by Sriparno08** [comment]
Unassigning the author due to inactivity.

**Comment by arisdelacruz** [comment]
Can I take this one?

**Comment by mamtawardhani** [comment]
Hey @arisdelacruz You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

**Comment by arisdelacruz** [comment]
Yes, I am.

**Comment by arisdelacruz** [comment]
@mamtawardhani just wondering

Are examples needed or recommended for each and every "sub-concepts" to be presented? I remember my numpy tensor ops entry to include only explanations.

thanks
