### ISSUE TITLE
[Concept Entry] TensorFlow neuralnetwork

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4595]
### Reason/inspiration (optional)

We would like a new entry on the `NeuralNetwork` concept under TensorFlow. The entry should go in a new file under `docs/content/tensorflow/concepts/nn/nn.md`.

The entry should include:

- An introductory paragraph that describes the concept
- Explain the nn module in tensorflow

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by mihneatatu** [comment]
Hello, interested in taking on this issue.

**Comment by letsbuildanything** [comment]
@mihneatatu You’re assigned :tada:  In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.
Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by mamtawardhani** [comment]
Unassigning the issue due to the inactivity of the contributor.

**Comment by vivitt** [comment]
Hello, I would like to work on this issue if help is needed. Thank you!

**Comment by rashi95** [comment]
Hey @vivitt ! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by vivitt** [comment]
Hi @rashi95, thanks for assigning me the issue. I submitted [a PR](https://github.com/Codecademy/docs/pull/4812) and look forward comments on it.
It actually is my first contribution so I tell you that I found about contributing in [this blogpost](https://www.freecodecamp.org/news/improve-tech-writing-skills-by-contributing-to-open-source/).
