### ISSUE TITLE
[Term Entry] Python sets .add()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4611]
### Reason/inspiration (optional)

We would like a new term entry on the '.add()' method for Sets in Python. The entry should go in a new file under `docs/content/python/concepts/sets/terms/add/add.md`

The entry should include the following:

- A description of the function
- A ## Syntax section that includes the syntax of the function and its details
- An ## Example section that includes a ```python ``` codeblock and ```shell ``` that shows the example output.
- A ## Codebyte Example that includes a ```codebyte/python ``` runnable codeblock

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by alimalim77** [comment]
Hello, I have five contributions for Codecademy Docs as of now and being coding in Python for over three years, I am comfortable contributing to this. Please assign if possible. 

Regards
Alim

**Comment by scottfinamore** [comment]
Hello, I just lost an issue I was working on and was eager to complete my web development path soon. This seems like something not too complicated I could handle and gain some experience if I may be assigned it. All the others seem out of my league at this time. Thank you for the consideration.

**Comment by letsbuildanything** [comment]
@scottfinamore You’re assigned :tada:  In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.
Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by letsbuildanything** [comment]
@alimalim77 You're currently assigned to another open issue.

**Comment by mamtawardhani** [comment]
Hey @scottfinamore! Are you still working on this? Since it has been a week, could you please update me on the status of this entry? 😃

**Comment by J0-0L26** [comment]
@mamtawardhani I would like to work on this. I am aware that this is claimed but should it be put back up I would like to be considered. I am currently working on the "Learn Git & GitHub" course, and this is all very new to me. Thank you.

**Comment by scottfinamore** [comment]
Im in the middle of moving and this issue is a bit out of my league at the moment. Thank you for assigning it to me but perhaps it should go to someone with the bandwidth to handle this right now. Thank you.

**Comment by mamtawardhani** [comment]
Alright, no worries @scottfinamore, feel free to contribute to an issue in future at your convenience. 😄

**Comment by mamtawardhani** [comment]
@J0-0L26 You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.
Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by J0-0L26** [comment]
@mamtawardhani Yes this is my first contribution. I found out about it as it is my final project in the "Git and GitHub" course on Codecademy.
