### ISSUE TITLE
[Term Entry] Python sets .issuperset()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4614]
### Reason/inspiration (optional)

We would like a new term entry on the '.issuperset()' method for Sets in Python. The entry should go in a new file under `docs/content/python/concepts/sets/terms/issuperset/issuperset.md`

The entry should include the following:

- A description of the function
- A ## Syntax section that includes the syntax of the function and its details
- An ## Example section that includes a ```python ``` codeblock and ```shell ``` that shows the example output.
- A ## Codebyte Example that includes a ```codebyte/python ``` runnable codeblock

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by ULTRAPAIN** [comment]
Hi I am Excited To work On this Issue !

**Comment by mamtawardhani** [comment]
Hey @ULTRAPAIN! I noticed that one of your pull requests is currently under review. Once it's merged, a new issue can be assigned to you afterward. Thank you!

**Comment by ULTRAPAIN** [comment]
Hi I am Excited To work On this Issue !
