### ISSUE TITLE
[Term Entry] Python sets .difference_update()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4617]
### Reason/inspiration (optional)

We would like a new term entry on the '.difference_update()' method for Sets in Python. The entry should go in a new file under `docs/content/python/concepts/sets/terms/difference-update/difference-update.md`

The entry should include the following:

- A description of the function
- A ## Syntax section that includes the syntax of the function and its details
- An ## Example section that includes a ```python ``` codeblock and ```shell ``` that shows the example output.
- A ## Codebyte Example that includes a ```codebyte/python ``` runnable codeblock

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by ULTRAPAIN** [comment]
Hi I will like to work On this Issue

**Comment by mamtawardhani** [comment]
Hey @ULTRAPAIN! I noticed that one of your pull requests is currently under review. Once it's merged, a new issue can be assigned to you afterward. Thank you!

**Comment by mamtawardhani** [comment]
Hey @JenHunnisett! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by JenHunnisett** [comment]
Hi @mamtawardhani 👋 thanks for assigning this to me. Yes its my first contribution, I am doing some codecademy courses and asked on the discord groups about the best ways to get involved with OS contributions, and this was suggested as a good first step 😃. I'm trying to get back into coding after 10 years of being a scrum master.
