### ISSUE TITLE
[Concept Entry] Python pillow

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4620]
### Reason/inspiration (optional)

Create a new concept for the `Pillow` library and include the `https://pypi.org/project/pillow/` in general. It should go under the path: `docs/content/pillow/pillow.md`
It can have the following:
- A short description of the concept
- ## Installation block
- ## Syntax for importing the concept

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by MattiasBaldi** [comment]
hey i'll to have this assigned!

**Comment by mamtawardhani** [comment]
Hey @MattiasBaldi! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by MattiasBaldi** [comment]
Hi @mamtawardhani, thank you!

I'm doing the git/github course on codeacademy and the last assignment was to take on an issue on docs. 

I'm actually not completely comfortable in python yet, but wanted to challenge myself. I'm going to finish the python course in a week or so, is it okay to have this issue open till then?

**Comment by mamtawardhani** [comment]
@MattiasBaldi Are you still working on this issue?
