### ISSUE TITLE
[Concept Entry] Python pillow - image module

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4621]
### Reason/inspiration (optional)

Create a new concept entry for the `Image Module` of `Pillow` library and include the `https://pillow.readthedocs.io/en/stable/reference/Image.html` in general. It should go under the path: `docs/content/pillow/concepts/image/image.md`
It can have the following:
- A short description of the concept
- ## Syntax for importing the concept

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by MattiasBaldi** [comment]
can I have this?

**Comment by mamtawardhani** [comment]
Hey @MattiasBaldi! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by mamtawardhani** [comment]
Hey @MattiasBaldi! Are you still working on this?

**Comment by mamtawardhani** [comment]
Hey @MattiasBaldi, any updates?

**Comment by MattiasBaldi** [comment]
Sorry, I've been busy. I'll take a look at it ASAP.

**Comment by mamtawardhani** [comment]
@MattiasBaldi yes please, this issue needs to be closed soon since it has been over 1.5 weeks. 😃

**Comment by mamtawardhani** [comment]
@MattiasBaldi any updates?

**Comment by mamtawardhani** [comment]
Hey @MattiasBaldi, I can give you a day more, or else I'll have to un-assign this issue since it has been 2+ weeks. I hope you understand. Thanks!

**Comment by MattiasBaldi** [comment]
@mamtawardhani I'm finishing it right now. 

This is my first issue ever, and the first time I contribute to the docs. This was an obligated part of my git learning course, to contribute to the docs. 

How do I 'include the https://pillow.readthedocs.io/en/stable/reference/Image.html in general.'? Do i just include that URL in my markdown file?  What does general refer to...

Also I am curious to what actually is meant by a concept? Is how to Create thumbnails considered a concept? Is how to mirror an image considered a concept? Is how to import the module itsself enough to be a concept? Is a concept multiple topics and if so which?

I already finished a fairly simple topic on how to create thumbnails, but also another on how to mirror an image.

**Comment by mamtawardhani** [comment]
Hey @MattiasBaldi! A concept entry is an entry that describes the concept (not any terms related to the concept like mirroring an image, or any other term). 
For example, `Plotly` is a library in Python that has modules like `express`, `figure_factory`, and `graph_module`. I'm sharing below a concept entry for the `express` module we need the concept entry for the `Image` module of the Pillow library to be something similar:
https://github.com/Codecademy/docs/blob/main/content/plotly/concepts/express/express.md

Hope this helps! 😃

**Comment by mamtawardhani** [comment]
@MattiasBaldi 
Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.
