### ISSUE TITLE
[Term Entry] Python pillow .rotate()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4627]
### Reason/inspiration (optional)

We would like a new term entry on the '.rotate()' method for the `Pillow` library in Python. The entry should go in a new file under `docs/content/pillow/concepts/image/terms/rotate/rotate.md`

The entry should include the following:

- A description of the function
- A ## Syntax section that includes the syntax of the function and its details
- An ## Example section that includes a ```python ``` codeblock and ```shell ``` that shows the example output.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by surendra-manjhi** [comment]
hey i'd like to have this assigned!

**Comment by letsbuildanything** [comment]
@surendra-manjhi You’re assigned :tada:  In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.
Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by mamtawardhani** [comment]
Unassigning the issue due to the inactivity of the contributor.

**Comment by mazwakes** [comment]
Hi, I am working through the git and gitHub course and I would love to try and collaborate on an issue as part of the course. Is it okay if this one gets assigned to me? I usually use Java but would also love the opportunity to improve my python skills.

**Comment by mamtawardhani** [comment]
Hey @mazwakes, you can take this up 😃
Please refer to the contribution guide I've shared in the above comment.

**Comment by mazwakes** [comment]
thank you
