### ISSUE TITLE
[Concept Entry] Python plotly - figure_factory module

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4644]
### Reason/inspiration (optional)

Create a new concept entry for the `figure_factory` module of `Plotly` library and include the `https://plotly.com/python/figure-factory-subplots/` in general. It should go under the path: `docs/content/plotly/concepts/figure-factory/figure-factory.md`
 It can have the following:
 - A short description of the concept
 - ## Syntax for importing the concept
 
 Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by J1234Mac** [comment]
I am interested in this issue. I heard about docs thorugh a Codecadamy class and it is part of the module. This will be the first time I will have participated in solving a issue. Thanks.

**Comment by J1234Mac** [comment]
Yes, this is my first contribution on docs; as well as, GitHub. I am
working on the Open-Source module in Codecademy. This will be a good
learning experience for me and hope to make more contributions in
the future.

Thanks,
Jeremiah

**Comment by mamtawardhani** [comment]
Hey @J1234Mac! Please review the path once before you start, there is a slight update in the path. Thank you!

**Comment by mamtawardhani** [comment]
No problem @J1234Mac, let me know if there is any help needed. Have a nice week ahead! 😀

**Comment by J1234Mac** [comment]
Figure Factoy

Well, I am not ready for GitHub. I would like to try again at a later time but presently I am not able to transfer from my local drive to github. I can use git and save to my local repository but  that is as far as I can go. Please reassign this project. When I figure out the problem and gain more experience I will try again.

My Apologies 
Jeremiah

**Comment by mamtawardhani** [comment]
Hey @AnkitGovind9 You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.
