### ISSUE TITLE
[Concept Entry] Postgresql constraints

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4646]
### Reason/inspiration (optional)

We would like a new entry on the `Constraints` concept under PostgreSQL. The entry should go in a new file under `docs/content/postgresql/concepts/constraints/constraints.md`.
 
 The entry should include:
 
 - An introductory paragraph that describes the concept
 - A ‘Syntax’ section that includes the syntax for the concept (if applicable)
 - An ‘Example’ section that shows the concept in use
 
 Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by LGVjr2** [comment]
@codecademy-docs I am interested in taking this issue on, I found about Docs through the codecademy git course.

**Comment by LGVjr2** [comment]
I would like to take this issue as part of my CodeCademy Pro Module "Learn Git & GitHub".

**Comment by LGVjr2** [comment]
@mamtawardhani Thanks for your message. Yes this is my first Contribution.
