### ISSUE TITLE
[Concept Entry] Postgresql transactions

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4647]
### Reason/inspiration (optional)

We would like a new entry on the `Transactions` concept under PostgreSQL. The entry should go in a new file under `docs/content/postgresql/concepts/transactions/transactions.md`.
 
 The entry should include:
 
 - An introductory paragraph that describes the concept
 - A ‘Syntax’ section that includes the syntax for the concept (if applicable)
 - An ‘Example’ section that shows the concept in use
 
 Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by natalyjazzviolin** [comment]
@codecademy-docs I'd like to take this issue on!

**Comment by mamtawardhani** [comment]
Hey @natalyjazzviolin! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by mamtawardhani** [comment]
@natalyjazzviolin are you still working on this? Following up on the status of this entry since it has been more than 3 weeks now, please let me know the status and when can you submit this PR. Thanks 😄

**Comment by mamtawardhani** [comment]
Hey @natalyjazzviolin unassigning you due to your inactivity.

**Comment by ScislakMatej** [comment]
@codecademy-docs Hello, I would like to work on this issue.

**Comment by mamtawardhani** [comment]
Hey @ScislakMatej! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by Sriparno08** [comment]
Hey @ScislakMatej, are you still working on this issue?

Note: If you don't respond in a week, you will be unassigned from this issue unfortunately.

**Comment by Sriparno08** [comment]
Unassigning the author due to inactivity.

**Comment by christina-ml** [comment]
Hey @codecademy-docs @Sriparno08, I would like to work on this issue.

**Comment by Sriparno08** [comment]
Hey @christina-ml, you're assigned!

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.
