### ISSUE TITLE
[Concept Entry] Postgresql inheritance

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4648]
### Reason/inspiration (optional)

We would like a new entry on the `Inheritance` concept under PostgreSQL. The entry should go in a new file under `docs/content/postgresql/concepts/inheritance/inheritance.md`.
 
 The entry should include:
 
 - An introductory paragraph that describes the concept
 - A ‘Syntax’ section that includes the syntax for the concept (if applicable)
 - An ‘Example’ section that shows the concept in use
 
 Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by itskarelleh** [comment]
I want to be assigned this issue, please.

**Comment by itskarelleh** [comment]
> @itskarelleh are u still willing to work on this?

I was never assigned this issue.

**Comment by shukriarahimitech** [comment]
hi, @itskarelleh interested in this issue.

**Comment by shukriarahimitech** [comment]
Hi @itskarelleh could you assigned me in this project? I am new and do not know what I should do. kindly help me.

**Comment by letsbuildanything** [comment]
Hi @shukriarahimitech, 
This issue has already been assigned, but you can request assignment on other [unclaimed issues](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee). 
If you need further assistance with the process, feel free to ask!
Thank you!

**Comment by shukriarahimitech** [comment]
@letsbuildanything how could collaborate to this project? thanks.
