### ISSUE TITLE
[Concept Entry] Postgresql operators

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4649]
### Reason/inspiration (optional)

We would like a new entry on the `Operators` concept under PostgreSQL. The entry should go in a new file under `docs/content/postgresql/concepts/operators/operators.md`.
 
 The entry should include:
 
 - An introductory paragraph that describes the concept
 - A ‘Syntax’ section that includes the syntax for the concept (if applicable)
 - An ‘Example’ section that shows the concept in use
 
 Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by nbarnhouse** [comment]
Hi, I would like to work on this.

**Comment by nbarnhouse** [comment]
@dakshdeepHERE I have a draft of this ready, but I wanted to make sure....I included arithmetic operators, comparison operators, and logical operators. Is this what you were expecting?

**Comment by nbarnhouse** [comment]
submitted PR #4764

**Comment by nbarnhouse** [comment]
Submitted https://github.com/Codecademy/docs/pull/4785 to fix PR #4764 error.
