### ISSUE TITLE
[Concept Entry] Python plotly - express module

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4653]
### Reason/inspiration (optional)

Create a new concept entry for the `express` module of `Plotly` library and include the `https://plotly.com/python/plotly-express/` in general. It should go under the path: `docs/content/plotly/concepts/express/express.md`
 It can have the following:
 - A short description of the concept
 - ## Syntax for importing the concept
 
 Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by juliajobczyk** [comment]
can I please be considered for this. it would be my first issue.

**Comment by mamtawardhani** [comment]
Hey @juliajobczyk! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.
