### ISSUE TITLE
[Edit] JavaScript: Errors

### ISSUE THREAD

**Issue by e-runyon** [Codecademy/docs#4662]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

I would like to add new content to the JavaScript [Errors](https://www.codecademy.com/resources/docs/javascript/errors) page for credit towards my course portfolio project.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by AmanWoody** [comment]
I would like to add new content to the JavaScript [Errors] page for credit towards my Learn Git & GitHub assignment.

**Comment by Krilc** [comment]
@e-runyon I would like to add new content to the javaScript [Errors] page for credit towards my Learn Git & GitHub assignment

**Comment by shukriarahimitech** [comment]
@e runyon Hi, I am interested in this issue, kindly assigned to me.

**Comment by e-runyon** [comment]
Everyone,

I need to clarify that I am a Codecademy student who has submitted this issue. I am not a Codecademy moderator, so please do not message/tag me as such.

**Comment by MIB909** [comment]
kindly assign me to this issue , I am interested

**Comment by Linchihj** [comment]
Hi there,
I'm a technical writer and would like to help fix the typos. Please assign this task to me, if no one has been assigned this task yet.

**Comment by Supercool14kassandrajo16** [comment]
@e-runyon  I would like to add new content to the javaScript [Errors] page for credit towards my Learn Git & GitHub assignment.
