### ISSUE TITLE
[Term Entry] Javascript Method : .parseInt()

### ISSUE THREAD

**Issue by ULTRAPAIN** [Codecademy/docs#4672]
### Reason/inspiration (optional)

We would like a new term entry for JavaScript [Numbers Methods](https://www.codecademy.com/resources/docs/javascript/number-methods) about the `.parseInt()` method. The entry should go in a new file in `docs/content/javascript/concepts/number-methods/terms/parseInt/parseInt.md.`

The entry should:

- Have an Introductory paragraph about what the method is and does.
- Have a syntax section illustrating the function in a   ` ```pseudo code` block.
- An example showing the function in a ` ```js` code block.
- A runnable codebyte example in a ` ```codebyte/javascript` block.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term  Entry for Existing Topic.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by andersooi** [comment]
Hi, I’m interested in taking on this issue!

**Comment by Desolateeeooo** [comment]
Hello! I want to contribute on this issue!

**Comment by mamtawardhani** [comment]
@ishg-153 
Can I assign this issue to the contributor? This issue was raised by @ULTRAPAIN (a contributor at Codecademy).
Let me know!

**Comment by ULTRAPAIN** [comment]
yes @mamtawardhani  You can the assign the Issue , Btw how can i assign them ,

**Comment by ishg-153** [comment]
@mamtawardhani Yep this looks good to be assigned!

@ULTRAPAIN Thank you for suggesting this issue.

**Comment by ishg-153** [comment]
@andersooi You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

**Comment by ishg-153** [comment]
@Desolateeeooo, @andersooi was here first. Please look through available issues, and ask to be assigned to an issue of your interest.
