### ISSUE TITLE
[Term Entry] Javascript Method : .parseFloat()

### ISSUE THREAD

**Issue by ULTRAPAIN** [Codecademy/docs#4673]
### Reason/inspiration (optional)

We would like a new term entry for JavaScript [Numbers Methods](https://www.codecademy.com/resources/docs/javascript/number-methods) about the `.parseFloat()` method. The entry should go in a new file in `docs/content/javascript/concepts/number-methods/terms/parseFloat/parseFloat.md.`

The entry should:

- Have an Introductory paragraph about what the method is and does.
- Have a syntax section illustrating the function in a   ` ```pseudo code` block.
- An example showing the function in a ` ```js` code block.
- A runnable codebyte example in a ` ```codebyte/javascript` block.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term Entry for Existing Concept Entry.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by filming** [comment]
Hi, I’m interested in taking on this issue!

**Comment by filming** [comment]
@ULTRAPAIN Hi, I’m interested in taking on this issue!

**Comment by filming** [comment]
@mamtawardhani Hi, I’m interested in taking on this issue!

**Comment by mamtawardhani** [comment]
Hey @filming! You're assigned!🎉You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.
