### ISSUE TITLE
[Concept Entry] MySQL data-types

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4675]
### Reason/inspiration (optional)

We would like a new entry on the `Data types` concept under MySQL. The entry should go in a new file under `docs/content/mysql/concepts/data-types/data-types.md`.

The entry should include:

- An introductory paragraph that describes the concept
- A ‘Syntax’ section that includes the syntax for the concept (if applicable)
- An ‘Example’ section that shows the concept in use

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by ULTRAPAIN** [comment]
I Would be Happy 😃  to work On this Issue , Assign Me❗

**Comment by mamtawardhani** [comment]
Hey @ULTRAPAIN!

Firstly, to inform you this will be the last issue that you can contribute to, since Codecademy allows 3 issues per contributor.  😄 

You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

**Comment by mamtawardhani** [comment]
Hey @ULTRAPAIN! Thank you for your interest in contribution, however, since you have already contributed thrice, I can't assign more issues to you. Codecademy allows 3 issues per contributor.

Thank you for your contribution to Codecademy! 😄

**Comment by emunoz8** [comment]
Can this issue be assigned to me? Thank you.

**Comment by mamtawardhani** [comment]
Hey @emunoz8! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.
Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by emunoz8** [comment]
This is my first time contributing to Docs.  I am doing the GitHub lessons in Codecademy.com.

**Comment by mamtawardhani** [comment]
Hey @emunoz8, are you still working on this? Since it has been a week, could you please update me on the status of this entry? 😃

**Comment by emunoz8** [comment]
Hello @mamtawardhani I believe I might have messed something up on the pull request because it is not going through the "ci" check; https://github.com/Codecademy/docs/pull/4706. Any suggestions would be greatly appreciated.

**Comment by mamtawardhani** [comment]
No worries @emunoz8, it is under review, will let you know if any changes are required. Thank you 😃

**Comment by Alexa86** [comment]
Hello, I would gladly work issue MySQL data-types and can submit first file aprox. by weekend 13-14.07.2024. If acceptable, please assign me. Thank you

**Comment by mamtawardhani** [comment]
@Alexa86 You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.
Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by mamtawardhani** [comment]
Assigned a new author due to inactivity of the previous author

**Comment by A1cX** [comment]
> @Alexa86 You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval. Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

Thank you. I found you during Journey to Linux course on employer learn platform. This is my 2nd attempt to a first contribution in Codecademy Docs and really happy with the learning progress.
