### ISSUE TITLE
[Concept Entry] MySQL bit-functions

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4676]
### Reason/inspiration (optional)

We would like a new entry on the `Bit Functions` concept under MySQL. The entry should go in a new file under `docs/content/mysql/concepts/bit-functions/bit-functions.md`.

The entry should include:

- An introductory paragraph that describes the concept
- A ‘Syntax’ section that includes the syntax for the concept (if applicable)
- An ‘Example’ section that shows the concept in use

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Alexa86** [comment]
Hi, I would love to try and work on this issue, please if possible, assign me. Thank you, alex

**Comment by mamtawardhani** [comment]
Hey @Alexa86! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by Alexa86** [comment]
> Hey @Alexa86! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.
> 
> Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

Hello, I found out about Docs contribution after completing a very good training course here on Codecademy. Thank you

**Comment by Alexa86** [comment]
Hello, I am working to correct the errors, I am sorry for long time. If possible, allow me more time on this issue, do not unassign it yet.

**Comment by mamtawardhani** [comment]
@Alexa86 Alright, got it! Can this be done within 2-3 days?

**Comment by Alexa86** [comment]
I'm working on the lint errors (manually because I can't find the right solution to yarn on my MAC before submit here, I think I keep doing something wrong at the json file), so for now I do all corrections manually with my local text editor ad then submit again.
