### ISSUE TITLE
[Concept Entry] MySQL keywords

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4679]
### Reason/inspiration (optional)

We would like a new entry on the `Keywords` concept under MySQL. The entry should go in a new file under `docs/content/mysql/concepts/keywords/keywords.md`.

The entry should include:

- An introductory paragraph that describes the concept
- A ‘Syntax’ section that includes the syntax for the concept (if applicable)
- An ‘Example’ section that shows the concept in use

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Danielmnm1** [comment]
Hello, I would like to be help out on this issue, I am currently on the iOS developer career path and part of it is to contribute on Docs. I would be very happy to help.

**Comment by mamtawardhani** [comment]
Hey @Danielmnm1! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by Danielmnm1** [comment]
> Hey @Danielmnm1! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.
> 
> 
> 
> Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

Yes, indeed it is my first contribution to Docs, I am currently doing my iOS Career path on Codecademy and part of the course is to contribute to Docs. I am excited to take this step since I know it is also part of being a developer. I will start working on this issue and get it as good as it can be! Thanks a lot!

**Comment by Danielmnm1** [comment]
Hello! Yes I am, I will make the first pull request for the review in a couple hours 🙏🏻
