### ISSUE TITLE
[Concept Entry] MySQL user defined variables

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4680]
### Reason/inspiration (optional)

We would like a new entry on the `User Defined Variables` concept under MySQL. The entry should go in a new file under `docs/content/mysql/concepts/user-defined-variables/user-defined-variables.md`.

The entry should include:

- An introductory paragraph that describes the concept
- A ‘Syntax’ section that includes the syntax for the concept (if applicable)
- An ‘Example’ section that shows the concept in use

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by achur00** [comment]
I would like to take this.

**Comment by letsbuildanything** [comment]
@achur00 You’re assigned :tada:  In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.
Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by achur00** [comment]
Alright, and no this is not my first contribution to Codecademy Docs.

**Comment by mamtawardhani** [comment]
Hey @achur00, following up on the status of this entry since it has been two weeks now, please let me know the status and when can you submit this PR. Thanks 😄

**Comment by mamtawardhani** [comment]
Unassigning @achur00 due to the inactivity

**Comment by andersooi** [comment]
Hi, I am interested in taking on this issue!

**Comment by mamtawardhani** [comment]
Hey @andersooi, you can take up the issue. Please refer to the guidelines shared above. Thanks! 😃
