### ISSUE TITLE
[Concept Entry] MySQL query attributes

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4682]
### Reason/inspiration (optional)

We would like a new entry on the `Query Attributes` concept under MySQL. The entry should go in a new file under `docs/content/mysql/concepts/query-attributes/query-attributes.md`.

The entry should include:

- An introductory paragraph that describes the concept
- A ‘Syntax’ section that includes the syntax for the concept (if applicable)
- An ‘Example’ section that shows the concept in use

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by adrianna-yixin** [comment]
Hi @codecademy-docs I'd like to work on this issue. Please assign 🙌 :)

**Comment by mamtawardhani** [comment]
Hey @adrianna-yixin! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by mamtawardhani** [comment]
@adrianna-yixin are you still working on this? Since it has been two weeks, could you please submit the entry at the earliest?
Thank you! 😃

**Comment by mamtawardhani** [comment]
Unassigning due to the inactivity of the contributor.

**Comment by smlhrnndz** [comment]
Hello, @codecademy-docs! May I work on this issue?

**Comment by mamtawardhani** [comment]
Hello @smlhrnndz! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by smlhrnndz** [comment]
Thank you!

This is my first contribution to Codecademy Docs! I found out from Codecademy's Learn Git & GitHub course!

**Comment by ishg-153** [comment]
@ghost It's been 3 weeks since you were assigned to this issue. Are you still working on the entry?

**Note:** If you don't respond with a PR or an update within a week, this issue will be unassigned from you.

**Comment by tahabakri** [comment]
Hi @mamtawardhani,

I'd like to work on this issue. Could you please assign it to me?

Thank you!

**Comment by mamtawardhani** [comment]
Hey @tahabakri You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by Sriparno08** [comment]
Hey @tahabakri, are you still working on this issue?

Note: If there's no response from your side in a week, you will be unassigned unfortunately.

**Comment by amonaksis** [comment]
Please, I would like to contribute to this topic! Can I have it assigned to me?

**Comment by Radhika-okhade** [comment]
Hey @amonaksis  You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by amonaksis** [comment]
This is my first contribution to Codecademy Docs! I found it out from Codecademy's Learn Git & GitHub course!

**Comment by amonaksis** [comment]
I couldn't find the directory: docs/content/mysql/concepts/query-attributes. Was it removed?
