### ISSUE TITLE
[Term Entry/Organization] Swift Method Term Organization

### ISSUE THREAD

**Issue by J-Fairchild** [Codecademy/docs#4683]
### Reason/inspiration (optional)
I am doing the iOS development career course and adding to the docs is a requirement. As I was looking on the docs to find something that wasn't there I noticed that there were terms for methods outside the method Concept. A example of this is under the Sets concept. I would like to move all methods terms to the method concept and point to that concept instead making the docs more organized. 

This would keep all the previous Entries and how they are used while also:

- Giving a brief description of how methods affect said concept and pointing to the method concept in the docs

- Separating the Method terms into where they are applicable 

- Give a list of built in method terms in one spot for easy finding

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by J-Fairchild** [comment]
The concepts this would affect are:
 Arrays
Classes
Dictionaries 
Extensions
Sets
Potentially structures
And most importantly Method concept

**Comment by chezcye** [comment]
@codecademy-docs I would love to know more about this entry, as I would like to be assigned to it. I am unclear about what I am asking, and I am having trouble with what it is saying. Does 1 of 3 tasks mean 1 task complete? How do you know what task is complete? Can you tell I am a newbie... haha?

**Comment by leopeq21** [comment]
im ready to work on this issue kindly assign it to me .

**Comment by SaviDahegaonkar** [comment]
Hey @leopeq21 ,
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

Thanks  & Regards,
Savi

**Comment by leopeq21** [comment]
Thanks

**Comment by FabioNH86** [comment]
Hello! 
I am very interested in this position, and I am ready to work. I found this course through the Codecademy website, where I am currently taking the iOS Developer course. 
I hope you consider me!

**Comment by mamtawardhani** [comment]
Hey @Sriparno08 as this is an issue related to Swift, could you give some insights if this is a good issue and we can assign it to the authors here? Thank you 😃

**Comment by Sriparno08** [comment]
Sounds like a good idea, @mamtawardhani. This will make the `Methods` concept a one-stop destination for all the methods in Swift. What do you think?

**Comment by mamtawardhani** [comment]
Likewise, @Sriparno0, thank you for the insights 😄 

@FabioNH86 @leopeq21 are any of you still interested in taking up this issue?

**Comment by doctoredroid** [comment]
Hello, I'm interested, I'm taking IOS developer course, I would study this a bit and than apply.
