### ISSUE TITLE
[Concept Entry] Markdown: Footnotes

### ISSUE THREAD

**Issue by CBID2** [Codecademy/docs#4702]
### Reason/inspiration (optional)

I would like to add this term to the Markdown chapter. It'll help technical writers learn how to add references in a new way. 

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by richard-salam** [comment]
Let me know if there is anything that I can help.

**Comment by CBID2** [comment]
> Let me know if there is anything that I can help.

Can you assign the issue to me @richard-salam?

**Comment by richard-salam** [comment]
> > Let me know if there is anything that I can help.
> 
> Can you assign the issue to me @richard-salam?

@CBID2  I am happy to help, but I would like to understand the requirements before committing. :)

**Comment by Sriparno08** [comment]
Hey @CBID2, you're assigned! The entry should go in a new file under `docs/content/markdown/concepts/footnotes/footnotes.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Hey @richard-salam, please go to the 'Issues' tab if you want to contribute and claim an issue that interests you. Please note that the issues are assigned on a first-come-first-serve basis.

**Comment by CBID2** [comment]
Made the pull request @Sriparno08! :)
