### ISSUE TITLE
[Term Entry] Python:NumPy Math Methods abs

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4712]
### Reason/inspiration (optional)

"We would like a new term entry on the `Math Methods` term for [Numpy](https://www.codecademy.com/resources/docs/numpy): abs. The entry should go in a new file under `docs/content/numpy/concepts/math-methods/terms/abs/abs.md`.

The entry should describe the term and how it is used. Also include:
- An "Example" section that explains readers how to use the abs method on a given array.
- Should contain informations for functions and syntax.
- Should have a python codebyte with working code snippet showcasing this function.
Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by evanshi0811** [comment]
Hi, I'd like to try to take this issue on. I'm relatively new to GitHub so this would be my first ever contribution!

**Comment by letsbuildanything** [comment]
@evanshi0811 You’re assigned :tada:  In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.
Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.
