### ISSUE TITLE
[Term Entry] Python:NumPy Math Methods arcsin

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4717]
### Reason/inspiration (optional)

"We would like a new term entry on the `Math Methods` term for [Numpy](https://www.codecademy.com/resources/docs/numpy): arcsin. The entry should go in a new file under `docs/content/numpy/concepts/math-methods/terms/arcsin/arcsin.md`.

The entry should describe the term and how it is used. Also include:
- An "Example" section that explains readers how to use the arcsin method on a given array.
- Should contain informations for functions and syntax.
- Should have a python codebyte with working code snippet showcasing this function.
Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by bhoejtework** [comment]
Could I get this one, please.

**Comment by mamtawardhani** [comment]
Hey @bhoejtework! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by bhoejtework** [comment]
Seems I'm unable to complete the format:verify check when doing a pull request.
At least the lint check gave an idea of what was wrong so you could fix it, but this one.

If I read it correctly, then it's the prettier command that does something...

```shell
Run yarn format:verify
##[debug]/usr/bin/bash --noprofile --norc -e -o pipefail /home/runner/work/_temp/18053e40-94c2-4df5-85ce-74c71fa7a9f1.sh
yarn run v1.22.22
$ prettier "./**/*.(ts|md)" --list-different
content/numpy/concepts/math-methods/terms/arcsin/arcsin.md
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
##[debug]Finished: run
##[debug]Finishing: Run Codecademy/run-on-yarn@v2.0.0
```

**Comment by mamtawardhani** [comment]
Hey @bhoejtework, you can submit the PR with the content, any format errors or lint errors will be taken care of by us, don't worry.
