### ISSUE TITLE
[Term Entry] Python:NumPy Math Methods arctan

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4719]
### Reason/inspiration (optional)

"We would like a new term entry on the `Math Methods` term for [Numpy](https://www.codecademy.com/resources/docs/numpy): arctan. The entry should go in a new file under `docs/content/numpy/concepts/math-methods/terms/arctan/arctan.md`.

The entry should describe the term and how it is used. Also include:
- An "Example" section that explains readers how to use the arctan method on a given array.
- Should contain informations for functions and syntax.
- Should have a python codebyte with working code snippet showcasing this function.
Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by GavinReid82** [comment]
Hi @codecademy-docs, I'm interested in helping with this issue. I'm doing the GitHub course and learning Python. 

Thanks, 
Gavin

**Comment by mamtawardhani** [comment]
Hey @GavinReid82! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by GavinReid82** [comment]
Thanks @mamtawardhani. It is my first, it's part of the Codecademy Git course.

**Comment by mamtawardhani** [comment]
Great! Waiting for your submission 😄

**Comment by ishg-153** [comment]
@GavinReid82 It's been 3 weeks since you were assigned to this issue. Are you still working on the entry?

**Note:** If you don't respond with a PR or an update within a week, this issue will be unassigned from you.

**Comment by GavinReid82** [comment]
Hi @ishg-153 , I thought I had already submitted. I will try and commit/push again. Please let me know if you don't receive it within the next hour.

**Comment by mamtawardhani** [comment]
Unassigning author due to inactivity
