### ISSUE TITLE
[Concept Entry] Python Pillow - ImageFilter module

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4722]
### Reason/inspiration (optional)

Create a new concept entry for the `ImageFilter` module of `Pillow` library and include the `https://pillow.readthedocs.io/en/stable/reference/ImageFilter.html` in general. It should go under the path: `docs/content/pillow/concepts/imagefilter/imagefilter.md`
It can have the following:
- A short description of the concept
- Syntax for importing the concept

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by cbjazzguitar** [comment]
@codecademy-docs  I am interested in taking this issue on, off platform project.

**Comment by mamtawardhani** [comment]
Hey @cbjazzguitar! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by cbjazzguitar** [comment]
Hello,

Sorry life gets in the way . I can work on this and finish it tomorrow.

Thank you

Chris

**Comment by cbjazzguitar** [comment]
Hello 

I pushed  my md file but I don’t see it on GitHub

Not sure what is going on yet

Chris

**Comment by cbjazzguitar** [comment]
hello @mamtaward

I pushed my markdown file but I don't see it on GitHub maybe am doing something wrong.

thanks Chris

**Comment by mamtawardhani** [comment]
Hey Chris, could you please check once if you created the PR from your forked repository and not from the main codecademy docs?

**Comment by cbjazzguitar** [comment]
Can’t find pull request option for my branch , I must have done something wrong . I think I have to start over. Docs is on my local machine - vscode used to write markdown , followed all the walkthroughs yet nothing seems to be getting pushed.

Chris

**Comment by mamtawardhani** [comment]
Yes, you can. Just make sure you follow the first point very carefully about cloning the forked repository on your local device, and also when you raise a pull request, it should be for the forked repository itself. Let me know when you retry it! 😄

**Comment by cbjazzguitar** [comment]
Ok I think I added it .

On py-pillow-imageFilter branch

Chris

**Comment by cbjazzguitar** [comment]
Hello,

Ok I started the whole project over from the beginning and I think I did it right this time.

Thank you

**Comment by cbjazzguitar** [comment]
hello, @mamtawardhani 

I think I did it correctly

Chris
