### ISSUE TITLE
[Term Entry] Python Plotly - Figure_factory .create_distplot()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4723]
### Reason/inspiration (optional)

We would like a new term entry on the '.create_distplot()' method for the `Plotly` library in Python. The entry should go in a new file under `docs/content/plotly/concepts/figure-factory/terms/create-distplot/create-distplot.md`

The entry should include the following:

- A description of the function
- A Syntax section that includes the syntax of the function and its details
- An Example section that includes a ```python ``` codeblock and ```shell ``` that shows the example output.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by kennyotani** [comment]
I am interested in submitting an entry for this topic

**Comment by mamtawardhani** [comment]
Hey @kennyotani! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by mamtawardhani** [comment]
Hey @kennyotani, following up on the status of this entry since it has been two weeks now, please let me know the status and when can you submit this PR. Thanks 😄

**Comment by kennyotani** [comment]
I am still working on this entry and plan to submit the PR by Sunday. Thank you.

**Comment by mamtawardhani** [comment]
Unassigning @kennyotani due to lack of activity

**Comment by Sleepyarno** [comment]
@mamtawardhani Can i work on this issue please?

**Comment by mamtawardhani** [comment]
Hey @Sleepyarno You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by mamtawardhani** [comment]
@Sleepyarno What are the updates on this? It has been almost 2 months now.

**Comment by Sriparno08** [comment]
Unassigning the author due to inactivity.

**Comment by danitellini** [comment]
Can I be assigned @mamtawardhani , please?

**Comment by mamtawardhani** [comment]
Hey @danitellini You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.
