### ISSUE TITLE
[Bug/Error] "Contributions" plural even if user has contributed only once

### ISSUE THREAD

**Issue by hughlilly** [Codecademy/docs#475]
### Actual Behavior

The "Contributors" block on the right side displays contributors, and when each is hovered over, a popup appears. This uses the term "contributions" in the plural, even if that user has contributed to that entry only once.

For example:

<img width="938" alt="image" src="https://user-images.githubusercontent.com/12046008/146692067-391fa176-123d-42c0-bb20-3c34c2367f86.png">

### Expected Behavior

The singular "contribution" should appear instead.

### What browsers are you seeing the problem on?

Safari

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Dusch4593** [comment]
@hughlilly Thank you for raising awareness to this issue! Similar to issue #466, I'm going to defer to our Engineering and Product teams. Perhaps this will be included in a future update to Docs.

**Comment by Dusch4593** [comment]
Closing for now but will most likely revisit later after New Year's. Thank you again, @hughlilly, for pointing this out! 😄
