### ISSUE TITLE
[Term Entry] Lua Strings: .len()

### ISSUE THREAD

**Issue by Sriparno08** [Codecademy/docs#4793]
### Reason/inspiration (optional)

We would like a new term entry on the `.len()` method under Lua. The entry should go in a new file under `docs/content/lua/concepts/strings/terms/len/len.md`.

The entry should include:

- An introduction to the term
- A ‘Syntax’ section that provides the syntax for the term
- An ‘Example’ section that provides an example demonstrating the concept in use
- A ‘Codebyte Example’ section that provides a codebyte example demonstrating the concept in use

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by ivaaane** [comment]
Can I be assigned? I already had a PR open

**Comment by mamtawardhani** [comment]
Hey @ivaaane! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.
