### ISSUE TITLE
[Term Entry] Python Sets: `.copy()`

### ISSUE THREAD

**Issue by mamtawardhani** [Codecademy/docs#4799]
### Reason/inspiration (optional)

We would like a new term entry on the `.copy()` method for Sets in Python. The entry should go in a new file under `docs/content/python/concepts/sets/terms/copy/copy.md`

The entry should include the following:

- A description of the term
- A ##Syntax section that includes the syntax of the method and its details
- An ##Example section that includes a ```py ``` codeblock and ```shell ``` that shows the example output.
- A ##Codebyte Example to show the working of the method

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by nbarnhouse** [comment]
Hi @codecademy-docs, I would like to work on this.

**Comment by mamtawardhani** [comment]
Hey @nbarnhouse! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by nbarnhouse** [comment]
Do you want me to include data on shallow and deep copy or keep it simple and only reference shallow?

**Comment by mamtawardhani** [comment]
@nbarnhouse Let's keep it single, I'll add another entry for `.deepcopy()`

**Comment by nbarnhouse** [comment]
Submitted PR [#4817 ](https://github.com/Codecademy/docs/pull/4817)
