### ISSUE TITLE
[Term Entry] Python Sets: `.clear()`

### ISSUE THREAD

**Issue by mamtawardhani** [Codecademy/docs#4800]
### Reason/inspiration (optional)

We would like a new term entry on the `.clear()` method for Sets in Python. The entry should go in a new file under `docs/content/python/concepts/sets/terms/clear/clear.md`

The entry should include the following:

- A description of the term
- A ##Syntax section that includes the syntax of the method and its details
- An ##Example section that includes a ```py ``` codeblock and ```shell ``` that shows the example output.
- A ##Codebyte Example to show the working of the method

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Linchihj** [comment]
@mamtawardhani Can you assign this issue to me? I'll give it a try.

**Comment by mamtawardhani** [comment]
Hey @Linchihj! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by Linchihj** [comment]
Hi @mamtawardhani,
I've submitted a pull request for your review. Please take a look and let me know if any edits are required.

**Comment by Linchihj** [comment]
@letsbuildanything Thank you for publishing the contribution. One small question, I had included my Github account details, but it's published as anonymous contributor...anyway to change that?
