### ISSUE TITLE
[Edit] Subject: How to Contribute to Codecademy Docs Typo

### ISSUE THREAD

**Issue by Linchihj** [Codecademy/docs#4802]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

Hi there,
I want to fix a typo and grammar issues in this article. 
https://dev.to/codecademy/how-to-contribute-to-codecademy-docs-1a77
Please assign this task to me, so I can complete my ongoing Git & GitHub course. Many thanks.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by mamtawardhani** [comment]
Hey @Linchihj! 
As part of completing your ongoing Git and GitHub course, please select any issue from the [Issues](https://github.com/Codecademy/docs/issues) section that hasn't been assigned to anyone yet. Once you've chosen an issue, request to be assigned to it. Once it is assigned to you, you can begin working on it.
I hope this helps!😃

**Comment by Linchihj** [comment]
Hey Mamta,

I’ve applied to one but that one also is someone trying to complete the
course. I’m not code savvy enough to contribute to other ongoing issues. So
can I just be assigned to work on the current typo issue I submitted?

Best regards,
Judy

**Comment by mamtawardhani** [comment]
@ishg-153 could you please suggest what can be done in this case?

**Comment by ishg-153** [comment]
@Linchihj I understand that you wish to make a contribution as part of your course, but the change you are suggesting is not part of Codecademy Docs. It is an article on a separate website.

I suggest you ask to be assigned to one of the [available issues](https://github.com/Codecademy/docs/issues?q=is%3Aopen+is%3Aissue+-label%3A%22claimed%22) that interest you and once assigned you can create a PR for that issue. Issues marked as `good first issues` typically only require a little bit of research to complete.

**Comment by Linchihj** [comment]
Hi Ishari,
OK. I see what the issue is. I thought that article was part of Codecademy
docs. I'll give one of the first time issues a try. I just don't feel super
confident about fixing code related stuff because if I were familiar with
coding languages I wouldn't have signed up with codecademy in the first
place.

I'll see what I can do.

Many thanks,
Judy

**Comment by Linchihj** [comment]
Please help me remove this issue. Thank you.
