### ISSUE TITLE
[Term Entry] Subject: SQL injection

### ISSUE THREAD

**Issue by cigar-galaxy82** [Codecademy/docs#4805]
### Reason/inspiration (optional)

Create an entry about `SQL injection`  

The entry should include the following:

- A description of the term
- How to perform it
- Use a diagram to show how the whole process works
- Suggest how it can be prevented

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by selenahuang017** [comment]
Hi! I am interested in taking the issue :)

**Comment by mamtawardhani** [comment]
Hey @selenahuang017 You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by selenahuang017** [comment]
Hi! While working on this entry, I found this existing entry: https://github.com/Codecademy/docs/blob/main/content/cybersecurity/concepts/cyber-attack/terms/sql-injection/sql-injection.md 
Is there additional need to add to it?

**Comment by mamtawardhani** [comment]
@selenahuang017 I'll check this and update you asap

**Comment by mamtawardhani** [comment]
@selenahuang017 thank you for highlighting this!

Closing this issue as an entry for this already exists.
