### ISSUE TITLE
[Term Entry] Subject: SQL update

### ISSUE THREAD

**Issue by cigar-galaxy82** [Codecademy/docs#4806]
### Reason/inspiration (optional)

We would like a new term entry on the `UPDATE` Statement in SQL. The entry should go in a new file under `docs/content/sql/concepts/operators/terms/update/update.md`

The entry should include the following:

- A description of the term
- ‘Syntax’ section that includes the how to use it
- Example section to show how to use it

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Entry Type (select all that apply)
New Concept Entrty for Existing Topic

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by zcamina** [comment]
Hi, I am interested in taking this issue on. I found out through a GitHub course.

**Comment by mamtawardhani** [comment]
Hey @zcamina! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by ishg-153** [comment]
@zcamina It's been 2 weeks since you were assigned to this issue. Are you still working on the entry?

**Note:** If you don't respond with a PR or an update within a week, this issue will be unassigned from you.

**Comment by heinzgoedel69** [comment]
This is a useful addition. I can contribute to this issue.

**Comment by mamtawardhani** [comment]
unassigned @zcamina due to inactivity

**Comment by mamtawardhani** [comment]
@heinzgoedel69 You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by Sriparno08** [comment]
Hey @heinzgoedel69, are you still working on this issue?

Note: If there's no response from your side in a week, you will be unassigned unfortunately.

**Comment by Sriparno08** [comment]
Unassigning the author due to inactivity.

**Comment by Maverick073** [comment]
Hi!
I'd love to take up this issue and work on it. If no one is currently assigned, could I be assigned to this? Thanks in advance! 😊
