### ISSUE TITLE
[Term Entry] Subject: SQL IF statement

### ISSUE THREAD

**Issue by cigar-galaxy82** [Codecademy/docs#4808]
### Reason/inspiration (optional)

We would like a new term entry on the `IF` Statement in SQL. The entry should go in a new file under `docs/content/sql/concepts/operators/terms/if/if.md`

The entry should include the following:

- A description of the term
- ‘Syntax’ section that includes the how to use it
- Example section to show how to use it

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Entry Type (select all that apply)
New Concept Entrty for Existing Topic

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by nbarnhouse** [comment]
Hi @codecademy-docs I would like to work on this.

**Comment by mamtawardhani** [comment]
Hey @nbarnhouse, since you are already working on another issue, I would suggest you to complete that first 😃

**Comment by andersooi** [comment]
Hi! I am interested in taking on this issue.

**Comment by AntonioFCampos** [comment]
Hi.
As part of a project to create and submit an entry to [Codecademy Docs](https://www.codecademy.com/resources/docs) I would like to take on this issue.

**Comment by mamtawardhani** [comment]
Hey @andersooi since a few of your PRs are already under review, I would suggest you to wait. Once they are merged, feel free to take more issues 😃

**Comment by mamtawardhani** [comment]
@AntonioFCampos You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by ishg-153** [comment]
@AntonioFCampos It's been a week since you were assigned to this issue. Are you still working on the entry?

**Note:** If you don't respond with a PR or an update within a week, this issue will be unassigned from you.

**Comment by andersooi** [comment]
@ishg-153 I can take on this issue if it's currently not being worked on

**Comment by ishg-153** [comment]
Hey @andersooi, You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

**Note:** I see that you have other issues assigned to you that still have open PRs. Make sure to keep working on changes suggested on those PRs.

**Comment by ishg-153** [comment]
@AntonioFCampos You are being unassigned due to inactivity.
