### ISSUE TITLE
[Entry] CSS: Floats

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#482]
### Entry Type (select all that apply)

New Entry for Existing Subject

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by sudojarvis** [comment]
I would like to work on this issue.

**Comment by Dusch4593** [comment]
> I would like to work on this issue.

@sudojarvis Awesome, thank you! Just assigned you. 😃 

If you haven't already, take a look at the [Docs contributing guide](https://github.com/Codecademy/docs/blob/main/documentation/entry-template.md) and [entry template](https://github.com/Codecademy/docs/blob/main/documentation/entry-template.md) for guidance on writing the entry and PR.

**Comment by ethan-master-coding** [comment]
@Dusch4593 do we know if they are still working on this.

**Comment by sudojarvis** [comment]
@ethan-master-coding  if someone to takes over, they can go ahead.

**Comment by Dusch4593** [comment]
@sudojarvis That sounds good! @ethan-master-coding why don't we allow someone else to ask to be assigned to this one? You've got a entries and edits going on in the "Pull requests" tab.

**Comment by ethan-master-coding** [comment]
@Dusch4593 it almost been a month and I only have 1 open PR. Can I be assigned to this?

**Comment by Dusch4593** [comment]
Sure!
