### ISSUE TITLE
[Concept Entry] Rust Data Types data-types

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4821]
### Reason/inspiration (optional)

We would like a new concept entry for Rust about Data Types. The entry should go in a new file in docs/content/rust/concepts/data-types/data-types.md

The entry should
    - Have an introductory paragraph about the concept.
    - Code block(s) displaying different aspects of the concept.
    - Gif to accompany the code block.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by oanizobanwota** [comment]
@codecademy-docs I will like to work on this task, if the task is not yet assigned to anyone. I came to knew about docs through my learning platform https://learningpeople.percipio.com .

**Comment by mamtawardhani** [comment]
Hey @sethaferd, you've been assigned to an issue already, would you like to take up this issue as well?

**Comment by sethaferd** [comment]
I just realized I jumped the "assignment" step. Apologies for that @mamtawardhani

**Comment by mamtawardhani** [comment]
No problem, just let's not do this in the future assignments 😃
