### ISSUE TITLE
[Concept Entry] Sklearn linear-models

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4822]
### Reason/inspiration (optional)

We would like a new entry on the `Linear Models` concept under Sklearn. The entry should go in a new file under `docs/content/sklearn/concepts/linear-models/linear-models.md`.

The entry should include:

- An introduction to the concept
- A ‘Syntax’ section that provides the syntax for the concept (if applicable)
- An ‘Example’ section that provides an example demonstrating the concept in use
- A ‘Codebyte Example’ section that provides a codebyte example demonstrating the concept in use

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by dueprincipati** [comment]
I'd like to claim this issue. I have reviewed the task requirements and am prepared to work on this. I will follow the contribution guidelines and submit a pull request once completed. Please let me know if any additional information is needed from me. Thank you!

**Comment by letsbuildanything** [comment]
@dueprincipati  You’re assigned :tada:  In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.
Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by dueprincipati** [comment]
Yes, this is my first contribution to Codecademy Docs. I discovered the opportunity to contribute through my exploration of educational technology platforms.

**Comment by Sriparno08** [comment]
Hey @dueprincipati, are you still working on this issue?

Note: If there's no response from your side in a week, you will be unassigned unfortunately.

**Comment by mamtawardhani** [comment]
Unassigned author due to inactivity
