### ISSUE TITLE
[Concept Entry] Sklearn linear-regression-analysis

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4823]
### Reason/inspiration (optional)

We would like a new entry on the `Linear Regression Analysis` concept under Sklearn. The entry should go in a new file under `docs/content/sklearn/concepts/linear-regression-analysis/linear-regression-analysis.md`.

The entry should include:

- An introduction to the concept
- A ‘Syntax’ section that provides the syntax for the concept (if applicable)
- An ‘Example’ section that provides an example demonstrating the concept in use
- A ‘Codebyte Example’ section that provides a codebyte example demonstrating the concept in use

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Barry-dE** [comment]
I would like to work on this.

**Comment by mamtawardhani** [comment]
Hey @Barry-dE You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by Sriparno08** [comment]
Hey @Barry-dE, are you still working on this issue?

Note: If there's no response from your side in a week, you will be unassigned unfortunately.

**Comment by Radhika-okhade** [comment]
Unassigning due to inactivity of the contributor.
