### ISSUE TITLE
[Concept Entry] PyTorch Tensors

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4825]
### Reason/inspiration (optional)

We would like a new entry on the `Tensors` concept under PyTorch. The entry should go in a new file under `docs/content/pytorch/concepts/tensors/tensors.md`.

The entry should include:

- An introduction to the concept
- A ‘Syntax’ section that provides the syntax for the concept (if applicable)
- An ‘Example’ section that provides an example demonstrating the concept in use
- A ‘Codebyte Example’ section that provides a codebyte example demonstrating the concept in use

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by noahpgordon** [comment]
I'll do this.

**Comment by mamtawardhani** [comment]
Hey @noahpgordon! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by noahpgordon** [comment]
> Hey @noahpgordon! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.
> 
> Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

Not my first rodeo. :)

**Comment by ishg-153** [comment]
@noahpgordon It's been a week since you were assigned to this issue. How's it coming along?

**Note:** If you don't respond with a PR or an update within a week, this issue will be unassigned from you.

**Comment by noahpgordon** [comment]
> @noahpgordon It's been a week since you were assigned to this issue. How's it coming along?
> 
> **Note:** If you don't respond with a PR or an update within a week, this issue will be unassigned from you.

I'm gonna need another week on this. Things have gotten unexpectedly busy on my end.

**Comment by ishg-153** [comment]
Alright @noahpgordon, I'll check back in next week.

**Comment by letsbuildanything** [comment]
@noahpgordon I've updated the path in the description above from `../tensor/tensor.md` to `../tensors/tensors.md`. Please review it before pushing the PR. 
Thanks!

**Comment by noahpgordon** [comment]
A quick update: I'm actively drafting this and should have a PR by today or tomorrow.
