### ISSUE TITLE
[Concept Entry] PyTorch autograd

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4827]
### Reason/inspiration (optional)

We would like a new entry on the `autograd` concept under PyTorch. The entry should go in a new file under `docs/content/pytorch/concepts/autograd/autograd.md`.

The entry should include:

- An introduction to the concept
- A ‘Syntax’ section that provides the syntax for the concept (if applicable)
- An ‘Example’ section that provides an example demonstrating the concept in use
- A ‘Codebyte Example’ section that provides a codebyte example demonstrating the concept in use

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Linchihj** [comment]
I'd like to be assigned this issue.

**Comment by mamtawardhani** [comment]
Since @Linchihj commented first, will assign it to her. @sethaferd you can look through the available issues and let me know if anything interests you 😃

**Comment by mamtawardhani** [comment]
@Linchihj You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by Linchihj** [comment]
Hi @mamtawardhani,
This one will take me more research to finish, so it may take me a week. I'll let you know when the draft is ready for review and include references I've used to write the concept.

**Comment by Linchihj** [comment]
Hi @mamtawardhani,
I've submitted the pull request for the first draft yesterday.
