### ISSUE TITLE
[Term Entry] Python:NumPy ndarray .tolist()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4828]
### Reason/inspiration (optional)

We would like a new entry on the `tolist` term under Numpy, `ndarray` concept. The entry should go in a new file under `docs/content/numpy/concepts/ndarray/terms/tolist/tolist.md`.

The entry should include:

- An introduction to the concept
- A ‘Syntax’ section that provides the syntax for the concept (if applicable)
- An ‘Example’ section that provides an example demonstrating the concept in use
- A ‘Codebyte Example’ section that provides a codebyte example demonstrating the concept in use

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by jmargitic** [comment]
I would like to take this issue! 
Thanks!

**Comment by mamtawardhani** [comment]
Hey, @jmargitic! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by jmargitic** [comment]
It is! I'm excited to contribute. Just a small question. I am not sure I'll be able to add all the contribution on one go, and I've seen people get unassigned for delaying to contribute. Is there a way I can let you know I'm still working on the issue?
