### ISSUE TITLE
[Term Entry] Python:NumPy ndarray .fill()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4830]
### Reason/inspiration (optional)

We would like a new entry on the `fill` term under Numpy, `ndarray` concept. The entry should go in a new file under `docs/content/numpy/concepts/ndarray/terms/fill/fill.md`.

The entry should include:

- An introduction to the concept
- A ‘Syntax’ section that provides the syntax for the concept (if applicable)
- An ‘Example’ section that provides an example demonstrating the concept in use
- A ‘Codebyte Example’ section that provides a codebyte example demonstrating the concept in use

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by oanizobanwota** [comment]
@codecademy-docs I will like to take on this task, if it is not yet assigned to anyone, I came to know about docs through my learning platform https://learningpeople.percipio.com

**Comment by mamtawardhani** [comment]
Hey @oanizobanwota! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by oanizobanwota** [comment]
@mamtawardhani thanks for assigning the task to me, yes it is my first time and  I came to know about docs through my learning platform https://learningpeople.percipio.com
