### ISSUE TITLE
[Term Entry] Subject: SQL Not equal to operator

### ISSUE THREAD

**Issue by cigar-galaxy82** [Codecademy/docs#4850]
### Reason/inspiration (optional)

We would like a new term entry on the `Not equal to` operator in SQL. The entry should go in a new file under `docs/content/sql/concepts/operators/terms/not-equal-to/not-equal-to.md`

The entry should include the following:

- A description of the term
- ‘Syntax’ section that includes the how to use it
- Example section to show how to use it

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by mamtawardhani** [comment]
Hey @sethaferd You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by cigar-galaxy82** [comment]
Hi @sethaferd we want it inside the docs. Can you send the link where you found it.

**Comment by cigar-galaxy82** [comment]
@sethaferd we want it inside the docs for SQL like [this](https://www.codecademy.com/resources/docs/sql/operators/and). The one you send is inside a module that is different.

**Comment by cigar-galaxy82** [comment]
Also for the PR you created someone will review it soon

**Comment by cigar-galaxy82** [comment]
@sethaferd understood so I hope everything is clear as to where this content will go.
