### ISSUE TITLE
Fix magic8.py error

### ISSUE THREAD

**Issue by Linchihj** [Codecademy/docs#4858]
The code for magic8.py uses the Python random library without importing it. This causes issues during runtime.

**Comment by ishg-153** [comment]
Hello @Linchihj Are you proposing a change to any of the existing Codecademy Docs entries or an idea for a new entry?

**Comment by Linchihj** [comment]
Hi @ishg-153,
I think the issue might be on MacOS running python3, the command needs to be changed to `python3` to work.

**Comment by ishg-153** [comment]
@Linchihj Can you tell me where you are facing this issue?

**Comment by Linchihj** [comment]
Hi @ishg-153,
My apologies, I think I mistook this issue with another one I faced in another project.
[add-automated-tests-off-platform-project](https://github.com/Linchihj/add-automated-tests-off-platform-project).

**Comment by mamtawardhani** [comment]
Closing this issue
