### ISSUE TITLE
[Concept Entry] Sklearn support-vector-machines

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4860]
### Reason/inspiration (optional)

We would like a new entry on the `Support Vector Machines` concept under Sklearn. The entry should go in a new file under `docs/content/sklearn/concepts/support-vector-machines/support-vector-machines.md`.

The entry should include:

- An introduction to the concept
- A `Syntax` section that provides the syntax for the concept (if applicable)
- An `Example` section that provides an example demonstrating the concept in use
- A `Codebyte Example` section that provides a codebyte example demonstrating the concept in use

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by evanshi0811** [comment]
I would like to contribute to this issue

**Comment by mamtawardhani** [comment]
Hey @evanshi0811 You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by evanshi0811** [comment]
Unassigned myself since I won't have time to work on this until at least next week.

**Comment by Sleepyarno** [comment]
@mamtawardhani  Hi, can i work on this issue please

**Comment by hakdo99** [comment]
Hi @mamtawardhani , I'd like to work on this issue!

**Comment by mamtawardhani** [comment]
Hey @hakdo99, you have been assigned to 2 issues already, would you like to work on this as well? If yes, until when can you submit a PR for this? Let me know, thank you! 😃

**Comment by liamjdavis** [comment]
Hi @mamtawardhani, if @hakdo99 is not assigned to this issue, I would like to be assigned!

**Comment by hakdo99** [comment]
@mamtawardhani Please assign this to @liamjdavis then, I'll focus on the other two issues!

**Comment by mamtawardhani** [comment]
Hello @liamjdavis, you can take up this issue. Please find the contribution guide in the above comment. Thank you! 😃
