### ISSUE TITLE
[Edit] JavaScript [Edit] JavaScript: Hash Tables

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4865]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Hash Tables` concept entry under JavaScript. The entry lives in `content/javascript/concepts/hashtables/hashtables.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a `Codebyte Example` section that provides a codebyte example demonstrating the concept in use
2) Ensure that the codebyte example is different than all the other examples in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by Vince326** [comment]
I'd like to work on this issue.

**Comment by mamtawardhani** [comment]
Hey @Vince326 You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by Vince326** [comment]
I found out about you through the project section on the IOS development path. Please also work on updating the content on the learning path as well.

**Comment by mamtawardhani** [comment]
Unassigning author due to inactivity

**Comment by ChristianNardi** [comment]
Hello, I would like to work on this issue...

**Comment by claudiooleite** [comment]
Hi guys! I want to work on this issue. Thank you
