### ISSUE TITLE
[Edit] CSS [Edit] CSS: Filter Functions `saturate`

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4867]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `saturate` term entry under Filter Functions concept in CSS. The entry lives in `content/css/concepts/filter-functions/terms/saturate/saturate.md`.

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a output image comparing the original image in the example already given in the entry to its saturate filter version.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by chrisleond11** [comment]
Hello, I would like to apply for this issue please

**Comment by mamtawardhani** [comment]
Hey @chrisleond11 You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by chrisleond11** [comment]
Thankyou for approving me! I found out Codecademy Docs through 'Learn Git & GitHub' course, as a part of one of its project.
I'll do my best for this issue.

**Comment by chrisleond11** [comment]
@mamtawardhani Aside from adding the output image, may I make some changes to the example and the content?

**Comment by mamtawardhani** [comment]
@chrisleond11 if you think it is needed, you can do that.
