### ISSUE TITLE
[Edit] CSS [Edit] CSS: Animations `animation-play-state`

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4868]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `animation-play-state` term entry under Animations concept in CSS. The entry lives in `content/css/concepts/animations/terms/animation-play-state/animation-play-state.md`.

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a output gif for both the examples already given in the entry.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by mamtawardhani** [comment]
Hey @MohamedLDamba You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by MohamedLDamba** [comment]
Thank you @mamtawardhani  I found about you through codecademy.
