### ISSUE TITLE
[Edit] CSS [Edit] CSS: Filter Functions `sepia`

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4869]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `sepia` term entry under Filter Functions concept in CSS. The entry lives in `content/css/concepts/filter-functions/terms/sepia/sepia.md`.

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a output image comparing the original image in the example already given in the entry to its sepia filter version.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by JEllis1313** [comment]
I am interested in working on this issue.

**Comment by mamtawardhani** [comment]
Hey @JEllis1313 You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by JEllis1313** [comment]
I am actually starting my coding journey using Codecademy courses.

**Comment by Sleepyarno** [comment]
@mamtawardhani I would like to work on this issue please.

**Comment by mamtawardhani** [comment]
Hey @Sleepyarno since this issue is already taken, you can look through the open issues [here](https://github.com/Codecademy/docs/issues), and let me know if anything interests you 😃

**Comment by sa-abdullah** [comment]
Hi @Sriparno08 Kindly assign this issue to me. I'm excited to work on it as soon as possible

**Comment by Sriparno08** [comment]
Hey @sa-abdullah, you're assigned!

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

**Comment by danitellini** [comment]
Can I be assigned to this issue, please? @Radhika-okhade

**Comment by mamtawardhani** [comment]
Hey @danitellini I already assigned you to an issue, would you like to work on this as well?

**Comment by danitellini** [comment]
Yes please

**Comment by Radhika-okhade** [comment]
Hey @danitellini  You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by Chantal8810** [comment]
I am interested in working on this issue.

**Comment by Radhika-okhade** [comment]
@Chantal8810, @danitellini is working on this issue. We have multiple new issues added today, you can take up that. 😃

**Comment by danitellini** [comment]
> Hey @danitellini You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. I see this is your first time contributing to Codecademy Docs. How did you find out about us?

Not my first time 😝
