### ISSUE TITLE
[Edit] CSS [Edit] CSS: Flexbox `flex-basis`

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4870]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `flex-basis` term entry under Flexbox concept in CSS. The entry lives in `content/css/concepts/flexbox/terms/flex-basis/flex-basis.md`.

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a output image for the example already given in the entry.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by George-Hiatt-Git** [comment]
I'd like to work on this issue if possible 🙂

**Comment by mamtawardhani** [comment]
Hey @George-Hiatt-Git You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by George-Hiatt-Git** [comment]
Apologies for the delay in response, I've was unwell for a short period there. I found out about this through the "Learn Git & GitHub" course which I'm completing. I'll submit a pull request for review over the coming weekend, much appreciated 🙂

**Comment by Sleepyarno** [comment]
Hi, can i work on this issue?

**Comment by mamtawardhani** [comment]
Hey @Sleepyarno since this issue is already taken, you can look through the open issues [here](https://github.com/Codecademy/docs/issues), and let me know if anything interests you 😃
