### ISSUE TITLE
[Edit] JavaScript: Iterators

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4888]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Iterators` concept entry under JavaScript. The entry lives in `content/javascript/concepts/iterators/iterators.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a `Codebyte Example` section that provides a codebyte example demonstrating the concept in use
2) Ensure that the codebyte example is different than all the other examples in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by blu3army** [comment]
Hi ! Can I have the assigned to this work ?

**Comment by blu3army** [comment]
Can I have the assignment to this work ?

**Comment by mamtawardhani** [comment]
Hey, @blu3army You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by tarunkumar101** [comment]
@tarunkumar101 I'm interested

**Comment by KORADA-BALA-PAVANI** [comment]
@KORADA-BALA-PAVANI I'm interested

**Comment by mamtawardhani** [comment]
@tarunkumar101 @KORADA-BALA-PAVANI since this issue is already taken, you can look through other issues [here](https://github.com/Codecademy/docs/issues) and comment on the issue that interests you 😃

**Comment by cigar-galaxy82** [comment]
Hi @blu3army are you still working on this issue?

**Comment by cigar-galaxy82** [comment]
unassigning due to lack of activity
