### ISSUE TITLE
[Edit] Markdown: Links

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4890]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Links` concept entry under Markdown. The entry lives in `content/markdown/concepts/links/links.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a section on Internal Linking.
2) Ensure to add an example of Internal Linking.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by affank1020** [comment]
Hello, could I be assigned to this issue? Would be my first contribution here, thank you

**Comment by mamtawardhani** [comment]
Hey, @affank1020 You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by affank1020** [comment]
> Hey, @affank1020 You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.
> 
> I see this is your first time contributing to Codecademy Docs. How did you find out about us?

Hi, thanks for assigning.
I think I found the Codecademy repository in my Explore Repositories feed. I want to get more involved in open-source development, and I thought working on Docs might be a good place to start.
