### ISSUE TITLE
[Edit] Markdown: Images

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4891]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Images` concept entry under Markdown. The entry lives in `content/markdown/concepts/images/images.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Edit the `Linked Images` section to add the output of the Markdown example.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by muhammedazhar** [comment]
I want to contribute to this issue. Can you assign me to this issue? I have been working with Markdowns for a while now. I would love to solve this one.

**Comment by mamtawardhani** [comment]
Hey @muhammedazhar 
You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by muhammedazhar** [comment]
Thank you for assigning this issue to me. I will read through the guide and materials you have provided to me. Thanks a lot for the help. I came across these Docs from Codecademy itself.

**Comment by arsan-che** [comment]
Hi @mamtawardhani,
Can I also be assigned to this issue, please?
I found this through Codecademy course.
Thanks!

**Comment by L33TW0RLD** [comment]
Hi, there hasn't been any activity on this issue. I'd be happy to take it over if it's available. Could you please assign it to me?

I found this through Codecademy Learn Git & GitHub course.

**Comment by mamtawardhani** [comment]
Hey @arsan-che @L33TW0RLD any of you would like to take on this issue?

**Comment by danitellini** [comment]
Can I be assigned this issue, please? @mamtawardhani
