### ISSUE TITLE
[Edit] Markdown: Code Blocks

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4892]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Code Blocks` concept entry under Markdown. The entry lives in `content/markdown/concepts/code-blocks/code-blocks.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a section on creating code blocks using the indent lines method.
2) Ensure to demonstrate using an example.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by RizalSuhaimi** [comment]
@SSwiniarski Hello. I am interested in taking on this issue. Currently going through the "Learn Git & GitHub" course, so this would be good practice

**Comment by RobertPantoja** [comment]
Hi! I would like to work on this issue as part of "Contributing to the Codecademy Docs" section.

**Comment by mamtawardhani** [comment]
Hey @RizalSuhaimi Hey @negarvahid You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by mamtawardhani** [comment]
@RobertPantoja since @RizalSuhaimi commented first, he has been assigned to this issue.

You can look at the available issues and let me know if anything interests you. 😃

**Comment by RizalSuhaimi** [comment]
@mamtawardhani Thanks. I'll get to implementing the feature.

I found out about Codecademy from my dad many years ago while I was still in high school but I never got into it then. Fast forward till now, I was affected by the mass layoffs happening in the video games industry, so I am currently looking for a career change. Currently, I'm also going through the Data Scientist: Machine Learning course.
