### ISSUE TITLE
[Edit] Powershell: Arrays

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4893]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Arrays` concept entry under Powershell. The entry lives in `content/powershell/concepts/arrays/arrays.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Edit the content of `Range Operator` in the section `Indexing`. It is stated that the operator is exclusive but it is inclusive.
2) Ensure to correct the description, note, and the code block.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by neonflamingo88** [comment]
Hi! May I work on this issue?

**Comment by mamtawardhani** [comment]
@neonflamingo88 You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by neonflamingo88** [comment]
Thank you! I'm working through the full-stack software engineering track on Codecademy and thought this would be a good first issue to tackle as I practice Git and GitHub.
