### ISSUE TITLE
[Edit] C#: Interfaces

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4894]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Interfaces` concept entry under C#. The entry lives in `content/c-sharp/concepts/interfaces/interfaces.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Edit the existing code block to demonstrate default implementations for some of the Interface members.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by LewisMK** [comment]
Hello, can I write this entry? Thank you!

**Comment by Maregeo-20** [comment]
## Hello,
I am writing to express my interest in resolving the issue related to editing the Interfaces concept entry under C# in the content/c-sharp/concepts/interfaces/interfaces.md file.

**Comment by mamtawardhani** [comment]
Hey @LewisMK You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by mamtawardhani** [comment]
@Maregeo-20 since @LewisMK has commented earlier, this issue has been assigned to him. You can look into the available issues and let me know if anything interests you 😃

**Comment by LewisMK** [comment]
Hey @mamtawardhani thank you for assigning me.  I found out about the program while taking a technical writing course last year and it is not my first contribution. I have contributed to a few issues since last year. One of them is issue #2774  

![image](https://github.com/user-attachments/assets/26d2a5d9-0c83-4b00-87b0-d02301f6959c)
