### ISSUE TITLE
[Term Entry] UI/UX Qualitative Research: Thematic Analysis

### ISSUE THREAD

**Issue by Sriparno08** [Codecademy/docs#4903]
### Reason/inspiration (optional)

We would like a new entry on the `Thematic Analysis` term under UI/UX. The entry should go in a new file under `docs/content/uiux/concepts/qualitative-research/terms/thematic-analysis/thematic-analysis.md`.

The entry should include:

- An introduction to the term and how it is used within UI/UX
- Image(s) to aid understanding (if applicable)

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by sturrdlefish** [comment]
Hi! Could I be assigned this issue?

**Comment by mamtawardhani** [comment]
Hey @sturrdlefish Hey @negarvahid You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by sturrdlefish** [comment]
I found out about Docs while looking for open-source technical writing projects I could contribute to. Glad to have found this!
