### ISSUE TITLE
[Entry Request] General: Cryptocurrency

### ISSUE THREAD

**Issue by lhmzhou** [Codecademy/docs#491]
### Reason/inspiration (optional)

What is cryptocurrency? 
Pretend I'm 5 years old, and explain what Bitcoin is? Ethereum? Dogecoin? DeFi?
Share wisdom on the future of crypto and how it will shape the role of money in society. 

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by catherinemds** [comment]
Hi, can I take on this issue?

**Comment by djouonhou** [comment]
#curency

**Comment by FarScoutOne** [comment]
I would love to take this one on.

**Comment by KTom101** [comment]
@FarScoutOne It's all yours!

**Comment by dharmelolar** [comment]
Hello @KTom101 
I can see that this issue has not been worked on. Would it be possible for me to work on it?

**Comment by KTom101** [comment]
@FarScoutOne Have you been working on this? If not, we can let @dharmelolar have it.

**Comment by FarScoutOne** [comment]
I have a draft that I would like to post this week. I apologize for the delay. I since started a new job and in the busyness of it all I completely forgot about this. I will post the finished crypto doc by the end of this week.

**Comment by KTom101** [comment]
@FarScoutOne Sounds good, thank you!

**Comment by KTom101** [comment]
@dharmelolar Is there another issue you would like to work on? If you see one, please tag me so I can assign you.

**Comment by dharmelolar** [comment]
I’ll look for other issues and tag you to it. Or do think it is possible for me to open a new issue?

**Comment by KTom101** [comment]
@dharmelolar What issue were you looking to add?

**Comment by dharmelolar** [comment]
@KTom101  I’m thinking of adding a technical writing issue  to the General concept

**Comment by KTom101** [comment]
@dharmelolar As suggested by my teammate @yangc95, this would work well as an improvement to our [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md#general-writing-tips) instead of being a Docs entry. We currently have a small section with writing tips. It can be extended to include information on technical writing. 

It will be a helpful resource for contributors looking for additional help. Is this something you would like to work on?

**Comment by dharmelolar** [comment]
@KTom101  That would be fine. Can I Jump on it immediately?

**Comment by KTom101** [comment]
@dharmelolar Yes, you can! I've made an issue for it [here](https://github.com/Codecademy/docs/issues/670). Can you drop a quick comment under the thread so I can assign you? Thanks!

**Comment by 0xTomas** [comment]
Hi there @KTom101, I see that this issue is still open. I would love to add a contribution here if possible.

**Comment by KTom101** [comment]
@FarScoutOne Are you still going to upload the draft you had for this entry?

**Comment by FarScoutOne** [comment]
You can pet someone else take it. I have way too much going on and I don't have easy access to my work. In case it helps though, I do have a list of the resources that I found most helpful and pasted them below for in case the next person can use them. 

https://www.investopedia.com/terms/c/cryptocurrency.asp

https://www.kaspersky.com/resource-center/definitions/what-is-cryptocurrency

https://www.forbes.com/advisor/investing/what-is-cryptocurrency/

https://www.nerdwallet.com/article/investing/cryptocurrency-7-things-to-know

https://www.coinbase.com/learn/crypto-basics/what-is-cryptocurrency

https://youtu.be/URN9kRMdQAM

**Comment by KTom101** [comment]
@FarScoutOne Thank you, will do!

**Comment by KTom101** [comment]
@0xTomas This is all yours now. You can check out the helpful links the previous assignee left above. Please let us know if you need help with anything!

**Comment by 0xTomas** [comment]
@KTom101 I have drafted a version here. Please review and let me know your thoughts.
