### ISSUE TITLE
[Term Entry] Python Math Module .isclose()

### ISSUE THREAD

**Issue by ashdawn04** [Codecademy/docs#4925]
### Reason/inspiration (optional)

.isclose can be used in places where float comparisons using the == operator would be false when we would actually want the comparison to be true.  I would like to create an entry in the Python Math Module for this term.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by ashdawn04** [comment]
@codecademy-docs  may I please add the .isclose() term?

**Comment by mamtawardhani** [comment]
Hey @ashdawn04 You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by mamtawardhani** [comment]
Hey @ashdawn04, I've created this issue in the codecademy issue's section, I'm assigning it to you there. Please do check! 😃 
Closing this issue.
