### ISSUE TITLE
[Term Entry] PyTorch Tensors .ones()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4936]
### Reason/inspiration (optional)

We would like a new entry on the `.ones()` term under PyTorch `Tensors` concept. The entry should go in a new file under `docs/content/pytorch/concepts/tensors/terms/ones/ones.md`.

The entry should include:

- An introduction to the concept
- A ‘Syntax’ section that provides the syntax for the concept (if applicable)
- An ‘Example’ section that provides an example demonstrating the concept in use

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by kerikek** [comment]
Hello! I would like to claim this issue, it would be my first issue. Looking forward to learning more about PyTorch.

**Comment by mamtawardhani** [comment]
Hey @kerikek You're assigned!! In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already. After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by kerikek** [comment]
This is my first contribution to Codecadeemy Docs and I found it through the "Learn Git & Github" course.

Thanks!

**Comment by letsbuildanything** [comment]
Hey @kerikek ,
I've edited the description. A codebyte example is not required for this issue.

**Comment by kerikek** [comment]
Hey there @letsbuildanything 
Noted! Thanks
