### ISSUE TITLE
[Term Entry] Python Math-Module: `.isclose()`

### ISSUE THREAD

**Issue by mamtawardhani** [Codecademy/docs#4943]
### Reason/inspiration (optional)

We would like a new term entry on the `.isclose()` method for [Python- Math Module](https://www.codecademy.com/resources/docs/python/math-module): `math.isclose()`. The entry should go in a new file under `docs/content/python/concepts/math-module/terms/math-isclose/math-isclose.md`

The entry should include the following:
- A description of the function
- A `## Syntax` section that includes the syntax of the function and its details
- An `## Example` section that includes a ` ```python ``` ` codeblock and ` ```shell ``` ` that shows the example output.
- A `## Codebyte Example` that includes a ` ```codebyte/python ``` ` runnable codeblock

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by mamtawardhani** [comment]
Hey @ashdawn04, You're assigned!! In addition to the documents linked in the description, please also look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide) if you haven't already. After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by ashdawn04** [comment]
This is my first contribution.  I am working toward the certification for Git and Github on Codecademy, and I really appreciate the courses and resources offered there. This function works very similar to how a delta check in a laboratory works, so it feels familiar.  Thank you for assigning this to me!
