### ISSUE TITLE
[New Entry] Subject: SQL CONCAT function

### ISSUE THREAD

**Issue by cigar-galaxy82** [Codecademy/docs#4958]
### Reason/inspiration (optional)

We want a new term entry on the CONCAT function in SQL. The entry should go into a new folder under docs/content/sql/concepts/string-function/terms/concat/concat.md

The entry should include the following:

- A description of the term
- ‘Syntax’ section that includes how to use it
- Example section to show how to use it

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by RomShalfey** [comment]
Hey, as a part of my "Learn Git & GitHub" course I'm looking for an issue on Docs to work with. I have a fair experience utilizing my SQL knowledges, but I'm eager to improve while solving this issue. 

Please, assign it for me. Thank you.

**Comment by mamtawardhani** [comment]
Hey @RomShalfey! You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by RomShalfey** [comment]
Sure, I will take a look on guide. 

Yes, it's going to be my 1st contribution to Docs. I learned about contributing to Docs via my learning process on course "Learn Git & GitHub" it's a part of my study. 

Thanks for assigning me ~
