### ISSUE TITLE
[New Entry] Subject: SQL SUBSTRING function

### ISSUE THREAD

**Issue by cigar-galaxy82** [Codecademy/docs#4960]
### Reason/inspiration (optional)

Reason/inspiration (optional)
We want a new term entry on the `SUBSTRING` function in SQL. The entry should go into a new folder under docs/content/sql/concepts/string-function/terms/substring/substring.md

The entry should include the following:

1. A description of the term
2. ‘Syntax’ section that includes how to use it
3. Example section to show how to use it

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by sebasmagno007** [comment]
Hello, I am interested in this issue. I found about it through the task in GitHub course.

**Comment by mamtawardhani** [comment]
Hey @sebasmagno007 You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by sebasmagno007** [comment]
Hello @mamtawardhani thank you, I will get in this issue right now, this is my first contribution and is part of my Doc contribution task in the Git&GitHub course.
