### ISSUE TITLE
[Concept Entry] Sklearn multilabel-classification

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4967]
### Reason/inspiration (optional)

We would like a new entry on the `Multilabel Classification` concept under Sklearn. The entry should go in a new file under `docs/content/sklearn/concepts/multilabel-classification/multilabel-classification.md`.

The entry should include:

- An introduction to the concept
- A `Syntax` section that provides the syntax for the concept (if applicable)
- An `Example` section that provides an example demonstrating the concept in use (if applicable)
- A `Codebyte Example` section that provides a codebyte example demonstrating the concept in use (if applicable)

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Ssylle** [comment]
Hello @codecademy-docs team! 

I'm currently going through the full stack engineer formation and thus would like to tackle on this issue as my first git contribution so I can validate the teamwork part of the github module 🙂. I didn't really know where to start or if this issue is really suited for me but i'll be sure to do my very best nontheless ! 

Kind regards 😽

**Comment by mamtawardhani** [comment]
Hey @Ssylle You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.
 😄

**Comment by Ssylle** [comment]
Perfect ! 
Is there a deadline of any sort ? I'm working on a 30h per week summer job aside the formation so if that is in any way shape or form a problem i'm open to discuss it if not i'll start working on it asap. 🙂

**Comment by mamtawardhani** [comment]
> Perfect ! Thanks!!
> 
> Is there a deadline of any sort ? I'm working on a 30h per week summer job aside the formation so if that is in any way shape or form a problem i'm open to discuss it if not i'll start working on it asap. 🙂

@Ssylle That shouldn't be a problem. Just if possible, you can try submitting a PR within a week or two at max 😃

**Comment by Ssylle** [comment]
Ok! 

I'll do my best it should be possible 🙂

**Comment by mamtawardhani** [comment]
Unassigning author due to inactivity
