### ISSUE TITLE
[Term Entry] C++ vector .empty()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4985]
### Reason/inspiration (optional)

"""We would like a new entry on the `.empty()` term entry in Cpp under `Vector` concept. The entry should go in a new file under `content/cpp/concepts/vectors/terms/empty/empty.md`.

The entry should include:

- An introduction to the concept
- A `Syntax` section that provides the syntax for the concept.
- An `Example` section that provides an example demonstrating the concept in use.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."""

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by nicolasperezquintero** [comment]
Hi! I would like to work in this issue as a first entry experience.

**Comment by nicolasperezquintero** [comment]
Thank you! I will look at the Contribution Guide.
I found out about contributing to Docs because I'm currently taking the learn git course.
