### ISSUE TITLE
[Edit] C: Pointers

### ISSUE THREAD

**Issue by Sriparno08** [Codecademy/docs#5003]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

We would like to edit the `Pointers` concept entry under C. The entry lives in `content/c/concepts/pointers/pointers.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Fix the last code example to get the desired output

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Sriparno08** [comment]
Hey @Alv4roVN, please claim this issue. It links to the PR opened by you (#4878).

**Comment by Alv4roVN** [comment]
I am claiming this issue.

**Comment by SaviDahegaonkar** [comment]
Hey @Alv4roVN,
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

Thanks  & Regards,
Savi
