### ISSUE TITLE
[Edit] Python: Operators

### ISSUE THREAD

**Issue by Sriparno08** [Codecademy/docs#5018]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

We would like to edit the `Operators` concept entry under Python. The entry lives in `content/python/concepts/operators/operators.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Change the return value of the `not in` operator under `Membership operators` from `False` to `True`

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Sriparno08** [comment]
Hey @fajardomike, please claim this issue. It links to the PR that you opened in the repository (#5010).

**Comment by fajardomike** [comment]
Hey @Sriparno08, could you please help me with this one? I am quite unsure of how to claim an issue.

**Comment by Sriparno08** [comment]
Hey @fajardomike, you can claim an issue by commenting something like 'I would like to work on this issue' and if you are the first one to claim it, you will be assigned to it.

Since you have already raised a PR for this issue, you just need to comment on this one to get assigned (which you have already done). So, you're assigned.

Note: Always claim and get assigned to an issue before working on it.

**Comment by fajardomike** [comment]
Got it! Thanks!
