### ISSUE TITLE
[Term Entry] Python random-module .choices()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5025]
### Reason/inspiration (optional)

We would like a new term entry on the `.choices()` method of the [`random-module`](https://www.codecademy.com/resources/docs/python/random-module) concept in Python. The entry should go in a new file under `docs/content/python/concepts/random-module/terms/choices/choices.md`

The entry should include the following:

- A description of the term
- A ##Syntax section that includes the syntax of the method and its details
- An ##Example section that includes a ```py ``` codeblock and ```shell ``` that shows the example output.
- A ##Codebyte Example to show the working of the method

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by sydnor** [comment]
Hi, I'd like to work on the issue. Thanks,

**Comment by mamtawardhani** [comment]
Hey @sydnor You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by sydnor** [comment]
so, i have spent over the last 8 yrs, being the student and teacher.  i just wanted to really understand and comprehend this profound technology.  I have been fortunate to be able to spend every waking hour learning, w/o having to work, however my main passion is Grapic Arts & thts how it strtd

and yes my first..... I have been all ovr the coding spectrum...so dont be deceived by those 8 yrs... I just wanted to code my own website, and here we are.   Thks for the warm welcome

**Comment by mamtawardhani** [comment]
@sydnor that is great! Waiting for your entry, good luck 😃

**Comment by mamtawardhani** [comment]
Unassigning author due to inactivity
