### ISSUE TITLE
[Term Entry] Python math-module math.radians()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5035]
### Reason/inspiration (optional)

We would like a new term entry on the `math.radians()` method of the [`math-module`](https://www.codecademy.com/resources/docs/python/math-module) concept in Python. The entry should go in a new file under `docs/content/python/concepts/math-module/terms/math-radians/math-radians.md`

The entry should include the following:

- A description of the term
- A ##Syntax section that includes the syntax of the method and its details
- An ##Example section that includes a ```py ``` codeblock and ```shell ``` that shows the example output.
- A ##Codebyte Example to show the working of the method

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by colinlsmatthews** [comment]
Hi, I would like to claim this issue.

**Comment by mamtawardhani** [comment]
Hey @colinlsmatthews I've assigned you to the `.degrees()` issue, do you want to take this up as well?

**Comment by colinlsmatthews** [comment]
Sure, I can take both.
