### ISSUE TITLE
[Edit] JavaScript Substring

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5037]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Substring` concept entry under JavaScript. The entry lives in `content/javascript/concepts/substring/substring.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a `Codebyte Example` section that provides a codebyte example demonstrating the concept in use
2) Ensure that the codebyte example is different than all the other examples in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by plumbae** [comment]
Hi, i would like to be assigned to this task. It's a part of my Codecademy full stack engineer course.

**Comment by mamtawardhani** [comment]
Hey @plumbae You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by plumbae** [comment]
Thank you very much. I will do my best :).
Yes, this is my first time contributing.
It's a part of the skill path in the Full stack engineer course to contribute.

**Comment by Samikshachari** [comment]
Hi, i would like to be assigned to this task.

**Comment by mamtawardhani** [comment]
Heey @Samikshachari, since this issue has already been taken by another author, you can look through the available issues [here](https://github.com/Codecademy/docs/issues) and let me know if anything interests you.
