### ISSUE TITLE
[Term Entry] PyTorch Tensors .mean()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5062]
### Reason/inspiration (optional)

Add a new term entry about the `.mean()` method for Tensors. Place your file under the file path `docs/content/pytorch/concepts/tensors/terms/mean/mean.md`

It should include the following sections:

- A "Syntax" section with a \```pseudo code block
- An "Example" section with a \```py code block

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by raheep06** [comment]
I want to take this one .

**Comment by mamtawardhani** [comment]
Hey @raheep06 You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by mamtawardhani** [comment]
@raheep06 unassigning you as dicussed

**Comment by deenovita** [comment]
Hello, may I get assigned to this issue? thank you

**Comment by SaviDahegaonkar** [comment]
Yes sure @deenovita,
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

Thanks  & Regards,
Savi
