### ISSUE TITLE
[Term Entry] PyTorch Tensors .view()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5063]
### Reason/inspiration (optional)

Add a new term entry about the `.view()` method for Tensors. Place your file under the file path `docs/content/pytorch/concepts/tensors/terms/view/view.md` 

It should include the following sections:

- A "Syntax" section with a \```pseudo code block
- An "Example" section with a \```py code block

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Sergio-Ottino** [comment]
Hi, I would like to work on this issue.

**Comment by mamtawardhani** [comment]
Hey @Sergio-Ottino You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by Sergio-Ottino** [comment]
Hello @mamtawardhani This is my first contribution. I'm taking a course called (journey) Using Linux.
I have the file ready to push but I am unable to access 'https://github.com/Codecademy/docs.git/':

**Comment by mamtawardhani** [comment]
> Hello @mamtawardhani This is my first contribution. I'm taking a course called (journey) Using Linux. I have the file ready to push but I am unable to access 'https://github.com/Codecademy/docs.git/':

Is it showing some error? If yes, could you please debrief? Because ideally you should be able to access it

**Comment by Sergio-Ottino** [comment]
yes @mamtawardhani 


C:\Users\SergioOttino\OneDrive - kyndryl\Documents\lssecfixes\GitHub\Codecademy\docs>git push origin tensors-view
remote: Permission to Codecademy/docs.git denied to Sergio-Ottino.
fatal: unable to access 'https://github.com/Codecademy/docs.git/': The requested URL returned error: 403

**Comment by mamtawardhani** [comment]
> yes @mamtawardhani
> 
> C:\Users\SergioOttino\OneDrive - kyndryl\Documents\lssecfixes\GitHub\Codecademy\docs>git push origin tensors-view remote: Permission to Codecademy/docs.git denied to Sergio-Ottino. fatal: unable to access 'https://github.com/Codecademy/docs.git/': The requested URL returned error: 403

Ah! I suppose you are pushing it on the main branch, make sure you first fork the docs repository to your GitHub account, then also create a feature branch. These two are very essential and I'm guessing the issue is due to these. You can once have a look at the Contribution Guide shared in the above comment and let me know if that worked. 😃

**Comment by mamtawardhani** [comment]
Unassigning as author is inactive
