### ISSUE TITLE
[Topic Entry] Python math-module math.isnan()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5086]
### Reason/inspiration (optional)

We would like a new term entry on the `math.isnan()` method of the [`math-module`](https://www.codecademy.com/resources/docs/python/math-module) concept in Python. The entry should go in a new file under `docs/content/python/concepts/math-module/terms/math-isnan/math-isnan.md`

The entry should include the following:

- A description of the term
- A ##Syntax section that includes the syntax of the method and its details
- An ##Example section that includes a ```py ``` codeblock and ```shell ``` that shows the example output.
- A ##Codebyte Example to show the working of the method

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by NelsonSanti** [comment]
Hello,
I would like to work on this issue. It will be my second one.
Is it possible?
Thank you

**Comment by SaviDahegaonkar** [comment]
Hey @NelsonSanti ,
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Thanks  & Regards,
Savi

**Comment by SaviDahegaonkar** [comment]
Hello @NelsonSanti,
Thanks for your contribution🤩. The PR will get merged as soon as it goes through a couple of reviews on it. The reviewer will let you know if any changes are required.

Thanks,
Savi

**Comment by NelsonSanti** [comment]
Thank you for your feedback @SaviDahegaonkar 🙂👍

**Comment by Hajar-El-Mhassani** [comment]
I am interesting in this
