### ISSUE TITLE
[Edit] Golang Strings

### ISSUE THREAD

**Issue by mamtawardhani** [Codecademy/docs#5090]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

We would like to edit the `.cutsuffix()` term entry under the strings concept in Golang. The entry lives in `content/go/concepts/strings/terms/cutsuffix/cutsuffix.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:

Correct the output of the example code given in the entry. 

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by mamtawardhani** [comment]
Hey @MarkFarmiloe raised an issue for your PR here. Let me know once you see this.

**Comment by mamtawardhani** [comment]
Hey @MarkFarmiloe please comment here so that I can assign the issue to you.

**Comment by MarkFarmiloe** [comment]
Impressed you spotted the other typo while checking my contribution.
Do you need me to do anything else?

**Comment by mamtawardhani** [comment]
No that is it, thank you @MarkFarmiloe. Will get your entry merged ASAP. 🚀
