### ISSUE TITLE
[Concept Entry] Sklearn clustering

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5114]
### Reason/inspiration (optional)

We would like a new entry on the `Clustering` concept under Sklearn. The entry should go in a new file under `docs/content/sklearn/concepts/clustering/clustering.md`.

The entry should include:

- An introduction to the concept
- A `Syntax` section that provides the syntax for the concept (if applicable)
- An `Example` section that provides an example demonstrating the concept in use (if applicable)
- A `Codebyte Example` section that provides a codebyte example demonstrating the concept in use (if applicable)

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Amirhosa** [comment]
Hi, i would like to work on this issue, thank you.

**Comment by Neema-Joju** [comment]
Hi,
I would like to attempt this. This would be my third time contributing to this repo.

**Comment by mamtawardhani** [comment]
Hey @Neema-Joju 
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

**Comment by Neema-Joju** [comment]
Hi @mamtawardhani ,
Clustering in sklearn is a very large topic. There are around 12 algorithms individually to be discussed. Should all 12 algorithms have a codebyte and example or is discussing the theory sufficient?. I haven't seen any other examples on this case.

**Comment by mamtawardhani** [comment]
> Hi @mamtawardhani , Clustering in sklearn is a very large topic. There are around 12 algorithms individually to be discussed. Should all 12 algorithms have a codebyte and example or is discussing the theory sufficient?. I haven't seen any other examples on this case.

No, for those 12 we will have separate term entries. For this you can give a generic explanation of clustering and an example and codebyte of your choice, chose any of the clustering algorithm
