### ISSUE TITLE
[Term Entry] Python built-in functions slice()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5117]
### Reason/inspiration (optional)

We would like a new term entry on the `slice()` built-in function in Python. The entry should go in a new file under `docs/content/python/concepts/built-in-functions/terms/slice/slice.md`

The entry should include the following:

- A description of the term
- A ##Syntax section that includes the syntax of the method and its details
- An ##Example section that includes a ```py ``` codeblock and ```shell ``` that shows the example output.
- A ##Codebyte Example to show the working of the method

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by aSagCoder** [comment]
Hi, I'd love to try working on this!

**Comment by SaviDahegaonkar** [comment]
Hey @aSagCoder,
 I have already assigned you one more issue, I would like to know if you still want to work on this, then I will assign you this issue

Thanks,
Savi

**Comment by SaviDahegaonkar** [comment]
Hello @aSagCoder, I want to know if you still want to work on this issue.

**Comment by aSagCoder** [comment]
Hey there, I'm still interested in working on this issue if it's okay.

**Comment by SaviDahegaonkar** [comment]
Hello @aSagCoder,
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Thanks  & Regards,
Savi

**Comment by aSagCoder** [comment]
Hi there, I have created a PR request with the term entry here - #5278.
