### ISSUE TITLE
[Term Entry] Swift dictionaries subscript

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5119]
### Reason/inspiration (optional)

"We would like a new term entry on the `subscript` for Dictionaries in Swift. The entry should go in a new file under `content/swift/concepts/dictionaries/terms/subscript/subscript.md`
The entry should include the following:

- A description of the term
- A ##Syntax section that includes the syntax of the method and its details
- An ##Example section that includes a ```swift ``` codeblock and ```shell ``` that shows the example 
- Explain how to Access a Value, Update a Value and Remove a Value

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by arisdelacruz** [comment]
i'll take this one

thanks

**Comment by SaviDahegaonkar** [comment]
Hello @arisdelacruz ,
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Thanks  & Regards,
Savi

**Comment by arisdelacruz** [comment]
@SaviDahegaonkar thanks
