### ISSUE TITLE
[Term Entry] Swift dictionaries keys()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5121]
### Reason/inspiration (optional)

"We would like a new term entry on the `keys` for Dictionaries in Swift. The entry should go in a new file under `content/swift/concepts/dictionaries/terms/keys/keys.md`
The entry should include the following:

- A description of the term
- A ##Syntax section that includes the syntax of the method and its details
- An ##Example section that includes a ```swift ``` codeblock and ```shell ``` that shows the example 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Great-Visions-Code** [comment]
Would love to take this. Currently doing the iOS Developer course here. This would be my 3rd contribution. 
Thank you.

**Comment by SaviDahegaonkar** [comment]
Hello @Great-Visions-Code,
I have already assigned you an issue. I would like to know if you still are comfortable with working on multiple issues at a time.

**Comment by Great-Visions-Code** [comment]
@SaviDahegaonkar Hi Savi! Yes, I'm sure I can handle it. Please assign and I'll work on both and submit a PR within a few days. Thank you.

**Comment by Great-Visions-Code** [comment]
Great! Thank you!

**Comment by Great-Visions-Code** [comment]
@SaviDahegaonkar PR submitted. 

Thank you,
Gus
