### ISSUE TITLE
[Term Entry] Swift dictionaries forEach

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5124]
### Reason/inspiration (optional)

"We would like a new term entry on the `forEach` for Dictionaries in Swift. The entry should go in a new file under `content/swift/concepts/dictionaries/terms/forEach/forEach.md`
The entry should include the following:

- A description of the term
- A ## Syntax section that includes the syntax of the method and its details
- An ## Example section that includes a ```swift ``` codeblock and ```shell ``` that shows the example 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Johnnie-kay** [comment]
Hello @codecademy-docs, this one too. Please assign it to me

**Comment by SaviDahegaonkar** [comment]
Hey @Johnnie-kay ,
I have already assigned you an issue, Are you sure if I should assign too to you?

**Comment by SaviDahegaonkar** [comment]
Hello @Johnnie-kay ,
I am curious if you are still interested in taking this issue. If yes, I will assign this to you.

**Comment by Amirhosa** [comment]
hello @codecademy-docs  ,
 I'd like to work on this issue

**Comment by mamtawardhani** [comment]
Hey @Amirhosa You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by Amirhosa** [comment]
@mamtawardhani yes it is, it was a project in learn git and github course.
