### ISSUE TITLE
[Term Entry] Swift sets isEmpty()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5125]
### Reason/inspiration (optional)

"We would like a new term entry on the `isEmpty` for Sets in Swift. The entry should go in a new file under `content/swift/concepts/sets/terms/isEmpty/isEmpty.md`
The entry should include the following:

- A description of the term
- A ## Syntax section that includes the syntax of the method and its details
- An ## Example section that includes a ```swift ``` codeblock and ```shell ``` that shows the example 

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Johnnie-kay** [comment]
Hello @codecademy-docs, I am interested in working on this issue to close it. please assign it to me.

**Comment by SaviDahegaonkar** [comment]
Hey @Johnnie-kay,

You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Thanks  & Regards,
Savi

**Comment by flo-olhn** [comment]
Hello,
I am looking to contribute to the doc (following the iOS Developer career path), and have found that this issue is still unresolved.
I would like to work on it, so let me know if you have any news.

Regards,
Florian

**Comment by SaviDahegaonkar** [comment]
Hey @Johnnie-kay,
Are you still working on this issue?
