### ISSUE TITLE
[Edit] JavaScript Try/Catch

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5128]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Try/Catch` concept entry under JavaScript. The entry lives in `content/javascript/concepts/try-catch/try-catch.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a `Codebyte Example` section that provides a codebyte example demonstrating the concept in use
2) Ensure that the codebyte example is different than all the other examples in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by bryantigwebuike** [comment]
Hi, please I would like to work on this issue. This is my first contribution and I learnt about codecademy docs from the front-end engineering path on codecademy.
