### ISSUE TITLE
[Edit] Subject: Error in docs example (C# methods)

### ISSUE THREAD

**Issue by iwarra** [Codecademy/docs#5143]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

The example provided returns an integer while the comment says it returns an object:

// Declare a public method which returns an object and takes an input parameter:
public int CalculateWithParameter(int x)

Link: https://www.codecademy.com/resources/docs/c-sharp/methods

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [X] Issue is assigned

**Comment by iwarra** [comment]
Would like to be assigned to this one, please. :)

**Comment by SaviDahegaonkar** [comment]
Hello @iwarra ,
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

Thanks  & Regards,
Savi

**Comment by iwarra** [comment]
Hi @SaviDahegaonkar, that is great, thanks for the info! 🎉 
It is my first contribution to Codecademy Docs. I noticed the error and saw the "Edit this page on GitHub to fix an error ..." link at the bottom of the article and thought why not. 🙂
