### ISSUE TITLE
[Concept Entry] Creating Custom function in MySQL

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5155]
### Reason/inspiration (optional)

We would like a new entry on the `Creating custom function` in SQL. The entry should go in a new file under `docs/content/sql/concepts/custom-function/custom-function.md`.

  
The entry should include:

- An introduction to the concept

- A `Syntax` section that provides the syntax for how to creating a custom function

- An `Example` section that provides an example demonstrating how to creating a custom function

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by AdiSol** [comment]
Hi! Can I be assigned to this issue? This is my first time contributing and I am coming from the "Learn Git & Github" course.
