### ISSUE TITLE
[Concept Entry] TRUCATE in SQL

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5162]
### Reason/inspiration (optional)

We would like a new entry on the `TRUCATE` concept in SQL. The entry should go in a new file under `docs/content/sql/concepts/commands/terms/trucate/trucate.md`.      
      
The entry should include:
     
- An introduction to the concept     
     
- A `Syntax` section that provides the syntax for the concept (if applicable)     
     
- An `Example` section that provides an example demonstrating the concept in use (if applicable)     
     
Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by JonAdams99** [comment]
i would really like to work on this issue. Thanks

**Comment by SaviDahegaonkar** [comment]
Hey @JonAdams99 , 
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

Thanks  & Regards,
Savi

**Comment by dejongbaba** [comment]
Hello, seems this issue has not been closed yet, would love to pick it up @SaviDahegaonkar

**Comment by mamtawardhani** [comment]
Unassigning the current author due to inactivity.

@dejongbaba would you still like to pick up this issue?

**Comment by dejongbaba** [comment]
> Unassigning the current author due to inactivity.
> 
> @dejongbaba would you still like to pick up this issue?

Yes Would very much like to pick it up
