### ISSUE TITLE
[Concept Entry] SQL ROLLBACK

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5168]
### Reason/inspiration (optional)

We would like a new entry on the `ROLLBACK` concept in SQL. The entry should go in a new file under `docs/content/sql/concepts/commands/terms/rollback/rollback.md`.    

The entry should include:

- An introduction to the concept   

- A `Syntax` section that provides the syntax for the concept (if applicable)   

- An `Example` section that provides an example demonstrating the concept in use (if applicable)   

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by davialano** [comment]
I would like to work on this

**Comment by mamtawardhani** [comment]
Hey @davialano you have already been assigned to one issue, do you want to work on this as well?

**Comment by davialano** [comment]
Hi @mamtawardhani, I can leave this issue for somebody interested.

**Comment by SaviDahegaonkar** [comment]
Hey @davialano, You can work on this issue if you are comfortable working on both issues.

**Comment by SaviDahegaonkar** [comment]
Hey @judygitsthejobdone ,
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

Thanks  & Regards,
Savi

**Comment by judygitsthejobdone** [comment]
> Hey @judygitsthejobdone , You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.
> 
> Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.
> 
> Thanks & Regards, Savi

Thanks, Savi!
Yes, it's my first contribution. I am learning about it through the Learn Git & GitHub course on codecademy.
-Judah
