### ISSUE TITLE
[Term Entry] Python Plotly - express .scatter_3d()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5169]
### Reason/inspiration (optional)

We would like a new term entry on the `.scatter_3d()` method of the [`express module`](https://www.codecademy.com/resources/docs/plotly/express) in Plotly, Python. The entry should go in a new file under `docs/content/plotly/concepts/express/terms/scatter_3d/scatter_3d.md`

The entry should include the following:

- A description of the term
- A ##Syntax section that includes the syntax of the method and its details
- An ##Example section that includes a ```py ``` codeblock and ```shell ``` that shows the example output.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by mamtawardhani** [comment]
Hey @pritamjr Kinly comment on this issue so that this can be assigned to you.

For future references, please note that you have to ask to be assigned to an issue, once assigned only then you can submit a PR.
Thank you. 😃

**Comment by pritamjr** [comment]
So sorry @mamtawardhani. I am new to open-source. Would keep in mind next time. So can I be assigned issue #5169?

**Comment by mamtawardhani** [comment]
No problem @pritamjr 😃 
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by pritamjr** [comment]
Yes, this is my first time contributing to Codecademy Docs. I found out about contributing to Docs by accident. I was searching through Github to find repos that welcomed contributions for their issues.
