### ISSUE TITLE
[Term Entry] Python Plotly - express .sunburst()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5173]
### Reason/inspiration (optional)

We would like a new term entry on the `.sunburst()` method of the [`express module`](https://www.codecademy.com/resources/docs/plotly/express) in Plotly, Python. The entry should go in a new file under `docs/content/plotly/concepts/express/terms/sunburst/sunburst.md`

The entry should include the following:

- A description of the term
- A ##Syntax section that includes the syntax of the method and its details
- An ##Example section that includes a ```py ``` codeblock and ```shell ``` that shows the example output.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Pharaoh1257** [comment]
I would like to take on this issue, found on the Codecademy docs.

**Comment by mamtawardhani** [comment]
Unassigning author due to inactivity
