### ISSUE TITLE
[Edit] Markdown: Paragraphs

### ISSUE THREAD

**Issue by word-wiz** [Codecademy/docs#5190]
### Type of Edit (select all that apply)

Clarify unclear content and/or terms, Add new content (definitions, codeblocks, etc.)

### Description (optional)

I think it would be helpful to differentiate between single and double line breaks in the **Line breaks** section, and add that a double space at the end of the line will also create a single line break.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by word-wiz** [comment]
I would like to tackle this

**Comment by SaviDahegaonkar** [comment]
Hey @word-wiz ,
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

Thanks  & Regards,
Savi
