### ISSUE TITLE
[Entry] CSS : Anatomy

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#525]
### Reason/inspiration (optional)

Write an entry about the anatomy of CSS, including:

- What a ruleset is and what it is made of.
- What are inline styles and what do they look like?
- Code snippet examples and images of diagrams would be helpful.

Use this Codecademy lesson as a guide: https://www.codecademy.com/courses/learn-css/lessons/learn-css-setup-and-syntax/exercises/css-anatomy

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
@Dusch4593, I'll take this one.
