### ISSUE TITLE
[Term Entry] HTML Tags:`<q>`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#526]
### Reason/inspiration (optional)

For [the HTML tags](https://www.codecademy.com/resources/docs/html/tags), write a term entry about the `<q>` element, including:

- Used for short, inline quotations.
- Its `cite` attribute and what it is used for.
- One "Syntax" section and one "Example" section.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Antonio-Riccelli** [comment]
Hi @Dusch4593, 
I see this has been open for a while, but no assignees. Could I contribute?

**Comment by Dusch4593** [comment]
Hey @Antonio-Riccelli, you're now assigned! 😄
