### ISSUE TITLE
[Term Entry] Python Built-in Methods: `open()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#527]
### Reason/inspiration (optional)

Write a term entry for the `open()` file method in Python and include the following information:

- A brief "## Syntax" section with a few brief sentences and supporting code snippet.
- A concise breakdown of the different modes Python can apply to files with `open()`:
  - `r` - read a file
  - `w` - write to a file
  - `a` - append a file
  - `x` - create a file

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by KTom101** [comment]
@Dusch4593 perhaps the first half of [PR #516 ](https://github.com/Codecademy/docs/pull/516/files) could resolve this?

**Comment by Dusch4593** [comment]
@shiningflutes is working on this issue.
