### ISSUE TITLE
[Bug/Error] Python version described in the document "GitHub Actions & Tutorial On Automated Testing" gives error

### ISSUE THREAD

**Issue by adnanfaisal** [Codecademy/docs#5276]
### Actual Behavior

In the **Learn Git and GitHub** course, in the topic titled **GitHub Actions & Tutorial On Automated Testing** (https://www.codecademy.com/courses/learn-git/articles/github-actions-tutorial-on-automated-testing), there is an example `yaml` file namely `unittests.yaml`. It mentions `python-version: 3.10.0`. But, if the workflow is run with this version, the following error is encountered. 

>**Build**: Version 3.10.0 with arch x64 not found The list of all available versions can be found here: >https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

*(The error seems to be due to this bug: https://github.com/actions/setup-python/issues/401)*

However, if Python version number is updated (for example to `3.12.0`), the workflow runs perfectly. 

### Expected Behavior

The `unittests.yaml` file should specify a version of Python (for example, `3.12.0`) that works without any error. 

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by adnanfaisal** [comment]
If the bug report is valid, could you kindly assign it to me?

**Comment by mamtawardhani** [comment]
This seems an invalid issue because this refers to an article. Issues are created for entries inside docs (new or edit entries)
 @Sriparno08 am I correct, your insights will be helpful.

**Comment by Sriparno08** [comment]
Yeah @mamtawardhani, you're correct. Since this issue refers to an article, it is invalid for this repository.

**Comment by mamtawardhani** [comment]
Thank you @Sriparno08 
@adnanfaisal since this issue is not related to docs, I'll have to close it. Thank you! 😃
