### ISSUE TITLE
[Edit] Learn Git & GitHub: Python version described in the document "GitHub Actions & Tutorial On Automated Testing" gives error

### ISSUE THREAD

**Issue by adnanfaisal** [Codecademy/docs#5279]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

In the Learn **Git and GitHub** course, in the topic titled **GitHub Actions & Tutorial On Automated Testing** (https://www.codecademy.com/courses/learn-git/articles/github-actions-tutorial-on-automated-testing), there is an example `yaml` file namely `unittests.yaml`. It mentions `python-version: 3.10.0`. But, if the workflow is run with this version, the following error is encountered.

>Build: Version 3.10.0 with arch x64 not found The list of all available versions can be found here: >https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

*(The error seems to be due to this bug: https://github.com/actions/setup-python/issues/401)*

However, if Python version number is updated (for example to `3.12.0`), the workflow runs perfectly.

So, the Python version number in the file `unittests.yaml` file should be corrected.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by adnanfaisal** [comment]
Hello, if approved, please assign to me. I would like to work on this.

**Comment by Brodes4JC** [comment]
I think it might depend on the version of Python loaded on the local system from which the course is being taken. So perhaps that should be clarified by the course page.

**Comment by SaviDahegaonkar** [comment]
Hey @adnanfaisal ,
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

Thanks  & Regards,
Savi

**Comment by SaviDahegaonkar** [comment]
> I too encountered this same Issue. I changed the version to 3.12.6 and it worked.

You can take another issue, we will assign the issue to you. Please comment on the issue so we can assign it.

**Comment by adnanfaisal** [comment]
> Hey @adnanfaisal , You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.
 
Thanks, @SaviDahegaonkar! 




> Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

Yes, it is my first contribution. I came to know about it from Codecademy's Git & GitHub course.

**Comment by SaviDahegaonkar** [comment]
Hello @adnanfaisal ,
Thank you for your contribution. You can write the PR and get it reviewed. You can reach out to me in case you have any concerns regarding this issue.

Thanks,
Savi

**Comment by adnanfaisal** [comment]
Hi @SaviDahegaonkar, thank you! 

Now my problem is - the issue is not in Codecademy's *public doc* about **Git** (https://www.codecademy.com/resources/docs/git), but it is in Codecademy's **Learn Git & GitHub** *course*: https://www.codecademy.com/enrolled/courses/learn-git. Can you kindly help me find the right repo to fork?

Best regards,
Adnan

**Comment by minisha1212** [comment]
@SaviDahegaonkar can I work on this issue?

**Comment by mamtawardhani** [comment]
@SaviDahegaonkar Kindly check this as per our discussion and close the issue at the earliest.

**Comment by mamtawardhani** [comment]
Hey @adnanfaisal this is not a valid issue as it tends to change an article and not a docs entry. However, thank you for highlighting this, I"ll get this checked. 
Thank you, closing this issue! 😄
