### ISSUE TITLE
[Term Entry] HTML Tags : `<picture>`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#529]
### Reason/inspiration (optional)

Write a term entry about the `<picture>` HTML tag, including:

- Brief "Syntax" and "Example" sections.
- Some of its use-cases (art direction, page load time optimization, etc.)
- How the `<source>` and `<img>` elements function within a `<picture>` element.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by denisCabrera** [comment]
Hi, I see this has been open for a bit, can I have a go at it ?
