### ISSUE TITLE
[Bug/Error] Java Map: .replaceAll()

### ISSUE THREAD

**Issue by avdhoottt** [Codecademy/docs#5291]
### Actual Behavior

The folder and file names is `replace` and `replace.md` inside `content/java/concepts/map/terms/replace/replace.md`.

### Expected Behavior

The folder and file names should be `replaceAll` and `replaceAll.md`.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by RaviRanjan-03** [comment]
I am interested in taking this issue on, I found out about docs through friends.

**Comment by mamtawardhani** [comment]
Hey @AKASHYADAVO @RaviRanjan-03 is any of you still interested in taking up this issue?

**Comment by tommaso-berti** [comment]
Good afternoon, I wold like to fix this issue. Its my first contribute issue for the Codecademy course.

**Comment by friskycodeur** [comment]
Hi, I would like to take this item up, if it is it is still claimable/pending. 
Thanks
