### ISSUE TITLE
[Entry] C++ : Errors

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#530]
### Reason/inspiration (optional)

Write a C++ concept entry about errors, including:

- Brief "Syntax" and "Example" sections with supporting text and code snippets.

- The general error-classifications, such as:
  - Syntax errors
  - Compile-time errors
  - Link-time errors
  - Run-time errors
  - Logic errors

Note: Don't talk too much about exceptions. We already have [an entry for that](https://www.codecademy.com/resources/docs/cpp/exceptions)! 😃 

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by KTom101** [comment]
@Dusch4593 I'll work on this one!

**Comment by Dusch4593** [comment]
Thank you!
