### ISSUE TITLE
[Term Entry] Kotlin Arrays .arrayOfNulls()

### ISSUE THREAD

**Issue by codecademy-gh-api** [Codecademy/docs#5310]
### Reason/inspiration (optional)

We would like a new term entry on the `arrayOfNulls` under the 'Arrays` concept on Koltin. The entry should go in a new file under `content/kotlin/concepts/arrays/terms/arrayOfNulls/arrayOffNulls.md`.

The entry should include:

- An introduction to the term
- A `Syntax` section that provides the syntax for the concept (if applicable)
- An `Example` section that provides an example demonstrating the concept in use (if applicable)

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by austinwdigital** [comment]
Hello 🙂
Can I be assigned to this issue please?

**Comment by mamtawardhani** [comment]
Hey @austinwdigital You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by austinwdigital** [comment]
Hi @mamtawardhani! 🙂
Thank you for assigning the issue to me. I am reviewing the Contribution Guide and will create a PR shortly.

This is my first contribution to Codecademy Docs. Hacktoberfest pointed me to "good first issues" and I was excited to see Codecademy had some good first issues open.
