### ISSUE TITLE
[Concept Entry] C++ Deque Deque

### ISSUE THREAD

**Issue by codecademy-gh-api** [Codecademy/docs#5313]
### Reason/inspiration (optional)

We would like a new entry on the `Deque` in C++. The entry should go in a new file under `docs/content/cpp/concepts/deque/deque.md`.       
  
The entry should include:      
  
- An introduction to the concept      
- A `Syntax` section that provides the syntax for the concept (if applicable)      
- An `Example` section that provides an example demonstrating the concept in use (if applicable)     
 - An `Codebyte Example` section that provides an example demonstrating how to use deque
 
Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.|

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by ultralegendary** [comment]
hey @codecademy-gh-api , can you assign this to me

**Comment by mamtawardhani** [comment]
Unassigning author due to inactivity

**Comment by SaviDahegaonkar** [comment]
Hey @mamtawardhani, I took this issue for raising the PR and I think a [PR](https://github.com/Codecademy/docs/pull/5325) has already been raised on the same [issue](https://github.com/Codecademy/docs/issues/4453). Can you please check on this?

**Comment by codecademy-docs** [comment]
Closing this issue as a PR has already been raised for it.
