### ISSUE TITLE
[Term Entry] Kotlin Arrays slice

### ISSUE THREAD

**Issue by codecademy-gh-api** [Codecademy/docs#5322]
### Reason/inspiration (optional)

We would like a new term entry on the `slice` under the 'Arrays` concept on Koltin. The entry should go in a new file under `content/kotlin/concepts/arrays/terms/slice/slice.md`.

The entry should include:

- An introduction to the term
- A `Syntax` section that provides the syntax for the concept (if applicable)
- An `Example` section that provides an example demonstrating the concept in use (if applicable)

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Manish-Giri** [comment]
@dakshdeepHERE Can I take this up?

**Comment by mamtawardhani** [comment]
Hey @Manish-Giri You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

**Comment by Manish-Giri** [comment]
@mamtawardhani Thank you, will have the PR up shortly

**Comment by mamtawardhani** [comment]
Unassigned author due to inactivity
