### ISSUE TITLE
[Term Entry] Python:NumPy built-in-functions trace

### ISSUE THREAD

**Issue by codecademy-gh-api** [Codecademy/docs#5323]
### Reason/inspiration (optional)

We would like a new term entry on the `built-in-functions` term for [Numpy](https://www.codecademy.com/resources/docs/numpy): matrix trace. The entry should go in a new file under `docs/content/numpy/concepts/built-in-functions/terms/trace/trace.md`.

The entry should describe the term and how it is used within statistical analysis. Also include: 
- An "Example" section that explains readers how to use the trace function to find the trace of a square matrix.
- Should contain informations for functions and syntax.
- Should have a python codebyte with working code snippet showcasing this function.
Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by NelsonSanti** [comment]
Hello @codecademy-docs ,
Can i work on this? 
Would be my 5th contribution
Thank you

**Comment by SaviDahegaonkar** [comment]
Hey @NelsonSanti ,
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

Thanks  & Regards,
Savi

**Comment by cigar-galaxy82** [comment]
Hi we already have an entry for this

**Comment by NelsonSanti** [comment]
Hello,

So should I ignore this? @cigar-galaxy82  and @SaviDahegaonkar

**Comment by NelsonSanti** [comment]
Hello @codecademy-docs . I will assume that I should not proceed with this.
If this is true, please unassign me.
Thank you guys

**Comment by mamtawardhani** [comment]
> Hello @codecademy-docs . I will assume that I should not proceed with this. If this is true, please unassign me. Thank you guys

Sorry for the inconvenience caused @NelsonSanti. Closing this issue
