### ISSUE TITLE
[Term Entry] PyTorch Tensors .cat()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5350]
### Reason/inspiration (optional)

We would like a new entry on the `.cat()` term under PyTorch. The entry should go in a new file under `docs/content/pytorch/concepts/tensors/terms/cat/cat.md`.

The entry should include:

- An introduction to the concept
- A `Syntax` section that provides the syntax for the concept
- An `Example` section that provides an example demonstrating the concept in use

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by arisdelacruz** [comment]
Can i take this one? Thanks

**Comment by mamtawardhani** [comment]
Hey @arisdelacruz You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

**Comment by arisdelacruz** [comment]
@mamtawardhani 

Can you help me with this?

**Comment by arisdelacruz** [comment]
![image](https://github.com/user-attachments/assets/e294a467-241a-448a-8c88-2fa5cae46ea1)

**Comment by arisdelacruz** [comment]
![image](https://github.com/user-attachments/assets/e5da4652-fd31-48b2-8d6b-f9560567e6ca)

**Comment by arisdelacruz** [comment]
I think I made a wrong pull?

Thanks

**Comment by mamtawardhani** [comment]
> I think I made a wrong pull?
> 
> Thanks

Thats correct, looks like you created a PR on the original Repo. A PR needs to be created on the "Forked repo" and then merged into the main Codecademy docs repo.
You will have to raise a PR again for this. Just make sure you raise it from your forked repo 😃
