### ISSUE TITLE
[Term Entry] C++ Maps .Size()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5353]
### Reason/inspiration (optional)

We would like a new entry on the `.size()` term under Maps in C++. The entry should go in a new file under `docs/content/cpp/concepts/maps/terms/size/size.md`.  
  
The entry should include:  
  
- An introduction to the concept  
- A `Syntax` section that provides the syntax for the concept  
- An `Example` section that provides an example demonstrating the concept in use  
- A `Codebyte Example` section that provides a codebyte example demonstrating the concept in use  
  
Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by RashmitTopG** [comment]
I would like to work on this issue. Can you assign it to me ??

**Comment by dejongbaba** [comment]
Can I pick this up ?

**Comment by jvara34** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by Sriparno08** [comment]
Closing this as it is a duplicate issue.
