### ISSUE TITLE
[Term Entry] C++ Deque Insert()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5358]
### Reason/inspiration (optional)

We would like a new entry on the `.insert()` term under Deque in C++. The entry should go in a new file under `docs/content/cpp/concepts/deque/terms/insert/insert.md`.  
  
The entry should include:  
  
- An introduction to the concept  
- A `Syntax` section that provides the syntax for the concept  
- An `Example` section that provides an example demonstrating the concept in use  
- A `Codebyte Example` section that provides a codebyte example demonstrating the concept in use  
  
Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Cibiyanna26** [comment]
Hey @codecademy-docs I am a contributor from HacktoberFest and would you assign this issue to me, I would like to work on this issue.

**Comment by mamtawardhani** [comment]
Hey @Cibiyanna26 you have already been assigned to an issue, would you like to work on this as well?

**Comment by Cibiyanna26** [comment]
Yeah sure @mamtawardhani, after completing #5362, I would like to work on this.

**Comment by Cibiyanna26** [comment]
Sorry for troubling you @mamtawardhani, I am a contributor from Hacktobest, so the event has mentioned to add labels 'hacktoberfest', 'hacktoberfest-accepted' to the issues which being assigned.

**Comment by mamtawardhani** [comment]
Hey @Cibiyanna26 no problem, and yes let me check this and get back to you ASAP.
Until then, let me know whenever you wish to work on this

**Comment by Cibiyanna26** [comment]
I wish to work on this issue👍

**Comment by Cibiyanna26** [comment]
@mamtawardhani would you assign this issue to me, I am free to work on this issue now.

**Comment by mamtawardhani** [comment]
Hey @Cibiyanna26 You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

**Comment by Cibiyanna26** [comment]
@mamtawardhani thanks!

**Comment by Cibiyanna26** [comment]
@mamtawardhani I have raised the pr for this issue #5438, please do review the pr and notify me if there are any changes to be done, thanks,
