### ISSUE TITLE
[Term Entry] C++ Deque .push_back()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5362]
### Reason/inspiration (optional)

"We would like a new entry on the `.push_back()` term under Deque in C++. The entry should go in a new file under `docs/content/cpp/concepts/deque/terms/push-back/push-back.md`.  
  
The entry should include:  
  
- An introduction to the concept  
- A `Syntax` section that provides the syntax for the concept  
- An `Example` section that provides an example demonstrating the concept in use  
- A `Codebyte Example` section that provides a codebyte example demonstrating the concept in use  
  
Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Cibiyanna26** [comment]
@codecademy-docs I am a contributor from HacktoberFest and I would like to work on this issue.

**Comment by SaviDahegaonkar** [comment]
Hey @Cibiyanna26 ,
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

Thanks  & Regards,
Savi

**Comment by Cibiyanna26** [comment]
Yes, This is my first time contribution to Codeacademy Docs, I found about Codeacademy through hacktoberfest.

**Comment by Cibiyanna26** [comment]
@SaviDahegaonkar could you tell me how to run the project in our local machine ?

**Comment by mamtawardhani** [comment]
> @SaviDahegaonkar could you tell me how to run the project in our local machine ?

Hey @Cibiyanna26 refer to this [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide), it has videos to guide you through the process of running project on your local machine and how to submit the pull request

**Comment by Cibiyanna26** [comment]
Hi @mamtawardhani, I have completed the work, added .push_back() in deque topic. Will raise the pr.

**Comment by mamtawardhani** [comment]
Yes, you will have to raise a pr from the forked branch itself

**Comment by Cibiyanna26** [comment]
@mamtawardhani Raised the pr.
