### ISSUE TITLE
[Edit] Python:NumPy NumPy - Built-in-functions - `.log()`

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5373]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `.log()` term entry under NumPy. The entry lives in `content/numpy/concepts/built-in-functions/terms/log/log.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) guide when working on the PR for this issue.

Please:

1. Add a ## Codebyte Example section that provides a codebyte example demonstrating the concept in use
2. Ensure that the codebyte example is different than all the other examples in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by Manish-Giri** [comment]
Since the issue is still unclaimed, can I take it up? This is not my first contribution though (in the interest of disclosure!).

**Comment by mamtawardhani** [comment]
Hey @Manish-Giri You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

**Comment by Manish-Giri** [comment]
@mamtawardhani Thank you! PR - https://github.com/Codecademy/docs/pull/5532
