### ISSUE TITLE
[Edit] Python:NumPy NumPy - Built-in-functions - `.reshape()`

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5374]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `.reshape()` term entry under NumPy. The entry lives in `content/numpy/concepts/built-in-functions/terms/reshape/reshape.md`

- Add a ##Codebyte Example block to the entry
- Make sure it is different than the rest of the examples in the entry

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) guide when working on the PR for this issue.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by NelsonSanti** [comment]
Hello @codecademy-docs 
Can i take this one?
It is my 6th I guess

**Comment by mamtawardhani** [comment]
Hey @NelsonSanti You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.
