### ISSUE TITLE
[Edit] JavaScript Try/Catch

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5377]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Try/Catch` concept entry under JavaScript. The entry lives in `content/javascript/concepts/try-catch/try-catch.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) guide when working on the PR for this issue.

Please:

1. Shorten the description of the concept to not more than 160 characters
2. Fix any typo in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by aparna-u** [comment]
Please assign this issue to me.

**Comment by mamtawardhani** [comment]
Unassigning author due to inactivity

**Comment by mamtawardhani** [comment]
Hey @Anshgrover23 You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by mamtawardhani** [comment]
@Anshgrover23 are you still working on this?

**Comment by Anshgrover23** [comment]
@mamtawardhani no, you can unassigning as i am busy with some other stuff can't manage time.
