### ISSUE TITLE
[Edit] JavaScript Switch

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5379]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Switch` concept entry under JavaScript. The entry lives in `content/javascript/concepts/switch/switch.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) guide when working on the PR for this issue.

Please:

1. Shorten the description of the concept to not more than 160 characters
2. Fix any typo in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by ChinoUkaegbu** [comment]
Hi, I'd like to work on this!

**Comment by SaviDahegaonkar** [comment]
Hey @ChinoUkaegbu,
You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by ChinoUkaegbu** [comment]
Yes, this will be my first contribution! I took the Phaser.js course on Codecademy and wanted to contribute to docs as well.
