### ISSUE TITLE
[Edit] Subject : Git

### ISSUE THREAD

**Issue by aedwardg** [Codecademy/docs#538]
### Type of Edit (select all that apply)

Fix grammar, spelling, Clarify unclear content and/or terms, Add new content (definitions, codeblocks, etc.)

### Description (optional)

There are several incorrect, incomplete or unclear areas in the Git content.
This issue is to edit/update those.  No new Git concepts to be added as part of this issue.

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by KTom101** [comment]
@aedwardg Are there specific concepts this issue is linked to?

**Comment by aedwardg** [comment]
@KTom101 All of them except for `init` and `status`.
PR to come shortly 🙂

**Comment by Dusch4593** [comment]
Hey @aedwardg! For your PR, could we actually make a few changes to `init` and `status` as well? I was thinking of the following:

**For `init`**

Any instances of using a 1st- and 2nd- person voice (both explicit and imperative) should be replaced with either of the following:

- A more neutral, manual-like voice.
- Usage of a 3rd-person voice.

Example: 

We should replace "How do I init?" with something like "How to `init`" or `Initializing a git repository`

**For `status`**

In the `Description` property near the top in the metadata, could we edit the beginning of the sentence a bit from: 

```
Git statuses show the state...
```

to something like:

```
In Git, the status command displays the state
```

Also, in the code snippet near the bottom (with the output), let's switch `master` with `main` (per GH's [renaming guidance](https://github.com/github/renaming#:~:text=The%20default%20branch%20name%20for%20new%20repositories%20created%20on%20GitHub,%2Fsettings%2Frepository%2Ddefaults%20page)).

**Comment by aedwardg** [comment]
@Dusch4593 Sure, I can add those in. 🙂 
My PR has been ready for a while, but it looks like I no longer have permissions to push up a new branch from a direct clone, so I'll have to migrate my changes to a fork until @sonnynomnom can fix the perms for me again.
