### ISSUE TITLE
[Edit] JavaScript Conditionals

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5383]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Conditionals` concept entry under JavaScript. The entry lives in `content/javascript/concepts/conditionals/conditionals.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) guide when working on the PR for this issue.

Please:

1. Shorten the description of the concept to not more than 160 characters
2. Fix any typo in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by pedaars** [comment]
please assign this to me

**Comment by mamtawardhani** [comment]
Hey @pedaars for future reference, please raise a PR only after the issue has been assigned to you. Thank you! 😄
