### ISSUE TITLE
[Edit] JavaScript Bitwise Operators

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5385]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Bitwise Operators` concept entry under JavaScript. The entry lives in `content/javascript/concepts/bitwise-operators/bitwise-operators.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) guide when working on the PR for this issue.

Please:

1. Shorten the description of the concept to not more than 160 characters
2. Fix any typo in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by Mandipbhattarai** [comment]
@dakshdeepHERE I would like to work on  this issue

**Comment by braanj** [comment]
@codecademy-docs Hello, hope everybody is doing great.
Can I work on this issue ?

**Comment by harshitkumargupta** [comment]
hi @dakshdeepHERE @codecademy-docs can you please assign me this

**Comment by braanj** [comment]
Hey @dakshdeepHERE thank you ✨ I'm familiar with the process. I'll take care of it.
And no, it's not my first time.

**Comment by braanj** [comment]
Hey @dakshdeepHERE a PR [#5435](https://github.com/Codecademy/docs/pull/5435) has been created for this issue.
