### ISSUE TITLE
[Edit] Python Built-in-functions

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5386]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Built-in-functions` concept entry under Python. The entry lives in `content/python/concepts/built-in-functions/built-in-functions.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) guide when working on the PR for this issue.

Please:

1. Shorten the description of the concept to not more than 160 characters
2. Fix any typo in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by rrayhka** [comment]
i can fix this issue

**Comment by mamtawardhani** [comment]
Hey @rrayhka since you have been already assigned to two issues, let us first focus on merging those. Once both of them are merged, you can be assigned to other issues. Hope this helps! Thank you 😃

**Comment by rrayhka** [comment]
> Hey @rrayhka since you have been already assigned to two issues, let us first focus on merging those. Once both of them are merged, you can be assigned to other issues. Hope this helps! Thank you 😃

may i fix it now?

**Comment by rrayhka** [comment]
> Hey @rrayhka since you have been already assigned to two issues, let us first focus on merging those. Once both of them are merged, you can be assigned to other issues. Hope this helps! Thank you 😃

I have submitted PR but there is an error #5404 , I have a problem, do you have any suggestions, because I am new

**Comment by rrayhka** [comment]
> > > Hey @rrayhka since you have been already assigned to two issues, let us first focus on merging those. Once both of them are merged, you can be assigned to other issues. Hope this helps! Thank you 😃
> > 
> > 
> > I have submitted PR but there is an error #5404 , I have a problem, do you have any suggestions, because I am new
> 
> No worries, the reviewers will take care of the tests failing. Also, @rrayhka since one of your PR has been merged, would you like to work on this issue now?

okay, i'll try

**Comment by mamtawardhani** [comment]
@rrayhka You’re assigned 🎉
