### ISSUE TITLE
[Edit] Python Comments

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5387]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Comments` concept entry under Python. The entry lives in `content/python/concepts/comments/comments.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) guide when working on the PR for this issue.

Please:

1. Shorten the description of the concept to not more than 160 characters
2. Fix any typo in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by rrayhka** [comment]
Assign to me, i wanna try

**Comment by mamtawardhani** [comment]
Hey @rrayhka this is the second issue you are being assigned to, just a heads up! Waiting for the entry from your side 😄
