### ISSUE TITLE
[Edit] Lua Remove

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5388]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Remove` concept entry under Lua. The entry lives in `content/lua/concepts/tables/terms/remove/remove.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Method syntax and description seem plagiarised. Edit/rephrase them.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by shaeebali** [comment]
Hi, can I have this issue assigned to me? Thanks.

**Comment by mamtawardhani** [comment]
Hey @shaeebali 

You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by shaeebali** [comment]
> Hey @shaeebali
> 
> You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.
> 
> Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

Hey @mamtawardhani Thanks for assigning the issue to me. Yes it's my first issue for codecademy docs. It was part of an exercise in the "Learn Git and GitHub" course.
