### ISSUE TITLE
[Edit] Python Thread

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5391]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Thread` concept entry under Python. The entry lives in `content/python/concepts/threading/terms/thread/thread.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add more meaningful example of running two thread then just printing the threads.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by RashmitTopG** [comment]
I would like to try this issue.

**Comment by mamtawardhani** [comment]
Hey @RashmitTopG You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by RashmitTopG** [comment]
Can you help me in explaining why my PR merge failed as I am new to Open
Source Contribution.
[image: {12CFD23E-B80B-42B0-809E-186F79A6FAA2}.png]
