### ISSUE TITLE
[Edit] Python Date

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5392]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Date` concept entry under Python. The entry lives in `content/python/concepts/dates/terms/date/date.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add an Example section in this entry with a code example and its output.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by rrayhka** [comment]
I can take this

**Comment by mamtawardhani** [comment]
Hey @rrayhka since you have been already assigned to two issues, let us first focus on merging those. Once both of them are merged, you can be assigned to other issues. Hope this helps! Thank you 😃

**Comment by tanmaytare** [comment]
I would like to work on this issue . Can you please assign it to me .

**Comment by mamtawardhani** [comment]
Hey @tanmaytare You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by TsaiberSpace** [comment]
Hi, I'd like to take on this issue as part of my 'GitHub: Best Practices' project.

Thanks

**Comment by mamtawardhani** [comment]
Hey, @TsaiberSpace, I would suggest looking through the other open [issues](https://github.com/Codecademy/docs/issues) since a PR has already been raised for this. Let us know if anything interests you 😄
