### ISSUE TITLE
[Edit] AI Greedy-Best-First-Search

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5393]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Greedy Algorithm` concept entry under AI. The entry lives in `content/ai/concepts/search-algorithms/terms/greedy-best-first-search/greedy-best-first-search.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a section explaining the advantages and disadvantages of `Greedy Best First Search` algorithm.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by kaustubhgap** [comment]
Hello @codecademy-docs codecademy-docs,

I’d like to work on this issue. I’ve reviewed the problem and believe I can contribute effectively. Could you please assign it to me if no one is currently working on it?

Thank you!

**Comment by mamtawardhani** [comment]
Hey @kaustubhgap You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by mamtawardhani** [comment]
Unassigning author due to inactivity
