### ISSUE TITLE
[Edit] AI A-Star-Search

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5394]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `A Start Search` concept entry under AI. The entry lives in `content/ai/concepts/search-algorithms/terms/a-star-search/a-star-search.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a codeblock showing how A-Star-Search can be implemented. 
2) Discuss about space and time complexity of this algorithm.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by simin75simin** [comment]
Hi I think I've done A* before, happy to contribute!

**Comment by mamtawardhani** [comment]
Hey @simin75simin You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by simin75simin** [comment]
> Hey @simin75simin You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.
> 
> Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

Hi I found this repo by github searching open source projects to contribute to.
