### ISSUE TITLE
[Edit] SQL Windows Function

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5395]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the term entry `Lag` in the concept entry `Window-Function` under SQL. The entry lives in `content/sql/concepts/window-functions/terms/lag/lag.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add more example with default value and use of partition by. 
2) Add one sentence on the usecases.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by ultralegendary** [comment]
hi, Can you assign this to me.

**Comment by mamtawardhani** [comment]
Hey @ultralegendary You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by gustavo-crespo** [comment]
Hi, can you assign this issue to me.
I'm doing my practice for contributing to codeacademy docs repo .
Thanks

**Comment by gustavo-crespo** [comment]
Hi @mamtawardhani, thank you for your help!

I’m currently working through a GitHub course on Codecademy, and this task is part of the practical exercises I need to complete. I would appreciate it if you could review the pull request so I can continue my progress.

Thanks again.
