### ISSUE TITLE
[Edit] Python Regex

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5396]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the term entry `Sub` in concept entry `Regex` under Python. The entry lives in `content/python/concepts/regex/terms/sub/sub.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Explain that the replacement argument in `re.sub()` can be a function, not just a string. 
2) Describe how the function is called for every match and should return the replacement string.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by rrayhka** [comment]
Please assign to me

**Comment by mamtawardhani** [comment]
Hey @rrayhka for future references, please raise a PR only after an issue is assigned to you. Thanks! 😄

**Comment by rrayhka** [comment]
> Hey @rrayhka for future references, please raise a PR only after an issue is assigned to you. Thanks! 😄

pardon me, okay
