### ISSUE TITLE
[Edit] C# Strings

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5397]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the term entry `Contains` under concept entry `Strings` in C#. The term entry lives in `content/c-sharp/concepts/strings/terms/contains/contains.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a code example explaining how to use `comparisonType` feature. 
2) Add more detail on `culture`, `invariant` & `ordinal comparison` type.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by ChiragAgg5k** [comment]
I can work on this issue. Can you assign it to me?

**Comment by mamtawardhani** [comment]
Hey @ChiragAgg5k You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.
