### ISSUE TITLE
[Edit] AI Generative AI

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5424]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Generative AI` concept entry under AI. The entry lives in `content/ai/concepts/generative-ai/generative-ai.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) guide when working on the PR for this issue.

Please:

1. Shorten the description of the concept to not more than 160 characters
2. Fix any typo in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by NeXuSuss** [comment]
Hey! This issue looks fine. I can work on this issue. Please assign to me.

**Comment by mamtawardhani** [comment]
Hey @NeXuSuss already assigned you one issue, do you want to work on this as well?

**Comment by NeXuSuss** [comment]
Yes @mamtawardhani

**Comment by mamtawardhani** [comment]
Unassiging due to inactivity
