### ISSUE TITLE
[Edit] C# Classes

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5429]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Classes` concept entry under C#. The entry lives in `content/c-sharp/concepts/classes/classes.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) guide when working on the PR for this issue.

Please:

1. Add a code example explaining how to use `classes`. 
2. Fix any typo in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by Russellzj** [comment]
Can I be assigned this issue?

**Comment by mamtawardhani** [comment]
Hey @Russellzj You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by Russellzj** [comment]
> Hey @Russellzj You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.
> 
> Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

I found it while doing the exercises for the Codecademy:  Git & GitHub course. One of the assignments is to contribute to the Docs.
