### ISSUE TITLE
[Edit] C# Conditionals

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5430]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Conditionals` concept entry under C#. The entry lives in `content/c-sharp/concepts/conditionals/conditionals.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) guide when working on the PR for this issue.

Please:

1. Add a code example explaining how to use `conditionals`. 
2. Fix any typo in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by braanj** [comment]
Hey @codecademy-docs can you assign it to me, plz ?

**Comment by mamtawardhani** [comment]
Hey @braanj let us merge the entry submitted by you, then you can take up the issue 😃

**Comment by RashmitTopG** [comment]
Can you assign this to me ??

**Comment by giwpypatents** [comment]
Kindly assign this to me, please.

**Comment by mamtawardhani** [comment]
Hey @giwpypatents You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by mamtawardhani** [comment]
Hey @RashmitTopG you are already working on three issues, once they are done, you can take more issues.

**Comment by RashmitTopG** [comment]
@mamtawardhani can you please review my PR for other issues.
