### ISSUE TITLE
[Edit] C# Deque

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5431]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Deque` concept entry under C#. The entry lives in `content/c-sharp/concepts/deque/deque.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) guide when working on the PR for this issue.

Please:

1. Add a code example explaining how to use `deque`. 
2. Fix any typo in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by braanj** [comment]
Hey @codecademy-docs can you assign it to me, plz ?

**Comment by mamtawardhani** [comment]
Hey @braanj you are already assigned two issues, let's first merge those, then you can take up other issues as well 😄

**Comment by braanj** [comment]
Hey @mamtawardhani thanks for the reply. Can't I take more then two ? 😄

**Comment by braanj** [comment]
Yes I'd love to, thank you @mamtawardhani

**Comment by mamtawardhani** [comment]
Alright, here you go @braanj You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.
