### ISSUE TITLE
[Term Entry] CSS: Position `relative`

### ISSUE THREAD

**Issue by dakshdeepHERE** [Codecademy/docs#5444]
### Reason/inspiration (optional)

We would like a new entry under CSS for the `relative` term. The entry should go in a new file under `content/css/concepts/position/terms/relative/relative.md`.

The entry should include:

- An introduction to the concept
- A `Syntax` section that provides the syntax for the concept
- An `Example` section that provides an example demonstrating the concept in use
- An image or GIF showcasing this position type can be a plus point.

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by ozearkhan** [comment]
@dakshdeepHERE is this issue available to take on? any guidance on specific areas I should focus on would be appreciated.
