### ISSUE TITLE
[Bug/Error] Subject: CSS: Position `left`

### ISSUE THREAD

**Issue by ozearkhan** [Codecademy/docs#5451]
### Actual Behavior

**Description:**
I noticed a problem on the Codecademy page about the `left` property in CSS (`https://www.codecademy.com/resources/docs/css/position/left`). The page is supposed to show some example images that demonstrate how to use the `left` property, but instead, all I see are broken image icons. It would be great if those images could load correctly so we can see the examples as intended.

**Steps to Reproduce:**
1. Go to this page: [CSS Positioning - Left](https://www.codecademy.com/resources/docs/css/position/left).
2. Scroll down to where the example images should be.
3. You’ll see that the images aren’t displaying, just broken icons instead.

**Actual Behavior:**
Instead of the images, there are just broken image icons.

**Screenshots:**
![broken image ](https://github.com/user-attachments/assets/e5d49611-c296-46b0-9a6a-f006b31a0343)

### Expected Behavior

**Expected Behavior:**
 I expected to see the example images showing how the left property works.

![Screenshot 2024-10-11 175628](https://github.com/user-attachments/assets/1bd5f5bf-7ea0-461c-aeb7-4ac6e65dffbc)

### On what browser(s) are you seeing the problem?

Chrome, Microsoft Edge

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by ozearkhan** [comment]
@dakshdeepHERE @mamtawardhani
Ive created a PR to address the issue #5452 I went ahead and submitted the PR before requesting your review to ensure we move forward swiftly. If this was premature, I really apologize for any inconvenience.

Is it possible to assign the Hacktoberfest label to this issue ?

**Comment by mamtawardhani** [comment]
Hey @ozearkhan thank you for pointing this out 😃
And just to check this once with @dakshdeepHERE should we create an issue or can we add the label to this itself? Because I guess issues are only supposed to be created by the team

**Comment by ozearkhan** [comment]
Thank you for getting back to me @mamtawardhani ,yeah I think that make sense.

**Comment by mamtawardhani** [comment]
Closing this issue. @ozearkhan please do comment on the issue raised so that it can be assigned to you. It is #5453
