### ISSUE TITLE
[Edit] CSS: Position `left`

### ISSUE THREAD

**Issue by mamtawardhani** [Codecademy/docs#5453]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

We would like to edit the `left` term entry under CSS position. The entry lives in `content/css/concepts/position/terms/left/left.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) guide when working on the PR for this issue.

Please:

1. Fix the broken image links

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by mamtawardhani** [comment]
Hey @ozearkhan please comment here so that it can be asigned to you

**Comment by sujalcharati** [comment]
hey @mamtawardhani , can i be assigned?

**Comment by mamtawardhani** [comment]
> hey @mamtawardhani , can i be assigned?

Hey @sujalcharati a tshis issue already has a PR, you can check other open issues [here](https://github.com/Codecademy/docs/issues) to see if anything interests you and let us know 😃

**Comment by ozearkhan** [comment]
@mamtawardhani thank you,
I'll then just change the issue tag on my PR.
