### ISSUE TITLE
[Concept Entry] C++: Unordered Set

### ISSUE THREAD

**Issue by mamtawardhani** [Codecademy/docs#5456]
### Reason/inspiration (optional)

We would like a new concept entry under CSS for `Unordered set`. The entry should go in a new file under `content/cpp/concepts/unordered-set/unordered-set.md`.

The entry should include:

- An introduction to the concept
- A Syntax section that provides the syntax for the concept
- An Example section that provides an example demonstrating the concept in use
- A
 Codebyte Example section with a runnable code
Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by mamtawardhani** [comment]
Hey @Jack-Race please comment "claim" on this issue, so that it can be assigned to you as you have raised a PR for this. 
Thanks!

**Comment by Jack-Race** [comment]
Claim

**Comment by mamtawardhani** [comment]
You are assigned @Jack-Race
