### ISSUE TITLE
[Entry] General: Vim

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#546]
### Reason/inspiration (optional)

In the "General" topic, write a concept entry about Vim, an open-source terminal-based text editor for Unix-based systems. Be sure to include the following:

- A link to the official Vim website, https://www.vim.org/.
- Code snippets (```bash) that show how to launch Vim.
- A _brief_ section about how to use Vim.
- A screenshot of Vim being used on a terminal.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by paulpetelski** [comment]
Hi! I was wondering if I can be assigned this issue.

**Comment by Dusch4593** [comment]
@paulpetelski absolutely! I'll assign you.

**Comment by Dusch4593** [comment]
@paulpetelski If you would like to receive credit for your contribution, make sure to have your Codecademy user profile linked to your GitHub account:

1. Go to your Codecademy dashboard.
2. Click on your profile image in the top-right and then choose "Profile".
3. Then click "Edit Profile".
4. In the "GitHub Username" field, add your username (without the @).
5. Click "Save Changes"

Of course, you can opt and prefer to be listed as an "Anonymous contributor", instead. :)
