### ISSUE TITLE
[Concept Entry] C++ Upper Bound Function map

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5479]
### Reason/inspiration (optional)

We would like a new entry on the `upper_bound()` term under C++ Maps. The entry should go in a new file under `docs/content/cpp/concepts/maps/terms/upper-bound/upper-bound.md`.

The entry should include:  
  
- An introduction to the concept  
- A `Syntax` section that provides the syntax for the concept  
- An `Example` section that provides an example demonstrating the concept in use  
- A `Codebyte Example` section that provides a codebyte example demonstrating the concept in use  
  
Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entrty for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by ozearkhan** [comment]
@codecademy-docs i would like to work on this if this could be assigned to me .

**Comment by mamtawardhani** [comment]
Hey @ozearkhan, you have been assigned to one issue already. Would you like to work on this as well?

**Comment by ozearkhan** [comment]
@mamtawardhani  I understand there's a rule for working on up to 3 issues at a time. I’ve already submitted PRs for all my assigned tasks, so I’m happy to take this on if needed, but no worries if it gets assigned to someone else. Thanks!

**Comment by mamtawardhani** [comment]
> @mamtawardhani I understand there's a rule for working on up to 3 issues at a time. I’ve already submitted PRs for all my assigned tasks, so I’m happy to take this on if needed, but no worries if it gets assigned to someone else. Thanks!

You can take this up :)
