### ISSUE TITLE
[Edit] C++ enum

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5483]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `enum` concept entry under C++. The entry lives in `content/cpp/concepts/enum/enum.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) guide when working on the PR for this issue.

Please:

1. Shorten the description to not more than 160 characters
2. Fix any typo in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by RashmitTopG** [comment]
I would like to work on this issue

**Comment by mamtawardhani** [comment]
Hey @RashmitTopG I already assigned another issue to you, do work on that

**Comment by danitellini** [comment]
I would like to work on this issue for my Github course, please.

**Comment by RashmitTopG** [comment]
@mamtawardhani I completed the earlier issue .

**Comment by RashmitTopG** [comment]
@mamtawardhani can you assign me with this issue ??

**Comment by mamtawardhani** [comment]
Hey @RashmitTopG You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

**Comment by mamtawardhani** [comment]
Hey @danitellini since @RashmitTopG had commented first, I assigned it to him. You can check the open issues and let me know if anything interests you 😃
