### ISSUE TITLE
[Edit] C++ files

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5485]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `files` concept entry under C++. The entry lives in `content/cpp/concepts/files/files.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) guide when working on the PR for this issue.

Please:

1. Shorten the description to not more than 160 characters
2. Fix any typo in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by Naumantamboli** [comment]
i would like to work on this issue

**Comment by mamtawardhani** [comment]
Hey @Naumantamboli you have been assigned to one issue already, would you like to work on this as well?

**Comment by Naumantamboli** [comment]
yes i would like to work on this one too

**Comment by Naumantamboli** [comment]
Yes, I would.
