### ISSUE TITLE
[Edit] C++ functions

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5486]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `functions` concept entry under C++. The entry lives in `content/cpp/concepts/functions/functions.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) guide when working on the PR for this issue.

Please:

1. Shorten the description to not more than 160 characters
2. Fix any typo in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by RashmitTopG** [comment]
I would like to work on this issue.

**Comment by mamtawardhani** [comment]
Hey @RashmitTopG you are already working on three issues, once they are done, you can take more issues.

**Comment by mamtawardhani** [comment]
> Good day,
> 
> I would like to work on this issue please. Thank you.

Hey @LesgoMega You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by mamtawardhani** [comment]
> @mamtawardhani I have completed them can you please check them your review is required.

Will do, as I can see a reviewer is already assigned, so it will get reviewed soon 😃
