### ISSUE TITLE
[Edit] C++ polymorphism

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5489]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `polymorphism` concept entry under C++. The entry lives in `content/cpp/concepts/polymorphism/polymorphism.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) guide when working on the PR for this issue.

Please:

1. Shorten the description to not more than 160 characters
2. Fix any typo in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by ozearkhan** [comment]
Is this still open to take ?

**Comment by Zubair576335** [comment]
@codecademy-docs can I work on this one ?

**Comment by mamtawardhani** [comment]
Hey @Zubair576335 You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by Zubair576335** [comment]
@mamtawardhani do i need to just shorten the description , or update everything like definitions code blocks examples ?

**Comment by mamtawardhani** [comment]
> @mamtawardhani do i need to just shorten the description , or update everything like definitions code blocks examples ?
Just the description is to be shortened, and if you find any typo in the previous entry, you can fix that
