### ISSUE TITLE
[Entry] Python: Substring

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#549]
### Reason/inspiration (optional)

Working with substrings in Python is pretty robust so we think it deserves its own concept entry! In this new entry, be sure to include the following:

- A hyperlink to [the existing Python: Strings entry](https://www.codecademy.com/resources/docs/python/strings).
- A "## Syntax" section that has 1-2 sentences about indexing in Python strings using the ```pseudo code snippet signature:

```
my_string[start:end:step]
```

  - Make sure to explain each argument, `start`, `end`, and `step`.

- One or two sections about common substring techniques including:
  - First `n` characters of a string: `my_string[:n]`
  - Get last character in a string: `my_string[-1]`
  - Get last `n` characters of a string: `my_string[-n:]`
  - Reverse a string in `n` negative steps: `reversed = my_string[::-n]`
  - Check for substring of characters in string with `in` or `.find()`:

```
substring in my_string

my_string.find(...)
```
  - By the way, we should link to `.find()` since we have [an entry](https://www.codecademy.com/resources/docs/python/strings/find) for it.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by KTom101** [comment]
@Dusch4593 I'll work on this.
