### ISSUE TITLE
[Entry] SQL: Wildcards

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#551]
### Reason/inspiration (optional)

Write a concept entry about how wildcards add versatility to SQL statements, including:

- A brief 2-3 sentence paragraph that defines wildcards and what they're used for.
- A "## Syntax" section with a short list of common wildcards (`*`, `_`, `%`, etc.).
- An "## Examples" section that has:
  - One example of using the `*` wildcard.
  - One example that demonstrates combining wildcards (`WHERE Name LIKE '_r%'`)

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
I'll do this one.

**Comment by SSwiniarski** [comment]
@Dusch4593, isn't this covered under the LIKE operator, and do we want to move the discussion on the details of pattern matching to its own article? Also, should SELECT * be part of this? It usually isn't referred to as a wildcard. Details on it probably belong under SELECT.

**Comment by Dusch4593** [comment]
@SSwiniarski All super fair points! You're right, we should keep details about `SELECT *` in the "SELECT" entry. 

As for the pattern-matching examples in the `LIKE` entry, it's up to you whether you want to polish within that entry (maybe consolidate the examples from the current 6 to 2 or 3) or reallocate to a new entry. Would it be entitled as something like "Pattern Matching" and is this different from regex?

**Comment by SSwiniarski** [comment]
@Dusch4593, Yes, it is different. I've gone through some hurdles trying to use regular expressions in SQL Server, as they're not supported natively. (Which is BS, it supports XML, it wouldn't be that hard to also support regex.)

I'd still call the separate entry "Wildcards." As that seems to be the more common verbiage. I'd lean towards a separate entry as in SQL (at least SQL Server) there's at least one other command that uses them. (I don't know if PATINDEX() is ANSI or not.)
