### ISSUE TITLE
[Terms Entry] Subject: Comand Line > Bash

### ISSUE THREAD

**Issue by aka-0x4C3DD** [Codecademy/docs#5515]
### Reason/inspiration (optional)

to make the entry more comprehensive, a lot of bash commands could be added to enhance the concept entry.
this is what I am targeting to accomplish adding.

        Syntax Fundamentals: Introduction to the basic syntax, rules, and structure of the language.
        Control Structure: Overview of conditional statements, loops, and branching mechanisms.
        Functions: Explanation of defining and using functions, including parameters and return values.
        Input and Output: Handling user input and system output, managing how data is received and displayed.
        File Operations: Working with files, including reading from and writing to files.
        String Manipulation: Techniques for processing and manipulating strings within scripts.
        Arrays and Associative Arrays: Usage of both indexed and associative arrays for data storage and retrieval.
        Best Practices:
        
            Script Organization: Structuring scripts for readability and maintainability.
            Naming Convention: Using consistent and meaningful names for variables and functions.
            Error Checking and Validation: Ensuring scripts handle errors and validate inputs.
            Security Consideration: Incorporating security practices to avoid vulnerabilities.

So, if you could assign me this issue, I can begin working on this. 
Also, putting this under the hacktober label would help me out. :)

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by AndreiCatanea** [comment]
Im on it

**Comment by codecademy-docs** [comment]
Hey! @aka-0x4C3DD 
Thanks for the suggestion. 
We need to upload multiple term entries for this. 
We will close this issue so that we can upload multiple term entries for this from our end.
