### ISSUE TITLE
[Entry] Go: Conditionals

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#553]
### Reason/inspiration (optional)

Write a concept entry that defines conditionals in Go and includes information about:

- The `if...else`  and `else if` statements.
- Comparison operators like `==` and `>=`.
- Logical operators like `&&` and `||`.

Be sure to include code snippet examples, as well. 😄 

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
I'll takle this to keep expanding our Go entries.
