### ISSUE TITLE
[Entry] Go: Loops

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#554]
### Reason/inspiration (optional)

Write a concept entry about using loops and how Go only uses the `for` keyword for it. Be sure to include "## Syntax" and "## Example" sections with code snippets.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
I can take on another Go entry.
