### ISSUE TITLE
[Term Entry] Python: Strings: `.join()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#555]
### Reason/inspiration (optional)

For the "Python: Strings" concept, write a term entry that defines the `.join()` string method, including:

- "## Syntax" and "## Example" sections with code snippets.
- At least one `codebyte/py` example (but only one) that is placed as the last example at the bottom of the term entry.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by KTom101** [comment]
Hey @Dusch4593, can I assign this one to myself?

**Comment by Dusch4593** [comment]
@KTom101 absolutely! 👍
