### ISSUE TITLE
[Edit] C# math-functions: asin

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5574]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `asin` term entry under `math-functions` C#. The entry lives in `content/c-sharp/concepts/math-functions/terms/asin/asin.md`

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
- Add an ## Example section above the ## codebyte example section (this is already present)
- Make sure the output for the example is enclosed within the ```shell``` block

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by mamtawardhani** [comment]
Hey @ChinoUkaegbu You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.
