### ISSUE TITLE
[Term Entry] HTML: Tags: `<source>`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#558]
### Reason/inspiration (optional)

For the "HTML: Tags" concept, write a term entry that defines the `<source>` tag including:

- "## Syntax" and "## Example" sections with code snippets.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by ethan-master-coding** [comment]
@Dusch4593 Can you assign me to this. Might take a while because like I said I have 2 other ideas I'm working on.

**Comment by Dusch4593** [comment]
@ethan-master-coding You're assigned! 🎊 Plus, see [my comment on the other thread](https://github.com/Codecademy/docs/pull/543#issuecomment-1043496827).
