### ISSUE TITLE
[Entry] HTML : Tags: `<abbr>`

### ISSUE THREAD

**Issue by ethan-master-coding** [Codecademy/docs#568]
### Reason/inspiration (optional)

It is a useful tag when displaying large abbreviated numbers or abbreviations and what to make available the full name when not using a link to another page or adding it directly in the text.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Nessvah** [comment]
Hi. I'm new to contributions, but I saw that this issue still doesn't have anyone assigned to it. Can I try to work on it?

**Comment by ethan-master-coding** [comment]
@Nessvah Sounds good. Just wait until somebody that has perms to assign you to this.

**Comment by KTom101** [comment]
Hi @Nessvah, I'll assign you right now! If you ever need help, you can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) or just ask for help!

**Comment by Nessvah** [comment]
Yes for sure, thanks!

**Comment by ethan-master-coding** [comment]
Page is now live. Can view it [here](https://www.codecademy.com/resources/docs/html/tags/abbr).
