### ISSUE TITLE
[Concept Entry] NumPy: Array Broadcasting

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5693]
### Reason/inspiration (optional)

We would like a new concept entry on the `Array Broadcasting` in NumPy. The entry should go in a new file under **`docs/content/numpy/concepts/array-broadcasting/array-broadcasting.md`.**       
  
The entry should include:      
  
- An introduction to the concept      
- A `Syntax` section that provides the syntax for the concept (if applicable)      
- An `Example` section that provides an example demonstrating the concept in use (if applicable)     
 - An `Codebyte Example` section that provides an example demonstrating how to use deque
 
Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.|

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by MiirzaBaig** [comment]
hey, i would like to work upon this issue...
could you assign me if currently none is assigned so far..

**Comment by Radhika-okhade** [comment]
Hey! @MiirzaBaig, I have assigned you 3 issues already. Once they are submitted, then, I will assign new ones to you.

**Comment by MiirzaBaig** [comment]
I Have submitted the PR..
lmk, if any changes needed tobe made..

meanwhile, can you assign me this issue too...
thank you!

**Comment by mohammadsohail23** [comment]
Hi! I’d like to work on this issue. Could you please assign it to me? Thanks!

**Comment by claudiooleite** [comment]
Hi guys! I want to work on this issue. Thank you

**Comment by codecademy-docs** [comment]
Hey @Aashishst  You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

**Comment by Sriparno08** [comment]
Unassigned author due to inactivity.
