### ISSUE TITLE
[Edit] JavaScript: try-catch

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5766]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `try catch` concept entry under JavaScript. The entry lives in `content/javascript/concepts/try-catch/try-catch.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) guide when working on the PR for this issue.

Please:

1. Shorten the description of the concept to not more than 160 characters
2. Fix any typo in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by Tarenthis** [comment]
Hi, I'd like to pick up this issue. Currently working through the Git course on Codecademy.

**Comment by mamtawardhani** [comment]
Hey @Tarenthis, you’re assigned! 🎉

In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).
