### ISSUE TITLE
[Edit] Documentation: Contribution Guide

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#579]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

- Add a section for "How do I keep my PR branch up to date" in the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) either right after [Codecademy username](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md#codecademy-username) or right before "Additional Resources". (Can be up for discussion)
- Add point about "if the creator of the PR doesn’t update the entry 5-7 days after a review, our maintainer will do so ourselves."

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by ethan-master-coding** [comment]
@yangc95 it looks like this change was made. Should we close this?

**Comment by yangc95** [comment]
Hi @ethan-master-coding! Appreciate you looking into this, however, I don't believe the proper change is up in the guide yet.

This issue is a result of a direct discussion with @aedwardg and @Dusch4593 to add more details and images for specific Git instructions/commands on how to keep a PR branch up-to-date.

Since this is brought to my attention again, I'm going to add one more point to this issue that was requested by @sonnynomnom.

**Comment by Nessvah** [comment]
This will be really helpful for new contributors.

**Comment by yangc95** [comment]
Hi, @aedwardg hope all is well! Reaching out to make sure this is an issue you're comfortable with still tackling. I'm happy to directly assist with this one as well. LMK 🙂

**Comment by yangc95** [comment]
@aedwardg are you cool if I take over this issue?

**Comment by Dusch4593** [comment]
There hasn't been much movement on this issue for a while so I'm gonna reassign to @ethan-master-coding.

**Comment by ethan-master-coding** [comment]
@Dusch4593 Already finished. #664. I think im the flash

**Comment by yangc95** [comment]
@Dusch4593 @ethan-master-coding Cool! we'll take a look at it soon 😌
