### ISSUE TITLE
[Term Entry] Python Built-in Functions: `super()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#586]
### Reason/inspiration (optional)

Please write a term entry** about the `super()` function that includes the follwoing:

* A "Syntax" section with ```pseudo code snippet(s)
* One or two "Example" sections that explain the two common use cases for `super()`.
* One "Codebyte Example" section with a ```codebyte/python snippet.

**Some content about `super()` already exists in the [Python: Inheritance](https://www.codecademy.com/resources/docs/python/inheritance) entry. See [comment below](https://github.com/Codecademy/docs/issues/586#issuecomment-1126266162) for more details.

Please also refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) when creating the entry.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Dusch4593** [comment]
@subzjee Good catch! That information about `super()` should be moved into its own entry under "Python: Built-in Functions". Would you like to take this one on?

**Comment by ethan-master-coding** [comment]
@Dusch4593 So is this issue just moving a file into a different section of the Python sections. Am I correct?

**Comment by beverand** [comment]
I saw that this has been sitting a while, my python is a little rusty since I've been doing mostly javascript, but I'd like to take a crack at this issue if no one else is working on it.

**Comment by Dusch4593** [comment]
@beverand Absolutely! I've assigned this issue to you. Thank you for your interest in contributing to Docs and let us know if have any questions about making/submitting the pull request. 😄

**Comment by beverand** [comment]
Thank you!

**Comment by beverand** [comment]
@Dusch4593, did I do this correctly?
