### ISSUE TITLE
[Term Entry] CSS Grids: `grid-template-areas`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#587]
### Reason/inspiration (optional)

Please write a term entry that defines the `grid-template-areas` CSS property and includes the following informating:

* Brief information about how `grid-template-areas` differs/relates to the `grid-template` and `grid-area` properties.
* A "Syntax" section with a ```pseudo code snippet.
* An "Examples" section.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Nessvah** [comment]
Can I try to work on this issue?

**Comment by Dusch4593** [comment]
@Nessvah Sure!

**Comment by Nessvah** [comment]
@Dusch4593 how are you? I have been working on this issue but slowly due to some work that I need to do outside this field. I'll try to end this by the end of this week but, if after that there's still no PR and someone wants to work on this, feel free to assign this issue to them. 🙂

**Comment by Dusch4593** [comment]
@Nessvah Sure thing! Take as much time as you need 😄
