### ISSUE TITLE
[Term Entry] HTML: Tags: `<code>`

### ISSUE THREAD

**Issue by ethan-master-coding** [Codecademy/docs#595]
### Reason/inspiration (optional)

To format code on websites. It is the same as back tics in MD.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

**Comment by Dusch4593** [comment]
@ethan-master-coding There is already [an existing entry](https://www.codecademy.com/resources/docs/html/tags/code) for the HTML `<code>` tag. Before creating issues, I encourage you to browse the relevant topic(s)/concept(s) and parse their entries to check if one you seek already exists.

**Comment by ethan-master-coding** [comment]
@Dusch4593 I must of missed it some how when I looked.

**Comment by Dusch4593** [comment]
> @Dusch4593 I must of missed it some how when I looked.

No worries! 😄 Admittedly, the Docs collection is growing and the navigability is becoming more pressing, imo. Hopefully in the near future, that navigation will be improved.

**Comment by ethan-master-coding** [comment]
@Dusch4593 Yea. The best thing would be a search feature. I would help build that but I don't know the backend.
