### ISSUE TITLE
[Term Entry] SQL: `CONTAINS`

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#612]
### Reason/inspiration (optional)

Create a new term entry within [content/sql/commands](https://www.codecademy.com/resources/docs/sql/commands)/contains

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by paulpetelski** [comment]
Hi! Can I be assigned this issue?

**Comment by yangc95** [comment]
@paulpetelski OFC!

**Comment by yangc95** [comment]
See you on the flip~ (PR side)
