### ISSUE TITLE
[Entry/Edit] CSS: Inheritance

### ISSUE THREAD

**Issue by ethan-master-coding** [Codecademy/docs#629]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Add if the CSS property is inherited.

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by ethan-master-coding** [comment]
I'm willing to make this change I'm just not sure where to put it in each entry.

**Comment by ethan-master-coding** [comment]
Should we have a table with some values like on MDN web docs?

![image](https://user-images.githubusercontent.com/92686703/158698261-53c1c9b5-c9fe-480a-a729-62753200cab0.png)

**Comment by Dusch4593** [comment]
Not too sure about the MDN-like yet. Also, are we sure this is an edit? Do we even have a CSS: Inheritance entry to begin with?

**Comment by ethan-master-coding** [comment]
@Dusch4593 I'm talking about properties. Like the `color` property is inherited. But the `border` is not inherited. Im talking about that inheritance for each property.

**Comment by Dusch4593** [comment]
> @Dusch4593 I'm talking about properties. Like the `color` property is inherited. But the `border` is not inherited. Im talking about that inheritance for each property. And you can remove the typo lable its not relevant to this.

Right but which entries would get this edit?

**Comment by ethan-master-coding** [comment]
@Dusch4593 The edit would be to every CSS property in the docs. And for the title, I couldn't think of a better one.

**Comment by Dusch4593** [comment]
> @Dusch4593 The edit would be to every CSS property in the docs. And for the title, I couldn't think of a better one.

Oof that's a lot of files. What if we did this to start?

* Create a CSS concept entry called "Inheritance" (since it is a pretty notable [aspect](https://developer.mozilla.org/en-US/docs/Web/CSS/inheritance) of CSS properties)
* Make that edit to 3-4 exiting CSS entries (`color`, `border`, etc.)


As for the title, no worries! 😊

**Comment by ethan-master-coding** [comment]
@Dusch4593 So we just have 1 big page that has all the properties and their inheritance. Got it.

**Comment by Dusch4593** [comment]
> @Dusch4593 So we just have 1 big page that has all the properties and their inheritance. Got it.

Maybe that could be written as [a markdown table](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables) with links to any appropriate Docs entries.

Also, this "Inheritance" should have a breakdown between inherited properties and non-inherited properties.

**Comment by ethan-master-coding** [comment]
@Dusch4593 Got it. A table for inherited properties and a table for not inherited properties.

**Comment by ethan-master-coding** [comment]
@Dusch4593 If we are going to link the entry in all the entries is it just easier to just put it on every entry instead of 1 big 1.

**Comment by Dusch4593** [comment]
> @Dusch4593 If we are going to link the entry in all the entries is it just easier to just put it on every entry instead of 1 big 1.

Not necessarily. My thoughts were that there would be one concept entry that does the following:

- Explains what CSS inheritance means at a high-level.
- Tables that breakdown common inherited properties and non-properties. 


Relatively speaking, our CSS entries are few in number so the tables are more likely to speak of both properties already covered in Docs and those that aren't.

**Comment by ethan-master-coding** [comment]
@Dusch4593 Can you assign this to me?

**Comment by ethan-master-coding** [comment]
Before I start working on this I am going to wait for at least 1 of my PRs to get merged (#616, #618, #627). Don't want to overwhelm the maintainers

**Comment by Dusch4593** [comment]
> Before I start working on this I am going to wait for at least 1 of my PRs to get merged (#616, #618, #627). Don't want to overwhelm the maintainers

No worries! Speaking of which, I just left a few last-minute suggestions for you on #616.

**Comment by ethan-master-coding** [comment]
@Dusch4593 speak of the devil. Im going through them right now.
