### ISSUE TITLE
[Entry] HTML: `<output>` tag

### ISSUE THREAD

**Issue by ethan-master-coding** [Codecademy/docs#653]
### Reason/inspiration (optional)

Added the result of an action done by the user or calculation to the page.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Antonio-Riccelli** [comment]
Hi there, 
is currently anyone working on this? If not, I'd like to.

**Comment by ethan-master-coding** [comment]
@Antonio-Riccelli start working on this while we wait for a maintainer to assign you.

**Comment by Dusch4593** [comment]
@Antonio-Riccelli assigned!
