### ISSUE TITLE
[Edit] Content Standards: Technical Writing

### ISSUE THREAD

**Issue by KTom101** [Codecademy/docs#670]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Expand our [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) to include information on technical writing. Please include this under the “General Writing Tips” section. 

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by dharmelolar** [comment]
@KTom101 I'd love to work on this issue

**Comment by KTom101** [comment]
@dharmelolar Thanks! I've assigned you.

**Comment by dharmelolar** [comment]
@KTom101 I submitted a pull request.

**Comment by ethan-master-coding** [comment]
I belive this can be closed #673
