### ISSUE TITLE
[Edit] React: State

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#671]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Continuation for [Issue 457](https://github.com/Codecademy/docs/issues/457#issuecomment-1083257266)

Include [property initializers](https://reactjs.org/blog/2015/01/27/react-v0.13.0-beta-1.html#es7-property-initializers) in the [React state](https://www.codecademy.com/resources/docs/react/state) entry.

Let us know if you'd like to take this issue on! Questions welcome 👐 

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by joneskj55** [comment]
May I be assigned to this issue? @yangc95 @Dusch4593

**Comment by Dusch4593** [comment]
You got it, @joneskj55! You're assigned and thank you for your interest in contributing to Codecademy Docs! 😄
