### ISSUE TITLE
[Term Entry] React: Hook

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#672]
### Reason/inspiration (optional)

Continuation for [Issue 457](https://github.com/Codecademy/docs/issues/457#issuecomment-1073067484)

Edits wanted to the [React Hooks](https://www.codecademy.com/resources/docs/react/hooks) entry for a terms table with different hooks as separate term entries. Ensure that the file structure is correct.

Let us know if you'd like to take this issue on! Questions welcome 👐 

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Dusch4593** [comment]
Which is preferable?

* A markdown table with headers/rows for the different hook data (names, descriptions, etc.).
* Separate folders/flies for terms entries for different hooks (e.g. `react/hooks/terms/useState/useState.md`).

**Comment by yangc95** [comment]
I think the second option is preferable; separate term entries instead of a markdown table

**Comment by krowter** [comment]
Hi @yangc95, this issue looks fun

Just want to clarify a something. By one "term entry", you meant a single markdown file containing some description, syntax, and example right?

**Comment by yangc95** [comment]
Hi @krowter! Yeah, React hooks are really fun to work with.

Yup! There are currently two hooks mentioned that should be terms (`useState` and `useEffect`). If you can create a `terms` folder within `hooks`, and create two separate folders (`useState` and `useEffect`) for the markdown files (`useState.md` and `useEffect.md`), that would be ideal. As a result, the concept entry `hooks.md` would also need editing.

You're on point with what a term entry consists of. If you'd like you can add a third term or just add onto the two terms that are already mentioned. I can assign this one over to you if you would like to take it on. LMK!
