### ISSUE TITLE
[Bug/Error] Repo : Entry of the week not being updated

### ISSUE THREAD

**Issue by ethan-master-coding** [Codecademy/docs#684]
### Actual Behavior

Not being updated on a weekly basis. It is supposed to be updated every week. The last time it was updated was on January 30ht 2022. See the file here: [https://github.com/Codecademy/docs/blob/main/bin/concept-of-the-week.txt](https://github.com/Codecademy/docs/blob/main/bin/concept-of-the-week.txt).

### Expected Behavior

It should update on a weekly basis.

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by Dusch4593** [comment]
@ethan-master-coding It looks like our COTW is having troubles again 😢  I believe that the script logic for the actual update [lives elsewhere](https://github.com/Codecademy/docs/pull/431) for security reasons.

@christian-dinh Any thoughts on why this might be happening?

**Comment by christian-dinh** [comment]
woops, yeah github canceled the workflow automatically since the repo it's in hasn't been updated in 60 days. Hopefully there's a way to disable that feature...

**Comment by christian-dinh** [comment]
anyway I re-enabled the workflow so it'll update next week

**Comment by ethan-master-coding** [comment]
@christian-dinh what day should it update?

**Comment by Dusch4593** [comment]
@ethan-master-coding I believe it should be every Sunday at 1pm UTC.

It's listed [here in this workflow](https://github.com/Codecademy/docs-update-cotw/blob/main/.github/workflows/update-cotw.yml) near the bottom of the file.

**Comment by ethan-master-coding** [comment]
@christian-dinh Just saying we have about 2 weeks until the workflow will be disabled again unless you disabled that setting. It may be worth reverting #431.

**Comment by christian-dinh** [comment]
@ethan-master-coding for security reasons we definitely can't revert that (it also never worked when it was in this repo 😅). Thanks for the heads up though! There is not a setting to be disabled, but it is possible to make a workaround via a script that pushes dummy commits to the repo, I'll try to do that when I have the time

**Comment by ethan-master-coding** [comment]
@Dusch4593 @christian-dinh COTW did not update today. Its 1:41 AM UTC and it was supposed to update 12.5 hours ago.

**Comment by Dusch4593** [comment]
@ethan-master-coding As of now, we have to re-enable _every 60 days_ because of [GH's policies regarding inactive workflows](https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow). When @christian-dinh [reenabled](https://github.com/Codecademy/docs/issues/684#issuecomment-1091983487) back on April 7th, that _reset_ the 60 days (hence [your anticipation](https://github.com/Codecademy/docs/issues/684#issuecomment-1132232972)). While we are still working on a solution that is more automated, they will have to reenable every 60 days (approx. 2 months).

**Comment by Dusch4593** [comment]
> @Dusch4593 It should still be enabled since it has not been 60 days since May 19th

I don't believe that was the last time the workflow was reenabled. Pretty sure it was April 7th. Can we confirm @christian-dinh?

**Comment by christian-dinh** [comment]
sorry for the delay, I've
- re-enabled the workflow
- run it manually, so the concept of the week should update sometime in the next hour or so
- made some changes to hopefully prevent the issue going forward, but I won't know for sure for some time

again apologies it took so long, but hopefully won't have to worry about it again!
