### ISSUE TITLE
[Entry] General: Virtual machines

### ISSUE THREAD

**Issue by not-a-ethan** [Codecademy/docs#710]
### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by YanisaHS** [comment]
Hey! I'd be into working on this one too if you can assign it to me! 🥳

**Comment by Dusch4593** [comment]
@YanisaHS Assigned! 😄
