### ISSUE TITLE
[Entry] General: Github

### ISSUE THREAD

**Issue by ethan-master-coding** [Codecademy/docs#717]
### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by ethan-master-coding** [comment]
@Dusch4593 Can you assign this to me?

**Comment by Dusch4593** [comment]
@ethan-master-coding Assigned!
