### ISSUE TITLE
[Entry] General: Full-stack

### ISSUE THREAD

**Issue by not-a-ethan** [Codecademy/docs#726]
### Reason/inspiration (optional)

We have a front-end and back-end entries so we need to finish it will a full-stack entry.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by joneskj55** [comment]
I'll take this if still available @not-a-ethan @Dusch4593

**Comment by Dusch4593** [comment]
@joneskj55 Assigned! 👍🏻

**Comment by joneskj55** [comment]
Hey @Dusch4593, I noticed that you wrote the front and back-end entries. Is it ok if I reuse some of your content for the full-stack entry? I am adding a lot of my own content as well however, I have found that your entries contain a lot of the info already so was thinking to just recycle some of it if thats ok.
