### ISSUE TITLE
[Entry] General: Time complexity

### ISSUE THREAD

**Issue by ethan-master-coding** [Codecademy/docs#759]
### Reason/inspiration (optional)

Include `O(n)`, `O(n^2)`, `O(log n)`, and any others I may not be aware of, 

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Dusch4593** [comment]
To whomever writes this entry, can we find a way to utilize [LaTex snippets](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/#latex) when referring to time complex formulae?

**Comment by Dusch4593** [comment]
I also realize that we might need a separate entry that just talks about Big-O notation in general so I filed an issue for it. We may also want to make a "Space Complexity" entry in the future, too.

**Comment by elliotfayman** [comment]
What's the difference between this issue and the big-o notation issue?

**Comment by Dusch4593** [comment]
This is duplicate. Thank you for flagging 😄 I'll close this
