### ISSUE TITLE
[Entry] General: File structure

### ISSUE THREAD

**Issue by not-a-ethan** [Codecademy/docs#779]
### Reason/inspiration (optional)

Write a General concept entry about file/directory structures, what they, and how they are used by computers to organize information.

Recommendation: Find ways to hyperlink to the existing [file format](https://www.codecademy.com/resources/docs/general/file-formats) and [file path](https://www.codecademy.com/resources/docs/general/file-paths) entries.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by YanisaHS** [comment]
Hi!! I'd be into working on this issue - mind assigning it to me? Thanks! 😄

**Comment by Dusch4593** [comment]
@YanisaHS Assigned! 😄
