### ISSUE TITLE
[Entry] General: Content Management System

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#806]
### Reason/inspiration (optional)

Create a new entry in the General topic about **content management systems (CMS)**, including:

- What they are and how they came to be.
- How and why are used.
- Common/modern examples of CMSs.

Please refer to the [Docs entry template](https://github.com/Codecademy/docs/blob/main/documentation/entry-template.md) [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when creating the entry.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by dharmelolar** [comment]
@Dusch4593 Can I work on this issue?

**Comment by Dusch4593** [comment]
@dharmelolar absolutely! Assigned 👍🏻

**Comment by tejas0124** [comment]
Can I Work On This Issue?

**Comment by dharmelolar** [comment]
@tejas0124 This issue has been assigned to me already and I'm currently working on it.

**Comment by Dusch4593** [comment]
@tejas0124 Here is a list of other open issues (not yet assigned) in the general topic: https://github.com/Codecademy/docs/issues?q=is%3Aopen+is%3Aissue+label%3Ageneral+no%3Aassignee

**Comment by SSwiniarski** [comment]
@dharmelolar I just wanted to check how you're progressing on this issue and if you need any help. If you're actively progressing on it, just leave a note here. Also note that there's only another two days for credit in hacktoberfest.

**Comment by dharmelolar** [comment]
@SSwiniarski I’ll send it in soon.

**Comment by SSwiniarski** [comment]
@dharmelolar, good to hear 👍

**Comment by SSwiniarski** [comment]
@dharmelolar, I just want to follow up on how you're progressing on this PR. Are you still working on it?

**Comment by dharmelolar** [comment]
@SSwiniarski I'm so sorry this is taking too long. I'm almost done with it but work has been hectic. That's why I haven't turned it in. Hope to do so in a few days.

**Comment by SSwiniarski** [comment]
@dharmelolar, I want to check on your progress again. Are you close to submitting a PR?

**Comment by dharmelolar** [comment]
@SSwiniarski I just opened a PR. I'm so sorry for the delay.
