### ISSUE TITLE
[Entry] SQL Commands: `CREATE INDEX`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#807]
### Reason/inspiration (optional)

Create a term entry for the `CREATE INDEX` SQL statement. Make sure to include the following sections:

- A "Syntax" section with a \```pseudo code snippet and descriptive text underneath.
- A "Codebyte Examlpe" section featuring a \```codebyte/sql snippet.

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) when creating the entry.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by sharkipelago** [comment]
Hi @Dusch4593 could I be assigned to this issue?

**Comment by Dusch4593** [comment]
@sharkipelago Sure! Assigned.

**Comment by sharkipelago** [comment]
@Dusch4593 Hi! I submitted a PR and I did add a code byte example, but noticed in the [content-standards.md](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) it doesn't list sql as having code byte support.

**Comment by Dusch4593** [comment]
It's true that SQL is supported in Codebytes. While I think it was left out of the list in `content-standards.md`by accident, implementing an SQL codebyte can be tricky because most of the time there isn't a table created beforehand.
