### ISSUE TITLE
[Entry] General: Big-O Notation

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#810]
### Reason/inspiration (optional)

Write a General concept entry about Big-O notation, including:

- What it is.
- How and why it is used to express the time/space complexity of algorithms.
- Usage of the [LaTeX code snippet](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/#latex) when using Big-O expressions.

Related issue: #759 

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by elliotfayman** [comment]
Hello, I think I can contribute to resolving this issue. I can create a md, pdf, txt, etc so which file type would you like and where should I insert the file? Thank you!

**Comment by Dusch4593** [comment]
Hi @elliotfayman and thanks for your interest in writing this entry! For the actual Docs entry, use a Markdown `.md` file. If you'd like to add media such as images, make sure to store in the `media/` folder and reference in the entry with the following format: `https://raw.githubusercontent.com/Codecademy/docs/main/media/filename.ext`.

For more information about getting starting/contributing in general: [Our CONTRIBUTING guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md).
For info about writing the actual Docs entry:
- [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md)
- [Entry Template](https://github.com/Codecademy/docs/blob/main/documentation/entry-template.md) (since this would be a concept entry)

**Comment by ethan-master-coding** [comment]
@Dusch4593 when the PR is merged can you tag me saying 
> forum featured challenged list thing
I will understand what you mean. (I want to link the entry in the post)

**Comment by elliotfayman** [comment]
Thank you. I will try to work on it as soon as I can!

**Comment by elliotfayman** [comment]
Ok, I submitted a pull request. I hope that the submission is satisfactory but if not, please let me know. Thank you!
