### ISSUE TITLE
[Entry] HTML: `<hr>` tag

### ISSUE THREAD

**Issue by not-a-ethan** [Codecademy/docs#827]
### Reason/inspiration (optional)

The `<hr>` tag is the equivalent of `___` in MD in HTML.

### Entry Type (select all that apply)

New Topic Entry, New Concept Entry for Existing Topic

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by Dusch4593** [comment]
Just for clarity: Inside the `html/concepts` directory, all HTML concept entries of this kind should be saved under `/elements` (**not** `/tags`), per [a recent change](https://github.com/Codecademy/docs/pull/811).

Also, for this entry, let's also mention that the `<hr>` element, in and of itself, is only meant to draw _semantic_ distinctions between pieces of content. Therefore, `<hr>` should still be styled with CSS for presentational purposes.

**Comment by sharkipelago** [comment]
Hi! I'm new to contributing to open source, but I think I can handle this issue. Do I have to fill anything out or just comment here?

**Comment by Dusch4593** [comment]
Hey @sharkipelago, sorry I'm super late getting to this. I went ahead and assigned you! 😄

**Comment by sharkipelago** [comment]
@Dusch4593 That was my bad I never pinged :sweat_smile:. I just submitted first draft of pr though!
