### ISSUE TITLE
[EDIT] General: JSON

### ISSUE THREAD

**Issue by not-a-ethan** [Codecademy/docs#829]
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

See [comment below](https://github.com/Codecademy/docs/issues/829#issuecomment-1187508337) for detailed description/instructions for this issue.

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by yhscherber** [comment]
Hey! I'm interested in working on this issue - would you mind assigning it to me? 🥳 Thanks!

**Comment by Dusch4593** [comment]
Hi @yhscherber! You're assigned 😄
