### ISSUE TITLE
[Edit] Java: Data Types + related entries

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#850]
### Type of Edit (select all that apply)

Clarify unclear content and/or terms

### Description (optional)

Add a section to the [Java: Data Types entry](https://www.codecademy.com/resources/docs/java/data-types) about **reference types**, including:

- Annotations
- Arrays
- Classes
- Enumeration
- Interfaces

For the following entries, include info about how the given concept is one of the reference data types (hyperlink back to Java: Data Types entry):

- [Arrays](https://www.codecademy.com/resources/docs/java/arrays)
- [Classes](https://www.codecademy.com/resources/docs/java/classes)
- [Enums](https://www.codecademy.com/resources/docs/java/enums)
- [Interfaces](https://www.codecademy.com/resources/docs/java/interfaces)

Let us know if you'd like to be assigned to this issue 😄

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by nimblegeek** [comment]
Hey! I would like to contribute to this, is it still open to work on?

**Comment by yangc95** [comment]
@nimblegeek assigned to you!

**Comment by nimblegeek** [comment]
Sorry but I don't think I properly understand this issue. Can I just commit and push the changes I find necessary? Related to i.e Arrays and some minor updates to primitive data types?

**Comment by yangc95** [comment]
Hey @nimblegeek, I'm wondering which part of the issue description is confusing.

Feel free to include other edits that you find necessary in your PR.

**Comment by SSwiniarski** [comment]
@nimblegeek it's been over two weeks since there's been any activity on this issue. Are you still working on this PR? Do you need further assistance?

**Comment by nimblegeek** [comment]
> @nimblegeek it's been over two weeks since there's been any activity on this issue. Are you still working on this PR? Do you need further assistance?

**Comment by nimblegeek** [comment]
@SSwiniarski hey, thanks for reminding me and sorry for dragging it for too long. I have been too busy with my day job. Haven't been able to spend time on this. I would have to get it unassigned.
Apologies for this.

**Comment by SSwiniarski** [comment]
@nimblegeek No problem. I'll unassign you so someone else can work on this.

**Comment by csavell** [comment]
Hey, this looks like something I can help with. Could you assign it to me?

**Comment by Dusch4593** [comment]
@csavell Sure thing! You're assigned. 😄

**Comment by csavell** [comment]
Thanks, I'll get on that asap
