### ISSUE TITLE
[Bug/Error] Subject: Double quotes vs Single quotes

### ISSUE THREAD

**Issue by alieldeba** [Codecademy/docs#852]
### Problem

- sometimes there is a task in the course that says import .... from .....
- and when I import it correctly an error message says "are you sure that you imported .... from ...."
- the solution was to use single quotes, not Double quotes 
- it seems not fair, so please fix this

### Example

✖️ import { store } from "./app/store.js"
✔️  import { store } from './app/store.js'

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by Dusch4593** [comment]
Hi @alieldeba 👋🏻 I believe this question was meant to go somewhere else. Check out [the forums](https://discuss.codecademy.com/t/faq-core-concepts-in-redux-introduction-to-redux/561527) to seek help with the lessons/exercises in the Redux course.

**Comment by lucwhite** [comment]
Hey @alieldeba thanks for submitting an issue! We strive to be as permissive as possible in our lessons, but it seems we may have slipped up there!

Unfortunately, this is the GitHub for the [Codecademy Docs](https://www.codecademy.com/resources/docs). Issues in our course content are handled by a different team, Curriculum Quality. 

If you go to the lesson exercise in which you encountered this issue, you can click the **Get Unstuck** button, and click on the **Bugs** tab, which will prompt you to describe the bug. Here's an article showing you [how to submit a bug/typo report](https://help.codecademy.com/hc/en-us/articles/220711148-Report-a-Bug-or-Typo).

Let me know if you have any questions!
