### ISSUE TITLE
[New Topic] Python:Seaborn

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#874]
### Reason/inspiration (optional)

Create a new topic for `Seaborn`.

Optional: Create a new terms folder with at least one term and up to two terms.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by yangc95** [comment]
@cjunhyuk

**Comment by cjunhyuk** [comment]
@yangc95 I can start with legend and mainly link out to `seaborn` from the `matplotlib` entries

**Comment by SSwiniarski** [comment]
@cjunhyuk I just want to follow up on how your progressing on this entry since there hasn't been any activity for a while. Just respond in this thread if you're still working on it or if you need any assistance.

**Comment by SSwiniarski** [comment]
@cjunhyuk, Because of the lack of activity on this issue I'm unassigning you so someone else can work on it.

**Comment by profithesame** [comment]
Hello, can I take this issue?
But i don't understand what to do)

> Create a new concept 
Need to create an article?

**Comment by SSwiniarski** [comment]
@profithesame you're assigned.

**Comment by SSwiniarski** [comment]
@profithesame, I unassigned you from this issue because the PR you submitted was lifted from another site. You are still free to claim an issue and submit a PR as long as the writings are your own.

**Comment by SSwiniarski** [comment]
@yangc95, Should this be a new topic like Pandas an NumPy rather than a new concept?

**Comment by yangc95** [comment]
> @yangc95, Should this be a new topic like Pandas an NumPy rather than a new concept?

@SSwiniarski works for me, I'll go ahead and change the issue description.

**Comment by BoboyeOkeya** [comment]
Hello, Please can I take this issue. I am presently asked to work on an open issue as part of my Learn Git/Github course on codeacademy.

Also, I do not know exactly what the task is about but I am willing to give it a try since Python is within my skillset

**Comment by SSwiniarski** [comment]
@BoboyeOkeya you're assigned. If you want an idea of how we want the entry to look, you can look at the source of the Pandas or NumPy topics in the repo. We want a similar one covering the Seaborn module.

**Comment by BoboyeOkeya** [comment]
@SSwiniarski Thank you for the assignment and for the explanation. I got it and I will start work!
