### ISSUE TITLE
[New Entry] C: Data Types

### ISSUE THREAD

**Issue by yangc95** [Codecademy/docs#886]
### Reason/inspiration (optional)

Create an entry on Data Types for [C](https://www.codecademy.com/resources/docs/c) language.

_Recommended to search throughout the C entries to see what types are mentioned and link out to this created data types entry. Questions are welcome!_

Let us know if you'd like to take this issue on! Tag someone on the team and ask to be assigned 😸 

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Nessvah** [comment]
@yangc95 Can I work on this issue?

**Comment by yangc95** [comment]
@Nessvah Yes, assigned you to this ☺️

**Comment by Nessvah** [comment]
@yangc95 @Dusch4593  Hi guys. Since there's a file about strings, should I copy and paste that information to the new file that I'm going to work on? Or is there a different way that I should approach this?

**Comment by Dusch4593** [comment]
@Nessvah It looks like [strings aren't necessarily regarded as a data type in C](https://www.cs.uic.edu/~jbell/CourseNotes/C_Programming/CharacterStrings.html#:~:text=Overview,terminated%20by%20a%20null%20byte.). Rather, they are arrays of `char`s (which _is_ one of the C data types).

An approach I would recommend for writing this entry is researching and outlining how C data types are classified. According to [the GNU manual for C](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#Data-Types), the entry could begin with a structure similar to this:

``` 
[paragraph of 3-5 sentences that introduces the concept of data types in C]

## Primitive Types

[1-2 sentences about this classification]

### Integer Types

[maybe a [markdown table](https://www.codecademy.com/resources/docs/markdown/tables) that include `int`/`unsigned int` and `char`/`unsigned char`?)

[followed by a small example]

### Real Number Types

[same thing, perhaps; a markdown table with 3 rows that includes info about `float`, `double`, and `long double`?)]

[again, followed by a small example]
```

**Comment by Nessvah** [comment]
You are completely right! I'm going to review my old classes on C and start to work on that. Thank you!
