### ISSUE TITLE
[Edit + Term Entries] C: Basic Output

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#893]
### Type of Edit (select all that apply)

Fix grammar, spelling, Clarify unclear content and/or terms, Add new content (definitions, codeblocks, etc.)

### Description (optional)

This entry needs the following edits:

### Line-specific

- Line # 3: meta-`Description` needs to be shortened to (ideally) 150 characters or less.
- Line # 15: Name of concept ("basic console output") needs to be **in bold**.
- Line # 19: Replace "typically" with "commonly".

### Other

The following sections in `basic-output.md` should be reallocated to separate term entries:

- "Print Character with `putchar()`"
- "Print Strings with `puts()`"
- "Print Formatted with `printf()`"

Create a new `terms/` folder under `c/concepts/basic-output/` along with the following folder-file pairs:

- `basic-output/terms/putchar/putchar.md`
- `basic-output/terms/puts/puts.md`
- `basic-output/terms/printf/printf.md`

For each term entry, be sure to include a "Syntax" section (with a \```pseudo code snippet) and an "Example" section (with a \```c code snippet).

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by TheZal** [comment]
I can work on this, pls assign it to me!

**Comment by adityaonstage** [comment]
Hii @Dusch4593. Pls let me contribute in this.

**Comment by Dusch4593** [comment]
@adityaonstage Looks like this issue had already been assigned to someone else recently. Plenty of other open issues to choose from, though. 😄
