### ISSUE TITLE
[Term Entry] Java Math Methods: `addExact()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#895]
### Reason/inspiration (optional)

Under `java/concepts/math-methods/terms/`, create a new term entry for the `Math.addExact()` Java method.

- In the `terms/` folder, make a new folder called `add-exact/`.
- Inside the `add-exact/` folder, create a new markdown file called `add-exact.md`.
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Also make sure to include an "Example" section with a \```java code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by shlok-2003** [comment]
@Dusch4593 I would love to work on this issue.

**Comment by Dusch4593** [comment]
@shlok-2003 Absolutely! You are now assigned 😄

**Comment by shlok-2003** [comment]
I am doing 2 documentation at the same time. so if I push both the readme files at same time. Do they count for both the issues

**Comment by Dusch4593** [comment]
> @Dusch4593 I am doing 2 documentation at the same time. so if I push both the readme files at same time. Do they count for both the issues

If I understand your question correctly, I would advise _against_ doing this because both issues were made separately to count as two distinct contributions towards Hacktoberfest. Creating a PR that closes more than one issue is definitely possible, but then it would be counted as _one_ Hacktoberfest contribution after the PR is merged.

**Comment by shlok-2003** [comment]
so I have to remove one of the file from the existing directory and I can add it after making a merge of the other file. Am I right

**Comment by Dusch4593** [comment]
@shlok-2003 Do we have a link for this merge request?

**Comment by shlok-2003** [comment]
Could you help me speed up the process of reviewing, as it hasn't been reviewed since yesterday
