### ISSUE TITLE
[Term Entry] Java Math Methods: `.cbrt()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#896]
### Reason/inspiration (optional)

Under `java/concepts/math-methods/terms/`, create a new term entry for the `Math.cbrt()` Java method.

- In the `terms/` folder, make a new folder called `cbrt/`
- Inside the `cbrt/` folder, create a new markdown file called `cbrt.md`
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Also make sure to include an "Example" section with a \```java code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Hariprasad19036** [comment]
I would like to work on this issue! Kindly assign this to me @Dusch4593 :)

**Comment by cryoung1998** [comment]
If this term is now available for assignment I would love to contribute!

**Comment by Dusch4593** [comment]
@cryoung1998 You're assigned! Thank you for your interest in contributing to Codecademy Docs. 😄
