### ISSUE TITLE
[Term Entry] Math Methods: `.decrementExact()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#898]
### Reason/inspiration (optional)

Under `java/concepts/math-methods/terms/`, create a new term entry for the `Math.decrementExact()` Java method.

- In the `terms/` folder, make a new folder called `decrement-exact`
- Inside the `decrement-exact` folder, create a new markdown file called `decrement-exact.md`.
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Also make sure to include an "Example" section with a \```java code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by isanketsaha** [comment]
@Dusch4593 , assign this to me.

**Comment by Dusch4593** [comment]
@isanketsaha assigned! 😄

**Comment by isanketsaha** [comment]
@Dusch4593 Raised PR. please review #1145
