### ISSUE TITLE
[Term Entry] Java Math Methods: `.incrementExact()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#901]
### Reason/inspiration (optional)

Under `java/concepts/math-methods/terms/`, create a new term entry for the `Math.incrementExact()` Java method.

- In the `terms/` folder, make a new folder called `increment-exact`
- Inside the `increment-exact` folder, create a new markdown file called `increment-exact.md`
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Also make sure to include an "Example" section with a \```java code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by isanketsaha** [comment]
Hey @Dusch4593 , can you please assign this to me?

**Comment by Dusch4593** [comment]
Hi @isanketsaha. Absolutely! You are assigned and thank you for your interest in contributing to Codecademy Docs 😄 🚀 

Quick question: How did you happen to learn about Docs and about contributing to it?

**Comment by isanketsaha** [comment]
Hello @Dusch4593. I have found this issue as part of hacktoberfest.

**Comment by isanketsaha** [comment]
Hello @Dusch4593. I have raised PR for this issue. Kindly check. 
PR number - 1140.
