### ISSUE TITLE
[Term Entries] Java Math Methods: logarithmic functions

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#902]
### Reason/inspiration (optional)

Under `java/concepts/math-methods/terms/`, create new term entries for the following methods:

- `Math.log()`
- `Math.log10()`
- `Math.log1p()`

- In the `terms/` folder, make a new folder for each method (i.e., `log`, `log10`, and `log1p`). 
- Inside the `log`, `log10`, and `log1p` folders, create a new markdown files called `log.md`, `log10.md`, and `log1p.md`, respectively.
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Also make sure to include an "Example" section with a \```java code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by itsvipindev** [comment]
Hello sir i would like to work on this issue

**Comment by Dusch4593** [comment]
@itsvipindev You got it! Assigned 😄 Just so you know, because you are also assigned to another issue, please open _one PR for each issue_ (e.g., one that closes #880 and a separate one that closes this one, #902).

**Comment by tanishq-singh-2301** [comment]
can I work on this?

**Comment by Dusch4593** [comment]
@tanishq-singh-2301 Assigned! 😄

**Comment by tanishq-singh-2301** [comment]
@Dusch4593 please review!!
