### ISSUE TITLE
[Term Entries] Java Math Methods: `.max()` and `.min()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#903]
### Reason/inspiration (optional)

Under `java/concepts/math-methods/terms/`, create a new term entry for the `Math.max()` and `Math.min()` Java methods.

- In the `terms/` folder, make new folders called `max` and `min`.
- Inside the `max` and `min` folders, create a new markdown file called `max.md` and `min.md`, respectively.
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Also make sure to include an "Example" section with a \```java code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by MinalGhate** [comment]
Hello sir I would like to work on this issue

**Comment by Dusch4593** [comment]
@MinalGhate You're assigned! Thanks for your interest in contributing to Codecademy Docs. 😄
