### ISSUE TITLE
[Term Entry] Java Math Methods: `.nextAfter()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#906]
### Reason/inspiration (optional)

Under `java/concepts/math-methods/terms/`, create a new term entry for the `Math.nextAfter()` Java method.

- In the `terms/` folder, make a new folder called `next-after`
- Inside the `next-after` folder, create a new markdown file called `next-after.md`.
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Also make sure to include an "Example" section with a \```java code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by YanisaHS** [comment]
Hi @Dusch4593 or @SSwiniarski , would you be able to assign this to me? I actually have 3 PRs open now though, so no worries if you can't! Just trying to do a 4th one to finish hacktoberfest 🥳

**Comment by yangc95** [comment]
@YanisaHS Thanks for putting your PRs on our radar! I've assigned you this in the meantime while I review your open PRs.
