### ISSUE TITLE
[Term Entry] Java Math Methods: `.pow()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#909]
### Reason/inspiration (optional)

Under `java/concepts/math-methods/terms/`, create a new term entry for the `Math.pow()` Java method.

- In the `terms/` folder, make a new folder called `pow`
- Inside the `pow` folder, create a new markdown file called `pow.md`.
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Also make sure to include an "Example" section with a \```java code snippet.

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy)

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by SSwiniarski** [comment]
@sharkipelago, done. And thanks for your interest in contributing.

**Comment by sharkipelago** [comment]
@SSwiniarski submitted the first draft PR!
