### ISSUE TITLE
[Term Entry] Java Math Methods: `.rint()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#910]
### Reason/inspiration (optional)

Under `java/concepts/math-methods/terms/`, create a new term entry for the `Math.rint()` Java method.

- In the `terms/` folder, make a new folder called `rint`
- Inside the `rint` folder, create a new markdown file called `rint.md`.
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Also make sure to include an "Example" section with a \```java code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by jcesardv** [comment]
@SSwiniarski I would like to take up this issue.

**Comment by Dusch4593** [comment]
@jcesardv Assigned! 😄

**Comment by jcesardv** [comment]
@Dusch4593 I already completed the review.
