### ISSUE TITLE
[Term Entry] Java Math Methods: `.scalb()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#911]
### Reason/inspiration (optional)

Under `java/concepts/math-methods/terms/`, create a new term entry for the `Math.scalb()` Java method.

- In the `terms/` folder, make a new folder called `scalb`
- Inside the `scalb` folder, create a new markdown file called `scalb.md`.
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Also make sure to include an "Example" section with a \```java code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Bobliuuu** [comment]
Hey @Dusch4593, can I take this issue?

**Comment by SSwiniarski** [comment]
@Bobliuuu, you've been assigned. Thanks for contributing.

One question, how did you come across this repo?

**Comment by Bobliuuu** [comment]
Through the Hacktoberfest label!

**Comment by SSwiniarski** [comment]
@Bobliuuu just wanted to check on your progress on this entry. Just reply in this thread if you're still working on it or if you need any help. Reminder there's only two days left for credit in hacktoberfest.

**Comment by Bobliuuu** [comment]
Hi @SSwiniarski, I already have my 4 PRs for Hacktoberfest, and I am a bit busy at the moment. I will complete this in the next 4 days (if that's okay)!

**Comment by SSwiniarski** [comment]
@Bobliuuu, that's fine. Just want to make sure that issues that are assigned are still being worked on.

**Comment by SSwiniarski** [comment]
@Bobliuuu just checking on your progress again.

**Comment by Bobliuuu** [comment]
Will do today, sorry for the delay.

**Comment by Bobliuuu** [comment]
@SSwiniarski done!
