### ISSUE TITLE
[Term Entry] Java Math Methods: `.signum()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#912]
### Reason/inspiration (optional)

Under `java/concepts/math-methods/terms/`, create a new term entry for the `Math.signum()` Java method.

- In the `terms/` folder, make a new folder called `signum`
- Inside the `signum` folder, create a new markdown file called `signum.md`.
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Also make sure to include an "Example" section with a \```java code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by Hariprasad19036** [comment]
I would like to work on this issue! Kindly assign this to me.

**Comment by SSwiniarski** [comment]
@Hariprasad19036, you've been assigned. Thanks for contributing.

Quick question, how did you come across this repo?

**Comment by Hariprasad19036** [comment]
Thanks @SSwiniarski ! I have actually contributed to this repo previously this month. I found this repo when I was searching for issues on the https://github.com/issues page.

**Comment by Hariprasad19036** [comment]
Hey @SSwiniarski, I've raised a PR for this issue. Kindly review it!
