### ISSUE TITLE
[Term Entry] Java Math Methods: `.sin()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#913]
### Reason/inspiration (optional)

Under `java/concepts/math-methods/terms/`, create a new term entry for the `Math.sin()` Java method.

- In the `terms/` folder, make a new folder called `sin`
- Inside the `sin` folder, create a new markdown file called `sin.md`.
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Also make sure to include an "Example" section with a \```java code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Yash-Var** [comment]
@SSwiniarski i want to work on this ....

**Comment by Yash-Var** [comment]
@SSwiniarski  assigne it to me ...

**Comment by Dusch4593** [comment]
@Yash-Var Assigned!

**Comment by Dusch4593** [comment]
Hey @Yash-Var! Just wanted to check in to see how things were going for you on your `.sin()` term entry? Let us know if you have any questions! 😄

**Comment by SSwiniarski** [comment]
@Yash-Var, because of the lack of activity on this entry, I'm unassigning you so someone else can work on it.

**Comment by TrishaGupta** [comment]
Can I get assigned to this?

**Comment by Dusch4593** [comment]
@TrishaGupta Sure thing! 😄 Thanks for your interest in contributing to Codecademy Docs! 🚀

By chance, how did you learn about Docs and about contributing to it?

**Comment by SSwiniarski** [comment]
@TrishaGupta it's been two weeks since you were assigned. Are you still working on this PR? Do you need any assistance?

**Comment by SSwiniarski** [comment]
@TrishaGupta because of more than two weeks of inactivity, I am unassigning you so someone else can work on this issue.

**Comment by Yash-Var** [comment]
@SSwiniarski @Dusch4593 i will complete this issue and complete with in three days....

**Comment by Yash-Var** [comment]
@Dusch4593 @Dusch4593 ps assign me ...

**Comment by SSwiniarski** [comment]
@Yash-Var, you've been assigned.

**Comment by Yash-Var** [comment]
@Dusch4593 ps review my pr...
