### ISSUE TITLE
[Term Entry] Java Math Methods: `.sqrt()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#915]
### Reason/inspiration (optional)

Under `java/concepts/math-methods/terms/`, create a new term entry for the `Math.sqrt()` Java method.

- In the `terms/` folder, make a new folder called `sqrt`
- Inside the `sqrt` folder, create a new markdown file called `sqrt.md`.
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Also make sure to include an "Example" section with a \```java code snippet.

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy)

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Yash-Var** [comment]
@SSwiniarski I want to do this can you assign it to me .....

**Comment by KTom101** [comment]
@Yash-Var Thank you for your interest in contributing to Codecademy Docs! I've assigned you to this issue.

You can take a look at the [contribution guide ](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for more information about contributing. Also, feel free to reach out if you have any other questions.

**Comment by Yash-Var** [comment]
@KTom101 I have not  find the folder       java/concepts/math-methods/terms/     can you provided it  folder java   ...........

**Comment by Yash-Var** [comment]
@KTom101 I have made a PR review it and guide me ..........

**Comment by Yash-Var** [comment]
@SSwiniarski I have made a PR review it and guide me ..........

**Comment by Yash-Var** [comment]
@Dusch4593  why you have closed the link pull request . If in my PR there is some bug and error so, you can guide me .......

**Comment by Dusch4593** [comment]
@Yash-Var I closed the PR because the entry contained content that was near identical to an outside, non-Codecademy source. When contributing content to Codecademy, you have to write and submit original content with your own examples and output. You can read more [here](https://github.com/Codecademy/docs/pull/927#issuecomment-1227616514) for more information, but I'm asking that you rewrite the entry and open a new pull request for the `.sqrt()` method.

**Comment by Yash-Var** [comment]
@Dusch4593 okk
