### ISSUE TITLE
[Term Entry] Java Math Methods: `.subtractExact()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#916]
### Reason/inspiration (optional)

Under `java/concepts/math-methods/terms/`, create a new term entry for the `Math.subtractExact()` Java method.

- In the `terms/` folder, make a new folder called `subtract-exact`
- Inside the `subtract-exact` folder, create a new markdown file called `subtract-exact.md`.
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Also make sure to include an "Example" section with a \```java code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by shivanshugour45** [comment]
Please assign this to me.

**Comment by Dusch4593** [comment]
@shivanshugour45 Assigned! Thank you for your interest in contributing to Codecademy Docs. 😄

**Comment by shivanshugour45** [comment]
I was searching for some good first issues to start contributing with and found this while exploring GitHub.

**Comment by shivanshugour45** [comment]
Please review the request and suggest changes if any.

**Comment by itsarraj** [comment]
Hello sir ,
I am new to open source contribution.
I already know java , my tech stacks & tools includes C, C++ , Python , Java, JavaScript , HTML , CSS , SQL , Bootstrap, ReactJS, ExpressJS, NodeJS & Git . I need a little help from your side to contribute to these amazing projects.
