### ISSUE TITLE
[Term Entry] Java Math Methods: `.tan()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#917]
### Reason/inspiration (optional)

Under `java/concepts/math-methods/terms/`, create a new term entry for the `Math.tan()` Java method.

- In the `terms/` folder, make a new folder called `tan`
- Inside the `tan` folder, create a new markdown file called `tan.md`.
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Also make sure to include an "Example" section with a \```java code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by sumedhav2004** [comment]
Please assign it to me.

**Comment by SSwiniarski** [comment]
@sumedhav2004, you've been assigned!

**Comment by sumedhav2004** [comment]
Unassigning me because i was assigned 5 issues at once. Please assign it to others.

**Comment by shlok-2003** [comment]
@SSwiniarski please assign it to me

**Comment by Dusch4593** [comment]
@shlok-2003 You got it! Glad you found one. 😄

**Comment by shlok-2003** [comment]
@Dusch4593 I have some doubts, so how could I get help from you guys ?

**Comment by SSwiniarski** [comment]
@shlok-2003 You can tag us in a question and one of us will try to get back to you. If your questions are about structure and format you can also look at the documentation [here](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md).
