### ISSUE TITLE
[Term Entry] Java Math Methods: `.toIntExact()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#920]
### Reason/inspiration (optional)

Under `java/concepts/math-methods/terms/`, create a new term entry for the `Math.toIntExact()` Java method.

- In the `terms/` folder, make a new folder called `to-int-exact`
- Inside the `to-int-exact` folder, create a new markdown file called `to-int-exact.md`.
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Also make sure to include an "Example" section with a \```java code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by sumedhav2004** [comment]
Please assign it to me.

**Comment by SSwiniarski** [comment]
@sumedhav2004, you've been assigned. Thanks for contributing.

One question, how did you come across this repo?

**Comment by sumedhav2004** [comment]
I found these issues using the hacktoberfest label.
Unassigning me because i was assigned 5 issues at once. Please assign it to others. 😃

**Comment by shivanshugour45** [comment]
I would Like to work on this please assign it to me.

**Comment by SSwiniarski** [comment]
@shivanshugour45, you're assigned. Thanks for contributing.

One question, how did you come across this repo?

**Comment by shivanshugour45** [comment]
Hi @SSwiniarski , I was searching for good first issues using hacktoberfest label and this came up.

**Comment by shivanshugour45** [comment]
Please review the file and suggest changes if any.

**Comment by vipul-027** [comment]
> ### Reason/inspiration (optional)
> Under `java/concepts/math-methods/terms/`, create a new term entry for the `Math.toIntExact()` Java method.
> 
> * In the `terms/` folder, make a new folder called `to-int-exact`
> * Inside the `to-int-exact` folder, create a new markdown file called `to-int-exact.md`.
> * Inside the file, be sure to include a "Syntax" section with a ```pseudo code snippet.
> * Also make sure to include an "Example" section with a ```java code snippet.
> 
> Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.
> 
> ### Entry Type (select all that apply)
> New Term for Existing Concept Entry
> 
> ### Code of Conduct
> * [x]  I agree to follow Codecademy Doc's Code of Conduct
> 
> ### For Maintainers
> * [x]  Labels added
> * [x]  Issue is assigned

I would Like to work on this please assign it to me.

**Comment by SSwiniarski** [comment]
@vipul-027 this issue was already assigned and a PR has been made for it. If you're looking for a similar issue [this one](https://github.com/Codecademy/docs/issues/905) hasn't been assigned yet.

**Comment by itsarraj** [comment]
Hello sir ,
I am new to open source contribution.
I already know java , my tech stacks & tools includes C, C++ , Python , Java, JavaScript , HTML , CSS , SQL , Bootstrap, ReactJS, ExpressJS, NodeJS & Git . I need a little help from your side to contribute to these amazing projects.

**Comment by SSwiniarski** [comment]
@itsarraj you can start by looking at [issues](https://github.com/Codecademy/docs/issues) and finding an open unassigned issue you would like to contribute. Then you can work on a PR for that issue. This one has been closed for a while.
