### ISSUE TITLE
[Entry] General: Yukihiro Matsumoto

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#934]
### Reason/inspiration (optional)

Please write a new concept entry in the "General" topic about Yukihiro Matsumoto (Matz), the designer/developer of the Ruby programming language.

- Be sure to include an image of Matz near the top of the entry, that is (preferably) less than 1 MB in size.
- Use other existing Doc entries like the ones for [Aaron Swartz](https://www.codecademy.com/resources/docs/general/aaron-swartz) and [Tim Berners-Lee](https://www.codecademy.com/resources/docs/general/tim-berners-lee) as guidance/inspiration.
- Make sure to include a reference/link back to the [Ruby](https://www.codecademy.com/resources/docs/ruby) topic in Docs: https://www.codecademy.com/resources/docs/ruby

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by mosmoo** [comment]
Hi, I'd like to request the permission to work on this issue.

**Comment by Dusch4593** [comment]
@mosmoo Absolutely! You're assigned 😄 

Thank you for your interest in contributing to Codecademy Docs! 🚀

I was curious, how did you happen to learn about Docs and about contributing to it?

**Comment by mosmoo** [comment]
> @mosmoo Absolutely! You're assigned 😄
> 
> Thank you for your interest in contributing to Codecademy Docs! 🚀
> 
> I was curious, how did you happen to learn about Docs and about contributing to it?

I just finished the Learn Git and Github course on Codecademy and I was redirected here to work on an issue! Super Excited, Thank you very much!
