### ISSUE TITLE
[Entry] General: Environment Variables

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#948]
### Reason/inspiration (optional)

Please write a new concept entry for **environment variables** under the General topic.

- Since this is a General entry, try to avoid language-specific information.
- But do include info about its relationship with Unix and Unix-like variants (Linux).
  - Go ahead and link out to the Docs entries for [Linux](https://www.codecademy.com/resources/docs/general/linux) and [Unix](https://www.codecademy.com/resources/docs/general/unix), as well.
- Include a list of the most common environment variables. (`PATH`, `HOME`, etc.)

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by joneskj55** [comment]
Hey @Dusch4593 I'll take this one if no one else is to be assigned.

**Comment by sumedhav2004** [comment]
I would love to work on this. Please assign it to me.

**Comment by Dusch4593** [comment]
Hey @sumedhav2004 you've already been assigned to two other issues. We typically like to limit each contributor to **three (3)** open issues/PRs at a given time. For your third, would you like to be assigned to this issue (about env variables) or to #952 (about `atan2()` C++ function)?

**Comment by gracekishino** [comment]
Hello! Please can I work on this?

**Comment by Dusch4593** [comment]
Hi @gracekishino! Thanks for your interest in contributing to Codecademy Docs! 😄

I've assigned to you.

**Comment by gracekishino** [comment]
@Dusch4593 Thanks for assigning to me! 

As far as I can tell, there isn't a page for [Linux](https://www.codecademy.com/resources/docs/general/linux) yet, shall I add one in?

**Comment by gracekishino** [comment]
> @Dusch4593 Thanks for assigning to me!
> 
> As far as I can tell, there isn't a page for [Linux](https://www.codecademy.com/resources/docs/general/linux) yet, shall I add one in?

It's OK, I found it here :)
[Linux](https://www.codecademy.com/resources/docs/open-source/linux)
