### ISSUE TITLE
[Entry] General: Optimization

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#949]
### Reason/inspiration (optional)

Please write a new General concept entry that defines **optimization** in programming. Make sure to also include a section about the various "levels" of optimization:

```pseudo
## Levels of Optimization

### Design

### Algorithms

### Source Code

### Builds

### Compilers

### Run Time

### Platform Dependence and Independence
```

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by tejas0124** [comment]
Can I Work On This Issue?

**Comment by Dusch4593** [comment]
@tejas0124 You sure can! Assigned. 😄

**Comment by SSwiniarski** [comment]
@tejas0124  I wanted to check on your progress on this issue. Please respond in this thread if you're still working on it or if you need assistance. Reminder, there's only two days left for credit in hacktoberfest.

**Comment by SSwiniarski** [comment]
@tejas0124 your PR was closed because it was primarily sourced from Wikipedia. Do you still intend to submit a PR for this issue that is your own work?

**Comment by SSwiniarski** [comment]
@tejas0124, since it's been a week, I'm going to assign this to @YKWIBN.

@YKWIBN, you're now assigned this issue.

**Comment by YKWIBN** [comment]
Great, thank you!

**Comment by Dusch4593** [comment]
Un-assigned @YKWIBN at their request. Issue re-opened for assignment.

**Comment by KaizenEngineer** [comment]
Greetings to all... May I take a shot at this bad boy. 
Hopefully it won't be kicking this noob to fiercely.., lol
Perhaps, best it should..

**Comment by yangc95** [comment]
> Greetings to all... @Dusch4593 @SSwiniarski  
> 
> Would appreciate the opportunity to take a shot at this bad boy. 
> 
> Hopefully it won't be kicking this noob to fiercely... ;)
> 
> Perhaps, best it should.  
> 
> Grateful regards. 

@KaizenEngineer thanks for your interest, you been assigned! Make sure to follow up with a PR within the 2-week timeframe. Also, how did you discover contributing to Docs?

**Comment by KaizenEngineer** [comment]
Amazing! @yangc95
Thank you kindly... 
It was through the Learn Git & GitHub Course. Figured this additional course would benefit my learning whilst getting the FEE Career Path done.
