### ISSUE TITLE
[Term Entry] C++ Math Functions: `atanh()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#955]
### Reason/inspiration (optional)

Under `cpp/concepts/math-functions/terms/`, create a new term entry for the `atanh()` function.

- In the `terms/` folder, make a new folder called `atanh`
- Inside the `atanh` folder, create a new markdown file called `atanh.md`
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Let's include an "Example" section with a \```cpp code snippet.
- Lastly, let's include a "Codebyte Example" with a runnable \```codebyte/cpp

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by sumedhav2004** [comment]
Hi,I would love to work on it.Please assign it to me.
