### ISSUE TITLE
[Term Entry] C++ Math Functions: `log()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#956]
### Reason/inspiration (optional)

Under `cpp/concepts/math-functions/terms/`, create a new term entry for the `log()` function.

- In the `terms/` folder, make a new folder called `log`
- Inside the `log` folder, create a new markdown file called `log.md`
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Let's include an "Example" section with a \```cpp code snippet.
- Lastly, let's include a "Codebyte Example" with a runnable \```codebyte/cpp

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Hitarth-Kothari** [comment]
@Dusch4593  I wish to be assigned

**Comment by Dusch4593** [comment]
@Hitarth-Kothari Sure thing! Let's have you work on the three issues for now (including this one). As the attached PRs get merged, feel free to ask to be assigned to another open issue! 😄

**Comment by Hitarth-Kothari** [comment]
Will do

**Comment by Dusch4593** [comment]
Thanks, @Hitarth-Kothari! Also, I was curious, how/where did you hear about contributing to Codecademy Docs?

**Comment by Hitarth-Kothari** [comment]
https://goodfirstissues.com/
I'm new to open source so this is where i found this repo

**Comment by Dusch4593** [comment]
Firstly, we're happy your starting your open-source journey with us! 🎉 Secondly, that is a cool resource that I've never stumbled upon before! Thank you for sharing 😄
