### ISSUE TITLE
[Term Entry] C++ Math Functions: `fmod()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#963]
### Reason/inspiration (optional)

Under `cpp/concepts/math-functions/terms/`, create a new term entry for the `fmod()` function,

- In the `terms/` folder, make a new folder called `fmod`
- Inside the `fmod` folder, create a new markdown file called `fmod.md`
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Let's include an "Example" section with a \```cpp code snippet.
- Lastly, let's include a "Codebyte Example" with a runnable \```codebyte/cpp

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by itsTodFod** [comment]
I would like to resolve the issue.

**Comment by Dusch4593** [comment]
@itsTodFod Assigned to you! 😄 I was curious, how did you learn about Codecademy Docs and the repository you can contribute to?

**Comment by itsTodFod** [comment]
I found it using the labels i learned about while attending a Hacktober based event.
