### ISSUE TITLE
[Term Entry] C++ Math Functions: `fmin()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#965]
### Reason/inspiration (optional)

Under `cpp/concepts/math-functions/terms/`, create a new term entry for the `fmin()` function.

- In the `terms/` folder, make a new folder called `fmin`
- Inside the `fmin` folder, create a new markdown file called `fmin.md`
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Let's include an "Example" section with a \```cpp code snippet.
- Lastly, let's include a "Codebyte Example" with a runnable \```codebyte/cpp

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by borntofrappe** [comment]
`fmin` is quite similar to `fmax` #964. Let me know if I can participate to this issue as well, I'll try to keep a consistent style for the entries.

**Comment by borntofrappe** [comment]
Sure. Since one is the mirror of the other I will wait for your suggestions on #964 though.

**Comment by Dusch4593** [comment]
@borntofrappe You may start drafting a PR for either one of these (`fmin()` or `fmax()`).
