### ISSUE TITLE
[Term Entry] C++ Math Functions: `isfinite()`

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#966]
### Reason/inspiration (optional)

Under `c++/concepts/math-functions/terms/`, create a new term entry for the `isfinite()` function.

- In the `terms/` folder, make a new folder called `isfinite`
- Inside the `isfinite` folder, create a new markdown file called `isfinite.md`
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Let's include an "Example" section with a \```cpp code snippet.
- Lastly, let's include a "Codebyte Example" with a runnable \```codebyte/cpp

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Dusch4593** [comment]
@Hitarth-Kothari thanks for taking on this issue and opening a PR! 🙏🏻

Could you comment back on this thread so I can formally assign you to this?

**Comment by Hitarth-Kothari** [comment]
Yep

**Comment by Dusch4593** [comment]
Awesome, thanks @Hitarth-Kothari! Anytime you wanna open a PR to address one of these issues, feel free to ask to be assigned beforehand and we'll assign you. 😄
