### ISSUE TITLE
[Edit] C++ Math Functions: `cosh()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#979]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting
Clarify unclear content and/or terms
Add new content (definitions, codeblocks, etc.)

### Description (optional)

Requesting edits for the [cosh()](https://www.codecademy.com/resources/docs/cpp/math-functions/cosh) term entry under the C++: Math Functions concept.

Under `cpp/concepts/math-functions/terms/cosh/cosh.md`, please make the following edits:

- Revise the opening sentence to refer to the term "cosh()" by name (and **bold** this term, as well)
- In the "Syntax" section:
  - Rename any and all parameters to something more informative and descriptive, if possible.
  - If there is no text underneath the \```pseudo snippet, please add 1-2 sentences that describe the parameters of the `cosh()` function as well as the return value.
- Remove any phrasing that is instructive in tone, as opposed to informational. For example, something like "Use the `cosh()` function to..." should be revised to something akin to "The following example uses the `cosh()` function to..."
- If there is no Codebyte example, please add a new "Codebyte Example" section with 1-2 sentences previewing a \```codebyte/cpp code snippet.

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by kitrak-rev** [comment]
I would like to be assigned with this task

**Comment by yangc95** [comment]
Hi @kitrak-rev,

Just assigned you this issue! Please tag myself or any of the maintainers if you have any questions you have prior to submitting a PR. Also, feel free to explore all parts of this repo.

Quick question: How did you learn about contributing to Codecademy Docs?

**Comment by kitrak-rev** [comment]
#1050 I have opened a PR, @yangc95 it seems to have met with an error, kindly let me know what other changes I need to do. I learnt about Codeacademy Docs from my friend
