### ISSUE TITLE
[Term Entry] C++ Math Functions: `nan()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#982]
### Reason/inspiration (optional)

Under `cpp/concepts/math-functions/terms/`, create a new term entry for the `nan()` function.

- In the terms/ folder, make a new folder called `nan`
- Inside the `nan()` folder, create a new markdown file called `nan.md`
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Let's include an "Example" section with a \```cpp code snippet.
- Lastly, let's include a "Codebyte Example" with a runnable \```codebyte/cpp

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by chiragcode11** [comment]
Can you assign this issue to me.

**Comment by SSwiniarski** [comment]
@chiragcode11, you've been assigned. Thanks for contributing.

Quick question, how did you come across this repo?

**Comment by chiragcode11** [comment]
was searching for contribution for hacktoberfest and came across this repo.

**Comment by chiragcode11** [comment]
I have also contributed to  codecadmy's another term entry and now, when I am creating a PR the previous changes are also getting along with it. what should I do now?

**Comment by SSwiniarski** [comment]
@chiragcode11, You should have a separate fork for each PR. That allows you to do two PRs and not have them interfere with each other.

**Comment by chiragcode11** [comment]
@SSwiniarski but it is not allowing me to do another fork as I have already forked it for the previous term entry

**Comment by SSwiniarski** [comment]
@chiragcode11 you need a new fork off the main branch for the other PR.

**Comment by chiragcode11** [comment]
@SSwiniarski how can I create another fork as it is not allowing me to.
please suggest the procedure

**Comment by SSwiniarski** [comment]
@chiragcode11, I may be confusing you because I was misspeaking. What we really want is a separate **branch** for each PR on your forked repository. This page [here](https://reflectoring.io/github-fork-and-pull/#:~:text=Creating%20a%20fork%20on%20GitHub,to%20the%20fork%20on%20GitHub.) may be helpful. Look at the section "Working on multiple pull requests at once."
