### ISSUE TITLE
[Term Entry] C++ Math Functions: `remainder()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#984]
### Reason/inspiration (optional)

Under `cpp/concepts/math-functions/terms/`, create a new term entry for the `remainder()` function.

- In the terms/ folder, make a new folder called `remainder`
- Inside the `remainder` folder, create a new markdown file called `remainder.md`
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Let's include an "Example" section with a \```cpp code snippet.
- Lastly, let's include a "Codebyte Example" with a runnable \```codebyte/cpp

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by kavin5kumar** [comment]
I would want to work on this. Please assign me!

**Comment by SSwiniarski** [comment]
@kavin5kumar, I've assigned you. Thanks for contributing.

Quick question, how did you find this repo?

**Comment by SSwiniarski** [comment]
@kavin5kumar  I wanted to check on your progress on this issue. Please respond in this thread if you're still working on it or if you need assistance. Reminder, there's only two days left for credit in hacktoberfest.

**Comment by ddiegow** [comment]
Hi, I'd like to work on this issue if the original assignee can't do it anymore.

**Comment by SSwiniarski** [comment]
@ddiegow we like to give the original assignee a week or so to respond. We'll let you know then.

**Comment by ddiegow** [comment]
@SSwiniarski OK, thanks

**Comment by SSwiniarski** [comment]
@kavin5kumar because it's been several weeks without activity, I'm going to assign @ddiegow to this issue.

@ddiegow, you're now assigned.

**Comment by ddiegow** [comment]
Thanks @SSwiniarski, will get on it

**Comment by ddiegow** [comment]
Hi, I'm ready to make a pull request.  Should I do something on this thread or just make the pull request from my branch?

**Comment by SSwiniarski** [comment]
@ddiegow, you can go ahead and make your PR. Under the development header to the right on this page, you'll be able to link the PR to this issue.

**Comment by ddiegow** [comment]
@SSwiniarski I think I might have put my foot in it when making the commits.  It seems I didn't add an e-mail address to my commits and I'm getting a "Daniel seems not to be a GitHub user." message at the bottom of my pull request.  I did sign the CLA agreement with this account but it's still showing as CLA not signed.  How should I proceed in order to fix it?

**Comment by SSwiniarski** [comment]
@Dusch4593, any insight on how to help @ddiegow?

**Comment by Dusch4593** [comment]
Hey @ddiegow! 👋🏻 

I'm going to check with some colleagues on Monday to learn the best course of action for this situation. You may have already learned this, but you can always confirm which email that is configured with Git across all repositories:

```
git config --global user.email
```

You can do the same with the username:

```
git config --global user.name
```

I'll follow up on Monday about this. 😄

**Comment by ddiegow** [comment]
@Dusch4593 @SSwiniarski Thanks! I was able to change the mail and commit changes correctly.  I was also able to correct the linting errors and hopefully the formatting error too in my last push.  I'll start working on another task I've been assigned while waiting for the follow up on Monday.  Thanks again for your help, I'm learning a lot 😄

**Comment by Dusch4593** [comment]
@ddiegow I received some feedback from my colleagues! However, I still need time to process how to implement this fix but I wanted to encourage you to go ahead and implement the feedback from the first review #1239. 😄
