### ISSUE TITLE
[Term Entry] C++ Math Functions: `rint()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#985]
### Reason/inspiration (optional)

Under `cpp/concepts/math-functions/terms/`, create a new term entry for the `rint()` function.

- In the terms/ folder, make a new folder called `rint`
- Inside the `rint` folder, create a new markdown file called `rint.md`
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Let's include an "Example" section with a \```cpp code snippet.
- Lastly, let's include a "Codebyte Example" with a runnable \```codebyte/cpp

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Dusch4593** [comment]
@chiragcode11 Assigned! Thank you for your interest in Codecademy Docs! 😄

I was wondering how you first learned about Docs and how you can contribute to it? Always curious about how our learners discover our content and products.

**Comment by Dusch4593** [comment]
Hey @chiragcode11 unfortunately you will have to resubmit a PR for this issue. See [my note](https://github.com/Codecademy/docs/pull/1070#issuecomment-1270453396) for details.

**Comment by chiragcode11** [comment]
@Dusch4593 will this contribution considered for hacktoberfest

**Comment by Dhanunjay18** [comment]
Hello , plz assign this issue to me

**Comment by SSwiniarski** [comment]
@Dhanunjay18, this issue has already been assigned and there's a existing PR that addresses it.

@chiragcode11, this does count for hacktoberfest.

**Comment by shlok-2003** [comment]
please assign me this issue

**Comment by Dusch4593** [comment]
@shlok-2003 I'm sorry but it looks like PE #1084 was already created to address this issue so we won't be able to assign this one. But feel free to check out any of the other open issues [here](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee+label%3A%22good+first+issue%22). 😄

**Comment by Dusch4593** [comment]
@shlok-2003 I would say skip making an issue for whatever you'd like to work on and open a new pull request. 😄 But I strongly advise that you look through the ["Issues" tab](https://github.com/Codecademy/docs/issues) beforehand and make sure there isn't already an issue created and/or assigned to someone else.
