### ISSUE TITLE
[Term Entry] C++ Math Functions: `signbit()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#989]
### Reason/inspiration (optional)

Under `cpp/concepts/math-functions/terms/`, create a new term entry for the `signbit()` function.

- In the terms/ folder, make a new folder called `signbit`
- Inside the `signbit` folder, create a new markdown file called `signbit.md`
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Let's include an "Example" section with a \```cpp code snippet.
- Lastly, let's include a "Codebyte Example" with a runnable \```codebyte/cpp

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [X] Issue is assigned

**Comment by AravindShounik** [comment]
I would like to work on this. Please assign it to me.

**Comment by SSwiniarski** [comment]
@AravindShounik, I've assigned you. Thanks for contributing.

Quick question, how did you come across this repo?

**Comment by AravindShounik** [comment]
I was searching for a good first issue because I recently started contributing and I came across this repo
