### ISSUE TITLE
[Term Entry] C++ Math Functions: `nearbyint()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#991]
### Reason/inspiration (optional)

Under `cpp/concepts/math-functions/terms/`, create a new term entry for the `nearbyint()` function.

- In the terms/ folder, make a new folder called `nearbyint`
- Inside the `nearbyint` folder, create a new markdown file called `nearbyint.md`
- Inside the file, be sure to include a "Syntax" section with a \```pseudo code snippet.
- Let's include an "Example" section with a \```cpp code snippet.
- Lastly, let's include a "Codebyte Example" with a runnable \```codebyte/cpp

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by codewithdev** [comment]
@Dusch4593 Could you please assign this to me?

**Comment by Dusch4593** [comment]
@codewithdev Assigned! 😊

**Comment by chiragcode11** [comment]
Could you please, assign this to me as well?

**Comment by Dusch4593** [comment]
Hey @chiragcode11! This issue has already been assigned (with a pull request created) and we generally assign just one contributor to one issue. Feel free to check out our list of C++ issues that have not yet been assigned: https://github.com/Codecademy/docs/issues?q=is%3Aopen+is%3Aissue+label%3Ac%2B%2B+no%3Aassignee
