### ISSUE TITLE
[Edit] C++ Math Functions: `exp()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#993]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting
Clarify unclear content and/or terms
Add new content (definitions, codeblocks, etc.)

### Description (optional)

Requesting edits for the [exp()](https://www.codecademy.com/resources/docs/cpp/math-functions/exp) term entry under the C++: Math Functions concept.

Under `cpp/concepts/math-functions/terms/exp/exp()`, please make the following edits:

- Revise the opening sentence to refer to the term "exp()" by name (and **bold** this term, as well)
- In the "Syntax" section:
  - Rename any and all parameters to something more informative and descriptive, if possible.
  - If there is no text underneath the \```pseudo snippet, please add 1-2 sentences that describe the parameters of the `exp()` function as well as the return value.
- Remove any phrasing that is instructive in tone, as opposed to informational. For example, something like "Use the `exp()` function to..." should be revised to something akin to "The following example uses the `exp()` function to..."
- If there is no Codebyte example, please add a new "Codebyte Example" section with 1-2 sentences previewing a \```codebyte/cpp code snippet.

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by borntofrappe** [comment]
Good morning maintainers.

If at all possible I'd like to contribute to the issue. I've looked at the example of the entry you crafted for the [`log`](https://www.codecademy.com/resources/docs/cpp/math-functions/log) function and I think I've a good handle on the necessary changes.

**Comment by SSwiniarski** [comment]
@borntofrappe, I assigned you this issue. Thanks for contributing 😃
