### ISSUE TITLE
[Edit] C++ Math Functions: `ceil()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#994]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting
Clarify unclear content and/or terms
Add new content (definitions, codeblocks, etc.)

### Description (optional)

Requesting edits for the [ceil()](https://www.codecademy.com/resources/docs/cpp/math-functions/ceil) term entry under the C++: Math Functions concept.

Under `cpp/concepts/math-functions/terms/ceil/ceil.md`, please make the following edits:

- Revise the opening sentence to refer to the term "ceil()" by name (and **bold** this term, as well)
- In the "Syntax" section:
  - Rename any and all parameters to something more informative and descriptive, if possible.
  - If there is no text underneath the \```pseudo snippet, please add 1-2 sentences that describe the parameters of the `ceil()` function as well as the return value.
- Remove any phrasing that is instructive in tone, as opposed to informational. For example, something like "Use the `ceil()` function to..." should be revised to something akin to "The following example uses the `ceil()` function to..."
- If there is no Codebyte example, please add a new "Codebyte Example" section with 1-2 sentences previewing a \```codebyte/cpp code snippet.

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by SSwiniarski** [comment]
@Yash-Var, I assigned you this issue.

**Comment by Yash-Var** [comment]
@Dusch4593 No, I will complete it very soon........

**Comment by SSwiniarski** [comment]
We have the entry now, but I can't find the PR
