### ISSUE TITLE
[Edit] C++ Math Functions: `floor()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#995]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting
Clarify unclear content and/or terms
Add new content (definitions, codeblocks, etc.)

### Description (optional)

Requesting edits for the [floor()](https://www.codecademy.com/resources/docs/cpp/math-functions/floor) term entry under the C++: Math Functions concept.

Under `c++/concepts/math-functions/terms/floor/floor.md`, please make the following edits:

- Revise the opening sentence to refer to the term "floor()" by name (and **bold** this term, as well)
- In the "Syntax" section:
  - Rename any and all parameters to something more informative and descriptive, if possible.
  - If there is no text underneath the \```pseudo snippet, please add 1-2 sentences that describe the parameters of the `floor()` function as well as the return value.
- Remove any phrasing that is instructive in tone, as opposed to informational. For example, something like "Use the `floor()` function to..." should be revised to something akin to "The following example uses the `floor()` function to..."
- If there is no Codebyte example, please add a new "Codebyte Example" section with 1-2 sentences previewing a \```codebyte/cpp code snippet.

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by Yash-Var** [comment]
@Dusch4593 @SSwiniarski i will work on this issue ...

**Comment by SSwiniarski** [comment]
@Yash-Var, I assigned you this issue.

**Comment by Dhanunjay18** [comment]
Hello @SSwiniarski , can u plz assign this issue to me

**Comment by SSwiniarski** [comment]
@Dhanunjay18, this issue has already been assigned to @Yash-Var. You're welcome to claim another issue that hasn't been assigned yet.

**Comment by Dhanunjay18** [comment]
Can u please assign another issue to me

**Comment by SSwiniarski** [comment]
@Dhanunjay18, If you want a similar issue that hasn't been assigned yet, you can claim [968](https://github.com/Codecademy/docs/issues/968).

**Comment by Dusch4593** [comment]
Hey @Yash-Var! Just wanted to check in to see how things were going for you on your `.sin()` term entry? Let us know if you have any questions! 😄

**Comment by Yash-Var** [comment]
@Dusch4593 NO, I will complete it very soon ....

**Comment by SSwiniarski** [comment]
We have the entry though I cannot find the PR.
