### ISSUE TITLE
[Edit] C++ Math Functions:  `abs()`

### ISSUE THREAD

**Issue by SSwiniarski** [Codecademy/docs#996]
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting
Clarify unclear content and/or terms
Add new content (definitions, codeblocks, etc.)

### Description (optional)

Requesting edits for the [abs()](https://www.codecademy.com/resources/docs/cpp/math-functions/abs) term entry under the C++: Math Functions concept.

Under `cpp/concepts/math-functions/terms/abs/abs.md`, please make the following edits:

- Revise the opening sentence to refer to the term "abs()" by name (and **bold** this term, as well)
- In the "Syntax" section:
  - Rename any and all parameters to something more informative and descriptive, if possible.
  - If there is no text underneath the \```pseudo snippet, please add 1-2 sentences that describe the parameters of the `abs()` function as well as the return value.
- Remove any phrasing that is instructive in tone, as opposed to informational. For example, something like "Use the `abs()` function to..." should be revised to something akin to "The following example uses the `abs()` function to..."
- If there is no Codebyte example, please add a new "Codebyte Example" section with 1-2 sentences previewing a \```codebyte/cpp code snippet.

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by binayuchai** [comment]
Hello, I would like to have some contribution to your repository. Please help me get started and assign me some tasks to do.

**Comment by Dusch4593** [comment]
Hey @binayuchai I assigned you to this issue so you can get started with the PR for it! Let us know if you have any questions with getting started. 😄

**Comment by SSwiniarski** [comment]
We have the entry for this now.
